## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا تَمِيمُ بْنُ الْمُنْتَصِرِ، أَخْبَرَنَا إِسْحَاقُ، - يَعْنِي ابْنَ يُوسُفَ - عَنْ شَرِيكٍ، عَنْ خُصَيْفٍ، بِإِسْنَادِهِ وَمَعْنَاهُ ‏.‏ قَالَ فَكَبَّرَ نَبِيُّ اللَّهِ صلى الله عليه وسلم وَكَبَّرَ الصَّفَّانِ جَمِيعًا ‏.‏ قَالَ أَبُو دَاوُدَ رَوَاهُ الثَّوْرِيُّ بِهَذَا الْمَعْنَى عَنْ خُصَيْفٍ وَصَلَّى عَبْدُ الرَّحْمَنِ بْنُ سَمُرَةَ هَكَذَا إِلاَّ أَنَّ الطَّائِفَةَ الَّتِي صَلَّى بِهِمْ رَكْعَةً ثُمَّ سَلَّمَ مَضَوْا إِلَى مَقَامِ أَصْحَابِهِمْ وَجَاءَ هَؤُلاَءِ فَصَلَّوْا لأَنْفُسِهِمْ رَكْعَةً ثُمَّ رَجَعُوا إِلَى مَقَامِ أُولَئِكَ فَصَلَّوْا لأَنْفُسِهِمْ رَكْعَةً ‏.‏ قَالَ أَبُو دَاوُدَ حَدَّثَنَا بِذَلِكَ مُسْلِمُ بْنُ إِبْرَاهِيمَ حَدَّثَنَا عَبْدُ الصَّمَدِ بْنُ حَبِيبٍ قَالَ أَخْبَرَنِي أَبِي أَنَّهُمْ غَزَوْا مَعَ عَبْدِ الرَّحْمَنِ بْنِ سَمُرَةَ كَابُلَ فَصَلَّى بِنَا صَلاَةَ الْخَوْفِ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1245</td></tr><tr><td>Arabic No</td><td>1245</td></tr><tr><td>Reference</td><td>Book 4 Hadith 48</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
তামিম ইবনুল মুনতাসির (রহঃ) .... খুসায়েফ (রহঃ) হতে এই সনদে উপরোক্ত হাদিসের অনুরূপ বর্ণিত হয়েছে। রাবী বলেন, অতঃপর নবী করীম সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম তাকবীর বললে উভয় দলই তাঁর সাথে তাকবীর বলে। ইমাম আবু দাউদ (রহ) বলেন, সাওরী অনুরূপ অর্থে খুসায়েফ হতে হাদিস বর্ণনা করেছেন এবং আব্দুর রহমান ইবন সামুরা (রাঃ) আবদুল্লাহ ইবন মাসউদ (রাঃ) কর্তৃক বর্ণিত হাদিসের নিয়মেই নামায আদায় করেন। তবে ব্যাতিক্রম এই যে, তিনি (নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম) দ্বিতীয় দলটির সাথে নামাযের দ্বিতীয় রাকাত আদায়ের পর সালাম ফিরালে মুক্তাদিগন শত্রুর মুকাবিলায় গমন করে এবং সেখানকার দলটি ফিরে এসে তাঁদের দ্বিতীয় রাকাত আদায় করে শত্রুর মুকাবিলায় গমন করে এবং পরবর্তী দলটি তাঁদের সুবিধা মত স্ব স্ব বাকী রাকাত আদায় করে। অন্য বর্ণনায় আছে যে, আব্দুস সামাদ ইবন হাবিব বলেন, আমার পিতা আমাকে জানান যে, তাঁরা আব্দুর রহমান ইবন সামুরা (রাঃ) এর সাথে কাবুল নামক স্থানে সালাতুল খাওফ আদায় করেন।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1245</td></tr><tr><td>Arabic No</td><td>1245</td></tr><tr><td>Reference</td><td>Book 4 Hadith 48</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
This tradition has been transmitted by Kushaif with a different chain of narrators and to the same effect. This version adds:The Prophet of Allah (ﷺ) uttered takbir and both rows uttered takbir together. Abu Dawud said: This tradition has been narrated by al-Thawri to the same effect on the authority of Khusaif. 'Abd al-Rahman b. Samurah also prayed in like manner. But the section which he (the Prophet) led in one rak'ah and then uttered the salutation and went and took the place of their companions. They came and prayed one rak'ah by themselves. Then they returned to their place and they prayed (one rak'ah) by themselves. Abu Dawud said: Muslim b. Ibrahim reported from 'Abd al-Samad b. Habib on the authority of his father that they had fought a battle at Kabul along with 'Abd al-Rahman b. Samurah. He led us in prayer in time of danger
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1245</td></tr><tr><td>Arabic No</td><td>1245</td></tr><tr><td>Reference</td><td>Book 4 Hadith 48</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Imran bin Maisarah] telah menceritakan kepada kami [Ibnu Fudlail] telah menceritakan kepada kami [Khushaif] dari [Abu 'Ubaidah] dari [Abdullah bin Mas'ud] dia berkata; "Rasulullah shallallahu 'alaihi wasallam pernah mengerjakan shalat khauf bersama kami, lalu sekelompok mereka berbaris di belakang Rasulullah shallallahu 'alaihi wasallam, sedangkan kelompok yang lain berjaga-jaga menghadapi musuh, maka Rasulullah shallallahu 'alaihi wasallam shalat dengan kelompok pertama satu raka'at, kemudian kelompok kedua datang dan menempati tempat kelompok pertama, sedangkan kelompok pertama bergantian berjaga menghadapi musuh, lalu Nabi shallallahu 'alaihi wasallam shalat dengan kelompok kedua satu raka'at, kemudian beliau salam, sementara kelompok yang shalat bersama beliau berdiri dan menyempurnakan satu raka'at sendiri-sendiri, kemudian mereka salam. Setelah itu mereka kembali dan menempati posisi kelompok yang menghadapi musuh, sedangkan kelompok pertama kembali (ke shaf shalat), kemudian mereka (menyempurnakan) shalat satu raka'at (yang tersisa) sendiri-sendiri, kemudian mereka salam." Telah menceritakan kepada kami [Tamim bin Al Muntashir] telah mengabarkan kepada kami [Ishaq yaitu Ibnu Yusuf] dari [Syarik] dari [Khushaif] dengan sanad dan maksud yang sama, katanya; "Kemudian Nabi shallallahu 'alaihi wasallam bertakbir, dan kedua kelompok juga ikut bertakbir bersama beliau." Abu Daud mengatakan; "Di riwayatkan pula oleh [Ats Tsauri] dengan makna seperti ini, dari [Khushaif], dan Abdurrahman bin Samurah juga mengerjakan cara shalat seperti ini, kecuali kelompok yang shalat satu raka'at, kemudian salam, lalu mereka bergantian menempati tempat sahabatnya yang lain (kelompok kedua), kemudian mereka (kelompok kedua) datang lalu shalat sendiri-sendiri satu raka'at, kemudian mereka kembali ke tempat mereka dan menyempurnakan shalat satu raka'at sendiri-sendiri." Abu Daud berkata; telah menceritakan kepada kami hadits seperti itu Muslim bin Ibrahim telah menceritakan kepada kami Abdusshamad bin Habib dia berkata; telah mengabarkan kepadaku ayahku bahwa mereka pernah berperang bersama Abdurrahman bin Samurah di daerah Kabul, kemudian dia mengerjakan shalat khauf bersama kami
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1245</td></tr><tr><td>Arabic No</td><td>1245</td></tr><tr><td>Reference</td><td>Book 4 Hadith 48</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
(Bir önceki hadisin 1244.) mânâsını aynı senedle İshâk b.Yûsuf (ve) Şerîk vasıtasıyla Husayf'tan Temîm b. Muntasır da rivayet etti. (Husayf) dedi ki: "Peygamber (s.a.v.) tekbir getirince her iki saf da birlikte tekbir getirdi." Ebû Dâvud dedi ki: Bir önceki hadisi (Şerîk'in rivayet ettiği) mânâ ile Husayf tan es-Sevrîde rivayet etmiştir. Abdurrahman b. Semure de (korku namazını) böyle kılmıştır. Ancak (Semure'nin kıldırdığı korku namazında imama ikinci rekata yetişen ve) imamla bir rekat na­maz kılan grub, (imam) selâm verince (daha önce birinci rekatı imam­la beraber kılıp düşman karşısında beklemekte olan) arkadaşlarının yerlerine gitmişler, (bu sefer) onlar gelip kendi başlarına bir rekat kı­larak (selâm vermişler) ve öbürlerinin yanına giderek (imamın arkası­na gelmelerini) ve kendi başlarına bir rekat (daha) kılmalarını sağlamışlardır. Ebû Dâvûd dedi ki: Şu (bir önceki) hadisi bize Müslim b. İbra­him de Abdussamed b. Habîb'den nakletti. Abdussamed; babam, Ab­durrahman b. Semure ile birlikte Kâbul'e savaşa gittiklerini söyledi ve "Abdurrahman bize korku namazı kıldırdı" dedi
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1245</td></tr><tr><td>Arabic No</td><td>1245</td></tr><tr><td>Reference</td><td>Book 4 Hadith 48</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
اس طریق سے بھی خصیف سے سابقہ سند سے اسی مفہوم کی روایت مروی ہے اس میں ہے کہ نبی اکرم صلی اللہ علیہ وسلم نے تکبیر ( تکبیر تحریمہ ) کہی اور دونوں صف کے سارے لوگوں نے بھی۔ ابوداؤد کہتے ہیں: ثوری نے بھی خصیف سے اسی مفہوم کی حدیث روایت کی ہے اور عبدالرحمٰن بن سمرہ نے اسی طرح یہ نماز ادا کی، البتہ اتنا فرق ضرور تھا کہ وہ گروہ جس کے ساتھ آپ نے ایک رکعت پڑھی اور سلام پھیر دیا، اپنے ساتھیوں کی جگہ واپس چلا گیا اور ان لوگوں نے آ کر خود سے ایک رکعت پوری کی۔ پھر وہ ان کی جگہ واپس چلے گئے اور اس گروہ نے آ کر اپنی باقی ماندہ رکعت خود سے ادا کی۔ ۱۲۴۵/م- ابوداؤد کہتے ہیں: ہم سے یہ حدیث مسلم بن ابراہیم نے بیان کی، مسلم کہتے ہیں: ہم سے عبدالصمد بن حبیب نے بیان کی، عبدالصمد کہتے ہیں: میرے والد نے مجھے بتایا کہ لوگوں نے عبدالرحمٰن بن سمرہ کے ساتھ کابل کا جہاد کیا تو انہوں نے ہمیں نماز خوف پڑھائی۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1245</td></tr><tr><td>Arabic No</td><td>1245</td></tr><tr><td>Reference</td><td>Book 4 Hadith 48</td></tr></tbody></table></div>