## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا الْحَسَنُ بْنُ عَلِيٍّ، حَدَّثَنَا أَبُو عَبْدِ الرَّحْمَنِ الْمُقْرِئُ، حَدَّثَنَا حَيْوَةُ، وَابْنُ، لَهِيعَةَ قَالاَ أَخْبَرَنَا أَبُو الأَسْوَدِ، أَنَّهُ سَمِعَ عُرْوَةَ بْنَ الزُّبَيْرِ، يُحَدِّثُ عَنْ مَرْوَانَ بْنِ الْحَكَمِ، أَنَّهُ سَأَلَ أَبَا هُرَيْرَةَ هَلْ صَلَّيْتَ مَعَ رَسُولِ اللَّهِ صلى الله عليه وسلم صَلاَةَ الْخَوْفِ قَالَ أَبُو هُرَيْرَةَ نَعَمْ ‏.‏ قَالَ مَرْوَانُ مَتَى فَقَالَ أَبُو هُرَيْرَةَ عَامَ غَزْوَةِ نَجْدٍ قَامَ رَسُولُ اللَّهِ صلى الله عليه وسلم إِلَى صَلاَةِ الْعَصْرِ فَقَامَتْ مَعَهُ طَائِفَةٌ وَطَائِفَةٌ أُخْرَى مُقَابِلَ الْعَدُوِّ ظُهُورُهُمْ إِلَى الْقِبْلَةِ فَكَبَّرَ رَسُولُ اللَّهِ صلى الله عليه وسلم فَكَبَّرُوا جَمِيعًا الَّذِينَ مَعَهُ وَالَّذِينَ مُقَابِلِي الْعَدُوِّ ثُمَّ رَكَعَ رَسُولُ اللَّهِ صلى الله عليه وسلم رَكْعَةً وَاحِدَةً وَرَكَعَتِ الطَّائِفَةُ الَّتِي مَعَهُ ثُمَّ سَجَدَ فَسَجَدَتِ الطَّائِفَةُ الَّتِي تَلِيهِ وَالآخَرُونَ قِيَامٌ مُقَابِلِي الْعَدُوِّ ثُمَّ قَامَ رَسُولُ اللَّهِ صلى الله عليه وسلم وَقَامَتِ الطَّائِفَةُ الَّتِي مَعَهُ فَذَهَبُوا إِلَى الْعَدُوِّ فَقَابَلُوهُمْ وَأَقْبَلَتِ الطَّائِفَةُ الَّتِي كَانَتْ مُقَابِلِي الْعَدُوِّ فَرَكَعُوا وَسَجَدُوا وَرَسُولُ اللَّهِ صلى الله عليه وسلم قَائِمٌ كَمَا هُوَ ثُمَّ قَامُوا فَرَكَعَ رَسُولُ اللَّهِ صلى الله عليه وسلم رَكْعَةً أُخْرَى وَرَكَعُوا مَعَهُ وَسَجَدَ وَسَجَدُوا مَعَهُ ثُمَّ أَقْبَلَتِ الطَّائِفَةُ الَّتِي كَانَتْ مُقَابِلِي الْعَدُوِّ فَرَكَعُوا وَسَجَدُوا وَرَسُولُ اللَّهِ صلى الله عليه وسلم قَاعِدٌ وَمَنْ مَعَهُ ثُمَّ كَانَ السَّلاَمُ فَسَلَّمَ رَسُولُ اللَّهِ صلى الله عليه وسلم وَسَلَّمُوا جَمِيعًا فَكَانَ لِرَسُولِ اللَّهِ صلى الله عليه وسلم رَكْعَتَانِ وَلِكُلِّ رَجُلٍ مِنَ الطَّائِفَتَيْنِ رَكْعَةٌ رَكْعَةٌ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1240</td></tr><tr><td>Arabic No</td><td>1240</td></tr><tr><td>Reference</td><td>Book 4 Hadith 43</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
আল হাসান ইবন আলী (রহঃ) ..... মারওান ইবনুল-হাকাম হতে বর্ণিত। তিনি আবু হুরায়রা (রাঃ) জিজ্ঞেস করেন, আপনি কি কখনও রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর সাথে ভয় ভীতির সময় নামায আদায় করেছেন? আবু হুরায়রা (রাঃ) বলেন, হ্যাঁ। মারওান পুনরায় জিজ্ঞেস করেন, কখন? তিনি বলেন, যাতুর-রিকার যুদ্ধের সময়। রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম আসরের নামায আদায়ের জন্য দাঁড়ালে একদল তাঁর সাথে নামাযে দাঁড়ায় এবং অপর দল কিবলার দিকে পিঠ ফিরিয়ে শত্রুর মুকাবিলায় নিয়োজিত থাকে। রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম আল্লাহু আকবার বললে যারা তাঁর সাথে ছিলেন এবং যারা শত্রুর মুকাবিলায় নিয়োজিত ছিলেন সকলে তাকবীর বলেন। তিনি তাঁর নিকটবর্তী লোকদের সঙ্গে নিয়ে প্রথম রাকাতের সিজদাহ করেন এবং অপর দল শত্রুর মুকাবিলায় নিয়োজিত থাকে। অতঃপর তিনি দ্বিতীয় রাকাতের জন্য দাঁড়ান এবং তাঁর সাথীগণ দুশমনের মুকাবিলায় যান এবং যারা ঐ দায়িত্বে নিয়োজিত ছিলেন তাঁরা এসে একাকী প্রথম রাকাতের রুকু ও সিজদা করে দ্বিতীয় রাকাতের জন্য তাঁর পশ্চাতে দণ্ডায়মান হন। তখন তিনি তাঁদের সাথে একত্রে দ্বিতীয় রাকাতের রুকু সিজদা করে বসে থাকেন। এই সময়ে যারা দুশমনের মুকাবিলায় নিয়োজিত ছিল তাঁরা ফিরে এসে নিজ নিজ রুকু সিজদা করে রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর পিছনে বসেন। অতঃপর তিনি সকলকে নিয়ে সালাম ফিরিয়ে নামায শেষ করেন। রাবী বলেন, এই সময় রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম তাঁর দুই রাকাত নামাযই জামায়াতের সাথে আদায় করেন, কিন্তু তাঁর সাহাবীদের (প্রতিটি দলের) নামায জামায়াতের সাথে এক রাকাত করে আদায় হয়েছে। (নাসাঈ)।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1240</td></tr><tr><td>Arabic No</td><td>1240</td></tr><tr><td>Reference</td><td>Book 4 Hadith 43</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Urwah ibn az-Zubayr reported that Marwan ibn al-Hakam asked AbuHurayrah:Did you pray in time of danger with the Messenger of Allah (ﷺ)? AbuHurayrah replied: Yes. Marwan then asked: When? AbuHurayrah said: On the occasion of the Battle of Najd. The Messenger of Allah (ﷺ) stood up to offer the afternoon prayer. One section stood with him (to pray) and the other was standing before the enemy, and their backs were towards the qiblah. The Messenger of Allah (ﷺ) uttered the takbir and all of them too uttered the takbir, i.e. those who were with him and those who were facing the enemy. Then the Messenger of Allah (ﷺ) offered one rak'ah and the section that was with him also prayed one rak'ah. He then prostrated himself and those who were with him also prostrated, while the other section was standing before the enemy. The Messenger of Allah (ﷺ) then stood up and the section with him also stood up. They went and faced the enemy and the section that was previously facing the enemy stepped forward. They bowed and prostrated while the Messenger of Allah (ﷺ) was standing in the same position. Then they stood up and the Messenger of Allah (may peace be upon) prayed another rak'ah and all of them bowed and prostrated along with him. After that the section that was standing before the enemy came forward and they bowed and prostrated, while the Messenger of Allah (ﷺ) remained seated and also those who were with him. The salutation then followed. The Messenger of Allah (ﷺ) uttered the salutation and all of them uttered it together. The Messenger of Allah (ﷺ) prayed two rak'ahs and each of the two sections prayed one rak'ah with him (and the other by themselves)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1240</td></tr><tr><td>Arabic No</td><td>1240</td></tr><tr><td>Reference</td><td>Book 4 Hadith 43</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Al Hasan bin Ali] telah menceritakan kepada kami [Abu Abdurrahman Al Muqri'i] telah menceritakan kepada kami [Haiwah] dan [Ibnu Lahi'ah] keduanya berkata; telah mengabarkan kepada kami [Abu Al Aswad] bahwa dia mendengar ['Urwah bin Az Zubair] bercerita dari [Marwan bin Hakam] bahwa dia bertanya kepada [Abu Hurairah]; "Apakah kamu pernah shalat khauf bersama Rasulullah shallallahu 'alaihi wasallam?" Abu Hurairah menjawab; "Ya, pernah." Marwan bertanya; "Kapan?" Abu Hurairah menjawab; "Ketika memerangi Bani Najd, Rasulullah shallallahu 'alaihi wasallam hendak mengerjakan shalat Ashar, lalu sekelompok orang berdiri (shalat) bersama beliau, sedangkan kelompok yang lain menghadap ke arah musuh membelakangi Kiblat. Rasulullah shallallahu 'alaihi wasallam bertakbir, lalu mereka juga ikut bertakbir, baik yang bersama beliau atau kelompok yang menghadap musuh. Setelah itu, Rasulullah shallallahu 'alaihi wasallam ruku' sekali bersama dengan kelompok yang menyertai beliau, lalu beliau sujud dan sujud pula orang yang menyertai beliau, sementara kelompok yang lain tetap berdiri menghadap ke arah musuh. Selanjutnya Rasulullah shallallahu 'alaihi wasallam berdiri, begitu juga kelompok yang menyertai beliau, kemudian kelompok ini pindah, menggantikan kelompok yang menghadapi musuh, sedangkan kelompok yang menghadapi musuh pindah ke belakang beliau untuk mengerjakan ruku' dan sujud sendiri-sendiri. Sedangkan Rasulullah shallallahu 'alaihi wasallam tetap berdiri menunggu sampai mereka berdiri pula. Setelah itu Rasulullah shallallahu 'alaihi wasallam ruku' (untuk raka'at kedua), lalu mereka ruku' bersama beliau, beliau sujud, mereka pun ikut sujud. Lalu kelompok yang menghadapi musuh datang, mereka ruku' dan sujud sendiri, sedangkan Rasulullah shallallahu 'alaihi wasallam tetap duduk menunggu bersama kelompok yang menyertai beliau tadi, setelah itu, baru tiba waktu salam. Maka Rasulullah shallallahu 'alaihi wasallam salam dan mereka semuanya pun salam. Maka bagi Rasulullah shallallahu 'alaihi wasallam dua rala'at, sedangkan bagi masing-masing mereka satu raka'at." Telah menceritakan kepada kami [Muhammad bin 'Amru Ar Razi] telah menceritakan kepada kami [Salamah] telah menceritakan kepadaku [Muhammad bin Ishaq] dari [Muhammad bin Ja'far bin Zubair] dan [Muhammad bin Al Aswad] dari ['Urwah bin Az Zubair] dari [Abu Hurairah] dua berkata; "Kami keluar bersama Rasulullah shallallahu 'alaihi wasallam menuju daerah Najd, hingga ketika kami sampai di perkebunan kurma Dzatur Riqa', beliau bertemu dengan sekelompok orang Bani Ghathafan…' kemudian dia menyebutkan makna dan lafadz hadits ini, tidak seperti lafadz hadits sebelumnya. Dalam hadits tersebut, dia berkata; "…Ketika beliau ruku' dam sujud bersama orang-orang yang berada di belakang beliau. selanjutnya Perawi berkata; "Setelah mereka berdiri, lalu berjalan mundur ke barisan sahabat mereka." dalam hadits ini tidak di sebutkan "membelakangi Kiblat
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1240</td></tr><tr><td>Arabic No</td><td>1240</td></tr><tr><td>Reference</td><td>Book 4 Hadith 43</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Mervân b. el-Hakem'den rivayet edildiğine göre kendisi Ebü Hureyre (r.a.)'e, "Resûlullah (s.a.v.) ile beraber korku namazı kıldın mı?" diye sormuş. O da "Evet" diye cevab vermiş. Mervân: "Ne zaman?" deyince; Ebû Hureyre de şu cevabı vermiş: Necid gazvesi yılında (kıldım). Resûlullah (s.a.v.) ikindi namazı için kalktı, (askerlerden) bir grup sırtları kıbleye karşı düşman karşısında dururlarken bir grub da kendisiyle beraber namaza durdu. Resûlullah (s.a.v.) tekbir alınca düşman karşısında olanlarla kendi yanında bulunanlar hep birlikte tekbir aldılar. Hz. Peygamber secde yaptı, onlar da yaptılar. Diğerleri ise düşman karşısında ayakta duruyorlardı, sonra Resûlullah (secdeden) kalkınca beraberindekiler de kalkıp gittiler ve düşmanın karşısında durdular. (Daha önce) düşman karşısında olan grub da Resûlullah'ın arkasına gelip durdular. Hz. Peygamber (s.a.v.) bir kere daha rükû'a ve secdeye vardı, onlar da O'nunla beraber rükû'a ve secdeye vardılar, Resûlullah ve beraberindekiler otururken düşman karşısında duranlar tekrar gelip rükû ve secdeye vardılar. Daha sonra da hep beraber selâm verdiler. Böylece (cemaatle kılınan namazın miktarı) Resûlullah (s.a.v.) için iki rekat her iki taifede bulunan kimseler içinse birer rekat oldu. Diğer tahric: Nesâî, havf
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1240</td></tr><tr><td>Arabic No</td><td>1240</td></tr><tr><td>Reference</td><td>Book 4 Hadith 43</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>

</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1240</td></tr><tr><td>Arabic No</td><td>1240</td></tr><tr><td>Reference</td><td>Book 4 Hadith 43</td></tr></tbody></table></div>