## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا مُسْلِمُ بْنُ إِبْرَاهِيمَ، حَدَّثَنَا عَبْدُ السَّلاَمِ بْنُ أَبِي حَازِمٍ أَبُو طَالُوتَ، قَالَ شَهِدْتُ أَبَا بَرْزَةَ دَخَلَ عَلَى عُبَيْدِ اللَّهِ بْنِ زِيَادٍ فَحَدَّثَنِي فُلاَنٌ، سَمَّاهُ مُسْلِمٌ وَكَانَ فِي السِّمَاطِ فَلَمَّا رَآهُ عُبَيْدُ اللَّهِ قَالَ ‏:‏ إِنَّ مُحَمَّدِيَّكُمْ هَذَا الدَّحْدَاحُ، فَفَهِمَهَا الشَّيْخُ فَقَالَ مَا كُنْتُ أَحْسِبُ أَنِّي أَبْقَى فِي قَوْمٍ يُعَيِّرُونِي بِصُحْبَةِ مُحَمَّدٍ صلى الله عليه وسلم فَقَالَ لَهُ عُبَيْدُ اللَّهِ إِنَّ صُحْبَةَ مُحَمَّدٍ صلى الله عليه وسلم لَكَ زَيْنٌ غَيْرُ شَيْنٍ ثُمَّ قَالَ ‏:‏ إِنَّمَا بُعِثْتُ إِلَيْكَ لأَسْأَلَكَ عَنِ الْحَوْضِ سَمِعْتَ رَسُولَ اللَّهِ صلى الله عليه وسلم يَذْكُرُ فِيهِ شَيْئًا فَقَالَ أَبُو بَرْزَةَ ‏:‏ نَعَمْ لاَ مَرَّةً وَلاَ ثِنْتَيْنِ وَلاَ ثَلاَثًا وَلاَ أَرْبَعًا وَلاَ خَمْسًا، فَمَنْ كَذَّبَ بِهِ فَلاَ سَقَاهُ اللَّهُ مِنْهُ ثُمَّ خَرَجَ مُغْضَبًا ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4749</td></tr><tr><td>Arabic No</td><td>4749</td></tr><tr><td>Reference</td><td>Book 42 Hadith 154</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
মুসলিম ইবন ইবরাহীম (রহঃ) .... আবদুস সালাম ইবন আবূ হাযিম (রহঃ) থেকে বর্ণিত। তিনি বলেনঃ আমি আবূ বারযা (রাঃ)-কে উবায়দুল্লাহ ইবন যিয়াদ (রহঃ) এর কাছে যেতে দেখি। এরপর আমার কাছে মুসলিম নামে এক ব্যক্তি, যিনি সেখানে উপস্থিত ছিলেন, বলেনঃ উবায়দুল্লাহ ইবন যিয়াদ (রহঃ) আবূ বারযা (রাঃ)-কে দেখে বলেনঃ দেখ! তোমাদের এ মুহাম্মদী (মুহাম্মদ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর সাহাবী) মোটা পা বিশিষ্ট। একথা শুনে আবূ বারযা (রাঃ) বুঝতে পারেন যে (ইবন যিয়াদ ঘৃণাভরে এরূপ উক্তি করছে।) তখন তিনি বলেনঃ আমি এরূপ খেয়াল করিনি যে, আমি এরূপ লোকদের সাথে অবস্থান করবো, যে আমাকে মুহাম্মদ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর সাহাবী হওয়ার জন্য দোষারূপ করবে। একথা শুনে উবায়দুল্লাহ ইবন যিয়াদ বলেনঃ মুহাম্মদ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর সোহবত তো আপনার জন্য গৌরবের বিষয়, এটা কোন দোষের ব্যাপার নয়। এরপর তিনি বলেনঃ আমি আপনাকে এ জন্য ডেকেছি যে, আমি আপনার কাছে হাওয-কাওছার সম্পর্কে জিজ্ঞাসা করবো। আপনি কি এ সম্পর্কে রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম থেকে কিছু শুনেছেন? আবূ বারযা (রাঃ) বলেনঃ হ্যাঁ, শুনেছি। এক, দুই, তিন, চার বা পাঁচবার নয়, বরং বহুবার শুনেছি। আর যে ব্যক্তি এ কথাকে মিথ্যা প্রতিপন্ন করবে, আল্লাহ্‌ তাকে সে হাওযের পানি পান করাবেন না। এরপর তিনি সেখানে থেকে বাগান্বিত হয়ে বেরিয়ে আসেন।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4749</td></tr><tr><td>Arabic No</td><td>4749</td></tr><tr><td>Reference</td><td>Book 42 Hadith 154</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
AbdusSalam ibn AbuHazim AbuTalut said:I saw AbuBarzah who came to visit Ubaydullah ibn Ziyad. Then a man named Muslim who was there in the company mentioned it to me. When Ubaydullah saw him, he said: This Muhammadan [i.e. Companion of Muhammad (ﷺ)] of yours is short and fat. The old man (i.e. AbuBarzah) understood it. So he said: I did not think I would remain amongst a people who would criticize me for having had the company of Muhammad (ﷺ). Thereupon Ubaydullah said to him: The company of Muhammad (ﷺ) is a honour for you, not a disgrace. He added: I called for you to ask about the Haud (reservoir or cistern). Did you hear the Messenger of Allah (ﷺ) say anything about it? AbuBarzah said: Yes, not once, twice, thrice, four times or five times. Whoever disbelieves in it, may Allah not supply him with water from it. He then went away angrily
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4749</td></tr><tr><td>Arabic No</td><td>4749</td></tr><tr><td>Reference</td><td>Book 42 Hadith 154</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Muslim bin Ibrahim] berkata, telah menceritakan kepada kami [Abdussalam bin Abu Hazim Abu Thalut] ia berkata; Aku melihat [Abu Barzah] masuk menemui Ubaidullah bin Ziyad, lalu ada seseorang dalam sebuah rombongan bernama Muslim bercerita kepadaku. Ketika Ubaidullah melihatnya, ia berkata, "Sesungguhnya salah satu dari kelompok Muhammad adalah orang yang gemuk dan pendek." Maka Abu Barzah pun mengerti apa yang dikatakan oleh Ubaidullah tersebut. Lantas Abu Barzah berkata, "Aku tidak menyangka bisa hidup bersama orang-orang yang mencelaku karena aku berkumpul dengan Muhammad shallallahu 'alaihi wasallam." Ubaidullah balik berkata, "Sesungguhnya persahabatanmu dengan Muhammad adalah perhiasan dan tidak ada celanya." Ia melanjutkan lagi kata-katanya, "Dan aku datang kepadamu untuk bertanya perihal telaga, aku pernah mendengar Muhammad shallallahu 'alaihi wasallam menyebut-nyebut tentang itu?" Abu Barzah menjawab, "Benar. Tidak hanya satu kali, dua kali, tiga kali, empat kali atau lima kali (beliau sebutkan itu). Maka siapa saja yang mendustainya Allah tidak akan memberinya minum darinya." Lalu ia keluar dengan marah
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4749</td></tr><tr><td>Arabic No</td><td>4749</td></tr><tr><td>Reference</td><td>Book 42 Hadith 154</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Abdüsselam İbn Ebi Hazim (yani) Ebu Talut dedi ki: Ben Ebu Berze'yi (Yezid İbn Muaviye'nin Kûfe'ye emir olarak tayin ettiği) Ubeydullah İbn Ziyad'in yanına girerken gördüm. (Fakat onunla birlikte Ubeydullah'ın yanına girmediğim için aralarından geçen konuşmayı dinleyemedim. Ancak bu konuşmayı) bana falanca (zat) nakletti... Musannif Ebu Davud der ki: Aslında bu hadisi bana nakleden şeyhim Müslim (ibn İbrahim) bu zat'ın ismini açıklamıştı (ama ben onu unuttum) ve (bu zat Ubeydullah ibn Ziyad'ın tabilerinden olan) cemaattendi (sözü geçen zat olayı şöyle anlattı): Ubeydullah, Ebu Berze'yi görünce (etrafındakilere) onu göstererek "Sizin Muhammed'e mensub olan sahabiniz işte şu kısa boylu ve şişman adamdır" dedi. Şeyh (Ebû Berze, dolayısıyla Hz. Nebi'in sahabilerine ve dolayısıyla Hz. Nebi'e hakaret etmek istediğini) derhal anladı ve: "Muhammed (s.a.v.) le olan sohbetimden dolayı beni ayıplayan bir toplumun yanında kalacağımı (böyleleri ile karşılaşacağımı) zannetmiyordum" dedi. Bunun üzerine Ubeydullah (sözü değiştirip): "Şüphesiz Muhammed (s.a.v.)'in sohbetinde bulunmak senin için bir zînettir (asla) ayıp değildir. Ben seni havuz hakkında (bildiklerini) sormak için (buraya) çağırmıştım. (Hakikaten) sen (hiç) Rasûlullah (s.a.v.)'i bu mevzuda bir şeyler söylerken işittin mi?" dedi. Ebu Berze (r.a.)'de; "Evet" (hem de pek çok defalar işittim, öyle) bir defa, iki defa, üç defa, dört defa, beş defa değil. Havuzu (n varlığını ve bu mevzudaki hadisleri) yalan sayan kimseyi Allah ondan içirmesin" dedi. Sonra Öfkeli olarak çıkıp gitti
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4749</td></tr><tr><td>Arabic No</td><td>4749</td></tr><tr><td>Reference</td><td>Book 42 Hadith 154</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
عبدالسلام بن ابی حازم ابوطالوت بیان کرتے ہیں کہ میں نے ابوبرزہ رضی اللہ عنہ کو دیکھا وہ عبیداللہ بن زیاد کے ہاں گئے، پھر مجھ سے فلاں شخص نے بیان کیا جو ان کی جماعت میں شریک تھا، ( مسلم نے اس کا نام ذکر کیا ہے ) جب انہیں عبیداللہ نے دیکھا تو بولا: دیکھو تمہارا یہ محمدی موٹا ٹھگنا ہے، تو شیخ ( ابوبرزہ ) اس کے اس طعنہ اور توہین کو سمجھ گئے اور بولے: مجھے یہ گمان نہ تھا کہ میں ایسے لوگوں میں باقی رہ جاؤں گا جو محمد صلی اللہ علیہ وسلم کی صحبت کا مجھے طعنہ دیں گے، تو عبیداللہ نے ان سے کہا: محمد صلی اللہ علیہ وسلم کی صحبت تو آپ کے لیے فخر کی بات ہے، نہ کہ عیب کی، پھر کہنے لگا: میں نے آپ کو اس لیے بلایا ہے کہ میں آپ سے حوض کوثر کے بارے میں معلوم کروں، کیا آپ نے رسول اللہ صلی اللہ علیہ وسلم سے اس کے متعلق کچھ ذکر فرماتے سنا ہے؟ تو ابوبرزہ رضی اللہ عنہ نے کہا: ہاں ایک بار نہیں، دو بار نہیں، تین بار نہیں، چار بار نہیں، پانچ بار نہیں ( یعنی بہت بار سنا ہے ) تو جو شخص اسے جھٹلائے اللہ اسے اس حوض میں سے نہ پلائے، پھر غصے میں وہ نکل کر چلے گئے۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4749</td></tr><tr><td>Arabic No</td><td>4749</td></tr><tr><td>Reference</td><td>Book 42 Hadith 154</td></tr></tbody></table></div>