## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا أَحْمَدُ بْنُ سِنَانٍ الْقَطَّانُ الْوَاسِطِيُّ، حَدَّثَنَا يَزِيدُ، عَنْ أَيُّوبَ أَبِي الْعَلاَءِ، عَنِ ابْنِ شُبْرُمَةَ، عَنِ امْرَأَةِ، مَسْرُوقٍ عَنْ عَائِشَةَ، عَنِ النَّبِيِّ صلى الله عليه وسلم مِثْلَهُ ‏.‏ قَالَ أَبُو دَاوُدَ وَحَدِيثُ عَدِيِّ بْنِ ثَابِتٍ وَالأَعْمَشِ عَنْ حَبِيبٍ وَأَيُّوبَ أَبِي الْعَلاَءِ كُلُّهَا ضَعِيفَةٌ لاَ تَصِحُّ وَدَلَّ عَلَى ضَعْفِ حَدِيثِ الأَعْمَشِ عَنْ حَبِيبٍ هَذَا الْحَدِيثُ أَوْقَفَهُ حَفْصُ بْنُ غِيَاثٍ عَنِ الأَعْمَشِ وَأَنْكَرَ حَفْصُ بْنُ غِيَاثٍ أَنْ يَكُونَ حَدِيثُ حَبِيبٍ مَرْفُوعًا وَأَوْقَفَهُ أَيْضًا أَسْبَاطٌ عَنِ الأَعْمَشِ مَوْقُوفٌ عَنْ عَائِشَةَ ‏.‏ قَالَ أَبُو دَاوُدَ وَرَوَاهُ ابْنُ دَاوُدَ عَنِ الأَعْمَشِ مَرْفُوعًا أَوَّلُهُ وَأَنْكَرَ أَنْ يَكُونَ فِيهِ الْوُضُوءُ عِنْدَ كُلِّ صَلاَةٍ وَدَلَّ عَلَى ضَعْفِ حَدِيثِ حَبِيبٍ هَذَا أَنَّ رِوَايَةَ الزُّهْرِيِّ عَنْ عُرْوَةَ عَنْ عَائِشَةَ قَالَتْ فَكَانَتْ تَغْتَسِلُ لِكُلِّ صَلاَةٍ ‏.‏ فِي حَدِيثِ الْمُسْتَحَاضَةِ وَرَوَى أَبُو الْيَقْظَانِ عَنْ عَدِيِّ بْنِ ثَابِتٍ عَنْ أَبِيهِ عَنْ عَلِيٍّ - رَضِيَ اللَّهُ عَنْهُ - وَعَمَّارٌ مَوْلَى بَنِي هَاشِمٍ عَنِ ابْنِ عَبَّاسٍ وَرَوَى عَبْدُ الْمَلِكِ بْنُ مَيْسَرَةَ وَبَيَانٌ وَالْمُغِيرَةُ وَفِرَاسٌ وَمُجَالِدٌ عَنِ الشَّعْبِيِّ عَنْ حَدِيثِ قَمِيرَ عَنْ عَائِشَةَ ‏"‏ تَوَضَّئِي لِكُلِّ صَلاَةٍ ‏"‏ ‏.‏ وَرِوَايَةُ دَاوُدَ وَعَاصِمٍ عَنِ الشَّعْبِيِّ عَنْ قَمِيرَ عَنْ عَائِشَةَ ‏"‏ تَغْتَسِلُ كُلَّ يَوْمٍ مَرَّةً ‏"‏ ‏.‏ وَرَوَى هِشَامُ بْنُ عُرْوَةَ عَنْ أَبِيهِ الْمُسْتَحَاضَةُ تَتَوَضَّأُ لِكُلِّ صَلاَةٍ ‏.‏ وَهَذِهِ الأَحَادِيثُ كُلُّهَا ضَعِيفَةٌ إِلاَّ حَدِيثَ قَمِيرَ وَحَدِيثَ عَمَّارٍ مَوْلَى بَنِي هَاشِمٍ وَحَدِيثَ هِشَامِ بْنِ عُرْوَةَ عَنْ أَبِيهِ وَالْمَعْرُوفُ عَنِ ابْنِ عَبَّاسٍ الْغُسْلُ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>300</td></tr><tr><td>Arabic No</td><td>300</td></tr><tr><td>Reference</td><td>Book 1 Hadith 300</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
আহমাদ ইবনু সিনান .... আয়িশা (রাঃ) নবী সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম হতে হাদীছের অনুরূপ বর্ণনা করেছেন। ইমাম আবূ দাউদ (রহঃ) বলেন, আদী ইবনু ছাবেত, আমাশ ও আইউবের হাদীছটি দুর্বল। আয়িশা (রাঃ) হতে অন্য একটি বর্ণনায় উল্লেখ আছে যে, ইস্তেহাযাগ্রস্ত মহিলাদের প্রত্যেক নামাযের পূর্বে গোসল করতে হবে। অপর এক বর্ণনায় আছে, প্রত্যেক নামাযের সময় উযূ (ওজু/অজু/অযু) করতে হবে। অপর এক বর্ণনায় আছে, ইস্তেহাযাগ্রস্থ মহিলাদের প্রত্যেহ একবার গোসল করতে হবে। হিশাম ইবনু উরওয়া (রহঃ) তাঁর পিতার সূত্রে ইস্তেহাযাগ্রস্ত মহিলাদের ব্যাপারে বর্ণনা করেছেন যে, তাদের প্রত্যেক নামাযের পূর্বে উযূ করতে হবে। ইমাম আবূ দাউদ (রহঃ) এর বর্ণনা মতে এই হাদীছের সনদ দুর্বল।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>300</td></tr><tr><td>Arabic No</td><td>300</td></tr><tr><td>Reference</td><td>Book 1 Hadith 300</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
This tradition has also been narrated by 'Aishah through a different chain of transmitters. Abu Dawud said:All the traditions (on this subject) transmitted by 'Adi b. Thabit and A'mash on the authority of Habib and Ayyub al-'Ala, all of them are weak; none of them is sound. This tradition indicates	the tradition reported by al-A'mash a a statement of Companion, i.e. 'Aishah. Hafs b. Ghayath has rejected the tradition transmitted by Habib as the statement (of the Prophet). And Asbat also reported it as a statement of 'Aishah. Abu Dawud said: Ibn Dawud has narrated the first part of this tradition as a statement (of the Prophet), and denied that there was any mention of performing ablution for every prayer. The weakness of the tradition reported by Habib is also indicated by the fact that the version transmuted by al-Zuhri from 'Urwah on the authority of 'Aishah says that she used to wash herself for every prayer; (these words occur) in the tradition about the woman who has a flow of blood. This tradition has been reported by Abu al-Yaqzan from 'Adi b. Thabit from his father from 'Ali, and narrated by 'Ammar, the freed salve of Banu Hashim, from Ibn 'Abbas, and transmitted by 'Abd al-Malik b. Maisarah, Bayan, al-Mughirah, Firas, on the authority of al-Sha'bi, from Qumair from 'Aishah, stating: You should perform ablution for every prayer. The version transmitted by Dawud, and 'Asim from al-Sha'bi from Qumair from 'Aishah has the words: She should take bath only once every day. The version reported by Hisham b. 'Urwah from his father has the words: The woman having a flow of blood should perform ablution for every prayer. All these traditions are weak except the tradition reported by Qumair and the tradition reported by 'Ammar, the freed slave of Banu Hashim, and the tradition narrated by Hisham b. 'Urwah on the authority of his father. What is commonly known from Ibn 'Abbas is bathing (for every prayer)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>300</td></tr><tr><td>Arabic No</td><td>300</td></tr><tr><td>Reference</td><td>Book 1 Hadith 300</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Ahmad bin Sinan Al-Qaththan Al-Wasithi] telah menceritakan kepada kami [Yazid] dari [Ayyub bin Abi Miskin] dari [Al-Hajjaj] dar [Ummu Kultsum] dari [Aisyah] tentang wanita yang menderita darah penyakit; Dia mandi, yakni sekali, kemudian cukup berwudhu sampai hari haidhnya datang. Telah menceritakan kepada kami [Ahmad bin Sinan Al-Qaththan Al-Wasithi] telah menceritakan kepada kami [Yazid] dari [Ayyub, Abu Al-'Ala'] dari [Ibnu Syubrumah] dari [Istri Masruq] dari [Aisyah] dari Nabi shallallahu 'alaihi wasallam, dengan lafazh semisal. Abu Dawud berkata; Dan hadits Adi bin Tsabit dan Al-A'masy dari Habib dan Ayyub, Abu Al-'Ala' semuanya dha'if, tidak shahih. Dan yang menunjukkan kedha'ifan hadits Al-A'masy dari Habib, hadits ini dimauqufkan oleh Hafsh bin Ghiyats dari Al-A'masy dan Hafsh bin Ghiyats mengingkari kemarfu'an hadits Habib. Dan dimauqufkan juga oleh Asbath dari Al-A'masy, mauquf dari Aisyah. Abu Dawud berkata; Dan diriwayatkan oleh Ibnu Dawud dari Al-A'masy secara marfu' awalnya, dan dia mengingkari padanya perihal wudhu pada setiap kali shalat. Dan yang menunjukkan kedha'ifan hadits Habib ini adalah bahwasanya riwayat Az-Zuhri dari Urwah dari Aisyah, dia berkata; Dia mandi untuk setiap kali shalat, di dalam hadits mustahadlah. Dan diriwayatkan oleh [Abu Al-Yaqzhan] dari [Adi bin Tsabit] dari [Ayahnya] dari [Ali radliallahu 'anhu], dan [Ammar, mantan budak Bani Hasyim] dari [Ibnu Abbas]. Dan diriwayatkan oleh [Abdul Malik bin Maisarah] dan [Bayan] dan [Al-Mughirah] dan [Firas] dan [Mujalid] dari [Asy-Sya'bi] dari hadits [Qamir] dari [Aisyah]; Berwudhulah untuk setiap kali shalat. Dan riwayat [Dawud] dan [Ashim] dari [Asy-Sya'bi] dari [Qamir] dari [Aisyah]; Dia mandi setiap hari satu kali. Dan diriwayatkan oleh Hisyam bin Urwah dari Ayahnya; Mustahadlah (wanita yang mengeluarkan darah penyakit) berwudhu untuk setiap kali shalat. Semua hadits ini dha'if, kecuali hadits Qamir dan hadits Ammar, mantan sahaya Bani Hasyim dan hadits Hisyam bin Urwah dari Ayahnya. Dan yang ma'ruf dari Ibnu Abbas adalah mandi
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>300</td></tr><tr><td>Arabic No</td><td>300</td></tr><tr><td>Reference</td><td>Book 1 Hadith 300</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Mesruk'un hanımı rivayet eti, Hz. Aişe validemizden, o da, Resulullah (Sallallahu aleyhi ve Sellem)'den aynen önceki hadisin benzerini rivayet etmiştir. Ebu Davud bu rivayetler hakkında şöyle demektedir: Adiy bin Sabit'in bu hadisi A'meş'in Habib'den rivayet ettiği hadis ve Eyyub Ebu'l-Ala'nın (Hz. Aişe'den mevkuf ve merfu olarak rivayet ettiği) hadislerin hepsi zayıftır, sahih değildir. A'meş'in Habib'den rivayet ettiği hadisin zayıflığına bu (evvelki) hadis delildir. Hafs bin Ğiyas bunu A'meş'den mevkuf olarak rivayet ederek Habib'in hadisinin merfu olduğunu redDetmiştir. Aynı şekilde Esbat, A'meş'ten; o da mevkuf olarak Hz. Aişe'den rivayet etmiştir. Ebu Davud devamla, İbn Davud bu hadisin baş tarafını merfu olarak rivayet etmiş ve onda, her namazda abdest alma (nın gerekli) olduğunu (bildiren ifadenin mevcudiyetini) red etmiştir. Zuhri'nin Urve'den; onun da Hz. Aişe'den rivayet ettiği müstehaza hadisinde "Her namaz için guslederdi" demesi Habib'in bu hadisinin Zaafına delildir. Ebu'l-Yekzan Adiy bin Sabit'ten; o da, babası tarikiyle Ali (r.a.), Beni Haşim'in azatlısı Ammar; İbn Abbas'tan, Abdülmelik bin Meysere, Beyan, Muğire, Firas, ve Mücahid de Şabi'den; o da Kamir vasıtasıyla Hz. Aişe'den "her namaz için abdest alır'' şeklinde rivayet etmişlerdir. Davud ve Asim'tn Şa'bi'den; onun da Kamir vasıtasıyla Aişe'den rivayeti "müstehaza her gün bir defa yıkatıp" şeklindedir. Hişam b. Urve de babasından "müstehaza her namaz için abdest ahr" diye rivayet etmiştir. Kamir ve Beni Haşim'in azatlısı Ammar ile Hişam bin Urve'nin babasından rivayet ettiği hadislerin dışındaki bütün bu hadisler zayıftır, ibn Abbas'tan bilinen (her namaz için abdest değil), ğusüldür
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>300</td></tr><tr><td>Arabic No</td><td>300</td></tr><tr><td>Reference</td><td>Book 1 Hadith 300</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
اس سند سے بھی ام المؤمنین عائشہ رضی اللہ عنہا نے نبی اکرم صلی اللہ علیہ وسلم سے اسی کے مثل روایت کی ہے۔ ابوداؤد کہتے ہیں عدی بن ثابت اور اعمش کی حدیث جو انہوں نے حبیب سے روایت کیا ہے، اور ایوب ابوالعلاء کی حدیث یہ سب کی سب ضعیف ہیں، صحیح نہیں ہیں، اور اعمش کی حدیث جسے انہوں نے حبیب سے روایت کیا ہے، اس کے ضعف پر یہی حدیث دلیل ہے، جسے حفص بن غیاث نے اعمش سے موقوفاً روایت کیا ہے، اور حفص بن غیاث نے حبیب کی حدیث کے مرفوعاً ہونے کا انکار کیا ہے، نیز اسے اسباط نے بھی اعمش سے، اور اعمش نے ام المؤمنین عائشہ رضی اللہ عنہا سے موقوفاً روایت کیا ہے ۱؎۔ ابوداؤد کہتے ہیں: اس کے ابتدائی حصہ کو ابن داود نے اعمش سے مرفوعاً روایت کیا ہے اور اس میں ہر نماز کے وقت وضو کے ہونے کا انکار کیا ہے۔ حبیب کی حدیث کے ضعف کی دلیل یہ بھی ہے کہ زہری کی روایت بواسطہ عروہ، عائشہ رضی اللہ عنہا سے مستحاضہ کے متعلق مروی ہے، اس میں یہ ہے کہ وہ ہر نماز کے لیے غسل کرتی تھیں۔ ابوالیقظان نے عدی بن ثابت سے، عدی نے اپنے والد ثابت سے، ثابت نے علی رضی اللہ عنہ سے، اور بنو ہاشم کے غلام عمار نے ابن عباس رضی اللہ عنہما سے روایت کی ہے، اور عبدالملک بن میسرہ، بیان، مغیرہ، فراس اور مجالد نے شعبی سے اور شعبی نے قمیر کی حدیث عائشہ رضی اللہ عنہا سے روایت کی ہے کہ: تم ہر نماز کے لیے وضو کرو ۔ اور داود اور عاصم کی روایت میں جسے انہوں نے شعبی سے، شعبی نے قمیر سے، اور قمیر نے عائشہ رضی اللہ عنہا سے روایت کیا ہے کہ وہ روزانہ ایک بار غسل کرے۔ ہشام بن عروہ نے اپنے والد سے روایت کی ہے کہ: مستحاضہ عورت ہر نماز کے لیے وضو کرے ۔ یہ ساری حدیثیں ضعیف ہیں سوائے تین حدیثوں کے: ایک قمیر کی حدیث ( جو عائشہ رضی اللہ عنہا سے مروی ہے ) ، دوسری عمار مولی بنی ہاشم کی حدیث ( جو ابن عباس رضی اللہ عنہما سے مروی ہے ) ، اور تیسری ہشام بن عروہ کی حدیث جو ان کے والد سے مروی ہے، ابن عباس سے مشہور ہر نماز کے لیے غسل ہے ۲؎۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>300</td></tr><tr><td>Arabic No</td><td>300</td></tr><tr><td>Reference</td><td>Book 1 Hadith 300</td></tr></tbody></table></div>