## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا عُبَيْدُ اللَّهِ بْنُ عُمَرَ بْنِ مَيْسَرَةَ، حَدَّثَنَا عَبْدُ الرَّحْمَنِ بْنُ مَهْدِيٍّ، عَنْ عَبْدِ اللَّهِ بْنِ الْمُبَارَكِ، عَنْ يُونُسَ بْنِ يَزِيدَ، عَنِ الزُّهْرِيِّ، أَخْبَرَنِي سَعِيدُ بْنُ الْمُسَيَّبِ، أَخْبَرَنِي جُبَيْرُ بْنُ مُطْعِمٍ، أَنَّهُ جَاءَ هُوَ وَعُثْمَانُ بْنُ عَفَّانَ يُكَلِّمَانِ رَسُولَ اللَّهِ صلى الله عليه وسلم فِيمَا قَسَمَ مِنَ الْخُمُسِ بَيْنَ بَنِي هَاشِمٍ وَبَنِي الْمُطَّلِبِ فَقُلْتُ يَا رَسُولَ اللَّهِ قَسَمْتَ لإِخْوَانِنَا بَنِي الْمُطَّلِبِ وَلَمْ تُعْطِنَا شَيْئًا وَقَرَابَتُنَا وَقَرَابَتُهُمْ مِنْكَ وَاحِدَةٌ ‏.‏ فَقَالَ النَّبِيُّ صلى الله عليه وسلم ‏ "‏ إِنَّمَا بَنُو هَاشِمٍ وَبَنُو الْمُطَّلِبِ شَىْءٌ وَاحِدٌ ‏"‏ ‏.‏ قَالَ جُبَيْرٌ وَلَمْ يَقْسِمْ لِبَنِي عَبْدِ شَمْسٍ وَلاَ لِبَنِي نَوْفَلٍ مِنْ ذَلِكَ الْخُمُسِ كَمَا قَسَمَ لِبَنِي هَاشِمٍ وَبَنِي الْمُطَّلِبِ ‏.‏ قَالَ وَكَانَ أَبُو بَكْرٍ يَقْسِمُ الْخُمُسَ نَحْوَ قَسْمِ رَسُولِ اللَّهِ صلى الله عليه وسلم غَيْرَ أَنَّهُ لَمْ يَكُنْ يُعْطِي قُرْبَى رَسُولِ اللَّهِ صلى الله عليه وسلم مَا كَانَ النَّبِيُّ صلى الله عليه وسلم يُعْطِيهِمْ ‏.‏ قَالَ وَكَانَ عُمَرُ بْنُ الْخَطَّابِ يُعْطِيهِمْ مِنْهُ وَعُثْمَانُ بَعْدَهُ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Bukhari</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2978</td></tr><tr><td>Arabic No</td><td>2978</td></tr><tr><td>Reference</td><td>Book 20 Hadith 51</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
উবায়দুল্লাহ ইবন আমর ইবন মায়সারা (রহঃ) ..... জুবায়র ইবন মুত'ইম (রাঃ) থেকে বর্ণিত। তিনি বলেনঃ একদা আমি এবং উছমান (রাঃ) রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর নিকট খুমুসের ব্যাপারে আলোচনার জন্য যাই, যা তিনি বনূ হাশিম ও বনূ মুত্তালিবের মাঝে বণ্টন করেন। এ সময় আমি জিজ্ঞেস করিঃ ইয়া রাসূলাল্লাহ! আপনি তো আমাদের ভাই বনূ মুত্তালিবকে অংশ দিলেন, কিন্তু আমাদের তো কিছু দিলেন না? অথচ আমাদের ও তাদের সস্পর্ক আপনার সঙ্গে একই ধরনের! তখন রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেনঃ বনূ হাশিম ও বনূ মুত্তালিব তো একই। রাবী জুবায়র (রাঃ) বলেনঃ তিনি বনূ আবদুশ শামস ও বনূ নওফলকে এ খুমুস হতে অংশ প্রদান করেননি, যেমন বনূ হাশিম ও বনূ মুত্তালিবকে অংশ প্রদান করেছিলেন। আর আবূ বকর (রাঃ)-ও রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর ন্যায় খুমুসের অংশ বন্টন করতেন। কিন্তু তিনি রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর আত্নীয়দের অংশ প্রদান করতেন না, যেমন রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম নিজে তাদের অংশ দিতেন। রাবী বলেনঃ উমার ইবন খাত্তাব (রাঃ) তাদের খুমুস থেকে অংশ দিতেন এবং তারপর উছমান (রাঃ)-ও এরূপ করতেন।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Bukhari</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2978</td></tr><tr><td>Arabic No</td><td>2978</td></tr><tr><td>Reference</td><td>Book 20 Hadith 51</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated Jubair b. Mut'im:That he and 'Uthman b. 'Affan went to the Messenger of Allah (ﷺ) talking to him about the fifth which he divided among the Banu Hisham and Abu 'Abd al-Muttalib. I said: Messenger of Allah, you have divided (the fifth) among our brethren Banu 'Abd al-Muttalib, but you have not given us anything, though our relationship to you is the same as theirs. The Prophet (ﷺ) said: The Banu Hisham and the Banu 'Abd al-Muttalib are one. Jubair said: He did not divide the fifth among the Banu 'Abd Shams and the Banu Nawfal as he divided among the Banu Hashim and the Banu 'Abd al-Muttalib. He said: Abu Bakr used to divide the fifth like the division of Messenger of Allah (ﷺ) except that he did not give the relatives of the Messenger of Allah (ﷺ), as he gave them. 'Umar b. al-Khattab and 'Uthman after him used to give them (a portion) from it
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Bukhari</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2978</td></tr><tr><td>Arabic No</td><td>2978</td></tr><tr><td>Reference</td><td>Book 20 Hadith 51</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami ['Ubaidullah bin Umar bin Maisarah], telah menceritakan kepada kami [Abdurrahman bin Mahdi] dari [Abdullah bin Al Mubarak] dari [Yunus bin Yazid?] dari [Az Zuhri], telah mengabarkan kepadaku [Sa'id bin Al Musayyab], telah mengabarkan kepadaku [Jubair bin Muth'im] bahwa ia bersama Utsman bin 'Affan datang untuk berbicara kepada Rasulullah shallallahu 'alaihi wasallam mengenai seperlima bagian yang beliau bagikan diantara Bani Hasyim dan Bani Al Muththalib. Kemudian aku katakan; wahai Rasulullah, anda telah membagi untuk saudara-saudara kami Bani Al Muththalib, dan anda tidak memberikan sesuatupun kepada kami, padahal kerabat kami dan kerabat mereka bagi anda adalah satu. Kemudian Nabi shallallahu 'alaihi wasallam bersabda: "Sesungguhnya Bani Hasyim dan Bani Abdul Muththalib adalah sesuatu yang satu." Jubair berkata; beliau tidak membagikan kepada Bani Abdusy Syams dan Bani Naufal dari seperlima tersebut sebagaimana beliau membagikan kepada Bani Hasyim dan Bani Al Muththalib. Ia berkata; dan Abu Bakr membagikan seperti pembagian Rasulullah shallallahu 'alaihi wasallam hanya saja ia tidak memberikan kepada kaum kerabat Rasulullah shallallahu 'alaihi wasallam, sebagaimana Rasulullah shallallahu 'alaihi wasallam memberikan kepada mereka. Ia berkata; dan Umar bin Al Khaththab memberikan kepada mereka dari bagian tersebut begitu juga Utsman setelahnya
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Bukhari</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2978</td></tr><tr><td>Arabic No</td><td>2978</td></tr><tr><td>Reference</td><td>Book 20 Hadith 51</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Cübeyr b. Mutim(in) haber verdi(ğine göre) Kendisi, Osman b. Affan (r.a) ile birlikte (Hz. Nebi'nin) humus'tan (ayırdığı bir payı) Haşim oğullarıyla, Muttalib oğulları arasında paylaştırdığını konuşarak Rasûlullah'ın huzuruna varmışlar. (Cubeyr b. Mutim sözlerine şöyle devam etmiştir) "Ben: Ey Allah'ın Rasûlü (sen humus'un bir kısmını) kardeşlerimiz Muttalib oğullarına dağıttın da bize (ondan) hiçbir şey vermedin. Oysa bizim sana olan yakınlığımızla onların yakınlığı aynıdır" dedim. Nebi (s.a.v.) de: "Haşim oğullarıyla, Muttalib oğulları aynı şey (gibi) dir" buyurdu. Cübeyr (rivayetine devam­la şöyle) dedi: (Hz. Nebi) bu humus'tan Haşim oğullarıyla Muttalib oğullarına verdiği gibi, Abdüşems ve Nevfel oğullarına vermedi. (Zührî) dedi ki: Ebû Bekir humus'u aynen Rasûlullah (s.a.v.) gibi bölüştürürdü, fakat Rasûlullah (s.a.v.)'in (kendi) yakınlarına vermiş olduğu hisseyi, onlara vermezdi. Ömer b. el-Hattab, humus'tan onlara hisse verirdi. Hz. Ömer'den sonra Osman da (onlara humustan pay verirdi)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Bukhari</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2978</td></tr><tr><td>Arabic No</td><td>2978</td></tr><tr><td>Reference</td><td>Book 20 Hadith 51</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
سعید بن مسیب کہتے ہیں کہ مجھے جبیر بن مطعم رضی اللہ عنہ نے خبر دی کہ وہ اور عثمان بن عفان دونوں اس خمس کی تقسیم کے سلسلے میں گفتگو کرنے کے لیے رسول اللہ صلی اللہ علیہ وسلم کے پاس آئے ۱؎ جو آپ نے بنو ہاشم اور بنو مطلب کے درمیان تقسیم فرمایا تھا، تو میں نے عرض کیا: اللہ کے رسول! آپ نے ہمارے بھائیوں بنو مطلب کو حصہ دلایا اور ہم کو کچھ نہ دلایا جب کہ ہمارا اور ان کا آپ سے تعلق و رشتہ یکساں ہے، اس پر رسول اللہ صلی اللہ علیہ وسلم نے فرمایا: بنو ہاشم اور بنو مطلب دونوں ایک ہی ہیں ۲؎ جبیر رضی اللہ عنہ کہتے ہیں: آپ صلی اللہ علیہ وسلم نے بنی عبد شمس اور بنی نوفل کو اس خمس میں سے کچھ نہیں دیا جیسے بنو ہاشم اور بنو مطلب کو دیا، ابوبکر رضی اللہ عنہ ۳؎ بھی اپنی خلافت میں خمس کو اسی طرح تقسیم کرتے تھے جیسے رسول اللہ صلی اللہ علیہ وسلم تقسیم فرماتے تھے مگر وہ رسول اللہ صلی اللہ علیہ وسلم کے عزیزوں کو نہ دیتے تھے جب کہ نبی اکرم صلی اللہ علیہ وسلم ان کو دیتے تھے، عمر بن خطاب رضی اللہ عنہ اس میں سے ان کو دیتے تھے اور ان کے بعد عثمان بن عفان رضی اللہ عنہ بھی ان کو دیتے تھے۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Bukhari</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2978</td></tr><tr><td>Arabic No</td><td>2978</td></tr><tr><td>Reference</td><td>Book 20 Hadith 51</td></tr></tbody></table></div>