## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا أَحْمَدُ بْنُ يُونُسَ، حَدَّثَنَا زَائِدَةُ بْنُ قُدَامَةَ الثَّقَفِيُّ، حَدَّثَنَا عُمَرُ بْنُ قَيْسٍ الْمَاصِرُ، عَنْ عَمْرِو بْنِ أَبِي قُرَّةَ، قَالَ كَانَ حُذَيْفَةُ بِالْمَدَائِنِ فَكَانَ يَذْكُرُ أَشْيَاءَ قَالَهَا رَسُولُ اللَّهِ صلى الله عليه وسلم لأُنَاسٍ مِنْ أَصْحَابِهِ فِي الْغَضَبِ فَيَنْطَلِقُ نَاسٌ مِمَّنْ سَمِعَ ذَلِكَ مِنْ حُذَيْفَةَ فَيَأْتُونَ سَلْمَانَ فَيَذْكُرُونَ لَهُ قَوْلَ حُذَيْفَةَ فَيَقُولُ سَلْمَانُ حُذَيْفَةُ أَعْلَمُ بِمَا يَقُولُ فَيَرْجِعُونَ إِلَى حُذَيْفَةَ فَيَقُولُونَ لَهُ قَدْ ذَكَرْنَا قَوْلَكَ لِسَلْمَانَ فَمَا صَدَّقَكَ وَلاَ كَذَّبَكَ ‏.‏ فَأَتَى حُذَيْفَةُ سَلْمَانَ وَهُوَ فِي مَبْقَلَةٍ فَقَالَ يَا سَلْمَانُ مَا يَمْنَعُكَ أَنْ تُصَدِّقَنِي بِمَا سَمِعْتُ مِنْ رَسُولِ اللَّهِ صلى الله عليه وسلم فَقَالَ سَلْمَانُ إِنَّ رَسُولَ اللَّهِ صلى الله عليه وسلم كَانَ يَغْضَبُ فَيَقُولُ فِي الْغَضَبِ لِنَاسٍ مِنْ أَصْحَابِهِ وَيَرْضَى فَيَقُولُ فِي الرِّضَا لِنَاسٍ مِنْ أَصْحَابِهِ أَمَا تَنْتَهِي حَتَّى تُوَرِّثَ رِجَالاً حُبَّ رِجَالٍ وَرِجَالاً بُغْضَ رِجَالٍ وَحَتَّى تُوقِعَ اخْتِلاَفًا وَفُرْقَةً وَلَقَدْ عَلِمْتَ أَنَّ رَسُولَ اللَّهِ صلى الله عليه وسلم خَطَبَ فَقَالَ ‏ "‏ أَيُّمَا رَجُلٍ مِنْ أُمَّتِي سَبَبْتُهُ سَبَّةً أَوْ لَعَنْتُهُ لَعْنَةً فِي غَضَبِي - فَإِنَّمَا أَنَا مِنْ وَلَدِ آدَمَ أَغْضَبُ كَمَا يَغْضَبُونَ وَإِنَّمَا بَعَثَنِي رَحْمَةً لِلْعَالَمِينَ - فَاجْعَلْهَا عَلَيْهِمْ صَلاَةً يَوْمَ الْقِيَامَةِ ‏"‏ ‏.‏ وَاللَّهِ لَتَنْتَهِيَنَّ أَوْ لأَكْتُبَنَّ إِلَى عُمَرَ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4659</td></tr><tr><td>Arabic No</td><td>4659</td></tr><tr><td>Reference</td><td>Book 42 Hadith 64</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
আহমদ ইবন ইউনুস (রহঃ) .... আমর ইবন আবূ কুর্‌রা (রাঃ) থেকে বর্ণিত। তিনি বলেনঃ হুযায়ফা (রাঃ) মাদায়েনে ছিলেন এবং তিনি লোকদের কাছে ঐ সব হাদীছ বর্ণনা করতেন, যা রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম রাগাম্বিত অবস্থায় লোকদের বলতেন। যারা হুযায়ফা (রাঃ) থেকে এ ধরনের হাদীছ শুনতেন, তারা সালমান (রাঃ)-এর কাছে গিয়ে তা বর্ণনা করতেন। তখন সালমান (রাঃ) বলতেনঃ হুযায়ফা (রাঃ) যা কিছু বলেনঃ সে ব্যাপারে তিনি অভিজ্ঞ। একথা লোকেরা হুযায়ফা (রাঃ)-এর কাছে গিয়ে বললো যে, আমরা আপনার বর্ণিত হাদীছ সালমান (রাঃ)-এর কাছে পেশ করলে, তিনি তা সম্পর্কে সত্য বা মিথ্যা কিছুই বলেন না। একথা শুনে হুযায়ফা (রাঃ) সালমান (রাঃ)-এর কাছে যান এবং এ সময় তিনি তরকারীর ক্ষেতে ছিলেন। তিনি তাকে বলেনঃ হে সালমান! আপনি আমার বর্ণিত ঐ সব হাদীছ কেন সত্যায়িত করেননি, যা আমি রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম থেকে শ্রবণ করেছি? তখন সালমান (রাঃ) বলেনঃ রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম কোন কোন সময় রাগাম্বিত হতেন, তখন তিনি রাগান্বিত অবস্থায় সাহাবীদের সাথে কথা বলতেন। আর কখনো তিনি সন্তুষ্ট থাকতেন, তখন তিনি তাদের সাথে খোশ-মেজাযে কথা বলতেন। এরপর সালমান (রাঃ) বলেনঃ আপনি কি এরূপ কাজ থেকে বিরত থাকবেন না, যাতে একে অন্যের প্রতি রাগ-বিরাগের সৃষ্টি হয়? আর সম্ভবতঃ এর ফলে লোকদের মাঝে মতানৈক্যের সৃষ্টি হতে পারে। তিনি আরো বলেনঃ আপনি এ বিষয়ে অবহিত আছেন যে, একদা রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম ভাষণ দেয়ার সময় বলেনঃ আমি রাগান্বিত থাকার কারণে যদি আমার উম্মাতকে কোন খারাপ কথা বলে থাকি বা তার উপর লা'নত করে থাকি, (তবে তা এজন্য যে,) আমিও আদম সন্তান। আমিও সেরূপ রাগান্বিত হই, যেরূপ অন্যরা হয়ে থাকে। অবশ্য মহান আল্লাহ্‌ আমাকে সারা জাহানের আমার খারাপ উক্তি ও লা'নতকে, (যা আমি করেছি,) কিয়ামতের দিন তা ঐ ব্যক্তির জন্য রহমত স্বরূপ করে দেবেন। এরপর সালমান (রাঃ) বলেনঃ আল্লাহ্‌র শপথ! হয় আপনি এরূপ করা থেকে বিরত থাকবেন, নয়তো আমি উমার (রাঃ)-কে চিঠি দিয়ে সব জানিয়ে দেব।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4659</td></tr><tr><td>Arabic No</td><td>4659</td></tr><tr><td>Reference</td><td>Book 42 Hadith 64</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
‘Amr b. Abl Qurrah said :Hudhaifah was in al-Mada’in. He used to mention things which the Messenger of Allah (May peace be upon him) said to some people from among his Companions in anger. The people who heard from Hudhaifah would go to Salman and tell him what Hudhaifah said. Salman would say: Hudhaifah knows best what he says. Then they would come to Hudhaifah and tell him: We mentioned Salman what you said, but he neither testified you nor falsified you. So Hudhaifah came to salman who was in his vegetable farm, and said : Salman, what prevents you from testifying me of what I heard from the Messenger of Allah (May peace be upon him) ? Salman said: The Messenger of Allah (May peace be upon him) sometimes would be angry, and said in anger something to some of his Companions; he would be sometimes pleased and said in pleasure something to some of his Companions. Would you not stop until you create love of some people in the hearts of some people, and hatred of some people in the hearts of some people, and until you generate disagreement and dissension? You know that the Messenger of Allah (May peace be upon him) addressed, saying : If I abused any person of my people, or cursed him in my anger. I am one of the children of Adam : I become angry as they become angry. He (Allah) has sent me as a mercy for all worlds. (O Allah!) make them (Abuse or curse) blessing for them on the day of judgment! I swear by Allah. You should stop (mentioning these traditions), otherwise I shall writ to ‘Umar
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4659</td></tr><tr><td>Arabic No</td><td>4659</td></tr><tr><td>Reference</td><td>Book 42 Hadith 64</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Ahmad bin Yunus] berkata, telah menceritakan kepada kami [Zaidah bin Qudamah Ats Tsaqafi] berkata, telah menceritakan kepada kami [Umar bin Qais Al Mashiri] dari [Amru bin Abu Qurrah] ia berkata, "Saat berada di Madain, [Hudzaifah] menyebutkan sesuatu yang dikatakan oleh Rasulullah shallallahu 'alaihi wasallam kepada para sahabatnya dengan marah. Orang-orang yang mendengar hal itu dari Hudzaifah langsung pergi dan mendatangi Salman. Mereka kemudian menceritakan apa yang dikatakan oleh Hudzaifah kepada Salman, namun Salaman justru berkata, "Hudzaifah lebih tahu dengan apa yang ia katakan." Orang-orang itu akhirnya kembali lagi menemui Hudzaifah dan berkata, "Ucapanmu tadi telah kami sampaikan kepada Salman, tetapi ia tidak membenarkan atau mendustakan kamu!" Hudzifah lantas pergi mendatangi Salman saat ia berada di Mabqalah, Hudzaifah berkata, "Wahai Salman, apa yang menghalangimu untuk membenarkan aku atas apa yang telah aku dengar dari Rasulullah shallallahu 'alaihi wasallam?" Salman menjawab, "Rasulullah shallallahu 'alaihi wasallam pernah marah dan berbicara dengan para sahabat dalam keadaam marah, tetapi beliau juga bisa ridha sehingga beliau berbicara dengan para sahabatnya dalam keadaan ridha. Tidakkah sebaiknya kamu tidak menceritakan apa yang telah kamu dengar hingga yang demikian itu dapat menjadikan sebagian cinta kepada sebagian dan benci kepada sebagian yang lain; agar tidak terjadi perpecahan. Engkau telah mendengar Rasulullah shallallahu 'alaihi wasallam berkhutbah: "Laki-laki manapun dari umatku yang pernah aku cela atau laknat saat dalam kondisi marah, sesungguhnya aku hanyalah anak turun Adam, hingga aku pun dapat marah sebagaimana mereka marah. Hanya saja aku diutus sebagai rahmat bagi seluruh alam, (Ya Allah) jadikanlah celaanku itu sebagai rahmat bagi mereka pada hari kiamat." Demi Allah, engkau segera berhenti dari melakukan hal yang demikian itu atau aku akan menulis surat kepada Umar
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4659</td></tr><tr><td>Arabic No</td><td>4659</td></tr><tr><td>Reference</td><td>Book 42 Hadith 64</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Amr b. Ebî Kurre'den (rivayet olunmuştur); dedi ki: Huzeyfe Medayin'de idi ve Rasûlullah (s.a.v.)'in öfke halinde sahabilerinden bazı kimseler için sarfetmiş olduğu sözleri (halka) aktardı. Bunları Huzeyfe'den dinleyenlerden bazıları da gider Selman'a haber verir ve Huzeyfe'den duyduklarını ona anlatırlardı. Selman da "Huzeyfe söylediği (sözün doğruluk derecesi) ni (benden) daha iyi bilir" derdi. Sonra da Huzeyfe'ye gelip: "Senin sözlerini Selman'a anlattık. Seni ne tasdik etti ne de tekzib etti." derlerdi. Huzeyfe (bir gün) sebze tarlasında bulunan Selman'a varıp; "Ey Selman benim Rasûlullah (s.a.v.)'den duyduklarımı tasdik etmekten seni engelleyen (sebep) nedir? dedi. Hz. Selman da (ona şöyle) cevap verdi: "Gerçekten Rasûlullah (s.a.v.) (bazan) öfkelenirdi ve öfkeli iken sahabilerinden bazıları hakkında (bazı ağır) sözler söylerdi. Bazan da hoşnut olur ve hoşnutluk halinde sahabilerinden bazıları hakkında (sitayişkâr) sözler söylerdi. Artık sen (Hz. Nebi'den her duyduğun sözü nakletmeye) bir son vermiyor musun? (Eğer sen bu rivayetlerine devam edersen) Bazı kimseler (in kalbin)e bazı kimselerin sevgisini, bazı kimseler (in kalbin) de bazılarının nefretini aşılarsın ve neticede bazı anlaşmazlıkların ve bölünmelerin meydana gelmesine sebep olursun. Oysa sen Rasûlullah (s.a.v.)'in bir hutbesinde: "Ben, öfkeli iken Ümmetimden herhangi bir kimseye sitem ya da beddua edersem (bu bir insanlık halidir); çünkü ben de Adem oğullarından biriyim. (Binaenaleyh) onların öfkelendiği gibi (bazan) ben de öfkelenirim (fakat, Allah) beni alemlere sadece rahmet için göndermiştir. (Bu sebeple ben rabbime: Ey Allah'ım, ben ancak bir beşerim, Müslümanlardan herhangi birisine, hak etmediği halde beddua yada sitem edersem) kıyamet gününde bunu onun için bir rahmet kıl (diye dua ettim. Rabbim de bu duamı kabul etti)" dediğini bilmektesin. Allah'a yemin olsun ki ya bu sözlerine son verirsin ya da (bunu) Ömer'e mektupla bildireceğim
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4659</td></tr><tr><td>Arabic No</td><td>4659</td></tr><tr><td>Reference</td><td>Book 42 Hadith 64</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
عمرو بن ابی قرہ کہتے ہیں کہ حذیفہ رضی اللہ عنہ مدائن میں تھے اور وہ ان باتوں کا ذکر کیا کرتے تھے، جو رسول اللہ صلی اللہ علیہ وسلم نے اپنے اصحاب میں سے بعض لوگوں سے غصہ کی حالت میں فرمائی تھیں، پھر ان میں سے کچھ لوگ جو حذیفہ سے باتیں سنتے چل کر سلمان رضی اللہ عنہ کے پاس آتے اور ان سے حذیفہ رضی اللہ عنہ کی باتوں کا تذکرہ کرتے تو سلمان رضی اللہ عنہ کہتے: حذیفہ ہی اپنی کہی باتوں کو بہتر جانتے ہیں، تو وہ لوگ حذیفہ کے پاس لوٹ کر آتے اور ان سے کہتے: ہم نے آپ کی باتوں کا تذکرہ سلمان سے کیا تو انہوں نے نہ آپ کی تصدیق کی اور نہ تکذیب، یہ سن کر حذیفہ سلمان کے پاس آئے، وہ اپنی ترکاری کے کھیت میں تھے کہنے لگے: اے سلمان! ان باتوں میں میری تصدیق کرنے سے آپ کو کون سی چیز روک رہی ہے جو میں نے رسول اللہ صلی اللہ علیہ وسلم سے سنی ہیں؟ تو سلمان نے کہا: رسول اللہ صلی اللہ علیہ وسلم بلاشبہ کبھی غصے میں اپنے بعض اصحاب سے کچھ باتیں کہہ دیتے اور کبھی خوش ہوتے تو خوشی میں اپنے بعض اصحاب سے کچھ باتیں کہہ دیتے، تو کیا آپ اس وقت تک باز نہ آئیں گے جب تک کہ بعض لوگوں کے دلوں میں بعض لوگوں کی محبت اور بعض دوسروں کے دلوں میں بعض کی دشمنی نہ ڈال دیں اور ان کو اختلاف میں مبتلا نہ کر دیں، حالانکہ آپ جانتے ہیں کہ رسول اللہ صلی اللہ علیہ وسلم نے اپنے ایک خطبہ میں فرمایا: میں نے اپنی امت کے کسی فرد کو غصے کی حالت میں اگر برا بھلا کہا یا اسے لعن طعن کی تو میں بھی تو آدم کی اولاد میں سے ہوں، مجھے بھی غصہ آتا ہے جیسے انہیں آتا ہے، لیکن اللہ نے مجھے رحمۃ للعالمین بنا کر بھیجا ہے تو ( اے اللہ ) میرے برا بھلا کہنے اور لعن طعن کو ان لوگوں کے لیے قیامت کے روز رحمت بنا دے اللہ کی قسم یا تو آپ اپنی اس حرکت سے باز آ جائیں ورنہ میں عمر بن الخطاب ( امیر المؤمنین ) کو لکھ بھیجوں گا۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4659</td></tr><tr><td>Arabic No</td><td>4659</td></tr><tr><td>Reference</td><td>Book 42 Hadith 64</td></tr></tbody></table></div>