## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا ابْنُ السَّرْحِ، أَخْبَرَنَا ابْنُ وَهْبٍ، أَخْبَرَنِي يُونُسُ، عَنِ ابْنِ شِهَابٍ، قَالَ أَخْبَرَنِي عَبْدُ الرَّحْمَنِ بْنُ عَبْدِ اللَّهِ بْنِ كَعْبِ بْنِ مَالِكٍ، أَنَّ عَبْدَ اللَّهِ بْنَ كَعْبٍ، قَالَ سَمِعْتُ كَعْبَ بْنَ مَالِكٍ، قَالَ كَانَ النَّبِيُّ صلى الله عليه وسلم إِذَا قَدِمَ مِنْ سَفَرٍ بَدَأَ بِالْمَسْجِدِ فَرَكَعَ فِيهِ رَكْعَتَيْنِ ثُمَّ جَلَسَ لِلنَّاسِ ‏.‏ وَقَصَّ ابْنُ السَّرْحِ الْحَدِيثَ قَالَ وَنَهَى رَسُولُ اللَّهِ صلى الله عليه وسلم الْمُسْلِمِينَ عَنْ كَلاَمِنَا أَيُّهَا الثَّلاَثَةُ حَتَّى إِذَا طَالَ عَلَىَّ تَسَوَّرْتُ جِدَارَ حَائِطِ أَبِي قَتَادَةَ وَهُوَ ابْنُ عَمِّي فَسَلَّمْتُ عَلَيْهِ فَوَاللَّهِ مَا رَدَّ عَلَىَّ السَّلاَمَ ثُمَّ صَلَّيْتُ الصُّبْحَ صَبَاحَ خَمْسِينَ لَيْلَةً عَلَى ظَهْرِ بَيْتٍ مِنْ بُيُوتِنَا فَسَمِعْتُ صَارِخًا يَا كَعْبُ بْنَ مَالِكٍ أَبْشِرْ ‏.‏ فَلَمَّا جَاءَنِي الَّذِي سَمِعْتُ صَوْتَهُ يُبَشِّرُنِي نَزَعْتُ لَهُ ثَوْبَىَّ فَكَسَوْتُهُمَا إِيَّاهُ فَانْطَلَقْتُ حَتَّى إِذَا دَخَلْتُ الْمَسْجِدَ فَإِذَا رَسُولُ اللَّهِ صلى الله عليه وسلم جَالِسٌ فَقَامَ إِلَىَّ طَلْحَةُ بْنُ عُبَيْدِ اللَّهِ يُهَرْوِلُ حَتَّى صَافَحَنِي وَهَنَّأَنِي ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Bukhari And Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2773</td></tr><tr><td>Arabic No</td><td>2773</td></tr><tr><td>Reference</td><td>Book 15 Hadith 297</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ইবন সারহা (রহঃ) .... কা‘ব ইবন মালিক (রাঃ) থেকে বর্ণিত। তিনি বলেনঃ নবী করীম সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম যখন কোন সফর হতে প্রত্যাবর্তন করতেন, তখন তিনি প্রথমে মসজিদে গিয়ে সেখানে দু‘রাকা‘আত সালাত আদায় করতেন। পরে তিনি লোকদের মাঝে উপবেশন করতেন। অবশেষে রাবী ইবনুস সারহা পূর্ণ হাদীছটি বর্ণনা করেন। রাবী [কা‘ব (রাঃ)] বলেনঃ রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম সকল মুসলিমকে আমাদের তিন ব্যক্তির সঙ্গে কথা বলতে নিষেধ করে দেন। (কেননা কা‘ব, হিলাল ইবন উমাইয়্যা এবং মারারা ইবন রাবী' এই তিনজন সাহাবী কোন কারণ ছাড়াই তাবুকের যুদ্ধে যাননি; অথচ রাসূলুল্লাহ্ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম সকল সক্ষম ব্যক্তিদের এ যুদ্ধে শরীক হওয়ার নির্দেশ দেন।)। এমতাবস্থায় যখন দীর্ঘদিন অতিবাহিত হলো, তখন আমি আবূ কাতাদা (রাঃ) এর বাগানে দেওয়াল টপকিয়ে তার ভেতরে গেলাম এবং তিনি ছিলেন আমার চাচাত ভাই। আমি তাকে সালাম করলাম। কিন্তু আল্লাহর শপথ! তিনি আমার সালামের জবাব দিলেন না। এভাবে পঞ্চাশ দিন অতিবাহিত হওয়ার পর একদিন সকালে আমি আমার ঘরের ছাদের উপর দাঁড়িয়ে সালাত আদায় করছিলাম। তখন আমি একজন আহবানকারীর এরূপ আওয়ায শুনতে পাই যে, ‘‘হে কা‘ব ইবন মালিক! তোমার জন্য সুসংবাদ। পরে যখন সে ব্যক্তি আমার নিকটবর্তী হয়, যার সুসংবাদদাতা আমি শুনেছিলাম, তখন আমি আমার গায়ের দু‘খানি কাপড় তাকে দিয়ে দিলাম এবং সে দু‘খানি তাকে পরিয়ে দিলাম। অতঃপর আমি মসজিদে হাযির হয়ে দেখতে পাই যে, রাসূলুল্লাহ্ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম সেখানে বসে আছেন। তখন আমাকে দেখে তালহা ইবন উবায়দুল্লাহ্ দৌড়ে আমার কাছে আসেন এবং আমার সাথে মুসফাহা করে আমাকে মুবারকবাদ জানান।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Bukhari And Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2773</td></tr><tr><td>Arabic No</td><td>2773</td></tr><tr><td>Reference</td><td>Book 15 Hadith 297</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ka’ab bin Malik said “When the Prophet(ﷺ) arrived from a journey, he first went to a mosque where he prayed two rak’ahs after which he sat in it and gave audience to the people. The narrator Ibn Al Sarh then narrated the rest of the tradition. He said “The Apostle of Allaah(ﷺ) forbade the Muslims to speak to any three of us. When considerable time had passed on me, I ascended the wall of Abu Qatadah who was my cousin. I saluted him, but, I swear by Allaah he did not return my salutation. I then offered the dawn prayer on the fiftieth day on the roof of one of our houses. I then hear d a crier say “Ka’ab bin Mailk, have good news”. When the man whose voice I heard came to me giving me good news, I took off my garments and clothed him. I went on till I entered the mosque. The Apostle of Allaah(ﷺ) was sitting there. Talhah bin ‘Ubaid Allaah stood up and hastened to me till he shook hands with me and greeted me
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Bukhari And Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2773</td></tr><tr><td>Arabic No</td><td>2773</td></tr><tr><td>Reference</td><td>Book 15 Hadith 297</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Ibnu As Sarh] telah mengabarkan kepada kami [Ibnu Wahb] telah mengabarkan kepadaku [Yunus] dari [Ibnu Syihab] ia berkata; telah mengabarkan kepadaku [Abdurrahman bin Abdullah bin Ka'b bin Malik], bahwa [Abdullah bin Ka'b] berkata; aku mendengar [Ka'b bin Malik] beliau berkata: Nabi shallallahu 'alaihi wasallam apabila datang dari safar beliau memulai dengan mendatangi masjid, kemudian melakukan shalat dua raka'at, dan duduk untuk memenuhi hajat orang-orang. Ibnu As Sarh berkata; dan Rasulullah shallallahu 'alaihi wasallam melarang orang-orang muslim untuk berbicara dengan kami bertiga. Hingga tatkala hal tersebut terasa lama bagiku, aku menaiki dinding kebun Abu Qatadah, ia adalah anak pamanku. Kemudian aku mengucapkan salam kepadanya. demi Allah, ia tidak membalas salamku. Kemudian aku melakukan Shalat Subuh pada hari kelima puluh, di atas rumah diantara rumah-rumah kami. Kemudian aku mendengar seseorang berteriak; wahai Ka'b bin Malik, bergembiralah. Kemudian tatkala orang yang aku dengan suaranya untuk memberikan kabar gembiera telah datang kepadaku, maka aku lepaskan pakaianku dan aku berikan kepadanya. kemudian aku pergi hingga tatkala aku memasuki masjid, ternyata Rasulullah shallallahu 'alaihi wasallam sedang duduk. Kemudian Thalhah berdiri untuk menyambutku dengan berlari-lari kecil, hingga ia menyalami dan mengucapkan selamat kepadaku
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Bukhari And Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2773</td></tr><tr><td>Arabic No</td><td>2773</td></tr><tr><td>Reference</td><td>Book 15 Hadith 297</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ka'b b. Malik demiştir ki: Nebi (S.A.V.) bir yolculuktan geldiği zaman, ilk önce mescid-de iki rek'at namaz kılar, sonra da halkla otururdu. (Musannif Ebu Davud'un şeyhi) İbnü's-Serh (Ka'b b. Malik'in bu hadisini sonuna kadar) nakletti. (Ka'b b. Malik konuşmasına devam ederek şöyle) dedi: Rasûlullah (S.A.V.) müslümanlara, bizim üçümüzle konuşmayı yasakladı. Nihayet, (onların bu küskünlüğü) bana (iyice) uzayınca (birgün). Amcamın oğlu olan Ebû Katade'nin bahçesinin duvarına tırmandım ve kendisine selam verdim. Daha sonra ellinci gecenin sabahında, sabah namazını evlerimizden bir evin damında kıldım ve hemen arkasından "Ey Malik'in oğlu Ka'b müjde sana!" diye bağıran birini işittim ve bana müjde vererek bağıran kimse yanıma gelince, (üzerimdeki) iki (kat) elbisemi çıkarıp ona giydirdim (ve) hemen arkasından (Rasûlü Ekrem'in huzuruna varmak üzere) harekete geçtim. Nihayet mescide girdim. Bir de ne göreyim, Rasûlullah (sallallahu aleyhi ve sellem (orada) oturuyor. Talha b. Ubeydillah kalktı, koşarak bana (geldi) benimle, müsafaha etti (elimi sıktı) ve beni tebrik etti
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Bukhari And Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2773</td></tr><tr><td>Arabic No</td><td>2773</td></tr><tr><td>Reference</td><td>Book 15 Hadith 297</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
کعب بن مالک رضی اللہ عنہ کہتے ہیں نبی اکرم صلی اللہ علیہ وسلم جب سفر سے آتے تو پہلے مسجد میں جاتے اور اس میں دو رکعت نماز پڑھتے، پھر لوگوں سے ملاقات کے لیے بیٹھتے ( اس کے بعد ابن السرح نے پوری حدیث بیان کی، اس میں ہے کہ ) رسول اللہ صلی اللہ علیہ وسلم نے مسلمانوں کو ہم تینوں ۱؎ سے بات کرنے سے منع فرما دیا، یہاں تک کہ مجھ پر جب ایک لمبا عرصہ گزر گیا تو میں اپنے چچا زاد بھائی ابوقتادہ رضی اللہ عنہ کے باغ میں دیوار پھاند کر گیا، میں نے ان کو سلام کیا، اللہ کی قسم انہوں نے جواب تک نہیں دیا، پھر میں نے اپنے گھر کی چھت پر پچاسویں دن کی نماز فجر پڑھی تو ایک پکارنے والے کی آواز سنی جو پکار رہا تھا: کعب بن مالک! خوش ہو جاؤ، پھر جب وہ شخص جس کی آواز میں نے سنی تھی میرے پاس آیا، تو میں نے اپنے دونوں کپڑے اتار کر اس کو پہنا دیئے، اور میں مسجد نبوی کی طرف چل پڑا، رسول اللہ صلی اللہ علیہ وسلم وہاں تشریف فرما تھے، مجھ کو دیکھ کر طلحہ بن عبیداللہ رضی اللہ عنہ اٹھ کھڑے ہوئے اور دوڑ کر مجھ سے مصافحہ کیا اور مجھے مبارکباد دی ۲؎۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Bukhari And Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2773</td></tr><tr><td>Arabic No</td><td>2773</td></tr><tr><td>Reference</td><td>Book 15 Hadith 297</td></tr></tbody></table></div>