## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا مُسَدَّدٌ، حَدَّثَنَا يَزِيدُ بْنُ زُرَيْعٍ، أَخْبَرَنَا دَاوُدُ بْنُ أَبِي هِنْدٍ، عَنِ الْوَلِيدِ بْنِ عَبْدِ الرَّحْمَنِ، عَنْ جُبَيْرِ بْنِ نُفَيْرٍ، عَنْ أَبِي ذَرٍّ، قَالَ صُمْنَا مَعَ رَسُولِ اللَّهِ صلى الله عليه وسلم رَمَضَانَ فَلَمْ يَقُمْ بِنَا شَيْئًا مِنَ الشَّهْرِ حَتَّى بَقِيَ سَبْعٌ فَقَامَ بِنَا حَتَّى ذَهَبَ ثُلُثُ اللَّيْلِ فَلَمَّا كَانَتِ السَّادِسَةُ لَمْ يَقُمْ بِنَا فَلَمَّا كَانَتِ الْخَامِسَةُ قَامَ بِنَا حَتَّى ذَهَبَ شَطْرُ اللَّيْلِ فَقُلْتُ يَا رَسُولَ اللَّهِ لَوْ نَفَّلْتَنَا قِيَامَ هَذِهِ اللَّيْلَةِ ‏.‏ قَالَ فَقَالَ ‏ "‏ إِنَّ الرَّجُلَ إِذَا صَلَّى مَعَ الإِمَامِ حَتَّى يَنْصَرِفَ حُسِبَ لَهُ قِيَامُ لَيْلَةٍ ‏"‏ ‏.‏ قَالَ فَلَمَّا كَانَتِ الرَّابِعَةُ لَمْ يَقُمْ فَلَمَّا كَانَتِ الثَّالِثَةُ جَمَعَ أَهْلَهُ وَنِسَاءَهُ وَالنَّاسَ فَقَامَ بِنَا حَتَّى خَشِينَا أَنْ يَفُوتَنَا الْفَلاَحُ ‏.‏ قَالَ قُلْتُ مَا الْفَلاَحُ قَالَ السُّحُورُ ثُمَّ لَمْ يَقُمْ بِنَا بَقِيَّةَ الشَّهْرِ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1375</td></tr><tr><td>Arabic No</td><td>1375</td></tr><tr><td>Reference</td><td>Book 6 Hadith 5</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
মুসাদ্দাদ (রহঃ) ..... আবু যার (রাঃ) হতে বর্ণিত। তিনি বলেনঃ আমরা রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লামের সাথে রমযান মাসে রোযাব্রত পালন করেছি। তিনি রমযান মাসের প্রথম দিকে (তারাবীহ নামায) আমাদের সাথে আদায় করেন নাই। অতঃপর উক্ত মাসের মাত্র সাতটি রাত অবশিষ্ট থাকতে তিনি আমাদের নিয়ে নামায (তারাবীহ) আদায় করেন; এভাবে রাতের এক-তৃতীয়াংশ অতিবাহিত হয়। অতঃপর তিনি ষষ্ঠ রাতে (অর্থাৎ পরের রাত) আমাদের সাথে (তারাবীহ) নামায আদায় করেন নাই। পরে পঞ্চম রাতে তিনি আমাদের সাথে নামায আদায় করাকালে রাতের অর্ধাংশ অতিবাহিত করেন। রাবী বলেনঃ ঐ সময় আমি তাঁকে বলিঃ ইয়া রাসূলাল্লাহ! অদ্য রজনীতে আপনি যদি আমাদের সাথে সারা রাত নামায আদায় করতেন, তবে কত উত্তম হত। তখন তিনি বলেনঃ কেউ জামাআতের সাথে (ইশার নামায) আদায় করে ঘরে প্রত্যাবর্তন করলে তাকে সারা রাতের জন্য নামাযী হিসাবে গণ্য করা হয়। রাবী বলেনঃ তিনি চতুর্থ রাতে (২৭শে রমযান) মসজিদে আসেন নাই (তারাবীর নামায আদায়ের জন্য)। অতঃপর তৃতীয় রাতে তিনি তাঁর স্ত্রী ও পরিবার-পরিজনদেরকে এবং অন্যান্য লোকদেরকে একত্রিত করে জামাআতের সাথে (তারাবীর) নামায আদায় করেন (এবং তার সময় এত দীর্ঘ হয় যে,) আমাদের আশংকা হচ্ছিল যে, হয়ত আমারা “ফালাহ্”-র সুযোগ হারিয়ে ফেলব। রাবী বলেন, আমি তখন জিজ্ঞাসা করিঃ ‘ফালাহ’ কি? তিনি বলেনঃ সেহরী খাওয়া। অতঃপর তিনি উক্ত মাসের বাকী দিনগুলিতে (২৯ ও ৩০) আমাদের সাথে জামাআতে আর তারাবীহ আদায় করেন নাই। (তিরমিযী, নাসাঈ, ইবন মাজা)।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1375</td></tr><tr><td>Arabic No</td><td>1375</td></tr><tr><td>Reference</td><td>Book 6 Hadith 5</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated AbuDharr: We fasted with the Messenger of Allah (ﷺ) during Ramadan, but he did not make us get up at night for prayer at any time during the month till seven nights remained; then he made us get up for prayer till a third of the night had passed. When the sixth remaining night came, he did not make us get up for prayer. When the fifth remaining night came, he made us stand in prayer till a half of the night had gone. So I said: Messenger of Allah, I wish you had led us in supererogatory prayers during the whole of tonight. He said: When a man prays with an imam till he goes he is reckoned as having spent a whole night in prayer. On the fourth remaining night he did not make us get up. When the third remaining night came, he gathered his family, his wives, and the people and prayed with us till we were afraid we should miss the falah (success). I said: What is falah? He said: The meal before daybreak. Then he did not make us get up for prayer during the remainder of the month
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1375</td></tr><tr><td>Arabic No</td><td>1375</td></tr><tr><td>Reference</td><td>Book 6 Hadith 5</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Musaddad] telah menceritakan kepada kami [Yazid bin Zurai'] telah mengabarkan kepada kami [Daud bin Abu Hind] dari [Al Walid bin Abdurrahman] dari [Jubair bin Nufair] dari [Abu Dzar] dia berkata; "Kami pernah berpuasa Ramadhan bersama Rasulullah shallallahu 'alaihi wasallam, dan beliau tidak pernah mengerjakan shalat malam bersama kami sedikitpun dalam sebulan sampai berlalu sepertiga malam, setelah malam ke enam (dari akhir bulan) beliau juga tidak mengerjakan shalat malam bersama kami, ketika di hari ke lima (dari akhir bulan), beliau mengerjakan shalat malam bersama kami hingga tengah malam pun berlalu. Maka kataku; "wahai Rasulullah, alangkah baiknya sekiranya anda memperbanyak shalat sunnah (qiyamullail) pada malam hari ini untuk kami!." Abu Dzar berkata; Maka beliau bersabda: "Sesungguhnya apabila seseorang shalat (malam) bersama imam hingga selesai, maka akan di catat baginya seperti bangun (untuk mengerjakan shalat malam) semalam suntuk." Kata Abu Dzar; "Ketika malam ke empat (dari akhir bulan) beliau tidak mengerjakan shalat malam (bersama kami), setelah malam ketiga (dari akhir bulan), beliu mengumpulkan keluarganya, isteri-isterinya dan orang-orang, lalu melakukan shalat malam bersama kami, sampai kami khawatir ketinggalah "Al falah." Jabir bertanya; "Apakah al falah itu?" jawabnya; "Waktu sahur, kemudian beliau tidak lagi melakukan shalat malam bersama kami di malam-malam berikutnya dari sebulan itu
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1375</td></tr><tr><td>Arabic No</td><td>1375</td></tr><tr><td>Reference</td><td>Book 6 Hadith 5</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ebû Zerr (r.a.)'den; demiştir ki: Ramazanda Resülullah (s.a.v.)'Ie birlikte oruç tuttuk. Ramazan ayından yedi gün kalıncaya kadar bize farzdan başka bir hiçbir şey kıldırmadı. Yedi gün kalınca bize gecenin üçte biri geçinceye kadar namaz kıldırdı. Altıncı (yani yirmi dördüncü gece) olunca (yine farzdan başka bir) namaz kıldırmadı. Beşinci (yani yirmi beşinci gece) olunca gecenin yarısı geçinceye kadar bize namaz kıldırdı. Bunun üzerine; Ey Allah'ın Resulü bu gecenin ihyâsı için bize daha fazla namaz kıldırsan? dedik. (Şöyle) buyurdu: "Bir kimse imam çekilinceye kadar onunla beraber namaz kılarsa, ona geceyi ihya etme sevabı verilir." Dördüncü (yani yirmi altıncı gece) olunca (bize) namaz kıl(dır)madi. Üçüncü (yani yirmi yedinci gece) olunca ehli (ailesi)ni, hanımlarım ve halkı topladı hepimize namaz kıldırdı. Öyle ki, felahın geçeceğinden korktuk. (Ravi Cübeyr) dedi ki: Felah nedir? dedim. (Ebû Zer) "sahur" diye cevab verdi. Ayın geri kalan kısmında bize (bir daha nafile) kıldırmadı
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1375</td></tr><tr><td>Arabic No</td><td>1375</td></tr><tr><td>Reference</td><td>Book 6 Hadith 5</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>

</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1375</td></tr><tr><td>Arabic No</td><td>1375</td></tr><tr><td>Reference</td><td>Book 6 Hadith 5</td></tr></tbody></table></div>