## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا إِبْرَاهِيمُ بْنُ مُوسَى الرَّازِيُّ، أَخْبَرَنَا عِيسَى بْنُ يُونُسَ، عَنْ ثَوْرٍ، عَنِ الْحُصَيْنِ الْحُبْرَانِيِّ، عَنْ أَبِي سَعِيدٍ، عَنْ أَبِي هُرَيْرَةَ، عَنِ النَّبِيِّ صلى الله عليه وسلم قَالَ ‏ "‏ مَنِ اكْتَحَلَ فَلْيُوتِرْ مَنْ فَعَلَ فَقَدْ أَحْسَنَ وَمَنْ لاَ فَلاَ حَرَجَ وَمَنِ اسْتَجْمَرَ فَلْيُوتِرْ مَنْ فَعَلَ فَقَدْ أَحْسَنَ وَمَنْ لاَ فَلاَ حَرَجَ وَمَنْ أَكَلَ فَمَا تَخَلَّلَ فَلْيَلْفِظْ وَمَا لاَكَ بِلِسَانِهِ فَلْيَبْتَلِعْ مَنْ فَعَلَ فَقَدْ أَحْسَنَ وَمَنْ لاَ فَلاَ حَرَجَ وَمَنْ أَتَى الْغَائِطَ فَلْيَسْتَتِرْ فَإِنْ لَمْ يَجِدْ إِلاَّ أَنْ يَجْمَعَ كَثِيبًا مِنْ رَمْلٍ فَلْيَسْتَدْبِرْهُ فَإِنَّ الشَّيْطَانَ يَلْعَبُ بِمَقَاعِدِ بَنِي آدَمَ مَنْ فَعَلَ فَقَدْ أَحْسَنَ وَمَنْ لاَ فَلاَ حَرَجَ ‏"‏ ‏.‏ قَالَ أَبُو دَاوُدَ رَوَاهُ أَبُو عَاصِمٍ عَنْ ثَوْرٍ قَالَ حُصَيْنٌ الْحِمْيَرِيُّ وَرَوَاهُ عَبْدُ الْمَلِكِ بْنُ الصَّبَّاحِ عَنْ ثَوْرٍ فَقَالَ أَبُو سَعِيدٍ الْخَيْرُ ‏.‏ قَالَ أَبُو دَاوُدَ أَبُو سَعِيدٍ الْخَيْرُ هُوَ مِنْ أَصْحَابِ النَّبِيِّ صلى الله عليه وسلم ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Daif</td><td>Shuaib Al Arnaut</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>35</td></tr><tr><td>Arabic No</td><td>35</td></tr><tr><td>Reference</td><td>Book 1 Hadith 35</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ইবরাহীম ইবনু মূসা .... আবূ হুরায়রা (রাঃ) নবী সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম হতে বর্ণনা করেছেন। তিনি বলেছেনঃ যে ব্যক্তি সুরমা ব্যবহার করে সে যেন বেজোড় সংখ্যায় ব্যবহার করে। যে ব্যক্তি এরূপ করে সে উত্তম কাজ করে এবং যে এরূপ করে না, এতে কোন ক্ষতি নেই! যে ব্যক্তি কুলুখ ব্যবহার করে সে যেন বেজোড় সংখ্যায় ব্যবহার করে। যে এরূপ করে, সে উত্তম কাজ করে এবং যে ব্যাক্তি এরূপ করে না, এতে কোন ক্ষতি নেই। খাদ্য গ্রহণের পর যে ব্যাক্তি খিলাল দ্বারা দাঁত হতে খাদ্যের ভুক্ত অংশ বের করে; সে যেন তা ফেলে দেয় এবং জিহবার স্পর্শে যা বের হয়, তা যেন খেয়ে ফেলে। যে ব্যক্তি এরূপ করে সে উত্তম কাজ করে এবং যে এরূপ করে না তাতে কোন ক্ষতি নেই। যে ব্যক্তি পায়খানায় গমন করে, সে যেন পর্দা করে। যদি পর্দা করার মত কোন বস্তু সে না পায়, তবে সে যেন অন্ততঃ বালুর স্তুপ করে তার দিকে পিঠ ফিরিয়ে বসে। কেননা শয়তান বনী আদমের গুপ্তাঙ্গ (পর্দার স্থান অর্থাৎ পেশাব- পায়খানার স্থান) নিয়ে খেলা করে। যে ব্যক্তি এরূপ করে সে উত্তম কাজ করে এবং যে এরূপ করেনা তাতে কোন দোষ নেই - (ইবনু মাজাহ)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Daif</td><td>Shuaib Al Arnaut</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>35</td></tr><tr><td>Arabic No</td><td>35</td></tr><tr><td>Reference</td><td>Book 1 Hadith 35</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated AbuHurayrah: The Prophet (ﷺ) said: If anyone applies collyrium, he should do it an odd number of times. If he does so, he has done well; but if not, there is no harm. If anyone cleanses himself with pebbles, he should use an odd number. If he does so, he has done well; but if not, there is no harm. If anyone eats, he should throw away what he removes with a toothpick and swallow what sticks to his tongue. If he does so, he has done well; if not, there is no harm. If anyone goes to relieve himself, he should conceal himself, and if all he can do is to collect a heap of send, he should sit with his back to it, for the devil makes sport with the posteriors of the children of Adam. If he does so, he has done well; but if not, there is no harm
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Daif</td><td>Shuaib Al Arnaut</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>35</td></tr><tr><td>Arabic No</td><td>35</td></tr><tr><td>Reference</td><td>Book 1 Hadith 35</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Ibrahim bin Musa Ar Razi] telah mengabarkan kepada kami [Isa bin Yunus] dari [Tsaur] dari [Al Hushain Al Hubrani] dari [Abu Sa'id] dari [Abu Hurairah] dari Nabi shallallahu 'alaihi wasallam, beliau bersabda: "Barang siapa bercelak hendaklah dia melakukannya dengan ganjil, barangsiapa yang melakukannya maka dia telah berbuat baik, dan barangsiapa yang tidak melakukannya maka tidak ada dosa baginya. Barangsiapa yang beristinja dengan batu hendaklah dia melakukannya dengan ganjil, barangsiapa yang melakukannya maka dia telah berbuat baik dan barangsiapa yang tidak melakukannya maka tidak ada dosa baginya. Barangsiapa yang makan, maka apa yang menyangkut hendaklah dia membuangnya, dan yang dapat di lepas oleh lidah hendaknya dia menelannya, Barangsiapa yang melakukannya maka dia telah berbuat baik dan barangsiapa yang tidak melakukannya maka tidak ada dosa baginya. Barangsiapa mendatangi tempat buang air maka hendaklah dia mengambil satir (penutup), dan jika tidak menemukan kecuali dengan mengumpulkan setumpuk pasir, maka hendaklah dia membelakanginya, karena sesungguhnya seta bermain-main dengan tempat duduk anak Adam. Barangsiapa yang melakukannya maka dia telah berbuat baik dan barangsiapa yang tidak melakukannya maka tidak ada dosa baginya." Abu Dawud berkata; Diriwayatkan oleh [Abu 'Ashim] dari [Tsaur]. Hushain Al Himyari berkata; dan diriwayatkan oleh [Abdul Malik bin Ash Shabbah] dari [Tsaur], dia berkata; [Abu Sa'id Al Khair]. Abu Dawud berkata; Abu Sa'id Al Khair termasuk di antara sahabat Nabi shallallahu 'alaihi wasallam
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Daif</td><td>Shuaib Al Arnaut</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>35</td></tr><tr><td>Arabic No</td><td>35</td></tr><tr><td>Reference</td><td>Book 1 Hadith 35</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ebu Hureyre (r.a.)'in Nebi Sallallahu Aleyhi ve Sellem'den rivayet ettiğine göre şöyle buyurmuştur: "Gözlerine sürme çeken kimse tek sayıda çeksin. Böyle yapan iyi yapmış olur. Yapmayana da günah yoktur. Taşla taharetlenen de tek sayıya riayet etsin. Böyle yapan iyi yapmakla beraber yapmayana günah yoktur. Yemek yiyen dişlerinin dibinden ayıkladığı kırıntıları dışarı atsın. Ağzındakini de dili ile toplarsa yutsun. Böyle yaparsa iyidir. Yapmazsa zorluk yoktur. Abdest bozmak isteyen gizlensin. Gizlenecek yer bulamayan kimse kum biriktirerek onu arkasına alsın. Çünkü şeytan insan oğullarının oturaklarıyla oynar. Kim böyle yaparsa iyi yapar, yapmazsa, zorluk yoktur." Ebu Davud der ki; Bu hadisi bu şekilde Ebu Asim Sevr'den rivayet etmiş ve ancak seneddeki el-Husayn el-Hubrani yerine Husayn EI-Himyeri demiştir. Yine Ebu Davud dedi ki: Bu hadis-i şerifi bir de Abdulmelik b. El-Sabbah, Sevr'den rivayet etmiştir. O da Ebu Said yerinde, Ebu Said el-Hayr demiştir. Ebu Davud dedi ki; Ebu Said el-Hayr ashab-i Kiramdandır. Diğer tahric: İbn Mace, tahare; Darimî, vudu; Ahmed b. Hanbel
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Daif</td><td>Shuaib Al Arnaut</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>35</td></tr><tr><td>Arabic No</td><td>35</td></tr><tr><td>Reference</td><td>Book 1 Hadith 35</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ابوہریرہ رضی اللہ عنہ سے روایت ہے کہ نبی اکرم صلی اللہ علیہ وسلم نے فرمایا: جو شخص سرمہ لگائے تو طاق لگائے، جس نے ایسا کیا اس نے اچھا کیا، اور جس نے ایسا نہیں کیا تو اس میں کوئی مضائقہ اور حرج نہیں، جو شخص ( استنجاء کے لیے ) پتھر یا ڈھیلا لے تو طاق لے، جس نے ایسا کیا اس نے اچھا کیا، اور جس نے ایسا نہیں کیا تو کوئی حرج نہیں، اور جو شخص کھانا کھائے تو خلال کرنے سے جو کچھ نکلے اسے پھینک دے، اور جسے زبان سے نکالے اسے نگل جائے، جس نے ایسا کیا اس نے اچھا کیا، اور جس نے ایسا نہیں کیا تو کوئی حرج نہیں، جو شخص قضائے حاجت ( پیشاب و پاخانہ ) کے لیے جائے تو پردہ کرے، اگر پردہ کے لیے کوئی چیز نہ پائے تو بالو یا ریت کا ایک ڈھیر لگا کر اس کی طرف پیٹھ کر کے بیٹھ جائے کیونکہ شیطان آدمی کی شرمگاہ سے کھیلتا ہے ۱؎، جس نے ایسا کیا اس نے اچھا کیا، اور جس نے نہیں کیا تو کوئی مضائقہ نہیں ۔ ابوداؤد کہتے ہیں: اسے ابوعاصم نے ثور سے روایت کی ہے، اس میں ( حصین حبرانی کی جگہ ) حصین حمیری ہے، اور عبدالملک بن صباح نے بھی اسے ثور سے روایت کیا ہے، اس میں ( ابوسعید کی جگہ ) ابوسعید الخیر ہے۔ ابوداؤد کہتے ہیں: ابوسعید الخیر نبی اکرم صلی اللہ علیہ وسلم کے اصحاب میں سے ہیں۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Daif</td><td>Shuaib Al Arnaut</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>35</td></tr><tr><td>Arabic No</td><td>35</td></tr><tr><td>Reference</td><td>Book 1 Hadith 35</td></tr></tbody></table></div>