## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا عَمْرُو بْنُ عَوْنٍ، حَدَّثَنَا خَالِدٌ، عَنْ حُمَيْدٍ، عَنْ بَكْرِ بْنِ عَبْدِ اللَّهِ، قَالَ قَالَ رَجُلٌ لاِبْنِ عَبَّاسٍ مَا بَالُ أَهْلِ هَذَا الْبَيْتِ يَسْقُونَ النَّبِيذَ وَبَنُو عَمِّهِمْ يَسْقُونَ اللَّبَنَ وَالْعَسَلَ وَالسَّوِيقَ أَبُخْلٌ بِهِمْ أَمْ حَاجَةٌ فَقَالَ ابْنُ عَبَّاسٍ مَا بِنَا مِنْ بُخْلٍ وَلاَ بِنَا مِنْ حَاجَةٍ وَلَكِنْ دَخَلَ رَسُولُ اللَّهِ صلى الله عليه وسلم عَلَى رَاحِلَتِهِ وَخَلْفَهُ أُسَامَةُ بْنُ زَيْدٍ فَدَعَا رَسُولُ اللَّهِ صلى الله عليه وسلم بِشَرَابٍ فَأُتِيَ بِنَبِيذٍ فَشَرِبَ مِنْهُ وَدَفَعَ فَضْلَهُ إِلَى أُسَامَةَ بْنِ زَيْدٍ فَشَرِبَ مِنْهُ ثُمَّ قَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏ "‏ أَحْسَنْتُمْ وَأَجْمَلْتُمْ كَذَلِكَ فَافْعَلُوا ‏"‏ ‏.‏ فَنَحْنُ هَكَذَا لاَ نُرِيدُ أَنْ نُغَيِّرَ مَا قَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2021</td></tr><tr><td>Arabic No</td><td>2021</td></tr><tr><td>Reference</td><td>Book 11 Hadith 301</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
আমর ইবন আওন (রহঃ) ...... বাকর ইবন আবদুল্লাহ্ (রহঃ) হতে বর্ণিত। তিনি বলেন, একদা জনৈক ব্যক্তি ইবন আব্বাস (রাঃ)-কে বলেন, এ গৃহের অধিবাসীদের (আব্বাসের) অবস্থান কী? এরা নবীয পান করে এবং এদের চাচার সন্তানসন্ততিরা দুধ, মধু ও পানীয় পান করে। এটা কি তাদের কৃপণতা, না অস্বচ্ছলতা? তদুত্তরে ইবন আব্বাস (রাঃ) বলেন, আমাদের সাথে না কৃপণতা আছে, না অসচ্ছলতা বরং (প্রকৃত ব্যাপার এই যে,) একদা রাসূলুল্লাহ্ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম একটি বাহনে আমাদের নিকট আগমন করেন, যা পশ্চাতে উসামা ইবন যায়িদ (রাঃ) সাওয়ার ছিলেন। তখন রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম পানীয় কিছু চাইলে তাঁর সম্মুখে নবীয পেশ করা হয়। তা হতে তিনি কিছু পানের পর অবশিষ্টাংশ উসামাকে প্রদান করেন। অতঃপর তিনি (উসামা) তা পান করেন। পরে রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেন, তোমরা অত্যন্ত উত্তম ও উৎকৃষ্ট কাজ করেছ। আর তোমরা এইরূপ করতে থাকবে। কাজেই আমরা এইরূপ করি এবং রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম যা করেছেন তার ব্যতিক্রম করতে চাই না।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2021</td></tr><tr><td>Arabic No</td><td>2021</td></tr><tr><td>Reference</td><td>Book 11 Hadith 301</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Bakr bin ‘Abd Allah said “A man said to Ibn ‘Abbas “What about the people of this House? They supply Nabidh to the public while their cousins provide milk, honey and mush (sawiq). Is this due to their niggardliness or need? Ibn ‘Abbas replied “This is due neither to our niggardliness nor to our need, but the Apostle of Allaah(ﷺ) (once) entered upon us on his riding beast and ‘Usamah bin Zaid was sitting behind him. The Apostle of Allaah(ﷺ) called for drink. Nabidh was brought to him and he drank from it and gave its left over to Usamah bin Zaid who drank from it. The Apostle of Allaah (ﷺ) then said “You have done a good and handsome deed and do it in a similar way . It is due to this we are doing so, we do not want to change what the Apostle of Allaah (ﷺ)had said
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2021</td></tr><tr><td>Arabic No</td><td>2021</td></tr><tr><td>Reference</td><td>Book 11 Hadith 301</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami ['Amr bin 'Aun], telah menceritakan kepada kami [Khalid] dari [Humaid] dari [Bakr bin Abdullah], ia berkata; seorang laki-laki berkata kepada [Ibnu Abbas]; kenapa penghuni rumah ini memberi minum nabidz (minuman rendaman kurma, anggur atau yang lainnya), sementara anak-anak paman mereka minum susu, madu dan sawiq (makanan yang terbuat dari gandum dicampur dengan mentega)? Apakah ada sifat kikir pada mereka atau sebuah kebutuhan? Ibnu Abbas berkata; kami tidak kikir, dan kami tidak butuh, akan tetapi Rasulullah shallallahu 'alaihi wasallam pernah berada di atas kendaraannya dan dibelangnya Usamah bin Zaid. Kemudian beliau meminta minum, lalu beliau diberi nabidz lalu beliau minum sebagian darinya dan memberikan sisanya kepada Usamah bin Zaid, dan ia pun minum sebagian darinya. Kemudian Rasulullah shallallahu 'alaihi wasallam bersabda: "Kalian telah bertindak baik, memang demikian yang sepatutnya kalian lakukan." Maka, kami seperti demikian dan tidak ingin mengubah apa yang Rasulullah shallallahu 'alaihi wasallam katakan
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2021</td></tr><tr><td>Arabic No</td><td>2021</td></tr><tr><td>Reference</td><td>Book 11 Hadith 301</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Bekr b. Abdillah dedi ki: Bir adam İbn Abbâs'a (gelerek): Şu Beyt'in ehline ne oluyor da amcalarının oğulları (hacılara) süt, bal ve kavut sunarlarken bunlar nebîz sunuyorlar. Onlarda cimrilik mi var yoksa muhtaç mıdırlar? dedi. İbn Abbas (r.a.) da: Biz ne cimriyiz, ne de muhtaç! Fakat (birgün) Resûlulah sallallahu aleyhi ve sellem terkisinde Usâme b. Zeyd olduğu halde (yanımıza) geldi de içecek (bir su) istedi. Bunun üzerine kendisine bir üzüm şerbeti getirildi, o bunu içti ve artanını da Usâme'ye sundu. Usâme de onu içti. Sonra Resûlullah sallallahu aleyhi ve sellem: "Aferin size, ne iyi ettiniz! Hep böyle yapın" buyurdu. İşte biz de böyle (yapıyoruz) Resûlullah sallallahu aleyhi ve sellemin buyruğunu değiştirmek istemiyoruz dedi
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2021</td></tr><tr><td>Arabic No</td><td>2021</td></tr><tr><td>Reference</td><td>Book 11 Hadith 301</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
بکر بن عبداللہ کہتے ہیں کہ ابن عباس رضی اللہ عنہما سے ایک شخص نے پوچھا: کیا وجہ ہے کہ اس گھر کے لوگ نبیذ ( کھجور کا شربت ) پلاتے ہیں اور آپ کے چچا کے بیٹے ( قریش ) دودھ، شہد اور ستو پلاتے ہیں؟ کیا یہ لوگ بخیل یا محتاج ہیں؟ ابن عباس نے کہا: نہ ہم بخیل ہیں اور نہ محتاج، بلکہ رسول اللہ صلی اللہ علیہ وسلم ایک روز اپنی سواری پر بیٹھ کر آئے، آپ صلی اللہ علیہ وسلم کے پیچھے اسامہ بن زید رضی اللہ عنہما تھے، آپ صلی اللہ علیہ وسلم نے پینے کو کچھ مانگا تو نبیذ پیش کیا گیا، آپ نے اس میں سے پیا اور باقی ماندہ اسامہ رضی اللہ عنہ کو دے دیا، تو انہوں نے بھی اس میں سے پیا، اس کے بعد رسول اللہ صلی اللہ علیہ وسلم نے فرمایا: تم نے اچھا کیا اور خوب کیا ایسے ہی کیا کرو ، تو ہم اسی کو اختیار کئے ہوئے ہیں جسے رسول اللہ صلی اللہ علیہ وسلم نے کہا تھا، اسے ہم بدلنا نہیں چاہتے۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2021</td></tr><tr><td>Arabic No</td><td>2021</td></tr><tr><td>Reference</td><td>Book 11 Hadith 301</td></tr></tbody></table></div>