## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا مُحَمَّدُ بْنُ الْمُثَنَّى، حَدَّثَنَا عَبْدُ الْوَهَّابِ، حَدَّثَنَا هِشَامٌ، عَنْ مُحَمَّدٍ، عَنْ أَبِي هُرَيْرَةَ، عَنِ النَّبِيِّ صلى الله عليه وسلم ‏"‏ أَنَّ إِبْرَاهِيمَ صلى الله عليه وسلم لَمْ يَكْذِبْ قَطُّ إِلاَّ ثَلاَثًا ثِنْتَانِ فِي ذَاتِ اللَّهِ تَعَالَى قَوْلُهُ ‏(‏ إِنِّي سَقِيمٌ ‏)‏ وَقَوْلُهُ ‏(‏ بَلْ فَعَلَهُ كَبِيرُهُمْ هَذَا ‏)‏ وَبَيْنَمَا هُوَ يَسِيرُ فِي أَرْضِ جَبَّارٍ مِنَ الْجَبَابِرَةِ إِذْ نَزَلَ مَنْزِلاً فَأُتِيَ الْجَبَّارُ فَقِيلَ لَهُ إِنَّهُ نَزَلَ هَا هُنَا رَجُلٌ مَعَهُ امْرَأَةٌ هِيَ أَحْسَنُ النَّاسِ قَالَ فَأَرْسَلَ إِلَيْهِ فَسَأَلَهُ عَنْهَا فَقَالَ إِنَّهَا أُخْتِي ‏.‏ فَلَمَّا رَجَعَ إِلَيْهَا قَالَ إِنَّ هَذَا سَأَلَنِي عَنْكِ فَأَنْبَأْتُهُ أَنَّكِ أُخْتِي وَإِنَّهُ لَيْسَ الْيَوْمَ مُسْلِمٌ غَيْرِي وَغَيْرُكِ وَإِنَّكِ أُخْتِي فِي كِتَابِ اللَّهِ فَلاَ تُكَذِّبِينِي عِنْدَهُ ‏"‏ ‏.‏ وَسَاقَ الْحَدِيثَ ‏.‏ قَالَ أَبُو دَاوُدَ رَوَى هَذَا الْخَبَرَ شُعَيْبُ بْنُ أَبِي حَمْزَةَ عَنْ أَبِي الزِّنَادِ عَنِ الأَعْرَجِ عَنْ أَبِي هُرَيْرَةَ عَنِ النَّبِيِّ صلى الله عليه وسلم نَحْوَهُ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2212</td></tr><tr><td>Arabic No</td><td>2212</td></tr><tr><td>Reference</td><td>Book 13 Hadith 38</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
মুহাম্মদ ইবন আল্ মুসান্না .... আবূ হুরায়রা (রাঃ) নবী করীম সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম হতে বর্ণনা করেছেন। তিনি বলেন, ইরবরাহীম (আঃ) তিনবার (আপাত) মিথ্যা বলেছিলেন। যার দুটি ছিল আল্লাহ্ তা‘আলার সত্ত্বা সম্পর্কে। যেমনঃ তাঁর কথাঃ আমি পিড়ীত এবং তাঁর কথা: বরং এদের বড়টাই (মূর্তি) তা করেছে। আর তিনি যখন অত্যাচারী শাসকদের মধ্যে কোন এক অত্যাচারী রাজার ভিতর দিয়ে গমণ করেছিলেন, এমতাবস্থায় তিনি (তাঁর স্ত্রী সারা সহ) যখন কোন এক স্থানে অবতরণ করেন; তখন ঐ অত্যাচারী রাজার জনৈক ব্যক্তি সেখানে আসে। এরপর সে তাকে (রাজাকে) গিয়ে বলে, এখানে এক ব্যক্তি এসেছে যার সাথে সুন্দরী রমনী আছে। এরপর তিনি বলেন, তখন সে (অত্যাচারী রাজা) তাঁর (ইবরাহীমের) নিকট একজন অনুচর পাঠিয়ে দেয়। তখন তিনি তাঁর নিকট উপস্থিত হলে, সে তাঁর (সারার) সম্পর্কে জিজ্ঞাসা করে যে, সে কে? জবাবে তিনি বলেন, সে আমার ভগ্নি। অতঃপর তিনি (ইবরাহীম) তাঁর (সারার) নিকট ফিরে এসে বলেন, এই ব্যক্তি আমাকে তোমার সম্পর্কে জিজ্ঞাসা করেছে; আমি তাকে বলেছি, তুমি আমার ভগ্নি। আর অবস্থা এই যে, বর্তমান দুনিয়াতে তুমি এবং আমি ব্যতীত আর কোন মুসলিম নেই। আর আল্লাহ কিতাব অনুযায়ী তুমি আমার বোন। কাজেই, আমি তোমার সম্পর্কে তার নিকট মিথ্যা বলেছি এরূপ মনে করবে না। এরূপে হাদীস বর্ণিত হয়েছে। ইমাম আবূ দাঊদ (রহঃ) বলেন, এ হাদীসটির অনুরূপ হাদীস শু‘আয়ব ইবন আবূ হামযা আবূ হুরায়রা (রাঃ) হতে, তিনি নবী করীম সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম হতে বর্ণিত হয়েছে। (অর্থাৎ আদম সন্তান হিসাবে সকল মুসলিম স্ত্রী-পুরুষ পাস্পর ভাই-বোন। আত্মরক্ষার প্রয়োজনে সমার্থবোধক শব্দ ব্যবহারকে তাওরিয়্যাহ বলে, তা মিথ্যা নয়)।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2212</td></tr><tr><td>Arabic No</td><td>2212</td></tr><tr><td>Reference</td><td>Book 13 Hadith 38</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Abu Hurairah reported the Prophet(ﷺ) as saying Abraham(peace be upon him) never told a lie except on three occasions twice for the sake of Allaah. Allaah quoted his words (in the Qur’an) “I am indeed sick” and “Nay, this was done by - this is their biggest one”. Once he was passing through the land of a tyrant (king). He stayed there in a place. People went to the tyrant and informed him saying “A man has come down here; he has a most beautiful woman with him.” So he sent for him (Abraham) and asked about her. He said she is my sister. When he returned to her, he said “he asked me about you and I informed him that you were my sister. Today there is no believer except me and you. You are my sister in the Book of Allaah (i.e., sister in faith). So do not belie me before him. The narrator then narrated the rest of the tradition. Abu Dawud said “A similar tradition has also been narrated by Shu’aib bin Abi Hamza from Abi Al Zinad from Al A’raj on the authority of Abu Hurairah from the Prophet (ﷺ)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2212</td></tr><tr><td>Arabic No</td><td>2212</td></tr><tr><td>Reference</td><td>Book 13 Hadith 38</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Muhammad bin Al Mutsanna], telah menceritakan kepada kami [Abdul Wahhab], telah menceritakan kepada kami [Hisyam] dari [Muhammad] dari [Abu Hurairah] dari Nabi shallallahu 'alaihi wasallam bahwa Ibrahim shallallahu 'alaihi wasallam tidak berdusta kecuali tiga hal, dua hal mengenai Dzat Allah ta'ala, perkataannya; sesungguhnya kau sakit, dan perkataannya; melainkan yang melakukannya adalah berhala yang besar diantara mereka, dan ketika ia berjalan di Negeri yang dipimpin oleh orang yang otoriter ketika ia singgah di suatu tempat kemudian ia dihadapkan kepada penguasa yang otoriter tersebut dan dikatakan kepada penguasa tersebut; sesungguhnya telah singgah di sini seorang laki-laki bersama seorang wanita yang paling cantik. Beliau bersabda: "Kemudian penguasa tersebut mengirim utusan kepadanya dan bertanya mengenai wanita tersebut. Lalu Ibrahim berkata; sesungguhnya ia adalah saudariku. Kemudian tatkala Ibrahim kembali kepada isterinya ia berkata; sesungguhnya penguasa ini bertanya kepadaku mengenai dirimu, kemudian aku beritahukan kepada mereka bahwa engkau adalah saudariku. Sesungguhnya pada hari ini tidak ada seorang muslim pun kecuali aku dan engkau, dan engkau adalah saudariku dalam kitab Allah, maka janganlah engkau dustakan aku di hadapannya!" kemudian Muhammad bin Al Mutsanna menyebutkan hadits tersebut. Abu Daud berkata; khabar ini diriwayatkan oleh [Syu'aib bin Abu Hamzah] dari [Abu Az Zinad] dari [Al A'raj] dari [Abu Hurairah] dari Nabi shallallahu 'alaihi wasallam seperti itu
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2212</td></tr><tr><td>Arabic No</td><td>2212</td></tr><tr><td>Reference</td><td>Book 13 Hadith 38</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ebu Hureyre (r.a.)'in, Nebi (s.a.v.)'den rivayet ettiğine göre; "İbrahim aleyhisselâm üç yalandan başka hiç bir yalan söylememiştir: (Bunlardan) ikisi yüce Allah'ın zatı hakkındadır; (birincisi) "Ben gerçekten hastayım" demesi, (ikincisi); "Belki bu işi büyükleri olan şu (put) yapmıştır" demesidir. (Üçüncüsüde) şöyle olmuştur; (Hz. İbrahim) zalimlerden birinin toprağında yolculuk yaparken bir yerde konaklamıştı. "Beraberinde insanlann en güzeli bir kadın bulunan bir adam (gelip ülkemizde) şuracıkta konaklamıştır" diye zâlim'e haber verildi. Bunun üzerine o zalim (Hz. İbrahim'e bir elçi) gönderip (yanına çağırttı ve) ona Sâre'yi sordu. Hz. İbrahim de; "O benim kız kardeşimdir" cevabını verdi. Sare'nin yanına dönünce "Bu (adam) bana seni sordu. Ben de kendisine senin kız kardeşim olduğunu söyledim. Çünkü bugün seninle benden başka müslüman yoktur. Allah'ın kitabına göre sen benim (kız) kardeşimsin. (Sakın) beni onun yanında yalancı çıkarma" dedi ve (daha sonra râvi Ebu Hureyre) hadisinin geri kalan kısmını) nakletti. Buharî, enbiya, nikâh; Müslim, fedail; Tirmizî, tefsir sure; Ahmed b. Hanbel, II, 403. Ebû Dâvud dedi ki: Şu'ayb b. Ebû Hamza, Ebu'z-Zinad'dan, (o da) el-A'rac'dan (o da) Ebu Hureyre'den (o da) Nebi sallalahu aleyhi vesellem'den bu hadisin bir benzerini rivayet etmiştir
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2212</td></tr><tr><td>Arabic No</td><td>2212</td></tr><tr><td>Reference</td><td>Book 13 Hadith 38</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ابوہریرہ رضی اللہ عنہ سے روایت ہے کہ نبی اکرم صلی اللہ علیہ وسلم نے فرمایا: ابراہیم علیہ السلام نے صرف تین جھوٹ بولے ۱؎ جن میں سے دو اللہ تعالیٰ کی ذات کے لیے تھے، پہلا جب انہوں نے کہا کہ میں بیمار ہوں ۲؎، دوسرا جب انہوں نے ایک سوال کے جواب میں کہا تھا: بلکہ یہ تو ان کے اس بڑے کی کارستانی ہے، تیسرا اس موقعہ پر جب کہ وہ ایک سرکش بادشاہ کے ملک سے گزر رہے تھے ایک مقام پر انہوں نے قیام فرمایا تو اس سرکش تک یہ بات پہنچی، اور اسے بتایا گیا کہ یہاں ایک شخص ٹھہرا ہوا ہے اور اس کے ساتھ ایک انتہائی خوبصورت عورت ہے، چنانچہ اس نے ابراہیم علیہ السلام کو بلوایا اور عورت کے بارے میں دریافت کیا تو انہوں نے کہا: یہ تو میری بہن ہے ، جب وہ لوٹ کر بیوی کے پاس آئے تو انہوں نے بتایا کہ اس نے مجھ سے تمہارے بارے میں دریافت کیا تو میں نے اسے یہ بتایا ہے کہ تم میری بہن ہو کیونکہ آج میرے اور تمہارے علاوہ کوئی بھی مسلمان نہیں ہے لہٰذا تم میری دینی بہن ہو، تو تم اس کے پاس جا کر مجھے جھٹلا نہ دینا ، اور پھر پوری حدیث بیان کی۔ ابوداؤد کہتے ہیں: شعیب بن ابی حمزہ نے ابوالزناد سے ابوالزناد نے اعرج سے، اعرج نے ابوہریرہ رضی اللہ عنہ سے، ابوہریرہ نے نبی اکرم صلی اللہ علیہ وسلم سے اسی طرح کی روایت کی ہے۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2212</td></tr><tr><td>Arabic No</td><td>2212</td></tr><tr><td>Reference</td><td>Book 13 Hadith 38</td></tr></tbody></table></div>