## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا النُّفَيْلِيُّ، حَدَّثَنَا زُهَيْرٌ، حَدَّثَنَا عَاصِمٌ الأَحْوَلُ، قَالَ حَدَّثَنِي أَبُو عُثْمَانَ، قَالَ حَدَّثَنِي سَعْدُ بْنُ مَالِكٍ، قَالَ سَمِعَتْهُ أُذُنَاىَ، وَوَعَاهُ، قَلْبِي مِنْ مُحَمَّدٍ عَلَيْهِ السَّلاَمُ أَنَّهُ قَالَ ‏ "‏ مَنِ ادَّعَى إِلَى غَيْرِ أَبِيهِ وَهُوَ يَعْلَمُ أَنَّهُ غَيْرُ أَبِيهِ فَالْجَنَّةُ عَلَيْهِ حَرَامٌ ‏"‏ ‏.‏ قَالَ فَلَقِيتُ أَبَا بَكْرَةَ فَذَكَرْتُ ذَلِكَ لَهُ فَقَالَ سَمِعَتْهُ أُذُنَاىَ وَوَعَاهُ قَلْبِي مِنْ مُحَمَّدٍ صلى الله عليه وسلم ‏.‏ قَالَ عَاصِمٌ فَقُلْتُ يَا أَبَا عُثْمَانَ لَقَدْ شَهِدَ عِنْدَكَ رَجُلاَنِ أَيُّمَا رَجُلَيْنِ ‏.‏ فَقَالَ أَمَّا أَحَدُهُمَا فَأَوَّلُ مَنْ رَمَى بِسَهْمٍ فِي سَبِيلِ اللَّهِ أَوْ فِي الإِسْلاَمِ يَعْنِي سَعْدَ بْنَ مَالِكٍ وَالآخَرُ قَدِمَ مِنَ الطَّائِفِ فِي بِضْعَةٍ وَعِشْرِينَ رَجُلاً عَلَى أَقْدَامِهِمْ فَذَكَرَ فَضْلاً ‏.‏ قَالَ أَبُو عَلِيٍّ سَمِعْتُ أَبَا دَاوُدَ قَالَ قَالَ النُّفَيْلِيُّ حَيْثُ حَدَّثَ بِهَذَا الْحَدِيثِ وَاللَّهِ إِنَّهُ عِنْدِي أَحْلَى مِنَ الْعَسَلِ يَعْنِي قَوْلَهُ حَدَّثَنَا وَحَدَّثَنِي قَالَ أَبُو عَلِيٍّ وَسَمِعْتُ أَبَا دَاوُدَ يَقُولُ سَمِعْتُ أَحْمَدَ يَقُولُ لَيْسَ لِحَدِيثِ أَهْلِ الْكُوفَةِ نُورٌ - قَالَ - وَمَا رَأَيْتُ مِثْلَ أَهْلِ الْبَصْرَةِ كَانُوا تَعَلَّمُوهُ مِنْ شُعْبَةَ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Bukhari And Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5113</td></tr><tr><td>Arabic No</td><td>5113</td></tr><tr><td>Reference</td><td>Book 43 Hadith 341</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
নুফায়লী (রহঃ) ..... সাআদ ইবন মালিক (রাঃ) থেকে বর্ণিত। তিনি বলেনঃ আমার দু'কান শুনেছে এবং অন্তর স্মরণ রেখেছে যে, মুহাম্মদ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেছেনঃ যে ব্যক্তি জেনে শুনে, যে ব্যক্তি তার পিতা নয়, এরূপ ব্যক্তির সাথে নিজের পিতার সম্পর্ক স্থাপন করে; তার জন্য জান্নাত হারাম। রাবী বলেনঃ এরপর আমি আবূ বাকরা (রাঃ)-এর সাথে সাক্ষাৎ করে, এ হাদীছে তার কাছে বর্ণনা করলে, তিনিও বলেনঃ আমার দু'কান শুনেছে এবং অন্তর স্মরণ রেখেছে যে, মুহাম্মদ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এরূপ বলেছেন। রাবী আসিম (রহঃ) বলেনঃ আমি উছমান (রাঃ)-কে জিজ্ঞাসা করিঃ আপনার কাছে দু'ব্যক্তি এ হাদীছ সম্পর্কে সাক্ষ্য দিয়েছেন, এরা দু'জন কেমন লোক? তিনি বলেনঃ এদের একজন এমন, যে সর্ব প্রথম আল্লাহ্‌র রাস্তায় অথবা ইসলামে তীর নিক্ষেপ করেছিল- অর্থাৎ সাআদ ইবন মালিক (রাঃ)। আর দ্বিতীয় ব্যক্তি এমন, যে তায়েফ থেকে বিশ জনের ও অধিক লোকের সাথে হেঁটে চলে আসে। এরপর তিনি তার মর্যাদা সম্পর্কে বর্ণনা করেন। রাবী আবূ আলী (রহঃ) বলেনঃ আমি ইমাম আবূ দাউদ (রহঃ)-কে বলতে শুনেছিঃ যখন নুফায়লী এ হাদীছ বর্ণনা করেন, তখন তিনি বলেন যে, আল্লাহ্‌র শপথ! এ হাদীছ আমার কাছে মধুর চাইতে ও মিষ্টি মনে হয়। রাবী আবূ আলী (রহঃ) আরো বলেনঃ ইমাম আবূ দাউদ (রহঃ) আহমদ (রহঃ)-কে বলতে শুনেনঃ কূফাবাসীদের বর্ণিত হাদীছে নূর নেই, (কেননা, তারা সনদ ঠিকভাবে বর্ণনা করে না।) ইমাম আহমদ (রহঃ) আরো বলেনঃ আমি বসরাবাসীদের চাইতে উত্তম লোক দেখিনি; কেননা, তারা শোবা (রহঃ) থেকে হাদীছ বর্ণনা করেন, (যিনি তাদের হাদীছ বর্ণনার ধারা উত্তমরূপে শিক্ষা দেন।)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Bukhari And Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5113</td></tr><tr><td>Arabic No</td><td>5113</td></tr><tr><td>Reference</td><td>Book 43 Hadith 341</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Sa’id b. Malik said:My ears heard it end my heart remembered it from Muhammad (May peace be upon him) who said: if a man claims to be the son of a man who is not his father, paradise will be forbidden for him. He said: I then met Abu Bakrah and mentioned it to him. He said: my ears heard it and my heart remembered it from Muhammad (peace be upon him). ‘Asim said : I said : Abu ‘Uthman! Two men testified before you. Who are they? He said : One of them is the one who is first to shoot arrow in the path of Allah or in the path of Islam, that is to say : Sa’d b. Malik. The other is the one came from al-Taif with ten and some men on foot. He then mentioned his excellence. Abu Dawud said : When al-Nufaili mentioned this tradition, he said : I swear by Allah, this is sweater with me than honey, that is no say, his way transmission. Abu ‘Ali said : I heard Abu Dawud say : I heard Ahmad say : The people of Kufah have no light in their traditions. I did not see them like the people of Basrah. They learnt it from Shu’bah
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Bukhari And Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5113</td></tr><tr><td>Arabic No</td><td>5113</td></tr><tr><td>Reference</td><td>Book 43 Hadith 341</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [An Nufaili] berkata, telah menceritakan kepada kami [Zuhair] berkata, telah menceritakan kepada kami [Ashim Al Ahwal] ia berkata; telah menceritakan kepadaku [Abu Utsman] ia berkata; telah menceritakan kepadaku [Sa'd bin Malik] ia berkata, "Kedua telingaku mendengar dan hatinya meresapinya dari Muhammad shallallahu 'alaihi wasallam, beliau bersabda: "Barangsiapa menisbatkan dirinya kepada selain bapaknya, padahal ia tahu dia bukan bapaknya, maka surga haram untuk ia masuki." Sa'd berkata, "Aku lalu bertemu [Abu Bakrah], maka aku pun menceritakan hadits itu kepadanya. Ia berkata, "Kedua telingaku mendengar dan hatiku meresapinya, dari Muhammad shallallahu 'alaihi wasallam. Ashim berkata, "Aku berkata, "Wahai Abu Utsman, ada dua orang yang ada di sisimu yang ikut melihatnya, maka siapakah salah seorang dari mereka itu?" Abu Utsman menjawab, "Seorang dari mereka itu adalah orang yang pertama kali yang melemparkan anak panahnya di jalan Allah -atau dalam Islam-, yaitu Sa'd bin Malik. Sedangkan yang lainnya adalah seseorang yang tergabung dalam sebuah rombongan yang datang dari Thaif dengan berjalan kaki, jumlah mereka dua puluhan orang lebih." lalu ia menyebutkan sisa hadits." An Nufaili saat menceritakan hadits ini ia berkata, "Demi Allah, sesungguhnya ucapan 'telah menceritakan kepada kami dan telah menceritakan kepadaku' menurutku lebih manis dari madu." Abu Ali berkata, "Aku mendengar Abu Dawud berkata, "Aku mendengar Ahmad berkata, "Pada hadits orang-orang Kufah tidak ada cahaya." Ahmad bin Hanbal berkata, "Aku tidak pernah melihat sebagaimana orang-orang Bashrah (dalam menuntut hadits), mereka mempelajarinya dari Syu'bah
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Bukhari And Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5113</td></tr><tr><td>Arabic No</td><td>5113</td></tr><tr><td>Reference</td><td>Book 43 Hadith 341</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ebu Osman dedi ki: Sa'd b. Malik bana dedi ki: Muhammed (s.a.v.)'in "Her kim babası olmadığını bildiği halde babasından başkasını (babam diye) iddia ederse ona cennet haram olur." dediğini kulaklarım duydu, kalbim iyi belledi. (Ebu Osman sözlerine devam ederek) dedi ki: (Bu hadisi Sa'd'den duyduktan) kısa bir süre sonra Ebu Bekre ile karşılaştım ve hadisi kendisine okudum da (bana ayren Sa'd'in dediği gibi): "Bunu Muhammed (s.a.v.)'den kulaklarım duydu, kalbim de iyice belledi" dedi. (Ravi) Âsim dedi ki ben (Ebu Osman'a) Ey Ebu Osman! Senin yanında (bu hadisin doğruluğuna dair) iki kişi şahidlik etmiştir. Bu iki adam kimdir? dedim de: Birisi Allah yolunda -yahut İslam uğrunda- ilk ok atan kimsedir. Öbürü ise (Tai kalesi kuşatıldığı zaman) Tai'den yaya olarak (Hz. Peygambere) gelip (Müslümanların safına katılan) yirmi küsur kişiden biridir" dedi ve (Ebu Bekre'yle ilgili bir takım) fazilet(ler)i anlattı
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Bukhari And Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5113</td></tr><tr><td>Arabic No</td><td>5113</td></tr><tr><td>Reference</td><td>Book 43 Hadith 341</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
سعد بن مالک رضی اللہ عنہ کہتے ہیں کہ میرے کانوں نے محمد صلی اللہ علیہ وسلم سے سنا ہے اور میرے دل نے یاد رکھا ہے، آپ نے فرمایا: جو شخص جان بوجھ کر، اپنے آپ کو اپنے والد کے علاوہ کسی اور کی طرف منسوب کرے تو جنت اس پر حرام ہے ۔ عثمان کہتے ہیں: میں سعد رضی اللہ عنہ سے یہ حدیث سن کر ابوبکرہ رضی اللہ عنہ سے ملا اور ان سے اس حدیث کا ذکر کیا، تو انہوں نے بھی کہا: میرے کانوں نے محمد صلی اللہ علیہ وسلم سے سنا، اور میرے دل نے اسے یاد رکھا، عاصم کہتے ہیں: اس پر میں نے کہا: ابوعثمان تمہارے پاس دو آدمیوں نے اس بات کی گواہی دی، لیکن یہ دونوں صاحب کون ہیں؟ ان کی صفات و خصوصیات کیا ہیں؟ تو انہوں نے کہا: ایک وہ ہیں جنہوں نے اللہ کی راہ میں یا اسلام میں سب سے پہلے تیر چلایا یعنی سعد بن مالک رضی اللہ عنہ اور دوسرے وہ ہیں جو طائف سے بیس سے زائد آدمیوں کے ساتھ پیدل چل کر آئے پھر ان کی فضیلت بیان کی۔ نفیلی نے یہ حدیث بیان کی تو کہا: قسم اللہ کی! یہ حدیث میرے لیے شہد سے بھی زیادہ میٹھی ہے، یعنی ان کا «حدثنا وحدثني» کہنا ( مجھے بہت پسند ہے ) ۔ ابوعلی کہتے ہیں: میں نے ابوداؤد سے سنا ہے، وہ کہتے تھے: میں نے احمد کو کہتے ہوئے سنا ہے کہ اہل کوفہ کی حدیث میں کوئی نور نہیں ہوتا ( کیونکہ وہ اسانید کو صحیح طریقہ پر بیان نہیں کرتے، اور اخبار و تحدیث کے درمیان کوئی فرق نہیں کرتے ) اور کہا: میں نے اہل بصرہ جیسے اچھے لوگ بھی نہیں دیکھے انہوں نے شعبہ سے حدیث حاصل کی ( اور شعبہ کا طریقہ اسناد کو اچھی طرح بتا دینے کا تھا ) ۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Bukhari And Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5113</td></tr><tr><td>Arabic No</td><td>5113</td></tr><tr><td>Reference</td><td>Book 43 Hadith 341</td></tr></tbody></table></div>