## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا الْحَسَنُ بْنُ عَلِيٍّ، حَدَّثَنَا عَفَّانُ، وَسَعِيدُ بْنُ عَامِرٍ، وَحَجَّاجٌ، - وَالْمَعْنَى وَاحِدٌ - قَالُوا حَدَّثَنَا هَمَّامٌ، حَدَّثَنَا عَامِرٌ الأَحْوَلُ، حَدَّثَنِي مَكْحُولٌ، أَنَّ ابْنَ مُحَيْرِيزٍ، حَدَّثَهُ أَنَّ أَبَا مَحْذُورَةَ حَدَّثَهُ أَنَّ رَسُولَ اللَّهِ صلى الله عليه وسلم عَلَّمَهُ الأَذَانَ تِسْعَ عَشْرَةَ كَلِمَةً وَالإِقَامَةَ سَبْعَ عَشْرَةَ كَلِمَةً الأَذَانُ ‏ "‏ اللَّهُ أَكْبَرُ اللَّهُ أَكْبَرُ اللَّهُ أَكْبَرُ اللَّهُ أَكْبَرُ أَشْهَدُ أَنْ لاَ إِلَهَ إِلاَّ اللَّهُ أَشْهَدُ أَنْ لاَ إِلَهَ إِلاَّ اللَّهُ أَشْهَدُ أَنَّ مُحَمَّدًا رَسُولُ اللَّهِ أَشْهَدُ أَنَّ مُحَمَّدًا رَسُولُ اللَّهِ أَشْهَدُ أَنْ لاَ إِلَهَ إِلاَّ اللَّهُ أَشْهَدُ أَنْ لاَ إِلَهَ إِلاَّ اللَّهُ أَشْهَدُ أَنَّ مُحَمَّدًا رَسُولُ اللَّهِ أَشْهَدُ أَنَّ مُحَمَّدًا رَسُولُ اللَّهِ حَىَّ عَلَى الصَّلاَةِ حَىَّ عَلَى الصَّلاَةِ حَىَّ عَلَى الْفَلاَحِ حَىَّ عَلَى الْفَلاَحِ اللَّهُ أَكْبَرُ اللَّهُ أَكْبَرُ لاَ إِلَهَ إِلاَّ اللَّهُ وَالإِقَامَةُ اللَّهُ أَكْبَرُ اللَّهُ أَكْبَرُ اللَّهُ أَكْبَرُ اللَّهُ أَكْبَرُ أَشْهَدُ أَنْ لاَ إِلَهَ إِلاَّ اللَّهُ أَشْهَدُ أَنْ لاَ إِلَهَ إِلاَّ اللَّهُ أَشْهَدُ أَنَّ مُحَمَّدًا رَسُولُ اللَّهِ أَشْهَدُ أَنَّ مُحَمَّدًا رَسُولُ اللَّهِ حَىَّ عَلَى الصَّلاَةِ حَىَّ عَلَى الصَّلاَةِ حَىَّ عَلَى الْفَلاَحِ حَىَّ عَلَى الْفَلاَحِ قَدْ قَامَتِ الصَّلاَةُ قَدْ قَامَتِ الصَّلاَةُ اللَّهُ أَكْبَرُ اللَّهُ أَكْبَرُ لاَ إِلَهَ إِلاَّ اللَّهُ ‏"‏ ‏.‏ كَذَا فِي كِتَابِهِ فِي حَدِيثِ أَبِي مَحْذُورَةَ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Hasan Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Hasan</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>502</td></tr><tr><td>Arabic No</td><td>502</td></tr><tr><td>Reference</td><td>Book 2 Hadith 112</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
আল্-হাসান ইবনু আলী ..... ইবনু মুহায়রিয (রহঃ) আবূ মাহযূরা (রাঃ) হতে বর্ণনা করেছেন। তিনি বলেন, রাসূলুল্লাহ্ সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম তাঁকে উনিশ শব্দে আযান এবং সতের শব্দে ইকামত শিক্ষা দিয়েছেন। আযানের শব্দগুলি নিম্নরূপঃ “আল্লাহু আকবার, আল্লাহু আকবার, আল্লাহু আকবার, আল্লাহু আকবার; আশহাদু আল্-লা ইলাহা ইল্লাল্লাহ্, আশহাদু আল্-লা ইলাহা ইল্লাল্লাহ্; আশহাদু আন্না মুহাম্মাদুর রাসূলুল্লাহ্, আশহাদু আন্না মুহাম্মাদুর রাসূলুল্লাহ্; আশহাদু আল্-লা ইলাহা ইল্লাল্লাহ্, আশহাদু আল্-লা ইলাহা ইল্লাল্লাহ্; আশহাদু আন্না মুহাম্মাদুর রাসূলুল্লাহ্, আশহাদু আন্না মুহাম্মাদুর রাসূলুল্লাহ্; হাইয়া আলাস্-সালাহ্, হাইয়া আলাস্-সালাহ্, হাইয়া আলাল-ফালাহ্, হাইয়া আলাল-ফালাহ্, আল্লাহু আকবার, আল্লাহু আকবার; লা ইলাহা ইল্লাল্লাহ্।” আর ইকামতের শব্দগুলি হলঃ “আল্লাহু আকবার, আল্লাহু আকবার, আল্লাহু আকবার, আল্লাহু আকবার, আশহাদু আল-লা ইলাহা ইল্লাল্লাহ্, আশহাদু আল-লা ইলাহা ইল্লাল্লাহ্, আশহাদু আন্না মুহাম্মাদুর রাসূলুল্লাহ্, আশহাদু আন্না মুহাম্মাদুর রাসূলুল্লাহ্, হাইয়া আলাস্-সালাহ্; হাইয়া আলাস্-সালাহ্; হাইয়া আলাল-ফালাহ্; হাইয়া আলাল-ফালাহ্; কাদ কামাতিস্ সালাহ্; কাদ কামাতিস্-সালাহ্, আল্লাহু আকবার, আল্লাহু আকবার; লা ইলাহা ইল্লাল্লাহ্” আবূ মাহযূরা (রাঃ) সূত্রে বর্ণিত। হাদীছটি তাঁর নিকট রক্ষিত কিতাবে এভাবে উল্লেখ আছে। (নাসাঈ, মুসলিম)।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Hasan Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Hasan</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>502</td></tr><tr><td>Arabic No</td><td>502</td></tr><tr><td>Reference</td><td>Book 2 Hadith 112</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Abu Mahdhurah reported ; The Messenger of Allah (May peace be upon him) taught him nineteen phrases in ADHAN and seventeen phrases in IQAMAH. ADHAN runs; Allah is most great. Allah is most great. Allah is most great. Allah is most great; I testify that there is no god but Allah. I testify that Muhammad is the Messenger of Allah. I testify that Muhammad is the Messenger of Allah; I testify that there is no god but Allah. I testify that there is no god but Allah; I testify that Muhammad is the Messenger of Allah, I testify that Muhammad is Messenger of Allah:come to prayer, come to prayer, come to salvation; Allah is most great, Allah is most great: there is no god but Allah. IQAMAH runs: Allah is most great, Allah is most great. Allah is most great, Allah is most great: I testify that there is no god but Allah, I testify that there is no god but Allah; I testify that Muhammad is the Messenger of Allah, I testify that Muhammad is the Messenger of Allah; come to prayer; come to prayer: come to salvation. Come to salvation; the time for prayer has come the time for prayer has come: Allah is most great, Allah is most great: there is no god but Allah. This is recorded in his collection (i.e., in the collection of the narrator Hammam b. Yahya) according to the tradition reported by Abu Mahdhurah (i.e., IQAMAH contains seventeen phrases)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Hasan Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Hasan</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>502</td></tr><tr><td>Arabic No</td><td>502</td></tr><tr><td>Reference</td><td>Book 2 Hadith 112</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Al-Hasan bin Ali] telah menceritakan kepada kami [Affan] dan [Sa'id bin Amir] dan [Hajjaj] dengan makna yang sama, mereka berkata; Telah menceritakan kepada kami [Hammam] telah menceritakan kepada kami [Amir Al-Ahwal] telah menceritakan kepadaku [Makhul] bahwasanya [Ibnu Muhairiz] telah menceritakan kepadanya bahwasanya [Abu Mahdzurah] telah menceritakan kepadanya bahwasanya Rasulullah shallallahu 'alaihi wasallam telah mengajarinya lafazh adzan sembilan belas kalimat, dan lafazh iqamah tujuh belas kalimat. Adzan: Allaahu akbar Allaahu akbar, Allaahu akbar Allaahu akbar, Asyhadu an laa ilaaha illallaah, Asyhadu an laa ilaaha illallaah, Asyhadu ana Muhammadar Rasuulullah, Asyhadu anna Muhammadar Rasuulullah, Asyhadu an laa ilaaha illallaah, Asyhadu ana Muhammadar Rasuulullah, Asyhadu anna Muhammadar Rasuulullah, Hayya 'alash shalaah, Hayya 'alash shalaah, Hayya 'alal falaah, Hayya 'alal falaah, Allaahu akbar Allaahu Akbar, Laa ilaaha illallaah. Sedangkan lafazh iqamah: Allaahu Akbar Allaahu akbar, Allaahu akbar Allaahu akbar, Asyhadu an laa ilaaha illallah, asyhadu an laa ilaaha illallaah, Asyhadu anna Muhammadar Rasulullah, asyhadu anna Muhammadar Rasulullah, hayya 'alash shalaah Hayya 'alash shalaah, Hayya 'alal falaah, Hayya 'alal falaah, Qad qaamatis shalaah, qad qaamatis shalaah, Allaahu akbar Allaahu akbar, Laa ilaaha illallaah. Demikianlah dalam kitabnya tentang Hadits Abu Mahdzurah
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Hasan Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Hasan</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>502</td></tr><tr><td>Arabic No</td><td>502</td></tr><tr><td>Reference</td><td>Book 2 Hadith 112</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
İbn Muhayrîz'în Ebu Mahzure'den naklettiğine göre: "Nebiyy-i Ekrem (Sallallahu aleyhi ve Sellem) Ebu Mahzure'ye ezan'ı on dokuz kelime, ikameti de on yedi kelime (olarak) öğretmiştir. Ezan (şu kelimelerden meydana gelir): ALLAHU EKBER, ALLAHU EKBER, ALLAHU EKBER, ALLAHU EKBER EŞHEDU EN LA İLAHE İLLALLAH EŞHEDU EN LA İLAHE İLLALLAH EŞHEDU ENNE MUHAMMEDEN RESULULLAH EŞHEDU ENNE MUHAMMEDEN RESULULLAH EŞHEDU EN LA İLAHE İLLALLAH EŞHEDU EN LA İLAHE İLLALLAH EŞHEDU ENNE MUHAMMEDEN RESULULLAH EŞHEDU ENNE MUHAMMEDEN RESULULLAH HAYYA ALE'S-SELAH HAYYA ALE'S-SELAH HAYYA ALE'L-FELAH HAYYA ALE'L-FELAH ALLAHU EKBER ALLAHU EKBER LA İLAHE İLLALLAH İkamet de,(şöyledir): ALLAHU EKBER, ALLAHU EKBER, ALLAHU EKBER, ALLAHU EKBER EŞHEHU EN LA İLAHE İLLALLAH, EŞHEHU EN LA İLAHE İLLALLAH EŞHEDU ENNE MUHAMMEDEN RESULULLAH, EŞHEDU ENNE MUHAMMEDEN RESULULLAH HAYYA ALE'S-SELAH, HAYYA ALE'S-SELAH HAYYA ALE'L-FELAH, HAYYA ALE'L-FELAH KAD KAMETU'S-SALAT, KAD KAMETU'S-SALAT ALLAHU EKBER, ALLAHU EKBER LA İLAHE İLLALLAH Hemram'ın kitabındaki (rivayet) de (bu) Ebu Mahzure hadisindeki gibidir. Diğer tahric: Nesai, ezan; İbn Mace, ezan
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Hasan Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Hasan</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>502</td></tr><tr><td>Arabic No</td><td>502</td></tr><tr><td>Reference</td><td>Book 2 Hadith 112</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ابن محیریز کا بیان ہے کہ ابو محذورہ رضی اللہ عنہ نے ان سے بیان کیا کہ رسول اللہ صلی اللہ علیہ وسلم نے انہیں اذان کے انیس کلمات اور اقامت کے سترہ کلمات سکھائے، اذان کے کلمات یہ ہیں: «الله أكبر الله أكبر الله أكبر الله أكبر أشهد أن لا إله إلا الله أشهد أن لا إله إلا الله أشهد أن محمدا رسول الله أشهد أن محمدا رسول الله أشهد أن لا إله إلا الله أشهد أن لا إله إلا الله أشهد أن محمدا رسول الله أشهد أن محمدا رسول الله حى على الصلاة حى على الصلاة حى على الفلاح حى على الفلاح الله أكبر الله أكبر لا إله إلا الله» ۔ اور اقامت کے کلمات یہ ہیں: «الله أكبر الله أكبر الله أكبر الله أكبر أشهد أن لا إله إلا الله أشهد أن لا إله إلا الله أشهد أن محمدا رسول الله أشهد أن محمدا رسول الله حى على الصلاة حى على الصلاة حى على الفلاح حى على الفلاح قد قامت الصلاة قد قامت الصلاة الله أكبر الله أكبر لا إله إلا الله» ۔ ہمام بن یحییٰ کی کتاب میں ابومحذورہ کی جو حدیث مذکور ہے، وہ اسی طرح ہے ( یعنی اقامت کے سترہ کلمات مذکور ہیں ) ۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Hasan Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Hasan</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>502</td></tr><tr><td>Arabic No</td><td>502</td></tr><tr><td>Reference</td><td>Book 2 Hadith 112</td></tr></tbody></table></div>