## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا قُتَيْبَةُ بْنُ سَعِيدٍ، حَدَّثَنَا لَيْثٌ، ح وَحَدَّثَنَا مُحَمَّدُ بْنُ رُمْحٍ، - وَاللَّفْظُ مُتَقَارِبٌ - أَخْبَرَنَا اللَّيْثُ، عَنِ ابْنِ شِهَابٍ، عَنْ عَطَاءِ بْنِ يَزِيدَ اللَّيْثِيِّ، عَنْ عُبَيْدِ اللَّهِ بْنِ عَدِيِّ بْنِ الْخِيَارِ، عَنِ الْمِقْدَادِ بْنِ الأَسْوَدِ، أَنَّهُ أَخْبَرَهُ أَنَّهُ، قَالَ يَا رَسُولَ اللَّهِ أَرَأَيْتَ إِنْ لَقِيتُ رَجُلاً مِنَ الْكُفَّارِ فَقَاتَلَنِي فَضَرَبَ إِحْدَى يَدَىَّ بِالسَّيْفِ فَقَطَعَهَا ‏.‏ ثُمَّ لاَذَ مِنِّي بِشَجَرَةٍ فَقَالَ أَسْلَمْتُ لِلَّهِ ‏.‏ أَفَأَقْتُلُهُ يَا رَسُولَ اللَّهِ بَعْدَ أَنْ قَالَهَا قَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏"‏ لاَ تَقْتُلْهُ ‏"‏ ‏.‏ قَالَ فَقُلْتُ يَا رَسُولَ اللَّهِ إِنَّهُ قَدْ قَطَعَ يَدِي ثُمَّ قَالَ ذَلِكَ بَعْدَ أَنْ قَطَعَهَا أَفَأَقْتُلُهُ قَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏"‏ لاَ تَقْتُلْهُ فَإِنْ قَتَلْتَهُ فَإِنَّهُ بِمَنْزِلَتِكَ قَبْلَ أَنْ تَقْتُلَهُ وَإِنَّكَ بِمَنْزِلَتِهِ قَبْلَ أَنْ يَقُولَ كَلِمَتَهُ الَّتِي قَالَ ‏"‏ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>274</td></tr><tr><td>Arabic No</td><td>95.01</td></tr><tr><td>Reference</td><td>Book 1 Hadith 180</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
হাদিস একাডেমি নাম্বারঃ ১৭৫, আন্তর্জাতিক নাম্বারঃ ৯৫ ১৭৫-(১৫৫/৯৫) কুতাইবাহ ইবনু সাঈদ ও মুহাম্মাদ ইবনু রুমহ (রহঃ) ..... মিকদাদ ইবনুল আসওয়াদ (রাযিঃ) থেকে বর্ণিত। তিনি বলেন, আমি জিজ্ঞেস করলাম, হে আল্লাহর রাসূল! আপনার কি মত? যদি আমি কোন কাফিরের সাথে যুদ্ধে লিপ্ত হই, আর সে আমার উপর আক্রমণ করে তরবারি দ্বারা আমার এক হাত কেটে ফেলে, অতঃপর সে এক বৃক্ষের আড়ালে গিয়ে আমার আক্রমণ থেকে আত্মরক্ষা করে এবং এ কথা বলে যে, আমি আল্লাহর জন্য ইসলাম গ্রহণ করেছি। হে আল্লাহর রাসূল, সে এ কথা বলে যে, আমি আল্লাহর জন্য ইসলাম গ্রহণ করেছি। হে আল্লাহর রাসূল! তার এ কথা বলার পর আমি কি তাকে হত্যা করবো? রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম বললেনঃ না তাকে হত্যা করো না। আমি বললাম, হে আল্লাহর রাসূল! সে তো আমার একটি হাত কেটে ফেলেছে আর এটা কাটার পরই ঐ কথা বলছে? এমতাবস্থায় আমি কি তাকে হত্যা করবো? এবারও রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম বললেনঃ তাকে হত্যা করো না। কেননা যদি তুমি তাকে হত্যা করো তাহলে তাকে হত্যা করার পূর্বে তুমি যে অবস্থায় ছিলে, সে তোমার সে অবস্থায় এসে যাবে। আর ঐ কালিমা বলার পূর্বে সে যে অবস্থায় ছিল, তুমি সে অবস্থায় এসে যাবে*। (ইসলামিক ফাউন্ডেশনঃ ১৭৬, ইসলামিক সেন্টারঃ ১৮২) * যদি তাকে হত্যা কর, তাহলে তুমি কাফির হয়ে যাবে, আর সে মুসলিম হয়ে যাবে (অন্তরের মালিক আল্লাহ)। (নবাবী)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>274</td></tr><tr><td>Arabic No</td><td>95.01</td></tr><tr><td>Reference</td><td>Book 1 Hadith 180</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
It is narrated on the authority of Miqdad b. Aswad that he said. Messenger of Allah, you just see (here is a point):If I encountered a person amongst the infidels (in the battlefield) and he attacked me and struck me and cut off one of my hands with the sword. Then he (in order to protect himself from me) took shelter of a tree and said: I become Muslim for Allah's sake. Messenger of Allah, can I kill him after he had uttered this? The Messenger of Allah (ﷺ) said: Do not kill him. I (the narrator) said: Messenger of Allah, he cut off my hand and uttered this after amputating it; should I then kill him? The Messenger of Allah (ﷺ) said: Don't kill him, for I you kill him, verily he would be in a position where you had been before killing him and verily you would be in a position where he had been before uttering (kalima)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>274</td></tr><tr><td>Arabic No</td><td>95.01</td></tr><tr><td>Reference</td><td>Book 1 Hadith 180</td></tr></tbody></table></div>

## French


<div dir="ltr" lang="fr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
D'après Al-Miqdâd Ibn Al-'Aswad (que Dieu l'agrée) J'ai dit à l'Envoyé de Dieu : "Figurez-vous que je me suis heurté à un polythéiste qui en m'ayant livré combat, m'amputerait la main avec son sabre, puis se réfugierait derrière un arbre où il prononcerait la profession de foi. Aurais-je droit à le tuer ou non (pour se venger) après qu'il eut prononcé la profession de foi?". L'Envoyé de Dieu (paix et bénédiction de Dieu sur lui) me répondit par le négatif. - "Mais, ai-je repris, il m'a coupé la main, et ce n'est qu'après cela qu'il a déclaré sa conversion à l'Islam. Pourrais-je donc le tuer?". - "Ne le tue pas, répéta l'Envoyé de Dieu, car si tu le tues, il sera dans l'état où tu étais avant de l'exécuter (musulman), et toi tu te trouveras dans celui où il était avant de se convertir (mécréant)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>274</td></tr><tr><td>Arabic No</td><td>95.01</td></tr><tr><td>Reference</td><td>Book 1 Hadith 180</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Qutaibah bin Sa'id] telah menceritakan kepada kami [Laits]. (dalam riwayat lain disebutkan) Dan telah menceritakan kepada kami [Muhammad bin Rumh] dan lafazh tersebut saling berdekatan kemiripannya. Telah mengabarkan kepada kami [Laits] dari [Ibnu Syihab] dari [Atha' bin Yazid al-Laitsi] dari [Ubaidullah bin Adi bin al-Khiyar] dari [al-Miqdad bin al-Aswad] bahwa dia mengabarkan kepadanya, bahwa dia berkata, "Wahai Rasulullah, apa pendapatmu seandainya aku berjumpa dengan seorang lelaki dari golongan orang-orang kafir, lalu mereka menyerangku dan memotong salah satu dari tanganku dengan pedangnya. Kemudian dia lari dariku dan berlindung di balik sepohon kayu', lalu orang yang melakukan itu berkata, 'Aku menyerahkan diri karena Allah. Wahai Rasulullah, apakah aku boleh membunuhnya setelah dia mengucapkan ungkapan itu (tauhid)? ' Rasulullah bersabda: "Janganlah kamu membunuhnya." Miqdad membantah, "Wahai Rasulullah! Lelaki itu telah memotong tanganku, dan setelah memotongnya ia (sengaja) mengucapkannya! Apakah aku boleh membunuhnya?" Rasulullah shallallahu 'alaihi wasallam menjawab: "Janganlah kamu membunuhnya, seandainya kamu membunuh lelaki itu, maka sungguh dia seperti kamu sebelum kamu membunuhnya, sedangkan kamu berkedudukan sepertinya sebelum dia mengucapkan perkataan tersebut (maksudnya kafir)." Telah menceritakan kepada kami [Ishaq bin Ibrahim] dan [Abd bin Humaid] keduanya berkata, telah mengabarkan kepada kami [Abdurrazzaq] dia berkata, telah mengabarkan kepada kami [Ma'mar]. (dalam riwayat lain disebutkan) Dan telah menceritakan kepada kami [Ishaq bin Musa al-Anshari] telah menceritakan kepada kami [al-Walid bin Muslim] dari [al-Auza'i]. (dalam riwayat lain disebutkan) Dan telah menceritakan kepada kami [Muhammad bin Rafi'] telah menceritakan kepada kami [Abdurrazzaq] telah mengabarkan kepada kami [Ibnu Juraij] semuanya dari [az-Zuhri] dengan sanad ini. Adapun al-Auza'i dan Ibnu Juraij, maka dalam hadits keduanya dia berkata, 'Saya menyerahkan diri kepada Allah' sebagaimana dikatakan al-Laits dalam haditsnya. Adapun Ma'mar, maka dalam haditsnya disebutkan, 'Ketika aku berkehendak untuk membunuhnya, maka dia berkata, 'Tidak ada tuhan (yang berhak disembah) kecuali Allah'." Dan telah menceritakan kepada kami [Harmalah bin Yahya] telah mengabarkan kepada kami [Ibnu Wahab] dia berkata, telah mengabarkan kepadaku [Yunus] dari [Ibnu Syihab] dia berkata, telah mengabarkan kepadaku [Atha' bin Yazid al-Laitsi al-Junda'i] bahwa [Abdullah bin Adi bin al-Khiyar] telah mengabarkan kepadanya, bahwa [al-Miqdad bin Amru bin al-Aswad al-Kindi] -dia adalah sekutu bani Zuhrah, dan dia termasuk sahabat yang ikut perang Badar bersama Rasulullah shallallahu 'alaihi wasallam- dia berkata, "Wahai Rasulullah, apa pendapatmu jika aku bertemu seorang laki-laki dari kalangan kafir? ' Kemudian dia menyebutkan sebagaimana hadits al-Laits
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>274</td></tr><tr><td>Arabic No</td><td>95.01</td></tr><tr><td>Reference</td><td>Book 1 Hadith 180</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
மிக்தாத் பின் அம்ர் அல்அஸ்வத் அல்கிந்தீ (ரலி) அவர்கள் கூறியதாவது: நான் (நபி (ஸல்) அவர்களிடம்) "இறை மறுப்பாளர்களில் ஒருவனை நான் சந்தித்தேன். அவன் என்னிடம் சண்டையிட்டான். அப்போது அவன் என் கைகளில் ஒன்றை வாளால் வெட்டித் துண்டித்துவிட்டான். பிறகு, அவன் என்னை விட்டு ஓடிப்போய் ஒரு மரத்தில் அபயம் தேடி (ஒளிந்து)கொண்டு, "அல்லாஹ்வுக்கு அடிபணிந்(து இஸ்லாத்தில் இணைந்)தேன்" என்று சொன்னான். இதை அவன் சொன்னதற்குப் பிறகு நான் அவனைக் கொல்லலாமா? அல்லாஹ்வின் தூதரே!" என்று கேட்டேன். அதற்கு அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள், "(வேண்டாம்) அவனைக் கொல்லாதே!" என்றார்கள். அதற்கு நான், "அல்லாஹ்வின் தூதரே! அவன் எனது கையைத் துண்டித்துவிட்டான். அதைத் துண்டித்த பிறகுதானே இதைச் சொன்னான்!" என்று கேட்டேன். அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள், "அவனை நீ கொல்லாதே! அவ்வாறு நீ அவனைக் கொன்றுவிட்டால் அவனைக் கொல்வதற்கு முன்பு நீயிருந்த (குற்றமற்ற) நிலைக்கு அவன் வந்து விடுவான். அந்த வார்த்தையைச் சொல்வதற்கு முன் அவனிருந்த (குற்றவாளி எனும்) நிலைக்கு நீ சென்றுவிடுவாய்" என்று கூறினார்கள். இந்த ஹதீஸ் இரு அறிவிப்பாளர்தொடர்களில் வந்துள்ளது. அத்தியாயம் : 1
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>274</td></tr><tr><td>Arabic No</td><td>95.01</td></tr><tr><td>Reference</td><td>Book 1 Hadith 180</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Bize Kuteybe b. Said tahdis etti. Bize Leys tahdis etti. (H) Bize Muhammed b. Rumh da tahdis etti -ki lafızlar birbirine yakındır.- Bize Leys, İbn Şihab'dan haber verdi. O Ata b. Yezid el-Leysi'den, o Ubeydullah b. Adiyy b. el-Hiyar'dan, o Mikdad el-Esved'den rivayet ettiğine göre kendisine şöyle dediğini haber vermiştir: Ey Allah'ın Resulü ne dersin kafirlerden bir adamla karşılaşsam, benimle çarpışsa, kılıçla ellerimden birini vurup kesse sonra benden (kaçıp) bir ağaca sığınsa, arkasından da: Allah için ben Müslüman oldum dese, o bu sözü söyledikten sonra onu öldürebilir miyim, ey Allah'ın Resulü? Resulullah (Sallallahu aleyhi ve Sellem): "Hayır, onu öldürme" buyurdu. Ben: Ey Allah'ın Resulü, ama o önce benim elimi kesti. Onu kestikten sonra bu sözü söyledi, onu öldüreyim mi, dedim. Resulullah (Sallallahu aleyhi ve Sellem) şöyle buyurdu: "Hayır, onu öldürme. Onu öldürecek olursan o vakit o, sen kendisini öldürmeden önceki senin konumunda olur ve sen de söylediği o sözden önceki onun konumunda olursun. " Diğer tahric: Buhari, 3794, 6472; Ebu Davud, 2644; Tuhfetu'l-Eşraf, 11547
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>274</td></tr><tr><td>Arabic No</td><td>95.01</td></tr><tr><td>Reference</td><td>Book 1 Hadith 180</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ليث نے ابن شہاب ( زہری ) سے ، انہوں نے عطاء بن یزید لیثی سے روایت کی کہ مقداد بن اسود ‌رضی ‌اللہ ‌عنہ ‌ ‌ نے عبید اللہ بن عدی بن خیار کو خبر دی کہ انہوں نے عرض کی : اے اللہ کے رسول ! مجھے بتائیے کہ اگرکافروں میں سے کسی شخص سے میرا سامنا ہو ، وہ مجھے سے جنگ کرے اور میرے ایک ہاتھ تلوار کی ضرب لگائے اور اسے کاٹ ڈالے ، پھر مجھ سے بچاؤ کے لیے کسی درخت کی آڑ لے اور کہے : میں نے اللہ کے لیے اسلام قبول کر لیا تو اے اللہ کے رسول ! کیا یہ کلمہ کہنے کے بعد میں اسے قتل کردوں ؟ رسول اللہﷺ نے فرمایا : ’’اسے قتل نہ کرو ۔ ‘ ‘ انہوں نے کہا : میں نے عرض کی : اے اللہ ک ےرسول ! اس نے میرا ہاتھ کاٹ دیا اور اسے کاٹ ڈالنے کے بعد یہ کلمہ کہے تو کیا میں اسے قتل کر دوں ؟ رسول اللہ ﷺ نے فرمایا : ’’اسے قتل نہ کرو ۔ اگر تم نے اسے قتل کر دیا تو وہ تمہارے اس مقام پر ہو گا جس پر تم اسے قتل کرنے سےپہلے تھے اور تم اس جگہ ہو گے جہاں وہ کلمہ کہنے سے پہلے تھا ۔ ‘ ‘
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>274</td></tr><tr><td>Arabic No</td><td>95.01</td></tr><tr><td>Reference</td><td>Book 1 Hadith 180</td></tr></tbody></table></div>