## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
وَحَدَّثَنَا يَحْيَى بْنُ يَحْيَى، قَالَ قَرَأْتُ عَلَى مَالِكِ بْنِ أَنَسٍ عَنْ إِسْحَاقَ بْنِ عَبْدِ، اللَّهِ بْنِ أَبِي طَلْحَةَ أَنَّهُ سَمِعَ أَنَسَ بْنَ مَالِكٍ، يَقُولُ قَالَ أَبُو طَلْحَةَ لأُمِّ سُلَيْمٍ قَدْ سَمِعْتُ صَوْتَ، رَسُولِ اللَّهِ صلى الله عليه وسلم ضَعِيفًا أَعْرِفُ فِيهِ الْجُوعَ فَهَلْ عِنْدَكِ مِنْ شَىْءٍ فَقَالَتْ نَعَمْ ‏.‏ فَأَخْرَجَتْ أَقْرَاصًا مِنْ شَعِيرٍ ثُمَّ أَخَذَتْ خِمَارًا لَهَا فَلَفَّتِ الْخُبْزَ بِبَعْضِهِ ثُمَّ دَسَّتْهُ تَحْتَ ثَوْبِي وَرَدَّتْنِي بِبَعْضِهِ ثُمَّ أَرْسَلَتْنِي إِلَى رَسُولِ اللَّهِ صلى الله عليه وسلم قَالَ فَذَهَبْتُ بِهِ فَوَجَدْتُ رَسُولَ اللَّهِ صلى الله عليه وسلم جَالِسًا فِي الْمَسْجِدِ وَمَعَهُ النَّاسُ فَقُمْتُ عَلَيْهِمْ فَقَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏"‏ أَرْسَلَكَ أَبُو طَلْحَةَ ‏"‏ ‏.‏ قَالَ فَقُلْتُ نَعَمْ ‏.‏ فَقَالَ ‏"‏ أَلِطَعَامٍ ‏"‏ ‏.‏ فَقُلْتُ نَعَمْ ‏.‏ فَقَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم لِمَنْ مَعَهُ ‏"‏ قُومُوا ‏"‏ ‏.‏ قَالَ فَانْطَلَقَ وَانْطَلَقْتُ بَيْنَ أَيْدِيهِمْ حَتَّى جِئْتُ أَبَا طَلْحَةَ فَأَخْبَرْتُهُ فَقَالَ أَبُو طَلْحَةَ يَا أُمَّ سُلَيْمٍ قَدْ جَاءَ رَسُولُ اللَّهِ صلى الله عليه وسلم بِالنَّاسِ وَلَيْسَ عِنْدَنَا مَا نُطْعِمُهُمْ فَقَالَتِ اللَّهُ وَرَسُولُهُ أَعْلَمُ - قَالَ - فَانْطَلَقَ أَبُو طَلْحَةَ حَتَّى لَقِيَ رَسُولَ اللَّهِ صلى الله عليه وسلم فَأَقْبَلَ رَسُولُ اللَّهِ صلى الله عليه وسلم مَعَهُ حَتَّى دَخَلاَ فَقَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏"‏ هَلُمِّي مَا عِنْدَكِ يَا أُمَّ سُلَيْمٍ ‏"‏ ‏.‏ فَأَتَتْ بِذَلِكَ الْخُبْزِ فَأَمَرَ بِهِ رَسُولُ اللَّهِ صلى الله عليه وسلم فَفُتَّ وَعَصَرَتْ عَلَيْهِ أُمُّ سُلَيْمٍ عُكَّةً لَهَا فَأَدَمَتْهُ ثُمَّ قَالَ فِيهِ رَسُولُ اللَّهِ صلى الله عليه وسلم مَا شَاءَ اللَّهُ أَنْ يَقُولَ ثُمَّ قَالَ ‏"‏ ائْذَنْ لِعَشَرَةٍ ‏"‏ ‏.‏ فَأَذِنَ لَهُمْ فَأَكَلُوا حَتَّى شَبِعُوا ثُمَّ خَرَجُوا ثُمَّ قَالَ ‏"‏ ائْذَنْ لِعَشَرَةٍ ‏"‏ ‏.‏ فَأَذِنَ لَهُمْ فَأَكَلُوا حَتَّى شَبِعُوا ثُمَّ خَرَجُوا ثُمَّ قَالَ ‏"‏ ائْذَنْ لِعَشَرَةٍ ‏"‏ ‏.‏ حَتَّى أَكَلَ الْقَوْمُ كُلُّهُمْ وَشَبِعُوا وَالْقَوْمُ سَبْعُونَ رَجُلاً أَوْ ثَمَانُونَ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5316</td></tr><tr><td>Arabic No</td><td>2040.01</td></tr><tr><td>Reference</td><td>Book 36 Hadith 190</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
হাদিস একাডেমি নাম্বারঃ ৫২১১, আন্তর্জাতিক নাম্বারঃ ২০৪০ ৫২১১-(১৪২/২০৪০) ইয়াহইয়া ইবনু ইয়াহইয়া (রহঃ) ..... আনাস ইবনু মালিক (রাযিঃ) হতে বর্ণিত। তিনি বলেন, (একদা) আবূ তালহাহ (রাযিঃ) উম্মু সুলায়ম (রাযিঃ) কে বললেন, আমি রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর দুর্বল শব্দ শ্রবণ করে বুঝতে পেরেছি যে, তিনি ক্ষুধার্ত। তাই তোমার কাছে কিছু আছে কি? তিনি বললেন, হ্যাঁ। তিনি যবের কয়েক খন্ড রুটি বের করলেন। তারপর তার ওড়না নিলেন এবং এটির একাংশ দিয়ে রুটিগুলো পেচিয়ে আমার কাপড়ের তলায় গুজে দিলেন এবং অপর অংশ আমার দেহে জড়িয়ে দিলেন। অতঃপর আমাকে রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর কাছে প্রেরণ করলেন। তিনি (আনাস) বলেন, আমি এগুলো নিয়ে এসে রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম কে দেখতে পেলাম তিনি মসজিদে বসে আছেন। তার সাথে আরো মানুষ ছিলেন। আমি তাদের নিকট গিয়ে দাঁড়ালাম। রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বললেনঃ তোমাকে আবূ তালহাহ প্রেরণ করেছে? আমি বললাম, হ্যাঁ। তিনি বললেন, খাওয়ার ব্যাপারে? আমি বললাম, হ্যাঁ। তারপর রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম তার সাথীদের বললেন, সবাই চলো। আনাস (রাযিঃ) বলেন, তারপর রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম গেলেন। আর আমি তাদের সামনে চলতে লাগলাম। পরিশেষে আমি আবূ তালহাহ্ (রাযিঃ)-এর কাছে এসে তাকে (ঘটনা) খবর দিলাম। তখন আবূ তালহাহ (রাযিঃ) বললেন, হে উম্মু সুলায়ম (রাযিঃ)! রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম তো লোকদের নিয়ে আসছেন, অথচ আমাদের কাছে সে পরিমাণ খাদ্য নেই যা দিয়ে তাদের আপ্যায়ন করতে পারি। উম্মু সুলায়ম (রাযিঃ) বললেন, (তুমি উদ্বিগ্ন হয়ে না) আল্লাহ এবং তার রসূলই ভাল জানেন। আনাস (রাযিঃ) বলেন, তারপর আবূ তালহাহ্ (রাযিঃ) যেয়ে রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর সাথে দেখা করলেন। রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম তার সাথে এসে (উভয়ে) ঘরে ঢুকলেন। রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম উম্মু সুলায়ম (রাযিঃ)-কে লক্ষ্য করে বললেন, হে উম্মু সুলায়ম! তোমার কাছে যা আছে নিয়ে আসো। তিনি সে রুটিগুলো তার সাথে করে নিয়ে আসলেন। রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম নির্দেশ দান করলে সেগুলো টুকরা টুকরা করা হলো। আর উম্মু সুলায়ম (রাযিঃ) চামড়া দ্বারা তৈরি ঘি-এর পাত্রটি চিপে সেটি সালুন হিসেবে দিলেন। আর এর ভিতরে রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম আল্লাহর ইচ্ছানুযায়ী কিছু পড়লেন। অতঃপর বললেন, দশজনকে আসতে বলো। তাদের ডাকা হলে তারা এসে তৃপ্তির সাথে খাবার খেয়ে বেরিয়ে গেলেন। অতঃপর তিনি বললেন, আরো দশজনকে আসতে বলে। তাদের ডাকা হলে তারা পেট ভরে খেয়ে চলে গেলেন। পুনরায় তিনি বললেন, দশজনকে ডাক। এভাবে দলের সকলে পেটপুরে খাবার খেলেন। সত্তর কিংবা আশিজন লোক তাদের দলে ছিল। (ইসলামিক ফাউন্ডেশন ৫১৪৩, ইসলামিক সেন্টার ৫১৫৫)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5316</td></tr><tr><td>Arabic No</td><td>2040.01</td></tr><tr><td>Reference</td><td>Book 36 Hadith 190</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Anas b. Malik reported that Abu Talha said to Umm Sulaim:I felt some feebleness in the voice of Allah's Messenger (ﷺ) and perceived that it was due to hunger; so have you anything with you? She said: Yes. She brought out barley loaves, then took out a head-covering of hers, in a part of which she wrapped those loaves and then put them beneath my mantle and covered me with a part of it. She then sent me to Allah's Messenger (ﷺ). I set forth and found Allah's Messenger (ﷺ) sitting in the mosque in the company of some persons. I stood near them, whereupon Allah's Messenger (ﷺ) said: Has Abu Talha sent you? I said, Yes. He said: Is it for a feast? I said. Yes. Thereupon Allah's messenger (ﷺ) said to'those who were with him to get up He went forth and so I did before them, until I came to Abu Talha and informed him. Abu Talba said: Umm Sulaim, here comes Allah's Messenger (ﷺ) along with people and we do not have enough (food) to feed them. She said: Allah and His Messenger know best. Abu Talha went out (to receive him) Until he met Allah's Messenger (ﷺ) and Allah's Apostle (ﷺ) came forward along with him until they both (Allah's Messenger, along with Abu Talha) came in. Then Allah's Messenger (ﷺ) said: Umm Sulaim. bring forth that which you have with you. She brought the bread. Allah's Messenger (ﷺ) commanded that the bread be broken into small pieces, and when Umm Sulaim had squeezed a small waterskin and put seasoning on it, Allah's Messenger (ﷺ) recited something regarding it what Allah wished him to say. He then said: Allow ten (guests to come in and have their meals). He permitted them; they ate until they had their fill. They then went out. He (the Holy Prophet) again said: Permit ten (more) and he (the host gave permission to them. They ate until they had enough. Then they went out. he again said: Permit ten (more) until all the people had eaten to their fill, and they were seventy or eighty persons
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5316</td></tr><tr><td>Arabic No</td><td>2040.01</td></tr><tr><td>Reference</td><td>Book 36 Hadith 190</td></tr></tbody></table></div>

## French


<div dir="ltr" lang="fr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>

</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5316</td></tr><tr><td>Arabic No</td><td>2040.01</td></tr><tr><td>Reference</td><td>Book 36 Hadith 190</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Yahya bin Yahya] dia berkata; Aku mebaca Hadits [Malik bin Anas] dari [Ishaq bin 'Abdullah bin Abu Thalhah]; Bahwasanya dia mendengar [Anas bin Malik] berkata; Abu Thalhah berkata kepada Ummu Sulaim; "Aku mendengar suara Rasulullah shallallahu 'alaihi wasallam sangat lemah, yang aku tahu bahwa beliau sangat lapar. Apakah kamu mempunyai sesuatu?" Dia menjawab; 'Ya.' Kemudian dia mengeluarkan beberapa roti pipih dari gandum, lalu meraih kerudungnya. Kemudian dia menyusupkan ke bawah tanganku, dan menyelendangkan kerudungnya (yang berisi roti). Dia mengutusku kepada Rasulullah shallallahu 'alaihi wasallam. Anas berkata; 'Aku membawanya menemui Rasulullah shallallahu 'alaihi wasallam. Aku mendapati beliau sedang duduk di masjid bersama para sahabat. Aku berdiri di hadapan mereka. Rasulullah shallallahu 'alaihi wasallam bertanya: 'Apakah Abu Thalhah yang menyuruhmu? ' Anas menjawab; 'Ya', Beliau bertanya: 'Untuk membawakan makanan? ' Aku menjawab; 'Ya, ' maka Rasulullah shallallahu 'alaihi wasallam berkata kepada orang-orang yang sedang bersamanya; 'Berdirilah! ' Anas berkata; 'Beliau berangkat dan aku berada di bagian depan mereka, hingga aku menemui Abu Thalhah dan mengabarkan hal itu.' Abu Thalhah berkata; 'Wahai Ummu Sulaim, Rasulullah shallallahu 'alaihi wasallam datang bersama orang-orang, sedangkan kita tidak memiliki makanan yang cukup untuk menjamu mereka? ' Ummu Sulaim menjawab; 'Allah dan Rasul-Nya lebih mengetahui.' Anas berkata; 'Abu Thalhah menemui Rasulullah shallallahu 'alaihi wasallam. Beliau tiba dan Abu Thalhah menghampiri beliau hingga memasuki rumahnya. Rasulullah shallallahu 'alaihi wasallam bersabda: 'Kemarilah, Wahai Ummu Sulaim, apa yang kau miliki? ' Dia datang dengan membawa roti itu, kemudian Rasulullah shallallahu 'alaihi wasallam memerintahkan agar roti tersebut dilumatkan. Roti pun dilumatkan dan Ummu Sulaim menuangkan minyak samin pada wadah tersebut. Sehingga menjadi lauk. Rasulullah shallallahu 'alaihi wasallam mengucapkan beberapa kalimat lalu bersabda: 'Persilahkan sepuluh orang untuk masuk.' Abu Thalhah mempersilahkan mereka. Mereka menyantapnya hingga kenyang kemudian keluar. Beliau bersabda: 'Persilahkan sepuluh orang untuk masuk.' Abu Thalhah mempersilahkan mereka, dan mereka menyantapnya hingga kenyang kemudian keluar. Kemudian beliau bersabda: 'Persilahkan sepuluh orang untuk masuk.' Hingga mereka mereka bisa makan dan kenyang. Jumlah mereka ada tujuh puluh orang atau delapan puluh orang
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5316</td></tr><tr><td>Arabic No</td><td>2040.01</td></tr><tr><td>Reference</td><td>Book 36 Hadith 190</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
அனஸ் பின் மாலிக் (ரலி) அவர்கள் கூறியதாவது: அபூதல்ஹா (ரலி) அவர்கள் (தம் துணைவியும் என் தாயாருமான) உம்மு சுலைம் (ரலி) அவர்களிடம், "நான் அல்லாஹ்வின் தூதர் (ஸல்) அவர்களது குரலைப் பலவீனமானதாகக் கேட்டேன். அதில் நான் (அவர்களுக்கு இருக்கும்) பசியைப் புரிந்து கொண்டேன். உன்னிடம் (உணவு) ஏதேனும் இருக்கிறதா?" என்று கேட்டார்கள். அதற்கு உம்மு சுலைம் (ரலி) அவர்கள், "ஆம் (இருக்கிறது)" என்று கூறிவிட்டு, தொலி நீக்கப்படாத கோதுமை(யில் தயாரித்த) ரொட்டிகள் சிலவற்றை எடுத்தார்கள். பிறகு அவர்கள் தமது துப்பட்டா ஒன்றை எடுத்து, அதன் ஒரு பகுதியில் அந்த ரொட்டிகளைச் சுற்றி எனது ஆடைக்குள் திணித்துவிட்டு, அதன் மற்றொரு பகுதியை எனக்கு மேல்துண்டாகப் போர்த்திவிட்டார்கள். பிறகு என்னை அல்லாஹ்வின் தூதர் (ஸல்) அவர்களிடம் அனுப்பினார்கள். நான் அதைக் கொண்டுசென்றேன். அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் பள்ளிவாசலில் அமர்ந்திருப்பதைக் கண்டேன். அவர்களுடன் மக்களும் இருந்தனர். நான் (சென்று) அவர்களுக்கு முன்னால் நின்றேன். அப்போது அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் (என்னிடம்), "உன்னை அபூதல்ஹா அனுப்பினாரா?" என்று கேட்டார்கள். நான் "ஆம்" என்றேன். "உணவு உண்ணவா?" என்று கேட்டார்கள். நான் "ஆம்" என்றேன். அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் தம்முடன் இருந்தவர்களிடம் "எழுந்திருங்கள்" என்று சொல்லிவிட்டு, (என் இல்லம் நோக்கி) நடக்கலானார்கள். நான் அவர்களுக்கு முன்னால் நடந்தேன். அபூதல்ஹா (ரலி) அவர்களிடம் நான் சென்று (அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் தம் தோழர்களுடன் வந்துகொண்டிருக்கும்) விவரத்தைத் தெரிவித்தேன். உடனே அபூதல்ஹா (ரலி) அவர்கள் (என் தாயாரிடம்), "உம்மு சுலைம்! அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் மக்களுடன் வந்துவிட்டார்கள். ஆனால், அவர்களுக்கு வேண்டிய உணவு நம்மிடம் இல்லையே!" என்று சொன்னார்கள். உம்மு சுலைம் (ரலி) அவர்கள் "அல்லாஹ்வும் அவனுடைய தூதருமே அறிந்தவர்கள்" என்று கூறினார்கள். அபூதல்ஹா (ரலி) அவர்கள் (தாமே அல்லாஹ்வின் தூதர் (ஸல்) அவர்களை வரவேற்பதற்காக) நடந்து சென்று, அல்லாஹ்வின் தூதர் (ஸல்) அவர்களைச் சந்தித்தார்கள். பிறகு அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் அபூதல்ஹா (ரலி) அவர்களுடன் வீட்டுக்குள் நுழைந்தார்கள். பிறகு அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள், "உம்மு சுலைம்! உம்மிடம் இருப்பதைக் கொண்டுவா" என்று சொல்ல, உம்மு சுலைம் (ரலி) அவர்கள் அந்த ரொட்டியைக் கொண்டுவந்தார்கள். அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் (அதைத் துண்டு துண்டாகப் பிய்க்கும்படி) உத்தரவிட, அவ்வாறே அது பிய்க்கப்பட்டது. உம்மு சுலைம் (ரலி) அவர்கள், தம்மிடமிருந்த தோல் பையிலிருந்து வெண்ணெய் எடுத்துப் பிழிந்து அதை (உருக்கி)க் குழம்பு செய்தார்கள். பிறகு அதில் அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் இறைவன் நாடிய (பிராத்தனை வரிகள் சில)வற்றைச் சொன்னார்கள். பிறகு "பத்துப் பேருக்கு (உள்ளே வர) அனுமதி அளியுங்கள்" என்று (அபூதல்ஹா (ரலி) அவர்களிடம்) சொன்னார்கள். அவ்வாறே அவர்களுக்கு அபூதல்ஹா (ரலி) அவர்கள் அனுமதி அளித்தார்கள். அவர்கள் (பத்துப் பேர்) வந்து வயிறார உண்டுவிட்டு வெளியேறினார்கள். பின்னர், "இன்னும் பத்துப் பேருக்கு அனுமதி அளியுங்கள்" என்று அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் கூற,அபூதல்ஹா (ரலி) அவர்களும் அனுமதியளித்தார்கள். அவர்களும் வயிறார உண்டுவிட்டு வெளியேறினார்கள். பிறகு "இன்னும் பத்துப் பேருக்கு அனுமதி அளியுங்கள்" என்றார்கள். (இவ்வாறு வந்திருந்த) மக்கள் அனைவரும் வயிறார உண்டார்கள். அப்படி உண்ட மக்கள் எழுபது அல்லது எண்பது பேர் ஆவர். அத்தியாயம் : 36
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5316</td></tr><tr><td>Arabic No</td><td>2040.01</td></tr><tr><td>Reference</td><td>Book 36 Hadith 190</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Bize Yahya b. Yahya rivayet etti. (Dediki): Mâlik b. Enes'e, İshâk b. Abdillah b. Ebî Talha'dan dinlediğim, onun da Enes b. Mâlik'den dinlediği şu hadîsi okudum: Enes şöyle diyormuş: Ehû Taİha Ümmü Süleym'e dediki: Ben ResûlulIah (Sallallahu Aleyhi ve Sellem)'in sesini zayıf işittim. Onda açlık olduğunu biliyorum. Senin yanında bir şey var mı? Ümmü Süleym: — Evet! dedi ve arpa ekmeğinden birkaç parça çıkardı. Sonra kendisinin bir baş örtüsünü alarak bir kısmına ekmeği sardı, sonra onu benim elbisemin altına tıktı. Bir kısmıyla da beni sardı. Sonra beni Resûlullah (Sallallahu Aleyhi ve Sellem)'e gönderdi. Ben ekmeği götürdüm ve Resûlullah (Sallallahu Aleyhi ve Sellem) mescidde otururken buldum. Beraberinde cemaat vardı. Başlarında durdum. Resûlullah (Sallallahu Aleyhi ve Sellem): «Seni Ebû Talha mı gönderdi?» diye sordu. — Evet! dedim. «Yemek için mi?» dedi. — Evet! cevâbını verdim. Bunun üzerine Resûlullah (Sallallahu Aleyhi ve Sellem) beraberindekilere ; «Kalkın!» dedi ve yürüdü. Ben de önlerinde yürüdüm ve Ebû Talha'ya gelerek ona haber verdim. Ebû Talha: — Ey Ümmü Süleym! Resûlullah (Sallallahu Aleyhi ve Sellem) cemaatla geldi. Halbuki bizde onları doyuracak bir şey yoktur, dedi. Ümmü Süleym : — Allah ve Resulü bilir, cevâbını verdi. Derken Ebû Talha giderek, Resûlullah (Sallallahu Aleyhi ve Sellem)'in huzuruna çıktı. Resûlullah (Sallallahu Aleyhi ve Sellem) de onunla beraber gelerek eve girdiler. Müteakiben Resûlullah (Sallallahu Aleyhi ve Sellem), «Nen varsa getir, ya Ümmü Süleym!» dedi. O da bu ekmeği getirdi. Resûlullah (Sallallahu Aleyhi ve Sellem) emir buyurarak ekmeği parçalattı. Üzerine de Ümmü Süleym tulumundan yağ sıkarak onu katıklattı. Sonra bu ekmek hakkında Resûlullah (Sallallahu Aleyhi ve Sellem) Allah ne dilediyse onu söyledi. Sonra : «On kişiye izin ver!» dedi. Ebû Talha da onlara izin verdi. Ve yediler. Nihayet doydular, sonra çıktılar. Sonra (tekrar) ; «On kişiye izin ver!» buyurdu. Böylece cemaatın hepsi yediler ve doydular. Bu cemâat yetmiş yahut seksen kişi idi
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5316</td></tr><tr><td>Arabic No</td><td>2040.01</td></tr><tr><td>Reference</td><td>Book 36 Hadith 190</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
اسحاق بن عبداللہ بن ابی طلحہ نے کہا کہ انھوں نے حضرت انس بن مالک رضی اللہ تعالیٰ عنہ سے سنا ، وہ کہہ رہے تھے : حضرت ابو طلحۃ رضی اللہ تعالیٰ عنہ نے حضرت سلیم رضی اللہ تعالیٰ عنہا سے کہا : میں نے رسول اللہ صلی اللہ علیہ وسلم کی آواز سنی ہے کمزورتھی ۔ مجھے محسوس ہوتا ہے کہ آپ صلی اللہ علیہ وسلم کو بھوک لگی ہے ۔ کیا تمہارے پاس کوئی چیز ہے؟انھوں نے کہا : ہاں ، پھر انھوں نے جو کی کچھ روٹیاں نکالیں ، پھر اپنی اوڑھنی لی اس کے ایک حصے میں روٹیاں لپیٹیں ، پھر ان کو میرے کپڑوں کےنیچے چھپاد یا اور اس ( اوڑھنی ) کا بقیہ حصہ چادر کی طرح میرے اوپر ڈال دیا ، پھر مجھے رسول اللہ صلی اللہ علیہ وسلم کی خدمت میں بھیج دیا ۔ حضرت انس رضی اللہ تعالیٰ عنہ نے کہا : میں ان روٹیوں کو لے کر گیا ، میں نے رسول اللہ صلی اللہ علیہ وسلم کو مسجد میں بیٹھے پایا اور آپ کےساتھ دوسرے لوگ موجود تھے ، میں ان کے پا کھڑا ہوگیا ، رسول اللہ صلی اللہ علیہ وسلم نے فرمایا : "" تمھیں ابو طلحہ رضی اللہ تعالیٰ عنہ نے بھیجا ہے؟ "" میں نے عرض کی : جی ہاں ۔ آپ صلی اللہ علیہ وسلم نے فرمایا : "" کیا کھانے کے لئے؟ "" میں نے کہا : جی ہاں ۔ رسول اللہ صلی اللہ علیہ وسلم نے ا پنے ساتھیوں سے کہا "" چلو "" حضرت انس رضی اللہ تعالیٰ عنہ نے کہا حضور صلی اللہ علیہ وسلم روانہ ہوئے اور میں ا ن کے آگے آگے چل پڑا ، یہاں تک کہ میں حضرت ابو طلحہ رضی اللہ تعالیٰ عنہ کے پاس آیا اور ان کو بتایا ۔ حضرت ابو طلحۃ رضی اللہ تعالیٰ عنہ کہنے لگے : ام سلیم!رسول اللہ صلی اللہ علیہ وسلم ( باقی ) لوگوں سمیت آگئے ہیں ، اور ہمارے پاس اتنا ( کھانا ) نہیں ہے کہ ان کو کھلا سکیں ۔ انھوں نے کہا : اللہ اور اسکا رسول صلی اللہ علیہ وسلم زیادہ جاننے والے ہیں ۔ حضرت انس رضی اللہ تعالیٰ عنہ نے کہا : پھر حضرت ابو طلحۃ رضی اللہ تعالیٰ عنہ آگے بڑھے اور ( جاکر ) رسول اللہ صلی اللہ علیہ وسلم سے ملے ۔ رسول اللہ صلی اللہ علیہ وسلم ان کےساتھ آئے اور وہ دونوں گھر میں داخل ہوگئے ، رسول اللہ صلی اللہ علیہ وسلم نے فرمایا : "" ام سلیم!جو کچھ تمہارے پاس ہے وہ لے آؤ ۔ "" وہ یہی روٹیاں لے آئیں ، رسول اللہ صلی اللہ علیہ وسلم نے ان کے بارے میں حکم دیا ، ان ( روٹیوں ) کے چھوٹے چھوٹے ٹکڑے کردیئے گئے ۔ ام سلیم رضی اللہ تعالیٰ عنہا نے ا پنا گھی کا کپہ ( چمڑے کا گول برتن ) ان ( روٹیوں ) پر نچوڑ کر سالن شامل کردیا ، پھر رسول اللہ صلی اللہ علیہ وسلم نے اس میں جو کچھ اللہ نے چاہا پڑھا ، پھر آپ صلی اللہ علیہ وسلم نےفرمایا : "" دس آدمیوں کو آنے کی اجازت دو ۔ "" انھوں ( ابوطلحہ رضی اللہ تعالیٰ عنہ ) نے دس آدمیوں کو اجازت دی ، انھوں نے کھانا کھایا حتیٰ کہ سیر ہوگئے اور باہر چلے گئے ، آپ صلی اللہ علیہ وسلم نے پھر فرمایا : "" دس آدمیوں کو اجازت دو ۔ "" انھوں نے اجازت دی ، ان سب نے کھایا سیر ہوگئے اور باہر چلے گئے ، آپ صلی اللہ علیہ وسلم نے پھر فرمایا : "" دس آدمیوں کو اجازت دو "" یہاں تک کہ سب لوگوں نے کھا لیا اورسیر ہوگئے ۔ وہ ستر یا اسی لوگ تھے ۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5316</td></tr><tr><td>Arabic No</td><td>2040.01</td></tr><tr><td>Reference</td><td>Book 36 Hadith 190</td></tr></tbody></table></div>