## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا أَبُو بَكْرِ بْنُ أَبِي شَيْبَةَ، حَدَّثَنَا وَكِيعٌ، ح وَحَدَّثَنَا عُبَيْدُ اللَّهِ بْنُ مُعَاذٍ، حَدَّثَنَا أَبِي كِلاَهُمَا، عَنْ شُعْبَةَ، ح وَحَدَّثَنَا مُحَمَّدُ بْنُ الْمُثَنَّى، وَمُحَمَّدُ بْنُ بَشَّارٍ، - وَاللَّفْظُ لاِبْنِ الْمُثَنَّى - قَالاَ حَدَّثَنَا مُحَمَّدُ بْنُ جَعْفَرٍ، حَدَّثَنَا شُعْبَةُ، عَنِ الْمُغِيرَةِ بْنِ النُّعْمَانِ، عَنْ سَعِيدِ بْنِ جُبَيْرٍ، عَنِ ابْنِ عَبَّاسٍ، قَالَ قَامَ فِينَا رَسُولُ اللَّهِ صلى الله عليه وسلم خَطِيبًا بِمَوْعِظَةٍ فَقَالَ ‏"‏ يَا أَيُّهَا النَّاسُ إِنَّكُمْ تُحْشَرُونَ إِلَى اللَّهِ حُفَاةً عُرَاةً غُرْلاً ‏(‏ كَمَا بَدَأْنَا أَوَّلَ خَلْقٍ نُعِيدُهُ وَعْدًا عَلَيْنَا إِنَّا كُنَّا فَاعِلِينَ‏)‏ أَلاَ وَإِنَّ أَوَّلَ الْخَلاَئِقِ يُكْسَى يَوْمَ الْقِيَامَةِ إِبْرَاهِيمُ عَلَيْهِ السَّلاَمُ أَلاَ وَإِنَّهُ سَيُجَاءُ بِرِجَالٍ مِنْ أُمَّتِي فَيُؤْخَذُ بِهِمْ ذَاتَ الشِّمَالِ فَأَقُولُ يَا رَبِّ أَصْحَابِي ‏.‏ فَيُقَالُ إِنَّكَ لاَ تَدْرِي مَا أَحْدَثُوا بَعْدَكَ ‏.‏ فَأَقُولُ كَمَا قَالَ الْعَبْدُ الصَّالِحُ ‏(‏ وَكُنْتُ عَلَيْهِمْ شَهِيدًا مَا دُمْتُ فِيهِمْ فَلَمَّا تَوَفَّيْتَنِي كُنْتَ أَنْتَ الرَّقِيبَ عَلَيْهِمْ وَأَنْتَ عَلَى كُلِّ شَىْءٍ شَهِيدٌ * إِنْ تُعَذِّبْهُمْ فَإِنَّهُمْ عِبَادُكَ وَإِنْ تَغْفِرْ لَهُمْ فَإِنَّكَ أَنْتَ الْعَزِيزُ الْحَكِيمُ‏)‏ قَالَ فَيُقَالُ لِي إِنَّهُمْ لَمْ يَزَالُوا مُرْتَدِّينَ عَلَى أَعْقَابِهِمْ مُنْذُ فَارَقْتَهُمْ ‏"‏ ‏.‏ وَفِي حَدِيثِ وَكِيعٍ وَمُعَاذٍ ‏"‏ فَيُقَالُ إِنَّكَ لاَ تَدْرِي مَا أَحْدَثُوا بَعْدَكَ ‏"‏ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>7201</td></tr><tr><td>Arabic No</td><td>2860.02</td></tr><tr><td>Reference</td><td>Book 53 Hadith 70</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
হাদিস একাডেমি নাম্বারঃ ৭০৯৩, আন্তর্জাতিক নাম্বারঃ ২৮৬০ ৭০৯৩-(৫৮/…) আবূ বাকর ইবনু আবূ শাইবাহ, উবাইদুল্লাহ ইবনু মুআয, মুহাম্মাদ ইবনুল মুসান্না ও মুহাম্মাদ ইবনু বাশশার (রহঃ) ..... ইবনু আব্বাস (রাযিঃ) থেকে বর্ণিত। তিনি বলেন, উপদেশ সম্বলিত ভাষণ প্রদানের উদ্দেশে রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম আমাদের মাঝে দাঁড়িয়ে বললেন, হে লোক সকল! তোমরা আল্লাহর সামনে খালি পা এবং উলঙ্গদেহে এবং খাতনাবিহীন অবস্থায় উপস্থিত হবে। (আল্লাহর বাণী) "যেমন আমি প্রথম দিন সৃষ্টি শুরু করেছিলাম, তেমনি তার পুনরাবৃত্তি করব। এটা আমার একটা ওয়াদা, তা পালন করা আমার দায়িত্বের অন্তর্ভুক্ত। আমি তা পালনে বদ্ধপরিকর।" সাবধান! কিয়ামতের দিন সৃষ্টির মাঝে সর্বপ্রথম ইবরাহীম (আঃ) কে পোশাক পরিধান করানো হবে, সেদিন আমার উম্মাতের মধ্য থেকে কিছু মানুষকে হাযির করা হবে, এদের মধ্যে যারা বাম হাতে আমলনামা প্রাপ্ত তাদের পাকড়াও করা হবে। তখন আমি বলব, হে আমার রব! এরা তো আমার উম্মাত। উত্তরে আমাকে বলা হবে, তুমি জানো না তোমার পরে এরা কি কার্যকলাপে জড়িত ছিল। আমি তখন আল্লাহর সৎ বান্দা ঈসা (আঃ) এর ন্যায় বলব, "যতদিন আমি তাদের মাঝে ছিলাম ততদিন আমি ছিলাম তাদের কার্যকলাপের সাক্ষী; কিন্তু যখন তুমি আমাকে তুলে নিলে তখন তুমিই তো ছিলে তাদের কার্যকলাপের পর্যবেক্ষণকারী এবং তুমিই সর্ব বিষয়ে সাক্ষী, তুমি যদি তাদেরকে শাস্তি দাও তবে তারা তো তোমারই বান্দা, আর যদি তাদেরকে মাফ করো তবে তুমি তো পরাক্রমশালী, প্রজ্ঞাময়।” তখন আমাকে বলা হবে, তুমি তাদের থেকে বিদায় গ্রহণের পর থেকে তারা সবসময় মুখ ফিরিয়ে কুফুরীর আশ্রয় নিয়েছিল। ওয়াকী এবং মুআয এর হাদীসের মধ্যে রয়েছে فَيُقَالُ إِنَّكَ لاَ تَدْرِي مَا أَحْدَثُوا بَعْدَكَ অতঃপর বলা হবে, আপনি অবশ্য জানেন না আপনার পরে তারা কোন নতুন ধর্মমত আবিষ্কার করেছে? (ইসলামিক ফাউন্ডেশন ৬৯৩৭, ইসলামিক সেন্টার ৬৯৯৫)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>7201</td></tr><tr><td>Arabic No</td><td>2860.02</td></tr><tr><td>Reference</td><td>Book 53 Hadith 70</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
This hadith has been narrated through other chains of transmitters on the authority of Ibn Abbas, (and) the words are:While Allah's Messenger (ﷺ) stood up to deliver a sermon, he said: 0 people, Allah would make you assemble barefooted, naked and uncircumcised (and then recited the words of the Qur'an):" As We created you for the first time, We shall repeat it. (It is) a promise (binding) upon us. Lo! We are to perform it, and the first person who would be clothed on the Day of Resurrection would be (Hadrat) Ibrahim (peace be upon him)" and, behold! some persons of my Ummah would be brought and taken to the left and I would say: My Lord, they are my companions, and it would be said: You do not know what they did after you, and I would say just as the pious servant (Hadrat 'Isa) said:, I was a witness regarding them as I remained among them and Thou art a witness over everything, so if Thou chastisest them, they are Thy servants and if Thou for- givest them, Thou art Mighty, Wise" (v. 117-118). And it would be said to him: They constantly turned to their heels since you left them. This hadith has been transmitted on the authority of Waki' and Mu'adh (and the words are):" What new things they fabricated
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>7201</td></tr><tr><td>Arabic No</td><td>2860.02</td></tr><tr><td>Reference</td><td>Book 53 Hadith 70</td></tr></tbody></table></div>

## French


<div dir="ltr" lang="fr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>

</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>7201</td></tr><tr><td>Arabic No</td><td>2860.02</td></tr><tr><td>Reference</td><td>Book 53 Hadith 70</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Abu Bakr bin Abu Syaibah] telah menceritakan kepada kami [Waki']. Telah menceritakan kepada kami [Ubaidullah bin Mu'adz] telah menceritakan kepada kami [ayahku], keduanya dari [Syu'bah]. Telah menceritakan kepada kami [Muhammad bin Al Mutsanna] dan [Muhammad bin Basyar], teks milik Ibnu Al Mutsanna, keduanya berkata: Telah menceritakan kepada kami [Muhammad bin Ja'far] telah menceritakan kepada kami [Syu'bah] dari [Al Mughirah bin An Nu'man] dari [Sa'id bin Jubair] dari [Ibnu Abbas] berkata: Rasulullah Shallallahu 'alaihi wa Salam berdiri berkhutbah menyampaikan suatu nasehat ditengah-tengah kami, beliau bersabda: "Wahai sekalian manusia, sesungguhnya kalian dikumpulkan menuju Allah dalam keadaan tidak beralas kaki, telanjang dan kulup 'Sebagaimana Kami telah memulai panciptaan pertama begitulah kami akan mengulanginya. Itulah suatu janji yang pasti kami tepati; Sesungguhnya kamilah yang akan melaksanakannya.' (Al Anbiyaa': 104) Ingat, sesungguhnya makhluk pertama yang diberi pakaian pada hari kiamat adalah Ibrahim 'alaihis salaam. Ingat, sesungguhnya beberapa orang dari ummatku akan didatangkan lalu mereka diambil ke golongan kiri, aku berkata: 'Wahai Rabb, sahabat-sahabatku.' Dikatakan: 'Sesungguhnya engkau tidak tahu apa yang mereka buat-buat sepeninggalmu.' Lalu aku mengucapkan seperti perkataan seorang hamba shalih: 'Aku menjadi saksi atas mereka selagi aku bersama mereka namun tatkala Engkau wafatkan aku, Engkaulah yang mengawasi mereka dan Engkau Maha menyaksikan terhadap segala sesuatu. Jika Engkau siksa mereka maka sesungguhnya mereka adalah hambaMu.' (Al Maa'idah: 117-118) lalu dijawab: Mereka senantiasa kembali ke belakang (murtad) sejak kau tinggalkan mereka." Disebutkan dalam hadits Waki' dan Mu'adz: Lalu dikatakan: "Sesungguhnya kau tidak tahu apa yang mereka buat-buat sepeninggalmu
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>7201</td></tr><tr><td>Arabic No</td><td>2860.02</td></tr><tr><td>Reference</td><td>Book 53 Hadith 70</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
இப்னு அப்பாஸ் (ரலி) அவர்கள் கூறியதாவது: (ஒரு முறை) அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் எங்களிடையே நின்று (எங்களுக்கு) அறிவுரை வழங்கிக்கொண்டிருந்தார்கள். அப்போது (பின்வருமாறு) கூறினார்கள்: மக்களே! (மறுமை நாளில்) நீங்கள் செருப்பணியாதவர்களாக, நிர்வாணமானவர்களாக, விருத்தசேதனம் செய்யப்படாதவர்களாக அல்லாஹ்விடம் ஒன்றுதிரட்டிக்கொண்டு வரப்படுவீர்கள். அல்லாஹ் கூறுகின்றான்: முதன் முதலாக அவர்களை நாம் படைத்ததைப் போன்றே (அந்நாளில்) அவர்களை நாம் மீண்டும் படைப்போம். இது நம்மீது (பொறுப்பாகிவிட்ட) வாக்குறுதியாகும். இதை நாம் நிச்சயமாகச் செய்வோம் (21:104). கவனத்தில் வையுங்கள்! மறுமை நாளில் படைப்பினங்களிலேயே முதன் முதலாக ஆடையணிவிக்கப்படுபவர் இப்ராஹீம் (அலை) அவர்கள் ஆவார்கள். கவனத்தில் வையுங்கள்! என் சமுதாயத்தாரில் சிலர் இடப் பக்கமாக (நரகம் நோக்கி)க் கொண்டு செல்லப்படுவார்கள். அப்போது நான் "என் இறைவா! (இவர்கள்) என் தோழர்கள்" என்பேன். அப்போது "(இவர்கள்) உம(து இறப்பு)க்குப்பின் (மார்க்கத்தில்) என்னவெல்லாம் புதிது புதிதாக உருவாக்கினார்கள் என்பது உமக்குத் தெரியாது" என்று கூறப்படும். அப்போது நான், நல்லடியார் (நபி ஈசா (அலை) அவர்கள்) சொன்னதைப் போன்று, "(இறைவா!)" நான் அவர்களுடன் இருந்தவரை அவர்களைக் கண்காணிப்பவனாகவே இருந்தேன். நீ என்னைத் திரும்ப அழைத்துக்கொண்டபோது, நீயே அவர்களைக் கண்காணிப்பவனாக இருந்தாய். நீ அனைத்தையும் கண்காணிப்பவன். அவர்களை நீ தண்டித்தால் அவர்கள் உன் அடியார்களே. அவர்களை நீ மன்னித்தால் நீ மிகைத்தவன்; ஞானமிக்கவன்" (5:117,118) என்று சொல்வேன். அப்போது என்னிடம், "நீர் இவர்களைவிட்டுப் பிரிந்ததிலிருந்து இவர்கள் தம் குதிகால் (சுவடு)களின் வழியே மார்க்கத்திலிருந்து வெளியேறிக்கொண்டேயிருந்தார்கள்" என்று கூறப்படும். இந்த ஹதீஸ் நான்கு அறிவிப்பாளர்தொடர்களில் வந்துள்ளது. அவற்றில் வகீஉ மற்றும் முஆத் (ரஹ்) ஆகியோரது அறிவிப்பிலேயே "அப்போது, இவர்கள் உம(து இறப்பு)க்குப் பின் (மார்க்கத்தில்) என்னவெல்லாம் புதிது புதிதாக உருவாக்கினார்கள் என்பது உமக்குத் தெரியாது" எனும் குறிப்பு இடம்பெற்றுள்ளது. அத்தியாயம் : 51
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>7201</td></tr><tr><td>Arabic No</td><td>2860.02</td></tr><tr><td>Reference</td><td>Book 53 Hadith 70</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Bize Ebû Bekr b. Ebî Şeybe rivayet etti. (Dediki): Bize Veki' rivayet etti. H. Bize Ubeydullah b. Muâz da rivayet etti. (Dediki): Bize babam ri­vayet etti. Her iki râvi Şu'be'den rivayet etmişlerdir. H.. Bize Muhamraed b. Müsennâ ile Muhammed b. Beşşar dahî rivayet ettiler. Lâfız İbni Müsennâ'nındır. (Dedilerki): Bize Muhammed b. Ca'fer rivayet etti. (Dediki): Bize Şu'be, Muğîra b. Nu'man'dan, o da Saîd h. Cübeyr'den, o da İbni Abbas'dan naklen rivayet etti. (Şöyle demiş): Resûlullah (Sallallahu Aleyhi ve Sellem) bir va'z dolayısıyla hutbe okumak için aramızda ayağa kalktı ve : «Ey insanlar! Hiç şüphe yok ki, siz Allah'a yalınayak, çıplak, sünnetsiz olarak haşredileceksiniz. (İlk yaratmaya nasıl başladıksa, üzerimize va'd olarak onu öylece iade edeceğiz. Biz va'dimizi yaparız.) [Enbiya 104] Dikkat edin ki, kıyamet gününde mahlûkatın ilk giydirileni İbrahim (Aleyhisselâm) olacaktır. Dikkat edin ki, benim ümmetimden bir takım adamlar getirilecek, fakat onlar sol tarafa alınacaktır. Bunun üzerine ben: Yarabbi! Bunlar benim ashabımdır, diyeceğim. (Bana); Bunların senden sonra ne modalar çıkardıklarını sen bilmezsin? denilecek? Ben de sâlih kulun dediği gibi (Ben onlara aralarında bulunduğum müddetçe şâhid oldum. Benim ruhumu kabzedince (artık) onların üzerine rakib sen oldun. Sen her şeye şâhidsin. Onları azab edersen, şüphesiz onlar senin kullarındır. Affedersen şüphe yok ki, Aziz Hakim olan ancak sensin) [Maide 117-118] diyeceğim. Bunun üzerine bana: Sen onlardan ayrılalı onlar geriye dönmekte devam ettiler, denilecektir.» Veki' ile Muâzın hadîsinde: «Bunun üzerine sen onların, senden sonra ne modalar çıkardıklarını bilmezsin, denilecek...» cümlesi vardır
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>7201</td></tr><tr><td>Arabic No</td><td>2860.02</td></tr><tr><td>Reference</td><td>Book 53 Hadith 70</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
وکیع اور معاذ دونوں نے ہمیں شعبہ سے حدیث بیان کی ، نیز محمد بن مثنیٰ اور محمد بن بشار نے ۔ الفاظ ابن مثنیٰ کے ہیں ۔ کہا : ہمیں محمد بن جعفرنے شعبہ سے حدیث بیان کی ، انھوں نے مغیرہ بن نعمان سے ، انھوں نے سعید بن جبیر سے اور انھوں نے حضرت ابن عباس رضی اللہ تعالیٰ عنہ سے روایت کی ، کہا : رسول اللہ صلی اللہ علیہ وسلم ہمارے درمیان نصیحت آموز خطبہ دینے کے لیے کھڑے ہوئے اور فرمایا : " اے لوگو! تم کو اللہ کے سامنے ننگے پاؤں بے لباس بے ختنہ اکٹھا کیا جا ئے گا ۔ ( قرآن مجید میں ہے ) : " جس طرح ہم نے پہلی پیدائش کا آغاز کیا تھا اسی کو دوبارہ لو ٹائیں گے ۔ یہ ہم پر ( پختہ ) وعدہ ہے ہم یہی کرنے والے ہیں ۔ " یاد رکھو!مخلوقات میں سے سب سے پہلے جنھیں لباس پہنایا جا ئے گا وہ ابراہیم علیہ السلام ہوں گے ۔ اور یاد رکھو!میری امت میں سے کچھ لوگ لائے جائیں گے ، پھر انھیں پکڑکر بائیں ( جہنم کی ) طرف لے جایا جائے گا ۔ میں کہوں گا ۔ میرے رب! میرے ساتھی ہیں ۔ تو کہا جا ئےگا ۔ آپ کو معلوم نہیں انھوں نے آپ کے بعد ( دین میں ) کیانئی باتیں نکالی تھیں ۔ تو وہی کچھ کہوں گا جو نیک بندے ( عیسیٰ علیہ السلام ) کہیں گے : " میں ان پر گواہ تھا جب تک میں ان کے درمیان رہا جب تونے مجھے اٹھالیا تو ان پر تو نگہبان تھا ۔ اگر تو انھیں عذاب دے تو بے شک یہ تیرے بندے ہیں اور اگر توانھیں بخش دے تو یقیناً تو ہی بڑا غالب اور بڑا دانا ہے ۔ " فرمایا : " تومجھ سے کہا جا ئے گا جب سے آپ ان سے جدا ہوئے تھے ۔ یہ مسلسل اپنی ایڑیوں پر لوٹتے چلے گئے ۔ اور وکیع اور معاذ کی حدیث میں ہے : " تو کہا جائے گا ۔ آپ نہیں جا نتے کہ انھوں نے آپ کے بعد ( دین میں ) کیا نئی باتیں نکالی تھیں ۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>7201</td></tr><tr><td>Arabic No</td><td>2860.02</td></tr><tr><td>Reference</td><td>Book 53 Hadith 70</td></tr></tbody></table></div>