## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا مُحَمَّدُ بْنُ أَبِي عُمَرَ، حَدَّثَنَا سُفْيَانُ، عَنْ سُهَيْلِ بْنِ أَبِي صَالِحٍ، عَنْ أَبِيهِ، عَنْ أَبِي هُرَيْرَةَ، قَالَ قَالُوا يَا رَسُولَ اللَّهِ هَلْ نَرَى رَبَّنَا يَوْمَ الْقِيَامَةِ قَالَ ‏"‏ هَلْ تُضَارُّونَ فِي رُؤْيَةِ الشَّمْسِ فِي الظَّهِيرَةِ لَيْسَتْ فِي سَحَابَةٍ ‏"‏ ‏.‏ قَالُوا لاَ ‏.‏ قَالَ ‏"‏ فَهَلْ تُضَارُّونَ فِي رُؤْيَةِ الْقَمَرِ لَيْلَةَ الْبَدْرِ لَيْسَ فِي سَحَابَةٍ ‏"‏ ‏.‏ قَالُوا لاَ ‏.‏ قَالَ ‏"‏ فَوَالَّذِي نَفْسِي بِيَدِهِ لاَ تُضَارُّونَ فِي رُؤْيَةِ رَبِّكُمْ إِلاَّ كَمَا تُضَارُّونَ فِي رُؤْيَةِ أَحَدِهِمَا - قَالَ - فَيَلْقَى الْعَبْدَ فَيَقُولُ أَىْ فُلْ أَلَمْ أُكْرِمْكَ وَأُسَوِّدْكَ وَأُزَوِّجْكَ وَأُسَخِّرْ لَكَ الْخَيْلَ وَالإِبِلَ وَأَذَرْكَ تَرْأَسُ وَتَرْبَعُ فَيَقُولُ بَلَى ‏.‏ قَالَ فَيَقُولُ أَفَظَنَنْتَ أَنَّكَ مُلاَقِيَّ فَيَقُولُ لاَ ‏.‏ فَيَقُولُ فَإِنِّي أَنْسَاكَ كَمَا نَسِيتَنِي ‏.‏ ثُمَّ يَلْقَى الثَّانِيَ فَيَقُولُ أَىْ فُلْ أَلَمْ أُكْرِمْكَ وَأُسَوِّدْكَ وَأُزَوِّجْكَ وَأُسَخِّرْ لَكَ الْخَيْلَ وَالإِبِلَ وَأَذَرْكَ تَرْأَسُ وَتَرْبَعُ فَيَقُولُ بَلَى أَىْ رَبِّ ‏.‏ فَيَقُولُ أَفَظَنَنْتَ أَنَّكَ مُلاَقِيَّ فَيَقُولُ لاَ ‏.‏ فَيَقُولُ فَإِنِّي أَنْسَاكَ كَمَا نَسِيتَنِي ‏.‏ ثُمَّ يَلْقَى الثَّالِثَ فَيَقُولُ لَهُ مِثْلَ ذَلِكَ فَيَقُولُ يَا رَبِّ آمَنْتُ بِكَ وَبِكِتَابِكَ وَبِرُسُلِكَ وَصَلَّيْتُ وَصُمْتُ وَتَصَدَّقْتُ ‏.‏ وَيُثْنِي بِخَيْرٍ مَا اسْتَطَاعَ فَيَقُولُ هَا هُنَا إِذًا - قَالَ - ثُمَّ يُقَالُ لَهُ الآنَ نَبْعَثُ شَاهِدَنَا عَلَيْكَ ‏.‏ وَيَتَفَكَّرُ فِي نَفْسِهِ مَنْ ذَا الَّذِي يَشْهَدُ عَلَىَّ فَيُخْتَمُ عَلَى فِيهِ وَيُقَالُ لِفَخِذِهِ وَلَحْمِهِ وَعِظَامِهِ انْطِقِي فَتَنْطِقُ فَخِذُهُ وَلَحْمُهُ وَعِظَامُهُ بِعَمَلِهِ وَذَلِكَ لِيُعْذِرَ مِنْ نَفْسِهِ ‏.‏ وَذَلِكَ الْمُنَافِقُ وَذَلِكَ الَّذِي يَسْخَطُ اللَّهُ عَلَيْهِ ‏"‏ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>7438</td></tr><tr><td>Arabic No</td><td>2968</td></tr><tr><td>Reference</td><td>Book 55 Hadith 22</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
হাদিস একাডেমি নাম্বারঃ ৭৩২৮, আন্তর্জাতিক নাম্বারঃ ২৯৬৮ ৭৩২৮-(১৬/২৯৬৮) মুহাম্মদ ইবনু আবূ উমর (রহঃ) ..... আবূ হুরাইরাহ (রাযিঃ) থেকে বর্ণিত। তিনি বলেন, সহাবাগণ জিজ্ঞেস করলেন, হে আল্লাহর রসূল! কিয়ামতের দিন আমরা কি আমাদের রবকে দেখতে পাব? জবাবে তিনি বললেন, আকাশে মেঘ না থাকাবস্থায় দুপুরের সময় সূর্য দেখতে তোমাদের কোন কষ্ট হয় কি? সহাবাগণ বললেন, জী না। অতঃপর তিনি বললেন, আকাশে মেঘ না থাকাবস্থায় পূর্ণিমার চাঁদ দেখতে তোমাদের কোন কষ্ট হয় কি? সহাবাগণ বললেন, জী না। তারপর তিনি বললেন, ঐ সত্তার কসম! যার হাতে আমার জীবন! চন্দ্ৰ-সূৰ্য কোন একটি দেখতে তোমাদের যেরূপ কষ্ট হয় না, তোমাদের রবকেও দেখতে তোমাদের ঠিক তদ্রুপ কষ্ট হবে না। আল্লাহর সাথে বান্দার সাক্ষাৎ হবে। তখন তিনি বললেন, হে অমুক! আমি কি তোমাকে সম্মান দান করিনি, কর্তৃত্ব দান করিনি, জোড়া মিলিয়ে দেইনি, ঘোড়া-উট তোমার কাজে লাগিয়ে দেইনি এবং সুখ-স্বাচ্ছদের মাঝে তোমার পানাহারের ব্যবস্থা করিনি? জবাবে বান্দা বলবে, হ্যাঁ, হে আমার রব। তারপর তিনি বলবেন, তুমি কি মনে করতে যে, তুমি আমার মুখোমুখী হবে? সে বলবে, না, তা মনে করতাম না। তিনি বললেন, তুমি যেরূপভাবে আমাকে ভুলে গিয়েছিলে তদ্রুপভাবে আমিও তোমাকে ভুলে যাচ্ছি। অতঃপর দ্বিতীয় অপর এক ব্যক্তির আল্লাহর সাথে সাক্ষাৎ হবে। তখন তিনি তাকেও বলবেন, হে অমুক! আমি কি তোমাকে সম্মান দান করিনি, নেতৃত্ব দেইনি, তোমার পরিবার (জোড়া মিলিয়ে) দেইনি, উট-ঘোড়া তোমার কাজে লাগিয়ে দেইনি এবং সুখ-স্বাচ্ছন্দ্যে পানাহারের জন্য তোমাকে কি সুবিধা করে দেইনি? সে বলবে, হ্যাঁ করেছেন। হে আমার পালনকর্তা! তারপর তিনি বললেন, আমার সাথে তোমার সাক্ষাৎ হবে এ কথা তুমি মনে করতে? সে বলবে, না। তখন আল্লাহ তা’আলা বলবেন, তুমি যেমন আমাকে ভুলে গিয়েছিলে অনুরূপভাবে আমিও তোমাদেরকে ভুলে যাব। তারপর তৃতীয় অপর এক ব্যক্তির আল্লাহর সাথে দেখা হবে। এরপর তিনি আগের মতো অবিকল বলবেন। তখন লোকটি বলবে, হে আমার প্রতিপালক! আমি আপনার প্রতি এবং কিতাব ও রসূলগণের প্রতি ঈমান এনেছি। আমি সালাত আদায় করেছি, সাওম পালন করেছি এবং সদাকাহ করেছি। এমনিভাবে সে যথাসাধ্য নিজের প্রশংসা করবে। এমতাবস্থায় আল্লাহ তা’আলা বলবেন, এখনই তোমার মিথ্যা প্রকাশিত হয়ে যাবে। রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেনঃ তারপর তাকে বলা হবে, এখনই আমি তোমার উপর আমার সাক্ষী উপস্থিত করব। তখন বান্দা মনে মনে চিন্তা করতে থাকবে যে, কে তার বিপক্ষে সাক্ষী দিবে? তখন তার জবান বন্ধ করে দেয়া হবে এবং তার উরু, গোশত ও হাড়কে বলা হবে, তোমরা কথা বলো। ফলে তার উরু, গোশত ও হাড় তার আমলের ব্যাপারে বলতে থাকবে। এ ব্যবস্থা এজন্য করা হবে যেন, আত্মপক্ষ সমর্থন করার কোন সুযোগ তার অবশিষ্ট না থাকে। এ ব্যক্তি হচ্ছে মুনাফিক যার প্রতি আল্লাহ তা’আলা অসন্তুষ্ট। (ইসলামিক ফাউন্ডেশন ৭১৬৯, ইসলামিক সেন্টার ৭২২২)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>7438</td></tr><tr><td>Arabic No</td><td>2968</td></tr><tr><td>Reference</td><td>Book 55 Hadith 22</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Abu Huraira reported that they (the Companions of the Holy Prophet) said:Allah's Messenger, will we be able to see our Lord on the Day of Judgment? He said: Do you feel any difficulty in seeing the sun in the noon when there is no cloud over it? They said: No. He again said: Do you feel any difficulty in seeing the moon on the fourteenth night when there is no cloud over it? They said: No. Thereupon he said: By Allah Who is One in Whose Hand is my life. you will not face any difficulty in seeing your Lord but only so much as you feel in seeing one of them. Then Allah would sit in judgment upon the servant and would say: O, so and so, did I not honour you and make you the chief and provide you the spouse and subdue for you horses, camels, and afforded you an opportunity to rule over your subjects? He would say: Yes. And then it would be said: Did you not think that you would meet Us? And he would say: No. Thereupon He (Allah) would say: Well, We forget you as you forgot Us. Then the second person would be brought for judgment. (And Allah would) say: 0, so and so. did We not honour you and make you the chief and make you pair and subdue for you horses and camels and afford you an opportunity to rule over your subjects? He would say: Yes, my Lord. And He (the Lord) would say: Did you not think that you would be meeting Us? And he would say: No. And then He (Allah) would say: Well, I forget you today as you forgot Us. Then the third -one would be brought and He (Allah) would say to him as He said before. And he (the third person) would say: O, my Lord, I affirmed my faith in Thee and in Thy Book and in Thy Messenger and I observed prayer and fasts and gave charity, and he would speak in good terms like this as he would be able to do. And He (Allah) would say: Well, We will bring our witnesses to you. And the man would think in his mind who would bear witness upon him and then his mouth would be sealed and it would be said to his thighs, to his flesh and to his bones to speak and his thighs. flesh and bones would bear witness to his deeds and it would be done so that he should not be able to make any excuse for himself and he would be a hypocrite and Allah would be annoyed with him
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>7438</td></tr><tr><td>Arabic No</td><td>2968</td></tr><tr><td>Reference</td><td>Book 55 Hadith 22</td></tr></tbody></table></div>

## French


<div dir="ltr" lang="fr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>

</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>7438</td></tr><tr><td>Arabic No</td><td>2968</td></tr><tr><td>Reference</td><td>Book 55 Hadith 22</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>

</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>7438</td></tr><tr><td>Arabic No</td><td>2968</td></tr><tr><td>Reference</td><td>Book 55 Hadith 22</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
அபூஹுரைரா (ரலி) அவர்கள் கூறியதாவது: மக்கள், "அல்லாஹ்வின் தூதரே! நாங்கள் மறுமைநாளில் எங்கள் இறைவனைக் காண்போமா?" என்று கேட்டார்கள். அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள், "மேக மூட்டமில்லாத நண்பகல் நேரத்தில் சூரியனைக் காண்பதற்கு நீங்கள் சிரமப்படுவீர்களா?" என்று கேட்டார்கள். மக்கள், "இல்லை" என்றார்கள். அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள், "மேகமூட்டமில்லாத பௌர்ணமி இரவில் சந்திரனைக் காண்பதற்கு நீங்கள் சிரமப்படுவீர்களா?" என்று கேட்டார்கள். மக்கள் "இல்லை" என்று கூறினார்கள். அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் கூறினார்கள்: என் உயிர் எவன் கையிலுள்ளதோ அவன்மீது சத்தியமாக! இவ்விரண்டில் ஒன்றைக் காண்பதற்கு நீங்கள் சிரமப்படாததைப் போன்றே, உங்கள் இறைவனைக் காண்பதற்கும் நீங்கள் சிரமப்படமாட்டீர்கள். இறைவன் அடியானைச் சந்தித்து, "இன்ன மனிதனே! உன்னை நான் கண்ணியப்படுத்தி, உன்னைத் தலைவனாக்கி,உனக்குத் துணையை ஏற்படுத்தவில்லையா? குதிரைகளையும் ஒட்டகங்களையும் நான் உன் வசப்படுத்தவில்லையா?உன்னை (செல்வாக்குள்ள) தலைவனாக்கிப் போர்ச்செல்வங்களில் நான்கில் ஒரு பகுதியை உனக்கு உரியதாக்க வில்லையா?" என்று கேட்பான். அதற்கு அந்த அடியான், "ஆம்" என்பான். இறைவன், "நீ என்னைச் சந்திப்பாய் என எண்ணினாயா?" என்று கேட்பான். அதற்கு அந்த அடியான், "இல்லை" என்பான். இறைவன், "அவ்வாறாயின், நீ என்னை மறந்ததைப் போன்றே நானும் உன்னை மறந்துவிடுகிறேன்" என்பான். பிறகு மற்றோர் அடியானைச் சந்திக்கும் இறைவன், "இன்ன மனிதனே! உன்னைக் கண்ணியப்படுத்தி, உன்னைத் தலைவனாக்கி, உனக்கு(த்தகுந்த) துணையையும் நான் வழங்கவில்லையா? குதிரைகளையும் ஒட்டகங்களையும் நான் உன் வசப்படுத்தவில்லையா? உன்னை (செல்வாக்குள்ள) தலைவனாக்கிப் போர்ச்செல்வத்தில் நான்கில் ஒரு பகுதியை உனக்கு உரிமையாக்கவில்லையா?" என்று கேட்பான். அதற்கு அந்த அடியான், "ஆம், என் இறைவா!" என்பான். இறைவன், "நீ என்னைச் சந்திப்பாய் என எண்ணினாயா?"என்று கேட்பான். அதற்கு அந்த அடியான், "இல்லை" என்பான். இறைவன், "அவ்வாறாயின், நீ என்னை மறந்ததைப் போன்றே நானும் உன்னை மறந்துவிடுகிறேன்" என்பான். பிறகு மூன்றாவது அடியானைச் சந்திக்கும் இறைவன், முன்பு கேட்டதைப் போன்றே அவனிடமும் கேட்பான். அதற்கு அந்த அடியான், "என் இறைவா! நான் உன்னையும் உன் வேதத்தையும் உன் தூதர்களையும் நம்பி, உன்னைத் தொழுது (உனக்காக) நோன்பு நோற்றேன்.தானதர்மம் செய்தேன்" என்று கூறிவிட்டு, தன்னால் இயன்ற நல்ல வார்த்தைகளைக் கூறி இறைவனைப் புகழ்வான். அப்போது இறைவன், "நீ இங்கேயே நில்" என்று கூறுவான். பிறகு அவனிடம், "இப்போது உனக்கெதிரான நம்முடைய சாட்சியை நாம் எழுப்பப்போகிறோம்" என்று கூறுவான். அந்த மனிதன், தனக்கெதிராகச் சாட்சியம் சொல்பவர் யார் என்று யோசித்துக்கொண்டிருப்பான். அப்போது அவனது வாய்க்கு முத்திரையிடப்படும். அவனது தொடை, சதை, எலும்பு ஆகியவற்றைப் பார்த்து "பேசுங்கள்" என்று சொல்லப்படும். அப்போது அவனுடைய தொடை, சதை, எலும்பு ஆகியவை அவன் செய்தவை பற்றி எடுத்துரைக்கும். அவன் சாக்குப்போக்குச் சொல்லித் தப்பிவிடக் கூடாது என்பதே இதற்குக் காரணம். அவன்தான் நயவஞ்சகன் (முனாஃபிக்) ஆவான். அவன்மீது இறைவன் கடும் கோபம் கொள்வான். அத்தியாயம் : 53
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>7438</td></tr><tr><td>Arabic No</td><td>2968</td></tr><tr><td>Reference</td><td>Book 55 Hadith 22</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Bize Muhammed b. Ebî Ömer rivayet etti. (Dediki): Bize Süfyan, Süheyl b. Ebî Sâlih'den, b da babasından, o da Ebû Hureyre'den naklen rivayet etti. (Şöyle demiş): Ashab : — Yâ Resûlallah! Biz kıyamet gününde Rabbimizi görecek miyiz? diye sordular. «Oğle zamanında bulut içinde değilken güneşi görmek husûsunda bir-birinizle itişip kakışıyor musunuz?» dedi. Ashab: — Hayır! cevâbını verdiler. «Yâ Bedir gecesinde bulut içinde olmayan ay'ı görmek hususumda bir-birinizle itişîr misiniz?» dedi. Ashab (yine) : — Hayır! cevâbını verdiler. «O halde nefsim yed-i kudretinde olan Allah'a yemin ederim ki, siz Rabbinizi görme hususunda ancak bu ayla güneşden birini görmek için itiştiğiniz gibi itişeceksiniz. Teâlâ Hazretleri kulun karşısına çıkarak : — Ey filân, ben sana ikram etmedim mi? Seni reis yapmadım mı? Sana zevce vermedim mi? Sana at ve develeri musahhar kılmadım mı? Reislik yapmana, ganimet malının dörtte birini almana müsaade etmedim mi? diyecek. O da : — Hay hay (ettin) cevâbını verecektir. Teâlâ Hazretleri : — Yâ bana kavuşacağını aklından geçirdin mî? diye soracak. Kul . — Hayır! cevâbını verecektir. Bunun üzerine Teâlâ Hazretleri: Işte ben de senin benî unuttuğun gibi, seni unutuyorum, diyecek. Sonıfa ikinci kulun karşısına çıkarak : — Ey filân! Ben sana ikram etmedim mi? Seni reis yapmadm mı? Sana zevce vermedim mi? Atları ve develeri sana musahhar kılmadım mı? Reislik yapmana ve ganimetin dörtte birini almana müsaade etmedim mi? diye soracak. O da : — Hay hay (ettin) Yarabbi! cevâbını verecek. —' Bana kavuşacağını hiç aklından geçirdin mi? diyecek. Kul : — Hayır! cevâbını verecektir. Bunun üzerine Teâlâ Hazretleri : — işte ben de senin benî unuttuğun gibi, seni unutuyorum, diyecek. Sonra üçüncü kulun karşısına çıkarak, ona da bunun mislini söyleyecek. Fakat o kul : — Yâ Rabbi! Ben Sana, Senin Kitabına ve Nebilerine inandım; namaz kıldım, oruç tuttum, sadaka verdim, diyecek ve olanca gücüyle hayır senasında bulunacak. Teâlâ Hazretleri : — Öyle ise şuraya! buyuracaktır. Sonra kendisine : — Şimdi sana şahidimizi göndereceğiz, denilecektir. Kul kendi kendine Aceb bana şâhîdlik yapacak bu zât kimdir? diye düşünecek, fakat ağzına mühür vurulacak; uyluğuna, etîne ve kemiğine : — Konuş! denilecek. Artık uyluğu, eti ve kemiği onun amelini söyleyecektir. Bu ona kendi nâmına bir özür bırakmamak içindir. işte bu münâfıktır. Allah'ın hışımına uğrayacak olan da budur.» İZAH 2969 DA
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>7438</td></tr><tr><td>Arabic No</td><td>2968</td></tr><tr><td>Reference</td><td>Book 55 Hadith 22</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حضرت ابو ہریرہ رضی اللہ تعالیٰ عنہ سے روایت ہے کہا : انھوں نے ( صحابہ کرام رضوان اللہ عنھم اجمعین ) نے عرض کی ، اللہ کے رسول اللہ صلی اللہ علیہ وسلم !قیامت کے دن ہم اپنے رب کو دیکھیں گے؟آپ صلی اللہ علیہ وسلم نے فرمایا : "" کیا دوپہر کے وقت جب بادل نہ ہوں تمھیں سورج کودیکھنے میں کوئی زحمت ہوتی ہے ۔ ؟ "" انھوں ( صحابہ کرام رضوان اللہ عنھم اجمعین ) نے کہا : نہیں آپ نے فرمایا : "" چودھویں کی رات کو جب بادل نہ ہوں تو کیا تمھیں چاند کو دیکھنے میں کو ئی زحمت ہوتی ہے؟ "" انھوں نے ( صحابہ کرام رضوان اللہ عنھم اجمعین ) نے کہا : نہیں آپ نے فرمایا : "" مجھے اس ذات کی قسم جس کے ہاتھ میں میری جان ہے ۔ !تمھیں اپنے رب کو دیکھنے میں اس سے زیادہ زحمت نہیں ہو گی جتنی زحمت تمھیں ان دونوں کو دیکھنے میں ہو تی ہے ۔ "" آپ نے فرمایا : "" وہ ( رب ) بندے سے ملا قات فرمائے گا تو کہے گا ۔ اے فلاں !کیا میں نے تمھیں عزت نہ دی تھی ، تمھیں سردار نہ بنایا تھا تمھاری شادی نہ کرائی تھی گھوڑے اور اونٹ تمھارے اختیار میں نہ دیے تھے اور تمھیں ایسا نہیں بنا چھوڑا تھا کہ تم سرداری کرتے تھے اور لوگوں کی آمدنی میں سے چوتھائی حصہ لیتے تھے ؟وہ جواب میں کہے گا ۔ کیوں نہیں ! ( بالکل ایسا ہی تھا ۔ ) تو وہ فرمائے گا ۔ کیا تم سمجھتے تھے کہ تم مجھ سے ملوگے؟ وہ کہے گا ۔ نہیں ۔ تووہ فرمائے گا ۔ آج میں اسی طرح تمھیں بھول جاؤں گا ۔ جس طرح تم مجھے بھول گئے تھے پھر دوسرے سے ملاقات کرے گا ۔ اے فلاں !کیا میں نے تمھیں عز ت اور سیادت سے نہیں نوازا تھا تمھاری شادی نہیں کرائی تھی تمھارے لیے اونٹ اور گھوڑے مسخر نہیں کیے تھے اور تمھیں اس طرح نہیں بنا چھوڑا تھا کہ تم ریاست کے مزے لیتے تھے ۔ اور لوگوں کے مالوں میں سے چوتھا ئی حصہ وصول کرتے تھے ۔ ؟وہ کہے گا کیوں نہیں میرے رب!تو وہ فرمائے گا ۔ تمھیں اس بات کا کوئی گمان بھی تھا کہ تم مجھ سے ملا قات کروگے؟ وہ کہے گا ۔ نہیں تو وہ فرمائے گا اب میں بھی اسی طرح تمھیں بھول جاؤں گا جس طرح تم مجھے بھول گئے تھے ۔ پھر تیسرے سے ملے گا ۔ اس سے بھی وہی فرمائے گا ۔ وہ کہے گا ۔ اے میرے رب !میں تجھ پر تیری کتابوں اور تیرے رسولوں پر ایمان لایا تھا اور نمازیں پڑھی تھیں روزے رکھے تھے اور صدقہ دیا کرتا تھا جتنا اس کے بس میں ہو گا ( اپنی نیکی کی ) تعریف کرے گا ، چنانچہ وہ فرمائے گا ۔ تب تم یہیں ٹھہرو ۔ فرمایا : پھر اس سے کہا جا ئے گا ۔ اب تم تمھارے خلاف اپنا گواہ لائیں گے ۔ وہ دل میں سوچے گا میرے خلاف کون گواہی دے گا ۔ ؟پھر اس کے منہ پر مہر لگادی جا ئے گیاور اس کی ران گوشت اور ہڈیوں سے کہا جائے گا ۔ بولو تو اس کی ران اس کا گوشت اور اس کی ہڈیاں اس کے عمل کے متعلق بتائیں گی ۔ یہ ( اس لیے ) کہا جا ئے گا کہ وہ ( اللہ ) اس کی ذات سے اس کا عذر دور کردے ۔ اور وہ منافق ہو گا اور وہی شخص ہو گا جس پر اللہ تعالیٰ سخت ناراض ہو گا ۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>7438</td></tr><tr><td>Arabic No</td><td>2968</td></tr><tr><td>Reference</td><td>Book 55 Hadith 22</td></tr></tbody></table></div>