## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
وَحَدَّثَنِي أَبُو الطَّاهِرِ، وَحَرْمَلَةُ بْنُ يَحْيَى، - وَاللَّفْظُ لِحَرْمَلَةَ - قَالاَ أَخْبَرَنَا ابْنُ، وَهْبٍ قَالَ أَخْبَرَنِي يُونُسُ بْنُ يَزِيدَ، عَنِ ابْنِ شِهَابٍ، قَالَ أَخْبَرَنِي عُرْوَةُ بْنُ الزُّبَيْرِ، عَنْ عَائِشَةَ، زَوْجِ النَّبِيِّ صلى الله عليه وسلم أَنَّ قُرَيْشًا أَهَمَّهُمْ شَأْنُ الْمَرْأَةِ الَّتِي سَرَقَتْ فِي عَهْدِ النَّبِيِّ صلى الله عليه وسلم فِي غَزْوَةِ الْفَتْحِ فَقَالُوا مَنْ يُكَلِّمُ فِيهَا رَسُولَ اللَّهِ صلى الله عليه وسلم فَقَالُوا وَمَنْ يَجْتَرِئُ عَلَيْهِ إِلاَّ أُسَامَةُ بْنُ زَيْدٍ حِبُّ رَسُولِ اللَّهِ صلى الله عليه وسلم ‏.‏ فَأُتِيَ بِهَا رَسُولُ اللَّهِ صلى الله عليه وسلم فَكَلَّمَهُ فِيهَا أُسَامَةُ بْنُ زَيْدٍ فَتَلَوَّنَ وَجْهُ رَسُولِ اللَّهِ صلى الله عليه وسلم فَقَالَ ‏"‏ أَتَشْفَعُ فِي حَدٍّ مِنْ حُدُودِ اللَّهِ ‏"‏ ‏.‏ فَقَالَ لَهُ أُسَامَةُ اسْتَغْفِرْ لِي يَا رَسُولَ اللَّهِ ‏.‏ فَلَمَّا كَانَ الْعَشِيُّ قَامَ رَسُولُ اللَّهِ صلى الله عليه وسلم فَاخْتَطَبَ فَأَثْنَى عَلَى اللَّهِ بِمَا هُوَ أَهْلُهُ ثُمَّ قَالَ ‏"‏ أَمَّا بَعْدُ فَإِنَّمَا أَهْلَكَ الَّذِينَ مِنْ قَبْلِكُمْ أَنَّهُمْ كَانُوا إِذَا سَرَقَ فِيهِمُ الشَّرِيفُ تَرَكُوهُ وَإِذَا سَرَقَ فِيهِمُ الضَّعِيفُ أَقَامُوا عَلَيْهِ الْحَدَّ وَإِنِّي وَالَّذِي نَفْسِي بِيَدِهِ لَوْ أَنَّ فَاطِمَةَ بِنْتَ مُحَمَّدٍ سَرَقَتْ لَقَطَعْتُ يَدَهَا ‏"‏ ‏.‏ ثُمَّ أَمَرَ بِتِلْكَ الْمَرْأَةِ الَّتِي سَرَقَتْ فَقُطِعَتْ يَدُهَا ‏.‏ قَالَ يُونُسُ قَالَ ابْنُ شِهَابٍ قَالَ عُرْوَةُ قَالَتْ عَائِشَةُ فَحَسُنَتْ تَوْبَتُهَا بَعْدُ وَتَزَوَّجَتْ وَكَانَتْ تَأْتِينِي بَعْدَ ذَلِكَ فَأَرْفَعُ حَاجَتَهَا إِلَى رَسُولِ اللَّهِ صلى الله عليه وسلم ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4411</td></tr><tr><td>Arabic No</td><td>1688.02</td></tr><tr><td>Reference</td><td>Book 29 Hadith 14</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
হাদিস একাডেমি নাম্বারঃ ৪৩০৩, আন্তর্জাতিক নাম্বারঃ ১৬৮৮ ৪৩০৩-(৯/...) আবূ তাহির ও হারমালাহ্ ইবনু ইয়াহইয়া (রহঃ) ..... রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর সহধর্মিণী আয়িশাহ্ (রাযিঃ) হতে বর্ণিত যে, কুরায়শরা এক মহিলার ব্যাপারে চিন্তিত হয়ে পড়লো, যে মহিলাটি রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর সময়কালে মক্কাহ বিজয়ের সময় চুরি করেছিল। তখন তারা বলল, এ ব্যাপারে কে রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর নিকট কথা (সুপারিশ) বলবে? তখন তারা বলল, এ ব্যাপারে রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর প্রিয়পাত্র উসামাহ্ ইবনু যায়দ (রাযিঃ) ব্যতীত আর কার হিম্মত থাকতে পারে? তিনি হলেন রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর খুবই প্রিয় পাত্র। অতঃপর উক্ত মহিলাকে নিয়ে উসামাহ্ ইবনু যায়দ (রাযিঃ) রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর নিকটে এসে তার ব্যাপারে কথা বললেন। এতে রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর মুখমণ্ডল বিবর্ণ হয়ে গেল। তখন তিনি বললেনঃ তুমি কি আল্লাহ কর্তৃক নির্ধারিত হদ এর ব্যাপারে সুপারিশ করতে চাও? তখন উসামাহ্ (রাযিঃ) বললেন, হে আল্লাহর রসূল। আমার জন্য (আল্লাহর কাছে) ক্ষমা প্রার্থনা করুন। যখন সন্ধ্যা হল তখন রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম দণ্ডায়মান হয়ে এক ভাষণ দিলেন। প্রথমে তিনি আল্লাহর যথাযথ প্রশংসা করলেন, অতঃপর বললেনঃ তোমাদের পূর্ববর্তী উম্মাতগণকে ধ্বংস করা হয়েছে এজন্য যে, যখন তাদের মধ্যে কোন সম্ভ্রান্ত লোক চুরি করতো, তখন তারা তাকে ছেড়ে দিত। আর যখন তাদের মধ্যে কোন হীন লোক চুরি করতো, তখন তার উপর হদ’ প্রয়োগ করতো। সে মহান আল্লাহর কসম যার হাতে আমার জীবন যদি মুহাম্মাদের কন্যা ফাতিমাহও চুরি করতো, তবে অবশ্যই আমি তার হাত কেটে দিতাম। এরপর যে মহিলা চুরি করেছিল, তিনি তার হাত কাটার নির্দেশ দিলেন। সুতরাং তার হাত কেটে দেয়া হল। ইউনুস (রহঃ) আয়িশাহ্ (রাযিঃ) হতে বর্ণনা করেন যে, অতঃপর সে মহিলা খাটিভাবে তওবা্ করল এবং এরপরে তার বিয়ে হলো। আয়িশাহ্ (রাযিঃ) বলেন, এ ঘটনার পর ঐ মহিলা প্রায়ই আমার কাছে আসতো। তার কোন প্রয়োজন থাকলে আমি তা রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর কাছে তুলে ধরতাম। (ইসলামিক ফাউন্ডেশন ৪২৬৪, ইসলামিক সেন্টার ৪২৬৪)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4411</td></tr><tr><td>Arabic No</td><td>1688.02</td></tr><tr><td>Reference</td><td>Book 29 Hadith 14</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
A'isha, the wife of Allah's Apostle (ﷺ), reported that the Quraish were concerned about the woman who had committed theft during the lifetime of Allah's Apostle (ﷺ), in the expedition of Victory (of Mecca). They said:Who would speak to Allah's Messenger (ﷺ) about her? They (again) said: Who can dare do this but Usama b. Zaid, the loved one of Allah's Messenger (ﷺ)? She was brought to Allah's Messenger (ﷺ) and Usama b. Zaid spoke about her to him (interceded on her behalf). The color of the face of Allah's Messenger (ﷺ) changed, and he said: Do you intercede in one of the prescribed punishments of Allah? He (Usama) said: 'Messenger of Allah, seek forgiveness for me.' When it was dusk. Allah's Messenger (ﷺ) stood up and gave an address. He (first) glorified Allah as He deserves, and then said: Now to our topic. This (injustice) destroyed those before you that when any one of (high) rank committed theft among them, they spared him, and when any weak one among them committed theft, they inflicted the prescribed punishment upon him. By Him in Whose Hand is my life, even if Fatima daughter of Muhammad were to commit theft, I would have cut off her hand. He (the Holy Prophet) then commanded about that woman who had committed theft, and her hand was cut off. 'A'isha (further) said: Hers was a good repentance, and she later on married and used to come to me after that, and I conveyed her needs (and problems) to Allah's Messenger (ﷺ)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4411</td></tr><tr><td>Arabic No</td><td>1688.02</td></tr><tr><td>Reference</td><td>Book 29 Hadith 14</td></tr></tbody></table></div>

## French


<div dir="ltr" lang="fr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>

</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4411</td></tr><tr><td>Arabic No</td><td>1688.02</td></tr><tr><td>Reference</td><td>Book 29 Hadith 14</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Dan telah menceritakan kepadaku [Abu At Thahir] dan [Harmalah bin Yahya] dan ini adalah lafadz Harmalah, keduanya berkata; telah mengabarkan kepada kami [Ibnu Wahb] dia berkata; telah mengabarkan kepadaku [Yunus bin Yazid] dari [Ibnu Syihab] dia berkata; telah mengabarkan kepadaku ['Urwah bin Az Zubair] dari ['Aisyah] isteri Nabi shallallahu 'alaihi wasallam, bahwa saat penaklukan Kota Makkah di masa Rasulullah shallallahu 'alaihi wasallam, orang-orang Quraisy pernah kebingungan mengenai masalahnya seorang wanita (mereka) yang ketahuan mencuri. Maka mereka berkata, "Siapa kiranya yang berani mengadukan permasalahan ini kepada Rasulullah shallallahu 'alaihi wasallam?" maka sebagian mereka mengusulkan, "Siapa lagi kalau bukan Usamah bin Zaid, orang yang paling dicintai oleh Rasulullah shallallahu 'alaihi wasallam." Lalu wanita itu dihadapkan kepada Rasulullah shallallahu 'alaihi wasallam dan Usamah bin Zaid pun mengadukan permasalahannya kepada beliau, tiba-tiba wajah Rasulullah shallallahu 'alaihi wasallam berubah menjadi merah seraya bersabda: "Apakah kamu hendak meminta syafa'at (keringanan) dalam hukum Allah (yang telah ditetapkan)!" Maka Usamah berkata kepada beliau, "Mohonkanlah ampuanan bagiku wahai Rasulullah." Sore harinya Rasulullah shallallahu 'alaihi wasallam berdiri dan berkhutbah, setelah memuji Allah dengan ujian yang layak untuk-Nya, beliau bersabda: "Amma Ba'du. Sesungguhnya yang membinasakan orang-orang sebelum kalian adalah manakala ada orang yang terpandang (terhormat) dari mereka mencuri, maka merekapun membiarkannya. Namun jika ada orang yang lemah dan hina di antara mereka ketahuan mencuri, maka dengan segera mereka melaksanakan hukuman atasnya. Demi Dzat yang jiwaku berada tangan-Nya, sekiranya Fatimah binti Muhammad mencuri, sungguh aku sendiri yang akan memotong tangannya." Akhirnya beliau memerintahkan terhadap wanita yang mencuri, lalu dipotonglah tangan wanita tersebut." [Yunus] berkata; [Ibnu Syihab] berkata; [Urwah] berkata; ['Aisyah] berkata, "Setelah peristiwa itu, wanita tersebut malakukan taubat nasuha dan menikah, hingga pada suatu ketika ia datang kepadaku untuk meminta tolong mengajukan permintaannya kepada Rasulullah shallallahu 'alaihi wasallam, lalu aku memnuhi permintaannya tersebut." Dan telah menceritakan kepada kami ['Abd bin Humaid] telah mengabarkan kepada kami [Abdurrazaq] telah mengabarkan kepada kami [Ma'mar] dari [Az Zuhri] dari ['Urwah] dari ['Aisyah] dia berkata, "Seorang wanita Makhzumiyah pernah meminjam suatu barang, setelah itu dia mengaku barang tersebut adalah miliknya. Maka Nabi shallallahu 'alaihi wasallam menyuruh supaya tangannya dipotong, hingga keluarga wanita tersebut menemui Usamah bin Zaid dan mengadukan permasalahan wanita itu. Usamah lalu mengadukannya kepada Rasulullah shallallahu 'alaihi wasallam …', kemudian dia menyebutkan seperti hadits Laits dan Yunus
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4411</td></tr><tr><td>Arabic No</td><td>1688.02</td></tr><tr><td>Reference</td><td>Book 29 Hadith 14</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>

</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4411</td></tr><tr><td>Arabic No</td><td>1688.02</td></tr><tr><td>Reference</td><td>Book 29 Hadith 14</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Bana Ebû't-Tâhir ile Harmele b. Yahya da rivayet ettiler. Lâfız Harmele'nindir. (Dedilerki): Bize İbni Vehb haber verdi. (Dediki): Bana Yûnus b. Yezîd, İbni Şihâb'dan naklen haber verdi. (Demişki): Bana Urve b. Zübeyr, Nebi (Sallallahu Aleyhi ve Sellem)'in zevcesi Âişe'den naklen haber verdi ki: Nebi (Sallallahu Aleyhi ve Sellem) zamanında Fetih gazasında hırsızlık eden kadının hali Kureyş'i üzmüş de : Bunun hakkında Resulullah (Sallallahu Aleyhi ve Sellem)'le kim konuşacak? demişler. (Bâzıları): Buna kim cesaret edebilir! Meğer ki Resûlullah (Sallallahu Aleyhi ve Sellem)'in habîbi Usâme ola! demişler. Bunun üzerine kadın Resûlullah (Sallallahu Aleyhi ve Sellem)'e getirilerek onun hakkında kendileri ile Usâme b. Zeyd konuşmuş. Derken Resûlullah (Sallallahu Aleyhi ve Sellem)'in yüzü renklenmiş; ve : «Allah'ın hadlerinden bir hadd hakkında şefâaf mı ediyorsun?» buyurmuş. Bunun üzerine Usâme kendilerine : — Benim için mağfiret dile yâ Resûlâllah! demiş. Akşam olunca Resûlullah (Sallallahu Aleyhi ve Sellem) ayağa kalkarak hutbe okumuş: Allah'a gerektiği gibi senada bulunmuş. Sonra şunları söylemiş: «Bundan sonra (malum ola ki) : (Allah) sizden öncekileri ancak şunun için helak etmiştir ki, onlar aralarından şerefli biri hırsızlık ederse onu bırakırlar; zayıf olan çalarsa üzerine haddi tatbik ederlerdi. Hiç şüphe yoîc ki ben —nefsim yed-i kudretinde bulunan Allah'a yemin olsun!— Muhammed'İn kızı Fâtıme hırsızlık etse mutlaka elini keserdim!» Bundan sonra emir buyurmuş ve hırsızlık eden o kadının eli kesilmiş. Yûnus şunları söylemiş: İbni Şihâb dedi ki: Urve şunu söyledi: Aişc: — Sonraları kadın güzelce tevbe etti; ve evlendi. Bu işten sonra bana gelir; ben de onun hacetini Resûlullah (Sallallahu Aleyhi ve Sellem)'e arz ederdim.» dedi
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4411</td></tr><tr><td>Arabic No</td><td>1688.02</td></tr><tr><td>Reference</td><td>Book 29 Hadith 14</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
یونس بن یزید نے مجھے ابن شہاب سے خبر دی ، انہوں نے کہا : مجھے عروہ بن زبیر نے نبی صلی اللہ علیہ وسلم کی زوجہ محترمہ حضرت عائشہ رضی اللہ عنہا سے خبر دی کہ قریش کو اس عورت کے معاملے نے فکر مند کیا جس نے رسول اللہ صلی اللہ علیہ وسلم کے عہد میں ، غزوہ فتح مکہ ( کے دنوں ) میں چوری کی تھی ۔ انہوں نے کہا : اس کے بارے میں رسول اللہ صلی اللہ علیہ وسلم سے کون بات کرے گا؟ ( کچھ ) لوگوں نے کہا : رسول اللہ صلی اللہ علیہ وسلم کے چہیتے اسامہ بن زید رضی اللہ عنہ ہی اس کی جراءت کر سکتے ہیں ۔ وہ عورت رسول اللہ صلی اللہ علیہ وسلم کے سامنے پیش کی گئی تو حضرت اسامہ بن زید رضی اللہ عنہ نے اس کے بارے میں بات کی ، اس پر رسول اللہ صلی اللہ علیہ وسلم کے چہرہ مبارک کا رنگ بدل گیا اور فرمایا : "" کیا تم اللہ کی حدود میں سے ایک حد کے بارے میں سفارش کر رہے ہو؟ "" تو حضرت اسامہ رضی اللہ عنہ نے عرض کی : اللہ کے رسول! میرے لئے مغفرت طلب کیجیے ۔ جب شام کا وقت ہوا تو رسول اللہ صلی اللہ علیہ وسلم اٹھے ، خطبہ دیا ، اللہ کے شایانِ شان اس کی ثنا بیان کی ، پھر فرمایا : "" امام بعد! تم سے پہلے لوگوں کو اسی چیز نے ہلاک کر ڈالا کہ جب ان میں سے کوئی معزز انسان چوری کرتا تو وہ اسے چھوڑ دیتے اور جب کمزور چوری کرتا تو اس پر حد نافذ کر دیتے اور میں ، اس ذات کی قسم جس کے ہاتھ میں میری جان ہے! اگر فاطمہ بنت محمد بھی چوری کرتی تو اس کا ( بھی ) ہاتھ کاٹ دیتا ۔ "" پھر آپ صلی اللہ علیہ وسلم نے اس عورت کے بارے میں حکم دیا جس نے چوری کی تھی تو اس کا ہاتھ کاٹ دیا گیا ۔ یونس نے کہا : ابن شہاب نے کہا : عروہ نے کہا : حضرت عائشہ رضی اللہ عنہا نے کہا : اس کے بعد اس کی توبہ ( اللہ کی طرف توجہ بہت ) اچھی ( ہو گئی ) اور اس نے شادی کر لی اور اس کے بعد وہ میرے پاس آتی تھی تو میں اس کی ضرورت رسول اللہ صلی اللہ علیہ وسلم کے سامنے پیش کرتی تھی ۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4411</td></tr><tr><td>Arabic No</td><td>1688.02</td></tr><tr><td>Reference</td><td>Book 29 Hadith 14</td></tr></tbody></table></div>