## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا أَبُو كُرَيْبٍ، حَدَّثَنَا يَحْيَى بْنُ عَبْدِ الرَّحْمَنِ الأَرْحَبِيُّ، حَدَّثَنَا يُونُسُ بْنُ أَبِي الْيَعْفُورِ، عَنْ أَبِيهِ، عَنِ ابْنِ عُمَرَ، قَالَ دَخَلَ عَلَيْهِ عُمَرُ وَهُوَ عَلَى مَائِدَتِهِ فَأَوْسَعَ لَهُ عَنْ صَدْرِ الْمَجْلِسِ فَقَالَ بِسْمِ اللَّهِ ‏.‏ ثُمَّ ضَرَبَ بِيَدِهِ فَلَقِمَ لُقْمَةً ثُمَّ ثَنَّى بِأُخْرَى ثُمَّ قَالَ إِنِّي لأَجِدُ طَعْمَ دَسَمٍ مَا هُوَ بِدَسَمِ اللَّحْمِ ‏.‏ فَقَالَ عَبْدُ اللَّهِ يَا أَمِيرَ الْمُؤْمِنِينَ إِنِّي خَرَجْتُ إِلَى السُّوقِ أَطْلُبُ السَّمِينَ لأَشْتَرِيَهُ فَوَجَدْتُهُ غَالِيًا فَاشْتَرَيْتُ بِدِرْهَمٍ مِنَ الْمَهْزُولِ وَحَمَلْتُ عَلَيْهِ بِدِرْهَمٍ سَمْنًا فَأَرَدْتُ أَنْ يَتَرَدَّدَ عِيَالِي عَظْمًا عَظْمًا ‏.‏ فَقَالَ عُمَرُ مَا اجْتَمَعَا عِنْدَ رَسُولِ اللَّهِ ـ صلى الله عليه وسلم ـ قَطُّ إِلاَّ أَكَلَ أَحَدَهُمَا وَتَصَدَّقَ بِالآخَرِ ‏.‏ قَالَ عَبْدُ اللَّهِ خُذْ يَا أَمِيرَ الْمُؤْمِنِينَ فَلَنْ يَجْتَمِعَا عِنْدِي إِلاَّ فَعَلْتُ ذَلِكَ ‏.‏ قَالَ مَا كُنْتُ لأَفْعَلَ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Daif</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3361</td></tr><tr><td>Arabic No</td><td>3361</td></tr><tr><td>Reference</td><td>Book 29 Hadith 111</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
১/৩৩৬১। ইবনে উমার (রাঃ) থেকে বর্ণিত। তিনি বলেন যে, তিনি আহাররত অবস্থায় উমার (রাঃ) তার ঘরে প্রবেশ করলেন। তিনি তাকে আহারের মজলিসে মধ্যখানে জায়গা করে দিলেন। তিনি বিসমিল্লাহ বলে খাবারের পাত্রে হাত দিলেন এবং এক গ্রাস তুলে দিলেন, অতঃপর দ্বিতীয় গ্রাস তুলে নিয়ে বলেনঃ আমি তৈলাক্ত জিনিসের স্বাদ পাচ্ছি এবং তা গোশতের চর্বি নয়। আবদুল্লাহ (রাঃ) বলেন, হে আমীরুল মুমিনীন! আমি মোটা গোশত ক্রয়ের উদ্দেশে বাজারে গিয়েছিলাম, কিন্তু তার চড়া দাম দেখে এক দিরহামের শীর্ণকায় পশুর গোশত ক্রয় করে এবং এক দিরহামের ঘি ক্রয় করে তা ঐ গোশতের মধ্যে ঢেলে দিয়েছি। আমি চাচ্ছিলাম যে, পরিবারের সকলের ভাগে অন্তত একটি করে হাড় পড়ুক। উমার (রাঃ) বলেন, রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর নিকট ঘি ও গোশত একত্রে উপস্থিত করা হলে, তিনি তার একটি আহার করতেন এবং অন্যটি দান-খয়রাত করতেন। আবদুল্লাহ (রাঃ) বলেন, হে আমীরুল মুমিনীন! আহার করুন। পুনরায় কখনও ঘি ও গোশত একত্র হলে আমিও তাই করবো। উমার (রাঃ) বলেন, আমি কখনও খাবো না।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Daif</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3361</td></tr><tr><td>Arabic No</td><td>3361</td></tr><tr><td>Reference</td><td>Book 29 Hadith 111</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
It was narrated that Ibn ‘Umar said that ‘Umar entered upon him when he was eating, and he made room for him in the middle of the gathering. He said:Bismillah, then he took a morsel and ate it, then a second. Then he said: “I notice some fat in the food but it is not the fat of the meat.” ‘Abdullah said: “O Commander of the Believers! I went out to the marketplace looking for some fatty meat (bones with plenty of meat on them) to buy, but it was expensive, so I bought some lean meat (bones with not much meat on them) for a Dirham, and added a Dirham’s worth of ghee. I wanted my family to go through it bone by bone.” ‘Umar said: “The Messenger of Allah (ﷺ) never had these two things together; he would eat one and give the other in charity.”
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Daif</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3361</td></tr><tr><td>Arabic No</td><td>3361</td></tr><tr><td>Reference</td><td>Book 29 Hadith 111</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Abu Kuraib] telah menceritakan kepada kami [Yahya bin Abdurrahman Al Arhabi] telah menceritakan kepada kami [Yunus bin Abu Al Ya'fur] dari [Ayahnya] dari [Ibnu Umar] mengatakan, bahwa Umar datang kepadanya saat ia berada di meja makannya. Ia lalu memberi tempat duduk kepadanya, Umar lalu mengucapkan 'Bismillah' seraya mengambil satu suapan dan mengambil lagi. Kemudian Umar berkata, "Sesungguhnya aku merasakan rasa lemak, tetapi bukan lemak daging." Abdullah berkata, "Wahai Amirul Mukminin, tadi aku keluar ke pasar untuk membeli minyak samin, namun aku mendapatkan harganya terlalu mahal, maka aku membeli tulang yang ada sedikit daging dengan harga satu dirham dan mencampurnya dengan sedirham samin, karena aku ingin anak-anakku bergantian mendapatkan satu tulang-satu tulang." Maka [Umar] berkata, "Tidak pernah sama sekali Rasulullah shallallahu 'alaihi wasallam mendapatkan ini kecuali beliau memakan salah satunya dan bersedekah dengan yang lainnya." Maka Abdullah berkata, "Ambillah wahai Amirul Mukminin, sekali-kali tidak akan menjadi satu di hadapanku kecuali aku akan melakukan seperti itu." Umar berkata, "Aku tidak akan melakukannya
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Daif</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3361</td></tr><tr><td>Arabic No</td><td>3361</td></tr><tr><td>Reference</td><td>Book 29 Hadith 111</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
İbn-i Ömer (r.a.)'den rivayet edildiğine göre: Bir gün kendisi sofrası üstünde (yemekte) iken Ömer (bin el-Hattâb) (r.a.) onun yanına giriyor. Abdullah sofranın baş kısmında Ömer için yer açıyor. Ömer de: Bismillah diyerek elini vurup bir lokma alıyor. Sonra diğer bir lokma ile ikiliyor, (yâni ikinci bir lokmayı alıyor). Sonra Ömer (r.a.): Ben bir yağ tadını cidden buluyorum. Bu, et yağı değildir, deyince Abdullah (r.a.): Ey mu'minlerin emîri, ben çarşıya çıkıp satınalayım diye semiz et aradım. Fakat bunu pahalı bulunca bir dirhem ile zayıf et aldım ve üstüne bir dirhemlik yağ koydum. Böylece aile ferdlerimin kemiklerden yararlanmasını istedim, diyor. Bunun üzerine Ömer (r.a.) : Resulullah (Sallallahu Aleyhi ve Sellem)'in yanında et ve yağ birleştiği her zaman O. mutlaka birini yemiş, diğerini de sadaka etmiş (ikisini yediği kat'iyen vâki olmamıştır), diyor. Abdullah (r.a.): Ey mu'minlerin emîr'i (bu defa) al. Bundan sonra et ve yağ benim yanımda birleştiğinde mutlaka bunu yapacağım, diyor. Fakat Ömer (r.a.): Ben yapacak değilim (Yâni bu yemeği yemem), diyor. Not: ZevA.id'de şöyle denilmiştir: Bu, hasen bIr seneddlr. Bu senedde Yahya bin Abdirrahman bin Ubeyd bulunur
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Daif</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3361</td></tr><tr><td>Arabic No</td><td>3361</td></tr><tr><td>Reference</td><td>Book 29 Hadith 111</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
عبداللہ بن عمر رضی اللہ عنہما کہتے ہیں کہ ان کے پاس عمر رضی اللہ عنہ تشریف لائے اور وہ اس وقت دستر خوان پر تھے، انہوں نے عمر رضی اللہ عنہ کے لیے مجلس کے درمیان میں جگہ بنائی، عمر رضی اللہ عنہ نے بسم اللہ کہا، پھر کھانے کی طرف ہاتھ بڑھایا، اور ایک لقمہ لیا، پھر دوسرا لقمہ لیا، پھر کہا: مجھے اس میں چکنائی کا ذائقہ مل رہا ہے، اور یہ چکنائی گوشت کی چربی نہیں ہے، عبداللہ بن عمر رضی اللہ عنہما نے کہا: اے امیر المؤمنین! میں فربہ گوشت کی تلاش میں بازار نکلا تاکہ اسے خریدوں، لیکن میں نے اسے مہنگا پایا تو ایک درہم میں دبلا گوشت خرید لیا، اور ایک درہم کا گھی خرید کر اس میں ملا دیا، اس سے میرا مقصد یہ تھا کہ ایک ایک ہڈی میرے تمام گھر والوں کے حصے میں آ جائے، اس پر عمر رضی اللہ عنہ نے کہا: جب کبھی بھی رسول اللہ صلی اللہ علیہ وسلم کے پاس یہ دونوں چیزیں بیک وقت اکٹھا ہوئیں تو آپ صلی اللہ علیہ وسلم نے ان میں سے ایک کھا لی، اور دوسری صدقہ کر دی۔ عبداللہ بن عمر رضی اللہ عنہما نے کہا: امیر المؤمنین! اب تو اسے کھا لیجئیے پھر جب کبھی میرے پاس یہ دونوں چیزیں اکٹھی ہوں گی میں بھی ایسا ہی کروں گا، عمر رضی اللہ عنہ بولے: میں اسے کھانے والا نہیں
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Daif</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3361</td></tr><tr><td>Arabic No</td><td>3361</td></tr><tr><td>Reference</td><td>Book 29 Hadith 111</td></tr></tbody></table></div>