## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا هِشَامُ بْنُ عَمَّارٍ، حَدَّثَنَا سُفْيَانُ، عَنِ الزُّهْرِيِّ، عَنْ أَبِي أُمَامَةَ بْنِ سَهْلِ بْنِ حُنَيْفٍ، قَالَ مَرَّ عَامِرُ بْنُ رَبِيعَةَ بِسَهْلِ بْنِ حُنَيْفٍ وَهُوَ يَغْتَسِلُ فَقَالَ لَمْ أَرَ كَالْيَوْمِ وَلاَ جِلْدَ مُخَبَّأَةٍ ‏.‏ فَمَا لَبِثَ أَنْ لُبِطَ بِهِ فَأُتِيَ بِهِ النَّبِيَّ ـ صلى الله عليه وسلم ـ فَقِيلَ لَهُ أَدْرِكْ سَهْلاً صَرِيعًا ‏.‏ قَالَ ‏"‏ مَنْ تَتَّهِمُونَ بِهِ ‏"‏ ‏.‏ قَالُوا عَامِرَ بْنَ رَبِيعَةَ ‏.‏ قَالَ ‏"‏ عَلاَمَ يَقْتُلُ أَحَدُكُمْ أَخَاهُ إِذَا رَأَى أَحَدُكُمْ مِنْ أَخِيهِ مَا يُعْجِبُهُ فَلْيَدْعُ لَهُ بِالْبَرَكَةِ ‏"‏ ‏.‏ ثُمَّ دَعَا بِمَاءٍ فَأَمَرَ عَامِرًا أَنْ يَتَوَضَّأَ فَيَغْسِلَ وَجْهَهُ وَيَدَيْهِ إِلَى الْمِرْفَقَيْنِ وَرُكْبَتَيْهِ وَدَاخِلَةَ إِزَارِهِ وَأَمَرَهُ أَنْ يَصُبَّ عَلَيْهِ ‏.‏ قَالَ سُفْيَانُ قَالَ مَعْمَرٌ عَنِ الزُّهْرِيِّ وَأَمَرَهُ أَنْ يَكْفَأَ الإِنَاءَ مِنْ خَلْفِهِ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3509</td></tr><tr><td>Arabic No</td><td>3509</td></tr><tr><td>Reference</td><td>Book 31 Hadith 74</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
৪/৩৫০৯। আবূ উমামা ইবনে হুনাইফ (রাঃ) থেকে বর্ণিত। তিনি বলেন, আমের ইবনে রবীআ (রাঃ) সাহল ইবনে হুনাইফ (রাঃ)-র নিকট দিয়ে যাচ্ছিলেন। তিনি তখন গোসল করছিলেন। আমের (রাঃ) বলেন, আমি এমন খুবসুরত সুপুরুষ দেখিনি, এমনকি পর্দানশীন নারীকেও এরূপ সুন্দর দেখিনি, যেমন আজ দেখলাম। অতঃপর কিছুক্ষণের মধ্যেই সাহল (রাঃ) বেহুঁশ হয়ে পড়ে গেলেন। তাকে নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম -এর নিকট নিয়ে যাওয়া হলো এবং তাঁকে বলা হলো, ধরাশায়ী সাহলকে রক্ষা করুন। তিনি জিজ্ঞেস করলেনঃ তোমরা কাকে অভিযুক্ত করছো? তারা বললো, আমের ইবনে রবীআকে। তিনি বলেনঃ তোমাদের কেউ বদনজর লাগিয়ে তার ভাইকে কেন হত্যা করতে চায়? তোমাদের কেউ তার ভাইয়ের মনোমুগ্ধকর কিছু দেখলে যেন তার জন্য বরকতের দোয়া করে। অতঃপর তিনি পানি নিয়ে ডাকলেন, অতঃপর আমেরকে উযু করতে নির্দেশ দিলেন। তিনি তার মুখমন্ডল, দু’ হাত কনুই পর্যন্ত, দু’ পা গোছা পর্যন্ত এবং লজ্জাস্থান ধৌত করলেন। তিনি আমেরকে পাত্রের পানি সকলের উপর ঢেলে দেয়ার নির্দেশ দিলেন। তিনি সাহলের পেছন দিক থেকে পানি ঢেলে দেয়ার জন্য আমেরকে নির্দেশ দেন।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3509</td></tr><tr><td>Arabic No</td><td>3509</td></tr><tr><td>Reference</td><td>Book 31 Hadith 74</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
It was narrated that Abu Umamah bin Sahl bin Hunaif said:“ ‘Amir bin Rabi’ah passed by Sahl bin Hunaif when he was having a bath, and said: ‘I have never seen such beautiful skin.’ Straightaway, he (Sahl) fell to the ground. He was brought to the Prophet (ﷺ) and it was said: ‘Sahl has had a fit.’ He said: ‘Whom do you accuse with regard to him?’ They said: “ ‘Amir bin Rabi’ah.’ They said: ‘Why would anyone of you kill his brother? If he sees something that he likes, then let him pray for blessing for him.’ Then he called for water, and he told ‘Amir to perform ablution, then he washed his face and his arms up to the elbows, his knees and inside his lower garment, then he told him to pour the water over him.”
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3509</td></tr><tr><td>Arabic No</td><td>3509</td></tr><tr><td>Reference</td><td>Book 31 Hadith 74</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Hisyam bin 'Ammar] telah menceritakan kepada kami [Sufyan] dari [Az Zuhri] dari [Abu Umamah bin Sahl bin Hunaif] dia berkata, "'Amir bin Rabi'ah melintasi Sahl bin Hunaif yang sedang mandi, lalu dia berkata, "Aku tidak pernah melihat seperti hari ini dan tidak ada kulit yang di sembunyikan." Maka tidak lama kemudian Sahl bin Hunaif pun pingsan. Kemudian ia di bawa ke hadapan Nabi shallallahu 'alaihi wasallam dan di katakan kepada beliau, "Sahl pingsan! " Beliau pun bertanya: "Siapakah yang menyerangnya?" Mereka menjawab, "'Amir bin Rabi'ah." Beliau bersabda: "Atas perkara apa seseorang dari kalian menyakiti saudaranya? Jika salah seorang dari kalian melihat sesuatu yang menakjubkan dari saudaranya, maka hendaknya ia mendo'akan keberkahan padanya." Kemudian beliau meminta air dan memerintahkan 'Amir untuk berwudlu, maka 'Amir lantas membasuh muka dan kedua tangannya sampai siku, kedua mata kaki dan apa yang ada di dalam bajunya. Setelah itu Rasulullah shallallahu 'alaihi wasallam memerintahkan untuk menyiram Sahl (dengan bekas air wudlu 'Amir)." [Sufyan] berkata; [Ma'mar] berkata dari [Az Zuhri], "Beliau memerintahkan supaya menuangkan tempat air tersebut dari belakang tubuh 'Amir
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3509</td></tr><tr><td>Arabic No</td><td>3509</td></tr><tr><td>Reference</td><td>Book 31 Hadith 74</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Sehl bin Huneyf'in oğlu Ebu Ümâme (r.a.)'dan; Şöyle demiştir: (Babam) Sehl bin Huneyf yıkanırken yanından Âmir bin Rebia geçti ve (onun vücûdunun güzelliğini kasdederek): Henüz evlenmemiş örtülü genç kızın cildi dâhil bugünkü gibi (hiç bir güzel) görmedim, dedi. Bu lâftan hemen sonra Sehl bin Huneyf yere yıkıldı. Bunun üzerine Sehl, Nebi (Sallallahu Aleyhi ve Sellem)'e götürülüp O'na: (Yâ Resulallah)! Nazar çarpması nedeniyle yere yıkılmış vaziyette Sehl'e yetiş, denildi. Resûl-i Ekrem (Sallallahu Aleyhi ve Sellem): «Kimden şüpheleniyorsunuz?» buyurdu. Onlar: Âmir bin Rebia, dediler. Resûl-i Ekrem (Sallallahu Aleyhi ve Sellem) (Âmir'i azarlayarak): «Neye binâen biriniz (din) kardeşini öldürüyor? Biriniz (din) kardeşinden beğendiği - hayran kaldığı bir şey gördüğü zaman ona mübarek olması için duâ etsin» buyurdu. Sonra bir mikdar su istedi ve Âmir'e abdest almasını emretti. Âmir de yüzünü, dirseklerine kadar kollarını, dizlerini ve peştemalının içindekini (yâni belden aşağıyı) yıkadı ve Nebi (Sallallahu Aleyhi ve Sellem) (bir kabta biriken bu suyu) başına dökmesini Âmir'e emretti. (Râvilerden) Süfyân demiştir ki: Mamer'in Zührî'den rivayetine göre: Ve Nebi (Sallallahu Aleyhi ve Sellem) o kabı onun arkasında ters çevirip yere koymasını Âmir'e emretti
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3509</td></tr><tr><td>Arabic No</td><td>3509</td></tr><tr><td>Reference</td><td>Book 31 Hadith 74</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ابوامامہ بن سہل بن حنیف رضی اللہ عنہ کہتے ہیں کہ عامر بن ربیعہ رضی اللہ عنہ کا گزر سہل بن حنیف رضی اللہ عنہ ( ابوامامہ کے باپ ) کے پاس ہوا، سہل رضی اللہ عنہ اس وقت نہا رہے تھے، عامر نے کہا: میں نے آج کے جیسا پہلے نہیں دیکھا، اور نہ پردہ میں رہنے والی کنواری لڑکی کا بدن ایسا دیکھا، سہل رضی اللہ عنہ یہ سن کر تھوڑی ہی دیر میں چکرا کر گر پڑے، تو انہیں نبی اکرم صلی اللہ علیہ وسلم کی خدمت میں لایا گیا، اور عرض کیا گیا کہ سہل کی خبر لیجئیے جو چکرا کر گر پڑے ہیں، آپ صلی اللہ علیہ وسلم نے پوچھا: تم لوگوں کا گمان کس پر ہے ؟ لوگوں نے عرض کیا کہ عامر بن ربیعہ پر، آپ صلی اللہ علیہ وسلم نے فرمایا: کس بنیاد پر تم میں سے کوئی اپنے بھائی کو قتل کرتا ہے ، جب تم میں سے کوئی شخص اپنے بھائی کی کسی ایسی چیز کو دیکھے جو اس کے دل کو بھا جائے تو اسے اس کے لیے برکت کی دعا کرنی چاہیئے، پھر آپ صلی اللہ علیہ وسلم نے پانی منگوایا، اور عامر کو حکم دیا کہ وضو کریں، تو انہوں نے اپنا چہرہ اپنے دونوں ہاتھ کہنیوں تک، اور اپنے دونوں گھٹنے اور تہبند کے اندر کا حصہ دھویا، اور آپ صلی اللہ علیہ وسلم نے انہیں سہل رضی اللہ عنہ پر وہی پانی ڈالنے کا حکم دیا۔ سفیان کہتے ہیں کہ معمر کی روایت میں جو انہوں نے زہری سے روایت کی ہے اس طرح ہے: آپ صلی اللہ علیہ وسلم نے انہیں حکم دیا کہ وہ برتن کو ان کے پیچھے سے ان پر انڈیل دیں ۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3509</td></tr><tr><td>Arabic No</td><td>3509</td></tr><tr><td>Reference</td><td>Book 31 Hadith 74</td></tr></tbody></table></div>