## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا مُحَمَّدُ بْنُ أَبِي عُمَرَ الْعَدَنِيُّ، حَدَّثَنَا فَرَجُ بْنُ سَعِيدِ بْنِ عَلْقَمَةَ بْنِ سَعِيدِ بْنِ أَبْيَضَ بْنِ حَمَّالٍ، حَدَّثَنِي عَمِّي، ثَابِتُ بْنُ سَعِيدِ بْنِ أَبْيَضَ بْنِ حَمَّالٍ عَنْ أَبِيهِ، سَعِيدٍ عَنْ أَبِيهِ، أَبْيَضَ بْنِ حَمَّالٍ ‏.‏ أَنَّهُ اسْتَقْطَعَ الْمِلْحَ الَّذِي يُقَالُ لَهُ مِلْحُ سَدِّ مَأْرِبٍ ‏.‏ فَأَقْطَعَهُ لَهُ ثُمَّ إِنَّ الأَقْرَعَ بْنَ حَابِسٍ التَّمِيمِيَّ أَتَى رَسُولَ اللَّهِ صلى الله عليه وسلم فَقَالَ يَا رَسُولَ اللَّهِ إِنِّي قَدْ وَرَدْتُ الْمِلْحَ فِي الْجَاهِلِيَّةِ وَهُوَ بِأَرْضٍ لَيْسَ بِهَا مَاءٌ وَمَنْ وَرَدَهُ أَخَذَهُ وَهُوَ مِثْلُ الْمَاءِ الْعِدِّ ‏.‏ فَاسْتَقَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم أَبْيَضَ بْنَ حَمَّالٍ فِي قَطِيعَتِهِ فِي الْمِلْحِ ‏.‏ فَقَالَ قَدْ أَقَلْتُكَ مِنْهُ عَلَى أَنْ تَجْعَلَهُ مِنِّي صَدَقَةً ‏.‏ فَقَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏ "‏ هُوَ مِنْكَ صَدَقَةٌ وَهُوَ مِثْلُ الْمَاءِ الْعِدِّ مَنْ وَرَدَهُ أَخَذَهُ ‏"‏ ‏.‏ قَالَ فَرَجٌ وَهُوَ الْيَوْمَ عَلَى ذَلِكَ مَنْ وَرَدَهُ أَخَذَهُ ‏.‏ قَالَ فَقَطَعَ لَهُ النَّبِيُّ صلى الله عليه وسلم أَرْضًا وَنَخْلاً بِالْجُرْفِ جُرْفِ مُرَادٍ مَكَانَهُ حِينَ أَقَالَهُ مِنْهُ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Hasan</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Daif</td><td>Shuaib Al Arnaut</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2475</td></tr><tr><td>Arabic No</td><td>2475</td></tr><tr><td>Reference</td><td>Book 16 Hadith 40</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
১/২৪৭৫। আবয়াদ ইবনে হাম্মাল (রাঃ) থেকে বর্ণিত। তিনি সাদ্দ মা‘রিব নামক লবণ খনিটি জায়গিররূপে প্রার্থনা করলেন। নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম তাকে সেটি জায়গিররূপে দান করলেন। অতঃপর আকরা ইবনে হাবিস আত-তামীমী (রাঃ) রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর নিকট এসে বলেন, ইয়া রাসূলুল্লাহ! জাহিলী যুগে আমি লবণের খনিটিতে গিয়েছিলাম। ঐ এলাকায় কোন পানি নাই। যে ব্যক্তিই সেখানে যায় সে-ই কিছু লবণ সংগ্রহ করে নেয়। তা প্রবাহিত পানির মতই পর্যাপ্ত। (এ কথা শুনে) রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম আবয়াদ বিন হাম্মালের নিকট লবনের চুক্তির প্রত্যাহার চাইলেন।আব্য়াদ ইবনে হাম্মাল বলেন, আমি আপনার সাথে চুক্তি রদ করতে প্রস্তুত এই শর্তে যে, সেটিকে আপনি আমার পক্ষ থেকে দানরূপে গণ্য করবেন। রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেনঃ তা তোমার পক্ষ থেকে দান হিসাবেই গণ্য হবে। আর তা প্রবহমান পানির ন্যায়, যে-ই সেখানে যাবে তা নিতে পারবে। অধস্তন রাবী ফারাজ ইবনে সাঈদ (রাঃ) বলেন, সেটা বর্তমানেও সেভাবেই আছে। যে-ই সেখানে যায়, সে তা থেকে সংগ্রহ করে। তিনি বলেন, নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম তার থেকে সেটি ফেরত নেয়ার বিনিময়ে তাকে জুরুফ মুরাদ নামক স্থানের এক খন্ড কৃষিভূমি ও একটি খেজুর বাগান জায়িগিররূপে দান করেন।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Hasan</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Daif</td><td>Shuaib Al Arnaut</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2475</td></tr><tr><td>Arabic No</td><td>2475</td></tr><tr><td>Reference</td><td>Book 16 Hadith 40</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
It was narrated from Abyad bin Hammal:That he asked for a salt flat called the Ma'rib Dam to be given to him, and it was given to him. Then Aqra bin Habis At-Tamimi came to the Messenger of Allah (ﷺ) and said: “O Messenger of Allah (ﷺ), I used to come to the salt flat during the Ignorance period and it was in a land in which there was no water, and whoever came to it took from it. It was (plentiful) like flowing water.” So the Messenger of Allah (ﷺ) asked Abyad bin Hammal to give back his share of the salt flat. He said: “I give it to you on the basis that you make it charity given by me.” The Messenger of Allah said: “It is a charity from you, and it is like flowing water, whoever comes to it may take from it.”(One of the narrators) Faraj said: “That is how it is today, whoever comes to it takes from it.” He said: “The Prophet (ﷺ) gave him land and palm trees in Jurf Murad instead, when he took back the salt flat from him.”
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Hasan</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Daif</td><td>Shuaib Al Arnaut</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2475</td></tr><tr><td>Arabic No</td><td>2475</td></tr><tr><td>Reference</td><td>Book 16 Hadith 40</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Muhammad bin Abu Umar Al 'Adani] berkata, telah menceritakan kepada kami [Faraj bin Sa'id bin Alqamah bin Sa'id bin Abyadl bin Hammal] berkata, telah menceritakan kepadaku pamanku [Tsabit bin Sa'id bin Abyadl bin Hammal] dari [Bapaknya] dari [Abyadl bin Hammal] bahwa ia pernah mengumpulkan garam yang disebut dengan garam bendungan Ma'rib, ia mengumpulkan untuk dirinya sendiri. Kemudian Al Aqra' bin Habis At Tamimi mendatangi Rasulullah shallallahu 'alaihi wasallam dan berkata, "Wahai Rasulullah, aku pernah melewati (kumpulan) garam di masa jahiliyah, ia terdapat di suatu daerah yang tidak berair. Siapa saja yang mendatanginya ia bebas untuk mengambilnya, ia seperti air yang mengalir." Maka Rasulullah shallallahu 'alaihi wasallam kemudian meminta pembatalan Abyadl bin Hammal dari garam yang dikumpulkan, Ia lalu berkata, "Aku telah merelakan pembatalan itu dengan syarat Tuan jadikan sebagai (pahala) sedekah dariku." Rasulullah shallallahu 'alaihi wasallam menjawab: "Ia adalah sedekah darimu, dan ia seperti air yang mengalir. Barangsiapa mendatanginya maka ia bebas mengambilnya." Faraj berkata, "Hari ini masih berlaku seperti dulu, siapa yang melewatinya bebas untuk mengambilnya." Ia (perawi) berkata, "Lalu Nabi shallallahu 'alaihi wasallam memberikan bagian tanah dan pohon kurma di Jauf. Jauf adalah tempat saat ia memberi pembatalan kepada Rasulullah
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Hasan</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Daif</td><td>Shuaib Al Arnaut</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2475</td></tr><tr><td>Arabic No</td><td>2475</td></tr><tr><td>Reference</td><td>Book 16 Hadith 40</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ebyad bin Hammâl (r.a.)'den rivayet edildiğine göre: Kendisi Me'rib Şeddi Tuzlası denilen tuzlayı (bağış veya satış yoluyla Resul-i Ekrem (Sallallahu Aleyhi ve Sellem)'den) istedi. (Resulullah (Sallallahu Aleyhi ve Sellem) de) bu tuzlayı kendisine verdi. Sonra el-Akra' bin Habis et-Temîmî (r.a.) Resulullah (Sallallahu Aleyhi ve Sellem)'in yanına vararak: Yâ Resûlallah! Ben câhiliyet devrinde (yâni müslüman olmadan önce) o tuzlaya vardım (gördüm). O tuzla susuz bîr arazidedir. Kim oraya varırsa tuz alır. Ve o tuz kesintisiz su gibidir (devamlı bulunur), dedi. Bunun üzerine Resulullah (Sallallahu Aleyhi ve Sellem) Ebyad bin Hammâl'den bu tuzla tahsis akdini kaldırmasını istedi. Ebyad bin Hammâl da (Resulullah (Sallallahu Aleyhi ve Sellem)'e): Anılan tuzlayı (ben(im tarafım)dan bir sadaka kılman üzere tahsis akdini kaldırmak hususunda senin isteğini kabul ettim, dedi. Resûl-i Ekrem (Sallallahu Aleyhi ve Sellem) de: «O (tuzla) senden bir sadakadır ve kesintisiz devam eden su mislidir. Kim ona varırsa onu(n tuzunu) alabilir (Yâni müslümanlarm müşterek malıdır) buyurdu. (Müellifimizin şeyhinin şeyhi) Ferec (bin Saîd): O tuzla bugün de o durum üzerinedir. Kim ona vardıysa onu(n tuzunu) alır, demiştir. (Râvî) demiştir ki: Ebyad bin Hammâl tuzlanın tahsis akdini kaldırmakla Resûl-i Ekrem (Sallallahu Aleyhi ve Sellem)'in isteğini kabul edince Peygamber (Sallallahu Aleyhi ve,Sellem) bu (tuzla)nın yerine kendisine Cürf-i Mürâd'da bir arazi ve hurma ağaçlarını verdi. EBU DAVUD HADİSİ VE İZAH İÇİN TIKLA
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Hasan</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Daif</td><td>Shuaib Al Arnaut</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2475</td></tr><tr><td>Arabic No</td><td>2475</td></tr><tr><td>Reference</td><td>Book 16 Hadith 40</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ابیض بن حمال رضی اللہ عنہ سے روایت ہے کہ انہوں نے اس نمک کو جو نمک سدمآرب کے نام سے جانا جاتا ہے رسول اللہ صلی اللہ علیہ وسلم سے بطور جاگیر طلب کیا، تو آپ صلی اللہ علیہ وسلم نے اسے انہیں جاگیر میں دے دیا، پھر اقرع بن حابس تمیمی رضی اللہ عنہ رسول اللہ صلی اللہ علیہ وسلم کے پاس آئے، اور عرض کیا: میں زمانہ جاہلیت میں اس نمک کی کان پر سے گزر چکا ہوں، وہ ایسی زمین میں ہے جہاں پانی نہیں ہے، جو وہاں جاتا ہے، وہاں سے نمک لے جاتا ہے، وہ بہتے پانی کی طرح ہے، جس کا سلسلہ کبھی بند نہیں ہوتا، یہ سن کر رسول اللہ صلی اللہ علیہ وسلم نے ابیض بن حمال سے نمک کی اس جاگیر کو فسخ کر دینے کو کہا، ابیض رضی اللہ عنہ نے عرض کیا: میں اس کو اس شرط پر فسخ کرتا ہوں کہ آپ صلی اللہ علیہ وسلم اسے میری طرف سے صدقہ کر دیں، رسول اللہ صلی اللہ علیہ وسلم نے فرمایا: اچھا وہ تمہاری طرف سے صدقہ ہے اور وہ جاری پانی کے مثل ہے، جو آئے اس سے لے جائے ۔ فرج بن سعید کہتے ہیں: اور وہ آج تک ویسے ہی ہے، جو وہاں جاتا ہے اس میں سے نمک لے جاتاہے۔ ابیض رضی اللہ عنہ کہتے ہیں: پھر نبی اکرم صلی اللہ علیہ وسلم نے انہیں اس جاگیر کے عوض جو آپ نے فسخ کر دی تھی «جرف» یعنی «جرف» مراد ( ایک مقام کا نام ہے ) میں زمین اور کھجور کے کچھ درخت جاگیر کے طور پر دیے۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Hasan</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Daif</td><td>Shuaib Al Arnaut</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2475</td></tr><tr><td>Arabic No</td><td>2475</td></tr><tr><td>Reference</td><td>Book 16 Hadith 40</td></tr></tbody></table></div>