## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا أَبُو بَكْرِ بْنُ أَبِي شَيْبَةَ، حَدَّثَنَا زَيْدُ بْنُ الْحُبَابِ، حَدَّثَنَا مُوسَى بْنُ عُبَيْدَةَ، حَدَّثَنِي سَعِيدُ بْنُ أَبِي سَعِيدٍ، عَنِ الأَدْرَعِ السُّلَمِيِّ، قَالَ جِئْتُ لَيْلَةً أَحْرُسُ النَّبِيَّ ـ صلى الله عليه وسلم ـ فَإِذَا رَجُلٌ قِرَاءَتُهُ عَالِيَةٌ فَخَرَجَ النَّبِيُّ ـ صلى الله عليه وسلم ـ فَقُلْتُ يَا رَسُولَ اللَّهِ هَذَا مُرَاءٍ ‏.‏ قَالَ فَمَاتَ بِالْمَدِينَةِ فَفَرَغُوا مِنْ جِهَازِهِ فَحَمَلُوا نَعْشَهُ فَقَالَ النَّبِيُّ ـ صلى الله عليه وسلم ـ ‏"‏ ارْفُقُوا بِهِ رَفَقَ اللَّهُ بِهِ إِنَّهُ كَانَ يُحِبُّ اللَّهَ وَرَسُولَهُ ‏"‏ ‏.‏ قَالَ وَحَفَرَ حُفْرَتَهُ فَقَالَ ‏"‏ أَوْسِعُوا لَهُ وَسَّعَ اللَّهُ عَلَيْهِ ‏"‏ ‏.‏ فَقَالَ بَعْضُ أَصْحَابِهِ يَا رَسُولَ اللَّهِ لَقَدْ حَزِنْتَ عَلَيْهِ ‏.‏ فَقَالَ ‏"‏ أَجَلْ إِنَّهُ كَانَ يُحِبُّ اللَّهَ وَرَسُولَهُ ‏"‏ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Daif</td><td>Shuaib Al Arnaut</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1559</td></tr><tr><td>Arabic No</td><td>1559</td></tr><tr><td>Reference</td><td>Book 6 Hadith 127</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
১/১৫৫৯। আল-আদরাআ আস-সুলামী (রাঃ) থেকে বর্ণিত। তিনি বলেন, আমি এক রাতে নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম -কে পাহারা দিতে আসলাম। এক ব্যক্তি উচ্চ কন্ঠে কুরআন পড়ছিলো। নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বেরিয়ে এলে আমি বললাম, হে আল্লাহর রাসূল! এ ব্যক্তি তো রিয়াকার। রাবী বলেন, লোকটি মাদ্বীনায় মারা গেলে লোকজন তার দাফন-কাফনে শংকাগ্রস্ত হয়ে পড়লো। তারা তার লাশ বহন করে নিয়ে গেলো। নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বললেনঃ তোমরা তার প্রতি সদয় হও, আল্লাহ তার প্রতি সদয় হয়েছেন। কারণ সে আল্লাহ্ ও তাঁর রাসূলকে ভালোবাসতো। রাবী বলেন, তার কবর খনন করলে নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেনঃ তার কভর আরো প্রশস্ত করো। আল্লাহ্ তাঁর প্রতি সদয় হয়েছেন। তাঁর কোন সাহাবী বলেন, ইয়া রাসূলাল্লাহ্! আপনি নিশ্চয় তার ব্যাপারে চিন্তান্বিত। তিনি বলেনঃ হ্যাঁ, নিশ্চয় সে আল্লাহ্ ও তাঁর রাসূলকে ভালোবাসতো।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Daif</td><td>Shuaib Al Arnaut</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1559</td></tr><tr><td>Arabic No</td><td>1559</td></tr><tr><td>Reference</td><td>Book 6 Hadith 127</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
It was narrated that Adra’ As-Sulami said:“I came one night to guard the Prophet (ﷺ), and there was a man reciting loudly. The Prophet (ﷺ) came out and I said: ‘O Messenger of Allah, this man is showing off.’ Then he died in Al-Madinah, and they finished preparing him, then they carried his dead body. The Prophet (ﷺ) said: ‘Be gentle with him, may Allah be gentle with him, for he loved Allah and His Messenger.’ Then his grave was dug and he (the Prophet (ﷺ)) said: ‘Make it spacious for him, and may Allah make it spacious for him.’ Some of his Companions said: ‘O Messenger of Allah, you are grieving for him.’ He said: ‘Yes indeed, for he loved Allah and His Messenger.’”
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Daif</td><td>Shuaib Al Arnaut</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1559</td></tr><tr><td>Arabic No</td><td>1559</td></tr><tr><td>Reference</td><td>Book 6 Hadith 127</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Abu Bakr bin Abu Syaibah] telah menceritakan kepada kami [Zaid bin Al Hubab] berkata, telah menceritakan kepada kami [Musa bin Ubaidah] berkata, telah menceritakan kepadaku [Sa'id bin Abu Sai'd] dari [Al Adra' As Sulami] ia berkata, "Suatu malam aku datang untuk menjaga Nabi shallallahu 'alaihi wasallam, tiba-tiba ada seorang laki-laki yang bacaannya sangat tinggi, hingga Nabi shallallahu 'alaihi wasallam keluar. Aku berkata, "Ya Rasulullah, orang ini telah berbuat riya. " Al Adra' berkata, "Lalu lelaki itu meninggal di Madinah. Ketika telah selesai mengurusi jenazahnya, mereka pun membawa jenazahnya. Nabi shallallahu 'alaihi wasallam kemudian bersabda: "Berlaku lembutlah kepadanya, semoga Allah memperlakukannya dengan lembut. Sesungguhnya dia mencintai Allah dan Rasul-Nya. " Al Adra' menuturkan; "Beliau lalu menggali kuburannya. Beliau bersabda: "Lapangkan kuburnya, semoga Allah melapangkannya. " Sebagian sahabat bertanya: "Wahai Rasulullah, apakah engkau merasa sedih?" beliau menjawab: "Benar, sebab ia seorang yang mencintai Allah dan Rasul-Nya
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Daif</td><td>Shuaib Al Arnaut</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1559</td></tr><tr><td>Arabic No</td><td>1559</td></tr><tr><td>Reference</td><td>Book 6 Hadith 127</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
el-Edra es-Sülemi (r.a.)'den şöyle demiştir: Bir gece Nebi (Sallallahu Aleyhi ve Sellem) için nöbet tutmaya gittim. Basktım ki bir adam yüksek sesle Kur'an okuyor. Biraz sonra Nebi (Sallallahu Aleyhi ve Sellem) dışarı çıktı. Ben: Ya Resulallah bu adam riyakardır. dedim. Edra (r.a.) demiştir ki: Sonra o adam Medine de vefat etti. Techiz işi bittikten sonra na'şını taşıyıp götürdüler. Nebi (Sallallahu Aleyhi ve Sellem) (oradakilere): «O'nu yavaş götürünüz. Allah onunla iyi mu'amele etti. Şüphesiz O Allah ve Resulünü seviyordu.» Edra (r.a.) demiştir ki: Efendimiz onun kabrini kazdırdı ve buyurdu ki: «Kabrini geniş tutun. Allah ona bolluk verdi.» Bunun üzerine Ashabından bazısı: Ya Resulallah, sen içinden ona üzüldün. dediler. Efendimiz (Sallallahu Aleyhi ve Sellem): «Evet çünkü o şüphesiz Allah'ı ve Resulünü seviyordu.» buyurdu. Not: Zevaid'de şöyle denilmiştir: Kütüb-i Sitte'de Edra' es•Sülemi (r.a.)'ın bundan başka hadisi yoktur. Bunun senedindeki ravi Musa bin Ubeyde hakkında: Hadisleri münker veya zayıftır, denilmiştir. Sika olduğunu söyliyenler de vardır. Hüccet değildir
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Daif</td><td>Shuaib Al Arnaut</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1559</td></tr><tr><td>Arabic No</td><td>1559</td></tr><tr><td>Reference</td><td>Book 6 Hadith 127</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ادرع سلمی رضی اللہ عنہ کہتے ہیں کہ میں ایک رات آیا، اور میں نبی اکرم صلی اللہ علیہ وسلم کی پہرہ داری کیا کرتا تھا، ایک شخص بلند آواز سے قرآن پڑھ رہا تھا، نبی اکرم صلی اللہ علیہ وسلم باہر نکلے، میں نے عرض کیا: اللہ کے رسول! یہ تو ریاکار معلوم ہوتا ہے، پھر اس کا مدینہ میں انتقال ہو گیا، جب لوگ اس کی تجہیز و تکفین سے فارغ ہوئے، تو لوگوں نے اس کی لاش اٹھائی تب نبی اکرم صلی اللہ علیہ وسلم نے فرمایا: اس کے ساتھ نرمی کرو ، اللہ تعالیٰ بھی اس کے ساتھ نرمی کرے، یہ اللہ اور اس کے رسول سے محبت رکھتا تھا، ادرع رضی اللہ عنہ کہتے ہیں کہ اس کی قبر کھودی گئی، تو رسول اللہ صلی اللہ علیہ وسلم نے فرمایا: اس کی قبر کشادہ کرو، اللہ اس پر کشادگی کرے ، یہ سن کر بعض صحابہ نے عرض کیا: اللہ کے رسول! کیا اس کی وفات پر آپ کو غم ہے؟ آپ صلی اللہ علیہ وسلم نے فرمایا: ہاں، یہ اللہ اور اس کے رسول سے محبت رکھتا تھا ۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Daif</td><td>Shuaib Al Arnaut</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1559</td></tr><tr><td>Arabic No</td><td>1559</td></tr><tr><td>Reference</td><td>Book 6 Hadith 127</td></tr></tbody></table></div>