## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا عَلِيُّ بْنُ مُحَمَّدٍ، حَدَّثَنَا وَكِيعٌ، حَدَّثَنَا سُفْيَانُ، وَأَبِي، وَإِسْرَائِيلُ، عَنْ أَبِي إِسْحَاقَ، عَنْ عَاصِمِ بْنِ ضَمْرَةَ السَّلُولِيِّ، قَالَ سَأَلْنَا عَلِيًّا عَنْ تَطَوُّعِ، رَسُولِ اللَّهِ ـ صلى الله عليه وسلم ـ بِالنَّهَارِ فَقَالَ إِنَّكُمْ لاَ تُطِيقُونَهُ فَقُلْنَا أَخْبِرْنَا بِهِ نَأْخُذْ مِنْهُ مَا اسْتَطَعْنَا ‏.‏ قَالَ كَانَ رَسُولُ اللَّهِ ـ صلى الله عليه وسلم ـ إِذَا صَلَّى الْفَجْرَ يُمْهِلُ حَتَّى إِذَا كَانَتِ الشَّمْسُ مِنْ هَاهُنَا - يَعْنِي مِنْ قِبَلِ الْمَشْرِقِ - بِمِقْدَارِهَا مِنْ صَلاَةِ الْعَصْرِ مِنْ هَا هُنَا - يَعْنِي مِنْ قِبَلِ الْمَغْرِبِ - قَامَ فَصَلَّى رَكْعَتَيْنِ. ثُمَّ يُمْهِلُ حَتَّى إِذَا كَانَتِ الشَّمْسُ مِنْ هَا هُنَا - يَعْنِي مِنْ قِبَلِ الْمَشْرِقِ - مِقْدَارَهَا مِنْ صَلاَةِ الظُّهْرِ مِنْ هَا هُنَا قَامَ فَصَلَّى أَرْبَعًا. وَأَرْبَعًا قَبْلَ الظُّهْرِ إِذَا زَالَتِ الشَّمْسُ. وَرَكْعَتَيْنِ بَعْدَهَا. وَأَرْبَعًا قَبْلَ الْعَصْرِ. يَفْصِلُ بَيْنَ كُلِّ رَكْعَتَيْنِ بِالتَّسْلِيمِ عَلَى الْمَلاَئِكَةِ الْمُقَرَّبِينَ وَالنَّبِيِّينَ. وَمَنْ تَبِعَهُمْ مِنَ الْمُسْلِمِينَ وَالْمُؤْمِنِينَ ‏.‏ قَالَ عَلِيٌّ: فَتِلْكَ سِتَّ عَشْرَةَ رَكْعَةً. تَطَوُّعُ رَسُولِ اللَّهِ ـ صلى الله عليه وسلم ـ بِالنَّهَارِ. وَقَلَّ مَنْ يُدَاوِمُ عَلَيْهَا ‏.‏ قَالَ وَكِيعٌ: زَادَ فِيهِ أَبِي: فَقَالَ حَبِيبُ بْنُ أَبِي ثَابِتٍ: يَا أَبَا إِسْحَاقَ مَا أُحِبُّ أَنَّ لِي بِحَدِيثِكَ هَذَا مِلْءَ مَسْجِدِكَ هَذَا ذَهَبًا ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Hasan</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1161</td></tr><tr><td>Arabic No</td><td>1161</td></tr><tr><td>Reference</td><td>Book 5 Hadith 359</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
১/১১৬১। আসেম ইবনু দমরা আস-সালূলী থেকে বর্ণিত। তিনি বলেন, আমরা আলী (রাঃ) কে রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম -এর দিনের বেলার নফল সালাত (নামায/নামাজ) সম্পর্কে জিজ্ঞেস করলাম। তিনি বলেন, তোমরা তা করতে সমর্থ নও। আমরা বললাম, আপনি আমাদের সেই সম্পর্কে অবহিত করুন, আমরা তা থেকে আমাদের সাধ্যমত গ্রহণ করবো। তিনি বলেন, রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম ফজরের সালাত পড়ার পর কিছুক্ষণ অবসর থাকতেন। অবশেষে সূর্য আসরের সময় পশ্চিমাকাশে যত উপরে থাকে, পূর্বাকাশে ঠিক ততটা উপরে উঠলে তিনি দু রাকআত সালাত আদায় করতো, অতঃপর অবসর থাকতেন। অবশেষে পশ্চিম আকাশে সূর্য যতটা উপরে থাকলে যোহরের সালাতের ওয়াক্ত থাকে, পূর্বাকাশে সূর্য ঠিক ততখানি উপরে উঠলে তিনি চার রাকআত সালাত আদায় করতো। সূর্য পশ্চিমাকাশে ঢলে পড়ার পর তিনি যোহরের (ফরয) সালাতের পূর্বে চার রাকআত এবং পরে দু রাকআত পড়তেন। তিনি আসরের পূর্বেও দু সালাম চার রাকআত সালাত আদায় করতো এবং তার মাঝখানে নৈকট্যপ্রাপ্ত ফেরেশতাগণ, আম্বিয়া (আলাইহিস সালাম) এবং তাদের অনুগত মুমিন মুসলিমদের জন্য শান্তি ও স্বস্তি কামনা করতেন (তাশাহ্হুদ পড়তেন)। আলী বলেন, এই হলো রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর দিনের বেলার ষোল রাকআত নফল সালাত। খুব কম লোকই তার উপর স্থায়ীভাবে আমল করতে পারে। ওয়াকী (রহঃ) বলেন, আমার পিতা এতে আরো বলেছেন, হাবীব ইবনু আবূ সাবিত (রহ) বলেছেন, হে আবূ ইসহাক! আপনার এই হাদীসের পরিবর্তে এই মসজিদে ভর্তি সোনা আমার মালিকানাভুক্ত হলে তাও আমার প্রিয় হতো না।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Hasan</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1161</td></tr><tr><td>Arabic No</td><td>1161</td></tr><tr><td>Reference</td><td>Book 5 Hadith 359</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
It was narrated that ‘Asim bin Damrah As-Saluli said:“We asked ‘Ali about the voluntary (prayer) of Allah’s Messenger (ﷺ) during the day. He said: ‘You will not be able.’ We said: ‘Inform us of it, we will do what we can of it?’ So he said: ‘When he prayed the Fajr he would delay praying any more. When the sun appeared over there (west) – like it appears here, meaning in the direction of the east, about the amount for the ‘Asr prayer from there, meaning in the direction of the west, meaning before the Maghrib – he would stand and perform two Rak’ah* then he would delay praying until the sun appeared over there (west), meaning in the direction of the east, about the amount of the Zuhr prayer from there, then he would stand and perform four. And, four before the Zuhr when the sun passed the zenith, and two Rak’ah after it, and, four before the ‘Asr, separating between every two Rak’ah with Taslim** upon the angels that are close (to Allah), the Prophets, and those who follow them among the Muslims and the believers.’” 'Ali said: "That is sixteen Rak'ah of voluntary prayer which Allah's Messenger (ﷺ) performed during the day. And there are very few who offer them regularly." Waki' said: “My father added: Habib bin Abu Thabit said: ‘O Abu Ishaq, this mosque filled with gold would not be dearer to me than this Hadith of yours.’” * Meaning, when the sun was low above the eastern horizon. That is the time of the Duha. ** Meaning the Tashah-hud
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Hasan</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1161</td></tr><tr><td>Arabic No</td><td>1161</td></tr><tr><td>Reference</td><td>Book 5 Hadith 359</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Ali bin Muhammad] berkata, telah menceritakan kepada kami [Waki'] berkata, telah menceritakan kepada kami [Sufyan] dan [Bapakku] dan [Isra'il] dari [Abu Ishaq] dari [Ashim bin Dlamrah As Saluli] ia berkata, "Kami bertanya kepada [Ali] tentang shalat sunnah Rasulullah shallallahu 'alaihi wasallam di waktu siang hari, " Ali pun menjawab, "Kalian tidak akan sanggup, " kami berkata, "Kabarkanlah, kami akan melakukan semampunya, " Ali berkata, "Kebiasaan Nabi shallallahu 'alaihi wasallam apabila hendak melaksanakan Shalat fajar (shubuh), beliau menundanya sehingga apabila matahari terbit dari arah sini yaitu dari arah timur, ukurannya seperti Shalat Ashar ketika matahari dari arah sini yaitu dari arah barat, maka beliau melaksanakan Shalat dua rakaat. Kemudian beliau menunda sehingga apabila matahari terbit dari arah sini yaitu dari arah timur, ukurannya jika dari Shalat Dzuhur dari arah sini yaitu dari arah barat, kemudian beliau melaksanakan Shalat sunnah empat rakaat, dan empat rakaat sebelum dzuhur apabila matahari telah tergelincir, dan shalat dua rakaat setelah Shalat dzuhur, kemudian beliau melaksanakan Shalat sunnah sebelum Shalat Ashar empat rakaat pada setiap dua rakaat dipisah dengan salam kepada para Malaikat, para Nabi serta orang-orang yang mengikuti mereka dari kaum muslimin dan mukminin." Ashim berkata; Ali berkata; "Itulah enam belas raka'at Shalat sunnahnya Nabi shallallahu 'alaihi wasallam di siang hari dan sangat sedikit orang mampu menekuninya." Waki' berkata; dalam hadits ini bapakku menambahkan; Habib Bin Abu Tsabit berkata; wahai Abu Ishaq "Wahai Abu Ishaq aku tidak menyukai kalau saja masjidmu di penuhi dengan emas kalau dibandingkan dengan haditsmu ini
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Hasan</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1161</td></tr><tr><td>Arabic No</td><td>1161</td></tr><tr><td>Reference</td><td>Book 5 Hadith 359</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>

</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Hasan</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1161</td></tr><tr><td>Arabic No</td><td>1161</td></tr><tr><td>Reference</td><td>Book 5 Hadith 359</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
عاصم بن ضمرہ سلولی کہتے ہیں کہ ہم نے علی رضی اللہ عنہ سے رسول اللہ صلی اللہ علیہوسلم کے دن کی نفل نماز کے متعلق پوچھا تو انہوں نے کہا: تم ان کو ادا نہ کر سکو گے، ہم نے کہا کہ آپ ہمیں بتائیے، ہم ان میں سے جتنی ادا کر سکیں گے اتنی لے لیں گے، انہوں نے کہا: رسول اللہ صلی اللہ علیہ وسلم فجر پڑھنے کے بعد رکے رہتے یہاں تک کہ جب سورج مشرق ( پورب ) کی جانب سے اتنا بلند ہو جاتا جتنا کہ عصر کے وقت مغرب ( پچھم ) کی جانب سے ہوتا ہے تو کھڑے ہوتے اور دو رکعت پڑھتے، ۱؎ پھر ٹھہر جاتے یہاں تک کہ جب سورج ( پورب ) کی جانب سے اتنا بلند ہو جاتا جتنا ظہر کے وقت مغرب ( پچھم ) کی طرف سے بلند ہوتا ہے، تو آپ کھڑے ہوتے اور چار رکعت پڑھتے، ۲؎ اور جب سورج ڈھل جاتا تو نماز ظہر سے پہلے چار رکعت اور اس کے بعد دو رکعت پڑھتے، اور چار رکعت عصر سے پہلے جن میں ہر دو رکعت کے درمیان مقرب فرشتوں، انبیاء کرام اور ان کے پیروکار مسلمانوں اور مومنوں پر سلام بھیج کر فصل کرتے۔ علی رضی اللہ عنہ نے کہا: یہ سب سولہ رکعتیں ہوئیں جو نبی اکرم صلی اللہ علیہ وسلم دن میں بطور نفل پڑھتے، اور ایسے لوگ بہت کم ہیں جو پابندی کے ساتھ انہیں پڑھتے رہیں۔ راوی حدیث وکیع کہتے ہیں کہ میرے والد نے اس حدیث میں اتنا اضافہ کیا کہ حبیب بن ابی ثابت نے ابواسحاق سے کہا کہ اے ابواسحاق! اگر اس حدیث کے بدلے مجھے تمہاری اس مسجد بھر سونا ملتا تو میں پسند نہیں کرتا۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Hasan</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1161</td></tr><tr><td>Arabic No</td><td>1161</td></tr><tr><td>Reference</td><td>Book 5 Hadith 359</td></tr></tbody></table></div>