## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا مُحَمَّدُ بْنُ عَبْدِ الْمَلِكِ بْنِ أَبِي الشَّوَارِبِ، حَدَّثَنَا مَسْلَمَةُ بْنُ عَلْقَمَةَ، عَنْ دَاوُدَ بْنِ أَبِي هِنْدٍ، عَنِ الْوَلِيدِ بْنِ عَبْدِ الرَّحْمَنِ الْجُرَشِيِّ، عَنْ جُبَيْرِ بْنِ نُفَيْرٍ الْحَضْرَمِيِّ، عَنْ أَبِي ذَرٍّ، قَالَ صُمْنَا مَعَ رَسُولِ اللَّهِ ـ صلى الله عليه وسلم ـ رَمَضَانَ فَلَمْ يَقُمْ بِنَا شَيْئًا مِنْهُ حَتَّى بَقِيَ سَبْعُ لَيَالٍ فَقَامَ بِنَا لَيْلَةَ السَّابِعَةِ حَتَّى مَضَى نَحْوٌ مِنْ ثُلُثِ اللَّيْلِ ثُمَّ كَانَتِ اللَّيْلَةُ السَّادِسَةُ الَّتِي تَلِيهَا فَلَمْ يَقُمْهَا حَتَّى كَانَتِ الْخَامِسَةُ الَّتِي تَلِيهَا ثُمَّ قَامَ بِنَا حَتَّى مَضَى نَحْوٌ مِنْ شَطْرِ اللَّيْلِ فَقُلْتُ يَا رَسُولَ اللَّهِ لَوْ نَفَّلْتَنَا بَقِيَّةَ لَيْلَتِنَا هَذِهِ ‏.‏ فَقَالَ ‏ "‏ إِنَّهُ مَنْ قَامَ مَعَ الإِمَامِ حَتَّى يَنْصَرِفَ فَإِنَّهُ يَعْدِلُ قِيَامَ لَيْلَةٍ ‏"‏ ‏.‏ ثُمَّ كَانَتِ الرَّابِعَةُ الَّتِي تَلِيهَا فَلَمْ يَقُمْهَا حَتَّى كَانَتِ الثَّالِثَةُ الَّتِي تَلِيهَا ‏.‏ قَالَ فَجَمَعَ نِسَاءَهُ وَأَهْلَهُ وَاجْتَمَعَ النَّاسُ ‏.‏ قَالَ فَقَامَ بِنَا حَتَّى خَشِينَا أَنْ يَفُوتَنَا الْفَلاَحُ ‏.‏ قِيلَ وَمَا الْفَلاَحُ قَالَ السُّحُورُ ‏.‏ قَالَ ثُمَّ لَمْ يَقُمْ بِنَا شَيْئًا مِنْ بَقِيَّةِ الشَّهْرِ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Hasan Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1327</td></tr><tr><td>Arabic No</td><td>1327</td></tr><tr><td>Reference</td><td>Book 5 Hadith 525</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
২/১৩২৭। আবূ যার (রাঃ) থেকে বর্ণিত। তিনি বলেন, আমরা রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর সাথে রমযানে সওম রাখলাম। তিনি আমাদের নিয়ে এ মাসে (নফল সালাতে) দাঁড়াননি, এমনকি রমযানের মাত্র সাতটি রাত বাকি রইল। সপ্তম রাতে তিনি আমাদের নিয়ে প্রায় এক-তৃতীয়াংশ রাত সালাত (নামায/নামাজ) পড়লেন। এরপর ষষ্ঠ রাতে তিনি (নফল) সালাত ড়েননি। অতঃপর পঞ্চম রাতে তিনি আমাদের নিয়ে প্রায় অর্ধরাত পর্যন্ত সালাত পড়েন। আমি বললাম, হে আল্লাহ্‌র রাসূল! এর রাতের অবশিষ্ট অংশও যদি আপনি আমাদের নিয়ে সালাত আদায় করতেন। তিনি বলেনঃ যে ব্যক্তি ইমামের সাথে সালাত পড়ে ফিরে আসে, সে সারা রাত সালাত পড়ার সমান সওয়াব পায়। অতঃপর তিনি চতুর্থ রাতে সালাত পড়েননি। তৃতীয় রাত এলে তিনি তাঁর স্ত্রীদের, পরিজনদের একত্র করেন এবং লোকেরাও একত্র হয়। রাবী বলেন, তিনি আমাদের নিয়ে এত দীর্ঘক্ষণ সালাত পড়লেন যে, আমরা কল্যাণ থেকে বঞ্চিত হওয়ার আশঙ্কা করলাম। আবূ যার (রাঃ) কে জিজ্ঞেস করা হলো, কল্যাণ কী? তিনি বলেন, সাহরী। অতঃপর তিনি আমাদের নিয়ে মাসের অবশিষ্ট রাতগুলোতে আর কোন নফল সালাত পড়েননি।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Hasan Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1327</td></tr><tr><td>Arabic No</td><td>1327</td></tr><tr><td>Reference</td><td>Book 5 Hadith 525</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
It was narrated that Abu Dharr said:“We fasted Ramadan with the Messenger of Allah (ﷺ) and he did not lead us in praying Qiyam (prayers at night) during any part of it, until there were seven nights left. He led us in praying Qiyam on the seventh night until approximately one third of the night had passed. Then on the sixth night which followed it he did not lead us in prayer. Then he led us in praying Qiyam on the fifth night which followed it until almost half the night had passed. I said: ‘O Messenger of Allah, would that we had offered voluntary prayers throughout the whole night.’ He said: ‘Whoever stands with the Imam until he finishes, it is equivalent to spending the whole night in prayer.’ Then on the fourth night which followed it, he did not lead us in prayer, until the third night that followed it, when he gathered his wives and family, and the people gathered, and he led us in prayer until we feared that we would miss the Falah.” It was asked: “What is the Falah?” He said: “Suhur.” He said: “Then he did not lead us in prayer at night for the rest of the month.”
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Hasan Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1327</td></tr><tr><td>Arabic No</td><td>1327</td></tr><tr><td>Reference</td><td>Book 5 Hadith 525</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Muhammad bin Abdul Malik bin Abu Asy Syawarib] berkata, telah menceritakan kepada kami [Maslamah bin Alqamah] dari [Dawud bin Abu Hind] dari [Al Walid bin 'Abdurrahman Al Jurasyi] dari [Jubair bin Nufair Al Hadlrami] dari [Abu Dzar] ia berkata, "Kami puasa ramadlan bersama Rasulullah shallallahu 'alaihi wasallam, namun beliau tidak shalat malam sekalipun, hingga tersisa tujuh hari dari bulan tersebut. Beliau shalat malam bersama kami pada malam ke tujuh hingga lewat dari seperti malam. Pada malam ke enam beliau tidak shalat hingga masuk malam ke lima di hari berikutnya. Beliau lalu shalat malam bersama kami hingga lewat pertengahan malam. Aku berkata, "Wahai Rasulullah, bagaimana jika sisa malam ini kita manfaatkan untuk shalat nafilah?" beliau bersabda: "Barangsiapa shalat bersama imam hingga selesai, sesungguhnya hal itu telah menyamai shalat satu malam penuh. " Kemudian pada malam ke empat hari berikutnya beliau tidak shalat hingga masuk malam ke tiga di hari berikutnya. " Abu Dzar berkata, "Beliau mengumpulkan semua isteri dan keluarganya, dan orang-orang pun ikut berkumpul. " Abu Dzar berkata, "Beliau shalat bersama kami hingga kami khawatir kehilangan Al Falah, " dikatakan kepadanya, "Al Falah itu apa?" ia menjawab, "Sahur. " Abu Dzar berkata, "Setelah itu beliau tidak lagi shalat bersama kami hingga akhir bulan
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Hasan Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1327</td></tr><tr><td>Arabic No</td><td>1327</td></tr><tr><td>Reference</td><td>Book 5 Hadith 525</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ebu Zer'(-i Ğıfari) (r.a.)'den: şöyle demiştir: Biz Resulullah (Sallallahu Aleyhi ve Sellem) ile beraber bir Ramazan (ayı boyunca) oruç tuttuk. (Ramazan ayından) yedi gece kalıncaya kadar hiç bir gecesinde bize kıyam ettirmedi (teravih kıldırmadı veya geceyi ihya ettirmedi.) (Ay sonundan başına doğru) yedinci gece olunca yaklaşık olarak gecenin üçte birisi geçinceye kadar bize teravih kıldırdı. (Veya gecenin o kısmını ihya ettirdi.) Sonra o geceyi takip eden (sondan) altıncı gece oldu. (Ama) onda teravih kıldırmadı. Nihayet (sondan) beşinci gece oldu. (Ondan) yaklaşık gecenin yarısı geçinceye kadar bize teravih kıldırdı. Ben: Ya Resulallah! Bu gecemizin kalan yarısını da ihya etmemizi buyurmanızı temenni ediyoruz, dedim. Buyurdular ki: «Şüphesiz, imam namazdan dönünceye kadar onunla beraber (yatsı farzını ve) teravihi kılan kimsenin bu ibadeti bir geceyi (tamamen) ihya etmeye denk olur.» Sonra o geceyi izleyen (sondan) dördüncü gece oldu da teravih kıldırmadı. Nihayet, onu takip eden (sondan) üçüncü gece oldu. O, (muhterem) eşlerini ve yakınlarını topladı. Cemaat da toplandı. Ebu Zer' (r.a.) demiştir ki: Efendimiz o gece, bize kıldırdığı teravihi o kadar uzattı ki biz felah'ı kaçıracağımızdan korktuk. Denilmiş ki: Felah nedir? Ebu Zer' (r.a.): Felah, sahur yemeğini yemektir, diye cevap vermiştir. Ebu Zer' (r.a.) demiştir ki; O geceden sonra efendimiz Ramazan ayının kalan iki gecesinde bize teravih namazından hiç bir şey kıldırmadı. Diğer tahric: Tirmizi, Ebu Davud, Nesai, Tahavi, Hakim ve Beyhaki de bunu rivayet etmişlerdir. Tirmizi ve Hakim bunun sahih olduğunu da belirtmişlerdir
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Hasan Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1327</td></tr><tr><td>Arabic No</td><td>1327</td></tr><tr><td>Reference</td><td>Book 5 Hadith 525</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ابوذر رضی اللہ عنہ کہتے ہیں کہ ہم نے رسول اللہ صلی اللہ علیہ وسلم کے ساتھ رمضان کے روزے رکھے، آپ نے کسی بھی رات ہمارے ساتھ نماز تراویح نہ ادا فرمائی، یہاں تک کہ جب سات راتیں باقی رہ گئیں، تو ساتویں ( یعنی تیئیسویں ) رات کو آپ نے ہمارے ساتھ قیام کیا، یہاں تک کہ رات تہائی کے قریب گزر گئی، پھر اس کے بعد چھٹی ( یعنی چوبیسویں ) رات کو جو اس کے بعد آتی ہے، آپ نے قیام نہیں کیا یہاں تک کہ اس کے بعد والی پانچویں یعنی ( پچیسویں ) رات کو آپ نے ہمارے ساتھ قیام کیا یہاں تک کہ رات آدھی کے قریب گزر گئی، میں نے عرض کیا: اللہ کے رسول! کاش آپ باقی رات بھی ہمیں نفل پڑھاتے رہتے، آپ صلی اللہ علیہ وسلم نے فرمایا: جو کوئی امام کے ساتھ قیام کرے یہاں تک کہ وہ فارغ ہو جائے، تو وہ ساری رات کے قیام کے برابر ہے، پھر جب اس کے بعد والی چوتھی ( یعنی چھبیسویں ) رات آئی تو آپ نے اس میں قیام نہیں کیا، جب اس کے بعد والی تیسری ( یعنی ستائیسویں ) رات آئی تو آپ صلی اللہ علیہ وسلم نے اپنی بیویوں اور گھر والوں کو جمع کیا، اور لوگ بھی جمع ہوئے، ابوذر رضی اللہ عنہ نے کہا: تو آپ نے ہمارے ساتھ قیام کیا یہاں تک کہ ہمیں خدشہ ہوا کہ ہم سے «فلاح» فوت نہ ہو جائے، ان سے پوچھا گیا: «فلاح» کیا ہے؟ کہا: سحری: پھر آپ صلی اللہ علیہ وسلم نے ماہ رمضان کے باقی دنوں میں تراویح باجماعت نہیں پڑھی ۱؎۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Hasan Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1327</td></tr><tr><td>Arabic No</td><td>1327</td></tr><tr><td>Reference</td><td>Book 5 Hadith 525</td></tr></tbody></table></div>