## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا مُحَمَّدُ بْنُ بَشَّارٍ: حَدَّثَنَا يَحْيَى بْنُ سَعِيدٍ: حَدَّثَنَا عَبْدُ الْحَمِيدِ بْنُ جَعْفَرٍ: حَدَّثَنَا مُحَمَّدُ بْنُ عَمْرِو بْنِ عَطَاءٍ، عَنْ أَبِي حُمَيْدٍ السَّاعِدِيِّ، قَالَ سَمِعْتُهُ، وَهُوَ فِي عَشَرَةٍ مِنْ أَصْحَابِ رَسُولِ اللَّهِ ـ صلى الله عليه وسلم ـ، أَحَدُهُمْ أَبُو قَتَادَةَ بْنُ رِبْعِيٍّ قَالَ أَنَا أَعْلَمُكُمْ بِصَلاَةِ رَسُولِ اللَّهِ ـ صلى الله عليه وسلم ـ كَانَ إِذَا قَامَ فِي الصَّلاَةِ اعْتَدَلَ قَائِمًا، وَرَفَعَ يَدَيْهِ حَتَّى يُحَاذِيَ بِهِمَا مَنْكِبَيْهِ، ثُمَّ قَالَ ‏"‏ اللَّهُ أَكْبَرُ ‏"‏ ‏.‏ وَإِذَا أَرَادَ أَنْ يَرْكَعَ، رَفَعَ يَدَيْهِ حَتَّى يُحَاذِيَ بِهِمَا مَنْكِبَيْهِ، فَإِذَا قَالَ ‏"‏ سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ ‏"‏ ‏.‏ رَفَعَ يَدَيْهِ فَاعْتَدَلَ، فَإِذَا قَامَ مِنَ الثِّنْتَيْنِ، كَبَّرَ وَرَفَعَ يَدَيْهِ حَتَّى يُحَاذِيَ بِهِمَا مَنْكِبَيْهِ، كَمَا صَنَعَ حِينَ افْتَتَحَ الصَّلاَةَ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>862</td></tr><tr><td>Arabic No</td><td>862</td></tr><tr><td>Reference</td><td>Book 5 Hadith 60</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
৫/৮৬২। আবূ হুমাইদ আস-সাইদী (রাঃ) থেকে বর্ণিত। তিনি আবূ ক্বাতাদাহ (রাঃ) সহ রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম -এর দশজন সাহাবীর উপস্থিতিতে বলেন, আমি রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম -এর সালাত সম্পর্কে তোমাদের চেয়ে অধিক অবগত। তিনি যখন সালাতে দাঁড়াতেন সোজা হয়ে দাঁড়াতেন এবং তাঁর দু হাত তাঁর কাঁধ বরাবর উঠাতেন, অতঃপর আল্লাহু আকবার বলতেন। তিনি যখন রুকূতে যাওয়ার ইচ্ছা করতেন তখনও তাঁর দু হাত তাঁর দু কাঁধ বরাবর উঠাতেন। অতঃপর তিনি যখন সামিআল্লাহু লিমান হামিদাহ বলতেন, তাঁর দু হাত উত্তোলন করতেন এবং সোজা হয়ে দাঁড়াতেন। তিনি দ্বিতীয় রাক্আতে দু সাজাদাহ থেকে যখন দাঁড়াতেন তখন তাকবীর বলতেন এবং তাঁর দু হাত তার কাঁধ বরাবর উঠাতেন, যেমনটি তিনি সালাত শুরু করার সময় করতেন।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>862</td></tr><tr><td>Arabic No</td><td>862</td></tr><tr><td>Reference</td><td>Book 5 Hadith 60</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
It was narrated that Muhammad bin 'Amr bin 'Ata’ said, concerning Abu Humaid As-Sa'di:“I heard him when he was among ten of the Companions of the Messenger of Allah (ﷺ), one of whom was Abu Qatadah bin Rib'i, saying: ‘I am the most knowledgeable of you about the prayer of the Messenger of Allah (ﷺ). When he stood up for prayer, he stood up straight and raised his hands until they were parallel to his shoulders, then he said: Allahu Akbar. When he wanted to bow in Ruku', he raised his hands until they were parallel to his shoulders. When he said Sami' Allahu liman hamidah (Allah hears those who praise Him), he raised his hands and stood up straight. When he stood up after two Rak'ah, he said Allahu Akbar and raised his hands until they were parallel to his shoulders, as he did when he started the prayer.’”
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>862</td></tr><tr><td>Arabic No</td><td>862</td></tr><tr><td>Reference</td><td>Book 5 Hadith 60</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Muhammad bin Basysyar] berkata, telah menceritakan kepada kami [Yahya bin Sa'id] berkata, telah menceritakan kepada kami [Abdul Hamid bin Ja'far] berkata, telah menceritakan kepada kami [Muhammad bin Amru bin 'Atho'] dari [Abu Humaid As Sa'idi] -ia berkata; "Aku mendengarnya berkata, ketika itu ia termasuk salah seorang dari sepuluh sahabat Rasulullah shallallahu 'alaihi wasallam (yang berkumpul), di antara mereka juga ada- [Abu Qatadah bin Rib'i], ia berkata; "Aku adalah orang yang paling tahu dengan shalat Rasulullah shallallahu 'alaihi wasallam di antara kalian. Jika shalat beliau berdiri tegak dan mengangkat kedua tangannya hingga sejajar dengan kedua pundak seraya mengucapkan ALLAHU AKBAR. Ketika rukuk beliau juga mengangkat kedua tangannya sejajar dengan kedua pundaknya. Apabila mengucapkan SAMI'A ALLAHU LIMAN HAMIDAHU beliau mengangkat kedua tangannya tegak berimbang. Dan ketika bangun pada raka'at kedua beliau takbir dan mengangkat kedua tangannya sejajar dengan kedua pundak sebagaimana ketika beliau membuka shalat
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>862</td></tr><tr><td>Arabic No</td><td>862</td></tr><tr><td>Reference</td><td>Book 5 Hadith 60</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Muhammet! bin Anır bin Ala (r.a.)'dan şöyle demiştir: Ben, Ebu Hümeyd es-Saidi (r.a.)'den işittim. Kendisi Resulullah (Sallallahu Aleyhi ve Sellem)'in ashabından on zatın arasındaydı. On sahabiden birisi Ebu Katade bin Rib'i idi. Ebu Humeyd, orada bulunan on sahabi'ye : Ben, Resulullah (Sallallahu Aleyhi ve Sellem)'in namaz kılışını hepinizden daha iyi bilirim Resulullah (Sallallahu Aleyhi ve Sellem) namaza durmak istediği zaman dimdik doğrulurdu ve ellerini omuzları hizasına kadar kaldırdıktan sonra: «Allahü ekber» derdi, rüku'a varmak istediği zaman da ellerini omuzları hizasına kadar kaldırırdı. semi'allahu limen hamideh dediği zaman da ellerini kaldırırdı, sonra tam doğrulurdu. İki rek'atten (üçüncü rek'ate) kalktığı zaman tekbir alırdı ve iftitah tekbirini aldığı zaman yaptığı gibi ellerini omuzlarının hizasına kadar kaldırırdı. Diğer tahric: Buhari, Ahmed, Ebu Davud, Tirmizi, Beyhaki, İbn-i Hibban ve Tahavi, bu hadisi uzun ve kısa metinler halinde rivayet etmişlerdir
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>862</td></tr><tr><td>Arabic No</td><td>862</td></tr><tr><td>Reference</td><td>Book 5 Hadith 60</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
محمد بن عمرو بن عطاء کہتے ہیں کہ میں نے ابو حمید ساعدی کو کہتے سنا اور وہ رسول اللہ صلی اللہ علیہ وسلم کے دس اصحاب کے بیچ میں تھے جن میں سے ایک ابوقتادہ بن ربعی تھے، ابو حمید ساعدی رضی اللہ عنہ نے کہا: میں تم میں رسول اللہ صلی اللہ علیہ وسلم کی نماز کو سب سے زیادہ جانتا ہوں، آپ صلی اللہ علیہ وسلم جب نماز کے لیے کھڑے ہوتے تو سیدھے کھڑے ہو جاتے، اور اپنے دونوں ہاتھ مونڈھوں کے بالمقابل اٹھاتے، پھر «ألله أكبر» کہتے، اور جب رکوع میں جانے کا ارادہ کرتے تو اپنے دونوں ہاتھ مونڈھوں کے بالمقابل اٹھاتے، اور جب «سمع الله لمن حمده» کہتے تو اپنے دونوں ہاتھ اٹھاتے اور سیدھے کھڑے ہو جاتے، اور جب دو رکعت کے بعد ( تیسری رکعت کے لیے ) کھڑے ہوتے تو «ألله أكبر» کہتے اور اپنے دونوں ہاتھ مونڈھوں کے بالمقابل اٹھاتے ( یعنی رفع یدین کرتے ) ، جیسا کہ نماز شروع کرتے وقت کیا تھا ۱؎۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>862</td></tr><tr><td>Arabic No</td><td>862</td></tr><tr><td>Reference</td><td>Book 5 Hadith 60</td></tr></tbody></table></div>