## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنِي مُحَمَّدُ بْنُ سَهْلٍ التَّمِيمِيُّ، وَأَبُو بَكْرِ بْنُ إِسْحَاقَ - قَالَ أَبُو بَكْرٍ أَخْبَرَنَا وَقَالَ ابْنُ سَهْلٍ، حَدَّثَنَا - ابْنُ أَبِي مَرْيَمَ، أَخْبَرَنَا مُحَمَّدٌ، - وَهُوَ ابْنُ مُطَرِّفٍ أَبُو غَسَّانَ - أَخْبَرَنِي أَبُو حَازِمٍ، عَنْ سَهْلِ بْنِ سَعْدٍ، قَالَ ذُكِرَ لِرَسُولِ اللَّهِ صلى الله عليه وسلم امْرَأَةٌ مِنَ الْعَرَبِ فَأَمَرَ أَبَا أُسَيْدٍ أَنْ يُرْسِلَ إِلَيْهَا فَأَرْسَلَ إِلَيْهَا فَقَدِمَتْ فَنَزَلَتْ فِي أُجُمِ بَنِي سَاعِدَةَ فَخَرَجَ رَسُولُ اللَّهِ صلى الله عليه وسلم حَتَّى جَاءَهَا فَدَخَلَ عَلَيْهَا فَإِذَا امْرَأَةٌ مُنَكِّسَةٌ رَأْسَهَا فَلَمَّا كَلَّمَهَا رَسُولُ اللَّهِ صلى الله عليه وسلم قَالَتْ أَعُوذُ بِاللَّهِ مِنْكَ قَالَ ‏"‏ قَدْ أَعَذْتُكِ مِنِّي ‏"‏ ‏.‏ فَقَالُوا لَهَا أَتَدْرِينَ مَنْ هَذَا فَقَالَتْ لاَ ‏.‏ فَقَالُوا هَذَا رَسُولُ اللَّهِ صلى الله عليه وسلم جَاءَكِ لِيَخْطُبَكِ قَالَتْ أَنَا كُنْتُ أَشْقَى مِنْ ذَلِكَ ‏.‏ قَالَ سَهْلٌ فَأَقْبَلَ رَسُولُ اللَّهِ صلى الله عليه وسلم يَوْمَئِذٍ حَتَّى جَلَسَ فِي سَقِيفَةِ بَنِي سَاعِدَةَ هُوَ وَأَصْحَابُهُ ثُمَّ قَالَ ‏"‏ اسْقِنَا ‏"‏ ‏.‏ لِسَهْلٍ قَالَ فَأَخْرَجْتُ لَهُمْ هَذَا الْقَدَحَ فَأَسْقَيْتُهُمْ فِيهِ ‏.‏ قَالَ أَبُو حَازِمٍ فَأَخْرَجَ لَنَا سَهْلٌ ذَلِكَ الْقَدَحَ فَشَرِبْنَا فِيهِ قَالَ ثُمَّ اسْتَوْهَبَهُ بَعْدَ ذَلِكَ عُمَرُ بْنُ عَبْدِ الْعَزِيزِ فَوَهَبَهُ لَهُ ‏.‏ وَفِي رِوَايَةِ أَبِي بَكْرِ بْنِ إِسْحَاقَ قَالَ ‏"‏ اسْقِنَا يَا سَهْلُ ‏"‏ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5236</td></tr><tr><td>Arabic No</td><td>2007</td></tr><tr><td>Reference</td><td>Book 36 Hadith 110</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
হাদিস একাডেমি নাম্বারঃ ৫১৩১, আন্তর্জাতিক নাম্বারঃ ২০০৭ ৫১৩১-(৮৮/২০০৭) মুহাম্মাদ ইবনু সাহল আত তামীমী ও আবূ বকর ইবনু ইসহাক (রহঃ) .... সাহল ইবনু সা'দ (রাযিঃ) হতে বর্ণিত। তিনি বলেন, রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর কাছে আরবের জনৈকা মহিলার ব্যাপারে আলোচনা করা হলে, তিনি আবূ উসায়দ (রাযিঃ) কে তার কাছে লোক প্রেরণের জন্য নির্দেশ দিলেন। তিনি লোক (দূত) পাঠালে উক্ত মহিলা আসলো এবং বানু সাইদাহ্ সম্প্রদায়ের দূর্গে অবস্থান গ্রহণ করলো। রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বের হয়ে তার কাছে আসলেন। তিনি যখন তার কাছে পৌছলেন, তখন মহিলা মাথা নীচু করে বসেছিল। তিনি তার সঙ্গে আলাপ করলে সে বলল, আমি আপনার থেকে আল্লাহর কাছে আশ্রয় চাই। তিনি বললেন, আমিও তোমাকে পরিত্রাণ দিলাম। লোকেরা মহিলাকে বলল, তুমি জান ইনি কে? সে বলল, না। তারা বলল, ইনি তো আল্লাহর রসূল। তিনি তোমাকে বিবাহের প্রস্তাব দিতে এসেছিলেন। তখন সে বলল, আমি তো এর অযোগ্য! সাহল (রাযিঃ) বলেন, অতঃপর রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম সেদিন প্রত্যাবর্তন করে তিনি ও তার সাহাবীগণ বানু সাইদার সাকীফায় (বাগানে) নিজেকে উপবেশন করেন। অতঃপর তিনি সাহলকে বললেন, আমাদেরকে কিছু পান করাও। সাহল বলেন, পরে আমি এ পেয়ালাটি বের করে তাদের সকলকেই তা হতে পান করিয়েছিলাম। আবূ হাযিম (রহঃ) বলেন, সাহল (রাযি) আমাদের সম্মুখে বাটিটি বের করলে আমরা তা হতে পান করলাম। অতঃপর উমার ইবনু আবদুল আযীয (রহঃ) তা চাইলে, তিনি তাকে সেটি দান করেন। আবূ বাকর ইবনু ইসহাক (রহঃ) এর রিওয়ায়াতে আছে, তিনি বললেন, হে সাহল! তুমি আমাদেরকে পান করাও। (ইসলামিক ফাউন্ডেশন ৫০৬৬, ইসলামিক সেন্টার ৫০৭৬)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5236</td></tr><tr><td>Arabic No</td><td>2007</td></tr><tr><td>Reference</td><td>Book 36 Hadith 110</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Sahl b. Sa'd reported:An Arab woman was mentioned before Allah's Messenger (ﷺ). He commanded Abu Usaid to send a message to her and he (accordingly) sent a message to her. She came and stayed in the fortresses of Banu Sa'idah. Allah's Messenger (ﷺ) went out until he came to her while she was (at that time) sitting with her head downcast. When Allah's Messenger (ﷺ) talked to her, she said: I seek refuge with Allah from you. Thereupon he said: I (have decided to) keep you away from me. They (the people near her) said: Do you know who he is? She said: No. They said: He is the Messenger of Allah (ﷺ). He came to you in order to give you the proposal of marriage. She said: Then I am the most unfortunate woman because of this (i. e. my defiance). Sahl said: Allah's. Messenger (ﷺ) then set forth on that day until he sat in the Saqifa of Banu Sa'idah along with his Companions. He then said to Sahl: Serve us drink. He (Sahl) said: I brought out for them this bowl (containing drink) and served them this. Abu Hazim said: Sahl brought out this cup for us and we also drank from that. Then 'Umar b. 'Abd al-'Aziz asked him to give that (cup) as a gift to him and he gave (it to) him as a gift. In the narration of Abu Bakr b. Ishaq (the words) are:" Sahl, serve us drink
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5236</td></tr><tr><td>Arabic No</td><td>2007</td></tr><tr><td>Reference</td><td>Book 36 Hadith 110</td></tr></tbody></table></div>

## French


<div dir="ltr" lang="fr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Sahl Ibn Sa'd (que Dieu l'agrée) a dit : On avait parlé au Prophète (paix et bénédiction de Dieu sur lui) d'une femme des Arabes. Il donna ordre à Abou 'Usayd de la mander (le Prophète voulut l'épouser). Abou 'Usayd fit alors venir cette femme qui vint et séjourna à la forteresse des Banû Sâ'ida. Le Prophète (paix et bénédiction de Dieu sur lui) s'y rendit et lorsqu'il entra chez elle, il vit une femme qui baissait la tête. Comme le Prophète (paix et bénédiction de Dieu sur lui) lui adressa la parole, elle s'écria : "Je me réfugie auprès de Dieu contre toi". - "Eh bien, répondit-il, tu t'es assurée un refuge contre moi (je ne vais pas t'épouser)". - "Sais-tu, demanda-t-on à cette femme, qui était cette personne?". - "Non", répliqua-t-elle. - "C'était, lui dit-on, l'Envoyé de Dieu (paix et bénédiction de Dieu sur lui) qui venait demander ta main". - "J'étais trop indigne (pour l'avoir traiter ainsi)", s'écria-t-elle. Sahl dit : Le Prophète (paix et bénédiction de Dieu sur lui) se rendit ensuite à la Saqîfa des Banû Sâ'ida; s'assit, lui et ses compagnons, puis dit : "Ô Sahl, donne-nous à boire (du vin qui n'a pas été encore fermenté)". Je leur donnai à boire dans le bol que voici
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5236</td></tr><tr><td>Arabic No</td><td>2007</td></tr><tr><td>Reference</td><td>Book 36 Hadith 110</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepadaku [Muhammad bin Sahl At Tamimi] dan [Abu Bakar bin Ishaq], Abu Bakar berkata; telah mengabarkan kepada kami, sedangkan Ibnu Sahl berkata; telah menceritakan kepada kami [Ibnu Abu Maryam] telah mengabarkan kepada kami [Muhammad] -yaitu Ibnu Mutharif Abu Ghassan- telah mengabarkan kepadaku [Abu Hazim] dari [Sahl bin Sa'd] dia berkata, "Ketika dituturkan kepada Rasulullah shallallahu 'alaihi wasallam tentang cerita wanita Arab kampung, maka beliau pun memerintahkan Abu Usaid untuk memanggilnya. Tidak lama kemudian wanita itu datang dan tinggal di rumah Bani Sa'idah. Kemudian Rasulullah shallallahu 'alaihi wasallam keluar dan pergi menemui wanita tersebut, ternyata wanita itu selalu menundukkan kepalanya. Pada saat Rasulullah shallallahu 'alaihi wasallam mengajaknya bicara, wanita itu justru berkata, "Saya berlindung kepada Allah darimu." Beliau menjawab: "Baiklah, saya juga melindungimu dariku." Setelah itu para sahabat berkata kepadanya, "Tahukah kamu siapakah orang yang mengajakmu bicara tadi?" wanita itu menjawab, "Tidak." Para sahabat berkata, "Orang itu adalah Rasulullah shallallahu 'alaihi wasallam, beliau datang untuk melamarmu." Wanita itu berkata, "Kalau begitu, saya termasuk orang yang tidak beruntung." Sahl berkata, "Pada saat itu Rasulullah shallallahu 'alaihi wasallam datang dan duduk di bangsal Bani Sa'idah bersama dengan para sahabat. Kemudian beliau bersabda kepada Sahl: "Berilah kami minuman." Sahl berkata, "Lalu saya mengeluarkan mangkuk ini untuk mereka dan memberikan minuman kepada mereka dengan menggunakan mangkuk tersebut." Abu Hazim berkata, "Kemudian Sahl mengeluarkan mangkuk tersebut untuk kami dan kami langsung meminumnya." Abu Hazim berkata, "Selang beberapa tahun kemudian, Umar bin Abdul Aziz meminta mangkuk itu. Lalu mangkuk itu pun akhirnya diberikan kepadanya." Dan dalam riwayat Abu Bakar bin Ishaq disebutkan, "Beliau bersabda: "Hidangkanlah minuman buat kami wahai Sahl
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5236</td></tr><tr><td>Arabic No</td><td>2007</td></tr><tr><td>Reference</td><td>Book 36 Hadith 110</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
சஹ்ல் பின் சஅத் (ரலி) அவர்கள் கூறியதாவது: அல்லாஹ்வின் தூதர் (ஸல்) அவர்களிடம் ஓர் அரபுப் பெண்ணைப் பற்றி (அவளை மணந்து கொள்ளுமாறு) கூறப்பட்டது. அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் அப்பெண்ணை அழைத்து வருவதற்கு ஆளனுப்புமாறு அபூஉசைத் அஸ்ஸாஇதீ (ரலி) அவர்களுக்கு உத்தரவிட, அவ்வாறே அவர்கள் ஆளனுப்பினார்கள். அந்தப் பெண் வந்து, (மதீனாவிலுள்ள) பனூ சாஇதா குலத்தாரின் கோட்டை ஒன்றில் தங்கினார். அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் புறப்பட்டு அப்பெண்ணிடம் வந்து, அவள் இருந்த இடத்தில் நுழைய, அங்கே அப்பெண் தலையைக் கவிழ்த்தபடி இருந்தாள். அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் அப்பெண்ணிடம் (தம்மை மணந்துகொள்ள சம்மதம் கேட்டுப்) பேசியபோது அவள், "உங்களிடமிருந்து நான் அல்லாஹ்விடம் பாதுகாப்புக் கோருகிறேன்" என்று சொன்னாள். அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் "என்னிடமிருந்து உனக்குப் பாதுகாப்பு அளித்துவிட்டேன்" என்று கூறினார்கள். மக்கள் அந்தப் பெண்ணிடம், "இவர்கள் யார் என்று உனக்குத் தெரியுமா?" என்று கேட்க, அவள் "தெரியாது” என்று பதிலளித்தாள். மக்கள் "இவர்கள்தாம் அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள். உன்னைப் பெண் பேசுவதற்காக வந்தார்கள்" என்று கூறினர். அந்தப் பெண், "அவர்களை மணந்துகொள்ளும் நற்பேற்றை நான் இழந்து துர்பாக்கியசாலி ஆகிவிட்டேனே!" என்று (வருத்தத்துடன்) கூறினாள். அன்று அல்லாஹ்வின் தூதர் (ஸல்) அவர்களும் தோழர்களும் முன்னே சென்று பனூ சாஇதா சமுதாயக் கூடத்தில் அமர்ந்துகொண்டனர். பிறகு "எங்களுக்குக் குடிக்க தண்ணீர் கொடுங்கள்" என்று என்னிடம் சொன்னார்கள். ஆகவே,நான் அவர்களுக்காக இந்தக் கிண்ணத்தை எடுத்துக்கொண்டு புறப்பட்டுச் சென்று அதில் அவர்களுக்குத் தண்ணீர் (கொண்டு வந்து) புகட்டினேன். இந்த ஹதீஸ் இரு அறிவிப்பாளர்தொடர்களில் வந்துள்ளது. இதன் அறிவிப்பாளர்களில் ஒருவரான அபூஹாஸிம் (ரஹ்) அவர்கள் கூறுகிறார்கள்: (பின்னர்) சஹ்ல் (ரலி) அவர்கள் அந்தக் கிண்ணத்தை வெளியில் எடுத்தார்கள். அதில் நாங்களும் பருகினோம். பிறகு (கலீஃபா) உமர் பின் அப்தில் அஸீஸ் (ரஹ்) அவர்கள் அதைத் தமக்கு அன்பளிப்பாகத் தரும்படி கேட்க, சஹ்ல் (ரலி) அவர்கள் அதை அவர்களுக்கு அன்பளிப்பாக வழங்கிவிட்டார்கள். அபூபக்ர் பின் இஸ்ஹாக் (ரஹ்) அவர்களது அறிவிப்பில், "எங்களுக்குக் குடிக்கத் தண்ணீர் கொடுங்கள், சஹ்லே!" என அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் கூறினார்கள் என்று இடம்பெற்றுள்ளது. அத்தியாயம் : 36
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5236</td></tr><tr><td>Arabic No</td><td>2007</td></tr><tr><td>Reference</td><td>Book 36 Hadith 110</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Bana yine Muhammed b. Sehl EI-Temİmî ve Ebü Bekr b. İshâk rivayet ettiler. (Ebû Bekr: Bize haber verdi tâbirini kullandı. İbn-i Sehl ise: Bize İbn-i Ebî Meryem rivayet etti, dedi.) (Demişki): Bize Muhammed —Bu zat Ebû Gassân İbn-i Mutarrifdir.— haber verdi. (Dediki): Bana Ebû Hazım, Sehl b. Sa'd'dan naklen haber verdi. Sehl (şöyle demiş) : Resûlullah (Sallallahu Aleyhi ve Sellem)'e Arablardan bir kadının lâfını ettiler. O da Ebû Useyd'e kadına haber göndermesini emir buyurdu. Ebû Useyd kadına haber gönderdi. Ve kadın gelerek Benî Sâide'nin kal'asına misafir indi. Derken Resûlullah (Sallallahu Aleyhi ve Sellem) çıktı ve kadının yanma gelerek içeri girdi. Bir de ne görsün, kadın boynunu eğmiş. Resûlullah (Sallallahu Aleyhi ve Sellem) kendisi ile konuşunca kadın: — Ben senden Allah'a sığınırım, dedi. O da: — «Ben seni kenefimden sığındırdım.» dedi. Bunun üzerine ashab kadına : — Bu kim, biliyor musun? dediler. Kadın : — Hayır! cevâbını verdi. — Bu Resûlullah (Sallallahu Aleyhi ve Sellem)'dir* Seni istemeye geldi, dediler. Kadın : — Ben bu işe yaramaz çıktım, cevâbını verdi. Sehl demiş ki: O gün Resûlullah (Saliallahu Aleyhi ve Sellem) geldi. Hattâ kendisi ve ashabı Benî Sâide'nin çatısı altında oturdular. Sonra Sehl'e: «Bizi sula!» buyurdular. Sehl: Ben de kendilerine su tası çıkararak ondan sundum. Ebû Haşim şöyle demiş: «Onun üzerine Sehl o tası bize çıkardı ve ondan su içtik. Bundan sonra Ömer h. Abdîlaziz onu hediyye olarak istedi. O da kendisine onu hediyye etti.» Ebû Bekr b. İshak'ın rivayetinde: «Bize su ver yâ Sehl!» cümlesi vardır. İzah 2008 de
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5236</td></tr><tr><td>Arabic No</td><td>2007</td></tr><tr><td>Reference</td><td>Book 36 Hadith 110</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
محمد بن سہل تیمی اور ابو بکر بن اسحٰق نے کہا : ہمیں ابن ابی مریم نے حدیث بیان کی ، کہا : ہمیں ابو غسان محمد بن مطرف نے بتا یا کہ مجھے ابو حازم نے حضرت سہل بن سعد رضی اللہ تعالیٰ عنہ سے روایت بیان کی ، کہا : رسول اللہ صلی اللہ علیہ وسلم کے سامنے عرب کی ایک عورت کا ذکر کیا گیا ۔ ( اس کے والد نعمان بن ابی الجون کندی نے پیش کش کی ) آپ نے ابو اسید رضی اللہ تعالیٰ عنہ سے کہا : کہ اس ( عورت کولا نے کے لیے اس ) کی طرف سواری وغیرہ بھیجیں ۔ تو انھوں ( حضرت ابو اسید رضی اللہ تعالیٰ عنہ ) نے بھیج دی وہ عورت آئی بنو ساعدہ کے قلعہ نما مکانات میں ٹھہری رسول اللہ صلی اللہ علیہ وسلم گھر سے روانہ ہو کر اس کے پاس تشریف لے گئے جب آپ اس کے پاس گئے تو وہ عورت سر جھکا ئے ہو ئے تھی رسول اللہ صلی اللہ علیہ وسلم نے جب اس سے بات کی تو وہ کہنے لگی : میں آپ سے اللہ کی پناہ میں آتی ہوں ۔ آپ صلی اللہ علیہ وسلم نے فرما یا : " میں نے تمھیں خود سے پناہ دے دی ۔ " لوگوں نے اس سے کہا : کیا تم جا نتی ہو یہ کو ن ہیں ؟ اس نے کہا : نہیں انھوں نے کہا : یہ رسول اللہ صلی اللہ علیہ وسلم تھے اور تمھیں نکا ح کا پیغا م دینے تمھا رے پاس آئے تھے ۔ اس نے کہا : میں اس سے کم تر نصیب والی تھی ۔ سہل رضی اللہ تعالیٰ عنہ نے کہا : اس دن رسول اللہ صلی اللہ علیہ وسلم تشریف لا ئے آپ خود اور آپ کے ساتھ بنو ساعدہ کے چھت والے چبوترے پر تشریف فرما ہو ئے پھر سہل پانی پلا ؤ " کہا : میں نے ان کے لیے وہی پیا لہ ( نما برتن ) نکا لا اور اس میں آپ کو پلا یا ۔ ابو حازم نے کہا : سہل رضی اللہ تعالیٰ عنہ نے ہمارے لیے بھی وہی پیالہ نکالا اور ہم نے بھی اس میں سے پیا ، پھر عمر بن عبد العزیز نے حضرت سہل رضی اللہ تعالیٰ عنہ سے وہ پیا لہ بطور ہبہ مانگ لیا ۔ حضرت سہل رضی اللہ تعالیٰ عنہ نے وہ پیا لہ ان کو ہبہ کر دیا ۔ ابو بکر بن اسحاق کی روایت میں ہے : آپ صلی اللہ علیہ وسلم نے فرما یا : " سہل!ہمیں ( کچھ ) پلا ؤ ۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5236</td></tr><tr><td>Arabic No</td><td>2007</td></tr><tr><td>Reference</td><td>Book 36 Hadith 110</td></tr></tbody></table></div>