## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
وَحَدَّثَنَا عُبَيْدُ اللَّهِ بْنُ مُعَاذٍ الْعَنْبَرِيُّ، وَحَامِدُ بْنُ عُمَرَ الْبَكْرَاوِيُّ، وَمُحَمَّدُ بْنُ عَبْدِ، الأَعْلَى جَمِيعًا عَنِ الْمُعْتَمِرِ بْنِ سُلَيْمَانَ، - وَاللَّفْظُ لاِبْنِ مُعَاذٍ - حَدَّثَنَا الْمُعْتَمِرُ، حَدَّثَنَا أَبِي، عَنْ أَبِي عُثْمَانَ، - وَحَدَّثَ أَيْضًا، - عَنْ عَبْدِ الرَّحْمَنِ بْنِ أَبِي بَكْرٍ، قَالَ كُنَّا مَعَ النَّبِيِّ صلى الله عليه وسلم ثَلاَثِينَ وَمِائَةً فَقَالَ النَّبِيُّ صلى الله عليه وسلم ‏"‏ هَلْ مَعَ أَحَدٍ مِنْكُمْ طَعَامٌ ‏"‏ ‏.‏ فَإِذَا مَعَ رَجُلٍ صَاعٌ مِنْ طَعَامٍ أَوْ نَحْوُهُ فَعُجِنَ ثُمَّ جَاءَ رَجُلٌ مُشْرِكٌ مُشْعَانٌّ طَوِيلٌ بِغَنَمٍ يَسُوقُهَا فَقَالَ النَّبِيُّ صلى الله عليه وسلم ‏"‏ أَبَيْعٌ أَمْ عَطِيَّةٌ - أَوْ قَالَ - أَمْ هِبَةٌ ‏"‏ ‏.‏ فَقَالَ لاَ بَلْ بَيْعٌ ‏.‏ فَاشْتَرَى مِنْهُ شَاةً فَصُنِعَتْ وَأَمَرَ رَسُولُ اللَّهِ صلى الله عليه وسلم بِسَوَادِ الْبَطْنِ أَنْ يُشْوَى ‏.‏ قَالَ وَايْمُ اللَّهِ مَا مِنَ الثَّلاَثِينَ وَمِائَةٍ إِلاَّ حَزَّ لَهُ رَسُولُ اللَّهِ صلى الله عليه وسلم حُزَّةً حُزَّةً مِنْ سَوَادِ بَطْنِهَا إِنْ كَانَ شَاهِدًا أَعْطَاهُ وَإِنْ كَانَ غَائِبًا خَبَأَ لَهُ - قَالَ - وَجَعَلَ قَصْعَتَيْنِ فَأَكَلْنَا مِنْهُمَا أَجْمَعُونَ وَشَبِعْنَا وَفَضَلَ فِي الْقَصْعَتَيْنِ فَحَمَلْتُهُ عَلَى الْبَعِيرِ ‏.‏ أَوْ كَمَا قَالَ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5364</td></tr><tr><td>Arabic No</td><td>2056</td></tr><tr><td>Reference</td><td>Book 36 Hadith 238</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
হাদিস একাডেমি নাম্বারঃ ৫২৫৯, আন্তর্জাতিক নাম্বারঃ ২০৫৬ ৫২৫৯-(১৭৫/২০৫৬) উবাইদুল্লাহ ইবনু মুআয আম্বারী, হামিদ ইবনু উমার বাকরাবী ও মুহাম্মাদ ইবনু 'আবদুল আ'লা (রহঃ) ..... আব্দুর রহমান ইবনু আবূ বাকর (রাযিঃ) হতে বর্ণিত। তিনি বলেন, আমরা একশ' তিরিশ জন ব্যক্তি (এক সফরে) নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর সাথে ছিলাম। নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বললেনঃ তোমাদের মাঝে কারো নিকট খাবার আছে কি? দেখা গেল, এক লোকের নিকটে এক সা’ বা সমপরিমাণ খাদ্য রয়েছে। তা (মিশিয়ে) খামীর করা হলো। অতঃপর এলোমেলো চুলে দীর্ঘাঙ্গ এক মুশরিক লোক কিছু ছাগল হাকিয়ে নিয়ে আসলো। নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বললেনঃ এগুলো বিক্রি করে দিবে না উপটৌকন হিসেবে দিবে? কিংবা উপঢৌকন শব্দের স্থলে তিনি দান করবে বলেছিলেন। লোকটি স্বলল, না; আমি বরং বিক্রি করবো। নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম তার নিকট থেকে একটি বকরী ক্রয় করলেন। বকরীটা যাবাহ করা হলো। রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম তার কলিজা ভূনা করতে নির্দেশ দিলেন। বর্ণনাকারী আব্দুর রহমান (রাযিঃ) বলেন, আল্লাহর শপথ! একশ' ত্রিশজনের মাঝে একজনও এমন ছিল না যাকে রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এক টুকরা কলিজা দেননি। যারা সমবেত ছিল তাদেরকে তো তখনই দিয়েছেন। আর যারা উপস্থিত ছিল না তাদের জন্য পৃথকভাবে তুলে রেখেছেন। বর্ণনাকারী বলেন, গোশত দুটি বাসনে বন্টন করে রাখলেন। আমরা সবাই তৃপ্তি সহকারে খেলাম। তারপরও বাসন দুটিতে গোশত অতিরিক্ত থাকলো। আমি তা উটের উপর বহন করে নিয়ে গেলাম। কিংবা তিনি (রাবী) যেভাবে রিওয়ায়াত করেছেন। (ইসলামিক ফাউন্ডেশন ৫১৯১, ইসলামিক সেন্টার ৫২০৩)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5364</td></tr><tr><td>Arabic No</td><td>2056</td></tr><tr><td>Reference</td><td>Book 36 Hadith 238</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Abd al-Rahman b. Abu Bakr reported:We were one hundred and thirty (persons) with Allah's Apostle (ﷺ). Allah's Apostle (ﷺ) said: Does any one of You possess food? There was a person with (us) who had a sa' of flour or something about that, and it was kneaded. Then a tall polytheist with dishevelled hair came driving his flock of sheep. Thereupon Allah's Apostle (ﷺ) said: Would you like to sell it (any one of these goats) or offer it as a gift or a present? He said: No, (I am not prepared to offer as a gift), but I would sell it. He (the Holy Prophet) bought a sheep from him, and it was slaughtered and its meat was prepared, and Allah's Messenger (ﷺ) commanded that its liver should be roasted. He (the narrator) said: By Allah, none among one hundred and thirty persons was left whom Allah's Messenger (ﷺ) had not given a part out of her liver; if anyone was present he gave it to him. but if he was absent it was set aside for him. And he (the Holy Prophet) filled two bowls (one with soup and the other with mutton) and we all ate out of them to our hearts' content, but (still) some part was (left) in (those) two bowls, and I placed it on the camel- (or words to the same effect)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5364</td></tr><tr><td>Arabic No</td><td>2056</td></tr><tr><td>Reference</td><td>Book 36 Hadith 238</td></tr></tbody></table></div>

## French


<div dir="ltr" lang="fr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
D'après 'Abdourrahmân Ibn 'Abî Bakr (que Dieu l'agrée), Nous étions cent trente personnes avec le Prophète (paix et bénédiction de Dieu sur lui), il nous dit : "Y a-t-il quelqu'un d'entre vous qui a de la nourriture?". Or il se trouva qu'un homme en avait un sâ' (mesure de 8 poignées de grandeur moyenne) ou presque une quantité équivalente de farine qu'on fit pétrir. A ce moment, arriva un polythéiste, de haute stature et aux cheveux ébouriffés; il conduisait un troupeau de moutons. - "A vendre ou à faire cadeau - ou suivant une variante à faire donation?", lui demanda le Prophète (paix et bénédiction de Dieu sur lui). - "Non, à vendre", répliqua l'homme. Le Prophète acheta de lui une brebis qu'on prépara; puis l'Envoyé de Dieu (paix et bénédiction de Dieu sur lui) ordonna d'en faire rôtir le foie. Le rapporteur poursuivit : "J'en jure par Dieu, il n'y eut pas un seul de ces cent trente hommes à qui l'Envoyé de Dieu (paix et bénédiction de Dieu sur lui) n'offrit un morceau de ce foie rôti. On servit un morceau à chacun de ceux qui étaient présents et on mit en réserve la part des absents. On fit remplir deux grands plats, nous en mangeâmes jusqu'à la satiété et il resta encore une part dans les deux plats, que je chargeai sur le chameau. Tel était le récit (ou quelque chose d'approchant)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5364</td></tr><tr><td>Arabic No</td><td>2056</td></tr><tr><td>Reference</td><td>Book 36 Hadith 238</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Dan telah menceritakan kepada kami ['Ubaidullah bin Mu'adz Al 'Anbari] dan [Hamid bin Al Bakrawi] dan [Muhammad bin 'Abdul A'la] seluruhnya dari [Al Mu'tamir bin Sulaiman] dan lafazh ini milik Ibnu Mu'adz; Telah menceritakan kepada kami [Al Mu'tamar]; Telah menceritakan kepada kami [Bapakku] dari [Abu 'Utsman]; dan telah menceritakan kepada kami pula ['Abdurrahman bin Abu Bakr] ia berkata; "Kami sejumlah seratus tiga puluh orang bersama Rasulullah shallallahu 'alaihi wasallam. Lalu beliau bertanya; 'Apakah salah seorang di antara kalian ada yang memiliki makanan?" Ternyata ada seorang sahabat yang membawa satu sha' makanan atau kurang lebih satu sha'. Lalu dibuatlah adonan. Tak lama kemudian, ada seorang musyrik yang tinggi, kurus, dan berambut kusut sambil mengiring kambing. Maka Rasulullah bertanya kepadanya: 'Apakah kambing ini dijual atau dihadiahkan? ' Orang musyrik itu menjawab; 'Kambing ini dijual.' Akhirnya Rasulullah membeli kambing tersebut darinya, lalu disembelih dan beliau memerintahkan agar hati kambing itu dipanggang. Abdurrahman berkata; 'Demi Allah, setiap sahabat yang berjumlah seratus tiga puluh itu mendapat jatah dari kambing panggang Rasulullah shallallahu 'alaihi wasallam. Jika kebetulan orangnya hadir, maka Rasulullah menyimpan jatahnya. Abdurrahman berkata; 'Rasulullah shallallahu 'alaihi wasallam membagi daging kambing tersebut menjadi dua periuk dan kami semua memakannya hingga kenyang. Lebih dari itu, kami pun tidak sanggup untuk menghabiskannya. Lalu sisanya dalam dua periuk itu kami angkut dengan unta. Atau kira-kira seperti itulah yang dia ceritakan
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5364</td></tr><tr><td>Arabic No</td><td>2056</td></tr><tr><td>Reference</td><td>Book 36 Hadith 238</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
அப்துர் ரஹ்மான் பின் அபீபக்ர் (ரலி) அவர்கள் கூறியதாவது: நாங்கள் நூற்று முப்பது பேர் நபி (ஸல்) அவர்களுடன் இருந்தோம். அப்போது நபி (ஸல்) அவர்கள், "உங்களில் யாரிடமாவது உணவு இருக்கிறதா?" என்று கேட்டார்கள். அப்போது ஒரு மனிதரிடம் ஒரு "ஸாஉ" அல்லது "கிட்டத்தட்ட அந்த அளவு" உணவு(க்கு வேண்டிய மாவு) இருந்தது. அது தண்ணீர் விட்டுக் குழைக்கப்பட்டது. (சற்று நேரத்திற்குப்) பின் பரட்டைத் தலையுடைய உயரமான இணைவைப்பாளரான மனிதர் ஒருவர் ஆடுகளை ஓட்டியபடி வந்தார். அவரிடம் நபி (ஸல்) அவர்கள், "(இவை) விற்பனைக்கா? அல்லது அன்பளிக்கவா?" என்று கேட்டார்கள். அவர், "இல்லை. விற்பனைக்குத்தான்" என்றார். அவரிடமிருந்து நபி (ஸல்) அவர்கள் ஓர் ஆட்டை விலைக்கு வாங்கினார்கள். அது அறு(த்துச் சமை)க்கப்பட்டது. அதன் ஈரலைப் பொரிக்கும்படி நபி (ஸல்) அவர்கள் உத்தரவிட்டார்கள். அல்லாஹ்வின் மீதாணையாக! எங்கள் நூற்று முப்பது பேரில் ஒருவர் விடாமல் ஆளுக்கொரு துண்டை நபி (ஸல்) அவர்கள் வெட்டித் தந்தார்கள். அங்கிருந்தவருக்கு (அப்போதே) அவரிடமே கொடுத்தார்கள். அங்கில்லாதவருக்காக எடுத்து வைத்(துப் பிறகு கொடுத்)தார்கள். பிறகு இரு அகன்ற தட்டுக(ளில் அந்த இறைச்சி)களை வைத்தார்கள். அவற்றிலிருந்து நாங்கள் அனைவரும் வயிறார உண்டோம். அப்படியிருந்தும் அவ்விரு தட்டுகளிலும் மீதி இருந்தது. எனவே, அதை நான் ஒட்டகத்தின் மீது ஏற்றிக்கொண்டேன். அத்தியாயம் : 36
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5364</td></tr><tr><td>Arabic No</td><td>2056</td></tr><tr><td>Reference</td><td>Book 36 Hadith 238</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Bize Ubeydullah b. Muaz El-Anberî ile Hamid b. Ömer EI-Bekrâvî ve Muhammed b. Abdi'l-A'lâ toptan Mu'temir b. Süleyman'dan rivayet ettiler. Lâfız İbni Muaz'ındir. (Dedilerki): Bize Mu'temir rivayet etti. (Dediki): Bize babam Ebû Osman'dan ve bir de Abdurrahman b. Ebî Bekr'den naklen rivayet etti. Abdurrahman şöyle demiş : Peygamber (Sallallahu Aleyhi ve Sellem) ile birlikte yüz otuz kişi bulunuyorduk. Nebi (Sallallahu Aleyhi ve Sellem): «Sizden hiç birinizin yanında yiyecek var m;?» diye sordu. Bir de baktık, bir adamın yanında bir ölçek zahire veya bunun gibi bir şey bulunuyormuş. Hemen hamur karıldı. Sonra saçları dağılmış uzun boylu müşrik bir adam bir sürü koyun sürerek (yanımıza) geldi. Nebi (Sallallahu Aleyhi ve Sellem) (ona) : «Satılık mı, hediyye mi? —Yahut hibe mi?—» diye sordu. Adam: — Hayır! Bilâkis satılık, dedi. Ve ondan bir koyun satın aldı. Koyun hasıllandi. Ve Resûlullah (Sallallahu Aleyhi ve Sellem) ciğerinin kızartılmasını emir buyurdu. Allah'a yemin ederim yüz otuz kişiden hiç bir kimse yoktur ki, Resûlullah (Sallallahu Aleyhi ve Sellem) o koyunun ciğerinden bir parça vermemiş olsun. Mevcut ise kendisine verdi. Gaibse onun için sakladı. Abdurrahman: «Akide çanak doldurdu, bunlardan hepimiz yedik ve doyduk. Kaplarda yemek de arttı da, ben onu deveye yükledim.» demiştir. Yahut dediği gibidir
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5364</td></tr><tr><td>Arabic No</td><td>2056</td></tr><tr><td>Reference</td><td>Book 36 Hadith 238</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ابو عثمان نے حضرت عبدالرحمان بن ابی بکر رضی اللہ تعالیٰ عنہ سے روایت کی ، کہا : سیدنا عبدالرحمن بن ابی بکر رضی اللہ عنہ کہتے ہیں کہ ہم رسول اللہ صلی اللہ علیہ وسلم کے ساتھ ایک سو تیس آدمی تھے ۔ آپ صلی اللہ علیہ وسلم نے فرمایا کہ کیا کسی پاس کھانا ہے؟ ایک شخص کے پاس ایک صاع اناج نکلا یا تھوڑا کم یا زیادہ ۔ پھر وہ سب گوندھا گیا ۔ پھر ایک مشرک آیا ، جس کے بال بکھرے ہوئے تھے لمبا بکریاں لے کر ہانکتا ہوا رسول اللہ صلی اللہ علیہ وسلم کے پاس پہنچا تو آپ صلی اللہ علیہ وسلم نے فرمایا کہ تو ( بکری ) بیچتا ہے یا ہدیہ دیتا ہے؟ اس نے کہا کہ نہیں بیچتا ہوں ۔ آپ صلی اللہ علیہ وسلم نے اس سے ایک بکری خریدی تو اس کا گوشت تیار کیا گیا اور آپ صلی اللہ علیہ وسلم نے کلیجی ، گردے ، ۔ دل وغیرہ کو بھوننے کا حکم دیا ، ( حضرت عبدالرحمان رضی اللہ تعالیٰ عنہ نے ) کہا : اللہ کی قسم!رسول اللہ صلی اللہ علیہ وسلم نے ایک سوتیس آدمیوں میں سے ہر ایک شخص کو اس کی کلیجی وغیرہ کا ایک ٹکڑا دیا ، جو شخص موجودتھا اس کو دے دیا اور جو موجود نہیں تھا اسکے لئے رکھ لیا ۔ ( عبدالرحمان بن ابی بکر رضی اللہ تعالیٰ عنہ نے ) کہا : آپ نے ( کھانے کے لئے ) دو بڑے پیالے بنائے اور ہم سب نے ان دو پیالوں میں سے کھایا اور سیر ہوگئے ، دونوں پیالوں میں کھانا پھر بھی بچ گیا تو میں نے اس کو اونٹ پر لاد لیا یاجس طرح انھوں نےکہا ۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5364</td></tr><tr><td>Arabic No</td><td>2056</td></tr><tr><td>Reference</td><td>Book 36 Hadith 238</td></tr></tbody></table></div>