## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
وَحَدَّثَنِي زُهَيْرُ بْنُ حَرْبٍ، حَدَّثَنَا إِسْمَاعِيلُ بْنُ إِبْرَاهِيمَ، عَنِ الْجُرَيْرِيِّ، عَنْ أَبِي، الْعَلاَءِ عَنِ الأَحْنَفِ بْنِ قَيْسٍ، قَالَ قَدِمْتُ الْمَدِينَةَ فَبَيْنَا أَنَا فِي، حَلْقَةٍ فِيهَا مَلأٌ مِنْ قُرَيْشٍ إِذْ جَاءَ رَجُلٌ أَخْشَنُ الثِّيَابِ أَخْشَنُ الْجَسَدِ أَخْشَنُ الْوَجْهِ فَقَامَ عَلَيْهِمْ فَقَالَ بَشِّرِ الْكَانِزِينَ بِرَضْفٍ يُحْمَى عَلَيْهِ فِي نَارِ جَهَنَّمَ فَيُوضَعُ عَلَى حَلَمَةِ ثَدْىِ أَحَدِهِمْ حَتَّى يَخْرُجَ مِنْ نُغْضِ كَتِفَيْهِ وَيُوضَعُ عَلَى نُغْضِ كَتِفَيْهِ حَتَّى يَخْرُجَ مِنْ حَلَمَةِ ثَدْيَيْهِ يَتَزَلْزَلُ قَالَ فَوَضَعَ الْقَوْمُ رُءُوسَهُمْ فَمَا رَأَيْتُ أَحَدًا مِنْهُمْ رَجَعَ إِلَيْهِ شَيْئًا - قَالَ - فَأَدْبَرَ وَاتَّبَعْتُهُ حَتَّى جَلَسَ إِلَى سَارِيَةٍ فَقُلْتُ مَا رَأَيْتُ هَؤُلاَءِ إِلاَّ كَرِهُوا مَا قُلْتَ لَهُمْ ‏.‏ قَالَ إِنَّ هَؤُلاَءِ لاَ يَعْقِلُونَ شَيْئًا إِنَّ خَلِيلِي أَبَا الْقَاسِمِ صلى الله عليه وسلم دَعَانِي فَأَجَبْتُهُ فَقَالَ ‏"‏ أَتَرَى أُحُدًا ‏"‏ ‏.‏ فَنَظَرْتُ مَا عَلَىَّ مِنَ الشَّمْسِ وَأَنَا أَظُنُّ أَنَّهُ يَبْعَثُنِي فِي حَاجَةٍ لَهُ فَقُلْتُ أَرَاهُ ‏.‏ فَقَالَ ‏"‏ مَا يَسُرُّنِي أَنَّ لِي مِثْلَهُ ذَهَبًا أُنْفِقُهُ كُلَّهُ إِلاَّ ثَلاَثَةَ دَنَانِيرَ ‏"‏ ‏.‏ ثُمَّ هَؤُلاَءِ يَجْمَعُونَ الدُّنْيَا لاَ يَعْقِلُونَ شَيْئًا ‏.‏ قَالَ قُلْتُ مَا لَكَ وَلإِخْوَتِكَ مِنْ قُرَيْشٍ لاَ تَعْتَرِيهِمْ وَتُصِيبُ مِنْهُمْ ‏.‏ قَالَ لاَ وَرَبِّكَ لاَ أَسْأَلُهُمْ عَنْ دُنْيَا وَلاَ أَسْتَفْتِيهِمْ عَنْ دِينٍ حَتَّى أَلْحَقَ بِاللَّهِ وَرَسُولِهِ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2306</td></tr><tr><td>Arabic No</td><td>992.01</td></tr><tr><td>Reference</td><td>Book 12 Hadith 43</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
হাদিস একাডেমি নাম্বারঃ ২১৯৬, আন্তর্জাতিক নাম্বারঃ ৯৯২ ২১৯৬-(৩৪/৯৯২) যুহায়র ইবনু হারব (রহঃ) ..... আহনাফ ইবনু কায়স (রাযিঃ) থেকে বর্ণিত। তিনি বলেন, আমি মদীনায় আসার পর একদা কুরায়শদের এক সমাবেশে বসা ছিলাম। সেখানে তাদের (গোত্রীয় নেতা) দলপতিও উপস্থিত ছিল। এমন সময় মোটা কাপড় পরিহিত সুঠাম দেহের অধিকারী ও রুক্ষ চেহারার এক ব্যক্তি আসল। এসে দাঁড়িয়ে বলল, সম্পদ কুক্ষিগতকারীদের সুসংবাদ দাও যে, একটি পাথর জাহান্নামের আগুনে উত্তপ্ত করে, তাদের কারো বুকের মাঝখানে রাখা হবে। এমনকি তার কাঁধের হাড় ভেদ করে বেরিয়ে যাবে এবং কাঁধের হাড়ের উপর রাখা হলে তা স্তনের বোটা ভেদ করে বেরিয়ে যাবে এবং পাথরটি (আগুনের উত্তাপের ফলে) কাঁপতে থাকবে। বর্ণনাকারী বলেন, উপস্থিত লোকেরা সবাই মাথা নত করে থাকল এবং তার বক্তব্যের প্রত্যুত্তরে কাউকে কিছু বলতে দেখলাম না। অতঃপর সে পেছন দিকে ফিরে এসে একটি খুঁটির কাছে বসে পড়ল, আমিও তাকে অনুসরণ করলাম। অর্থাৎ তার কাছে এসে বসলাম। তারপর আমি বললাম যে, এরা তো তোমার প্রতি অসন্তুষ্ট হয়েছে বলে আমি দেখতে পাচ্ছি। তিনি (উত্তরে) বললেন, এরা (দীন সম্পর্কে) কিছুই বোঝে না বা জ্ঞান রাখে না। আমার বন্ধুবর আবূল কাসিম সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম একবার আমাকে ডাকলেন এবং আমি উপস্থিত হলাম। অতঃপর তিনি বললেন, “তুমি উহুদ পাহাড় দেখতে পাচ্ছ? আমি তখন সূর্যের দিকে আমার দৃষ্টি নিবন্ধ করলাম এবং ধারণা করলাম, হয়ত তিনি আমাকে তার কোন কাজে পাঠাবেন। আমি বললাম, হ্যাঁ দেখতে পাচ্ছি। অতঃপর তিনি বললেন, আমি এটা চাই না যে, এ পাহাড় আমার জন্য সোনা হোক আর যদি এত অঢেল সম্পদের মালিক আমি হয়েও যাই তাহলে ঋণ পরিশোধের জন্য, শুধু তিন দীনার রেখে বাকি সব খরচ করে দিব। অতঃপর এরা শুধু দুনিয়া সঞ্চয় করছে, আর কিছুই বুঝছে না।" বর্ণনাকারী বলেন, আমি তাকে বললাম, তুমি ও তোমার কুরায়শ গোত্রীয় ভাইদের কী হয়েছে; তুমি তাদের কাছে প্রয়োজনে কেন যাও না মেলামেশা করো না আর কেন বা কোন কিছু গ্রহণ করো না? উত্তরে সে বলল, তোমার প্রভুর শপথ আমি আল্লাহ ও তার রসূলের সাথে সাক্ষাতের পূর্বে (অর্থাৎ মৃত্যু পর্যন্ত) তাদের কাছে পার্থিব কোন কিছু চাই না এবং দীন সম্পর্কেও কোন কিছু জিজ্ঞেস করব না। (ইসলামিক ফাউন্ডেশন ২১৭৫, ইসলামীক সেন্টার ২১৭৭)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2306</td></tr><tr><td>Arabic No</td><td>992.01</td></tr><tr><td>Reference</td><td>Book 12 Hadith 43</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ahnaf b. Qais reported:I came to Medina and when I was in the company of the grandees of Quraish a man with a crude body and an uncouth face wearing coarse clothes came there. He stood up before them and said: Give glad tidings to those whom who amass riches of the stones which would be heated in the Fire of Hell, and would be placed at the tick of the chest till it would project from the shoulder bone and would he put on the shoulder bone till it would project from the tick of his chest, and it (this stone) would continue passing and repassing (from one side to the other). He (the narrator) said: Then people hung their heads and I saw none among them giving any answer. He then returned and I followed him till he sat near a pillar. I said: I find that these (people) disliked what you said to them and they do not understand anything. My friend Abu'l-Qasim (Muhammad) (may peace he upon him) called me and I responded to him, and he said: Do you see Uhud? I saw the sun (shining) on me and I thought that he would send me on an errand for him. So I said: I see it. Upon this he said: Nothing would delight me more than this that I should have gold like it (equal to the bulk of Uhud), and I should spend it all except three dinars. (How sad it is) that they hoard worldly riches, and they know nothing. I said: What about you and your brothers Quraish? You do not go to thein for any need and do not accept anything from them. He said: By Allah, I neither beg anything from them (from worldly goods), nor do I ask them anything about religion till I meet my Allah and His Messenger
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2306</td></tr><tr><td>Arabic No</td><td>992.01</td></tr><tr><td>Reference</td><td>Book 12 Hadith 43</td></tr></tbody></table></div>

## French


<div dir="ltr" lang="fr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
D'après Abou Dharr (que Dieu l'agrée) : Al-'Ahnaf Ibn Qays a dit : Je gagnai Médine et alors que j'étais assis parmi un groupe de Qoraychites, arriva un homme grossier de traits, d'aspect et de vêtements. Il s'adressa à eux en disant : "Annonce aux thésauriseurs (des biens et des fortunes qui ne s'acquittent pas de l'aumône légale) qu'on fera rougir dans le feu de la Géhenne pour les punir des pierres qu'on appliquera sur le mamelon de chacun d'eux, qu'on laissera là jusqu'à ce qu'elle pénètre la clavicule de son épaule; et qu'on posera ensuite sur sa clavicule jusqu'à ce qu'elle pénètre son mamelon; ce qui le fera trembler". Ceci dit, les gens inclinèrent leur tête sans souffler mot. Quant à l'homme, il s'en alla et moi, de le suivre. Il s'installa auprès d'un pilier. Je lui dis : "Je crois que ces gens ont pris en horreur ce que tu leur avais dit". - "Ceux-ci ne comprennent rien. Mon ami, Abou Al-Qâsim (paix et bénédiction de Dieu sur lui) m'appela un jour et me dit : "Vois-tu le mont 'Uhud ?". Alors, je regardai le soleil (pour savoir l'heure), car je pensai qu'il (paix et bénédiction de Dieu sur lui) voulait me charger de quelque mission, et je répondis : "Oui, je le vois". - "Ah! reprit-il, je ne serais pas heureux de posséder une quantité d'or égale à la montagne de 'Uhud, sinon que pour la dépenser toute en aumône et n'en conserver que trois dinars. Et voilà que ces gens-là, ajouta Abou Dharr, s'acharnent à amasser les biens de l'ici-bas sans penser". Je lui dis alors : "Pourquoi ne demandes-tu pas de l'argent à tes coreligionnaires Qoraychites?". - "Non, par Dieu! Je ne leur demanderai jamais des biens temporels ni ne leur expliquerai leur religion jusqu'à ce que j'aille rejoindre Dieu et Son Envoyé". Encouragement à dépenser l'argent et la compensation que recevra celui qui le fait
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2306</td></tr><tr><td>Arabic No</td><td>992.01</td></tr><tr><td>Reference</td><td>Book 12 Hadith 43</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Dan telah menceritakan kepadaku [Zuhair bin Harb] Telah menceritakan kepada kami [Isma'il bin Ibrahim] dari [Al Jurairi] dari [Abul Ala'] dari [Al Ahnaf bin Qais] ia berkata; Ketika aku berada di Madinah dan berada dalam sekelompok orang Quraisy, tiba-tiba datanglah [seorang laki-laki] yang berpakaian dari bahan yang kasar, kulit serta wajahnya juga kasar. Kemudian laki-laki itu berdiri seraya berkata, "Berilah kabar gembira kepada orang-orang yang menumpuk harta (tidak membayar zakat), bahwa mereka akan disiksa dengan batu yang dipanaskan di dalam neraka jahannam. Lalu diletakkan di atas dada salah seorang dari mereka hingga batu itu keluar dari pundak mereka. Kemudian batu itu diletakkan di tengah-tengah kedua pundaknya hingga keluar dari dadanya dengan mendidih." (Mendengar hal itu) orang-orang pun menundukkan kepala. Dan aku tidak melihat seorang pun dari mereka kembali memandangnya. Kemudian laki-laki itu berbalik, lalu kuikuti sampai ia duduk di rombongannya. Maka kukatakan padanya, "Tidaklah aku melihat mereka, melainkan benci terhadap apa yang telah Anda katakan." Ia berkata, "Sesungguhnya orang-orang itu tidak memahami sedikitpun. Sesungguhnya kekasihku Abu Al Qasim shallallahu 'alaihi wasallam pernah memanggilku, lalu aku pun menjawab panggilannya. Kemudian beliau bertanya: 'Apakah kamu melihat bukit gunung Uhud? ' Lalu aku melihat matahari yang menyinariku, dan aku menyangka bahwa beliau akan mengutusku untuk suatu keperluan, lalu aku jawab, "Ya, aku lihat." Maka beliau bersabda: 'Tidaklah membahagiakanku jika aku memiliki emas sebesar bukit itu, bahkan aku akan menginfakkannya seluruhnya, kecuali tiga Dinar.' Namun mereka itu mengumpulkan harta benda dunia dan mereka tidak berakal sedikitpun." Aku bertanya, "Kenapa Anda dan saudara perempuan Anda dari Quraisy tidak mendatangi dan meminta kepada mereka?" Ia menjawab, "Tidak, dan demi Rabb-mu, aku tidak akan meminta dunia pada mereka dan tidak pula akan meminta fatwa pada mereka hingga aku berjumpa dengan Allah dan Rasul-Nya
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2306</td></tr><tr><td>Arabic No</td><td>992.01</td></tr><tr><td>Reference</td><td>Book 12 Hadith 43</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
அஹ்னஃப் பின் கைஸ் (ரஹ்) அவர்கள் கூறியதாவது: நான் மதீனாவிற்குச் சென்றேன். அங்கு ஓர் அவையில் பங்கேற்றேன். அந்த அவையில் குறைஷிப் பிரமுகர்களும் இருந்தனர். அப்போது மிகவும் சொரசொரப்பான ஆடையும் முரட்டுத்தனமான தோற்றமும் முகமும் கொண்ட ஒரு மனிதர் (அங்கு) வந்து அவர்கள் முன் நின்று, "(ஸகாத் வழங்காமல்) செல்வத்தைக் குவித்து வைத்திருப்போருக்கு "நற்செய்தி" கூறுக: நரக நெருப்பில் சூடாக்கப்பட்ட ஒரு கல் அவருக்கு உண்டு. அந்தக் கல் அவர்களில் ஒருவரது மார்புக் காம்பின் மேல் வைக்கப்படும். உடனே அது அவரது தோளின் மேற்பகுதி எலும்பின் வழியாக வெளியேறும். பிறகு அந்தக் கல் அவரது தோளின் மேற்பகுதியில் வைக்கப்படும். உடனே அது மார்புக்காம்பின் வழியாக ஊடுருவி வெளியேறும்" என்று கூறினார். (இதைக் கேட்டவுடன்) மக்கள் தங்கள் தலைகளைத் தாழ்த்திக்கொண்டனர். அவர்களில் ஒருவர்கூட அவருக்கு எந்தப் பதிலும் அளித்ததை நான் பார்க்கவில்லை. பிறகு அந்த மனிதர் திரும்பிச்சென்றார். அவரைப் பின்தொடர்ந்து நான் சென்றேன். அவர் ஒரு தூணுக்கு அருகில் போய் உட்கார்ந்தார். அப்போது அவரிடம் நான், "தாங்கள் கூறியதைக் கேட்டு இம்மக்கள் வெறுப்படைந்ததையே நான் கண்டேன்" என்றேன். அதற்கு அவர், "இவர்கள் விவரமற்ற மக்கள். என் உற்ற தோழர் அபுல்காசிம் (முஹம்மத்-ஸல்) அவர்கள் (ஒருமுறை) என்னை அழைத்தார்கள். நான் அவர்களது அழைப்பிற்குப் பதிலளித்தேன். அப்போது அவர்கள் "உஹுத் மலையை நீர் பார்க்கிறீரா?" என்று கேட்டார்கள். தமது தேவை ஒன்றுக்காக அவர்கள் என்னை அங்கு அனுப்பப்போகிறார்கள் என எண்ணியவாறு (நேரத்தை அறிந்துகொள்ள) எனக்கு மேலே உள்ள சூரியனைப் பார்த்து விட்டு, "(ஆம்; உஹுத் மலையைப்) பார்க்கிறேன்" என்றேன். அப்போது "இந்த (உஹுத் மலை) அளவிற்கு என்னிடம் தங்கம் இருந்தாலும், அதில் அனைத்தையும் ஈந்து மகிழவே நான் விரும்புவேன். (அதில் எதையும் சேகரித்து வைக்கமாட்டேன். என் கடனை அடைப்பதற்காக நான் எடுத்து வைக்கும்) மூன்று பொற்காசுகளைத் தவிர" என்று அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் கூறினார்கள். ஆனால், இந்த மக்களோ எதையுமே அறியாதவர்களாய் உலக ஆதாயங்களைச் சேகரித்து வைத்துக் கொண்டிருக்கிறார்கள்" என்று கூறினார். நான், "உங்களுக்கும் உங்களுடைய குறைஷி சகோதர்களுக்கும் என்ன ஆயிற்று? நீங்கள் அவர்களை அணுகி அவர்களிடமிருந்து எதையும் பெற்றுக்கொள்வதில்லையே?" என்று கேட்டேன். அதற்கு அவர், "உம்முடைய இறைவன் மீதாணையாக! நான் அல்லாஹ்வையும் அவன் தூதரையும் சந்திக்கும்வரை இவர்களிடம் இவ்வுலகப் பொருட்கள் எதையும் கேட்கமாட்டேன்; மார்க்க விஷயங்களைப் பற்றிய எந்தத் தீர்ப்பையும் கோரவுமாட்டேன்" என்று கூறினார். அத்தியாயம் : 12
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2306</td></tr><tr><td>Arabic No</td><td>992.01</td></tr><tr><td>Reference</td><td>Book 12 Hadith 43</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Bana Züheyr b. Harb rivayet etti. (Dediki): Bize îsmail b. îbrâhîm, Cüreyri'den, o da Ebû'l-Alâ'dan, o da Ahnef b. Kays'dan naklen rivayet etti. Ahnef şöyle demiş: Medine'ye geldim bir defa ben, içlerinde Kureyş'in ileri gelenlerinden bir cemâat da bulunan bir halkada otururken son derece haşîn elbiseli, haşîn vücutlu ve haşin yüzlü bir adam çıka geldi. Cemâatin başlarına dikilerek: «Mal biriktirenlere cehennem ateşinde kızdırılan taşlarla müjde!.. Bu taşlar onların her birinin memeleri ucuna konacak, tâ kürek kemiklerinden çıkacak; kürek kemiği üzerine konacak, memeleri ucundan çıkacak. (Böylece) çalkalanıp duracaklar.» dedi. Bunun üzerine cemâat başlarını indirdiler, onlardan hiç birinin bu adama cevap verdiğini görmedim. Müteakiben adam dönüp gitti. Ben de peşinden takip ettim. Nihayet bir direğin yanına oturdu, (kendisine), — «Zannetmem ki bu zevat, senin kendilerine söylediklerinden hoşlanmamış olmasınlar.» dedim; O zat şu cevabı verdi: — «Hakikaten bunların hiç bir şey'e aklı ermiyor. Dostum Ebû'l-Kaasim (Sallallahu Aleyhi ve Sellem) beni çağırdı, ben de kendisine icabet ettim. (Bana): — Uhud'u görüyor musun? dedi. Akşama ne kalmış, diye baktım. Bir haceti için beni gönderecek zannediyordum. — (Evet) görüyorum... dedim. Bunun üzerine: — Bunun kadar altınım olmasını bunlardan üç dînâr müstesna olmak üzere hepsini infâk etmiş olmamı arzu etmem buyurdu. Sonra bunlar dünyâyı topluyorlar, hiç bir şey'e akılları ermiyor!» dedi. »Ben; — «Seninle kardeşlerin Kureyş arasında ne var ki onların yanına uğramıyor ve onlardan bir şey almıyorsun?» dedim. O zât: — «Rabbine Yemin ederim ki, taa Allah ve Resulüne kavuşuncaya kadar ben onlardan ne dünyalık isterim, ne de kendilerine din nâmına bir şey sorarım!» dedi
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2306</td></tr><tr><td>Arabic No</td><td>992.01</td></tr><tr><td>Reference</td><td>Book 12 Hadith 43</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ابو علاء نے حضرت احنف بن قیس ؒسے روایت کی انھوں نے کہا : میں مدینہ آیا تو میں قریشی سر داروں کے ایک حلقے میں بیٹھا ہوا تھا کہ اچانک کھردرے کپڑوں گٹھے ہو ئے جسم اور سخت چہرے والا ایک آدمی آیا اور ان کے سر پر کھڑا ہو گیا اور کہنے لگا ۔ مال و دولت جمع کرنے والوں کو اس تپتے ہو ئے پتھر کی بشارت سنا دو جس کو جہنم کی آگ میں گرم کیا جا ئے گا اور اسے ان کے ایک فرد کی نو ک پستان پر رکھا جائے گا حتیٰ کہ وہ اس کے دونوں کندھوں کی باریک ہڈیوں سے لہراتا ہوا نکل جا ئے گا اور اسے اس کے شانوں کی باریک ہڈیوں پر رکھا جا ئے گا حتیٰ کہ وہ اس کے پستانوں کے سروں سے حرکت کرتا ہوا نکل جا ئے گا ۔ ( احنف نے ) کہا : اس پر لو گوں نے اپنے سر جھکا لیے اور میں نے ان میں سے کسی کو نہ دیکھا کہ اسے کو ئی جواب دیا ہو کہا پھر وہ لو ٹا اور میں نے اس کا پیچھا کیا حتیٰ کہ وہ ایک ستون کے ساتھ ( ٹیک لگا کر ) بیٹھ گیا میں نے کہا : آپ نے انھیں جو کچھ کہا ہے میں نے انھیں اس کو نا پسند کرتے ہو ئے ہی دیکھا ہے انھوں نے کہا : یہ لو گ کچھ سمجھتے نہیں میرے خلیل ابو القاسم صلی اللہ علیہ وسلم نے مجھے بلا یا میں نے لبیک کہا تو آپ نے فر ما یا : " کیا تم احد ( پہاڑ ) کو دیکھتے ہو؟ میں نے دیکھا کہ مجھ پر کتنا سورج باقی ہے میں سمجھ رہا تھا کہ آپ مجھے اپنی کسی ضرورت کے لیے بھیجنا چا ہتے ہیں چنا نچہ میں نے عرض کی میں اسے دیکھ رہا ہوں تو آپ نے فر مایا : " میرے لیے یہ بات باعث مسرت نہ ہو گی کہ میرے پا س اس کے برا برا سونا ہو اور میں تین دیناروں کے سوا اس سارے ( سونے ) کو خرچ ( بھی ) کر ڈالوں ۔ پھر یہ لو گ ہیں دنیا جمع کرتے ہیں کچھ عقل نہیں کرتے ۔ میں نے ان سے پو چھا آپ کا اپنے ( حکمران ) قریشی بھائیوں کے ساتھ کیا معاملہ ہے آپ اپنی ضرورت کے لیے نہ ان کے پاس جا تے ہیں اور نہ ان سے کچھ لیتے ہیں ؟ انھوں نے جواب دیا نہیں تمھا رے پرودیگار کا قسم! نہ میں ان سے دنیا کی کو ئی چیز مانگوں گا نہ ہی ان سے کسی دینی مسئلے کے بارے میں پو چھوں گا یہاں تک کہ میں اللہ اور اس کے رسول اللہ صلی اللہ علیہ وسلم سے جا ملوں ۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2306</td></tr><tr><td>Arabic No</td><td>992.01</td></tr><tr><td>Reference</td><td>Book 12 Hadith 43</td></tr></tbody></table></div>