## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا مُحَمَّدُ بْنُ عَبْدِ اللَّهِ بْنِ نُمَيْرٍ، حَدَّثَنَا أَبِي، حَدَّثَنَا عَبْدُ الْمَلِكِ بْنُ أَبِي سُلَيْمَانَ، عَنْ عَطَاءٍ، عَنْ جَابِرِ بْنِ عَبْدِ اللَّهِ، قَالَ شَهِدْتُ مَعَ رَسُولِ اللَّهِ صلى الله عليه وسلم صَلاَةَ الْخَوْفِ فَصَفَّنَا صَفَّيْنِ صَفٌّ خَلْفَ رَسُولِ اللَّهِ صلى الله عليه وسلم وَالْعَدُوُّ بَيْنَنَا وَبَيْنَ الْقِبْلَةِ فَكَبَّرَ النَّبِيُّ صلى الله عليه وسلم وَكَبَّرْنَا جَمِيعًا ثُمَّ رَكَعَ وَرَكَعْنَا جَمِيعًا ثُمَّ رَفَعَ رَأْسَهُ مِنَ الرُّكُوعِ وَرَفَعْنَا جَمِيعًا ثُمَّ انْحَدَرَ بِالسُّجُودِ وَالصَّفُّ الَّذِي يَلِيهِ وَقَامَ الصَّفُّ الْمُؤَخَّرُ فِي نَحْرِ الْعَدُوِّ فَلَمَّا قَضَى النَّبِيُّ صلى الله عليه وسلم السُّجُودَ وَقَامَ الصَّفُّ الَّذِي يَلِيهِ انْحَدَرَ الصَّفُّ الْمُؤَخَّرُ بِالسُّجُودِ وَقَامُوا ثُمَّ تَقَدَّمَ الصَّفُّ الْمُؤَخَّرُ وَتَأَخَّرَ الصَّفُّ الْمُقَدَّمُ ثُمَّ رَكَعَ النَّبِيُّ صلى الله عليه وسلم وَرَكَعْنَا جَمِيعًا ثُمَّ رَفَعَ رَأْسَهُ مِنَ الرُّكُوعِ وَرَفَعْنَا جَمِيعًا ثُمَّ انْحَدَرَ بِالسُّجُودِ وَالصَّفُّ الَّذِي يَلِيهِ الَّذِي كَانَ مُؤَخَّرًا فِي الرَّكْعَةِ الأُولَى وَقَامَ الصَّفُّ الْمُؤَخَّرُ فِي نُحُورِ الْعَدُوِّ فَلَمَّا قَضَى النَّبِيُّ صلى الله عليه وسلم السُّجُودَ وَالصَّفُّ الَّذِي يَلِيهِ انْحَدَرَ الصَّفُّ الْمُؤَخَّرُ بِالسُّجُودِ فَسَجَدُوا ثُمَّ سَلَّمَ النَّبِيُّ صلى الله عليه وسلم وَسَلَّمْنَا جَمِيعًا ‏.‏ قَالَ جَابِرٌ كَمَا يَصْنَعُ حَرَسُكُمْ هَؤُلاَءِ بِأُمَرَائِهِمْ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1945</td></tr><tr><td>Arabic No</td><td>840.01</td></tr><tr><td>Reference</td><td>Book 6 Hadith 373</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
হাদিস একাডেমি নাম্বারঃ ১৮৩০, আন্তর্জাতিক নাম্বারঃ ৮৪০ ১৮৩০-(৩০৭/৮৪০) মুহাম্মাদ ইবনু আবদুল্লাহ ইবনু নুমায়র (রহঃ) ..... জাবির ইবনু আবদুল্লাহ (রাযিঃ) থেকে বর্ণিত। তিনি বলেন, আমি রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর সাথে সালাতুল খাওফ আদায় করেছি। তিনি আমাদেরকে দু' দলে বিভক্ত করলেন। একদল ছিল রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর পিছনে আর শত্রুবাহিনী ছিল আমাদের ও কিবলার মাঝখানে। রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম তাকবীরে তাহরীমা বললে আমরাও সকলে তাকবীরে তাহরীমা বললাম। তিনি রুকূ’ করলে আমরা সকলেই রুকূ করলাম অতঃপর তিনি রুকূ’ থেকে মাথা উঠালে আমরা সকলেই মাথা উঠালাম। অতঃপর তিনি সাজদায় গেলেন এবং তার নিকটস্থ কাতারের লোকজনও, আর খানিক দূরের কাতারটি শত্রুবাহিনীর বিরুদ্ধে প্রতিরক্ষায় দাঁড়িয়ে থাকল। নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম যখন সিজদা সমাপ্ত করলেন এবং তার নিকটস্থ কাতারও দাঁড়িয়ে গেল, তখন খানিক দূরের কাতারটি সাজাদায় গেল। আর এরা দাঁড়িয়ে থাকল। অতঃপর পিছনের দলটি সামনে আসল এবং সামনের দলটি পিছনে সরে গেল। অতঃপর নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম রুকূ করলে আমরাও সকলে রুকূ করলাম। অতঃপর তিনি রুকূ’ থেকে মাথা উঠালে আমরাও সকলে মাথা উঠালাম। অতঃপর তিনি সাজদায় গেলেন এবং তার নিকটবর্তী দলটি যারা প্রথম রাকাআতে পিছনে ছিল, তারাও। আর খানিক দূরের দলটি শত্রুবাহিনীর বিরুদ্ধে প্রতিরক্ষায় দাঁড়িয়ে থাকল। নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম তার নিকটবর্তী দলটিসহ সিজদা সমাপ্ত করার পর খানিক দূরের দলটি সাজদায় গেল এবং এভাবে সালাত আদায় করল। অতঃপর নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম সালাম ফিরালে আমরাও সালাম ফিরালাম। জাবির (রাযিঃ) বলেন, যেমন তোমাদের প্রহরীগণ তাদের আমীরগণকে পাহারা দেয়। (ইসলামী ফাউন্ডেশন ১৮১৫, ইসলামীক সেন্টার ১৮২২)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1945</td></tr><tr><td>Arabic No</td><td>840.01</td></tr><tr><td>Reference</td><td>Book 6 Hadith 373</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Jabir b. 'Abdullah reported:I observed prayer in danger with the Messenger of Allah (ﷺ). We drew ourselves up in two rows, one row behind him with the enemy between us and the Qibla. The Apostle of Allah (ﷺ) said: Allah is Most Great, and we all said it. He then bowed and we all bowed. He then raised his head from bowing, we all raised (our heads). He then went down in prostration along with the row close to him, and the rear row faced the enemy; then when the Messenger of Allah (ﷺ) completed the prostration, ; and then stood up, the row near to him also did it; then went down the rear row in prostration; then they stood up; then the rear row went to the front and the front row went to the rear. Then the Messenger of Allah (may peace he upon him) bowed down and we all bowed. He then raised his head from bowing and we also raised (our heads). He and the row close to him which I had been in the rear then went down in prostration In the first rak'ah, whereas the rear row faced the enemy. And when the Messenger of Allah (ﷺ) and the rear row close to him had finished the prostration, the rear row went down and prostrated themselves; then the Messenger of Allah pronounced the salutation and we also pronounced the salutation. (Jabir said we hadith) as your guards behave with their chiefs
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1945</td></tr><tr><td>Arabic No</td><td>840.01</td></tr><tr><td>Reference</td><td>Book 6 Hadith 373</td></tr></tbody></table></div>

## French


<div dir="ltr" lang="fr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Jâbir Ibn Abdoullah (رضي الله عنهما) a dit : "J'ai assisté à la prière de la crainte présidée par l'Envoyé de Dieu (paix et bénédiction de Dieu sur lui). Il nous mit en deux rangées dont une se trouva juste derrière l'Envoyé de Dieu (paix et bénédiction de Dieu sur lui) alors que l'ennemi s'interposa entre nous et la Qibla. Le Prophète (paix et bénédiction de Dieu sur lui) prononça le takbîr et nous fîmes tous de même, puis il s'inclina et nous fîmes aussi de même, puis il leva sa tête de l'inclination et ainsi le fîmes-nous. Ensuite il se prosterna ainsi que ceux qui formaient la première rangée, quant à ceux de la seconde rangée, ils restèrent debout en faisant face à l'ennemi. Quand le Prophète (paix et bénédiction de Dieu sur lui) termina sa prosternation et que les hommes de la première rangée se levèrent, ceux de la deuxième rangée s'avancèrent, se prosternèrent et se levèrent. Ensuite les hommes de la deuxième rangée s'avancèrent et ceux de la première se retirèrent. Puis, le Prophète (paix et bénédiction de Dieu sur lui) s'inclina et nous fîmes tous de même. Il releva la tête de l'inclination et nous le fîmes aussi. Il se prosterna ainsi que les hommes de la deuxième rangée qui étaient en arrière pendant la première rak'a, tandis que les hommes de l'autre rangée firent face à l'ennemi. Lorsque le Prophète (paix et bénédiction de Dieu sur lui) acheva sa prosternation ainsi que la rangée qui se trouvait juste derrière lui, ceux de l'autre rangée se prosternèrent. A la fin, le Prophète (paix et bénédiction de Dieu sur lui) fit la salutation finale (le taslîm) et nous fîmes de même". Jâbir a ajouté : "C'était à la façon dont vos gardiens-là surveillent leurs souverains
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1945</td></tr><tr><td>Arabic No</td><td>840.01</td></tr><tr><td>Reference</td><td>Book 6 Hadith 373</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Muhammad bin Abdullah bin Numair] telah menceritakan kepada kami [bapakku] telah menceritakan kepada kami [Abdul Malik bin Abu Sulaiman] dari [Atha'] dari [Jabir bin Abdullah] ia berkata; "Aku pernah ikut menunaikan shalat Khauf bersama Rasulullah shallallahu 'alaihi wasallam. Kami berbaris dua shaf di belakang Rasulullah shallallahu 'alaihi wasallam, sedangkan musuh berada tepat antara kami dan kiblat (di hadapan kami). Mula-mula Nabi shallallahu 'alaihi wasallam bertakbir, lalu kami semua ikut bertakbir. Kemudian beliau ruku' dan kami pun ikut ruku' semua. Kemudian beliau I'tidal (bangkit) dari ruku', maka kami bangkit pula semuanya. Sesudah itu, beliau turun untuk sujud bersama-sama dengan shaf yang pertama, sedangkan shaf kedua tetap berdiri untuk berjaga-jaga. Ketika Nabi shallallahu 'alaihi wasallam bersama shaf pertama telah selesai sujud dan telah berdiri, barulah shaf kedua turun untuk sujud, dan mereka terus bangun kembali. Sesudah itu, shaf kedua maju ke depan, sedangkan shaf pertama mundur. Kemudian Nabi shallallahu 'alaihi wasallam ruku' dan kami ruku' pula semuanya. Kemudian beliau bangkit dari ruku', lalu kami bangkit pula semuanya. Kemudian beliau turun untuk sujud diikuti oleh shaf yang berada di belakang beliau. Sedangkan shaf yang setelahnya (tadinya shaf pertama) tetap berdiri untuk berjaga-jaga ke arah musuh. Ketika Nabi shallallahu 'alaihi wasallam dan shaf yang berada di belakangnya telah selesai sujud, barulah shaf yang kedua turun untuk sujud. Kemudian Nabi shallallahu 'alaihi wasallam mengucapkan salam, dan kami pun mengucapkan salam semuanya." Jabir berkata; Sebagaimana yang dilakukan oleh para penjaga kalian bersama para pemimpinnya
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1945</td></tr><tr><td>Arabic No</td><td>840.01</td></tr><tr><td>Reference</td><td>Book 6 Hadith 373</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ஜாபிர் பின் அப்தில்லாஹ் (ரலி) அவர்கள் கூறியதாவது: அல்லாஹ்வின் தூதர் (ஸல்) அவர்களுடன் அச்ச நேரத் தொழுகையில் நான் பங்கேற்றுள்ளேன். அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் எங்களைத் தமக்குப் பின்னால் இரு வரிசைகளில் நிறுத்தினார்கள். அப்போது எதிரிகள் எங்களுக்கும் தொழும் திசை(யான கிப்லாவு)க்குமிடையே இருந்தார்கள். நபி (ஸல்) அவர்கள் தக்பீர் கூறி (தொழுகையைத் துவக்கி)னார்கள். (இரு வரிசைகளில் நின்றிருந்த) நாங்கள் அனைவரும் தக்பீர் கூறினோம். பின்னர் ருகூஉச் செய்தார்கள். நாங்கள் அனைவரும் ருகூஉச் செய்தோம். பின்னர் ருகூஉவிலிருந்து தலையை உயர்த்தினார்கள். நாங்கள் அனைவரும் (தலையை) உயர்த்தினோம். பிறகு நபி (ஸல்) அவர்களும் அவர்களுக்கு அருகில் (முதல் வரிசையில்) நின்றவர்களும் குனிந்து சஜ்தாச் செய்தனர். அப்போது இரண்டாவது வரிசையிலிருந்தவர்கள் (அப்படியே) எதிரிகளுக்கு நேராக (அவர்களைக் கண்காணித்தவாறு) நின்றுகொண்டேயிருந்தனர். நபி (ஸல்) அவர்கள் சஜ்தாவை நிறைவேற்றி, முதல் வரிசையிலிருந்தவர்கள் (சஜ்தாச் செய்து) எழுந்து நின்றதும் இரண்டாவது வரிசையிலிருந்தவர்கள் குனிந்து சஜ்தாச் செய்தனர். பிறகு எழுந்தனர். பிறகு இரண்டாவது வரிசையிலிருந்தவர்கள் முன்னே (முதல் வரிசைக்கு) வந்தனர். முன் வரிசையிலிருந்தவர்கள் பின்னால் (இரண்டாம் வரிசைக்கு) வந்துவிட்டனர். பிறகு நபி (ஸல்) அவர்கள் ருகூஉச் செய்தபோது (இரு வரிசைகளில் நின்றிருந்த) நாங்கள் அனைவரும் ருகூஉச் செய்தோம். பிறகு நபி (ஸல்) அவர்கள் ருகூஉவிலிருந்து தலையை உயர்த்தியபோது (இரு வரிசைகளிலிருந்த) நாங்கள் அனைவரும் தலையை உயர்த்தினோம். பிறகு நபி (ஸல்) அவர்கள் குனிந்து சஜ்தாச் செய்தார்கள். முதல் ரக்அத் நடைபெற்றபோது பின் வரிசையிலிருந்தவர்களும் இப்போது நபியவர்களுக்கு அருகில் இருப்பவர்களுமான (முதல்) அணியினர் சஜ்தாச் செய்தார்கள். பின்வரிசையிலிருந்தவர்கள் (சஜ்தாச் செய்யாமல்) எதிரிகளுக்கு நேராக (அவர்களைக் கண்காணித்தவாறு) நின்று கொண்டனர். நபி (ஸல்) அவர்களும் முதல் வரிசையிலிருந்தவர்களும் சஜ்தாச் செய்து முடித்ததும் பின்வரிசையில் நின்றுகொண்டி ருந்தவர்களும் குனிந்து சஜ்தாச் செய்தனர். நபி (ஸல்) அவர்கள் சலாம் கொடுத்தபோது நாங்கள் அனைவரும் சலாம் கொடுத்தோம். (இன்றைக்கு எவ்வாறு) உங்கள் படைவீரர்கள் தங்கள் தலைவர்களுடன் சேர்ந்து (போர்க் களங்களில்) தொழுகின்றனரோ அதைப் போன்றுதான் (நாங்களும் செய்தோம்). அத்தியாயம் : 6
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1945</td></tr><tr><td>Arabic No</td><td>840.01</td></tr><tr><td>Reference</td><td>Book 6 Hadith 373</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Bize Muhammed b. Abdillâh b. Numeyr rivayet etti. (Dediki): Bize babam rivayet etti. (Dediki): Bize Abdülmelik b. Ebî Süleyman, Atâ'dan, o da Câbir b. Abdillâh'dan naklen rivayet etti. Câbir şöyle demiş: ResûlulIah (Sallallahu Aleyhi ve Sellem) ile birlikde korku na­mazında bulundum. Bizi iki saff yaptı. Bir saff ResûlulIah (Sallallahu Aleyhi ve Sellem)'in arkasına durdu. Düşman bizimle kıble arasında idi. Peygamber (Sallallahu Aleyhi ve Sellem) tekbîr aldı. Biz de toptan tekbîr aldık. Sonra rükû' etti; biz de toptan rükû' ettik. Sonra başını rükû'dan kaldırdı; biz de toptan başlarımızı kaldırdık. Sonra kendisi ve arkasındaki ilk rek'âtda geride kalan saff secdeye kapandılar. Geriye bırakılan saff düşmanın karşısında durdu. Nebi (Sallallahu Aleyhi ve Sellem) secdeyi eda edip, arkasındaki saff ayağa kalkınca gerideki saff secdeye kapandı; ve kalktılar. Sonra geriki saff ilerledi; ileriki saff geriye çekildi. Sonra Peygamber (Sallallahu Aleyhi ve Sellem) rükû'a vardı. Biz de hep birden rükû' ettik. Sonra başını rükû'dan kaldırdı; biz de toptan başlarımızı kaldırdık. Sonra ilk rek'âtda geride kalan, bu sefer Resûlullah (Sallallahu Aleyhi ve Sellem)'in hemen arkasında bulunan saff ile bîrlikde secdeye kapandı. Geriki saff düşmanın karşısına dikildi. Nebi (Sallallahu Aleyhi ve Sellem) arkasındaki saffla birlikde secdeyi edâ edince geriki saff secdeye kapanarak secde ettiler. Sonra Nebi (Sallallahu Aleyhi ve Sellem) selâm verdi; biz de hep birden selâm verdik.» Cabir: «Şu sizin muhafızlarınızın kumandanlarına yaptığı gibi...» demiş
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1945</td></tr><tr><td>Arabic No</td><td>840.01</td></tr><tr><td>Reference</td><td>Book 6 Hadith 373</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
عطاء نے حضرت جابر بن عبداللہ انصاری رضی اللہ تعالیٰ عنہ سے روایت کی ، انھوں نے کہا : میں رسول اللہ صلی اللہ علیہ وسلم کے ساتھ نماز خوف میں شریک ہوا ، آپ صلی اللہ علیہ وسلم نے ہماری دو صفیں بنائیں ، ایک صف رسول اللہ صلی اللہ علیہ وسلم کے پیچھے تھی ( اوردوسری ان کے پیچھے ) اور دشمن ہمارے اور قبلے کے درمیان تھا ، نبی اکرم صلی اللہ علیہ وسلم نے تکبیر ( تحریمہ ) کہی اور ہم سب نے بھی تکبیر کہی ، پھر آپ صلی اللہ علیہ وسلم نے رکوع کیا اور ہم سب نے رکوع کیا ، پھر آپ صلی اللہ علیہ وسلم نے رکوع سے اپنا سر اٹھایا اور ہم سب نے سراٹھایا ، پھر آپ صلی اللہ علیہ وسلم سجدے کے لئے جھک گئے اور آپ صلی اللہ علیہ وسلم سے متصل صف نے بھی سجدہ کیا اور پچھلی صف دشمن کے مد مقابل کھڑی رہی ، جب آپ صلی اللہ علیہ وسلم نے دو سجدے کے کرلیے ۔ اور آپ صلی اللہ علیہ وسلم سے متصل صف ( سجدے کرکے آپ صلی اللہ علیہ وسلم کے ساتھ ) کھڑی ہوگئی تو پچھلی صف سجدے کے لئے نیچے ہوئی اور پھر کھڑی ہوگئی ، اس کے بعد پچھلی صف آگے آگئی اور اگلی صف پیچھے چلی گئی ، پھر جب آپ صلی اللہ علیہ وسلم نے رکوع کیا تو ہم سب نے رکوع کیا ۔ پھر آپ نے رکوع سے اپنا سر اٹھایا اور ہم سب نے بھی سراٹھایا ، پھر آپ صلی اللہ علیہ وسلم اور آپ صلی اللہ علیہ وسلم سے متصل صف جو پہلی رکعت میں پیچھے تھی ، سجدے کے لئے نیچے چلی گئی اور پچھلی صف دشمن کے مقابلے میں کھڑی رہی ، جب نبی اکرم صلی اللہ علیہ وسلم اور آپ صلی اللہ علیہ وسلم سے متصل صف نے سجدہ کرلیا تو پچھلی صف سجدے کے لئے جھکی ۔ انھوں نے سجدے کیے ۔ پھر نبی اکرم صلی اللہ علیہ وسلم نے سلام پھیرا اور ہم سب نے بھی سلام پھیردیا ۔ حضرت جابر رضی اللہ تعالیٰ عنہ نے بتایا : جس طرح تمہارےمحافظ ( آجکل ) اپنے امیروں کی حفاظت کے لئے کرتے ہیں ۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1945</td></tr><tr><td>Arabic No</td><td>840.01</td></tr><tr><td>Reference</td><td>Book 6 Hadith 373</td></tr></tbody></table></div>