## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنِي أَبُو الطَّاهِرِ، وَحَرْمَلَةُ بْنُ يَحْيَى، قَالاَ أَخْبَرَنَا ابْنُ وَهْبٍ، أَخْبَرَنِي يُونُسُ بْنُ يَزِيدَ، عَنِ ابْنِ شِهَابٍ، قَالَ أَخْبَرَنِي سَعِيدُ بْنُ الْمُسَيَّبِ، وَأَبُو سَلَمَةَ بْنُ عَبْدِ الرَّحْمَنِ بْنِ عَوْفٍ أَنَّهُمَا سَمِعَا أَبَا هُرَيْرَةَ، يَقُولُ كَانَ رَسُولُ اللَّهِ صلى الله عليه وسلم يَقُولُ حِينَ يَفْرُغُ مِنْ صَلاَةِ الْفَجْرِ مِنَ الْقِرَاءَةِ وَيُكَبِّرُ وَيَرْفَعُ رَأْسَهُ ‏"‏ سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ رَبَّنَا وَلَكَ الْحَمْدُ ‏"‏ ‏.‏ ثُمَّ يَقُولُ وَهُوَ قَائِمٌ ‏"‏ اللَّهُمَّ أَنْجِ الْوَلِيدَ بْنَ الْوَلِيدِ وَسَلَمَةَ بْنَ هِشَامٍ وَعَيَّاشَ بْنَ أَبِي رَبِيعَةَ وَالْمُسْتَضْعَفِينَ مِنَ الْمُؤْمِنِينَ اللَّهُمَّ اشْدُدْ وَطْأَتَكَ عَلَى مُضَرَ وَاجْعَلْهَا عَلَيْهِمْ كَسِنِي يُوسُفَ اللَّهُمَّ الْعَنْ لِحْيَانَ وَرِعْلاً وَذَكْوَانَ وَعُصَيَّةَ عَصَتِ اللَّهَ وَرَسُولَهُ ‏"‏ ‏.‏ ثُمَّ بَلَغَنَا أَنَّهُ تَرَكَ ذَلِكَ لَمَّا أُنْزِلَ ‏(‏ لَيْسَ لَكَ مِنَ الأَمْرِ شَىْءٌ أَوْ يَتُوبَ عَلَيْهِمْ أَوْ يُعَذِّبَهُمْ فَإِنَّهُمْ ظَالِمُونَ‏)‏ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1540</td></tr><tr><td>Arabic No</td><td>675.01</td></tr><tr><td>Reference</td><td>Book 5 Hadith 373</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
হাদিস একাডেমি নাম্বারঃ ১৪২৬, আন্তর্জাতিক নাম্বারঃ ৬৭৫ ১৪২৬-(২৯৪/৬৭৫) আবূত তহির ও হারমালাহ ইবনু ইয়াহইয়া (রহঃ) ..... আবূ হুরায়রাহ (রাযিঃ) থেকে বর্ণিত। রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম ফজরের সালাতে কিরআত শেষ তাকবীর দিয়ে রুকূ’তে গিয়ে রুকূ’ থেকে যখন মাথা উঠাতেন তখন বলতেনঃ "সামি'আল্ল-হু লিমান হামিদাহ, রব্বনা- ওয়ালাকাল হামদ” – (অর্থাৎ- যে আল্লাহর প্রশংসা করে আল্লাহ তার প্রশংসা শুনেন। হে আমাদের প্রভু! সকল প্রশংসা তোমারই জন্য নির্দিষ্ট)। এরপর তিনি দাঁড়িয়ে বলতেনঃ হে আল্লাহ! ওয়ালীদ ইবনু ওয়ালীদ, সালামাহ ইবনু হিশাম ও আইয়্যাশ ইবনু রবী’আহ এবং দুর্বল ও নিপীড়িত মু'মিনদের নাযাত দান করো। হে আল্লাহ! তুমি মুযার গোত্রকে কঠোর হস্তে পাকড়াও করো। আর ইউসুফ (আঃ)-এর সময়ের দুর্ভিক্ষের মতো দুর্ভিক্ষ দিয়ে তাদের শায়েস্তা করো। হে আল্লাহ! তুমি লিহইয়ান, রি'লান, যাকওয়ান ও উসাইয়্যাহ গোত্রের ওপর অভিসম্পাত বর্ষণ করো। কেননা তারা আল্লাহ এবং তার রসূলের অবাধ্য হয়েছে। অতঃপর আমরা জানতে পারলাম যে, আয়াত- "হে নবী! এর ব্যাপারে তোমার কোন করণীয় নেই। আল্লাহ তাদের তওবা কবুল করুন আর তাদেরকে শাস্তি দান করুন এ ব্যাপারে তিনি পূর্ণ ইখতিয়ারের অধিকারী। কেননা তারা তো যালিম" (সূরাহ আ-লি ইমরান ৩ঃ ১২৮)। অবতীর্ণ হওয়ার পর নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এভাবে কুনুত পড়া ছেড়ে দিয়েছিলেন। (ইসলামী ফাউন্ডেশন ১৪১১, ইসলামীক সেন্টার ১৪২২)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1540</td></tr><tr><td>Arabic No</td><td>675.01</td></tr><tr><td>Reference</td><td>Book 5 Hadith 373</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Abu Salama b. Abd al-Rahman b. 'Auf heard Abu Huraira say:(When) Allah's Messenger (ﷺ) (wished to invoke curse or blessing on someone, he would do so at the end) of the recitation in the dawn prayer, when he had pronounced Allah-o-Akbar (for bending) and then lifted his head (saying):" Allah listened to him who praised Him; our Lord! to Thee is all praise" ; he would then stand up and say:" Rescue al-Walid b. Walid, Salama b. Hisham, and 'Ayyash b. Abd Rabi'a, and the helpless among the Muslims. O Allah! trample severely Mudar and cause them a famine (which broke out at the time) of Joseph. O Allah! curse Lihyan, Ri'l, Dhakwan, 'Usayya, for they disobeyed Allah and His Messenger." (The narrator then adds): The news reached us that he abandoned (this) when this verse was revealed:" Thou but no concern in the matter whether He turns to them (mercifully) or chastises them; surely they are wrongdoers" (ill. 127)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1540</td></tr><tr><td>Arabic No</td><td>675.01</td></tr><tr><td>Reference</td><td>Book 5 Hadith 373</td></tr></tbody></table></div>

## French


<div dir="ltr" lang="fr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Abou Hourayra (que Dieu l'agrée) a dit : Lors de la prière de fajr (de l'aurore), l'Envoyé de Dieu (paix et bénédiction de Dieu sur lui) avait l'habitude de dire, après la récitation du Coran et la prononciation du takbîr et en relevant sa tête de l'inclination : "Dieu écoute celui qui Le loue. Seigneur! à Toi la louange". Puis, étant toujours debout, il disait : "Seigneur! Délivre Al-Walîd Ibn Al-Walîd, Salama Ibn Hichâm, 'Ayyâch Ibn 'Abî Rabî'a et tous les faibles d'entre les Croyants (ceux-ci étaient emprisonnés chez les polythéistes). Seigneur! Accable de Ta colère la tribu de Mudar (hostile aux musulmans) et fais que ses années soient comme celles de Yûsuf (Joseph) (années de détresse). Seigneur! Maudit Lihyân, Ri'l, Dhakwân et 'Usayya qui s'étaient montrés rebelles à Dieu et à Son Messager". - Plus tard, ajoute le transmetteur, nous sûmes que le Prophète abandonna cette habitude à la révélation de ce verset : Tu n'as (Muhammad) aucune part dans l'ordre (divin) - qu'Il (Dieu) accepte leur repentir (en embrassant l'Islam) ou qu'Il les châtie, car ils sont bien des injustes
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1540</td></tr><tr><td>Arabic No</td><td>675.01</td></tr><tr><td>Reference</td><td>Book 5 Hadith 373</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepadaku [Abu At Thahir] dan [Harmalah bin Yahya], keduanya berkata; telah mengabarkan kepada kami [Ibnu Wahb] telah mengabarkan kepadaku [Yunus bin Yazid] dari [Ibnu Syihab] katanya; telah mengabarkan kepadaku [Said bin Musayyab] dan [Abu Salamah bin Abdurrahman bin 'Auf], keduanya mendengar [Abu Hurairah] berkata; "Ketika Rasulullah shallallahu 'alaihi wasallam shalat fajar (subuh), yaitu setelah membaca, bertakbir dan mengangkat kepalanya, beliau membaca "Sami'allahu liman hamidah. Rabbanaa walakal hamdu." Kemudian beliau membaca lagi dan beliau masih berdiri, yaitu; ALLAAHUMMA ANJI ALWALID BIN WALID WA SALAMAH BIN HISYAM, WA AYYASY BIN ABU RABIAH, WAL MUSTADH'AFIINA MINAL MUL'MINIINA, ALLAAHUMMASY DUD WATH'ATHAKA 'ALAA MUDHARR WAJ'ALHAA 'ALIHIM KASINII YUUSUFA, ALLAAHUMMAL'AN LIHYAANA WARI'LAN WADZAKWAAANA WA'USHAYYAH ASHATALLAAHA WARASUULAHU (Ya Allah, selamatkanlah Walid bin walid, Salamah bin Hisyam, Ayyasy bin Abu Rabiah dan orang-orang mukmin yang lemah, Ya Allah, perkuatlah hukumanmu kepada Mudharr dan jadikanlah untuk mereka masa-masa paceklik sebagaimana paceklik Yusuf, Ya Allah, laknatilah Lihyan, Ri'l, dan Dzakwan, mereka yang telah membangkang Allah dan Rasul-Nya." Kemudian sampai berita kepada kami, bahwa beliau meninggakan doa (qunut) tersebut, tepatnya ketika turun ayat "Tidak ada urusanmu entah Allah mengampuni mereka atau menyiksa mereka, sesungguhnya mereka orang-orang yang zhalim (QS. Ali Imran 128), Telah menceritakan kepada kami [Abu Bakr bin Abu Syaibah] dan ['Amru An Naqid], keduanya berkata; telah menceritakan kepada kami [Ibn 'Uyainah] dari [Az Zuhri] dari [Sa'id bin Musayyab] dari [Abu Hurairah] dari Nabi shallallahu 'alaihi wasallam hingga sabdanya: "Ya Allah, jadikanlah untuk mereka tahun-tahun paceklik sebagaimana tahun-tahun paceklik Yusuf." Dan ia tidak menyebutkan kalimat sesudahnya
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1540</td></tr><tr><td>Arabic No</td><td>675.01</td></tr><tr><td>Reference</td><td>Book 5 Hadith 373</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
அபூஹுரைரா (ரலி) அவர்கள் கூறியதாவது: அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் ஃபஜ்ர் தொழுகையில் (குர்ஆன்) ஓதிய பின் தக்பீர் சொல்(லி ருகூஉ செய்)வார்கள். பிறகு ருகூஉவிலிருந்து தலையை உயர்த்தும்போது "சமிஅல்லாஹு லிமன் ஹமிதஹ்" (அல்லாஹ் தன்னைப் புகழ்வோரின் புகழுரையை ஏற்றுக்கொள்கிறான்) "ரப்பனா வ லக்கல் ஹம்து" (எங்கள் இறைவா! உனக்கே புகழ் அனைத்தும்) என்று கூறுவார்கள். பிறகு நின்றவாறு (பின்வரும் "குனூத்"தை) ஓதுவார்கள்: இறைவா! வலீத் பின் அல்வலீத், சலமா பின் ஹிஷாம், அய்யாஷ் பின் அபீரபீஆ ஆகியோரையும் (மக்காவிலுள்ள) ஒடுக்கப்பட்ட இறைநம்பிக்கையாளர்களையும் நீ காப்பாற்றுவாயாக! இறைவா, (கடும் பகை கொண்ட) முளர் குலத்தார்மீது உனது பிடியை இறுக்குவாயாக! இறைவா! (உன் தூதர்) யூசுஃபின் காலத்தில் ஏற்பட்ட பஞ்சம் நிறைந்த ஆண்டுகளைப் போன்று இவர்களுக்கும் ஏற்படுத்துவாயாக! இறைவா! லிஹ்யான், ரிஅல், தக்வான், உஸய்யா ஆகிய குலத்தாரை நீ உன் அருளிலிருந்து அப்புறப்படுத்துவாயாக! உஸய்யா குலத்தார் (பெயருக்கேற்ப) அல்லாஹ்வுக்கும் அவனுடைய தூதருக்கும் மாறு செய்துவிட்டனர். பிறகு "அவர்களை அல்லாஹ் மன்னிக்கும் வரை, அல்லது அவர்கள் அக்கிரமக்காரர்களாக இருப்பதால் அவர்களை அவன் வேதனை செய்யும்வரை (அவர்களுக்குத் தண்டனை வழங்குமாறு கூற நபியே!) உங்களுக்கு எந்த உரிமையும் இல்லை" எனும் (3:128ஆவது) இறைவசனம் அருளப்பெற்ற போது அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் இவ்வாறு பிரார்த்திப்பதை விட்டுவிட்டார்கள் என நமக்குச் செய்தி எட்டியது. இந்த ஹதீஸ் இரு அறிவிப்பாளர்தொடர்களில் வந்துள்ளது. - மேற்கண்ட ஹதீஸ் மேலும் இரு அறிவிப்பாளர்தொடர்கள் வழியாகவும் வந்துள்ளது. அவற்றில் "(நபி) யூசுஃபின் காலத்தில் ஏற்பட்ட பஞ்சம் நிறைந்த ஆண்டுகளைப் போன்று இவர்களுக்கும் பஞ்ச ஆண்டுகளை ஏற்படுத்துவாயாக!" என்பதுவரை இடம்பெற்றுள்ளது. அதற்குப் பின்னுள்ள குறிப்புகள் இடம்பெறவில்லை. அத்தியாயம் : 5
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1540</td></tr><tr><td>Arabic No</td><td>675.01</td></tr><tr><td>Reference</td><td>Book 5 Hadith 373</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Bana Ebu't-Tâhir iîe Harmeletü'bnü Yahya rivayet ettiler. Dedilerki: Bize İbni Vehb haber verdi. (Dediki): Bana Yûnus, İbni Yezîd'den, o da İbni Şihâb'dan naklen haber verdi. Demişkî: Bana Saîd b. El-Müseyyeb ile Ebu Selemete'bnü Abdirrahmân b. Avf haber verdiler ki onlar da Ebu Hureyre'yi şöyle derken işitmişler: Resûlullah (Saliallahu Aleylıi ve Sellem) sabah namazının kıraatini bitirip; tekbîr aldığı ve başını kaldırdığı zaman: «Semiallahu limen hamideh. Rabbena ve leke'l-hamd.» (Allah, kendisine hamd edenin hamdını kabul eder. Ey Rabbımiz! Hamd de sana mahsûsdur.) der: sonra ayakta iken şunları okurdu: «Allah'ım! Velid b. Velid'i, Selemetü'bnü Hişâm'ı, Ayyaş, b. Ebî Rabia'yı ve mu'minlerin zayıf olanlarını kurtar! Yâ Rabbî, Mudar kabilesine olan şiddet ve baskını arttır! Bunu onlara Yûsuf'un kıtlık yılları gibi yap! Allah'ım, Lihyân, Ri'l ve Zekvân ile Allâh ve Resulüne isyan eden Usayye kabilelerine lanet eyle!» Sonra (sana bu işde hiç bir vazife düşmez. Yâ Allah Teâlâ onların tevbesini kabul edecek yahut kendilerini azâb eyleyecekdir. Çünkü hakkı ile zâlimler ancak onlardır.) [ A'li İmran 128 ] âyet-i kerimesi indirilince bu kunut'dan vazgeçtiğini duyduk
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1540</td></tr><tr><td>Arabic No</td><td>675.01</td></tr><tr><td>Reference</td><td>Book 5 Hadith 373</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
یونس بن یزید نے ابن شہاب سے روایت کرتے ہوئے خبر دی ، کہا : مجھے سعید بن مسیب اور ابو سلمہ بن عبدالرحمان بن عوف نے بتایا کہ ان دونوں نے حضرت ابوہریرہ رضی اللہ عنہ کو یہ کہتے ہوئے سنا کہ رسول اللہ ﷺ جب نماز فجر کی قراءت سے فارغ ہوتے اور ( رکوع میں جانے کے لیے ) تکبیر کہتے تو سر اٹھانے کے بعد سمع اللہ لمن حمدہ ربنا ولک الحمد ( اللہ نے سن لیا جس نے اس کی حمد کی ، اے ہمارے رب! اور ٰحمدتیرے ہی لیے ہے ) کہتے ، پھر حالت قیام ہی میں آپ فرماتے : ‘ ‘ اے اللہ!ولید بن ولید ، سلمہ بن ہشام ، عیاش بن ابی ربیعہ اور مومنوں میں سے ان لوگوں کو جنھیں ( کافروں نے ) کمزور پایا ، نجات عطا فرما ۔ اے اللہ!قبیلہ مضر پر اپنے روندنے کو سخت کر ، ان پر اپنے اس مؤاخذے کو یوسف علیہ السلام کے زمانے کے قحط کی طرح کر د ۔ اے اللہ! الحیان ، رعل ، ذکوان اور عصیہ پر ، جنھوں نے اللہ اور اس کے رسول کی نافرمانی کی ، لعنت نازل کر ۔ ’’پھر ہم تک یہ بات پہنچی کہ اس کے بعد جب آپ پر یہ آیت اتری : ‘ ‘ آپ کا اس معاملے سے کوئی سروکار نہیں ، ( اللہ تعالیٰ ) چاہے ان کو توبہ کا موقع عطا کرے ، چاہے ان کو عذاب دے کہ و ہ یقینا ظلم کرنے والے ہیں’’ تو آپ نے یہ دعا چھوڑ دی ۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1540</td></tr><tr><td>Arabic No</td><td>675.01</td></tr><tr><td>Reference</td><td>Book 5 Hadith 373</td></tr></tbody></table></div>