## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنِي مُحَمَّدُ بْنُ عَبَّادٍ، حَدَّثَنَا سُفْيَانُ، عَنْ عَمْرٍو، عَنْ جَابِرٍ، قَالَ كَانَ مُعَاذٌ يُصَلِّي مَعَ النَّبِيِّ صلى الله عليه وسلم ثُمَّ يَأْتِي فَيَؤُمُّ قَوْمَهُ فَصَلَّى لَيْلَةً مَعَ النَّبِيِّ صلى الله عليه وسلم الْعِشَاءَ ثُمَّ أَتَى قَوْمَهُ فَأَمَّهُمْ فَافْتَتَحَ بِسُورَةِ الْبَقَرَةِ فَانْحَرَفَ رَجُلٌ فَسَلَّمَ ثُمَّ صَلَّى وَحْدَهُ وَانْصَرَفَ فَقَالُوا لَهُ أَنَافَقْتَ يَا فُلاَنُ قَالَ لاَ وَاللَّهِ وَلآتِيَنَّ رَسُولَ اللَّهِ صلى الله عليه وسلم فَلأُخْبِرَنَّهُ ‏.‏ فَأَتَى رَسُولَ اللَّهِ صلى الله عليه وسلم فَقَالَ يَا رَسُولَ اللَّهِ إِنَّا أَصْحَابُ نَوَاضِحَ نَعْمَلُ بِالنَّهَارِ وَإِنَّ مُعَاذًا صَلَّى مَعَكَ الْعِشَاءَ ثُمَّ أَتَى فَافْتَتَحَ بِسُورَةِ الْبَقَرَةِ ‏.‏ فَأَقْبَلَ رَسُولُ اللَّهِ صلى الله عليه وسلم عَلَى مُعَاذٍ فَقَالَ ‏"‏ يَا مُعَاذُ أَفَتَّانٌ أَنْتَ اقْرَأْ بِكَذَا وَاقْرَأْ بِكَذَا ‏"‏ ‏.‏ قَالَ سُفْيَانُ فَقُلْتُ لِعَمْرٍو إِنَّ أَبَا الزُّبَيْرِ حَدَّثَنَا عَنْ جَابِرٍ أَنَّهُ قَالَ ‏"‏ اقْرَأْ وَالشَّمْسِ وَضُحَاهَا ‏.‏ وَالضُّحَى ‏.‏ وَاللَّيْلِ إِذَا يَغْشَى ‏.‏ وَسَبِّحِ اسْمَ رَبِّكَ الأَعْلَى ‏"‏ ‏.‏ فَقَالَ عَمْرٌو نَحْوَ هَذَا ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1040</td></tr><tr><td>Arabic No</td><td>465.01</td></tr><tr><td>Reference</td><td>Book 4 Hadith 202</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
হাদিস একাডেমি নাম্বারঃ ৯২৭, আন্তর্জাতিক নাম্বারঃ ৪৬৫ ৯২৭-(১৭৮/৪৬৫) মুহাম্মাদ ইবনু আব্বাদ (রহঃ) ..... জাবির (রাযিঃ) হতে বর্ণিত। তিনি বলেন, মুআয (রাযিঃ) নবী সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম এর সাথে সালাত আদায় করতেন, অতঃপর নিজের সম্প্রদায়ে ফিরে এসে তাদের সালাতে ইমামতি করতেন। এক রাতে তিনি নবী সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম এর সাথে ইশার সালাত আদায় করলেন, অতঃপর নিজের সম্প্রদায়ের কাছে ফিরে এসে তাদের সালাতে ইমাম হলেন। তিনি সূরাহ আল বাকারাহ পড়া শুরু করলেন। এক ব্যক্তি এতে বিরক্ত হয়ে পড়ল। সে সালাম ফিরিয়ে একাকি সালাত আদায় করে চলে গেল। লোকেরা তাকে বলল, হে অমুক তুমি কি মুনাফিক হয়ে গেছ? সে বলল, আল্লাহর শপথ আমি মুনাফিক হয়ে যাইনি। আমি অবশ্যই রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম এর কাছে যাব এবং তাকে এ সম্পর্কে অবহিত করব। সে রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম এর নিকট এসে বলল, হে আল্লাহর রাসূল! আমরা উট চালক, দিনের বেলায় কঠোর পরিশ্রম করি। আর মু'আয (রাযিঃ) আপনার সাথে ইশার সালাত আদায় করে ফিরে এসে আমাদের ইমামতি করলেন এবং সালাতে সূরাহ আল বাকারাহ পড়া শুরু করে দিলেন। রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম মুআয এর দৃষ্টি আকর্ষণ করে বললেন, হে মুআয! তমি কি ফিতনা সৃষ্টিকারী? তুমি এ রকম এ রকম সূরাহ পাঠ করবে। সুফইয়ান বলেন, আমি 'আমরকে বললাম, আবূ যুবায়র জাবির এর সূত্রে আমাদের বলেছেন যে, তিনি নবী সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম বলেছেন, তুমি সূরাহ আশ শামস সূরাহ আয যুহা সূরাহ আল লায়ল এবং সূরাহ আল আ'লা পাঠ করবে। আমুর বললেন, হ্যাঁ, এ ধরনের সূরাই পাঠ করার কথা বলেছেন। (ইসলামিক ফাউন্ডেশনঃ ৯২২, ইসলামিক সেন্টারঃ ৯৩৪)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1040</td></tr><tr><td>Arabic No</td><td>465.01</td></tr><tr><td>Reference</td><td>Book 4 Hadith 202</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Jabir reported that Mu'adh b. Jabal used to pray with the Apostle (ﷺ), then came and led his people in prayer. One night he said the night prayer with the Messenger of Allah (ﷺ). He then came to his people and led them in prayer beginning with Surat al-Baqara. A man turned aside, pronounced the taslim (salutation for concluding the prayer), then prayed alone and departed. The people said to him:Have you become a hypocrite, so and so? He said: I swear by Allah that I have not, but I will certainly go to Allah's Messenger (ﷺ) and will inform (him) about this. He then came to the Messenger of Allah (ﷺ) and said: Messenger of Allah, we look after camels used for watering and work by day. Mu'adh said the night prayer with you. He then came and began with Surat al-Baqara. Allah's Messenger (ﷺ) then turned to Mu'adh and said: Are you there to (put the people) to trial? Recite such and recite such (and such a surah). It is transmitted on the authority of Jabir, as told by Sufyan, that he (the Holy Prophet) had said: "By the sun and its morning brightness" (Surah xci), "By brightness" (Surah xciii), "By the night when it spreads" (Surah xcii), and "Glorify the name of thy most high Lord" (Surah lxxxii)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1040</td></tr><tr><td>Arabic No</td><td>465.01</td></tr><tr><td>Reference</td><td>Book 4 Hadith 202</td></tr></tbody></table></div>

## French


<div dir="ltr" lang="fr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
D'après Jâbir Ibn 'Abdillâh (que Dieu l'agrée), Mou'âdh Ibn Jabal faisait la prière avec le Prophète (paix et bénédiction de Dieu sur lui), puis, allait diriger la prière des siens. Or un soir, après avoir fait la prière de 'ichâ' avec le Prophète (paix et bénédiction de Dieu sur lui), il alla trouver les siens et présida la prière en la commençant par la sourate d'Al-Baqara. Un homme quitta aussitôt la prière en commun, fit le taslîm et accomplit la prière en solitaire. L'ayant achevée, on l'accuse d'hypocrisie. Et lui de répondre : "Non, par Dieu! J'irai trouver l'Envoyé de Dieu (paix et bénédiction de Dieu sur lui) pour lui raconter ce qui s'est arrivé". Arrivé chez l'Envoyé de Dieu (paix et bénédiction de Dieu sur lui), il dit : "Ô Envoyé de Dieu, nous gardions des chameaux qui servent à distribuer l'eau, nous travaillions toute la journée; et Mu'âdh a fait la prière de 'ichâ' avec vous; puis en nous présidant dans la prière, il l'a entamée par la récitation de la sourate d'Al-Baqara". L'Envoyé de Dieu (paix et bénédiction de Dieu sur lui) alla trouver Mu'âdh et lui dit : "Ô Mu'âdh, est-ce que tu veux décourager les fidèles de faire la prière? Récite telle et telle sourate! Sufyân transmet avoir dit à 'Amr que, selon Abou Az-Zoubayr, Jâbir dit que le Prophète conseillait de réciter : "Par le soleil et par sa clarté!" (sourate n° 91, Ach-Chams); "Par le jour montant!" (sourate n° 93, Ad-Duhâ); "Par la nuit quand elle enveloppe tout!" (sourate n° 92, Al-Layl); "Glorifie le nom de ton Seigneur le Très-Haut! (sourate n° 87, Al-'A'lâ)"; 'Amr ajoute que c'était presque cela. Obligation faite aux imams d'alléger la prière, tout en la faisant à la perfection
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1040</td></tr><tr><td>Arabic No</td><td>465.01</td></tr><tr><td>Reference</td><td>Book 4 Hadith 202</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepadaku [Muhammad bin 'Abbad] telah menceritakan kepada kami [Sufyan] dari [Amru] dari [Jabir] dia berkata, "Muadz shalat bersama Nabi Shallallahu'alaihiwasallam, kemudian dia datang, lalu mengimami kaumnya. Maka dia melakukan shalat Isya' pada malam tersebut bersama Nabi Shallallahu'alaihiwasallam, kemudian mendatangi kaumnya, lalu mengimami mereka. Lalu dia membuka dengan surat al-Baqarah, maka seorang laki-laki berpaling lalu salam, kemudian shalat sendirian, lalu berpaling pergi. Maka mereka berkata kepadanya, 'Apakah kamu berlaku munafik wahai fulan? ' Dia menjawab, 'Tidak, demi Allah, aku akan mendatangi Rasulullah Shallallahu'alaihiwasallam, lalu aku akan mengabarkan kepada beliau. Lalu dia mendatangi Rasulullah Shallallahu'alaihiwasallam seraya berkata, 'Wahai Rasulullah, sesungguhnya para pekerja penyiram (tanaman) bekerja pada siang hari (sehingga kecapekan), dan sesungguhnya Mu'adz shalat Isya' bersamamu, kemudian dia datang kepada kami lalu shalat dengan membukanya dengan surat al-Baqarah.' Maka Rasulullah Shallallahu'alaihiwasallam menghadap Mu'adz seraya bersabda, 'Wahai Mu'adz, apakah kamu pemfitnah (yang membuat orang lari dari agama), bacalah dengan surat ini dan bacalah dengan ini' -maksudnya surat yang ringkas dan pendek--." Berkata Sufyan, maka saya berkata kepada Amru sesungguhnya [Abu az-Zubair] telah menceritakan kepada kami, dari [Jabir] bahwa dia berkata, "Bacalah 'Iqra dan asy-Syams wa Dhuhaha, serta Wa adh-dhuha wa al-Laili Idza Yaghsya dan Sabbihisma Rabbika al-A'la". Maka Amru berkata semisal ini
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1040</td></tr><tr><td>Arabic No</td><td>465.01</td></tr><tr><td>Reference</td><td>Book 4 Hadith 202</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ஜாபிர் பின் அப்தில்லாஹ் (ரலி) அவர்கள் கூறியதாவது: முஆத் பின் ஜபல் (ரலி) அவர்கள் நபி (ஸல்) அவர்களுடன் தொழுதுவிட்டுப் பிறகு (தம் கூட்டத்தாரிடம்) திரும்பிச் சென்று (நபி (ஸல்) அவர்களுக்குப் பின்னால் தொழுத தொழுகையை மீண்டும்) தம் கூட்டத்தாருக்குத் தொழுவிப்பார்கள். ஒரு நாள் இரவில் முஆத் (ரலி) அவர்கள் நபி (ஸல்) அவர்களுடன் இஷாத் தொழுது விட்டுத் தம் கூட்டத்தாரிடம் திரும்பிச் சென்று அவர்களுக்கு (அதே இஷாவை)த் தொழுவித்தார்கள்.அதில் (பெரிய அத்தியாயமான) அல்பகராஎனும் (2ஆவது) அத்தியாயத்தை ஓத ஆரம்பித்தார்கள். அப்போது ஒரு மனிதர் (தொழுகையிலிருந்து) விலகி சலாம் கொடுத்தார். பின்னர் தனியாகத் தொழுதுவிட்டுத் திரும்பிச் சென்றுவிட்டார். மக்கள் அவரிடம், இன்னாரே, நீர் நயவஞ்சகர் (முனாஃபிக்) ஆகிவிட்டீரா? என்று கேட்டார்கள். அதற்கு அந்த மனிதர், இல்லை. அல்லாஹ்வின் மீது சத்தியமாக! (நான் நயவஞ்சகன் அல்லன்). நிச்சயம் நான் அல்லாஹ்வின் தூதர் (ஸல்) அவர்களிடம் சென்று (இது குறித்து) தெரிவிப்பேன் எனக் கூறினார். அவ்வாறே அவர் அல்லாஹ்வின் தூதர் (ஸல்) அவர்களிடம் சென்று, அல்லாஹ்வின் தூதரே! நாங்கள் பகல் வேளைகளில் வேலைவெட்டிகளில் ஈடுபடுகின்றவர்கள். நாங்கள் ஒட்டகங்கள் மூலம் தண்ணீர் பாய்ச்சுவோம். இந்நிலையில் முஆத் பின் ஜபல் அவர்கள் (நேற்றிரவு) உங்களுடன் இஷாத் தொழுதுவிட்டு வந்து (எங்களுக்குத் தொழுவித்தார். அதில் பெரிய அத்தியாயமான) அல்பகரா அத்தியாயத்தை ஓதலானார். (எனவேதான் விலகிச் சென்று தனியாகத் தொழுதேன்) என்று கூறினார். உடனே அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் முஆத் (ரலி) அவர்களை நோக்கித் திரும்பி, முஆதே! (நீரென்ன) குழப்பவாதியா? என்று கேட்டுவிட்டு, (நீர் மக்களுக்குத் தலைமை தாங்கித் தொழுவிக்கும் போது சற்று சிறிய அத்தியாயமான) இன்ன அத்தியாயத்தை ஓதுவீராக; இன்ன அத்தியாயத்தை ஓதுவீராக என்று சொன்னார்கள். இதன் அறிவிப்பாளர்களில் ஒருவரான சுஃப்யான் பின் உயைனா (ரஹ்) அவர்கள் கூறுகின்றார்கள்: நான் (இந்த ஹதீஸை எனக்கு அறிவித்த) அம்ர் பின் தீனார் (ரஹ்) அவர்களிடம், (நபி (ஸல்) அவர்கள் முஆத் (ரலி) அவர்களிடம்) வஷ்ஷம்ஸி வ ளுஹாஹா, வள்ளுஹா வல்லைலி, வல்லைலி இதா யஃக்ஷா, சப்பிஹிஸ்ம ரப்பிக்கல் அஃலா ஆகிய (முறையே 91, 93,92,87ஆவது) அத்தியாயங்களை ஓதுவிராக என்று கூறியதாக ஜாபிர் (ரலி) அவர்களிடமிருந்து அபுஸ்ஸுபைர் (ரஹ்) அவர்கள் எமக்கு அறிவித்தார்களே? என்று கேட்டேன். அதற்கு அம்ர் பின் தீனார் (ரஹ்) அவர்கள், (ஆம்) இது போன்றுதான் (அறிவித்தார்கள்) என்றார்கள். அத்தியாயம் : 4
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1040</td></tr><tr><td>Arabic No</td><td>465.01</td></tr><tr><td>Reference</td><td>Book 4 Hadith 202</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Bana Muhammed b. Abbâd rivayet etti. (Dediki): Bize Süfyân, Amr'dan, o da Câbir'den naklen rivayet etti. Câbir şöyle demiş: — Muaz, Nebi (Sallallahu Aleyhi ve Sellem) ile birlikte namazı kılar, sonra kavmine gelerek onlara imam olurdu. Bir gece Nebi (Sallallahu Aleyhi ve Sellem) ile birlikte yatsıyı kıldıktan sonra kavmine gelerek onlara imam oldu ve «Bakara» suresini okumağa başladı. Derken bir adam selâm vererek namazdan ayrıldı. Sonra yalnız başına kıldı ve çıktı gitti. Ashâb o zâta: Sen münafık mı oldun yâ fiilân? dediler. — «Hayır Vallahi (münafık değilim; hele sabah olsun) ben bunu mutlaka gider Resulullah (Sallallahı Aleyhi ve Sellem)'e haber veririm!.» cevâbını verdi, ve (ertesi günü) Resulullah (Sallallahu Aleyhi ve Sellem) 'e gelerek: «Yâ Resulâllah, biz develerle su taşıyan insanlarız, gündüzleyin çalışırız, Muâz seninle birlikte yatsıyı kılmış; sonra (Bize) gelerek Sure-i Bakara'yı tutturdu.»» dedi. Bunun üzerine Resulullah (Sallallahu Aleyhi ve Sellem) Muâz'a dönerek: «Yâ Muâz, sen fitnebaz mı oldun yoksa?., filân ve filân sureleri (okusaydın yâ!)» buyurdular. Süfyân şöyle demiş: «Ben Amr'a: Ebu Zübeyr bize Câbir'den naklen Resulullah (Sallallahu Aleyhi ve Sellem)'in: Şems, Duha, Leyi ve A'lâ surelerini oku!» buyurduğunu rivayet etti, dedim. Amr da bunun gibi bir şey, dedi.»
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1040</td></tr><tr><td>Arabic No</td><td>465.01</td></tr><tr><td>Reference</td><td>Book 4 Hadith 202</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
سفیان نے عمرو سے ، انہوں نے حضرت جابر ‌رضی ‌اللہ ‌عنہ ‌ ‌ سے حدیث بیان کی ، انہوں نے کہا : حضرت معاذ ‌رضی ‌اللہ ‌عنہ ‌ ‌ نبی اکرمﷺ کے ساتھ نماز پڑھا کرتے تھے ، پھر آ کر اپنے قبیلے کی ( مسجد میں ) امامت کراتے ، ایک رات انہوں نے عشاء کی نماز رسول اللہﷺ کے ساتھ پڑھی ، پھر اپنی قوم کے پاس آئے ، ان کی امامت اور ( سورۃ فاتحہ کے بعد ) سورۃ بقرہ پڑھنی شروع کر دی ۔ ایک شخص الگ ہو گیا ، ( نماز سے ، سلام پھیرا ، پھر اکیلے نماز پڑھی اور چلا گیا تو لوگوں نے اس سے کہا : اے فلاں! کیا تو منافق ہو گیا ہے؟ اس نے جواب دیا : اللہ کی قسم! نہیں ، میں ضرور رسول اللہﷺ کی خدمت میں حاضر ہو کر آپ کو اس معاملے سے آگاہ کروں گا ، چنانچہ وہ رسول اللہﷺ کی خدمت میں حاضر ہوا اور عرض کی : اے اللہ کے رسول! ہم ان اونٹوں والے ہیں جو پانی ڈھوتے ہیں ، دن بھر کام کرتے ہیں اور معاذ ‌رضی ‌اللہ ‌عنہ ‌ ‌ نے عشاء کی نماز آپ کے ساتھ پڑھی ، پھر آ کر سورۃ بقرہ کے ساتھ نماز شروع کر دی ۔ رسول اللہﷺ نے ( یہ سن کر ) حضرت معاذ ‌رضی ‌اللہ ‌عنہ ‌ ‌ کی طرف رخ کیا اور فرمایا : ’’اے معاذ! کیا لوگوں کو فتنے میں مبتلا کرنے والے ہو؟ فلاں سورت پڑھا کرو اور فلاں سورت پڑھا کرو ۔ ‘ ‘ سفیان نے کہا : میں نے عمرو سے کہا : ابو زبیر نے ہمیں جابر ‌رضی ‌اللہ ‌عنہ ‌ ‌ سے بیان کیا کہ آپ نے فرمایا : ﴿والشمس وضحاها﴾ ﴿والضحى﴾ ، ﴿واليل إذا يغشى﴾ اور ﴿سبح اسم ربك الأعلى﴾ پڑھا کرو ۔ اور عمرو نے کہا : اس جیسی ( سورتیں پڑھا کرو)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1040</td></tr><tr><td>Arabic No</td><td>465.01</td></tr><tr><td>Reference</td><td>Book 4 Hadith 202</td></tr></tbody></table></div>