## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا قُتَيْبَةُ بْنُ سَعِيدٍ، حَدَّثَنَا لَيْثُ بْنُ سَعْدٍ، عَنْ عُقَيْلٍ، عَنِ الزُّهْرِيِّ، قَالَ أَخْبَرَنِي عُبَيْدُ اللَّهِ بْنُ عَبْدِ اللَّهِ بْنِ عُتْبَةَ بْنِ مَسْعُودٍ، عَنْ أَبِي هُرَيْرَةَ، قَالَ لَمَّا تُوُفِّيَ رَسُولُ اللَّهِ صلى الله عليه وسلم وَاسْتُخْلِفَ أَبُو بَكْرٍ بَعْدَهُ وَكَفَرَ مَنْ كَفَرَ مِنَ الْعَرَبِ قَالَ عُمَرُ بْنُ الْخَطَّابِ لأَبِي بَكْرٍ كَيْفَ تُقَاتِلُ النَّاسَ وَقَدْ قَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏ "‏ أُمِرْتُ أَنْ أُقَاتِلَ النَّاسَ حَتَّى يَقُولُوا لاَ إِلَهَ إِلاَّ اللَّهُ فَمَنْ قَالَ لاَ إِلَهَ إِلاَّ اللَّهُ فَقَدْ عَصَمَ مِنِّي مَالَهُ وَنَفْسَهُ إِلاَّ بِحَقِّهِ وَحِسَابُهُ عَلَى اللَّهِ ‏"‏ ‏.‏ فَقَالَ أَبُو بَكْرٍ وَاللَّهِ لأُقَاتِلَنَّ مَنْ فَرَّقَ بَيْنَ الصَّلاَةِ وَالزَّكَاةِ فَإِنَّ الزَّكَاةَ حَقُّ الْمَالِ وَاللَّهِ لَوْ مَنَعُونِي عِقَالاً كَانُوا يُؤَدُّونَهُ إِلَى رَسُولِ اللَّهِ صلى الله عليه وسلم لَقَاتَلْتُهُمْ عَلَى مَنْعِهِ ‏.‏ فَقَالَ عُمَرُ بْنُ الْخَطَّابِ فَوَاللَّهِ مَا هُوَ إِلاَّ أَنْ رَأَيْتُ اللَّهَ عَزَّ وَجَلَّ قَدْ شَرَحَ صَدْرَ أَبِي بَكْرٍ لِلْقِتَالِ فَعَرَفْتُ أَنَّهُ الْحَقُّ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>124</td></tr><tr><td>Arabic No</td><td>20</td></tr><tr><td>Reference</td><td>Book 1 Hadith 32</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
হাদিস একাডেমি নাম্বারঃ ৩২, আন্তর্জাতিক নাম্বারঃ ২০ ৩২-(৩২/২০) কুতাইবাহ ইবনু সাঈদ (রহঃ) ... আবূ হুরাইরাহ (রাযিঃ) থেকে বর্ণিত। তিনি বলেন, রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম এর ইন্তিকালের পর আবূ বাকর (রাযিঃ) খলীফা নিযুক্ত হলেন। এ সময় আরবের একদল লোক (যাকাত অস্বীকার করে) মুরতাদ হয়ে গেল। [আবূ বাকর (রাযিঃ) তাদের বিরুদ্ধে যুদ্ধের সংকল্প করলেন] 'উমার (রাযিঃ) বললেন, আপনি কিরূপে লোকদের বিরুদ্ধে যুদ্ধ করবেন?[1] অথচ রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম বলেছেনঃ "আমি (আল্লাহর পক্ষ থেকে) লোকদের বিরুদ্ধে যুদ্ধ করতে আদিষ্ট হয়েছি যে পর্যন্ত না তারা বলে “লা-ইলা-হা ইল্লাল্লা-হ (আল্লাহ ছাড়া প্রকৃত কোন ইলাহ নেই) আর যে ব্যক্তি 'লা-ইলা-হা ইল্লাল্লা-হ' বললো, সে তার জান-মাল আমার হাত থেকে রক্ষা করলো। অবশ্য আইনের দাবী আলাদা। (অর্থাৎ ইসলামের বিধান অনুযায়ী দণ্ডনীয় কোন অপরাধ করলে তাকে অবশ্যই শাস্তি ভোগ করতে হবে)। তবে তার আসল বিচারের ভার আল্লাহর উপর ন্যস্ত। আবূ বাকর (রাযিঃ) বললেন, আল্লাহর কসম, যে ব্যক্তি সালাত ও যাকাতের মধ্যে পার্থক্য করবে আমি অবশ্যই তার বিরুদ্ধে যুদ্ধ করবো [2] কেননা যাকাত হচ্ছে মালের (উপর বঞ্চিতের) অধিকার। আল্লাহর কসম, যদি তারা আমাকে একখানা রশি প্রদানেও অস্বীকৃতি জানায় যা তারা (যাকাত বাবদ) রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম কে প্রদান করতো, তবে আমি এ অস্বীকৃতির কারণে তাদের বিরুদ্ধে যুদ্ধ করবো। এবার উমর ইবনুল খাত্তাব (রাযিঃ) বললেন, আল্লাহর কসম, ব্যাপারটা এ ছাড়া আর কিছুই নয় যে, আল্লাহ তা'আলা আবূ বাকরের হৃদয়কে যুদ্ধের জন্য প্রশস্ত করে দিয়েছিলেন। আমি স্পষ্টই উপলদ্ধি করলাম, এটাই (আবূ বকরের সিদ্ধান্তই) সঠিক এবং যথার্থ। (ইসলামিক ফাউন্ডেশনঃ ৩২, ইসলামিক সেন্টারঃ ৩২) 1. রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম এর ইন্তিকালের পর আরাবের কিছু সংখ্যক লোক মুরতাদ হয়ে যায়, কিছু সংখ্যক লোক যাকাত দিতে অস্বীকার করে। উমার (রাযিঃ) এর জিজ্ঞাস্য ছিল, যারা যাকাত দিতে অস্বীকার করে অথচ 'লা-ইলা-হা ইল্লাল্লা-হ' বলে, তাদের বিরুদ্ধে জিহাদ করা কি উচিত? 2. যারা সালাত ফরয মনে করে অথচ যাকাত দেয়া ফরয মনে করে না।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>124</td></tr><tr><td>Arabic No</td><td>20</td></tr><tr><td>Reference</td><td>Book 1 Hadith 32</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
It is narrated on the authority of Abu Huraira that when the Messenger of Allah (ﷺ) breathed his last and Abu Bakr was appointed as his successor (Caliph), those amongst the Arabs who wanted to become apostates became apostates. 'Umar b. Khattab said to Abu Bakr:Why would you fight against the people, when the Messenger of Allah declared: I have been directed to fight against people so long as they do not say: There is no god but Allah, and he who professed it was granted full protection of his property and life on my behalf except for a right? His (other) affairs rest with Allah. Upon this Abu Bakr said: By Allah, I would definitely fight against him who severed prayer from Zakat, for it is the obligation upon the rich. By Allah, I would fight against them even to secure the cord (used for hobbling the feet of a camel) which they used to give to the Messenger of Allah (as zakat) but now they have withheld it. Umar b. Khattab remarked: By Allah, I found nothing but the fact that Allah had opened the heart of Abu Bakr for (perceiving the justification of) fighting (against those who refused to pay Zakat) and I fully recognized that the (stand of Abu Bakr) was right
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>124</td></tr><tr><td>Arabic No</td><td>20</td></tr><tr><td>Reference</td><td>Book 1 Hadith 32</td></tr></tbody></table></div>

## French


<div dir="ltr" lang="fr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Abou Hourayra (que Dieu l'agrée) a dit : A la mort de l'Envoyé de Dieu (paix et bénédiction de Dieu sur lui), quand Abou Bakr fut investi du califat et qu'un certain nombre d'Arabes renièrent leur foi, dit à Abou Bakr : "Comment vas-tu les combattre alors que l'Envoyé de Dieu (le Très-Haut) a dit : J'ai reçu l'ordre de combattre les idolâtres jusqu'à ce qu'ils confessent qu'il n'y a d'autre divinité que Dieu. Celui qui témoigne de l'unicité de Dieu, rends sa vie et ses biens inviolables, sauf au cas où il serait jugé coupable et c'est à Dieu qu'il appartiendra de régler son compte". Abou Bakr répondit : "Par Dieu! Je combattrai quiconque fait de distinction entre la prière et l'aumône légale (Az-Zakâ); car celle-ci est le dû des biens (c.-à-d. le droit de Dieu sur nos biens comme la prière et le jeûne sont le droit de Dieu sur notre corps). Par Dieu! S'ils me refusent un licou qu'ils livraient en impôt à l'Envoyé de Dieu (paix et bénédiction de Dieu sur lui), je les combattrai pour ce refus
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>124</td></tr><tr><td>Arabic No</td><td>20</td></tr><tr><td>Reference</td><td>Book 1 Hadith 32</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Qutaibah bin Sa'id] telah menceritakan kepada kami [Laits bin Sa'ad] dari [Uqail] dari [az-Zuhri] dia berkata, telah mengabarkan kepada kami [Ubaidullah bin Abdullah bin Utbah bin Mas'ud] dari [Abu Hurairah] dia berkata, "Ketika Rasulullah shallallahu 'alaihi wasallam meninggal dunia, dan Abu Bakar diangkat sebagai khalifah setelahnya, serta orang-orang kafir dari kalangan Arab melakukan kekufuran, maka [Umar bin al-Khaththab] berkata kepada Abu Bakar, 'Bagaimana mungkin kamu akan memerangi manusia, sementara Rasulullah shallallahu 'alaihi wasallam telah bersabda: "Aku diperintahkan untuk memerangi manusia hingga mereka mengucapkan, 'Tidak ada tuhan (yang berhak disembah) melainkan Allah', maka barangsiapa yang mengucapkan, 'Tidak ada tuhan (yang berhak disembah) melainkan Allah', maka sungguh dia telah menjaga harta dan jiwanya dari (seranganku) kecuali dengan hak Islam, dan hisabnya diserahkan kepada Allah.' Maka [Abu Bakar] berkata, 'Demi Allah, sungguh aku akan memerangi orang yang membedakan antara shalat dan zakat, karena zakat adalah (tuntuan) hak terhadap harta. Demi Allah, kalau mereka menghalangiku karena keengganan mereka sedangkan mereka pernah membayarnya kepada Rasulullah shallallahu 'alaihi wasallam, aku tetap akan memerangi mereka karena keengganan mereka.' Maka [Umar bin al-Khaththab] berkata, 'Demi Allah tidaklah dia melainkan bahwa aku melihat Allah telah melapangkan dada Abu Bakar untuk memerangi (mereka) lalu aku mengetahui bahwa ia adalah kebenaran
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>124</td></tr><tr><td>Arabic No</td><td>20</td></tr><tr><td>Reference</td><td>Book 1 Hadith 32</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>

</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>124</td></tr><tr><td>Arabic No</td><td>20</td></tr><tr><td>Reference</td><td>Book 1 Hadith 32</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Bize Kuteybetü'bnü Said rivayet etti, (Dedi ki): Bize Leys b. Sa'd, Ukayl'den, o da Zühri'den naklen rivayet etti. Zühri de-miş ki: Bana Ubeydullah b. Abdillâh b.Utbete'bni Mer'ud Ebu Hüreyre'den naklen haber verdi. Ebu Hüreyre şöyle demiş : Raslilullah (Sallallahu aleyhi ve Sellem) vefat edip ondan sonra Ebu Bekir halifelik makamına seçilip Araplardan küfre sapanlar da kafir olunca Ömer b. el-Hattab, Ebu Bekir'e: - İnsanlarla nasıl savaşırsın? Halbuki Raslilullah (Sallallahu aleyhi ve Sellem): "Ben insanlarla Ia ilahe illallah deyinceye kadar savaşmakla emrolundum. La ilahe illallah diyen bana karşı malını ve canını -onun hakkı ile olması dışında- korumuş olur, hesabını görmek de Allah'a aittir" buyurmuşken nasıl savaşırsın, dedi. Ebu Bekr: Allah'a yemin ederim ki namaz ile zekat arasında fark gören kimselerle savaşırım çünkü zekat malın hakkıdır. Allah'a yemin ederim ki eğer Raslilullah (Sallallahu aleyhi ve Sellem)'e O hayatta iken verdikleri bir yuları dahi bana vermeyecek olurlarsa onu bana vermemelerine karşılık andolsun onlarla savaşırım, dedi. Sonra Ömer b. el-Hattab şöyle dedi: Allah'a yemin ederim ki sonunda aziz ve celil Allah'ın, Ebu Bekr'in kalbine savaşmak için bir genişlik vermiş olduğunu gördüm ve onun (bu halinin) hak olduğunu bildim. Diğer tahric: Buhari, 1399, 1457,2946,6924,7284; Ebu Davud, 1556, 1557; Tirmizi, 2607; Nesai, 2442,3091-3093,3980,3981, 3983, 3985; Tuhfetu'l-Eşraf, 10666 AHMED DAVUDOĞLU AÇIKLAMASI İÇİN BURAYA TIKLAYIN 124,125,126,127,128,129,130
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>124</td></tr><tr><td>Arabic No</td><td>20</td></tr><tr><td>Reference</td><td>Book 1 Hadith 32</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
جناب عبید اللہ بن عبد اللہ بن عتبہ بن مسعود نے حضرت ابو ہریرہ ‌رضی ‌اللہ ‌عنہ ‌ ‌ سے روایت کی کہ جب رسول ا للہﷺ نے وفات پائی اور آپ کے بعد حضرت ابو بکر ‌رضی ‌اللہ ‌عنہ ‌ ‌ خلیفہ بنائے گئے تو عربوں میں سے کافر ہونے والے کافر ہو گئے ( اور ابوبکر ‌رضی ‌اللہ ‌عنہ ‌ ‌ نےمانعین زکاۃ سے جنگ کا ارادہ کیا ) تو حضرت عمر بن خطاب ‌رضی ‌اللہ ‌عنہ ‌ ‌ نے حضرت ابو بکر ‌رضی ‌اللہ ‌عنہ ‌ ‌ سے کہا : آپ ان لوگوں سے کیسے جنگ کریں گے جبکہ رسول ا للہ ﷺ فرما چکے ہیں : ’’ مجھے حکم دیا گیا ہے کہ میں لوگوں سے لڑائی کروں یہاں تک کہ وہ لا اله الاالله کا اقرار کر لیں ، پس جو کوئی لا اله الا الله کا قائل ہو گیا ، اس نے میری طرف سے اپنی جان اور اپنا مال محفوظ کر لیا ، الا یہ کہ اس ( لا اله الا الله ) کا حق ہو ، اور اس کا حساب اللہ تعالیٰ پر ہے ؟ ‘ ‘ اس پر ابوبکر ‌رضی ‌اللہ ‌عنہ ‌ ‌ نےجواب دیا : اللہ کی قسم ! میں ان لوگوں سے جنگ کروں گا جو نماز او رزکاۃ میں فرق کریں گے ، کیونکہ زکاۃ مال ( میں اللہ ) کا حق ہے ۔ اللہ کی قسم ! اگر یہ لوگ ( اونٹ کا ) پاؤں باندھنے کی ایک رسی بھی روکیں گے ، جو وہ رسول اللہ ﷺ کو دیا کرتے تھے تو میں اس کے روکنے پر بھی ان سے جنگ کروں گا ۔ اس پر حضرت عمر ‌رضی ‌اللہ ‌عنہ ‌ ‌ نے کہا تھا : اللہ کی قسم ! اصل بات اس کےسوا اور کچھ نہیں کہ میں نے دیکھا اللہ تعالیٰ نےحضرت ابوبکر ‌رضی ‌اللہ ‌عنہ ‌ ‌ کا سینہ جنگ کے لیے کھول دیا ، تو میں جان گیا کہ حق یہی ہے ۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>124</td></tr><tr><td>Arabic No</td><td>20</td></tr><tr><td>Reference</td><td>Book 1 Hadith 32</td></tr></tbody></table></div>