## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
أَخْبَرَنَا مُحَمَّدُ بْنُ عَبْدِ اللَّهِ بْنِ بَزِيعٍ، قَالَ حَدَّثَنَا عَبْدُ الأَعْلَى بْنُ عَبْدِ الأَعْلَى، قَالَ حَدَّثَنَا عُبَيْدُ اللَّهِ، - وَهُوَ ابْنُ عُمَرَ - عَنْ أَبِي حَازِمٍ، عَنْ سَهْلِ بْنِ سَعْدٍ، قَالَ انْطَلَقَ رَسُولُ اللَّهِ صلى الله عليه وسلم يُصْلِحُ بَيْنَ بَنِي عَمْرِو بْنِ عَوْفٍ فَحَضَرَتِ الصَّلاَةُ فَجَاءَ الْمُؤَذِّنُ إِلَى أَبِي بَكْرٍ فَأَمَرَهُ أَنْ يَجْمَعَ النَّاسَ وَيَؤُمَّهُمْ فَجَاءَ رَسُولُ اللَّهِ صلى الله عليه وسلم فَخَرَقَ الصُّفُوفَ حَتَّى قَامَ فِي الصَّفِّ الْمُقَدَّمِ وَصَفَّحَ النَّاسُ بِأَبِي بَكْرٍ لِيُؤْذِنُوهُ بِرَسُولِ اللَّهِ صلى الله عليه وسلم وَكَانَ أَبُو بَكْرٍ لاَ يَلْتَفِتُ فِي الصَّلاَةِ فَلَمَّا أَكْثَرُوا عَلِمَ أَنَّهُ قَدْ نَابَهُمْ شَىْءٌ فِي صَلاَتِهِمْ فَالْتَفَتَ فَإِذَا هُوَ بِرَسُولِ اللَّهِ صلى الله عليه وسلم فَأَوْمَأَ إِلَيْهِ رَسُولُ اللَّهِ صلى الله عليه وسلم أَىْ كَمَا أَنْتَ فَرَفَعَ أَبُو بَكْرٍ يَدَيْهِ فَحَمِدَ اللَّهَ وَأَثْنَى عَلَيْهِ لِقَوْلِ رَسُولِ اللَّهِ صلى الله عليه وسلم ثُمَّ رَجَعَ الْقَهْقَرَى وَتَقَدَّمَ رَسُولُ اللَّهِ صلى الله عليه وسلم فَصَلَّى فَلَمَّا انْصَرَفَ قَالَ لأَبِي بَكْرٍ ‏"‏ مَا مَنَعَكَ إِذْ أَوْمَأْتُ إِلَيْكَ أَنْ تُصَلِّيَ ‏"‏ ‏.‏ فَقَالَ أَبُو بَكْرٍ رضى الله عنه مَا كَانَ يَنْبَغِي لاِبْنِ أَبِي قُحَافَةَ أَنْ يَؤُمَّ رَسُولَ اللَّهِ صلى الله عليه وسلم ‏.‏ ثُمَّ قَالَ لِلنَّاسِ ‏"‏ مَا بَالُكُمْ صَفَّحْتُمْ إِنَّمَا التَّصْفِيحُ لِلنِّسَاءِ ‏"‏ ‏.‏ ثُمَّ قَالَ ‏"‏ إِذَا نَابَكُمْ شَىْءٌ فِي صَلاَتِكُمْ فَسَبِّحُوا ‏"‏ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Abu Ghuddah</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1183</td></tr><tr><td>Arabic No</td><td>1183</td></tr><tr><td>Reference</td><td>Book 13 Hadith 5</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
হাদিস একাডেমি নাম্বারঃ ১১৮৩, আন্তর্জাতিক নাম্বারঃ ১১৮৪ ১১৮৩. মুহাম্মাদ ইবনু আবদুল্লাহ ইবনু বাযী (রহ.) ..... সাহল ইবনু সা'দ (রাঃ) হতে বর্ণিত। তিনি বলেন, রাসূলুল্লাহ (সা.) বানূ ‘আমর ইবনু 'আওফে (কোন সংকট) মীমাংসা করার জন্যে গেলেন। এরপর সালাতের সময় হলে মুয়াযযিন আবু বাকর (রাঃ)-এর নিকট এসে সাহাবীগণকে একত্র করে তাদের ইমামাত করতে অনুরোধ করলেন। ইতোমধ্যে রাসূলুল্লাহ (সা.) এসে কাতার ফাঁক করে প্রথম সারিতে দাঁড়িয়ে গেলেন। সাহাবীগণ আবূ বাকর (রাঃ)-কে রাসূলুল্লাহ (সা.) -এর আগমন সম্পর্কে জানানোর জন্যে হাতে তালি দিলেন। আবূ বাকর (রাঃ) সালাতে (একাগ্রচিত্ততার কারণে) অন্যদিকে লক্ষ্য করতেন না। যখন হাত তালির মাত্রা বেড়ে গেল তিনি বুঝতে পারলেন যে, তাঁদের সালাতে কোন কিছু ঘটেছে। তিনি লক্ষ্য করে রাসূলুল্লাহ (সা.)- এর আসা সম্বন্ধে অবহিত হলেন। রাসূলুল্লাহ (সা.) তার দিকে ইশারা করলেন যে, তুমি নিজ অবস্থায় থাক। তখন আবূ বাকর (রাঃ) রাসূলুল্লাহ (সা.) -এর এ কথার জন্যে তাঁর দু' হাত উত্তোলন পূর্বক আল্লাহ তা'আলার প্রশংসা ও তাঁর গুণগান করলেন এবং পিছু হটে গেলেন। রাসূলুল্লাহ (সা.) অগ্রসর হয়ে সালাত আদায় করালেন। সালাত সমাপ্ত করে তিনি আবূ বাকর (রাঃ) -কে বললেন, আমি যখন তোমার প্রতি ইঙ্গিত করেছিলাম তখন তোমাকে সালাত আদায় করতে কিসে নিষেধ করেছিল? তিনি বললেন, ইবনু আবূ কুহাফার (আবূ বাকর) জন্যে রাসূলুল্লাহ (সা.) -এর সামনে ইমামতি করা সমীচীন ছিল না। এরপর রাসূলুল্লাহ (সা.) সাহাবীগণকে বললেন, তোমাদের কি হয়েছিল? তোমরা হাতে তালি দিচ্ছিলে কেন? হাতে তালি দেয়া তো মহিলাদের জন্যে। অতঃপর বললেন, যদি তোমাদের সালাতে কিছু ঘটে যায় তবে তোমরা তাসবীহ (সুবহানাল্লা-হ) পড়বে। সহীহ: বুখারী ৬৮৪, ১২৩৪; মুসলিম (১/১০২), (১/১০৩)। [দ্রঃ ৭৮৪, ৭৯৩]
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Abu Ghuddah</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1183</td></tr><tr><td>Arabic No</td><td>1183</td></tr><tr><td>Reference</td><td>Book 13 Hadith 5</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
It was narrated that Sahl bin Sa'd said:"The Messenger of Allah (ﷺ) set out to bring about reconciliation among Banu 'Amr bin 'Awf. The time for prayer came, and the Mu'adhdhin went to Abu Bakr to tell him to gather the people and lead them in prayer. Then the Messenger of Allah (ﷺ) came and passed though the rows until he stood in the first row. The people started clapping to let Abu Bakr know that the Messenger of Allah (ﷺ) had come. Abu Bakr never used to turn around when he prayed, but when they clapped consistently he realized something must have happened while they were praying. So he turned around and saw the Messenger of Allah (ﷺ). The Messenger of Allah (ﷺ) gestured to him to stay where he was. Abu Bakr raised his hands and praised and thanked Allah (SWT) for what the Messenger of Allah (ﷺ) had said. Then, he moved backwards, and the Messenger of Allah (ﷺ) went forward and prayed. When he finished, he said to Abu Bakr: 'What stopped you from continuing to pray when I gestured to you?' Abu Bakr, may Allah (SWT) be pleased with him, said: 'It was not appropriate for the son of Abu Quhafah to lead the Messenger of Allah (ﷺ) in prayer.' Then he said to the people: 'Why did you clap?' Clapping is for women.' Then he said: 'If you notice something when you are praying, say "SubhanAllah
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Abu Ghuddah</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1183</td></tr><tr><td>Arabic No</td><td>1183</td></tr><tr><td>Reference</td><td>Book 13 Hadith 5</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah mengabarkan kepada kami [Muhammad bin 'Abdullah bin Bazi'] dia berkata; telah menceritakan kepada kami ['Abdul A'la bin 'Abdul A'la] dia berkata; telah menceritakan kepada kami ['Ubaidullah bin 'Umar] dari [Abu Hazim] dari [Sahl bin Sa'ad] dia berkata; Pernah Rasulullah Shallallahu'alaihiwasallam pergi untuk mendamaikan Bani Amru bin Auf yang mempunyai suatu masalah. Ketika' tiba waktu shalat, muadzin datang kepada Abu Bakar dan menyuruhnya mengumpulkan orang-orang dan mengimami mereka. Kemudian datang Rasulullah Shallallahu'alaihiwasallam melalui celah-celah barisan shalat hingga beliau Shallallahu'alaihiwasallam berdiri di barisan terdepan. Orang-orang lalu mulai menepukkan tangannya kepada Abu Bakar untuk memberitahu keberadaan Rasulullah Shallallahu'alaihiwasallam, namun Abu Bakar tidak menoleh dalam shalatnya. Setelah orang-orang banyak yang menepukkan tangannya (sebagai isyarat), Abu Bakar tahu bahwa mereka mengingatkan sesuatu, maka ia menoleh dan mendapati Rasulullah Shallallahu'alaihiwasallam. Rasulullah Shallallahu'alaihiwasallam mengisyaratkan kepadanya untuk terus melanjutkan shalatnya. Maka Abu Bakar mengangkat kedua tangannya dan memuji Allah dengan ucapan Rasulullah Shallallahu'alaihiwasallam lantas mundur ke belakang, maka Rasulullah Shallallahu'alaihiwasallam maju untuk menjadi imam. Setelah selesai shalat beliau Shallallahu'alaihiwasallam bertanya kepada Abu Bakar, 'Wahai Abu Bakar, apakah yang menghalangimu untuk shalat menjadi imam bagi manusia saat kuisyaratkan demikian? ' Abu Bakar berkata; 'Tidaklah pantas bagi Ibnu Quhafah untuk mengimami shalat Rasulullah Shallallahu'alaihi wasallam'. Kemudian beliau Shallallahu'alaihiwasallam bersabda kepada orang-orang: 'Wahai manusia sekalian, kenapa kalian bertepuk tangan. Tepuk tangan hanya untuk wanita. Jika terjadi sesuatu dalam shalat kalian, maka ucapkan, "Subhanallah (Maha suci Allah)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Abu Ghuddah</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1183</td></tr><tr><td>Arabic No</td><td>1183</td></tr><tr><td>Reference</td><td>Book 13 Hadith 5</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>

</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Abu Ghuddah</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1183</td></tr><tr><td>Arabic No</td><td>1183</td></tr><tr><td>Reference</td><td>Book 13 Hadith 5</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
سہل بن سعد رضی اللہ عنہ کہتے ہیں کہ رسول اللہ صلی اللہ علیہ وسلم قبیلہ بنی عمرو بن عوف کے درمیان صلح کرانے گئے تھے کہ نماز کا وقت ہو گیا، تو مؤذن ابوبکر رضی اللہ عنہ کے پاس آیا، اور اس نے ان سے لوگوں کو جمع کر کے ان کی امامت کرنے کے لیے کہا ( چنانچہ انہوں نے امامت شروع کر دی ) اتنے میں رسول اللہ صلی اللہ علیہ وسلم تشریف لے آئے، اور صفوں کو چیر کر اگلی صف میں آ کر کھڑے ہو گئے، لوگ ابوبکر رضی اللہ عنہ کو تالیاں بجانے لگے تاکہ انہیں رسول اللہ صلی اللہ علیہ وسلم کی آمد کی خبر دے دیں، جب لوگوں نے کثرت سے تالیاں بجائیں تو انہیں احساس ہوا کہ نماز میں کوئی چیز ہو گئی ہے، تو وہ متوجہ ہوئے، تو کیا دیکھتے ہیں کہ رسول اللہ صلی اللہ علیہ وسلم تشریف لے آئے ہیں ابوبکر رضی اللہ عنہ نماز میں کسی اور طرف دھیان نہیں کرتے تھے رسول اللہ صلی اللہ علیہ وسلم نے انہیں اشارہ کیا کہ جیسے ہو ویسے ہی رہو، رسول اللہ صلی اللہ علیہ وسلم کے اس کہنے پر ابوبکر رضی اللہ عنہ نے اپنے دونوں ہاتھ اٹھا کر اللہ کی حمد و ثنا کی، پھر وہ الٹے پاؤں پیچھے آ گئے، اور رسول اللہ صلی اللہ علیہ وسلم آگے بڑھ گئے، پھر آپ نے نماز پڑھائی، جب آپ نماز سے فارغ ہوئے تو ابوبکر رضی اللہ عنہ سے پوچھا: تم نے نماز کیوں نہیں پڑھائی، جب میں نے تمہیں اشارہ کر دیا تھا؟ تو ابوبکر رضی اللہ عنہ نے کہا: ابوقحافہ کے بیٹے کو یہ بات زیب نہیں دیتی کہ وہ رسول اللہ صلی اللہ علیہ وسلم کی امامت کرے، پھر آپ صلی اللہ علیہ وسلم نے لوگوں سے کہا: تمہیں کیا ہو گیا تھا کہ تم تالیاں بجا رہے تھے، تالیاں تو عورتوں کے لیے ہے ، پھر آپ صلی اللہ علیہ وسلم نے فرمایا: جب تمہیں تمہاری نماز میں کوئی چیز پیش آ جائے، تو تم سبحان اللہ کہو ۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Abu Ghuddah</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1183</td></tr><tr><td>Arabic No</td><td>1183</td></tr><tr><td>Reference</td><td>Book 13 Hadith 5</td></tr></tbody></table></div>