## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
أَخْبَرَنَا قُتَيْبَةُ، قَالَ حَدَّثَنَا يَعْقُوبُ بْنُ عَبْدِ الرَّحْمَنِ، قَالَ حَدَّثَنِي أَبُو حَازِمِ بْنِ دِينَارٍ، أَنَّ رِجَالاً، أَتَوْا سَهْلَ بْنَ سَعْدٍ السَّاعِدِيَّ وَقَدِ امْتَرَوْا فِي الْمِنْبَرِ مِمَّ عُودُهُ فَسَأَلُوهُ عَنْ ذَلِكَ فَقَالَ وَاللَّهِ إِنِّي لأَعْرِفُ مِمَّ هُوَ وَلَقَدْ رَأَيْتُهُ أَوَّلَ يَوْمٍ وُضِعَ وَأَوَّلَ يَوْمٍ جَلَسَ عَلَيْهِ رَسُولُ اللَّهِ صلى الله عليه وسلم أَرْسَلَ رَسُولُ اللَّهِ صلى الله عليه وسلم إِلَى فُلاَنَةَ امْرَأَةٍ قَدْ سَمَّاهَا سَهْلٌ ‏"‏ أَنْ مُرِي غُلاَمَكِ النَّجَّارَ أَنْ يَعْمَلَ لِي أَعْوَادًا أَجْلِسُ عَلَيْهِنَّ إِذَا كَلَّمْتُ النَّاسَ ‏"‏ ‏.‏ فَأَمَرَتْهُ فَعَمِلَهَا مِنْ طَرْفَاءِ الْغَابَةِ ثُمَّ جَاءَ بِهَا فَأَرْسَلَتْ إِلَى رَسُولِ اللَّهِ صلى الله عليه وسلم فَأَمَرَ بِهَا فَوُضِعَتْ هَا هُنَا ثُمَّ رَأَيْتُ رَسُولَ اللَّهِ صلى الله عليه وسلم رَقِيَ فَصَلَّى عَلَيْهَا وَكَبَّرَ وَهُوَ عَلَيْهَا ثُمَّ رَكَعَ وَهُوَ عَلَيْهَا ثُمَّ نَزَلَ الْقَهْقَرَى فَسَجَدَ فِي أَصْلِ الْمِنْبَرِ ثُمَّ عَادَ فَلَمَّا فَرَغَ أَقْبَلَ عَلَى النَّاسِ فَقَالَ ‏"‏ يَا أَيُّهَا النَّاسُ إِنَّمَا صَنَعْتُ هَذَا لِتَأْتَمُّوا بِي وَلِتَعَلَّمُوا صَلاَتِي ‏"‏ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Abu Ghuddah</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>739</td></tr><tr><td>Arabic No</td><td>739</td></tr><tr><td>Reference</td><td>Book 8 Hadith 52</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
হাদিস একাডেমি নাম্বারঃ ৭৩৯, আন্তর্জাতিক নাম্বারঃ ৭৪০ ৭৩৯. কুতায়বাহ্ (রহ.) ..... আবূ হাযিম ইবনু দীনার (রহ.) হতে বর্ণিত। কয়েকজন লোক সাহল ইবনু সা'দ আস-সাইদী (রাঃ)-এর নিকট আসলেন, তাঁরা মিম্বারের বিষয়ে সন্দেহ করতে লাগল যে, তার কাঠ কোথা থেকে আনা হয়েছে। তাঁরা তাঁকে এ সম্বন্ধে প্রশ্ন করলে তিনি বললেন, আল্লাহর শপথ! আমি জানি কোথা থেকে আনা হয়েছে। প্রথম যেদিন তা স্থাপন করা হয় এবং প্রথম যেদিন রাসূলুল্লাহ (সা.) তাতে বসেন সেদিন আমি তা দেখেছিলাম। রাসূলুল্লাহ (সা.) জনৈক মহিলার নিকট লোক পাঠিয়ে বললেন যে, তোমার কাঠমিস্ত্রি চাকরকে আদেশ কর, সে যেন আমার জন্যে একটা কাঠের মিম্বার তৈরি করে দেয়, যখন লোকের সাথে কথা বলবো আমি তার উপর বসবো। ঐ রমণী তাকে আদেশ করলে সে গাবা অরণ্যের ঝাউ বৃক্ষের কাঠ দ্বারা তা তৈরি করলো। তারপর তা নিয়ে সে মিস্ত্রি আসলো। সে মহিলা তা রাসূলুল্লাহ (সা.) -এর নিকট প্রেরণ করলে রসূলুল্লাহ্ (সা.)-এর নির্দেশে তা এখানে স্থাপন করা হয়। তারপর আমি রাসূলুল্লাহ (সা.) -কে তাতে আরোহণ করে সালাত আদায় করতে দেখেছি। তিনি এর উপর থেকেই তাকবীর বললেন ও রুকু করলেন। তারপর তিনি পেছনে সরে মিম্বারের মূলে সাজদাহ করলেন। তিনি পুনরায় মিম্বারে ফিরে আসলেন। তারপর তিনি সালাত শেষ করে লোকের দিকে মুখ করে বললেন, হে লোক সকল! আমি এমন করলাম যাতে তোমরা আমার অনুসরণ করতে পার এবং তোমরা আমার সালাত দেখে তা তোমরা শিখতে পার। সহীহ: বুখারী ৯১৭, মুসলিম ৫৪৪।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Abu Ghuddah</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>739</td></tr><tr><td>Arabic No</td><td>739</td></tr><tr><td>Reference</td><td>Book 8 Hadith 52</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Abu Hazim bin Dinar narrated that some men came to Sahl bin Sa'd As-Sa'idi. They were wondering what kind of wood the Minbar was made of, so they asked him about that. He said:"By Allah, I know what it is made of. I saw it the first day it was set up and the first day the Messenger of Allah (ﷺ) sat on it. The Messenger of Allah (ﷺ) sent word to so-and-so" - a woman whose name Sahl mentioned - "telling her: 'Tell your carpenter slave to make me something of wood that I can sit on when I speak to the people.' So she told him, and he made it from tamarisk wood from Al-Ghabah (a place near Al-Madinah). Then he brought it and it was sent to the Messenger of Allah (ﷺ), who commanded that it be set up here. Then I saw the Messenger of Allah (ﷺ) ascend it and praying on it, and saying the Takbir while he was on top of it, then he bowed when he was on top of it, then he came down backward and prostrated at the base of the Minbar, then he went back. When he had finished he turned to face the people and said: 'O people, I only did this so that you can follow me in prayer and learn how I pray
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Abu Ghuddah</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>739</td></tr><tr><td>Arabic No</td><td>739</td></tr><tr><td>Reference</td><td>Book 8 Hadith 52</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah mengabarkan kepada kami [Qutaibah] dia berkata; telah menceritakan kepada kami [Ya'qub bin 'Abdurrahman] dia berkata; telah menceritakan kepadaku [Abu Hazim bin Dinar] bahwasanya beberapa orang laki-laki mendatangi Sahl bin Sa'd As-Sa'idi dan mereka berdebat tentang kayu yang digunakan untuk membuat mimbar; Mereka bertanya tentang hal itu. [Sahal bin Sa'ad] berkata, "Demi Allah, aku mengetahui jenis kayu yang digunakan untuk membuat mimbar itu. Aku pernah melihat pada hari pembuatannya dan pada hari pertama Rasulullah Shallallahu'alaihi wasallam duduk di atasnya. Rasulullah Shallallahu'alaihi wasallam pernah mengutus seseorang kepada Fulanah -perempuan yang namanya disebutkan oleh Sahal- dan dikatakan kepadanya, 'Suruh budakmu si tukang kayu agar membuatkan kayu-kayu untuk tempat dudukku bila sedang berbicara dengan orang banyak'. Lalu perempuan itu menyuruhnya membuatnya dari kayu hutan. Kemudian orang ini membawanya kepada Rasulullah Shallallahu'alaihi wasallam, dan beliau Shallallahu'alaihi wasallam menyuruhnya meletakkannya di sini. Setelah itu aku melihat Rasulullah Shallallahu'alaihi wasallam naik ke atas mimbar tersebut lalu shalat di atasnya. Beliau bertakbir di atas mimbar kemudian ruku', juga masih di atasnya. Lantas beliau turun sambil mundur, kemudian sujud di dasar mimbar, dan kembali lagi. Setelah selesai shalat beliau menghadap kepada manusia dan bersabda, 'Wahai manusia, aku berbuat demikian agar kalian mengikutiku dan mempelajari shalatku
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Abu Ghuddah</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>739</td></tr><tr><td>Arabic No</td><td>739</td></tr><tr><td>Reference</td><td>Book 8 Hadith 52</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ebû Hazım b. Dinar (radıyallahü anh)’dan rivâyete göre, bazı kimseler, Sehl b. Sa’d es Saidi‘nin yanına gelerek: Medine Mescidindeki Minberin hangi ağaçtan yapıldığında ihtilafa düşüp ona sordular Sehl‘de şunları anlattı: ben minberin hangi ağaçtan yapıldığını biliyorum. Hatta minberin yerine ilk konduğu günü de Rasûlüllah (sallallahü aleyhi ve sellem)’in oturduğu ilk günü de biliyorum. Rasûlüllah (sallallahü aleyhi ve sellem), bir kadına haber göndererek -Ravi Sehl’in o kadının ismini söylediğini fakat bu hadiste geçmediğini söylüyor- (Marangoz olan kölene emret insanlara konuşacağımda üzerine çıkacağım bir yer yapsın.) Bunun üzerine kadın, kölesine; Rasûlüllah (sallallahü aleyhi ve sellem)’in istediğini yapmasını emretti. Köle de ormandaki Tafra denilen ağaçtan isteneni yapıp getirdi. Kadın, bunu alıp Rasûlüllah (sallallahü aleyhi ve sellem)’e gönderdi. Rasûlüllah (sallallahü aleyhi ve sellem)’in emri üzerine bu minber işte şuraya kondu. Sonra Rasûlüllah (sallallahü aleyhi ve sellem) minberin üzerine çıkıp namaz kıldığını gördüm. Tekbir alıp namaza durdu, yine minber üzerinde rükû’a vardı sonra geri geri inerek yere secde etti sonra tekrar minbere çıktı, namazını bitirince insanlara dönerek şöyle buyurdu: insanlar: Benim namaz kıldığımı göresiniz ve bilesiniz ve Bana uyasınız diye böyle yaptım.) (Ebû Dâvûd, Salat: 222; Buhârî, Salat: 64)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Abu Ghuddah</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>739</td></tr><tr><td>Arabic No</td><td>739</td></tr><tr><td>Reference</td><td>Book 8 Hadith 52</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ابوحازم بن دینار کہتے ہیں کہ کچھ لوگ سہل بن سعد ساعدی رضی اللہ عنہ کے پاس آئے وہ لوگ منبر کی لکڑی کے بارے میں بحث کر رہے تھے کہ وہ کس چیز کی تھی؟ ان لوگوں نے سہیل رضی اللہ عنہ اس بارے میں پوچھا، تو انہوں نے کہا: اللہ کی قسم میں خوب جانتا ہوں کہ یہ منبر کس لکڑی کا تھا، میں نے اسے پہلے ہی دن دیکھا تھا جس دن وہ رکھا گیا، اور جس دن رسول صلی اللہ علیہ وسلم پہلے پہل اس پر بیٹھے ( ہوا یوں تھا ) کہ رسول اللہ صلی اللہ علیہ وسلم نے فلاں عورت ( سہل رضی اللہ عنہ نے اس کا نام لیا تھا ) کو کہلوا بھیجا کہ آپ اپنے غلام سے جو بڑھئی ہے کہیں کہ وہ میرے لیے کچھ لکڑیوں کو اس طرح بنا دے کہ جب میں لوگوں کو وعظ و نصیحت کروں تو اس پر بیٹھ سکوں، تو اس عورت نے غلام سے منبر بنانے کے لیے کہہ دیا، چنانچہ غلام نے جنگل کے جھاؤ سے اسے تیار کیا، پھر اسے اس عورت کے پاس لے کر آیا تو اس نے اسے رسول اللہ صلی اللہ علیہ وسلم کے پاس بھیج دیا گیا، آپ صلی اللہ علیہ وسلم کے حکم پر اسے یہاں رکھا گیا، پھر میں نے رسول اللہ صلی اللہ علیہ وسلم کو دیکھا کہ آپ اس پر چڑھے، اور اس پر نماز پڑھی، آپ نے اللہ اکبر کہا، آپ اسی پر تھے، پھر آپ نے رکوع کیا، اور آپ اسی پر تھے، پھر آپ الٹے پاؤں اترے اور منبر کے پایوں کے پاس سجدہ کیا، پھر آپ نے دوبارہ اسی طرح کیا، تو جب آپ فارغ ہو گئے، تو لوگوں کی طرف متوجہ ہوئے اور فرمایا: لوگو! میں نے یہ کام صرف اس لیے کیا ہے تاکہ تم لوگ میری پیروی کر سکو، اور ( مجھ سے ) میری نماز سیکھ سکو ۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Abu Ghuddah</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>739</td></tr><tr><td>Arabic No</td><td>739</td></tr><tr><td>Reference</td><td>Book 8 Hadith 52</td></tr></tbody></table></div>