## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
أَخْبَرَنَا عِيسَى بْنُ حَمَّادٍ، عَنِ اللَّيْثِ، عَنْ سَعِيدٍ، عَنْ شَرِيكِ بْنِ أَبِي نَمِرٍ، أَنَّهُ سَمِعَ أَنَسَ بْنَ مَالِكٍ، يَقُولُ بَيْنَا نَحْنُ جُلُوسٌ فِي الْمَسْجِدِ جَاءَ رَجُلٌ عَلَى جَمَلٍ فَأَنَاخَهُ فِي الْمَسْجِدِ ثُمَّ عَقَلَهُ فَقَالَ لَهُمْ أَيُّكُمْ مُحَمَّدٌ - وَرَسُولُ اللَّهِ صلى الله عليه وسلم مُتَّكِئٌ بَيْنَ ظَهْرَانَيْهِمْ - قُلْنَا لَهُ هَذَا الرَّجُلُ الأَبْيَضُ الْمُتَّكِئُ فَقَالَ لَهُ الرَّجُلُ يَا ابْنَ عَبْدِ الْمُطَّلِبِ ‏.‏ فَقَالَ لَهُ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏"‏ قَدْ أَجَبْتُكَ ‏"‏ ‏.‏ فَقَالَ الرَّجُلُ إِنِّي سَائِلُكَ يَا مُحَمَّدُ فَمُشَدِّدٌ عَلَيْكَ فِي الْمَسْأَلَةِ فَلاَ تَجِدَنَّ فِي نَفْسِكَ ‏.‏ قَالَ ‏"‏ سَلْ مَا بَدَا لَكَ ‏"‏ ‏.‏ فَقَالَ الرَّجُلُ نَشَدْتُكَ بِرَبِّكَ وَرَبِّ مَنْ قَبْلَكَ آللَّهُ أَرْسَلَكَ إِلَى النَّاسِ كُلِّهِمْ فَقَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏"‏ اللَّهُمَّ نَعَمْ ‏"‏ ‏.‏ قَالَ فَأَنْشُدُكَ اللَّهَ آللَّهُ أَمَرَكَ أَنْ تُصَلِّيَ الصَّلَوَاتِ الْخَمْسَ فِي الْيَوْمِ وَاللَّيْلَةِ قَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏"‏ اللَّهُمَّ نَعَمْ ‏"‏ ‏.‏ قَالَ فَأَنْشُدُكَ اللَّهَ آللَّهُ أَمَرَكَ أَنْ تَصُومَ هَذَا الشَّهْرَ مِنَ السَّنَةِ قَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏"‏ اللَّهُمَّ نَعَمْ ‏"‏ ‏.‏ قَالَ فَأَنْشُدُكَ اللَّهَ آللَّهُ أَمَرَكَ أَنْ تَأْخُذَ هَذِهِ الصَّدَقَةَ مِنْ أَغْنِيَائِنَا فَتَقْسِمَهَا عَلَى فُقَرَائِنَا فَقَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏"‏ اللَّهُمَّ نَعَمْ ‏"‏ ‏.‏ فَقَالَ الرَّجُلُ آمَنْتُ بِمَا جِئْتَ بِهِ وَأَنَا رَسُولُ مَنْ وَرَائِي مِنْ قَوْمِي وَأَنَا ضِمَامُ بْنُ ثَعْلَبَةَ أَخُو بَنِي سَعْدِ بْنِ بَكْرٍ ‏.‏ خَالَفَهُ يَعْقُوبُ بْنُ إِبْرَاهِيمَ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Abu Ghuddah</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2092</td></tr><tr><td>Arabic No</td><td>2092</td></tr><tr><td>Reference</td><td>Book 22 Hadith 3</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>

</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Abu Ghuddah</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2092</td></tr><tr><td>Arabic No</td><td>2092</td></tr><tr><td>Reference</td><td>Book 22 Hadith 3</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
It was narrated that Anas bin Malik said:"While we were sitting in the Masjid, a man came on a camel and made it keneel in the Masjid, then he hobbled it and said to them: 'Which of you is Muhammad?' The Messenger of Allah was reclining amid his Companions, and we said to him: This white man who is reclining.' The man said to him: 'O son of 'Abdul-Muttalib.' The Messenger of Allah said: ' I have answered you.' The man said; 'O Muhammad, I am going to ask you questions, and I will be harsh in asking; do not get upset.; The man said: 'I adjure you by your Lord and the Lord of those who cam before you, has Allah sent you to all the people?' The Messenger of Allah said: 'By Allah, yes.' He said; 'I adjure you by Allah, has Allah commanded you to offer five prayers each day and night?' The Messenger of Allah said: 'By Allah, yes.; He said: 'I adjure you by Allah, has Allah commanded you to fast this month each year? The Messenger of Allah said: 'By Allah, Yes.' He said: 'I adjure you by Allah, has Allah commanded you to take this charity from our rich and distribute it among our poor?' The Messenger of Allah said. 'By Allah, yes.' The man said: 'I believe in that which you have brought, and I am the envoy of my people who are coming after me. I am Dimam bin Thalabah, the brother of Banu sad bin Bakr."' Yaqub bin Ibrahim contradicted him
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Abu Ghuddah</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2092</td></tr><tr><td>Arabic No</td><td>2092</td></tr><tr><td>Reference</td><td>Book 22 Hadith 3</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah mengabarkan kepada kami ['Isa bin Hammad] dari [Al Laits] dari [Sa'id] dari [Syarik bin Abu Namir] bahwasanya dia mendengar [Anas bin Malik] berkata; "Ketika kami sedang duduk di masjid, datanglah seseorang dengan menaiki seekor unta, ia menderumkannya di masjid, kemudian mengikatnya lalu bertanya kepada mereka, "Manakah di antara kalian yang bernama Muhammad?" padahal Rasulullah shallallahu 'alaihi wasallam sedang bersandar di antara mereka. Kami berkata kepadanya; "Orang putih yang sedang bersandar ini." Orang tersebut berkata kepada beliau; "Wahai anak Abdul Muththallib." Maka Rasulullah shallallahu 'alaihi wasallam bersabda: "Aku telah menjawab panggilanmu." Orang itu berkata; "Sungguh aku akan bertanya kepadamu wahai Muhammad, dan mendesakmu dalam bertanya, maka janganlah engkau marah! Beliau bersabda: "Tanyakanlah apa yang terlintas dalam pikiranmu." Lalu orang itu bertanya; "Aku bersumpah atas nama Rabbmu dan Rabb orang-orang sebelum kamu, apakah Allah telah mengutusmu kepada seluruh manusia?" maka Rasulullah shallallahu 'alaihi wasallam menjawab: "Ya Allah, ya." Ia bertanya, "Aku bersumpah atas nama Allah, apakah Allah telah memerintahkanmu untuk mengerjakan shalat lima waktu dalam sehari semalam? Rasulullah shallallahu 'alaihi wasallam menjawab: "Ya Allah, ya." Ia bertanya; "Aku bersumpah atas nama Allah, apakah Allah telah memerintahkanmu untuk berpuasa pada bulan ini setiap tahun." Rasulullah shallallahu 'alaihi wasallam menjawab: "Ya Allah, Ya." Ia bertanya; "Aku bersumpah atas nama Allah, apakah Allah telah memerintahkanmu untuk mengambil zakat ini dari orang-orang kaya di antara kami, lalu dibagikan kepada orang-orang fakir di antara kami? Rasulullah shallallahu 'alaihi wasallam menjawab: "Ya Allah, Ya." Orang itu berkata; "Aku beriman dengan apa yang telah engkau bawa dan aku adalah utusan kaumku yang mereka berada di belakangku. Aku adalah Dhimam bin Tsa'labah berasal dari Bani Sa'd bin Bakr." Ya'qub bin Ibrahim menyelisihi Hadits ini
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Abu Ghuddah</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2092</td></tr><tr><td>Arabic No</td><td>2092</td></tr><tr><td>Reference</td><td>Book 22 Hadith 3</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>

</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Abu Ghuddah</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2092</td></tr><tr><td>Arabic No</td><td>2092</td></tr><tr><td>Reference</td><td>Book 22 Hadith 3</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
انس بن مالک رضی الله عنہ کہتے ہیں: ہم مسجد میں بیٹھے تھے کہ اسی دوران ایک شخص اونٹ پر آیا، اسے مسجد میں بٹھایا پھر اسے باندھا، ( اور ) لوگوں سے پوچھا: تم میں محمد کون ہیں؟ اور رسول اللہ صلی اللہ علیہ وسلم ان کے درمیان ٹیک لگائے بیٹھے تھے۔ تو ہم نے اس سے کہا: یہ گورے چٹے آدمی ہیں، جو ٹیک لگائے بیٹھے ہیں، آپ کو پکار کر اس شخص نے کہا: اے عبدالمطلب کے بیٹے! تو رسول اللہ صلی اللہ علیہ وسلم نے اس سے فرمایا: ”میں نے تمہاری بات سن لی“ ( کہو کیا کہنا چاہتے ہو ) اس نے کہا: محمد! میں آپ سے کچھ پوچھنے والا ہوں، ( اور ذرا ) سختی سے پوچھوں گا تو آپ دل میں کچھ محسوس نہ کریں، آپ نے فرمایا: ”پوچھو جو چاہتے ہو“، تو اس نے کہا: میں آپ کو آپ کے، اور آپ سے پہلے ( جو گزر چکے ہیں ) ان کے رب کی قسم دلاتا ہوں! کیا اللہ تعالیٰ نے آپ کو تمام لوگوں کی طرف ( رسول بنا کر ) بھیجا ہے؟ تو رسول اللہ صلی اللہ علیہ وسلم نے کہا: ”اے اللہ! ( میری بات پر گواہ رہنا ) ہاں“، ( پھر ) اس نے کہا: میں اللہ کی قسم دلاتا ہوں! کیا اللہ تعالیٰ نے آپ کو دن اور رات میں پانچ ( وقت کی ) نماز پڑھنے کا حکم دیا ہے؟ تو رسول اللہ صلی اللہ علیہ وسلم نے فرمایا: ”اے اللہ! ( گواہ رہنا ) ہاں“، ( پھر ) اس نے کہا: میں آپ کو اللہ کی قسم دلاتا ہوں! کیا اللہ تعالیٰ نے آپ کو سال کے اس ماہ میں روزے رکھنے کا حکم دیا ہے؟ تو رسول اللہ صلی اللہ علیہ وسلم نے فرمایا: ”اے اللہ! ( گواہ رہنا ) ہاں،“ ( پھر ) اس نے کہا: میں آپ کو اللہ کی قسم دلاتا ہوں! اللہ تعالیٰ نے آپ کو مالداروں سے زکاۃ لے کر غریبوں میں تقسیم کرنے کا حکم دیا ہے؟ تو رسول اللہ صلی اللہ علیہ وسلم نے کہا: ”اے اللہ! ( گواہ رہنا ) ہاں“، تب ( اس ) شخص نے کہا: میں آپ کی لائی ہوئی ( شریعت ) پر ایمان لایا، میں اپنی قوم کا جو میرے پیچھے ہیں قاصد ہوں، اور میں قبیلہ بنی سعد بن بکر کا فرد ضمام بن ثعلبہ ہوں۔ یعقوب بن ابراہیم نے حماد بن عیسیٰ کی مخالفت کی ہے ۱؎۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Abu Ghuddah</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2092</td></tr><tr><td>Arabic No</td><td>2092</td></tr><tr><td>Reference</td><td>Book 22 Hadith 3</td></tr></tbody></table></div>