## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا عَبْدُ اللَّهِ بْنُ عَبْدِ الرَّحْمَنِ، أَخْبَرَنَا عَمْرُو بْنُ عَوْنٍ، أَخْبَرَنَا خَالِدُ بْنُ عَبْدِ اللَّهِ، عَنْ سُهَيْلٍ، عَنْ أَبِيهِ، عَنْ أَبِي هُرَيْرَةَ، رضى الله عنه قَالَ كَانَ رَسُولُ اللَّهِ صلى الله عليه وسلم يَأْمُرُنَا إِذَا أَخَذَ أَحَدُنَا مَضْجَعَهُ أَنْ يَقُولَ ‏ "‏ اللَّهُمَّ رَبَّ السَّمَوَاتِ وَرَبَّ الأَرَضِينَ وَرَبَّنَا وَرَبَّ كُلِّ شَيْءٍ وَفَالِقَ الْحَبِّ وَالنَّوَى وَمُنْزِلَ التَّوْرَاةِ وَالإِنْجِيلِ وَالْقُرْآنِ أَعُوذُ بِكَ مِنْ شَرِّ كُلِّ ذِي شَرٍّ أَنْتَ آخِذٌ بِنَاصِيَتِهِ أَنْتَ الأَوَّلُ فَلَيْسَ قَبْلَكَ شَيْءٌ وَأَنْتَ الآخِرُ فَلَيْسَ بَعْدَكَ شَيْءٌ وَالظَّاهِرُ فَلَيْسَ فَوْقَكَ شَيْءٌ وَالْبَاطِنُ فَلَيْسَ دُونَكَ شَيْءٌ اقْضِ عَنِّي الدَّيْنَ وَأَغْنِنِي مِنَ الْفَقْرِ ‏"‏ ‏.‏ قَالَ أَبُو عِيسَى هَذَا حَدِيثٌ حَسَنٌ صَحِيحٌ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3400</td></tr><tr><td>Arabic No</td><td>3400</td></tr><tr><td>Reference</td><td>Book 48 Hadith 31</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
৩৪০০। আবূ হুরাইরাহ (রাযিঃ) হতে বর্ণিত আছে, তিনি বলেন, আমাদেরকে রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এই মর্মে হুকুম করতেন যে, আমাদের কেউ ঘুমানোর জন্য যখন বিছানাগত হয় সে সময় সে যেন বলেঃ “হে আল্লাহ! আকাশমণ্ডলীর প্রভু, মাটিসমূহের প্রভু, আমাদের প্রভু, প্রতিটি বস্তুর প্রভু, শস্যবীজ ও আঁটির অংকুরোদগমনকারী এবং তাওরাত, ইনজীল ও কুরআন অবতীর্ণকারী! আমি প্রত্যেক অনিষ্টকারীর ক্ষতি হতে তোমার কাছে আশ্রয় প্রার্থনা করি। এগুলো তোমারই আয়ত্তাধীন, তুমিই শুরু, তোমার আগে কিছুই নেই। আর তুমিই শেষ, তোমার পরে কিছুই নেই। তুমিই প্রকাশিত, তোমার উপরে কিছুই নেই। তুমিই লুকায়িত, তোমার হতে কিছুই গোপন নয়। সুতরাং তুমি আমার ঋণ পরিশোধের ব্যবস্থা করে দাও এবং দরিদ্রতা হতে আমাকে সাবলম্বী করে দাও"। সহীহঃ আল-কালিমুত তাইয়্যিব (হাঃ ৪০), মুসলিম। আবূ ঈসা বলেন, হাদীসটি হাসান সহীহ।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3400</td></tr><tr><td>Arabic No</td><td>3400</td></tr><tr><td>Reference</td><td>Book 48 Hadith 31</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Abu Hurairah (ra) said:“The Messenger of Allah (ﷺ) used to order that when one of us went to sleep, he should say: ‘O Allah, Lord of the heavens and Lord of the earths, and our Lord, and the Lord of everything, splitter of the seed-grain and date-stone, and Revealer of the Tawrah and the Injil and the Qur’an. I seek refuge in You from the evil of every evil that You are holding by the forelock. You are the First, there is nothing before You, You are the Last, there is nothing after You, and Az-Zahir, there is nothing above you, and Al-Batin, there is nothing below You. Relieve me of my debt, and enrich me from poverty (Allāhumma rabbas-samāwati wa rabbal-arḍīna wa rabbanā, wa rabba kulli shai’in, fāliqal-ḥabbi wan-nawā, wa munzilat-Tawrāti wal-Injīli wal-Qur’ān. A'ūdhu bika sharri kulli dhi sharrin anta ākhidhun bināṣiyatihi, antal-Awwalu falaisa qablaka shai’un, wa antal-Ākhiru falaisa ba'daka shai’un, waẓ-Ẓāhiru falaisa fauqaka shai'un wal-Bātinu falaisa dūnaka shai’un, iqḍi 'annid-daina wa aghninī minal-faqr).’”
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3400</td></tr><tr><td>Arabic No</td><td>3400</td></tr><tr><td>Reference</td><td>Book 48 Hadith 31</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Abdullah bin Abdur Rahman] telah mengabarkan kepada kami ['Amru bin 'Aun] telah mengabarkan kepada kami [Khalid bin Abdullah]? dari [Suhail]? dari [ayahnya]? dari [Abu Hurairah? radliallahu 'anhu]? ia berkata;? Rasulullah shallallahu 'alaihi wasallam memerintahkan kami apabila salah seorang diantara kami hendak tidur untuk mengucapkan; ALLAAHUMMA RABBAS SAMAAWAATI WA RABBAL ARADHIINA WA RABBANAA WA RABBA KULLI SYAI-IN WA FAALIQAL HABBI WAN NAWAA, WA MUNZILAT TAURAATI WAL INJIILI WAL QUR'AAN, A'UUDZU BIKA MIN SYARRI KULLI DZII SYARRIN ANTA AAKHIDZUN BINAASHIYATIHI., ANTAL AWWALU FALAISA QABLAKA SYAIUN WA ANTAL AAKHIRU FALAISA BA'DAKA SYAIUN WAZHZHAAHIRU FALAISA FAUQAKA SYAIUN WAL BAATHINU FALAISA DUUNAKA SYAIUN. IQDHI 'ANNID DAINA WA AGHNINII MINAL FAQRI. (Wahai Tuhan langit yang tujuh dan 'arsy yang agung, Tuhan kami dan Tuhan kami serta Tuhan segala sesuatu, Yang menumbuhkan butir tumbuh-tumbuhan dan biji buah-buahan, Yang menurunkan Taurat dan Injil serta Al Qur'an. Aku berlindung kepadaMu dari segala keburukan segala sesuatu yang memiliki keburukan, Engkau Yang memegang jambulnya, Engkau adalah Al Awwal tidak ada sesuatu sebelumMu dan Engkau adalah Al Akhir, Yang tidak ada sesuatu pun setelahMu, dan Azh Zhahir, tidak ada sesuatu pun di atasMu, serta Al Bathin, Yang tidak ada sesuatu pun di bawahMu, tunaikanlah hutangku dan cukupkanlah aku dari kefakiran) Abu Isa berkata; hadits ini adalah hadits hasan shahih
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3400</td></tr><tr><td>Arabic No</td><td>3400</td></tr><tr><td>Reference</td><td>Book 48 Hadith 31</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ebû Hureyre (r.a.)’den rivâyete göre, şöyle demiştir: Rasûlullah (s.a.v.): Herhangi birimiz yatacağında bize şöyle dememizi emrederdi: “Allah’ım Ey göklerin ve yerlerin Rabbi, bizim ve her şeyin rabbi, taneyi ve çekirdeği yaran, Tevrat’ı, İncil’i ve Kur’ân’ı indiren! Her şerlinin şerrinden sana sığınırım ki her şeyin iradesi senin elindedir. Önce sensin senden önce hiçbir varlık yoktur. Ahir olan sensinsenden sonra hiçbir varlık yoktur. Zahir olan sensin senin üzerinde hiçbir varlık yoktur. Bâtın sensin senin ötende hiçbir şey yoktur. Benim borçlarımı ödettir ve beni fakirlikten kurtar.”
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3400</td></tr><tr><td>Arabic No</td><td>3400</td></tr><tr><td>Reference</td><td>Book 48 Hadith 31</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ابوہریرہ رضی الله عنہ کہتے ہیں کہ رسول اللہ صلی اللہ علیہ وسلم ہمیں حکم دیتے تھے کہ جب ہم میں سے کوئی اپنے بستر پر سونے کے لیے جائے تو کہے: «اللهم رب السموات ورب الأرضين وربنا ورب كل شيء وفالق الحب والنوى ومنزل التوراة والإنجيل والقرآن أعوذ بك من شر كل ذي شر أنت آخذ بناصيته أنت الأول فليس قبلك شيء وأنت الآخر فليس بعدك شيء والظاهر فليس فوقك شيء والباطن فليس دونك شيء اقض عني الدين وأغنني من الفقر» ”اے آسمانوں اور زمینوں کے رب! اے ہمارے رب! اے ہر چیز کے رب! زمین چیر کر دانے اور گٹھلی سے پودے اگانے والے، توراۃ، انجیل اور قرآن نازل کرنے والے، اے اللہ! میں تیری پناہ چاہتا ہوں ہر شر والی چیز کے شر سے، تو ہی ہر شر و فساد کی پیشانی اپنی گرفت میں لے سکتا ہے۔ تو ہی سب سے پہلے ہے تجھ سے پہلے کوئی چیز نہیں ہے، تو ہی سب سے آخر ہے، تیرے بعد کوئی چیز نہیں ہے، تو سب سے ظاہر ( اوپر ) ہے تیرے اوپر کوئی چیز نہیں ہے، تو باطن ( نیچے و پوشیدہ ) ہے تیرے سے نیچے کوئی چیز نہیں ہے، مجھ پر جو قرض ہے اسے تو ادا کر دے اور تو مجھے محتاجی سے نکال کر غنی کر دے“۔ امام ترمذی کہتے ہیں: یہ حدیث حسن صحیح ہے۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3400</td></tr><tr><td>Arabic No</td><td>3400</td></tr><tr><td>Reference</td><td>Book 48 Hadith 31</td></tr></tbody></table></div>