## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا أَبُو كُرَيْبٍ، حَدَّثَنَا وَكِيعٌ، عَنْ هِشَامٍ الدَّسْتَوَائِيِّ، عَنْ قَتَادَةَ، عَنْ أَبِي حَسَّانَ الأَعْرَجِ، عَنِ ابْنِ عَبَّاسٍ، أَنَّ النَّبِيَّ صلى الله عليه وسلم قَلَّدَ نَعْلَيْنِ وَأَشْعَرَ الْهَدْىَ فِي الشِّقِّ الأَيْمَنِ بِذِي الْحُلَيْفَةِ وَأَمَاطَ عَنْهُ الدَّمَ ‏.‏ قَالَ وَفِي الْبَابِ عَنِ الْمِسْوَرِ بْنِ مَخْرَمَةَ ‏.‏ قَالَ أَبُو عِيسَى حَدِيثُ ابْنِ عَبَّاسٍ حَدِيثٌ حَسَنٌ صَحِيحٌ ‏.‏ وَأَبُو حَسَّانَ الأَعْرَجُ اسْمُهُ مُسْلِمٌ ‏.‏ وَالْعَمَلُ عَلَى هَذَا عِنْدَ أَهْلِ الْعِلْمِ مِنْ أَصْحَابِ النَّبِيِّ صلى الله عليه وسلم وَغَيْرِهِمْ يَرَوْنَ الإِشْعَارَ ‏.‏ وَهُوَ قَوْلُ الثَّوْرِيِّ وَالشَّافِعِيِّ وَأَحْمَدَ وَإِسْحَاقَ ‏.‏ قَالَ أَبُو عِيسَى سَمِعْتُ يُوسُفَ بْنَ عِيسَى يَقُولُ سَمِعْتُ وَكِيعًا يَقُولُ حِينَ رَوَى هَذَا الْحَدِيثَ قَالَ لاَ تَنْظُرُوا إِلَى قَوْلِ أَهْلِ الرَّأْىِ فِي هَذَا فَإِنَّ الإِشْعَارَ سُنَّةٌ وَقَوْلَهُمْ بِدْعَةٌ ‏.‏ قَالَ وَسَمِعْتُ أَبَا السَّائِبِ يَقُولُ كُنَّا عِنْدَ وَكِيعٍ فَقَالَ لِرَجُلٍ عِنْدَهُ مِمَّنْ يَنْظُرُ فِي الرَّأْىِ أَشْعَرَ رَسُولُ اللَّهِ صلى الله عليه وسلم وَيَقُولُ أَبُو حَنِيفَةَ هُوَ مُثْلَةٌ ‏.‏ قَالَ الرَّجُلُ فَإِنَّهُ قَدْ رُوِيَ عَنْ إِبْرَاهِيمَ النَّخَعِيِّ أَنَّهُ قَالَ الإِشْعَارُ مُثْلَةٌ ‏.‏ قَالَ فَرَأَيْتُ وَكِيعًا غَضِبَ غَضَبًا شَدِيدًا وَقَالَ أَقُولُ لَكَ قَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم وَتَقُولُ قَالَ إِبْرَاهِيمُ مَا أَحَقَّكَ بِأَنْ تُحْبَسَ ثُمَّ لاَ تَخْرُجَ حَتَّى تَنْزِعَ عَنْ قَوْلِكَ هَذَا ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih Bukhari And Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>906</td></tr><tr><td>Arabic No</td><td>906</td></tr><tr><td>Reference</td><td>Book 9 Hadith 99</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
৯০৬। ইবনু আব্বাস (রাঃ) হতে বর্ণিত আছে, যুল-হুলাইফা নামক জায়গায় রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম কুরবানীর পশুর গলায় একজোড়া জুতা বুলিয়ে দিলেন এবং এর কুঁজের ডান দিকে চিরে রক্ত প্রবাহিত করলেন। — সহীহ, ইবনু মা-জাহ (৩০৯৭), মুসলিম মিসওয়ার ইবনু মাখরামা (রাঃ) হতেও এই অনুচ্ছেদে হাদীস বর্ণিত আছে। এই হাদীসটিকে আবু ঈসা হাসান সহীহ বলেছেন। আবু হাসসান আল-আরাজের নাম মুসলিম। এই হাদীস অনুযায়ী রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লামের সাহাবী ও অন্যান্য আলিমগণ আমল করেছেন। কুরবানীর উট বা গরুর কুজের ডান বা বাম দিক দিয়ে চিরে দেয়া তাদের মতে সুন্নাত। এই অভিমত সাওরী, শাফিঈ, আহমাদ ও ইসহাক (রাহঃ)-এর। ইউসুফ ইবনু ঈসা বলেন, এই হাদীস বর্ণনার সময় আমি ওয়াকীকে বলতে শুনেছি, আহলুর রায়ের কথার প্রতি এই বিষয়ে ক্ৰক্ষেপ করবে না। কারণ, কুঁজ চিরা হলো সুন্নাত এবং আহলুর রায়ের কথা হলো বিদ’আত। আমি আবুস সাইবকে বলতে শুনেছি, আমরা ওয়াকীর নিকট বসা ছিলাম। একজন আহলুর রায়কে লক্ষ্য করে তিনি বললেন, রাসুলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম কুরবানীর পশুর কুঁজ চিরেছেন। আর আবু হানীফা বলেন যে, তা মুসলা বা অঙ্গ বিকৃতকরণ। ঐ ব্যক্তি বলল, ইবরাহীম নাখঈ বলেছেন, এটা হলো মুসলা। আবুস সাঈব বলেন, আমি দেখতে পেলাম ওয়াকী ভীষণভাবে রেগে গেলেন এবং বললেন, আমি বলছি রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেছেন, আর তুমি বলছ ইবরাহীম বলেছেন। তোমাকে কারারুদ্ধ করা উচিত। তুমি যে পর্যন্ত না এই বক্তব্য প্রত্যাহার করছ সে পর্যন্ত তোমাকে কারামুক্ত করা অনুচিত।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih Bukhari And Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>906</td></tr><tr><td>Arabic No</td><td>906</td></tr><tr><td>Reference</td><td>Book 9 Hadith 99</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ibn Abbas narrated:"The Prophet garlanded two sandals and marked the Hadi on the right side at Dhul-Hulaifah, and removed the blood from it
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih Bukhari And Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>906</td></tr><tr><td>Arabic No</td><td>906</td></tr><tr><td>Reference</td><td>Book 9 Hadith 99</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Abu Kuraib], telah menceritakan kepada kami [Waki'] dari [Hisyam Ad Dastuwa'i] dari [Qatadah] dari [Abu Hassan Al A'raj] dari [Ibnu Abbas] bahwa Nabi shallallahu 'alaihi wasallam mengalungkan sepasang sandal pada badan hewan sembelihan yang sebelah kanan dan dan memberi tanda hewan kurbannya di Dzul Hulaifah. Beliau juga menghilangkan darah dari hewan itu. (Abu Isa At Tirmidzi) berkata; "Hadits semakna diriwayatkan dari Al Miswar bin Makhramah." Abu 'Isa berkata; "Hadits Ibnu Abbas merupakan hadits hasan shohih dan Abu Al Hasan Al 'Araj bernama Muslim. Hadits ini diamalkan oleh para ulama dari kalangan sahabat Nabi shallallahu 'alaihi wasallam dan yang lainnya. Mereka berpendapat disunnahkannya untuk memberi tanda pada hewan sembelihan, ini juga merupakan pendapat Ats Tsauri, Syafi'i, Ahmad dan Ishaq. (Abu Isa At Tirmidzi) berkata; "Saya telah mendengar Yusuf bin 'Isa berkata; Saya mendengar Waki' berkomentar ketika meriwayatkan hadits ini; 'Jangan kalian mendengar perkataan orang yang berpegang pada akal dalam masalah ini. Memberi tanda pada hewan ialah sunnah dan pendapat mereka ialah bid'ah'." (Abu Isa At Tirmidzi) berkata; "Saya telah mendengar Abu Sa'ib berkata; Tatkala kami bersama Waki', dia berkata kepada seseorang di dekatnya yang berpegang pada akal bahwa Rasulullah shallallahu 'alaihi wasallam memberi tanda pada hewan, sedangkan Abu Hanifah mengatakan; itu merupakan bentuk penganiayaan kepada hewan. Orang itu berkata; hal itu telah diriwayatkan dari Ibrahim An Nakha'i bahwa dia mengatakan; memberi tanda pada hewan merupakan bentuk penganiayaan. Abu Sa'ib berkata; 'Lalu saya melihat Waki' menjadi sangat marah sambil berkata; Saya sampaikan sabda Rasulullah shallallahu 'alaihi wasallam, engkau malah membantah dengan perkataan Ibrahim. Sungguh engkau pantas untuk dipenjara dan tidak dikeluarkan sampai kamu menarik ucapanmu ini
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih Bukhari And Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>906</td></tr><tr><td>Arabic No</td><td>906</td></tr><tr><td>Reference</td><td>Book 9 Hadith 99</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
İbn Abbâs (r.a.)’den rivâyete göre, şöyle demiştir: “Rasûlullah (s.a.v.), kurban edeceği hayvanın boynuna iki takunya takmış Zu’l-huleyfe denilen yerde hayvan’ın sağ tarafına kurbanlık olduğunu belirtmek için yararak kan akıttı ve kan izlerini de silip yok etti.” Diğer tahric: Müslim, Hac; Buhârî, Hac Tirmîzî: Bu konuda Misver b. Mahreme’den de hadis rivâyet edilmiştir. Tirmîzî: İbn Abbâs hadisi hasen sahihtir. Ebû Hassân el A’rec’in adı Müslim’dir. Rasûlullah (s.a.v.)’in ashabından ve sonraki dönemlerden ilim adamları bu hadisle amel ederler, kurbanlık hayvanların işaretlenmesi görüşündedirler. Sevrî, Şâfii, Ahmed ve İshâk’ın görüşleri böyledir. Yusuf b. İsa’dan işittim Vekî’den işittiğini söylüyordu bu hadisi rivâyet edince şöyle dedi: Bu konuda kendi görüşlerine iltifat etmeyin! Çünkü kurbanlık hayvanı işaretlemek sünnet onların sözleri ise bidattır. Ebû’s Sâib’den işittim şöyle diyordu: Vekî’nin yanında idik Vekî’ kendi görüşlerine göre konuşanlardan birine dedi ki: Rasûlullah (s.a.v.) kurbanlık develere işaret koymak üzere hayvanı yaraladı. Ebû Hanife ise bu işe “Müsle” yapmaktır diyor. O adamda bu mesele İbrahim Nehai’den rivâyet edilmiştir. O der ki: Kurbanlık hayvana işaret koymak müsle yapmak demektir. Bu söz üzerine Vekî’ çok şiddetli bir şekilde kızdı ve şöyle dedi: Ben sana Peygamber (s.a.v.) söyledi diyorum sen bana İbrahim söyledi diyorsun, bu sözünden vazgeçinceye kadar hapsedilmeyi nasılda hak etmişsin
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih Bukhari And Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>906</td></tr><tr><td>Arabic No</td><td>906</td></tr><tr><td>Reference</td><td>Book 9 Hadith 99</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
عبداللہ بن عباس رضی الله عنہما سے روایت ہے کہ اکرم صلی اللہ علیہ وسلم نے ذو الحلیفہ میں ( ہدی کے جانور کو ) دو جوتیوں کے ہار پہنائے اور ان کی کوہان کے دائیں طرف اشعار ۱؎ کیا اور اس سے خون صاف کیا۔ امام ترمذی کہتے ہیں: ۱- ابن عباس رضی الله عنہما کی حدیث حسن صحیح ہے، ۲- صحابہ کرام رضی الله عنہم وغیرہم میں سے اہل علم کا اسی پر عمل ہے، وہ اشعار کے قائل ہیں۔ یہی ثوری، شافعی، احمد اور اسحاق بن راہویہ کا قول ہے، ۳- یوسف بن عیسیٰ کہتے ہیں کہ میں نے وکیع کو کہتے سنا جس وقت انہوں نے یہ حدیث روایت کی کہ اس سلسلے میں اہل رائے کے قول کو نہ دیکھو، کیونکہ اشعار سنت ہے اور ان کا قول بدعت ہے، ۴- میں نے ابوسائب کو کہتے سنا کہ ہم لوگ وکیع کے پاس تھے تو انہوں نے اپنے پاس کے ایک شخص سے جو ان لوگوں میں سے تھا جو رائے میں غور و فکر کرتے ہیں کہا کہ رسول اللہ صلی اللہ علیہ وسلم نے اشعار کیا ہے، اور ابوحنیفہ کہتے ہیں کہ وہ مثلہ ہے تو اس آدمی نے کہا: ابراہیم نخعی سے مروی ہے انہوں نے بھی کہا ہے کہ اشعار مثلہ ہے، ابوسائب کہتے ہیں: تو میں نے وکیع کو دیکھا کہ ( اس کی اس بات سے ) وہ سخت ناراض ہوئے اور کہا: میں تم سے کہتا ہوں کہ ”رسول اللہ صلی اللہ علیہ وسلم نے فرمایا ہے“ اور تم کہتے ہو: ابراہیم نے کہا: تم تو اس لائق ہو کہ تمہیں قید کر دیا جائے پھر اس وقت تک قید سے تمہیں نہ نکالا جائے جب تک کہ تم اپنے اس قول سے باز نہ آ جاؤ ۲؎۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih Bukhari And Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>906</td></tr><tr><td>Arabic No</td><td>906</td></tr><tr><td>Reference</td><td>Book 9 Hadith 99</td></tr></tbody></table></div>