## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا هَنَّادٌ، حَدَّثَنَا أَبُو مُعَاوِيَةَ، عَنِ الأَعْمَشِ، عَنْ عَبْدِ اللَّهِ بْنِ عَبْدِ اللَّهِ الرَّازِيِّ، عَنْ عَبْدِ الرَّحْمَنِ بْنِ أَبِي لَيْلَى، عَنِ الْبَرَاءِ بْنِ عَازِبٍ، قَالَ سُئِلَ رَسُولُ اللَّهِ صلى الله عليه وسلم عَنِ الْوُضُوءِ مِنْ لُحُومِ الإِبِلِ فَقَالَ ‏"‏ تَوَضَّئُوا مِنْهَا ‏"‏ ‏.‏ وَسُئِلَ عَنِ الْوُضُوءِ مِنْ لُحُومِ الْغَنَمِ فَقَالَ ‏"‏ لاَ تَتَوَضَّئُوا مِنْهَا ‏"‏ ‏.‏ قَالَ وَفِي الْبَابِ عَنْ جَابِرِ بْنِ سَمُرَةَ وَأُسَيْدِ بْنِ حُضَيْرٍ ‏.‏ قَالَ أَبُو عِيسَى وَقَدْ رَوَى الْحَجَّاجُ بْنُ أَرْطَاةَ هَذَا الْحَدِيثَ عَنْ عَبْدِ اللَّهِ بْنِ عَبْدِ اللَّهِ عَنْ عَبْدِ الرَّحْمَنِ بْنِ أَبِي لَيْلَى عَنْ أُسَيْدِ بْنِ حُضَيْرٍ ‏.‏ وَالصَّحِيحُ حَدِيثُ عَبْدِ الرَّحْمَنِ بْنِ أَبِي لَيْلَى عَنِ الْبَرَاءِ بْنِ عَازِبٍ ‏.‏ وَهُوَ قَوْلُ أَحْمَدَ وَإِسْحَاقَ ‏.‏ وَهُوَ قَوْلُ أَحْمَدَ وَإِسْحَاقَ وَقَدْ رُوِيَ عَنْ بَعْضِ أَهْلِ الْعِلْمِ مِنَ التَّابِعِينَ وَغَيْرِهِمْ أَنَّهُمْ لَمْ يَرَوُا الْوُضُوءَ مِنْ لُحُومِ الإِبِلِ وَهُوَ قَوْلُ سُفْيَانَ الثَّوْرِيِّ وَأَهْلِ الْكُوفَةِ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>81</td></tr><tr><td>Arabic No</td><td>81</td></tr><tr><td>Reference</td><td>Book 1 Hadith 81</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
৮১। বারাআ ইবনু আযিব (রাঃ) হতে বর্ণিত আছে, তিনি বলেন, উটের গোশত খেলে আবার ওযু করতে হবে কি না এ সম্পর্কে রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লামকে প্রশ্ন করা হল। তিনি বললেনঃ উটের গোশত খাওয়ার পর ওযু কর। তাকে আবার বকরীর গোশত খেলে ওযু করতে হবে কি না এ সম্পর্কে প্রশ্ন করা হল। তিনি বললেন এতে (বকরীর গোশত খেলে) তোমরা ওযু করো না। -সহীহ। ইবনু মাজাহ– (৪৯৪)। এ অনুচ্ছেদে জাবির ইবনু সামুরা ও উসাইদ ইবনু হুযাইর (রাঃ) হতে বর্ণনা করা হাদীসও রয়েছে। আবু ঈসা বলেনঃ হাজ্জাজ ইবনু আরতাত তার সনদ পরম্পরায় এ হাদীসটি উসাইদ ইবনু হুযাইর (রাঃ)-এর সূত্রে বর্ণনা করেছেন। তবে বারাআ ইবনু আযিব (রাঃ)-এর সূত্রে বর্ণনাকৃত হাদীসটি সহীহ। এ হাদীসটি উবাইদাহ যাববী বর্ণনা করেছেন আব্দুল্লাহ ইবনু আব্দিল্লাহ আলরাজী হতে তিনি আব্দুর রহমান ইবনু আবী লাইলা হতে, তিনি জিল গুররাহ জুহানী হতে। আর হাম্মাদ ইবনু সালামা হাদীসটি বর্ণনা করেছেন হাজ্জাজ ইবনু আরতাহ হতে। তিনি ভুলবশতঃ বলেছেন, আব্দুল্লাহ ইবনু আব্দুর রহমান ইবনু আবী লাইলা হতে তিনি তার পিতা হতে তিনি উসাইদ ইবনু হুদাইর হতে। সঠিক কথা হলো- আব্দুল্লাহ ইবনু আবদিল্লাহ আলরাজী হতে তিনি আব্দুর রহমান ইবনু আবী লাইলা হতে তিনি বারাআ ইবনু আযিব হতে বর্ণনা করেছেন। ইসহাক বলেন, এ অনুচ্ছেদে রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লামের নিকট হতে বর্ণনা করা দু’টি সর্বাধিক সহীহ হাদীস রয়েছে। একটির রাবী বারাআ ইবনু আযিব (রাঃ) এবং অপরটির রাবী জাবির ইবনু সামুরা (রাঃ)। ইমাম ইসহাক ও আহমাদের মতে, উটের গোশত খেলে ওযু করতে হবে কিন্তু কিছু তাবেয়ী বিদ্বান, সুফিয়ান সাওরী ও কৃফাবাসী আলিমদের মতে ওযু করতে হবে না।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>81</td></tr><tr><td>Arabic No</td><td>81</td></tr><tr><td>Reference</td><td>Book 1 Hadith 81</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Al-Bara bin Azib narrated:Allah's Messenger was asked about performing Wudu for camel meat. He said: "Perform Wudu for it." He Was asked about Wudu after eating goat meat. So he said: "Do not perform Wudu for it
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>81</td></tr><tr><td>Arabic No</td><td>81</td></tr><tr><td>Reference</td><td>Book 1 Hadith 81</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
telah menceritakan kepada kami [Hannad] berkata, telah menceritakan kepada kami [Abu Mu'awiyah] dari [Al A'masy] dari [Abdullah bin Abdullah Ar Razi] dari [Abdurrahman bin Abu Laila] dari [Al Barro' bin 'Azib] ia berkata; Rasulullah shallallahu 'alaihi wasallam pernah ditanya tentang hukum wudlu karena maka daging unta, beliau menjawab: "Berwudlulah karenanya." Lalu beliau ditanya tentang hukum wudlu karena makan daging kambing, beliau menjawab: "Janganlah kalian berwudlu karenanya." Ia berkata; "Dalam bab ini juga ada riwayat dari Jabir bin Samurah dan Usaid bin Hudlair." Abu Isa berkata; "Al Hajjaj bin Artha'ah telah meriwayatkan hadits ini dari Abdullah bin Abdullah, dari Abdurrahman bin Abu Laila, dari Usaid bin Hudlair. Tetapi yang benar adalah hadits Abdurrahman bin Abu Laila dari Al Bara' bin 'Azib. Ini adalah pendapat Ahmad dan Ishaq. Dan [Ubaidah Adl Dlabbi] meriwayatkan dari [Abdullah bin Abdullah Ar Razi], dari [Abdurrahman bin Abu Laila], dari [Dzul Ghurrah Al Juhanni]. Sedangkan Hammad bin Salamah meriwayatkan hadits ini dari Al Hajjaj bin Artha'ah, namun ia melakukan kesalahan dalam periwayatannya. Ia mengatakan; "Abdullah bin Abdurrahman bin Abu Laila, dari bapaknya, dari Usaid bin Hudlair. Dan yang shahih adalah, dari Abdullah bin Abdullah Ar Razi, dari Abdurrahman bin Abu Laila, dari Al Bara' bin 'Azib. Ishaq berkata; "Dalam bab ini ada dua hadits dari Rasulullah shallallahu 'alaihi wasallam yang shahih; yaitu hadits Barra' dan hadits Jabir bin Samurah." Ini pendapat Ahmad dan Ishaq. Dan telah diriwayatkan dari sebagian ahli ilmu dari kalangan tabi'in dan selainnya, mereka berpendapat bahwasanya tidak harus wudlu karena makan daging unta. Ini adalah pendapat Sufyan Ats Tsauri dan penduduk Kufah
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>81</td></tr><tr><td>Arabic No</td><td>81</td></tr><tr><td>Reference</td><td>Book 1 Hadith 81</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Berâ b. Âzib (radıyallahü anh)’den aktarıldığına göre, şöyle demiştir: Rasûlüllah (sallallahü aleyhi ve sellem)’e deve eti yenildiğinde abdest alınmasından soruldu da: “Abdest alın” buyurdu. Koyun etlerinden dolayı abdest alınmalı mı? sorusuna da: “Abdest gerekmez” buyurdular. (Ebû Dâvûd, Tahara: 71; İbn Mâce, Tahara: 67) Bu konuda Câbir b. Semure ve Üseyd b. Hudayr’dan da hadis rivâyet edilmiştir Haccac b. Ertaa bu hadisi Abdullah b. Abdullah, Abdurrahman b. ebî Leylâ ve Üseyd b. Hudayr’dan rivâyet ediyor. Fakat sahih olan; Abdurrahman b. ebî Leylâ’nın, Berâ b. Âzib’den rivâyet ettiği hadistir. Ahmed ve İshâk’ta bu görüştedirler. ed Dabbî ise, bu hadisi; Abdullah b. Abdullah er Razî, Abdurrahman b. ebî Leylâ ve Zülkurra el Cühenî’den rivâyet etmiştir. b. Seleme bu hadisi, Haccac b. Ertaa’dan rivâyet ederek isim konusunda hataya düşüp şöyle demektedir. Abdullah b. Abdurrahman b. ebî Leylâ’dan, babasından ve Üseyd b. Hudayr’dan… Doğru ve sahih olan rivâyet: Abdullah b. Abdullah er Razî’nin Abdurrahman b. ebî Leylâ yoluyla Berâ b. Âzib’den yapılan şeklidir. İshâk diyor ki: Bu konuda Rasûlüllah (sallallahü aleyhi ve sellem)’den iki sahih hadis vardır ki birisi Berâ b. Âzib’in diğeri de Câbir b. Semure’den gelir. ve İshâk’ın görüşü de bu doğrultuda olup Tabiin ve Tebe-i tabiinden bazı ilim adamlarının: “Deve etinin yenilmesinden dolayı abdest almak gerekmediği görüşünde oldukları” rivâyet edilmiştir. Sûfyân es Sevrî ve Kufeli ilim adamları da bu görüştedir
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>81</td></tr><tr><td>Arabic No</td><td>81</td></tr><tr><td>Reference</td><td>Book 1 Hadith 81</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
براء بن عازب رضی الله عنہما کہتے ہیں کہ رسول اللہ صلی الله علیہ وسلم سے اونٹ کے گوشت کے بارے پوچھا گیا تو آپ نے فرمایا: اس سے وضو کرو اور بکری کے گوشت کے بارے میں پوچھا گیا تو آپ نے فرمایا: ”اس سے وضو نہ کرو“۔ امام ترمذی کہتے ہیں: ۱- اس باب میں جابر بن سمرہ اور اسید بن حضیر رضی الله عنہما سے بھی احادیث آئی ہیں، ۲- یہی قول احمد، عبداللہ اور اسحاق بن راہویہ کا ہے، ۳- اسحاق بن راہویہ کہتے ہیں کہ اس باب میں رسول اللہ صلی الله علیہ وسلم سے دو حدیثیں صحیح ہیں: ایک براء بن عازب کی ( جسے مولف نے ذکر کیا اور اس کے طرق پر بحث کی ہے ) اور دوسری جابر بن سمرہ کی، ۴- یہی قول احمد اور اسحاق بن راہویہ کا ہے۔ اور تابعین وغیرہم میں سے بعض اہل علم سے مروی ہے کہ ان لوگوں کی رائے ہے کہ اونٹ کے گوشت سے وضو نہیں ہے اور یہی سفیان ثوری اور اہل کوفہ کا قول ہے ۱؎۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>81</td></tr><tr><td>Arabic No</td><td>81</td></tr><tr><td>Reference</td><td>Book 1 Hadith 81</td></tr></tbody></table></div>