## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا قُتَيْبَةُ، حَدَّثَنَا يَحْيَى بْنُ زَكَرِيَّا بْنِ أَبِي زَائِدَةَ، عَنْ دَاوُدَ بْنِ أَبِي هِنْدٍ، عَنْ عِكْرِمَةَ، عَنِ ابْنِ عَبَّاسٍ، قَالَ قَالَتْ قُرَيْشٌ لِيَهُودَ اعْطُونَا شَيْئًا نَسْأَلُ عَنْهُ هَذَا الرَّجُلَ فَقَالَ سَلُوهُ عَنِ الرُّوحِ قَالَ فَسَأَلُوهُ عَنِ الرُّوحِ فَأَنْزَلَ اللَّهُ ‏:‏ ‏(‏وَ يَسْأَلُونَكَ عَنِ الرُّوحِ قُلِ الرُّوحُ مِنْ أَمْرِ رَبِّي وَمَا أُوتِيتُمْ مِنَ الْعِلْمِ إِلاَّ قَلِيلاً ‏)‏ قَالُوا أُوتِينَا عِلْمًا كَثِيرًا التَّوْرَاةُ وَمَنْ أُوتِيَ التَّوْرَاةَ فَقَدْ أُوتِيَ خَيْرًا كَثِيرًا فَأُنْزِلَتْْ‏:‏ ‏(‏ قُلْ لَوْ كَانَ الْبَحْرُ مِدَادًا لِكَلِمَاتِ رَبِّي لَنَفِدَ الْبَحْرُ ‏)‏ إِلَى آخِرِ الآيَةِ . قَالَ هَذَا حَدِيثٌ حَسَنٌ صَحِيحٌ غَرِيبٌ مِنْ هَذَا الْوَجْهِ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih Isnaad</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih Isnaad</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3140</td></tr><tr><td>Arabic No</td><td>3140</td></tr><tr><td>Reference</td><td>Book 47 Hadith 192</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
৩১৪০। ইবনু আব্বাস (রাযিঃ) হতে বর্ণিত, তিনি বলেন, কুরাইশরা ইয়াহুদীদের বলল, তোমরা আমাদেরকে এমন কিছু শিখিয়ে দাও যে প্রসঙ্গে আমরা এই ব্যক্তিকে (রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-কে) প্রশ্ন করতে পারি। ইয়াহুদীরা বলল, তোমরা রূহ প্রসঙ্গে তাকে প্রশ্ন কর। বর্ণনাকারী বলেনঃ তারা রূহ (বা প্রাণ) বিষয়ে তাকে প্রশ্ন করল। তখন আল্লাহ তা'আলা এ আয়াত অবতীর্ণ করেনঃ “লোকেরা রূহ প্রসঙ্গে তোমার নিকট প্রশ্ন করে। বল, রূহ আমার প্রতিপালকের আদেশ ঘটিত। জ্ঞানের খুব সামান্যই তোমাদেরকে প্রদান করা হয়েছে"- (সূরা বনী ইসরাঈল ৮৫)। ইয়াহুদীরা বলল, “আমাদের বিরাট বা প্রচুর জ্ঞান দান করা হয়েছে। আমাদেরকে তাওরাত কিতাব দেয়া হয়েছে। আর যাদেরকে তাওরাত গ্রন্থ দেয়া হয়েছে তাদেরকে প্রভূত কল্যাণ দেয়া হয়েছে। এ কথার পরিপ্রেক্ষিতে এ আয়াত অবতীর্ণ হয় (অনুবাদ) “বল, আমার প্রতিপালকের কথাগুলো লেখার জন্য সমুদ্রের সমস্ত পানি যদি কালি হয়ে যায় তবুও তা আমার প্রভুর কথাগুলো লিখে শেষ করার পূর্বেই নিঃশেষ হয়ে যবে। আমরা যদি আবার একই রকম কালি নিয়ে আসি তুবও তা যথেষ্ট হবে না"- (সূরা কাহফ ১০৯)। সহীহঃ আত্তা’লীকাত আল-হাসসান (৯৯) আবূ ঈসা বলেন, উল্লেখিত সনদসূত্রে এ হাদীসটি হাসান সহীহ গারীব।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih Isnaad</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih Isnaad</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3140</td></tr><tr><td>Arabic No</td><td>3140</td></tr><tr><td>Reference</td><td>Book 47 Hadith 192</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated Ibn 'Abbas:"The Quraish said to the Jews: 'Give us something that we can ask this man about.' So he said: 'Ask him about the Ruh.' So they asked him about the Ruh. So Allah Most High, revealed: They ask you concerning the Ruh. Say: The Ruh is one of the things, the knowledge of which is only with my Lord. And of knowledge, you have been given only a little (17:85). They replied: 'We have been given immense knowledge, we were given the Tawrah, and whoever has been given the Tawrah, then he has indeed been given a wealth of knowledge.' So the following was revealed: Say: 'If the sea were ink for the Words of my Lord, surely the sea would be exhausted (before the Words of my Lord would be finished.) (18:109)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih Isnaad</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih Isnaad</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3140</td></tr><tr><td>Arabic No</td><td>3140</td></tr><tr><td>Reference</td><td>Book 47 Hadith 192</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Qutaibah] telah menceritakan kepada kami [Yahya bin Zakariya bin Abu Za'idah] dari [Dawud bin Abu Hind] dari [Ikrimah] dari [Ibnu Abbas] berkata: kaum Quraisy berkata kepada seorang Yahudi: Berilah sesuatu yang bisa kami tanyakan pada lelaki ini (Rasulullah Shallallahu 'alaihi wa Salam)! Quraisy menjawab: Tanyakan padanya tentang ruh! lalu Allah menurunkan "Dan mereka bertanya kepadamu tentang ruh. Katakanlah: 'Ruh itu termasuk urusan Rabb-ku, dan tidaklah kamu diberi pengetahuan melainkan sedikit." (Al Israa': 85) mereka (yahudi) mengatakan: Kami diberi banyak ilmu, dan siapapun yang diberi Taurat sungguh ia telah diberi banyak kebaikan. Lalu diturunkan "Sekiranya lautan menjadi tinta untuk (menulis) kalimat-kalimat Rabbku, sungguh habislah lautan itu sebelum habis (ditulis) kalimat-kalimat Rabbku, meskipun Kami datangkan tambahan sebanyak itu (pula)." (Al Israa': 108) Abu Isa mengatakan bahwa hadits ini hasan shahih gharib
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih Isnaad</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih Isnaad</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3140</td></tr><tr><td>Arabic No</td><td>3140</td></tr><tr><td>Reference</td><td>Book 47 Hadith 192</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
İbn Abbâs (r.a.)’den rivâyete göre, şöyle demiştir: Kureyşliler Yahudilere bize bazı şeyler söyleyin ki şu adama (Muhammed’e) soralım dediler. Yahudiler de: O'na ruh'tan sorun dediler. Bunun üzerine Mekkeli müşrik Kureyşliler, Nebiye ruh’dan sordular. Bunun üzerine Allah İsra sûresi 85. ayetini indirdi; “Sana ruhtan yani insanın ruh'u, Cebrâil, vahyin gelişi ve Kur’ân’ın Allah’tan gelişi hakkında soruyorlar, de ki: “Ruh, Rabbimin emrindedir. Bu konuda size pek az bilgi verilmiştir.” Yahudiler dediler ki: Bize çok büyük bilgi kaynağı olan Tevrat verilmiştir. Kime Tevrat verilmişse ona büyük hayır verilmiş demektir, dediler. Bunun üzerine Kehf sûresi 109. ayet nazil oldu: “De ki: Rabbimin sözlerini yazmak için denizler mürekkep olsa, ayrıca deniz üzerine deniz katsak, yine Rabbimin sözleri bitmeden denizler tükenirdi.” Diğer tahric: Müsned: 2195 Tirmizî: Bu hadis bu şekliyle hasen sahihtir
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih Isnaad</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih Isnaad</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3140</td></tr><tr><td>Arabic No</td><td>3140</td></tr><tr><td>Reference</td><td>Book 47 Hadith 192</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
عبداللہ بن عباس رضی الله عنہما کہتے ہیں کہ قریش نے یہود سے کہا کہ ہمیں کوئی ایسا سوال دو جسے ہم اس شخص ( یعنی محمد صلی اللہ علیہ وسلم ) سے پوچھیں، انہوں نے کہا: اس شخص سے روح کے بارے میں سوال کرو، تو انہوں نے آپ سے روح کے بارے میں پوچھا ( روح کی حقیقت کیا ہے؟ ) اس پر اللہ نے آیت «ويسألونك عن الروح قل الروح من أمر ربي وما أوتيتم من العلم إلا قليلا» ”تم سے روح کے بارے میں پوچھتے ہیں، کہہ دو! روح امر الٰہی ہے، تمہیں بہت ہی تھوڑا علم دیا گیا ہے“ ( بنی اسرائیل: ۸۵ ) ، انہوں نے کہا: ہمیں تو بہت زیادہ علم حاصل ہے، ہمیں توراۃ ملی ہے، اور جسے توراۃ دی گئی ہو اسے بہت بڑی خیر مل گئی، اس پر آیت «قل لو كان البحر مدادا لكلمات ربي لنفد البحر» ”کہہ دیجئیے: اگر میرے رب کی باتیں، کلمے، معلومات و مقدرات لکھنے کے لیے سمندر سیاہی ( روشنائی ) بن جائیں تو سمندر ختم ہو جائے ( مگر میرے رب کی حمد و ثناء ختم نہ ہو ) “ ( الکہف: ۱۰۹ ) ، نازل ہوئی ۲؎۔ امام ترمذی کہتے ہیں: یہ حدیث اس سند سے حسن صحیح غریب ہے۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih Isnaad</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih Isnaad</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3140</td></tr><tr><td>Arabic No</td><td>3140</td></tr><tr><td>Reference</td><td>Book 47 Hadith 192</td></tr></tbody></table></div>