## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا عَبْدُ بْنُ حُمَيْدٍ، أَخْبَرَنَا عَبْدُ الرَّزَّاقِ، أَخْبَرَنَا مَعْمَرٌ، عَنِ الزُّهْرِيِّ، عَنْ سَالِمٍ، عَنِ ابْنِ عُمَرَ، أَنَّ رَسُولَ اللَّهِ صلى الله عليه وسلم مَرَّ بِابْنِ صَيَّادٍ فِي نَفَرٍ مِنْ أَصْحَابِهِ فِيهِمْ عُمَرُ بْنُ الْخَطَّابِ وَهُوَ يَلْعَبُ مَعَ الْغِلْمَانِ عِنْدَ أُطُمِ بَنِي مَغَالَةَ وَهُوَ غُلاَمٌ فَلَمْ يَشْعُرْ حَتَّى ضَرَبَ رَسُولُ اللَّهِ صلى الله عليه وسلم ظَهْرَهُ بِيَدِهِ ثُمَّ قَالَ ‏"‏ أَتَشْهَدُ أَنِّي رَسُولُ اللَّهِ ‏"‏ ‏.‏ فَنَظَرَ إِلَيْهِ ابْنُ صَيَّادٍ فَقَالَ أَشْهَدُ أَنَّكَ رَسُولُ الأُمِّيِّينَ ‏.‏ ثُمَّ قَالَ ابْنُ صَيَّادٍ لِلنَّبِيِّ صلى الله عليه وسلم أَتَشْهَدُ أَنْتَ أَنِّي رَسُولُ اللَّهِ فَقَالَ النَّبِيُّ صلى الله عليه وسلم ‏"‏ آمَنْتُ بِاللَّهِ وَبِرُسُلِهِ ‏"‏ ‏.‏ ثُمَّ قَالَ النَّبِيُّ صلى الله عليه وسلم ‏"‏ مَا يَأْتِيكَ ‏"‏ ‏.‏ قَالَ ابْنُ صَيَّادٍ يَأْتِينِي صَادِقٌ وَكَاذِبٌ ‏.‏ فَقَالَ النَّبِيُّ صلى الله عليه وسلم ‏"‏ خُلِّطَ عَلَيْكَ الأَمْرُ ‏"‏ ‏.‏ ثُمَّ قَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏"‏ إِنِّي خَبَأْتُ لَكَ خَبِيئًا ‏"‏ ‏.‏ وَخَبَأَ لَهُ ‏:‏ ‏(‏يَوْمَ تَأْتِي السَّمَاءُ بِدُخَانٍ مُبِينٍ ‏)‏ فَقَالَ ابْنُ صَيَّادٍ هُوَ الدُّخُّ ‏.‏ فَقَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏"‏ اخْسَأْ فَلَنْ تَعْدُوَ قَدْرَكَ ‏"‏ ‏.‏ قَالَ عُمَرُ يَا رَسُولَ اللَّهِ ائْذَنْ لِي فَأَضْرِبَ عُنُقَهُ ‏.‏ فَقَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏"‏ إِنْ يَكُ حَقًّا فَلَنْ تُسَلَّطَ عَلَيْهِ وَإِنْ لاَ يَكُنْهُ فَلاَ خَيْرَ لَكَ فِي قَتْلِهِ ‏"‏ ‏.‏ قَالَ عَبْدُ الرَّزَّاقِ يَعْنِي الدَّجَّالَ ‏.‏ قَالَ أَبُو عِيسَى هَذَا حَدِيثٌ حَسَنٌ صَحِيحٌ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2249</td></tr><tr><td>Arabic No</td><td>2249</td></tr><tr><td>Reference</td><td>Book 33 Hadith 92</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
২২৪৯। ইবনু উমার (রাঃ) হতে বর্ণিত আছে, কোন একদিন রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম একদল সাহাবী নিয়ে ইবনু সাইয়্যাদের পাশ দিয়ে যাচ্ছিলেন। তাদের মধ্যে উমার ইবনুল খাত্তাব (রাঃ)-ও ছিলেন। সে তখন মাগালা’ গোত্রের দুর্গের পাশে বালকদের সাথে খেলা করছিল। সেও তখন কিশোর ছিল। সে সাড়া পাওয়ার আগেই রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম গিয়ে তার পিঠে হাত চাপড় দিয়ে প্রশ্ন করলেনঃ তুমি কি সাক্ষ্য দাও যে, আমি আল্লাহর রাসূল? ইবনু সাইয়্যাদ তার দিকে দৃষ্টিপাত করে বলল, আমি সাক্ষ্য দিচ্ছি যে, আপনি নিরক্ষরদের রাসূল! বর্ণনাকারী বলেন, এরপর সে রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লামকে বলল, আপনি কি সাক্ষ্য দিচ্ছেন যে, আমিও আল্লাহর রাসূল? রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বললেনঃ আমি তো আল্লাহ ও তার রাসূলদের প্রতি ঈমান এনেছি। রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম তাকে আবার প্রশ্ন করলেনঃ তোমার নিকট কী আসে? ইবনু সাইয়্যাদ বলল, আমার নিকট সত্যবাদীও আসে মিথ্যাবাদীও আসে। তারপর রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বললেনঃ তোমার বিষয়টা তালগোল পাকিয়ে গেছে। তারপর রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বললেনঃ আমি একটি বিষয় তোমার জন্য ঠিক করে রেখেছি। বলতো তা কি? এই বলে তিনি মনে মনে পাঠ করলেনঃ “আকাশ সেদিন স্পষ্ট ধোয়ায় ছেয়ে যাবে" (সূরাঃ আদ-দুখান— ১০)। উত্তরে ইবনু সাইয়্যাদ বলল, সেটা তো “আদ-দুখ” (ধোঁয়া)। একথা শুনে রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বললেনঃ দূর হও! তুই কখনো তোর ভাগ্যকে অতিক্রম করতে পারবি না। উমার (রাঃ) বললেন, হে আল্লাহর রাসূল (সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম) আমাকে সম্মতি দিন, একে মেরে ফেলি। রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বললেনঃ সে যদি সত্যিই (দাজ্জাল) হয়ে থাকে তাহলে তার উপর তুমি জয়লাভ করতে পারবে না। আর সে তা না হয়ে থাকলে তবে তাকে মেরে ফেলায় তোমার কোন কল্যাণ নেই। আবদুর রাযযাক বলেন, শব্দটিতে দাজ্জাল বুঝান হয়েছে। সহীহ, সহীহ আদাবুল মুফরাদ, বুখারী, মুসলিম। আবূ ঈসা বলেন, এ হাদীসটি হাসান সহীহ।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2249</td></tr><tr><td>Arabic No</td><td>2249</td></tr><tr><td>Reference</td><td>Book 33 Hadith 92</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
It was narrated from Ibn 'Umar, that the Messenger of Allah(s.a.w) passed by Ibn Sayyad with a group of his Companions – among them 'Umar bin Al-Khattab – while he was playing with two boys at the fort of Banu Maghalah, and he was a boy. He did not realize until the Messenger of Allah(s.a.w) struck him with his hand on his back, then he said:“Do you testify that I am the Messenger of Allah?” So Ibn Sayyad looked at him, and said: 'I testify that you are the Messenger to the illiterates.'” He said: “Then Ibn Sayyad said to the Prophet(s.a.w): 'Do you testify that I am the Messenger of Allah?' So the Prophet(s.a.w) said: 'I believe in Allah and His Messengers.' Then the Prophet(s.a.w) said: 'Who has come to you?' Ibn Sayyad said: 'A truthful one and a liar came to me.' So the Prophet(s.a.w) said: 'The matter has been confused for you.' Then the Messenger of Allah(s.a.w) said: 'I have concealed something from you.' And he had concealed (the verse): The day when the sky will bring forth a visible smoke. Ibn Sayyad said: 'It is, “Ad-Dukh.'” So the Messenger of Allah(s.a.w) said: 'Beat it! You can never surpass your ability.' 'Umar said: 'O Messenger of Allah! Permit me to chop off his head!' The Messenger of Allah(s.a.w) said: 'If he is indeed him, then you will never overpower him, and if he is not, then there is no good in you killing him.'” (Sahih)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2249</td></tr><tr><td>Arabic No</td><td>2249</td></tr><tr><td>Reference</td><td>Book 33 Hadith 92</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami ['Abd bin Humaid] telah mengkhabarkan kepada kami [Abdurrazzaq] telah mengkhabarkan kepada kami [Ma'mar] dari [Az Zuhri] dari [Salim] dari [Ibnu Umar], Rasulullah Shallallahu 'alahi wa Salam melewati Ibnu Shayyad bersama beberapa sahabat, diantara mereka ada Umar bin Al Khaththab, ia bermain bersama anak-anak kecil didekat Uthum bin Maghalah, ia adalah seorang budak, ia tidak merasa hingga Rasulullah Shallallahu 'alahi wa Salam memukul punggungnya lalu beliau bertanya: "Apa kau bersaksi bahwa aku utusan Allah?" Ibnu Shayyad memandang beliau, ia menjawab: Aku bersaksi bahwa engkau adalah rasul kaum ummi. Selanjutnya Ibnu Shayyad bertanya: Apa kau bersaksi bahwa aku utusan Allah? Rasulullah Shallallahu 'alaihi wa salam bersabda: "Aku beriman kepada Allah dan rasulNya." Setelah itu nabi Shallallahu 'alaihi wa Salam bertanya: "Apa yang mendatangimu?" Ibnu Shayyad menjawab: Seorang jujur dan seorang pendusta mendatangiku. Nabi Shallallahu 'alaihi wa Salam bersabda: "Urusan dicampur adukkan padamu." Setelah itu Rasulullah Shallallahu 'alahi wa Salam bertanya: " aku menyembunyikan sesuatu padamu." Nabi Shallallahu 'alaihi wa Salam ketika itu menyembunyikan kutipan ayat yang berbunyi "dan ingatlah ketika langit membawa asap yang nyata (QS. Addukhan: 10). Ibnu Shayyad menjawab: Itu adalah asap. Rasulullah Shallallahu 'alaihi wa salam bersabda: "Hinalah engkau, engkau tidak bakalan melampaui batas kemampuanmu sebagai dukun!." Umar berkata: Wahai Rasulullah, izinkan aku menebas lehernya. Rasulullah Shallallahu 'alaihi wa salam bersabda: "Bila ia benar, kau tidak akan bisa menguasainya dan bila tidak, tidak ada baiknya bagimu untuk membunuhnya." Berkata 'Abdur Razza: Maksud beliau Dajjal. Berkata Abu Isa: Hadits ini hasan shahih
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2249</td></tr><tr><td>Arabic No</td><td>2249</td></tr><tr><td>Reference</td><td>Book 33 Hadith 92</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
İbn Ömer (r.a.)’den rivâyet edilmiştir. Rasûlullah (s.a.v.) ashabından aralarında Ömer b. Hattâb’ın da bulunduğu birkaç kişiyle İbn Sayyad’a uğramıştı. İbn Sayyad; bir delikanlı olup, Beni Meğale konağı yanında bazı çocuklarla oynamakta idi. Rasûlullah (s.a.v.) onun yanına varıp onun sırtına eliyle vurup şöyle dedi: Benim Allah’ın elçisi olduğuma şâhidlik yapar mısın? İbn Sayyad, Rasûlullah (s.a.v.)’e baktı ve: Sen, Ümmîlerin peygamberisin dedi. Sonra Rasûlullah (s.a.v.)’e: Sen benim Allah’ın Rasûlü olduğuma şâhidlik edermisin? Diye sordu. Bunun üzerine Rasûlullah (s.a.v.), Allah’a ve elçilerine iman etmişimdir dedi. Sonra Peygamberimiz şöyle devam etti: Sana ne geliyor? İbn Sayyad dedi ki: Bana yalan da doğruda geliyor dedi. Rasûlullah (s.a.v.): Senin işin karma karışıktır buyurdu. Sonra Rasûlullah (s.a.v.), içimde gizlice tuttuğum bir şey var onu bil bakalım dedi. Peygamberimiz (Duhan sûresinin 10. ayetini içinden geçirmişti.) İbn Sayyad; “O Duhh” tur dedi. Rasûlullah (s.a.v.), defol oradan sen bir kahin olarak haddini asla aşamayacaksın. Ömer: Ey Allah’ın Rasûlü! izin ver de buynunu uçurayım dedi. Bunun üzerine Rasûlullah (s.a.v.): Bu gerçekten Deccâl ise sen onun hakkından gelemezsin, eğer o değilse onu öldürmekte bir hayır yoktur buyurdular. Diğer tahric: Ebû Dâvûd, Melahım; Müslim, Fiten Abdurrezzak diyor ki: “O değilse” demekten Deccâl’ı kastediyor. Tirmizî: Bu hadis hasen sahihtir
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2249</td></tr><tr><td>Arabic No</td><td>2249</td></tr><tr><td>Reference</td><td>Book 33 Hadith 92</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
عبداللہ بن عمر رضی الله عنہما سے روایت ہے کہ رسول اللہ صلی اللہ علیہ وسلم اپنے صحابہ کی ایک جماعت کے ساتھ جس میں عمر بن خطاب بھی تھے ابن صیاد کے پاس سے گزرے، اس وقت وہ بچوں کے ساتھ بنی مغالہ کے ٹیلوں کے پاس کھیل رہا تھا، وہ ایک چھوٹا بچہ تھا اس لیے اسے آپ کی آمد کا احساس اس وقت تک نہ ہو سکا یہاں تک کہ آپ صلی اللہ علیہ وسلم نے اپنے ہاتھ سے اس کی پیٹھ پر مارا، پھر فرمایا: ”کیا تم گواہی دیتے ہو کہ میں اللہ کا رسول ہوں؟“ ابن صیاد نے آپ کی طرف دیکھ کر کہا: میں گواہی دیتا ہوں کہ آپ امیوں کے رسول ہیں، پھر ابن صیاد نے نبی اکرم صلی اللہ علیہ وسلم سے کہا: کیا آپ گواہی دیتے ہیں کہ میں اللہ کا رسول ہوں؟ نبی اکرم صلی اللہ علیہ وسلم نے فرمایا: ”میں اللہ اور اس کے رسولوں پر ایمان لایا ہوں“، پھر نبی اکرم صلی اللہ علیہ وسلم نے دریافت کیا: ”تمہارے پاس ( غیب کی ) کون سی چیز آتی ہے؟“ ابن صیاد نے کہا: میرے پاس ایک سچا اور ایک جھوٹا آتا ہے، پھر نبی اکرم صلی اللہ علیہ وسلم نے فرمایا: ”تمہارے اوپر تیرا معاملہ مشتبہ ہو گیا ہے“، پھر آپ صلی اللہ علیہ وسلم نے فرمایا: ”میں تمہارے لیے ( دل میں ) ایک بات چھپاتا ہوں“ اور آپ نے آیت: «يوم تأتي السماء بدخان مبين» ۱؎ چھپا لی، ابن صیاد نے کہا: وہ ( چھپی ہوئی چیز ) «دخ» ہے تو رسول اللہ صلی اللہ علیہ وسلم نے فرمایا: ”پھٹکار ہو تجھ پر تو اپنی حد سے آگے نہیں بڑھ سکے گا“، عمر رضی الله عنہ نے کہا: اللہ کے رسول! مجھے اجازت دیجئیے میں اس کی گردن اڑا دوں، آپ صلی اللہ علیہ وسلم نے فرمایا: ”اگر وہ حقیقی دجال ہے تو تم اس پر غالب نہیں آ سکتے اور اگر وہ نہیں ہے تو اسے قتل کرنے میں کوئی بھلائی نہیں ہے“۔ عبدالرزاق کہتے ہیں: «حقا» سے آپ کی مراد دجال ہے ۲؎۔ امام ترمذی کہتے ہیں: یہ حدیث حسن صحیح ہے۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2249</td></tr><tr><td>Arabic No</td><td>2249</td></tr><tr><td>Reference</td><td>Book 33 Hadith 92</td></tr></tbody></table></div>