## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا ابْنُ أَبِي عُمَرَ، حَدَّثَنَا سُفْيَانُ، عَنْ دَاوُدَ بْنِ أَبِي هِنْدٍ، وَإِسْمَاعِيلَ بْنِ أَبِي خَالِدٍ، وَزَكَرِيَّا بْنِ أَبِي زَائِدَةَ، عَنِ الشَّعْبِيِّ، عَنْ عُرْوَةَ بْنِ مُضَرِّسِ بْنِ أَوْسِ بْنِ حَارِثَةَ بْنِ لاَمٍ الطَّائِيِّ، قَالَ أَتَيْتُ رَسُولَ اللَّهِ صلى الله عليه وسلم بِالْمُزْدَلِفَةِ حِينَ خَرَجَ إِلَى الصَّلاَةِ فَقُلْتُ يَا رَسُولَ اللَّهِ إِنِّي جِئْتُ مِنْ جَبَلَىْ طَيِّئٍ أَكْلَلْتُ رَاحِلَتِي وَأَتْعَبْتُ نَفْسِي وَاللَّهِ مَا تَرَكْتُ مِنْ حَبْلٍ إِلاَّ وَقَفْتُ عَلَيْهِ فَهَلْ لِي مِنْ حَجٍّ فَقَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏"‏ مَنْ شَهِدَ صَلاَتَنَا هَذِهِ وَوَقَفَ مَعَنَا حَتَّى نَدْفَعَ وَقَدْ وَقَفَ بِعَرَفَةَ قَبْلَ ذَلِكَ لَيْلاً أَوْ نَهَارًا فَقَدْ أَتَمَّ حَجَّهُ وَقَضَى تَفَثَهُ ‏"‏ ‏.‏ قَالَ أَبُو عِيسَى هَذَا حَدِيثٌ حَسَنٌ صَحِيحٌ ‏.‏ قَالَ قَوْلُهُ ‏"‏ تَفَثَهُ ‏"‏ ‏.‏ يَعْنِي نُسُكَهُ ‏.‏ قَوْلُهُ ‏"‏ مَا تَرَكْتُ مِنْ حَبْلٍ إِلاَّ وَقَفْتُ عَلَيْهِ ‏"‏ ‏.‏ إِذَا كَانَ مِنْ رَمْلٍ يُقَالُ لَهُ حَبْلٌ وَإِذَا كَانَ مِنْ حِجَارَةٍ يُقَالُ لَهُ جَبَلٌ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>891</td></tr><tr><td>Arabic No</td><td>891</td></tr><tr><td>Reference</td><td>Book 9 Hadith 84</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
৮৯১। উরওয়া ইবনু মুয়ারিস ইবনু আওস ইবনু হারিসা ইবনু লাম আত-তাঈ (রাঃ) হতে বর্ণিত আছে, তিনি বলেন, আমি মুযদালফায় রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লামের নিকট আসলাম, তখন তিনি নামাযের উদ্দেশ্যে বের হয়েছেন। আমি বললাম, হে আল্লাহর রাসূল! আমি তাঈ-এর দুই পাহাড় (অঞ্চল) হতে এসেছি। আমার বাহনকেও আমি ক্লান্ত করে ফেলেছি এবং নিজেকেও খুবই পরিশ্রান্ত করেছি। আল্লাহর শপথ। আমি এমন কোন বালির স্তুপ ছেড়ে যাইনি যেখানে আমি অবস্থান করিনি। আমার কি হাজ্জ হবে? রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বললেনঃ আমাদের এই নামাযে যে লোক শরীক হয়েছে, আমাদের সাথে ফিরে আসা পর্যন্ত অবস্থান করেছে এবং এর পূর্বে রাতে বা দিনে আরাফাতে থেকেছে তার হাজ্জ পূর্ণ হয়েছে এবং সেলোক তার অপরিচ্ছন্নতা দূর করে নিয়েছে। সহীহ, ইবনু মা-জাহ (৩০২৬),বুখারী, মুসলিম এই হাদিসটিকে আবূ ঈসা হাসান সহীহ বলেছেন। তাফাসাহু এর অর্থ তাঁর হাজ্জ। বালির স্তূপকে হাবল বলা হয়। পাথরের স্তূপকে জাবাল বলা হয়।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>891</td></tr><tr><td>Arabic No</td><td>891</td></tr><tr><td>Reference</td><td>Book 9 Hadith 84</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Urwah bin Mudarris bin Aws bin Harithah bin Lam At-Ta'i narrated:"I came to the Messenger of Allah at Al-Muzdalifah when he left for the Salat. I said: 'O Messenger of Allah! I came from the two mountains of (the tribe of) Tai, wearing out my mount and exhausting myself. By Allah! I did not leave a Habl (sand dune) without stopping on it. So is there Hajj for me?' The Messenger of Allah said: 'Whoever attends this Salat of ours, and stays here with us until departing, while he has stood during the night or the day before that at Arafat, then he has completed his Hajj and fulfilled his Tafath
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>891</td></tr><tr><td>Arabic No</td><td>891</td></tr><tr><td>Reference</td><td>Book 9 Hadith 84</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Ibnu Abu 'Umar], telah menceritakan kepada kami [Sufyan] dari [Daud bin Abu Hind] dan [Isma'il bin Abu Khalid] dan [Zakariya bin Abu Za'idah] dari [Asy Sya'bi] dari [Urwah bin Mudlarris bin Aus bin Haritsah bin Laam Al Thai] berkata; "Aku menemui Rasulullah shallallahu 'alaihi wasallam di Muzdalifah ketika beliau hendak shalat. Aku berkata; 'Wahai Rasulullah, saya datang dari dua gunung Thayyi'. Perjalananku cukup melelahkan dan diriku merasa letih. Demi Allah, tidak ada gunung pasir kecuali aku wukuf di sana. Apakah hajiku sah? ' Rasulullah shallallahu 'alaihi wasallam menjawab; 'Barangsiapa yang shalat bersama kami, dan wukuf bersama kami hingga selesai dan sebelum itu dia wuquf di Arafah baik malam maupun siang maka hajinya telah sempurna serta telah melaksanakan seluruh manasik'." Abu 'Isa berkata; "Ini merupakan hadits hasan shahih. Makna sabda beliau 'TAFATSAHU' yaitu Manasiknya, dan arti dari perkataannya 'MAA TARAKTU MIN HABLIN ILLA WAQAFTU ILAIHI' (tidak ada gunung pasir kecuali aku wukuf di sana), jika dari pasir disebut 'HABLUN' sedang jika dari bebatuan disebut 'JABALUN
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>891</td></tr><tr><td>Arabic No</td><td>891</td></tr><tr><td>Reference</td><td>Book 9 Hadith 84</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Urve b. Mudarris b. Evs b. Hârise b. Lâm’in et Taî’den rivâyet edildiğine göre, şöyle demiştir: “Müzdelife’de namaza çıkacağı sırada Rasûlullah (s.a.v.)’e geldim ve Şöyle dedim: Ey Allah’ın Rasûlü, Tayyi denilen bölgenin iki dağı arasından geliyorum hayvanımı da yordum kendim de yoruldum üzerinde durmadığım bir dağ bırakmadım. Benim haccım olur mu?” Bunun üzerine Rasûlullah (s.a.v.) şöyle buyurdular: “Bizim kılacağımız şu sabah namazına katılan burayı terk edinceye kadar bizimle beraber olan bundan öncede gece veya gündüzden bir an bile olsa Arafat’ta bulunan kimse hac vazifesini yapmış ve haccını tamamlamış sayılır.” Diğer tahric: Ebû Dâvûd, Menasik; Nesâî, Menasik Tirmîzî: Bu hadis hasen sahihtir. Hadiste geçen Tefesehu: Kelimesinin anlamı hacla ilgili vazifeler demektir. “Habelün” kumluk arazi “Cebelün” ise taşlık yerler demektir
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>891</td></tr><tr><td>Arabic No</td><td>891</td></tr><tr><td>Reference</td><td>Book 9 Hadith 84</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
عروہ بن مضرس بن اوس بن حارثہ بن لام الطائی رضی الله عنہ کہتے ہیں: میں رسول اللہ صلی اللہ علیہ وسلم کے پاس مزدلفہ آیا، جس وقت آپ نماز کے لیے نکلے تو میں نے آپ سے عرض کیا: اللہ کے رسول! میں قبیلہ طی کے دونوں پہاڑوں سے ہوتا ہوا آیا ہوں، میں نے اپنی سواری کو اور خود اپنے کو خوب تھکا دیا ہے، اللہ کی قسم! میں نے کوئی پہاڑ نہیں چھوڑا جہاں میں نے ( یہ سوچ کر کہ عرفات کا ٹیلہ ہے ) وقوف نہ کیا ہو تو کیا میرا حج ہو گیا؟ رسول اللہ صلی اللہ علیہ وسلم نے فرمایا: ”جو بھی ہماری اس نماز میں حاضر رہا اور اس نے ہمارے ساتھ قیام کیا یہاں تک کہ ہم یہاں سے روانہ ہوں اور وہ اس سے پہلے دن یا رات میں عرفہ میں وقوف کر چکا ہو ۱؎ تو اس نے اپنا حج پورا کر لیا، اور اپنا میل کچیل ختم کر لیا“ ۲؎۔ امام ترمذی کہتے ہیں: ۱ – یہ حدیث حسن صحیح ہے، ۲- «تَفَثَهُ» کے معنی «نسكه» کے ہیں یعنی مناسک حج کے ہیں۔ اور اس کے قول: «ما تركت من حبل إلا وقفت عليه» ”کوئی ٹیلہ ایسا نہ تھا جہاں میں نے وقوف نہ کیا ہو“ کے سلسلے میں یہ ہے کہ جب ریت کا ٹیلہ ہو تو اسے حبل اور جب پتھر کا ہو تو اسے جبل کہتے ہیں۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>891</td></tr><tr><td>Arabic No</td><td>891</td></tr><tr><td>Reference</td><td>Book 9 Hadith 84</td></tr></tbody></table></div>