## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا يَعْقُوبُ بْنُ إِبْرَاهِيمَ الدَّوْرَقِيُّ، حَدَّثَنَا هُشَيْمٌ، حَدَّثَنَا يَعْلَى بْنُ عَطَاءٍ، عَنْ عُمَارَةَ بْنِ حَدِيدٍ، عَنْ صَخْرٍ الْغَامِدِيِّ، قَالَ قَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏ "‏ اللَّهُمَّ بَارِكْ لأُمَّتِي فِي بُكُورِهَا ‏"‏ ‏.‏ قَالَ وَكَانَ إِذَا بَعَثَ سَرِيَّةً أَوْ جَيْشًا بَعَثَهُمْ أَوَّلَ النَّهَارِ وَكَانَ صَخْرٌ رَجُلاً تَاجِرًا وَكَانَ إِذَا بَعَثَ تِجَارَةً بَعَثَهُمْ أَوَّلَ النَّهَارِ فَأَثْرَى وَكَثُرَ مَالُهُ ‏.‏ قَالَ وَفِي الْبَابِ عَنْ عَلِيٍّ وَابْنِ مَسْعُودٍ وَبُرَيْدَةَ وَأَنَسٍ وَابْنِ عُمَرَ وَابْنِ عَبَّاسٍ وَجَابِرٍ ‏.‏ قَالَ أَبُو عِيسَى حَدِيثُ صَخْرٍ الْغَامِدِيِّ حَدِيثٌ حَسَنٌ ‏.‏ وَلاَ نَعْرِفُ لِصَخْرٍ الْغَامِدِيِّ عَنِ النَّبِيِّ صلى الله عليه وسلم غَيْرَ هَذَا الْحَدِيثِ ‏.‏ وَقَدْ رَوَى سُفْيَانُ الثَّوْرِيُّ عَنْ شُعْبَةَ عَنْ يَعْلَى بْنِ عَطَاءٍ هَذَا الْحَدِيثَ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1212</td></tr><tr><td>Arabic No</td><td>1212</td></tr><tr><td>Reference</td><td>Book 14 Hadith 11</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
১২১২। সাখর আল-গামিদী (রাঃ) হতে বর্ণিত আছে, তিনি বলেন, রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেছেনঃ “হে আল্লাহ! আমার উম্মাতের ভোর বেলার মধ্যে তাদেরকে বারকাত ও প্রাচুর্য দান করুন।” বর্ণনাকারী বলেন, যখন তিনি কোথাও কোন ক্ষুদ্র অথবা বৃহৎ বাহিনী পাঠানোর সিদ্ধান্ত নিতেন, তখন তাদেরকে দিনের প্রথম অংশেই পাঠাতেন। সাখর (রাঃ) ছিলেন একজন ব্যবসায়ী। তিনি তার ব্যবসায়ীদের পাঠাতে ইচ্ছা করলে তাদেরকে দিনের প্রথম অংশেই পাঠাতেন। ফলে তিনি অনেক সম্পদের মালিক হন। — সহীহ, তিনি ক্ষুদ্র অথবা বৃহৎ বাহিনী দিনের প্রথম অংশেই প্রেরণ করতেন—’অংশটুকু যঈফ রাওযুন নায়ীর (৪৯০), সহীহ আবূ দাউদ (২৬৪৫), বেচা-কেনার হাদীস, যঈফা (৪১৭৮) ও জাবির (রাঃ) হতেও এ অনুচ্ছেদে হাদীস বর্ণিত আছে। আবূ ঈসা বলেন, সাখর আল-গামিদী (রাঃ) হতে বর্ণিত হাদীসটি হাসান। রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লামের এই একটি মাত্র হাদিসই আমরা সাখর (রাঃ)-এর নিকট হতে জেনেছি। এ হাদীসটি সুফিয়ান সাওরী শুবা হতে, তিনি ইয়া'লা ইবনু আতা হতে পরম্পরায় বর্ণনা করেছেন।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1212</td></tr><tr><td>Arabic No</td><td>1212</td></tr><tr><td>Reference</td><td>Book 14 Hadith 11</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated 'Umarah bin Hadid: From Shakr Al-Ghamidi that the Messenger of Allah (ﷺ) said: "O Allah bless my Ummah in what they do early (in the day)." He said: "Whenever he (ﷺ) would dispatch a military expedition or an army, he would send them in the first part of the day." And Sakhr, a man who was a merchant, used to send his goods for trade during the beginning of the day, so he became rich, and his wealth increased. [He said:] There are narrations on this topic from 'Ali, Buraidah, Ibn Mas'ud, Anas, Ibn 'Umar, Ibn 'Abbas, and Jabir. [Abu 'Eisa said:] The Hadith is Sakhr Al-Ghamidi is a Hasan Hadith. We do not know of a narration that Sakhr Al-Ghamidi reported from the Prophet (ﷺ) other than this Hadith. Sufyan Ath-Thawri reported this Hadith from Shu'bah, from Ya'la bin 'Ata
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1212</td></tr><tr><td>Arabic No</td><td>1212</td></tr><tr><td>Reference</td><td>Book 14 Hadith 11</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Ya'qub bin Ibrahim Ad Dauraqi] telah menceritakan kepada kami [Husyaim] telah menceritakan kepada kami [Ya'la bin 'Atha'] dari ['Umarah bin Hadid] dari [Shakhr Al Ghamidi] ia berkata; Rasulullah shallallahu 'alaihi wasallam berdoa: "ALLAHUMMA BAARIK LI UMMATII FII BUKUURIHAA (Ya Allah, limpahkanlah keberkahan kepada ummatku pada waktu pagi buta." Ia melanjutkan; Beliau jika mengutus ekspedisi atau pasukan, beliau mengutus mereka pada waktu pagi hari. Shakhr adalah seorang pedagang, jika ia mengirim barang dagangan, ia mengirimnya pada pagi hari, lalu ia meraih keuntungan dan bertambah banyak hartanya. Ia mengatakan; Dalam hal ini ada hadits serupa dari Ali, Ibnu Mas'ud, Buraidah, Anas, Ibnu Umar, Ibnu Abbas dan Jabir. Abu Isa berkata; Hadits Shakhr Al Ghamidi adalah hadits hasan dan kami tidak mengetahui hadits Shakhr Al Ghamidi dari Nabi shallallahu 'alaihi wasallam selain hadits ini dan [Sufyan Ats Tsauri] meriwayatkan hadits ini dari [Syu'bah] dari [Ya'la bin 'Atha]
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1212</td></tr><tr><td>Arabic No</td><td>1212</td></tr><tr><td>Reference</td><td>Book 14 Hadith 11</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Sahr el Gâmidî (radıyallahü anh)’den rivâyete göre, şöyle demiştir: Rasûlüllah (sallallahü aleyhi ve sellem) şöyle buyurdu: “Allah’ım ümmetimin gündüzün ilk vaktinde yaptıkları işleri bereketli kıl.” Sahr diyor ki: “Rasûlüllah (sallallahü aleyhi ve sellem) bir askerî birlik ve orduyu savaşa göndereceğinde sabahın ilk ve erken vakitlerinde gönderirdi.” Râvî diyor ki: Sahr ticaretle meşgul birisiydi, ticaretini sabah erken saatlerinde çıkmak ve göndermek şeklinde yapardı bunun için zengin olup malı çoğaldı. (Ebû Dâvûd, Cihad: 78; İbn Mâce, Ticarat: 41) Bu konuda Ali, İbn Mes’ûd, Büreyde, Enes, İbn Ömer, İbn Abbâs ve Câbir’den de hadis rivâyet edilmiştir. Sahr el Gâmidî’nin hadisi hasendir. Sahr el Gâmidî’nin bu hadisten başka rivâyet ettiği bir hadis bilmiyoruz. Sûfyân es Sevrî, Şu’be’den, Ya’la b. Âta’dan bu hadisi rivâyet etmiştir
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1212</td></tr><tr><td>Arabic No</td><td>1212</td></tr><tr><td>Reference</td><td>Book 14 Hadith 11</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
صخر غامدی رضی الله عنہ کہتے ہیں کہ رسول اللہ صلی اللہ علیہ وسلم نے فرمایا: ”اے اللہ! میری امت کو اس کے دن کے ابتدائی حصہ میں برکت دے“ ۱؎ صخر کہتے ہیں کہ آپ جب کسی سریہ یا لشکر کو روانہ کرتے تو اسے دن کے ابتدائی حصہ میں روانہ کرتے۔ اور صخر ایک تاجر آدمی تھے۔ جب وہ تجارت کا سامان لے کر ( اپنے آدمیوں کو ) روانہ کرتے تو انہیں دن کے ابتدائی حصہ میں روانہ کرتے۔ تو وہ مالدار ہو گئے اور ان کی دولت بڑھ گئی۔ امام ترمذی کہتے ہیں: ۱- صخر غامدی کی حدیث حسن ہے۔ ہم اس حدیث کے علاوہ صخر غامدی کی کوئی اور حدیث نہیں جانتے جسے انہوں نے نبی اکرم صلی اللہ علیہ وسلم سے روایت کی ہو، ۲- اس باب میں علی، ابن مسعود، بریدہ، انس، ابن عمر، ابن عباس، اور جابر رضی الله عنہم سے بھی احادیث آئی ہیں۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1212</td></tr><tr><td>Arabic No</td><td>1212</td></tr><tr><td>Reference</td><td>Book 14 Hadith 11</td></tr></tbody></table></div>