## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا مُحَمَّدُ بْنُ بَشَّارٍ، وَمُحَمَّدُ بْنُ الْمُثَنَّى، قَالاَ حَدَّثَنَا مُحَمَّدُ بْنُ جَعْفَرٍ، حَدَّثَنَا شُعْبَةُ، عَنْ مَنْصُورِ بْنِ الْمُعْتَمِرِ، قَالَ سَمِعْتُ رِبْعِيَّ بْنَ حِرَاشٍ، يُحَدِّثُ عَنْ زَيْدِ بْنِ ظَبْيَانَ، يَرْفَعُهُ إِلَى أَبِي ذَرٍّ عَنِ النَّبِيِّ صلى الله عليه وسلم قَالَ ‏ "‏ ثَلاَثَةٌ يُحِبُّهُمُ اللَّهُ وَثَلاَثَةٌ يَبْغَضُهُمُ اللَّهُ فَأَمَّا الَّذِينَ يُحِبُّهُمُ اللَّهُ فَرَجُلٌ أَتَى قَوْمًا فَسَأَلَهُمْ بِاللَّهِ وَلَمْ يَسْأَلْهُمْ بِقَرَابَةٍ بَيْنَهُ وَبَيْنَهُمْ فَمَنَعُوهُ فَتَخَلَّفَ رَجُلٌ بِأَعْقَابِهِمْ فَأَعْطَاهُ سِرًّا لاَ يَعْلَمُ بِعَطِيَّتِهِ إِلاَّ اللَّهُ وَالَّذِي أَعْطَاهُ وَقَوْمٌ سَارُوا لَيْلَتَهُمْ حَتَّى إِذَا كَانَ النَّوْمُ أَحَبَّ إِلَيْهِمْ مِمَّا يُعْدَلُ بِهِ نَزَلُوا فَوَضَعُوا رُءُوسَهُمْ فَقَامَ أَحَدُهُمْ يَتَمَلَّقُنِي وَيَتْلُو آيَاتِي وَرَجُلٌ كَانَ فِي سَرِيَّةٍ فَلَقِيَ الْعَدُوَّ فَهُزِمُوا وَأَقْبَلَ بِصَدْرِهِ حَتَّى يُقْتَلَ أَوْ يُفْتَحَ لَهُ ‏.‏ وَالثَّلاَثَةُ الَّذِينَ يَبْغَضُهُمُ اللَّهُ الشَّيْخُ الزَّانِي وَالْفَقِيرُ الْمُخْتَالُ وَالْغَنِيُّ الظَّلُومُ ‏"‏ ‏.‏ حَدَّثَنَا مَحْمُودُ بْنُ غَيْلاَنَ، حَدَّثَنَا النَّضْرُ بْنُ شُمَيْلٍ، عَنْ شُعْبَةَ، نَحْوَهُ ‏.‏ قَالَ أَبُو عِيسَى هَذَا حَدِيثٌ صَحِيحٌ ‏.‏ وَهَكَذَا رَوَى شَيْبَانُ، عَنْ مَنْصُورٍ، نَحْوَ هَذَا وَهَذَا أَصَحُّ مِنْ حَدِيثِ أَبِي بَكْرِ بْنِ عَيَّاشٍ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2568</td></tr><tr><td>Arabic No</td><td>2568</td></tr><tr><td>Reference</td><td>Book 38 Hadith 46</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
২৫৬৮। আবূ যার (রাঃ) হতে বর্ণিত আছে, রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেনঃ আল্লাহ তা'আলা তিন প্রকার লোককে ভালোবাসেন এবং তিন প্রকার লোককে ঘৃণা করেন। যাদের আল্লাহ তা'আলা ভালোবাসেন তারা হলঃ (১) কোন ব্যক্তি কোন সম্প্রদায়ের নিকটে এসে আল্লাহ তা'আলার ওয়াস্তে কিছু চাইল, তবে আত্মীয়তার সম্পর্কের দোহাই দিয়ে চায়নি। তারা তাকে কিছুই দিল না। এ সম্প্রদায়ের একটি লোক তাদের হতে আলাদা হয়ে গোপনে তাকে কিছু দান করল এবং তার দান প্রসঙ্গে আল্লাহ তা'আলা ও গ্রহণকারী ব্যতীত আর কেউ জানতে পারল না। (২) একটি দল সারারাত সফররত থাকল, তারপর সকল কিছুর তুলনায় ঘুম যখন তাদের প্রিয় হয়ে গেল, ফলে সব লোক (বালিশে) মাথা রেখে ঘুমিয়ে পড়ল; কিন্তু তাদেরই একজন আমার সন্তুষ্টি অর্জনের উদ্দেশ্যে নামাযে দাড়ায় এবং আমার কুরআনের আয়াত তিলাওয়াত করে। (৩) আর এক ব্যক্তি কোন সেনাবাহিনীতে যোগদান করল। তারপর শত্রুর মুকাবিলা করে তার পক্ষের লোকেরা পরাজিত হল; কিন্তু সে বুক ফুলিয়ে সামনে এগিয়ে গেলো। তারপর সে হয় শহীদ হল কিংবা বিজয়ী হল। আর আল্লাহ তা'আলা যে তিনজনকে ঘৃণা করেন তারা হলঃ (১) বৃদ্ধ যেনাকারী; (২) অহংকারী ভিক্ষুক এবং (৩) অত্যাচারী সম্পদশালী ব্যক্তি। যঈফ, মিশকাত (১৯২২) মাহমূদ ইবনু গাইলান-নাযর ইবনু শুমাইল হতে তিনি শুবা (রাহঃ) হতে উপরে বর্ণিত হাদীসের সমার্থক হাদীস বর্ণনা করেছেন। আবূ ঈসা বলেনঃ এ হাদীসটি সহীহ। শাইবান (রাহঃ)-ও মানসূরের সূত্রে এরকমই বর্ণনা করেছেন। এই সূত্রে বর্ণিত রিওয়ায়াতটি আবূ বাকর ইবনু আইয়্যাশের সূত্রে বর্ণিত হাদীসের তুলনায় অনেক বেশী সহীহ।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2568</td></tr><tr><td>Arabic No</td><td>2568</td></tr><tr><td>Reference</td><td>Book 38 Hadith 46</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Abu Dharr narrated that the Prophet(s.a.w) said:"There are three whom Allah loves and three whom Allah hates. As for those whom Allah loves: Then a man who came to a people and asked them by Allah, and he did not ask them due to any relation between him and them, but they did not give him. So a man stayed behind them and gave him secretly, none knew about what he gave except Allah and the one he gave. And, a group of people who traveled the night until when sleep became more beloved to them than all the things that equal it and they lay their heads down, but a man stoop up humbling himself to Me and reciting My Ayat. And a man who was in a small expedition and met the enemy and they were vanquished, yet he faced them until he was killed or victory was granted to him. And the three whom Allah hates are, the old man who commits adultery, the arrogant poor man, and the oppressive rich man." Another chain reports a similar narration
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2568</td></tr><tr><td>Arabic No</td><td>2568</td></tr><tr><td>Reference</td><td>Book 38 Hadith 46</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Muhammad bin Basyar] dan [Muhammad bin Al Mutsanna] keduanya berkata: telah menceritakan kepada kami [Muhammad bin Ja'far] telah bercerita kepada kami [Syu'bah] dari [Manshur bin Al Mu'tamir] berkata: aku telah mendengar [Rib'I bin Hirasy] dari [Zaid bin Dlabyan] ia memarfu'kannya melalui [Abu Dzar] dari Nabi Shallallahu 'alaihi wa Salam, beliau bersabda: "Ada tiga orang yang dicintai oleh Allah dan tiga orang yang dibenci oleh Allah, adapun yang dicintai oleh Allah adalah; seseorang yang datang kepada suatu kaum lalu meminta kepada mereka dengan nama Allah, ia tidak meminta karena ada hubungan kekerabatan antaranya dengan mereka namun mereka menolaknya, lalu ada seseorang dari kaum itu pergi secara sembunyi-sembunyi dan memberikan sesuatu kepada lelaki yang meminta tadi dengan sembunyi sembunyi, tidak ada yang mengetahui pemberiannya kecuali hanya Allah dan orang yang diberi, suatu kaum yang berjalan di malam hari keinginan untuk tidur lebih mereka sukai dari yang lain, mereka pun singgah lalu meletakkan kepala mereka (tertidur), namun ada seorang lelaki yang bangun bermunajat kepadaNya dan membaca ayat ayatNya, dan seseorang berada dalam barisan pasukan lalu berhadapan dengan musuh, dan ketika pasukannya hancur, justeru dia maju dengan menghadapkan dadanya sampai dia terbunuh atau mendapat kemenangan. Sedangkan tiga orang yang dibenci oleh Allah adalah; orang tua yang berzina, orang fakir yang sombong dan orang kaya yang dzalim." Telah menceritakan kepada kami [Mahmud bin Ghailan] telah bercerita kepada kami [An Nadlar bin Syumail] dari [Syu'bah] dengan hadits yang semakna. Abu Isa berkata: Hadits ini shahih, seperti itu juga [Syaiban] meriwayatkan dari [Manshur] dan ini lebih shahih dari hadits Abu Bakar bin Ayyasy
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2568</td></tr><tr><td>Arabic No</td><td>2568</td></tr><tr><td>Reference</td><td>Book 38 Hadith 46</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ebû Zerr (radıyallahü anh)’den rivâyete göre, Rasûlüllah (sallallahü aleyhi ve sellem) şöyle buyurmuştur: “Üç kişi vardır ki Allah onları sever, üç kişi de vardır ki Allah onlara buğzeder. Allah sevdikleri kimselerden birincisi bir adamdır ki bir toplumdan bir şeyler ister bu istediği şey Allah içindir aralarındaki yakınlıktan dolayı değildir. Onlarda bu adama bir şey vermezler. Bir adam onlardan geri durarak gizlice bir şeyler verir bu verdiğini sadece Allah ve verdiği kimse bilir. İkinci kimse ise: Bir toplum geceleri yürürler sonunda uyku onlara galip gelir ve başlarını eğerek uyurlar ancak bir adam kalkar bana yaranmak için âyetlerimi okur ve onunla yaşamaya çalışır. Üçüncü kimse ise; bir müfrezede bulunur düşmanla karşılaştıklarında yenilirler fakat o ileri atılarak devam eder ya şehîd olur veya Allah o kimseye fetih nasib eder. Allah’ın gazâblandığı üç kişi ise: Zina eden yaşlı kişi, büyüklük taslayan fakir ve hakka tecavüz eden zengindir.” (Nesâî, Kıyam-ül leyl: 17)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2568</td></tr><tr><td>Arabic No</td><td>2568</td></tr><tr><td>Reference</td><td>Book 38 Hadith 46</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ابوذر رضی الله عنہ سے روایت ہے کہ نبی اکرم صلی اللہ علیہ وسلم نے فرمایا: ”تین قسم کے لوگوں سے اللہ تعالیٰ محبت کرتا ہے، اور تین قسم کے لوگوں سے نفرت، جن لوگوں سے اللہ تعالیٰ محبت کرتا ہے وہ یہ ہیں: ایک وہ آدمی جو کسی قوم کے پاس جائے اور ان سے اللہ کا واسطہ دے کر مانگے وہ اپنے اور اس قوم کے درمیان پائے جانے والے کسی رشتے کا واسطہ دے کر نہ مانگے اور وہ لوگ اسے کچھ نہ دیں، پھر ان میں سے ایک آدمی پیچھے پھرے اور اسے چپکے سے لا کر کچھ دے، اس کے عطیہ کو اللہ تعالیٰ اور جس کو دیا ہے اس کے سوا کوئی نہ جانے۔ دوسرے وہ لوگ جو رات کو چلیں یہاں تک کہ جب ان کو نیند ان چیزوں سے پیاری ہو جائے جو نیند کے برابر ہیں تو سواری سے اتریں اور سر رکھ کر سو جائیں اور ان میں کا ایک آدمی کھڑا ہو کر میری خوشامد کرنے اور میری آیتوں کی تلاوت کرنے لگے، تیسرا وہ آدمی جو کسی سریہ میں ہو اور دشمن سے مقابلہ ہو تو اس کے ساتھی ہار جائیں پھر بھی وہ سینہ سپر ہو کر آگے بڑھے یہاں تک کہ مارا جائے یا فتح حاصل ہو جائے۔ جن تین لوگوں سے اللہ تعالیٰ نفرت کرتا ہے وہ یہ ہیں: وہ بوڑھا جو زنا کار ہو، وہ فقیر جو تکبر کرنے والا ہو اور مالدار جو دوسروں پر ظلم ڈھائے“۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2568</td></tr><tr><td>Arabic No</td><td>2568</td></tr><tr><td>Reference</td><td>Book 38 Hadith 46</td></tr></tbody></table></div>