## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا الْحَسَنُ بْنُ مُحَمَّدٍ الزَّعْفَرَانِيُّ، حَدَّثَنَا عَفَّانُ بْنُ مُسْلِمٍ، حَدَّثَنَا حَفْصُ بْنُ غِيَاثٍ، حَدَّثَنَا حَبِيبُ بْنُ أَبِي عَمْرَةَ، عَنْ سَعِيدِ بْنِ جُبَيْرٍ، عَنِ ابْنِ عَبَّاسٍ، فِي قَوْلِ اللَّهِ عَزَّ وَجَلَّ ‏:‏ ‏(‏ما قَطَعْتُمْ مِنْ لِينَةٍ أَوْ تَرَكْتُمُوهَا قَائِمَةً عَلَى أُصُولِهَا ‏)‏ ‏.‏ قَالَ اللِّينَةُ النَّخْلَةُِيُخْزِيَ الْفَاسِقِينَ ‏)‏ قَالَ اسْتَنْزَلُوهُمْ مِنْ حُصُونِهِمْ قَالَ وَأَمَرُوا بِقَطْعِ النَّخْلِ فَحَكَّ فِي صُدُورِهِمْ ‏.‏ فَقَالَ الْمُسْلِمُونَ قَدْ قَطَعْنَا بَعْضًا وَتَرَكْنَا بَعْضًا فَلَنَسْأَلَنَّ رَسُولَ اللَّهِ صلى الله عليه وسلم هَلْ لَنَا فِيمَا قَطَعْنَا مِنْ أَجْرٍ وَهَلْ عَلَيْنَا فِيمَا تَرَكْنَا مِنْ وِزْرٍ فَأَنْزَلَ اللَّهُ تَعَالَى ‏:‏ ‏(‏ما قَطَعْتُمْ مِنْ لِينَةٍ أَوْ تَرَكْتُمُوهَا قَائِمَةً عَلَى أُصُولِهَا ‏)‏ ‏.‏ الآيَةَ ‏.‏ قَالَ أَبُو عِيسَى هَذَا حَدِيثٌ حَسَنٌ غَرِيبٌ ‏.‏ وَرَوَى بَعْضُهُمْ، هَذَا الْحَدِيثَ عَنْ حَفْصِ بْنِ غِيَاثٍ، عَنْ حَبِيبِ بْنِ أَبِي عَمْرَةَ، عَنْ سَعِيدِ بْنِ جُبَيْرٍ، مُرْسَلاً وَلَمْ يَذْكُرْ فِيهِ عَنِ ابْنِ عَبَّاسٍ، ‏.‏ حَدَّثَنِي بِذَلِكَ عَبْدُ اللَّهِ بْنُ عَبْدِ الرَّحْمَنِ، حَدَّثَنَا هَارُونُ بْنُ مُعَاوِيَةَ، عَنْ حَفْصِ بْنِ غِيَاثٍ، عَنْ حَبِيبِ بْنِ أَبِي عَمْرَةَ، عَنْ سَعِيدِ بْنِ جُبَيْرٍ، عَنِ النَّبِيِّ صلى الله عليه وسلم مُرْسَلاً ‏.‏ قَالَ أَبُو عِيسَى سَمِعَ مِنِّي مُحَمَّدُ بْنُ إِسْمَاعِيلَ هَذَا الْحَدِيثَ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih Isnaad</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih Isnaad</td><td>Al-Albani</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3303</td></tr><tr><td>Arabic No</td><td>3303</td></tr><tr><td>Reference</td><td>Book 47 Hadith 355</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
৩৩০৩। ইবনু আব্বাস (রাযিঃ) হতে বর্ণিত আছে, আল্লাহ তা'আলার বাণীঃ “যে খেজুর গাছগুলো তোমরা কেটেছ এবং তার কাণ্ডের উপর যেগুলো স্থির রেখে দিয়েছ" এ প্রসঙ্গে তিনি বলেন, আল-লীনাহ অর্থঃ খেজুর গাছ। “এবং এ কারণে যে, তিনি পাপাচারী ও অন্যায়কারীদেরকে লাঞ্ছিত করবেন" আয়াতটি প্রসঙ্গে তিনি বলেন, অর্থাৎ মুসলিমরা তাদেরকে তাদের দুর্গগুলো হতে বহিষ্কার করে দেয়। ইবনু আব্বাস (রাযিঃ) আরো বলেন, যখন তাদেরকে খেজুর গাছগুলো কেটে ফেলার আদেশ দেয়া হয় সে সময় তাদের মনে ধারণা (সন্দেহ) হয়। মুসলিমরা বলেন, আমরা কিছু বৃক্ষ কেটে ফেলেছি এবং কিছু বৃক্ষ বহাল রেখেছি। এ বিষয়ে অবশ্যই রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-কে আমরা প্রশ্ন করবো যে, যে গাছগুলো আমরা কেটেছি তার কারণে আমাদেরকে সাওয়াব প্রদান করা হবে কি এবং যে বৃক্ষগুলো বহাল রেখেছি তার জন্য আমাদের কোন গুনাহ হবে কি? তখন আল্লাহ তা'আলা অবতীর্ণ করেনঃ “যে খেজুর গাছগুলো তোমরা কেটেছ এবং তাদের কাণ্ডের উপর যেগুলো স্থির রেখে দিয়েছ তা তো আল্লাহ তা'আলার অনুমতিক্রমেই”- (সূরা হাশূর ৫)। হাদীসটির সানাদ সহীহ। আবূ ঈসা বলেন, এ হাদীসটি হাসান গারীব। এ হাদীসটি কিছু বর্ণনাকারী হাফস ইবনু গিয়াস হতে, তিনি হাবীব ইবনু আবী আমরাহ হতে, তিনি সাঈদ ইবনু জুবাইর (রহঃ) হতে এই সূত্রে মুরসালরূপে রিওয়ায়াত করেছেন এবং তার মধ্যে ইবনু আব্বাস (রাযিঃ)-এর উল্লেখ করেননি। আবদুল্লাহ ইবনু আবদুর রহমান-হারূন ইবনু মু'আবিয়াহ হতে, তিনি হাফস ইবনু গিয়াস হতে, তিনি হাবীব ইবনু আবী আমরাহ হতে, তিনি সাঈদ ইবনু জুবাইর (রাহঃ) হতে, তিনি নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম হতে এই সূত্রে মুরসালরূপে উক্ত হাদীস বর্ণনা করেছেন। আবূ ঈসা বলেন, এ হাদীসটি মুহাম্মাদ ইবনু ইসমাঈল আমার কাছে শুনেছেন।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih Isnaad</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih Isnaad</td><td>Al-Albani</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3303</td></tr><tr><td>Arabic No</td><td>3303</td></tr><tr><td>Reference</td><td>Book 47 Hadith 355</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Hafs bin Ghiyath narrated:“Habib bin Abi Amrah narrated to us, from Sa’eed bin Jubair, from Ibn Abbas, regarding the saying of Allah, the Mighty and Sublime: What you cut down of the Linah, or you left of them standing on their trunks – he said: ‘The Linah is the date-palms.’ That He might disgrace the rebellious. He said: ‘They were forced from their forts.’ And they were ordered to cut down the date-pals, that caused some hesitation in their chests, so the Muslims said: “We cut some of them, and we left some of them, so let us ask the Messenger of Allah is we are to be rewarded for those that we cut down, and if we will be burdened for what we left?” So Allah [Most High] revealed the Ayah: What you cut down of the Linah, or you left of them standing on their trunks.”
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih Isnaad</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih Isnaad</td><td>Al-Albani</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3303</td></tr><tr><td>Arabic No</td><td>3303</td></tr><tr><td>Reference</td><td>Book 47 Hadith 355</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Al Hasan bin Muhammad Az Za'farani] telah menceritakan kepada kami ['Affan bin Muslim] telah menceritakan kepada kami [Hafsh bin Ghiyats] telah menceritakan kepada kami [Habib bin Abu 'Amrah] dari [Sa'id bin Jubair] dari [Ibnu Abbas] mengenai firman Allah 'azza wajalla: "Apa saja yang kamu tebang dari pohon kurma (milik orang-orang kafir) atau yang kamu biarkan (tumbuh) berdiri di atas pokoknya, maka (semua itu) adalah dengan izin Allah; dan karena Dia hendak memberikan kehinaan kepada orang-orang fasik." (QS.Alhasyr 5), Beliau bersabda: Maksud Allinah adalah pohon kurma. Dan maksud untuk menghinakan orang-orang fasik ialah"Para sahabat menurunkan mereka dari benteng-benteng mereka." Ibnu Abbas berkata; dan mereka diperintahkan agar memotong pohon kurma. Kemudian mereka merasa ragu, lalu orang-orang muslim berkata; kami telah memotong sebagian dan membiarkan sebagian, sungguh kami akan bertanya kepada Rasulullah shallallahu 'alaihi wasallam; apakah kami mendapatkan pahala pada apa yang telah kami tebang? Dan apakah kami mendapatkan dosa atas apa yang kami biarkan? Kemudian Allah ta'ala menurunkan ayat: "Apa saja yang kamu tebang dari pohon kurma (milik orang-orang kafir) atau yang kamu biarkan (tumbuh) berdiri di atas pokoknya, maka (semua itu) adalah dengan izin Allah; dan karena Dia hendak memberikan kehinaan kepada orang-orang fasik." (QS.Alhasyr 5), Abu Isa berkata; hadits ini adalah hadits hasan gharib, dan sebagian mereka meriwayatkan hadits ini dari Hafsh bin Ghiyats dari Habib bin Abu 'Amrah dari Sa'id bin Jubair secara mursal, dan belum menyebutkan padanya dari Ibnu Abbas. Telah menceritakan kepadaku hal tersebut [Abdullah bin Abdur Rahman] telah menceritakan kepada kami [Harun bin Mu'awiyah] dari [Hafsh bin Ghiyats] dari [Habib bin Abu 'Amrah] dari [Sa'id bin Jubair] dari Nabi shallallahu 'alaihi wasallam secara mursal. Abu Isa berkata; Muhammad bin Isma'il telah menyebutkan dariku
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih Isnaad</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih Isnaad</td><td>Al-Albani</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3303</td></tr><tr><td>Arabic No</td><td>3303</td></tr><tr><td>Reference</td><td>Book 47 Hadith 355</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
İbn Abbâs (r.a.)’den rivâyete göre, Haşr sûresi 5. ayetindeki: “Lîne” kelimesi hurma anlamındadır, demiştir. “Allah’ın yoldan çıkanları cezalandırması içindir.” Sözünü ise şöyle tefsir etti: Onlardan kalelerinden inmelerini istediler. Kendilerine de hurmalarını kesmeleri emredildi ve yüreklerine bir kuşku düştü. Müslümanlar dediler ki: Bir kısmını kestik bir kısmını bıraktık. Rasûlullah (s.a.v.)’e mutlaka soracağız. Kestiklerimizden dolayı sevap bıraktıklarımızdan dolayı günahımız var mı? Bunun üzerine Allah, Haşr süresi 5. ayetini indirdi: “Onların hurma ağaçlarından her ne kestiyseniz veya kökleri üzerinde her ne bıraktıysanız, hepsi Allah’ın izniyle olmuştur ve bu izin, Allah’ın yoldan çıkanları cezalandırması içindir.”
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih Isnaad</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih Isnaad</td><td>Al-Albani</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3303</td></tr><tr><td>Arabic No</td><td>3303</td></tr><tr><td>Reference</td><td>Book 47 Hadith 355</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
عبداللہ بن عباس رضی الله عنہما آیت «ما قطعتم من لينة أو تركتموها قائمة على أصولها» کی تفسیر میں فرماتے ہیں: «لينة» سے مراد کھجور کے درخت ہیں اور «وليخزي الفاسقين» ( تاکہ اللہ فاسقوں کو ذلیل کرے ) کے بارے میں کہتے ہیں: ان کی ذلت یہی ہے کہ مسلمانوں نے انہیں ان کے قلعوں سے نکال بھگایا اور ( مسلمانوں کو یہود کے ) کھجور کے درخت کاٹ ڈالنے کا حکم دیا گیا، تو ان کے دلوں میں یہ بات کھٹکی، مسلمانوں نے کہا: ہم نے بعض درخت کاٹ ڈالے اور بعض چھوڑ دیئے ہیں تو اب ہم رسول اللہ صلی اللہ علیہ وسلم سے پوچھیں گے کہ ہم نے جو درخت کاٹے ہیں کیا ہمیں ان کا کچھ اجر و ثواب ملے گا، اور جو درخت ہم نے نہیں کاٹے ہیں کیا ہمیں اس کا کچھ عذاب ہو گا؟ تو اللہ نے یہ آیت نازل فرمائی، «ما قطعتم من لينة أو تركتموها قائمة على أصولها» ”تم نے کھجوروں کے جو درخت کاٹ ڈالے یا جنہیں تم نے ان کی جڑوں پر باقی رہنے دیا، یہ سب اللہ تعالیٰ کے فرمان سے تھا اور اس لیے بھی تھا کہ اللہ فاسقوں کو رسوا کرے“۔ امام ترمذی کہتے ہیں: یہ حدیث حسن غریب ہے۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih Isnaad</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih Isnaad</td><td>Al-Albani</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3303</td></tr><tr><td>Arabic No</td><td>3303</td></tr><tr><td>Reference</td><td>Book 47 Hadith 355</td></tr></tbody></table></div>