## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا ابْنُ أَبِي عُمَرَ، حَدَّثَنَا سُفْيَانُ، عَنْ أَبِي إِسْحَاقَ، عَنْ زَيْدِ بْنِ يُثَيْعٍ، قَالَ سَأَلْنَا عَلِيًّا بِأَىِّ شَيْءٍ بُعِثْتَ فِي الْحَجَّةِ قَالَ بُعِثْتُ بِأَرْبَعٍ أَنْ لاَ يَطُوفَ بِالْبَيْتِ عُرْيَانٌ وَمَنْ كَانَ بَيْنَهُ وَبَيْنَ النَّبِيِّ صلى الله عليه وسلم عَهْدٌ فَهُوَ إِلَى مُدَّتِهِ وَمَنْ لَمْ يَكُنْ لَهُ عَهْدٌ فَأَجَلُهُ أَرْبَعَةُ أَشْهُرٍ وَلاَ يَدْخُلُ الْجَنَّةَ إِلاَّ نَفْسٌ مُؤْمِنَةٌ وَلاَ يَجْتَمِعُ الْمُشْرِكُونَ وَالْمُسْلِمُونَ بَعْدَ عَامِهِمْ هَذَا ‏.‏ قَالَ أَبُو عِيسَى هَذَا حَدِيثٌ حَسَنٌ وَهُوَ حَدِيثُ سُفْيَانَ بْنِ عُيَيْنَةَ عَنْ أَبِي إِسْحَاقَ وَرَوَاهُ الثَّوْرِيُّ عَنْ أَبِي إِسْحَاقَ عَنْ بَعْضِ أَصْحَابِهِ عَنْ عَلِيٍّ ‏.‏ وَفِي الْبَابِ عَنْ أَبِي هُرَيْرَةَ ‏.‏ حَدَّثَنَا نَصْرُ بْنُ عَلِيٍّ، وَغَيْرُ، وَاحِدٍ، قَالُوا حَدَّثَنَا سُفْيَانُ بْنُ عُيَيْنَةَ، عَنْ أَبِي إِسْحَاقَ، عَنْ زَيْدِ بْنِ يُثَيْعٍ، عَنْ عَلِيٍّ، نَحْوَهُ ‏.‏ حَدَّثَنَا عَلِيُّ بْنُ خَشْرَمٍ، حَدَّثَنَا سُفْيَانُ بْنُ عُيَيْنَةَ، عَنْ أَبِي إِسْحَاقَ، عَنْ زَيْدِ بْنِ أُثَيْعٍ، عَنْ عَلِيٍّ، نَحْوَهُ ‏.‏ قَالَ أَبُو عِيسَى وَقَدْ رُوِيَ عَنِ ابْنِ عُيَيْنَةَ، كِلْتَا الرِّوَايَتَيْنِ يُقَالُ عَنْهُ عَنِ ابْنِ أُثَيْعٍ، وَعَنِ ابْنِ يُثَيْعٍ، وَالصَّحِيحُ، هُوَ زَيْدُ بْنُ أُثَيْعٍ وَقَدْ رَوَى شُعْبَةُ، عَنْ أَبِي إِسْحَاقَ، عَنْ زَيْدٍ، غَيْرَ هَذَا الْحَدِيثِ فَوَهِمَ فِيهِ وَقَالَ زَيْدُ بْنُ أُثَيْلٍ وَلاَ يُتَابَعُ عَلَيْهِ ‏.‏ وَفِي الْبَابِ عَنْ أَبِي هُرَيْرَةَ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3092</td></tr><tr><td>Arabic No</td><td>3092</td></tr><tr><td>Reference</td><td>Book 47 Hadith 144</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
৩০৯২। যাইদ ইবনু ইউসাই (রহঃ) হতে বর্ণিত, তিনি বলেন, আমরা আলী (রাযিঃ)-কে প্রশ্ন করলাম, আপনাকে হাজ্জ উপলক্ষে কোন জিনিস সহকারে পাঠানো হয়েছিল। তিনি বললেন, আমাকে (হাজ্জে) চারটি বিষয় সহকারে পাঠানো হয়েছিলঃ (১) কোন উলঙ্গ ব্যক্তি বাইতুল্লাহ তাওয়াফ করতে পারবে না; (২) যাদের সাথে নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর চুক্তি আছে তা তার নির্দিষ্ট মেয়াদ পর্যন্ত কার্যকর থাকবে আর যাদের সাথে তার কোন চুক্তি নেই তারা চার মাসের অবকাশ পাবে (নিরাপত্তা সহকারে বিচরণ করার); (৩) মুমিন ব্যতীত কোন ব্যক্তি জান্নাতে যেতে পারবে না এবং (৪) এ বছরের পর মুসলিমগণ ও মুশরিকরা (হাজ্জে) একত্র হতে পারবে না (এরপর হতে মুশরিকদের জন্য হজ্জে যোগদান চিরতরে নিষিদ্ধ)। সহীহঃ (৮৭১) নং হাদীস পূর্বে বর্ণিত হয়েছে। আবূ ঈসা বলেন, এ হাদীসটি হাসান সহীহ। এটি আবূ ইসহাক হতে ইবনু উয়াইনার বর্ণিত হাদীস। সুফইয়ান সাওরীও এটি আবূ ইসহাক হতে, তিনি তার কোন সহযোগী হতে, তিনি আলী (রাযিঃ) হতে এই সূত্রে বর্ণনা করেছেন। আবূ হুরাইরাহ (রাযিঃ) হতেও এ অনুচ্ছেদে হাদীস বর্ণিত আছে। নাসর ইবনু আলী প্রমুখ সুফিয়ান ইবনু উয়াইনাহ হতে, তিনি আবু ইসহাক হতে, তিনি যাইদ ইবনু ইউসাই হতে, তিনি আলী (রাযিঃ) সূত্রে পূর্বোক্ত হাদীসের মত বর্ণনা করেছেন। আলী ইবনু খাশরাম-সুফইয়ান ইবনু তিনি আলী (রাযিঃ) হতে এই সূত্রে একই রকম বর্ণনা করেছেন। আবূ ঈসা বলেন, ইবনু উয়াইনাহ উভয় রিওয়ায়াত ইবনু উসাই ও ইবনু ইউসাই উভয়ের সূত্রে বর্ণনা করেছেন। সঠিক হল যাইদ ইবনু উসাই। শু'বাহ (রাহঃ) উক্ত হাদীস ব্যতীত অন্য হাদীস আবূ ইসহাকের সূত্রে বর্ণনা করেছেন এবং তাতে সন্দেহে পতিত হয়েছেন এবং যাইদ ইবনু উসাইল নাম বলেছেন; কিন্তু এ ক্ষেত্রে শু’বাহর অনুসরণ করা হয়নি।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3092</td></tr><tr><td>Arabic No</td><td>3092</td></tr><tr><td>Reference</td><td>Book 47 Hadith 144</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated Zaid bin Yuthai':"We asked 'Ali what he had been dispatched with during the Hajj. He said: 'I was sent with four: That there shall be no Tawaf around the House while naked, that if there is a treaty between someone and the Prophet (ﷺ), then the treaty remains until its expiration, and whoever does not have a treaty, then he has the span of four months, none shall enter Paradise except a believer, and the idolaters and Muslims shall not congregate (for Hajj) after this year.'" [Abu 'Eisa said:] This Hadith is Hasan Sahih. It is the narration of [Sufyan] bin 'Uyainah from Abu Ishaq. Sufyan Ath-Thawri reported it from Abu Ishaq, from some of his companions, from 'Ali, and there is something about it from Abü Hurairah. (Another chain) from Zaid bin Yuthai' from 'Ali with similar wordings. (Another chain) Zaid bin Uthal' from 'Ali with similar wordings. [Abu 'Eisa said:] Both narrations have been reported from Ibn 'Uyainah; from Ibn Uthai' and from Ibn Yuthai'. What is correct is that he is Zaid bin Yuthai'. Shu'bah reported a different narration from Abu Ishaq [from Zaid], and he was mistaken in it, he said: "From Zaid bin Uthail" and no one corroborated him in that. [There is something on this topic from Abu Hurairah]
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3092</td></tr><tr><td>Arabic No</td><td>3092</td></tr><tr><td>Reference</td><td>Book 47 Hadith 144</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Ibnu Abi Umar] telah menceritakan kepada kami [Sufyan] dari [Abu Ishaq] dari [Zaid bin Yutsai'] berkata: Kami bertanya kepada [Ali], apa yang diutuskan padamu saat haji? Ia menjawab: Aku diutus (untuk menyampaikan) empat hal; tidak boleh thawaf dengan telanjang, siapa pun yang punya janji dengan nabi Shallallahu 'alaihi wa Salam, janji itu berlaku hingga batas waktunya dan siapa pun yang tidak memiliki perjanjian, batas waktunya empat bulan, tidak masuk surga kecuali jiwa yang mu'min dan kaum musyrik tidak boleh menyatu dengan kaum muslimin setelah tahun mereka ini. Abu Isa berkata: Hadits ini hasan shahih dari hadits Sufyan bin Uyainah dari Abu Ishaq. [Ats Tsauri] meriwayatkannya dari [Abu Ishaq] dari [sebagaian sahabatnya] dari [Ali]. Dalam hal ini ada hadits serupa dari Abu Hurairah. Telah menceritakan kepada kami [Nashr bin Ali] dan lainnya, mereka berkata: Telah menceritakan kepada kami [Sufyan bin Uyainah] dari [Abu Ishaq] dari [Zaid bin Yutsai'] dari [Ali] sepertinya. Telah menceritakan kepada kami [Ali bin Khasyram] telah menceritakan kepada kami [Sufyan bin Uyainah] dari [Abu Ishaq] dari [Zaid bin Yutsai'] dari [Ali] sepertinya. Abu Isa berkata: Kedua hadits ini diriwayatkan dari Ibnu Uyainah, ada yang mengatakan dari Ibnu Utsyai' dan dari Ibnu Yusatai', yang benar dia adalah Zaid bin Yutsyai'. Syu'bah meriwayatkan bukan hadits ini dari Abu Ishaq dari Zaid lalu ia salah Didalamnya dan berkata: Zaid bin Utsail, tapi kesalahan ini tidak diteliti
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3092</td></tr><tr><td>Arabic No</td><td>3092</td></tr><tr><td>Reference</td><td>Book 47 Hadith 144</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Zeyd b. Yüseyyi (radıyallahü anh)’den rivâyete göre, şöyle demiştir: Ali’ye, hac mevsiminde hangi emirlerle gönderilmiştin diye sorduk. Dedi ki: Dört şeyle gönderilmiştim; Çıplak olarak Ka’be tavaf edilmeyecektir, Peygamber (sallallahü aleyhi ve sellem) ile bir müşrik arasında bir sözleşme varsa o sözleşme bitimine kadar devam edecektir. Anlaşması olmayanların süresi dört aydır, Cennete ancak mü’min olan kimse girecektir. Bu seneden sonra hac ve umre için Müslümanlarla müşrikler bir araya gelemeyeceklerdir. (Tirmizî rivâyet etmiştir.) Bu hadis hasendir. Sûfyân b. Uyeyne bu hadisi Ebû İshâk’tan rivâyet etmiştir. Sevrî ise bu hadisi Ebû İshâk’tan, Ebû İshâk’ın bazı arkadaşlarından ve Ali’den rivâyet etmiştir
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3092</td></tr><tr><td>Arabic No</td><td>3092</td></tr><tr><td>Reference</td><td>Book 47 Hadith 144</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
زید بن یثیع کہتے ہیں کہ میں نے علی رضی الله عنہ سے پوچھا: آپ حج میں کیا پیغام لے کر بھیجے گئے تھے؟ کہا: میں چار چیزوں کا اعلان کرنے کے لیے بھیجا گیا تھا ( ایک یہ کہ ) کوئی ننگا بیت اللہ کا طواف ( آئندہ ) نہیں کرے گا۔ ( دوسرے ) یہ کہ جس کافر اور نبی اکرم صلی اللہ علیہ وسلم کے درمیان کوئی معاہدہ ہے وہ معاہدہ مدت ختم ہونے تک قائم رہے گا اور جن کا کوئی معاہدہ نہیں ان کے لیے چار ماہ کی مدت ہو گی ۱؎ ( تیسرے ) یہ کہ جنت میں صرف ایمان والا ( مسلمان ) ہی داخل ہو سکے گا۔ ( چوتھے یہ کہ ) اس سال کے بعد مسلم و مشرک دونوں حج نہ کر سکیں گے ۲؎۔ امام ترمذی کہتے ہیں: ۱- یہ حدیث سفیان بن عیینہ کی روایت سے جسے وہ ابواسحاق سے روایت کرتے ہیں حسن صحیح ہے، ۲- اسے سفیان ثوری نے ابواسحاق کے بعض اصحاب سے روایت کی ہے اور انہوں نے علی رضی الله عنہ سے روایت کی ہے، ۳- اس باب میں ابوہریرہ رضی الله عنہ سے بھی روایت ہے۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3092</td></tr><tr><td>Arabic No</td><td>3092</td></tr><tr><td>Reference</td><td>Book 47 Hadith 144</td></tr></tbody></table></div>