## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
قَالَتْ زَيْنَبُ وَسَمِعْتُ أُمِّي أُمَّ سَلَمَةَ، تَقُولُ جَاءَتِ امْرَأَةٌ إِلَى رَسُولِ اللَّهِ صلى الله عليه وسلم فَقَالَتْ يَا رَسُولَ اللَّهِ إِنَّ ابْنَتِي تُوُفِّيَ عَنْهَا زَوْجُهَا وَقَدِ اشْتَكَتْ عَيْنَيْهَا أَفَنَكْحَلُهَا فَقَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏"‏ لاَ ‏"‏ مَرَّتَيْنِ أَوْ ثَلاَثَ مَرَّاتٍ كُلُّ ذَلِكَ يَقُولُ ‏"‏ لاَ ‏"‏ ‏.‏ ثُمَّ قَالَ ‏"‏ إِنَّمَا هِيَ أَرْبَعَةُ أَشْهُرٍ وَعَشْرًا وَقَدْ كَانَتْ إِحْدَاكُنَّ فِي الْجَاهِلِيَّةِ تَرْمِي بِالْبَعْرَةِ عَلَى رَأْسِ الْحَوْلِ ‏"‏ ‏.‏ قَالَ وَفِي الْبَابِ عَنْ فُرَيْعَةَ بِنْتِ مَالِكٍ أُخْتِ أَبِي سَعِيدٍ الْخُدْرِيِّ وَحَفْصَةَ بِنْتِ عُمَرَ ‏.‏ قَالَ أَبُو عِيسَى حَدِيثُ زَيْنَبَ حَدِيثٌ حَسَنٌ صَحِيحٌ ‏.‏ - وَالْعَمَلُ عَلَى هَذَا عِنْدَ أَصْحَابِ النَّبِيِّ صلى الله عليه وسلم وَغَيْرِهِمْ أَنَّ الْمُتَوَفَّى عَنْهَا زَوْجُهَا تَتَّقِي فِي عِدَّتِهَا الطِّيبَ وَالزِّينَةَ ‏.‏ وَهُوَ قَوْلُ سُفْيَانَ الثَّوْرِيِّ وَمَالِكِ بْنِ أَنَسٍ وَالشَّافِعِيِّ وَأَحْمَدَ وَإِسْحَاقَ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1197</td></tr><tr><td>Arabic No</td><td>1197</td></tr><tr><td>Reference</td><td>Book 13 Hadith 24</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
১১৯৭। (তিন), যাইনাব (রাঃ) বলেন, আমি আমার মা উম্মু সালামা (রাঃ)-কে বলতে শুনেছিঃ রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লামের নিকট এক মহিলা এসে বলল, হে আল্লাহর রাসূল! আমার মেয়ের স্বামী মৃত্যুবরণ করেছে। ইদানীং তার দুই চোখে অসুখ দেখা দিয়েছে। আমরা তার চোখে সুরমা লাগাতে পারব কি? রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বললেনঃ না। মহিলাটি দুই কি তিনবার এই প্রশ্ন করল এবং প্রতি বারেই তিনি (রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম) বললেনঃ না। তারপর তিনি বললেনঃ এটা তো মাত্র চার মাস দশ দিনের ব্যাপার। জাহিলী যুগে তোমাদের কোন মহিলাকে এক বছর পর্যন্ত শোক পালন শেষে বিষ্ঠা নিক্ষেপ করে ইদ্দাতকে সমাপ্ত করতে হত। — সহীহ, প্রাগুক্ত মালিক ইবনু সিনানের কন্যা এবং আবু সাঈদ আল-খুদরী (রাঃ)-এর বোন ফুরাইআ ও উমার (রাঃ)-এর কন্যা হাফসা (রাঃ) হতেও এ অনুচ্ছেদে হাদীস বর্ণিত আছে। আবু ঈসা বলেন, যাইনাব (রাঃ) হতে বর্ণিত হাদীসটি হাসান সহীহ। এ হাদীস অনুযায়ী রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লামের সাহাবী ও অন্যান্য আলিম মত দিয়েছেন। তাদের মতে যে মহিলার স্বামী মৃত্যুবরণ করেছে সে মহিলা ইদাতের সময় সুগন্ধি ও সাজসজ্জা বর্জন করবে। এই মত দিয়েছেন সুফিয়ান সাওরী, মালিক, শাফিঈ, আহমাদ ও ইসহাক।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1197</td></tr><tr><td>Arabic No</td><td>1197</td></tr><tr><td>Reference</td><td>Book 13 Hadith 24</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Humaid bin Nafi narrated that :Zainab said: "And I heard my mother, Umm Salamah said: 'A woman came to the Messenger of Allah and she said: "O Messenger of Allah! My daughter's husband died, and she is suffering from an eye ailment, so can she use Kohl?" the Messenger of Allah said: "No" two or three time. Each time (she asked) he said "no." Then he said: "It is just a mater of four months and ten (days). During Jahliyyah one of you would throw a clump of camel dung when one year passed
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1197</td></tr><tr><td>Arabic No</td><td>1197</td></tr><tr><td>Reference</td><td>Book 13 Hadith 24</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
[Zainab] berkata; Dan aku pun mendengar ibuku, [Ummu Salamah], berkata; Ada seorang wanita datang menemui Rasulullah shallallahu 'alaihi wasallam seraya berkata; Wahai Rasulullah, sesungguhnya anak perempuanku ditinggal mati suaminya dan kedua matanya sakit, bolehkah kami memberi celak pada matanya? Maka Rasulullah shallallahu 'alaihi wasallam menjawab: "Jangan." Beliau mengatakan dua atau tiga kali, setiap pertanyaan beliau menjawab: "Jangan." Kemudian beliau bersabda: "Sesungguhnya iddahnya adalah empat bulan sepuluh hari, pada masa jahiliyah salah seorang dari kalian (berkabung) dengan cara melempar kotoran unta pada penghujung akhir tahun." Ia mengatakan; Dalam hal ini ada hadits serupa dari Furai'ah binti Malik saudari Abu Sa'id Al Khudri dan Hafshah binti Umar. Abu Isa berkata; Hadits Zainab adalah hadits hasan shahih serta menjadi pedoman amal menurut kalangan sahabat Nabi shallallahu 'alaihi wasallam dan selain mereka, bahwa seorang wanita yang ditinggal mati suaminya, harus menjauhkan diri dari wewangian dan berhias pada masa iddahnya. Dan ini pendapat Sufyan Ats Tsauri, Malik bin Anas, Asy Syafi'i, Ahmad dan Ishaq
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1197</td></tr><tr><td>Arabic No</td><td>1197</td></tr><tr><td>Reference</td><td>Book 13 Hadith 24</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Zeyneb (r.anha) diyor ki: Annem Ümmü Seleme’den işittim diyordu ki: Bir kadın, Rasûlullah (s.a.v.)’e geldi ve dedi ki: “Ey Allah’ın Rasûlü! Kızımın kocası vefat etti kızım da gözlerinden rahatsız oldu onun gözüne sürme çekebilir miyiz? Rasûlullah (s.a.v.) iki veya üç sefer hayır dedi. Her seferinde hayır olamaz buyurdu sonra şöyle devam etti: Vefat, iddeti dört ay on gündür. Oysa sizler cahiliyye zamanında iddeti bir yıl bekler sene sonunda deve tezeği atmak suretiyle bu süreyi doldurdu.” Diğer tahric: Müslim, Talak; Buhârî, Talak Tirmîzî: Bu konuda Füreya binti Mâlik, (ki Ebû Saîd el Hudrî’nin kız kardeşidir.) ve Hafsa binti Ömer’den de hadis rivâyet edilmiştir. Tirmîzî: Zeyneb hadisi hasen sahihtir. Rasûlullah (s.a.v.)’in ashabından ve daha sonraki dönemlerden bir kısım ilim adamlarının uygulaması bu hadise göredir. Yani kocası ölen kadın vefat iddeti süresi olan dört ay on gün içersinde güzel koku ve süslenmekten sakınır. Sûfyân es Sevrî, Mâlik b. Enes, Şâfii, Ahmed ve İshâk’ta bu görüştedirler
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1197</td></tr><tr><td>Arabic No</td><td>1197</td></tr><tr><td>Reference</td><td>Book 13 Hadith 24</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
(تیسری حدیث یہ ہے) زینب کہتی ہیں میں نے اپنی ماں ام المؤمنین ام سلمہ رضی الله عنہا کو کہتے سنا کہ رسول اللہ صلی اللہ علیہ وسلم کے پاس ایک عورت نے آ کر عرض کیا: اللہ کے رسول! میری بیٹی کا شوہر مر گیا ہے، اور اس کی آنکھیں دکھ رہی ہیں، کیا ہم اس کو سرمہ لگا دیں؟ رسول اللہ صلی اللہ علیہ وسلم نے فرمایا: ”نہیں“۔ دو یا تین مرتبہ اس عورت نے آپ سے پوچھا اور آپ نے ہر بار فرمایا: ”نہیں“، پھر آپ نے فرمایا: ” ( اب تو اسلام میں ) عدت چار ماہ دس دن ہے، حالانکہ جاہلیت میں تم میں سے ( فوت شدہ شوہر والی بیوہ ) عورت سال بھر کے بعد اونٹ کی مینگنی پھینکتی تھی“ ۱؎۔ امام ترمذی کہتے ہیں: ۱- زینب کی حدیث حسن صحیح ہے، ۲- اس باب میں ابو سعید خدری کی بہن فریعہ بنت مالک، اور حفصہ بنت عمر رضی الله عنہما سے بھی احادیث آئی ہیں، ۳- صحابہ کرام وغیرہم کا اسی پر عمل ہے کہ جس عورت کا شوہر مر گیا ہو وہ اپنی عدت کے دوران خوشبو اور زینت سے پرہیز کرے گی۔ سفیان ثوری، مالک بن انس، شافعی، احمد اور اسحاق بن راہویہ کا بھی یہی قول ہے۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1197</td></tr><tr><td>Arabic No</td><td>1197</td></tr><tr><td>Reference</td><td>Book 13 Hadith 24</td></tr></tbody></table></div>