## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا عَبْدُ اللَّهِ بْنُ عَبْدِ الرَّحْمَنِ، قَالَ أَخْبَرَنَا أَحْمَدُ بْنُ أَبِي شُعَيْبٍ الْحَرَّانِيُّ، قَالَ حَدَّثَنِي مُحَمَّدُ بْنُ سَلَمَةَ الْحَرَّانِيُّ، عَنْ مُحَمَّدِ بْنِ إِسْحَاقَ، عَنْ مُحَمَّدِ بْنِ إِبْرَاهِيمَ، عَنْ مَالِكِ بْنِ أَبِي عَامِرٍ، قَالَ جَاءَ رَجُلٌ إِلَى طَلْحَةَ بْنِ عُبَيْدِ اللَّهِ فَقَالَ يَا أَبَا مُحَمَّدٍ أَرَأَيْتَ هَذَا الْيَمَانِيَ يَعْنِي أَبَا هُرَيْرَةَ هُوَ أَعْلَمُ بِحَدِيثِ رَسُولِ اللَّهِ صلى الله عليه وسلم مِنْكُمْ نَسْمَعُ مِنْهُ مَا لاَ نَسْمَعُ مِنْكُمْ أَوْ يَقُولُ عَلَى رَسُولِ اللَّهِ صلى الله عليه وسلم مَا لَمْ يَقُلْ ‏.‏ قَالَ أَمَّا أَنْ يَكُونَ سَمِعَ مِنْ رَسُولِ اللَّهِ صلى الله عليه وسلم مَا لَمْ نَسْمَعْ فَلاَ أَشُكُّ إِلاَّ أَنَّهُ سَمِعَ مِنْ رَسُولِ اللَّهِ صلى الله عليه وسلم مَا لَمْ نَسْمَعْ وَذَاكَ أَنَّهُ كَانَ مِسْكِينًا لاَ شَىْءَ لَهُ ضَيْفًا لِرَسُولِ اللَّهِ صلى الله عليه وسلم يَدُهُ مَعَ يَدِ رَسُولِ اللَّهِ صلى الله عليه وسلم وَكُنَّا نَحْنُ أَهْلَ بُيُوتَاتٍ وَغِنًى وَكُنَّا نَأْتِي رَسُولَ اللَّهِ صلى الله عليه وسلم طَرَفَىِ النَّهَارِ فَلاَ نَشُكُّ إِلاَّ أَنَّهُ سَمِعَ مِنْ رَسُولِ اللَّهِ صلى الله عليه وسلم مَا لَمْ نَسْمَعْ وَلاَ نَجِدُ أَحَدًا فِيهِ خَيْرٌ يَقُولُ عَلَى رَسُولِ اللَّهِ صلى الله عليه وسلم مَا لَمْ يَقُلْ ‏.‏ قَالَ أَبُو عِيسَى هَذَا حَدِيثٌ حَسَنٌ غَرِيبٌ لاَ نَعْرِفُهُ إِلاَّ مِنْ حَدِيثِ مُحَمَّدِ بْنِ إِسْحَاقَ ‏.‏ وَقَدْ رَوَاهُ يُونُسُ بْنُ بُكَيْرٍ وَغَيْرُهُ عَنْ مُحَمَّدِ بْنِ إِسْحَاقَ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif Isnaad</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Daif Isnaad</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3837</td></tr><tr><td>Arabic No</td><td>3837</td></tr><tr><td>Reference</td><td>Book 49 Hadith 237</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
৩৮৩৭। মালিক ইবনু আবূ আমির (রহঃ) হতে বর্ণিত আছে, তিনি বলেন, এক লোক তালহা ইবনু উবাইদুল্লাহ (রাঃ)-এর নিকট এসে বলল, হে আবূ মুহাম্মাদ! ঐ ইয়ামানী লোকটি অর্থাৎ আবূ হুরাইরা (রাঃ) প্রসঙ্গে আপনার কি বক্তব্য? তিনি কি আপনাদের চাইতে রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লামের হাদীস অনেক বেশি জানেন? তার নিকট আমরা এমন কিছু হাদীস শুনি যা আপনাদের নিকট শুনতে পাই না। অথবা তিনি কি রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লামের বরাতে এমন কথা বলেন যা প্রকৃতপক্ষে তিনি বলেননি? তালহা (রাঃ) বললেন, বস্তুত তিনি রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম হতে এ হাদীস শুনেছেন যা আমরা শুনতে পারিনি। তার কারণ এই যে, তিনি ছিলেন একজন গারীব লোক, তার কিছুই ছিল না। তিনি ছিলেন রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লামের অতিথি। তার হাত থাকত রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লামের হাতের সাথে (অর্থাৎ সব সময় তার সঙ্গে থাকতেন)। আর আমরা ছিলাম বাড়ি-ঘর ও পরিবার-পরিজনসহ ধনবান। তাই আমরা রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লামের খিদমাতে হাযির হওয়ার সুযোগ পেতাম দিনের দুই ভাগে (সকাল ও সন্ধ্যায়)। তাই নিঃসন্দেহে তিনি অবশ্যই রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লামের বাণী শুনেছেন, যা আমরা শুনিনি। আর তুমি এমন একজন সৎ লোকও খুঁজে পাবে না যিনি রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লামের বরাতে এমন কথা বলবেন, যা সত্যিকার আর্থে তিনি বলেননি। সনদ দুর্বল আবূ ঈসা বলেনঃ এ হাদীসটি হাসান গারীব। আমরা শুধু মুহাম্মাদ ইবনু ইসহাকের সূত্রেই এ হাদীস জেনেছি। অবশ্য ইউসুফ ইবনু বুকাইর প্রমুখগণ এ হাদীস মুহাম্মাদ ইবনু ইসহাক হতে বর্ণনা করেছেন।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif Isnaad</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Daif Isnaad</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3837</td></tr><tr><td>Arabic No</td><td>3837</td></tr><tr><td>Reference</td><td>Book 49 Hadith 237</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated Malik bin Abi 'Amir:"A man came to Talhah bin 'Ubaidullah and said: 'O Abu Muhammad, do you see this Yemeni - meaning: Abu Hurairah - is he more knowledgeable of the Ahadith of the Messenger of Allah (ﷺ) than you? We hear from him what we do not hear from you, or does he attribute to the Messenger of Allah (ﷺ) what he did not say?' He said: 'As for his having heard from the Messenger of Allah (ﷺ) what we did not hear from him, then that is because he was poor, having nothing, a guest of the Messenger of Allah (ﷺ), his hand was in the hand of the Messenger of Allah (ﷺ). And we used to be people of houses and wealth, and we used to come to the Messenger of Allah (ﷺ) at the two ends of the day. I do not doubt that he heard from the Messenger of Allah (ﷺ) what we did not hear, and you will not find anyone in whom there is good attributing to the Messenger of Allah (ﷺ) what he did not say
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif Isnaad</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Daif Isnaad</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3837</td></tr><tr><td>Arabic No</td><td>3837</td></tr><tr><td>Reference</td><td>Book 49 Hadith 237</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Abdullah bin Abdurrahman] telah mengabarkan kepada kami [Ahmad bin Abu Syu'aib Al Harrani] telah mengabarkan kepada kami [Muhammad bin Salamah Al Harrani] dari [Muhammad bin Ishaq] dari [Muhammad bin Ibrahim] dari [Malik bin Abu 'Amir] dia berkata; seorang laki-laki datang menemui [Thalhah bin Ubaidillah] seraya berkata; "Wahai Abu Muhammad, apakah anda tahu orang dari Yaman ini -maksudnya Abu Hurairah-, apakah dia lebih mengetahui tentang hadits Rasulullah shallallahu 'alaihi wasallam dari pada kalian?, karena kami telah mendengar darinya apa yang belum pernah kami mendengarnya dari kalian, atau dia cuma mengatakan atas nama Rasulullah shallallahu 'alaihi wasallam sesuatu yang belum pernah beliau sabdakan." Thalhah berkata; "Adapun perkataannya, bahwa dia pernah mendengar Rasulullah shallallahu 'alaihi wasallam terhadap sesuatu yang belum pernah kami dengar, maka aku tidak ragu lagi akan hal itu, bahwa dia memang mendengar Rasulullah shallallahu 'alaihi wasallam sesuatu yang belum pernah kami dengar, sebab dia adalah orang miskin yang tidak memiliki sesuatu, dia sebagai tamu Rasulullah shallallahu 'alaihi wasallam. tangannya selalu menyertai tangan Rasulullah shallallahu 'alaihi wasallam, sedangkan kami memiliki rumah-rumah dan selalu kecukupan, kami datang kepada Rasulullah shallallahu 'alaihi wasallam hanya di awal dan di akhir siang, maka aku tidak ragu lagi bila dia mendengar sesuatu dari Rasulullah shallallahu 'alaihi wasallam apa yang tidak kami dengar, dan kami juga tidak pernah mendapati seseorang yang memiliki kebaikan, yang berkata atas nama Rasulullah shallallahu 'alaihi wasallam terhadap sesuatu yang tidak beliau katakan." Abu Isa berkata; "Hadits ini adalah hadits gharib, kami tidak mengenalnya kecuali dari hadits Muhammad bin Ishaq, [Yunus bin Bukair] dan yang lain juga meriwayatkan hadits tersebut dari [Muhammad bin Ishaq]
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif Isnaad</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Daif Isnaad</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3837</td></tr><tr><td>Arabic No</td><td>3837</td></tr><tr><td>Reference</td><td>Book 49 Hadith 237</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Mâlik b. ebî Âmir (r.a.)’den rivâyete göre, şöyle demiştir: Bir adam Talha b. Ubeydullah’a gelip; “Ey Ebû Muhammed şu Yemenli Ebû Hureyre sizden daha âlim mi? ki sizlerden işitmediğiniz hadisleri ondan işitiyorsunuz yoksa Nebi (s.a.v)’in söylemediği şeyleri mi söylüyor?” Talha b. Ubeydullah şöyle dedi: “Gerçek şu ki o bizim işitmediğimiz şeyleri işitmiştir. Bunda kuşkumuz yok çünkü kendisi fakir ve yoksul olup hiçbir şeyi yoktu. Rasûlullah (s.a.v.)’in misafiri olarak Suffeliler arasında kalmaktaydı eli Nebi (s.a.v)’in eliyle beraberdi. Bizler ise ev, bark ve servet sahibi idik. Rasûlullah (s.a.v.)’in yanına gündüzün iki ucunda yani sabah akşam ancak gelebiliyorduk. Ebû Hureyre’nin bizim duymadığımız şeyleri duyması konusunda hiç şüphe etmiyorum. Değil Ebû Hureyre iman ve hayır sahibi hiçbir kimseyi Rasûlullah (s.a.v.)’in söylemediği bir şeyi yalan yere onun sözü imiş gibi söylemiş bulamazsın.” Tirmizî rivâyet etmiştir. Tirmizî: Bu hadis Muhammed b. İshâk rivâyeti olarak hasen garibtir. Yine Yunus b. Bükeyr ve başkaları bu hadisi Muhammed b. İshâk’tan rivâyet etmişlerdir
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif Isnaad</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Daif Isnaad</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3837</td></tr><tr><td>Arabic No</td><td>3837</td></tr><tr><td>Reference</td><td>Book 49 Hadith 237</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
مالک بن ابوعامر کہتے ہیں کہ ایک شخص نے طلحہ بن عبیداللہ کے پاس آ کر کہا: اے ابو محمد! کیا یہ یمنی شخص یعنی ابوہریرہ رسول اللہ صلی اللہ علیہ وسلم کی حدیثوں کا آپ لوگوں سے زیادہ جانکار ہے، ہم اس سے ایسی حدیثیں سنتے ہیں جو آپ سے نہیں سنتے یا وہ رسول اللہ صلی اللہ علیہ وسلم پر ایسی بات گھڑ کر کہتا ہے جو آپ نے نہیں فرمائی، تو انہوں نے کہا: نہیں ایسی بات نہیں، واقعی ابوہریرہ نے رسول اللہ صلی اللہ علیہ وسلم سے ایسی چیزیں سنی ہیں جو ہم نے آپ سے نہیں سنیں اور اس کی وجہ یہ تھی کہ وہ مسکین تھے، ان کے پاس کوئی چیز نہیں تھی وہ رسول اللہ صلی اللہ علیہ وسلم کے مہمان رہتے تھے، ان کا ہاتھ ( کھانے پینے میں ) رسول اللہ صلی اللہ علیہ وسلم کے ہاتھ کے ساتھ پڑتا تھا، اور ہم گھربار والے تھے اور مالدار لوگ تھے، ہم رسول اللہ صلی اللہ علیہ وسلم کے پاس صبح میں اور شام ہی میں آ پاتے تھے، اور اس میں کوئی شک نہیں کہ انہوں نے رسول اللہ صلی اللہ علیہ وسلم سے ایسی چیزیں سنی ہیں جو ہم نے نہیں سنیں، اور تم کوئی ایسا آدمی نہیں پاؤ گے جس میں کوئی خیر ہو اور وہ رسول اللہ صلی اللہ علیہ وسلم پر جھوٹ باندھے۔ امام ترمذی کہتے ہیں: ۱- یہ حدیث حسن غریب ہے، ہم اسے صرف محمد بن اسحاق کی روایت سے جانتے ہیں، ۲- اسے یونس بن بکیر نے اور ان کے علاوہ دوسرے راویوں نے بھی محمد بن اسحاق سے روایت کیا ہے۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif Isnaad</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Daif Isnaad</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3837</td></tr><tr><td>Arabic No</td><td>3837</td></tr><tr><td>Reference</td><td>Book 49 Hadith 237</td></tr></tbody></table></div>