## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا ابْنُ أَبِي عُمَرَ، حَدَّثَنَا سُفْيَانُ، عَنْ سُهَيْلِ بْنِ أَبِي صَالِحٍ، عَنْ أَبِيهِ، عَنْ أَبِي هُرَيْرَةَ، قَالَ قَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏"‏ مَنْ كَانَ مِنْكُمْ مُصَلِّيًا بَعْدَ الْجُمُعَةِ فَلْيُصَلِّ أَرْبَعًا ‏"‏ ‏.‏ قَالَ أَبُو عِيسَى هَذَا حَدِيثٌ حَسَنٌ صَحِيحٌ ‏.‏ حَدَّثَنَا الْحَسَنُ بْنُ عَلِيٍّ حَدَّثَنَا عَلِيُّ بْنُ الْمَدِينِيِّ عَنْ سُفْيَانَ بْنِ عُيَيْنَةَ قَالَ كُنَّا نَعُدُّ سُهَيْلَ بْنَ أَبِي صَالِحٍ ثَبْتًا فِي الْحَدِيثِ ‏.‏ وَالْعَمَلُ عَلَى هَذَا عِنْدَ بَعْضِ أَهْلِ الْعِلْمِ ‏.‏ وَرُوِيَ عَنْ عَبْدِ اللَّهِ بْنِ مَسْعُودٍ أَنَّهُ كَانَ يُصَلِّي قَبْلَ الْجُمُعَةِ أَرْبَعًا وَبَعْدَهَا أَرْبَعًا ‏.‏ وَقَدْ رُوِيَ عَنْ عَلِيِّ بْنِ أَبِي طَالِبٍ رضى الله عنه أَنَّهُ أَمَرَ أَنْ يُصَلَّى بَعْدَ الْجُمُعَةِ رَكْعَتَيْنِ ثُمَّ أَرْبَعًا ‏.‏ وَذَهَبَ سُفْيَانُ الثَّوْرِيُّ وَابْنُ الْمُبَارَكِ إِلَى قَوْلِ ابْنِ مَسْعُودٍ ‏.‏ وَقَالَ إِسْحَاقُ إِنْ صَلَّى فِي الْمَسْجِدِ يَوْمَ الْجُمُعَةِ صَلَّى أَرْبَعًا وَإِنْ صَلَّى فِي بَيْتِهِ صَلَّى رَكْعَتَيْنِ ‏.‏ وَاحْتَجَّ بِأَنَّ النَّبِيَّ صلى الله عليه وسلم كَانَ يُصَلِّي بَعْدَ الْجُمُعَةِ رَكْعَتَيْنِ فِي بَيْتِهِ وَحَدِيثِ النَّبِيِّ صلى الله عليه وسلم ‏"‏ مَنْ كَانَ مِنْكُمْ مُصَلِّيًا بَعْدَ الْجُمُعَةِ فَلْيُصَلِّ أَرْبَعًا ‏"‏ ‏.‏ قَالَ أَبُو عِيسَى وَابْنُ عُمَرَ هُوَ الَّذِي رَوَى عَنِ النَّبِيِّ صلى الله عليه وسلم أَنَّهُ كَانَ يُصَلِّي بَعْدَ الْجُمُعَةِ رَكْعَتَيْنِ فِي بَيْتِهِ وَابْنُ عُمَرَ بَعْدَ النَّبِيِّ صلى الله عليه وسلم صَلَّى فِي الْمَسْجِدِ بَعْدَ الْجُمُعَةِ رَكْعَتَيْنِ وَصَلَّى بَعْدَ الرَّكْعَتَيْنِ أَرْبَعًا ‏.‏ حَدَّثَنَا بِذَلِكَ ابْنُ أَبِي عُمَرَ، حَدَّثَنَا سُفْيَانُ بْنُ عُيَيْنَةَ، عَنِ ابْنِ جُرَيْجٍ، عَنْ عَطَاءٍ، قَالَ رَأَيْتُ ابْنَ عُمَرَ صَلَّى بَعْدَ الْجُمُعَةِ رَكْعَتَيْنِ ثُمَّ صَلَّى بَعْدَ ذَلِكَ أَرْبَعًا ‏.‏ حَدَّثَنَا سَعِيدُ بْنُ عَبْدِ الرَّحْمَنِ الْمَخْزُومِيُّ حَدَّثَنَا سُفْيَانُ بْنُ عُيَيْنَةَ عَنْ عَمْرِو بْنِ دِينَارٍ قَالَ مَا رَأَيْتُ أَحَدًا أَنَصَّ لِلْحَدِيثِ مِنَ الزُّهْرِيِّ وَمَا رَأَيْتُ أَحَدًا الدَّنَانِيرُ وَالدَّرَاهِمُ أَهْوَنُ عَلَيْهِ مِنْهُ إِنْ كَانَتِ الدَّنَانِيرُ وَالدَّرَاهِمُ عِنْدَهُ بِمَنْزِلَةِ الْبَعْرِ ‏.‏ قَالَ أَبُو عِيسَى سَمِعْت ابْنَ أَبِي عُمَرَ قَال سَمِعْتُ سُفْيَانَ بْنَ عُيَيْنَةَ يَقُولُ كَانَ عَمْرُو بْنُ دِينَارٍ أَسَنَّ مِنْ الزُّهْرِيِّ
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>523</td></tr><tr><td>Arabic No</td><td>523</td></tr><tr><td>Reference</td><td>Book 4 Hadith 36</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
৫২৩। আবু হুরাইরা (রাঃ) হতে বর্ণিত আছে, তিনি বলেন, রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেছেনঃ তোমাদের মধ্যে যে ব্যক্তি জুমু'আর নামাযের পর নামায আদায় করতে চায় সে যেন চার রাকাআত আদায় করে। -সহীহ। ইবনু মাজাহ– (১১৩২)। আবু ঈসা বলেনঃ এ হাদীসটি হাসান। সুফিয়ান ইবনু উয়াইনা বলেন, সুহাইল ইবনু আবু সালিহ হাদীসশাস্ত্রে একজন নির্ভরযোগ্য রাবী। একদল আলিম এ হাদীস অনুযায়ী আমল করেন। আবদুল্লাহ ইবনু মাসউদ (রাঃ) জুমুআর (ফরযের) পূর্বে চার রাকাআত এবং পরে চার রাকাআত (সুন্নাত) নামায আদায় করতেন। আলী (রাঃ) প্রসঙ্গে বর্ণিত আছে যে, তিনি জুমু'আর পর দুই রাকাআত তারপর চার রাকাআত আদায় করার হুকুম দিয়েছেন। সুফিয়ান সাওরী ও ইবনুল মুবারাক (রহঃ) ইবনু মাসউদের মত গ্রহণ করেছেন। ইসহাক বলেছেন, জুমুআর দিন যদি মসজিদে (সুন্নাত) নামায আদায় করা হয় তবে চার রাক'আত আদায় করবে আর যদি ঘরে আদায় করে তবে দুই রাকাআত আদায় করবে। তিনি দলীল হিসাবে এ হাদীস উল্লেখ করেছেন, وَاحْتَجَّ بِأَنَّ النَّبِيَّ صلى الله عليه وسلم كَانَ يُصَلِّي بَعْدَ الْجُمُعَةِ رَكْعَتَيْنِ فِي بَيْتِهِ “রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম জুমু'আর পর বাড়িতে গিয়ে দুই রাকাআত (সুন্নাত) নামায আদায় করেছেন।” তিনি আরে বলেছেনঃ وَحَدِيثِ النَّبِيِّ صلى الله عليه وسلم مَنْ كَانَ مِنْكُمْ مُصَلِّيًا بَعْدَ الْجُمُعَةِ فَلْيُصَلِّ أَرْبَعًا “তোমাদের মধ্যে যে ব্যক্তি জুমুআর (ফরযের) পরে নামায আদায় করতে চায় সে যেন চার রাক’আত আদায় করে।" আবু ঈসা বলেনঃ ইবনু উমার (রাঃ) যিনি নবী সাল্লাল্লাহু 'আলাইহি ওয়াসাল্লামের নিকট হতে বর্ণনা করেছেন, “জুমুআর পর তিনি বাড়িতে গিয়ে দুই রাকাআত আদায় করতেন।” তিনিও রাসূলুল্লাহ সাল্লাল্লাহু”আলাইহি ওয়াসাল্লামের পরে জুমু'আর নামাযের পর মসজিদেই দুই রাকাআত নামায আদায় করেছেন, তারপর চার রাকাআত আদায় করেছেন। আতা (রহঃ) হতে বর্ণিত আছে, তিনি বলেন, আমি ইবনু উমার (রাঃ)-কে জুমু'আর (ফরয নামাযের) পর দুই রাকাআত তারপর চার রাকাআত নামায আদায় করতে দেখেছি। -সহীহ। আবু দাউদ (১০৩৫, ১০৩৮) আমর ইবনু দীনার বলেন, যুহরীর চাইতে ভালভাবে হাদীস বর্ণনা করতে আমি আর কাউকে দেখতে পাইনি এবং তার মত আর কাউকে ধন-দৌলতকে তুচ্ছ ভাবিতে দেখিনি। তার দৃষ্টিতে ধন-দৌলত উটের মলতুল্য তুচ্ছ জিনিস। আমর ইবনু দীনার যুহরীর চাইতে বেশি বয়সী ছিলেন।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>523</td></tr><tr><td>Arabic No</td><td>523</td></tr><tr><td>Reference</td><td>Book 4 Hadith 36</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Abu Hurairah narrated that :Allah's Messenger said: "Whoever among you is to pray after the Friday prayer, then let him pray four
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>523</td></tr><tr><td>Arabic No</td><td>523</td></tr><tr><td>Reference</td><td>Book 4 Hadith 36</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Ibnu Abu Umar] telah menceritakan kepada kami [Sufyan] dari [Suhail bin Abu Shalih] dari [ayahnya] dari [Abu Hurairah] dia berkata, Rasulullah Shallahu 'alaihi wa sallam bersabda: "Barang siapa diantara kalian yang shalat setelah shalat Jum'at hendaknya ia shalat empat raka'at." Abu Isa berkata, ini adalah hadits hasan shahih. Telah menceritakan kepada kami Hasan bin Ali telah menceritakan kepada kami Ali bin Madini dari Sufyan bin 'Uyainah dia berkata, kami menganggap bahwa Suhail bin Shalih adalah tsabat dalam hadits, hadits ini juga diamalkan oleh sebagian para ulama. Diriwayatkan dari Abdullah bin Mas'ud bahwa dia shalat empat raka'at sebelum dan setela shalat jum'at sebanyak empat raka'at, dan telah diriwayatkan dari Ali bin Abu Thalib radliallahu 'anhu bahwa dia memerintahkan untuk shalat dua raka'at setelah shalat jum'at, kemudian empat raka'at, sedangkan Sufyan At Tsauri, Ibnu Mubarak berpendapat sebagaiaman perkataannya Ibnu Mas'ud. Ishaq berkata, jika pada hari Jum'at dia shalat dimasjid, maka ia shalat empat raka'at, jika ia shalat dirumahnya, maka ia shalat dua raka'at, dia berhujah bahwa Nabi Shallahu 'alaihi wa sallam shalat dua raka'at dirumahnya setelah shalat jum'at, sedangkan hadits Nabi Shallahu 'alaihi wa sallam: "Barang siapa diantara kalian yang shalat setelah shalat Jum'at hendaknya ia shalat empat raka'at." Abu Isa berkata, bahwa Ibnu Umar meriwayatkan dari Nabi Shallahu 'alaihi wa sallam bahwa beliau shalat dua raka'at dirumahnya setelah shalat jum'at, dan Ibnu Umar setelah Nabi Shallahu 'alaihi wa sallam selesai melaksanakan shalat dua raka'at dimasjid, beliau shalat empat raka'at. Telah menceritakan kepada kami Ibnu Abu Umar seperti itu, telah menceritakan kepada kami Sufyan bin 'Uyainah dari Ibnu Juraij dari Atha' dia berkata, saya melihat Ibnu Umar mengerjakan shalat dua raka'at setelah shalat Jum'at, setelah itu dia shalat empat raka'at. Telah menceritakan kepada kami Sa'id bin Abdurrahman Al Mahzumi, telah menceritakan kepada kami Sufyan bin 'Uyainah dari Amru bin Dinar dia berkata, saya tidak pernah melihat seseorang yang sanggup menashkan hadits selain Az Zuhri, dan saya tidak pernah melihat seseorang yang menganggap remeh (hina) dianr dan dirham selain dia, bahwa dinar dan dinar menurutnya tak ubahnya seperti keledai. Abu Isa berkata, saya pernah mendengar Ibnu Abu Umar berkata, saya mendengar Sufyan bin 'Uyainah berkata, adalah Amru bin Dinar lebih tua dari Az Zuhri
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>523</td></tr><tr><td>Arabic No</td><td>523</td></tr><tr><td>Reference</td><td>Book 4 Hadith 36</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ebû Hüreyre (radıyallahü anh)’den rivâyete göre, Rasûlüllah (sallallahü aleyhi ve sellem) şöyle buyurmuştur: “Cuma’dan sonra namaz kılmak isteyen dört rek’at kılsın.” (Ebû Dâvûd, Salat: 236; Nesâî, Cuma: 44) Bu hadis hasen sahihtir. b. Ali, Ali b. el Medinî ve Sûfyân b. Uyeyne’den naklederek şöyle demişlerdir: Süheyl b. ebî Salih’i hadis konusunda sabit ve sağlam bir kimse olarak kabul ederdik. Bazı ilim adamları da bu hadisle amel etmişlerdir. b. Mes’ûd (radıyallahü anh)’den, Cuma’dan önce dört, Cuma’dan sonra dört rek’at kıldığı rivâyet edilmiştir. b. ebî Tâlib’in Cuma’dan sonra iki rek’at ve dört rek’at kılınmasını emrettiği de rivâyet edilmiştir. es Sevrî ve İbn’ül Mübarek, İbn Mes’ûd’un görüşündedirler. Cuma’dan önce dört rek’at sonra dört rek’at sünnet kılarlar. diyor ki: Bir kimse Cuma’dan sonraki sünneti evinde kılarsa iki, mescidde kılarsa dört kılmalıdır, demekte ve bunu şu iki hadise dayandırmaktadır; “Rasûlüllah (sallallahü aleyhi ve sellem) Cuma’dan sonra evinde iki rek’at sünnet kılardı.” “Kim Cuma’dan sonra namaz kılacaksa dört rek’at kılsın.”
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>523</td></tr><tr><td>Arabic No</td><td>523</td></tr><tr><td>Reference</td><td>Book 4 Hadith 36</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ابوہریرہ رضی الله عنہ کہتے ہیں کہ رسول اللہ صلی اللہ علیہ وسلم نے فرمایا: ”جو تم میں سے جمعہ کے بعد نماز پڑھے تو چاہیئے کہ چار رکعت پڑھے“۔ امام ترمذی کہتے ہیں: ۱- یہ حدیث حسن صحیح ہے، ۲- بعض اہل علم کا اسی پر عمل ہے، ۳- نیز عبداللہ بن مسعود رضی الله عنہ سے بھی مروی ہے کہ وہ جمعہ سے پہلے چار رکعتیں اور اس کے بعد بھی چار رکعتیں پڑھتے تھے، ۴- اور علی بن ابی طالب رضی الله عنہ سے بھی مروی ہے کہ انہوں نے حکم دیا کہ جمعہ کے بعد پہلے دو پھر چار رکعتیں پڑھی جائیں، ۵- سفیان ثوری اور ابن مبارک بھی ابن مسعود کے قول کی طرف گئے ہیں، ۶- اسحاق بن راہویہ کہتے ہیں: جمعہ کے دن اگر مسجد میں پڑھے تو چار رکعتیں اور اگر اپنے گھر میں پڑھے تو دو رکعتیں پڑھے، ان کی دلیل یہ ہے کہ نبی اکرم صلی اللہ علیہ وسلم جمعہ کے بعد دو رکعتیں اپنے گھر میں پڑھتے تھے۔ اور نبی اکرم صلی اللہ علیہ وسلم کی ( یہ بھی ) حدیث ہے کہ تم میں سے جو کوئی جمعہ کے بعد نماز پڑھے تو چار رکعتیں پڑھے، ۷- ابن عمر رضی الله عنہما ہی ہیں جنہوں نے نبی اکرم صلی اللہ علیہ وسلم سے روایت کی ہے کہ آپ جمعہ کے بعد دو رکعتیں اپنے گھر میں پڑھتے تھے۔ اور ابن عمر رضی الله عنہما نے خود نبی اکرم صلی اللہ علیہ وسلم کے بعد مسجد میں جمعہ کے بعد دو رکعتیں پڑھیں اور دو رکعتوں کے بعد چار رکعتیں پڑھیں۔ عطا سے روایت کی ہے کہ میں نے ابن عمر رضی الله عنہما کو دیکھا کہ انہوں نے جمعہ کے بعد دو رکعتیں پڑھیں۔ اس کے بعد چار رکعتیں پڑھیں۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>523</td></tr><tr><td>Arabic No</td><td>523</td></tr><tr><td>Reference</td><td>Book 4 Hadith 36</td></tr></tbody></table></div>