## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا هَنَّادٌ، حَدَّثَنَا أَبُو الأَحْوَصِ، عَنْ لَيْثٍ، عَنْ شَهْرِ بْنِ حَوْشَبٍ، عَنْ عَبْدِ الرَّحْمَنِ بْنِ غَنْمٍ، عَنْ أَبِي ذَرٍّ، قَالَ قَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏ "‏ يَقُولُ اللَّهُ تَعَالَى يَا عِبَادِي كُلُّكُمْ ضَالٌّ إِلاَّ مَنْ هَدَيْتُهُ فَسَلُونِي الْهُدَى أَهْدِكُمْ وَكُلُّكُمْ فَقِيرٌ إِلاَّ مَنْ أَغْنَيْتُ فَسَلُونِي أَرْزُقْكُمْ وَكُلُّكُمْ مُذْنِبٌ إِلاَّ مَنْ عَافَيْتُ فَمَنْ عَلِمَ مِنْكُمْ أَنِّي ذُو قُدْرَةٍ عَلَى الْمَغْفِرَةِ فَاسْتَغْفَرَنِي غَفَرْتُ لَهُ وَلاَ أُبَالِي وَلَوْ أَنَّ أَوَّلَكُمْ وَآخِرَكُمْ وَحَيَّكُمْ وَمَيِّتَكُمْ وَرَطْبَكُمْ وَيَابِسَكُمُ اجْتَمَعُوا عَلَى أَتْقَى قَلْبِ عَبْدٍ مِنْ عِبَادِي مَا زَادَ ذَلِكَ فِي مُلْكِي جَنَاحَ بَعُوضَةٍ وَلَوْ أَنَّ أَوَّلَكُمْ وَآخِرَكُمْ وَحَيَّكُمْ وَمَيِّتَكُمْ وَرَطْبَكُمْ وَيَابِسَكُمُ اجْتَمَعُوا عَلَى أَشْقَى قَلْبِ عَبْدٍ مِنْ عِبَادِي مَا نَقَصَ ذَلِكَ مِنْ مُلْكِي جَنَاحَ بَعُوضَةٍ وَلَوْ أَنَّ أَوَّلَكُمْ وَآخِرَكُمْ وَحَيَّكُمْ وَمَيِّتَكُمْ وَرَطْبَكُمْ وَيَابِسَكُمُ اجْتَمَعُوا فِي صَعِيدٍ وَاحِدٍ فَسَأَلَ كُلُّ إِنْسَانٍ مِنْكُمْ مَا بَلَغَتْ أُمْنِيَّتُهُ فَأَعْطَيْتُ كُلَّ سَائِلٍ مِنْكُمْ مَا سَأَلَ مَا نَقَصَ ذَلِكَ مِنْ مُلْكِي إِلاَّ كَمَا لَوْ أَنَّ أَحَدَكُمْ مَرَّ بِالْبَحْرِ فَغَمَسَ فِيهِ إِبْرَةً ثُمَّ رَفَعَهَا إِلَيْهِ ذَلِكَ بِأَنِّي جَوَادٌ مَاجِدٌ أَفْعَلُ مَا أُرِيدُ عَطَائِي كَلاَمٌ وَعَذَابِي كَلاَمٌ إِنَّمَا أَمْرِي لِشَيْءٍ إِذَا أَرَدْتُهُ أَنْ أَقُولَ لَهُ كُنْ فَيَكُونُ ‏"‏ ‏.‏ قَالَ هَذَا حَدِيثٌ حَسَنٌ ‏.‏ وَرَوَى بَعْضُهُمْ هَذَا الْحَدِيثَ عَنْ شَهْرِ بْنِ حَوْشَبٍ عَنْ مَعْدِيكَرِبَ عَنْ أَبِي ذَرٍّ عَنِ النَّبِيِّ صلى الله عليه وسلم نَحْوَهُ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Bashar Awad Maarouf</td></tr><tr><td>Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2495</td></tr><tr><td>Arabic No</td><td>2495</td></tr><tr><td>Reference</td><td>Book 37 Hadith 81</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
২৪৯৫। আবূ যার (রাঃ) হতে বর্ণিত আছে, তিনি বলেন, রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেছেন, আল্লাহ তা'আলা বলেনঃ হে আমার বান্দাগণ! তোমরা তো সবাই পথভ্রষ্ট, তবে তারা নয়, যাদের আমি হিদায়াত করি। সুতরাং তোমরা আমার নিকটে হিদায়াতের আবেদন কর, আমি হিদায়াত করব। আর যাদের আমি ধনী করেছি তাদের ব্যতীত তোমাদের সবই তো দরিদ্র। তোমরা আমার নিকটে প্রার্থনা কর আমি রিযিক দেব। আর আমি যাদের মাফ করেছি তাদের ব্যতীত তোমাদের সকলেই তো গুনাহগার। তোমাদের মধ্যে যে ব্যক্তি এ কথা জানে যে, আমি মাফ করার ক্ষমতা রাখি, তারপর সে ক্ষমা ভিক্ষা করে, আমি তার গুনাহ মাফ করে দেই। আমি এ ব্যাপারে কোন ভ্রূক্ষেপ করি না। তোমাদের পূর্বের ও পরের, জীবিত ও মৃত, সিক্ত ও শুষ্ক (স্বচ্ছল ও অস্বচ্ছল) সকলেই যদি আমার বান্দাদের মধ্যে সর্বাধিক তাকওয়ার অধিকারী ব্যক্তির হৃদয়ের মত হয়ে যায়, তাহলে একটি মশার পাখার সম-পরিমাণও আমার রাজত্বের শ্ৰীবৃদ্ধি ঘটবে না। আর তোমাদের আগের ও পরের, জীবিত ও মৃত, ভিজা ও শুষ্ক (স্বচ্ছল ও অস্বচ্ছল) সকলে যদি আমার বান্দাদের মধ্যে সবচাইতে বড় পাপী বান্দার মত হয়ে যায়, তাহলে একটি মশার পাখার সম-পরিমাণও আমার রাজত্বের হানি ঘটবে না। আর যদি তোমাদের আগের ও পরের, জীবিত ও মৃত, ভিজা ও শুষ্ক সকলে একটি জায়গায় সমবেত হয় এবং প্রত্যেকেই তার পূর্ণ চাহিদামত আমার নিকট প্রার্থনা করে, আর আমি তাদের চাওয়া অনুযায়ী সবকিছু যদি দেই, তাহলেও আমার রাজত্বের কিছুই কমবে না, তবে এতটুকু পরিমাণ যে, তোমাদের কেউ সমুদ্রের মধ্য দিয়ে যাবার সময় তাতে একটি সুই ডুবিয়ে তা তুলে নিলে তাতে সমুদ্রের পানি যতটুকু কমবে। কারণ আমি হলাম দাতা, দয়ালু ও মহান। আমি যা চাই তাই করি। আমার দান হল আমার কথা আর আমার আযাব হল আমার নির্দেশ। আমার ব্যাপার এই যে, আমি যখন কিছু ইচ্ছা করি তখন বলি, “হয়ে যাও” অমনি তা হয়ে যায়। এই বর্ণনাটি যঈফ, তবে হাদীসের অধিকাংশই সহীহ, মুসলিম, ইবনু মাজাহ (৪২৫৭) আবূ ঈসা বলেন, এ হাদীসটি হাসান। কিছু রাবী এ হাদীস শাহর ইবনু হাওশাব হতে মাদীকারিব-এর সূত্রে আবূ যার (রাঃ)-এর বরাতে রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম হতে একই রকম বর্ণনা করেছেন।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Bashar Awad Maarouf</td></tr><tr><td>Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2495</td></tr><tr><td>Arabic No</td><td>2495</td></tr><tr><td>Reference</td><td>Book 37 Hadith 81</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Abu Dharr narrated that the Messenger of Allah (s.a.w) said:"Allah,Most High said: 'O My Slaves! All of you are astray except whom I guide, so ask Me for guidance and I shall guide you. All of you are poor except whom I enrich, so ask Me and I shall provide you. All of you are sinners except whom I have pardoned, so whoever among you knows that I am the One able to forgive, and seeks My forgiveness, I shall forgive him, without concern for Me (and it will not affect Me). If the first of you and the last of you, the living among you and the dead among you, the fresh among you and the dry among you were to gather together to help the heart with the most Taqwa among My slaves, that would not add a mosquito's wing to My sovereignty. If the first of you and the last of you, the living among you and the dead among you, the fresh among you and the dry among you were to gather together to help the worst heart of My slaves, that would not diminish a mosquito's wing to My sovereignty. I shall forgive him, without concern for Me (and it will not affect Me). If the first of you and the last of you, the living among you and the dead among you, the fresh among you and the dry among you were to gather together upon one plateau, and each person among them were to ask for his utmost desire, and I were to give each what he asked for, that would not diminish from My sovereignty, except as if one of you were to pass by an ocean and dip a needle into it and then remove it. That is because I am the Most Liberal without need, the Most Generous, doing as I will. I give by My speech and I punish by My speech, whenever I will something I only say: "Be" and it shall be.'" Another chain reports a similar narration
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Bashar Awad Maarouf</td></tr><tr><td>Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2495</td></tr><tr><td>Arabic No</td><td>2495</td></tr><tr><td>Reference</td><td>Book 37 Hadith 81</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>

</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Bashar Awad Maarouf</td></tr><tr><td>Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2495</td></tr><tr><td>Arabic No</td><td>2495</td></tr><tr><td>Reference</td><td>Book 37 Hadith 81</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ebû Zer’ (r.a.)’den rivayete göre, Rasûlullah (s.a.v.) şöyle buyurdu; “Allah şöyle buyurur: “Ey kullarım! Hepiniz dalalettesiniz ancak benim hidayet nasib ettiğim kişiler hariç benden hidayet isteyiniz ki, size hidayet vereyim. Hepiniz fakirsiniz, ancak benim zengin ettiğim kimseler hariç; benden isteyin, sizi rızıklandırayım. Hepiniz günahkarsınız, benim affettiklerim dışında; içinizden her kim, benim bağışlama gücüne sahip olduğumu bilir ve benden bağışlanmasını isterse günahlarının çokluğuna ve büyüklüğüne aldırmaksızın onu affederim. Sizin öncekileriniz, sonrakileriniz, ölüleriniz ve dirileriniz yaşlarınız ve kurularınız kullarımdan en takvalı bir kimse gibi olsalar benim saltanatımda sivrisineğin kanadı kadar bir şey artmaz. Eğer sizin öncekileriniz ve sonrakileriniz, ölüleriniz ve dirileriniz yaşlarınız ve kurularınız kullarımdan en kötü ve bedbaht bir kimse gibi olsalar benim saltanatımdan sivrisineğin kanadı kadar bir şey eksilmez. Eğer sizin öncekileriniz ve sonrakileriniz, ölüleriniz ve dirileriniz yaşlarınız ve kurularınız büyük bir meydanda toplansa ve herkes hayalinde canlandırabileceği her şeyi istese hepsini veririm ve bu verilenler benim mülkümden hiç bir şey eksiltmez; ancak bir kişinin denize iğne daldırıp çıkardığında ne kadar su eksilirse o kadar eksilir. Çünkü ben cömerdim, varlık sahibiyim, güçlüyüm istediğimi yapabilirim, bağışlamam bir söze bağlıdır. Azabım da yine bir söze bağlıdır. Bir şeyin olmasını istediğimde sadece ol derim ve o şey hemen oluverir.” Diğer tahric: Müslim, Birr ve Sıla; İbn Mâce, Zühd Bu hadis hasendir. Bazıları da bu hadisi Şehr b. Havşeb’den, Ma’dikerb’den ve Ebû Zerr’den benzeri şekilde rivâyet etmişlerdir.­
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Bashar Awad Maarouf</td></tr><tr><td>Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2495</td></tr><tr><td>Arabic No</td><td>2495</td></tr><tr><td>Reference</td><td>Book 37 Hadith 81</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ابوذر غفاری رضی الله عنہ کہتے ہیں کہ رسول اللہ صلی اللہ علیہ وسلم نے فرمایا: ”اللہ تعالیٰ فرماتا ہے: اے میرے بندو! تم سب گمراہ ہو، سوائے اس کے جسے میں ہدایت دوں، اس لیے تم سب مجھ سے ہدایت مانگو میں تمہیں ہدایت دوں گا، اور تم سب کے سب محتاج ہو سوائے اس کے جسے میں غنی ( مالدار ) کر دوں، اس لیے تم مجھ ہی سے مانگو میں تمہیں رزق دوں گا، اور تم سب گنہگار ہو، سوائے اس کے جسے میں عافیت دوں سو جسے یہ معلوم ہے کہ میں بخشنے پر قادر ہوں پھر وہ مجھ سے مغفرت چاہتا ہے تو میں اسے معاف کر دیتا ہوں، اور مجھے کوئی پرواہ نہیں اگر تمہارے اگلے اور پچھلے، تمہارے زندے اور مردے اور تمہارے خشک و تر سب میرے بندوں میں سے سب سے زیادہ متقی و پرہیزگار بندے کی طرح ہو جائیں تو بھی میری سلطنت میں ایک مچھر کے پر برابر اضافہ نہ ہو گا، اور اگر تمہارے اگلے اور پچھلے، تمہارے زندے اور مردے اور تمہارے خشک و تر سب میرے بندوں میں سے سب سے زیادہ شقی و بدبخت کی طرح ہو جائیں تو بھی میری سلطنت میں ایک مچھر کے پر برابر کمی نہ ہو گی، اور اگر تمہارے اگلے اور پچھلے، تمہارے زندے اور مردے اور تمہارے خشک و تر سب ایک ہی زمین پر جمع ہو جائیں اور تم میں سے ہر انسان مجھ سے اتنا مانگے جہاں تک اس کی آرزوئیں پہنچیں اور میں تم میں سے ہر سائل کو دے دوں تو بھی میری سلطنت میں کچھ بھی فرق واقع نہ ہو گا مگر اتنا ہی کہ تم میں سے کوئی سمندر کے کنارے سے گزرے اور اس میں ایک سوئی ڈبو کر نکال لے، اور ایسا اس وجہ سے ہے کہ میں سخی، بزرگ ہوں، جو چاہتا ہوں کرتا ہوں، میرا دینا صرف کہہ دینا، اور میرا عذاب صرف کہہ دینا ہے، کسی چیز کے لیے جب میں چاہتا ہوں تو میرا حکم یہی ہے کہ میں کہتا ہوں ”ہو جا“ بس وہ ہو جاتی ہے“۔ امام ترمذی کہتے ہیں: ۱- یہ حدیث حسن ہے، ۲- بعض لوگوں نے اسی طرح اس حدیث کو بطریق: «عن شهر بن حوشب عن معدي كرب عن أبي ذر عن النبي صلى الله عليه وسلم» روایت کیا ہے۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Bashar Awad Maarouf</td></tr><tr><td>Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2495</td></tr><tr><td>Arabic No</td><td>2495</td></tr><tr><td>Reference</td><td>Book 37 Hadith 81</td></tr></tbody></table></div>