## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا حُمَيْدُ بْنُ مَسْعَدَةَ، أَخْبَرَنَا عُبَيْدُ اللَّهِ بْنُ شُمَيْطِ بْنِ عَجْلاَنَ، حَدَّثَنَا الأَخْضَرُ بْنُ عَجْلاَنَ، عَنْ عَبْدِ اللَّهِ الْحَنَفِيِّ، عَنْ أَنَسِ بْنِ مَالِكٍ، أَنَّ رَسُولَ اللَّهِ صلى الله عليه وسلم بَاعَ حِلْسًا وَقَدَحًا وَقَالَ ‏"‏ مَنْ يَشْتَرِي هَذَا الْحِلْسَ وَالْقَدَحَ ‏"‏ ‏.‏ فَقَالَ رَجُلٌ أَخَذْتُهُمَا بِدِرْهَمٍ ‏.‏ فَقَالَ النَّبِيُّ صلى الله عليه وسلم ‏"‏ مَنْ يَزِيدُ عَلَى دِرْهَمٍ مَنْ يَزِيدُ عَلَى دِرْهَمٍ ‏"‏ فَأَعْطَاهُ رَجُلٌ دِرْهَمَيْنِ فَبَاعَهُمَا مِنْهُ ‏.‏ قَالَ أَبُو عِيسَى هَذَا حَدِيثٌ حَسَنٌ لاَ نَعْرِفُهُ إِلاَّ مِنْ حَدِيثِ الأَخْضَرِ بْنِ عَجْلاَنَ ‏.‏ وَعَبْدُ اللَّهِ الْحَنَفِيُّ الَّذِي رَوَى عَنْ أَنَسٍ هُوَ أَبُو بَكْرٍ الْحَنَفِيُّ ‏.‏ وَالْعَمَلُ عَلَى هَذَا عِنْدَ بَعْضِ أَهْلِ الْعِلْمِ لَمْ يَرَوْا بَأْسًا بِبَيْعِ مَنْ يَزِيدُ فِي الْغَنَائِمِ وَالْمَوَارِيثِ ‏.‏ وَقَدْ رَوَى الْمُعْتَمِرُ بْنُ سُلَيْمَانَ وَغَيْرُ وَاحِدٍ مِنْ أَهْلِ الْحَدِيثِ عَنِ الأَخْضَرِ بْنِ عَجْلاَنَ هَذَا الْحَدِيثَ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1218</td></tr><tr><td>Arabic No</td><td>1218</td></tr><tr><td>Reference</td><td>Book 14 Hadith 17</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
১২১৮। আনাস ইবনু মালিক (রাঃ) হতে বর্ণিত আছে, রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম (উটের পিঠে বিছানোর) একটি ছালা (বা মোটা কাপড়) এবং একটি কাঠের পাত্র বেচার প্রস্তাব করেন এবং তিনি বলেনঃ কে এই ছালা ও পাত্রটি কিনবে? এক লোক বলল, আমি এ দু'টি এক দিরহামে কিনতে চাই। নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেনঃ কে এক দিরহামের বেশী দিবে, কে এক দিরহামের বেশী দিবে? এক ব্যক্তি তাকে দুই দিরহাম দিয়ে তার নিকট হতে জিনিস দুটি কিনলো। যঈফ, ইবনু মাজাহ (২১৯৮) আবূ ঈসা বলেন, এ হাদীসটি হাসান। আমরা শুধুমাত্র আখ্যারের সূত্রেই এ হাদীসটি অবগত হয়েছি। আবদুল্লাহ হানাফী যিনি আনাস (রাঃ) হতে হাদীস বর্ণনা করেছেন তার উপনাম আবূ বকর। একদল বিশেষজ্ঞ আলিম এ হাদীস অনুযায়ী আমল করার মত দিয়েছেন। তাদের মতে গানীমাত ও ওয়ারিসী সম্পত্তি নিলাম ডাকের মাধ্যমে বিক্রয় করাতে কোন সমস্যা নেই। মুতামির-সহ একাধিক রাবী উক্ত হাদীস আখ্যারের সূত্রে বর্ণনা করেছেন।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1218</td></tr><tr><td>Arabic No</td><td>1218</td></tr><tr><td>Reference</td><td>Book 14 Hadith 17</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated Anas bin Malik: That the Messenger of Allah (ﷺ) sold a saddle blanket and a drinking bowl. He (ﷺ) said: "Who will buy saddle blanket and drinking bowl ?". So a man said: "I will take them for a Dirham." So the Prophet (ﷺ) said: "Who will give more than a Dirham ? Who will give more that a Dirham ?" A man agreed to give him two Dirham, so he sold them to him. [Abu 'Eisa said:] This Hadith is Hasan. We do not know of it except from the narration of Al-Akhdar bin 'Ajlan, and 'Abdullah Al-Hanafi who is reporting from Anas, is Abu Bakr Al-Hanafi. This is acted upon according to some of the people of knowledge, they did not see any harm in auctioning the spolis of war and inheritance. Al-Mu'tamir bin Sulaiman and others among the people of Hadith reported from Al-Akhdar bin 'Ajlan
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1218</td></tr><tr><td>Arabic No</td><td>1218</td></tr><tr><td>Reference</td><td>Book 14 Hadith 17</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Humaid bin Ma'adah] telah mengabarkan kepada kami [Ubaidullah bin Syumaith bin 'Ajlan] telah menceritakan kepada kami [Al Akhdhar bin 'Ajlan] dari [Abdullah bin Al Hanafi] dari [Anas bin Abdul Malik bin Amru] bahwa Rasulullah shallallahu 'alaihi wasallam pernah menjual alas pelana dan gelas, lalu beliau menawarkan: "Siapa yang akan membeli alas pelana dan gelas ini?" Seseorang berkata; Saya akan membelinya seharga satu dirham, Nabi shallallahu 'alaihi wasallam menawarkan lagi: "Siapa yang mau membelinya lebih dari satu dirham?" Lalu seorang laki-laki memberinya dua dirham, beliau pun menjual kepadanya. Abu Isa berkata; Hadits ini hasan, kami tidak mengetahuinya kecuali dari hadits Al Akhdhar bin 'Ajlan dan Abdullah Al Hanafi yang meriwayatkan dari Anas, ia adalah Abu Bakr Al Hanafi. Hadits ini menjadi pedoman amal menurut sebagian ulama, mereka berpendapat bolehnya menjual harta rampasan perang dan warisan kepada orang yang membeli dengan harga yang lebih tinggi. Dan hadits ini telah diriwayatkan oleh [Al Mu'tamir bin Sulaiman] dan banyak dari kalangan ulama besar kaum muslimin dari [Al Akhdhar bin 'Ajlan]
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1218</td></tr><tr><td>Arabic No</td><td>1218</td></tr><tr><td>Reference</td><td>Book 14 Hadith 17</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Enes b. Mâlik (r.a.)’den rivâyete göre, Rasûlullah (s.a.v.), yoksul bir kimsenin bir parça çulunu ve su kabını satıp o kimseye yiyecek parası ve sermaye yapmak istedi ve: “Bu çulu ve bardağı kim satın alır” dedi. Bir adam: “Onun ikisini bir dirheme ben aldım” dedi. Bunun üzerine Rasûlullah (s.a.v.): ''Bir dirhemden fazla veren var mı? Bir dirhemden fazla veren var mı?” buyurdu. Bir adam: “İki dirhem verince onları ona sattı.” Diğer tahric: Nesâî, Buyu; Buhârî, Buyu’ Tirmîzî: Bu hadis hasendir. Bu hadisi sadece Ahdar b. Aclan’ın rivâyetiyle bilmekteyiz. Enes’den hadis rivâyet eden Abdullah el Hanefî, Ebû Bekir el Hanefî’dir. Bazı ilim adamlarının uygulaması bu hadise göre olup miras ve ganimet mallarının açık artırma yoluyla satılmasında bir sakınca görmezler. Mu’temir b. Süleyman ve hadisçilerin büyüklerinden pek çok kimse bu hadisi bu hadisi Ahdar b. Aclan’dan rivâyet etmişlerdir
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1218</td></tr><tr><td>Arabic No</td><td>1218</td></tr><tr><td>Reference</td><td>Book 14 Hadith 17</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
انس بن مالک رضی الله عنہ کہتے ہیں کہ رسول اللہ صلی اللہ علیہ وسلم نے ایک ٹاٹ جو کجاوہ کے نیچے بچھایا جاتا ہے اور ایک پیالہ بیچا، آپ نے فرمایا: ”یہ ٹاٹ اور پیالہ کون خریدے گا؟ ایک آدمی نے عرض کیا: میں انہیں ایک درہم میں لے سکتا ہوں“، نبی اکرم صلی اللہ علیہ وسلم نے فرمایا: ”ایک درہم سے زیادہ کون دے گا؟“ تو ایک آدمی نے آپ کو دو درہم دیا، تو آپ نے اسی کے ہاتھ سے یہ دونوں چیزیں بیچ دیں۔ امام ترمذی کہتے ہیں: ۱- یہ حدیث حسن ہے۔ ہم اسے صرف اخضر بن عجلان کی روایت سے جانتے ہیں، ۲- اور عبداللہ حنفی ہی جنہوں نے انس سے روایت کی ہے ابوبکر حنفی ہیں ۱؎، ۳- بعض اہل علم کا اسی پر عمل ہے۔ یہ لوگ غنیمت اور میراث کے سامان کو زیادہ قیمت دینے والے سے بیچنے میں کوئی حرج نہیں سمجھتے ہیں، ۴- یہ حدیث معتمر بن سلیمان اور دوسرے کئی بڑے لوگوں نے بھی اخضر بن عجلان سے روایت کی ہے۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1218</td></tr><tr><td>Arabic No</td><td>1218</td></tr><tr><td>Reference</td><td>Book 14 Hadith 17</td></tr></tbody></table></div>