## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا أَبُو كُرَيْبٍ، حَدَّثَنَا عَبْدَةُ بْنُ سُلَيْمَانَ، حَدَّثَنَا مُحَمَّدُ بْنُ عَمْرٍو، حَدَّثَنَا أَبُو سَلَمَةَ، عَنْ أَبِي هُرَيْرَةَ، قَالَ قَالَ يَهُودِيٌّ بِسُوقِ الْمَدِينَةِ لاَ وَالَّذِي اصْطَفَى مُوسَى عَلَى الْبَشَرِ ‏.‏ قَالَ فَرَفَعَ رَجُلٌ مِنَ الأَنْصَارِ يَدَهُ فَصَكَّ بِهَا وَجْهَهُ قَالَ تَقُولُ هَذَا وَفِينَا نَبِيُّ اللَّهِ صلى الله عليه وسلم ‏.‏ فَقَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏(‏ ونُفِخَ فِي الصُّورِ فَصَعِقَ مَنْ فِي السَّمَوَاتِ وَمَنْ فِي الأَرْضِ إِلاَّ مَنْ شَاءَ اللَّهُ ثُمَّ نُفِخَ فِيهِ أُخْرَى فَإِذَا هُمْ قِيَامٌ يَنْظُرُونَ ‏)‏ فَأَكُونُ أَوَّلَ مَنْ رَفَعَ رَأْسَهُ فَإِذَا مُوسَى آخِذٌ بِقَائِمَةٍ مِنْ قَوَائِمِ الْعَرْشِ فَلاَ أَدْرِي أَرَفَعَ رَأْسَهُ قَبْلِي أَوْ كَانَ مِمَّنِ اسْتَثْنَى اللَّهُ وَمَنْ قَالَ أَنَا خَيْرٌ مِنْ يُونُسَ بْنِ مَتَّى فَقَدْ كَذَبَ ‏"‏ ‏.‏ قَالَ أَبُو عِيسَى هَذَا حَدِيثٌ حَسَنٌ صَحِيحٌ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Hasan Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Hasan Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3245</td></tr><tr><td>Arabic No</td><td>3245</td></tr><tr><td>Reference</td><td>Book 47 Hadith 297</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
৩২৪৫। আবূ হুরাইরাহ (রাযিঃ) হতে বর্ণিত আছে। তিনি বলেন, এক ইয়াহুদী মদীনার বাজারে উচ্চস্বরে বললঃ না! সেই সৃষ্টিকর্তার শপথ, যিনি মূসাকে মানবজাতির উপর মর্যাদা দিয়েছেন। বর্ণনাকারী বলেন, এক আনসার লোক এ কথা শুনার সাথে সাথে হাত তুলে ইয়াহুদীর মুখে থাপ্পর মেরে দেয়। সে বলল, তুমি এই কথা বলছ, অথচ আল্লাহর নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম আমাদের মধ্যে বর্তমান আছেন? (উভয়ে মহানবীর নিকট উপস্থিত হলে) রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বললেনঃ “আর শিঙ্গায় ফুঁ দেয়া হবে। তখন আসমান-জামীনের সকলে মূৰ্ছিত হয়ে পড়বে, আল্লাহ তা’আলা যাকে জ্যান্ত রাখতে চান সে ছাড়া। তারপর আবার শিঙ্গায় ফুঁ দেয়া হবে। সহসা তারা দণ্ডায়মান হয়ে তাকাতে থাকবে”— (সূরা যুমার ৬৮)। আমিই সবার আগে মাথা তুলে দেখতে পাব যে, মূসা (আঃ) আরশের পায়াসমূহের একটি ধরে আছেন। আমি জানি না, তিনি কি আমার আগে মাথা তুলেছেন, না তিনি ঐ সব লোকের দলে যাদেরকে আল্লাহ তা'আলা (জ্ঞানশূন্য হওয়া হতে) মুক্ত রেখেছেন। যে লোক বলে যে, আমি ইউনুস ইবনু মাত্তা (আঃ)-এর চেয়ে শ্ৰেষ্ঠ সে মিথ্যা বলে। হাসান সহীহঃ তাখরীজুত তাহাবিয়াহ (১৬২), বুখারী অনুরূপ বর্ণনা করেছেন। আবূ ঈসা বলেন, এ হাদীসটি হাসান সহীহ।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Hasan Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Hasan Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3245</td></tr><tr><td>Arabic No</td><td>3245</td></tr><tr><td>Reference</td><td>Book 47 Hadith 297</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated Abu Hurairah:"In the market of Al-Madinah, a Jew said 'No! By the One who chose Musa above all humans.'" He said: "A man from the Ansar raised his hand and struck him in his face. He said 'You say this while Allah's Prophet (ﷺ) is among us?' So the Messenger of Allah (ﷺ) said 'And the Trumpet will be blown, and all who are in the heavens and all who are on the earth will swoon away, except him whom Allah wills. Then it will blown another time and behold, they will be standing, looking on (39:68). So I shall be the first to raise his head and there will be Musa holding on to one of the supports of the Throne. So I will not know if he raised his head before me, or if he was one of those whom Allah made the exception for. And whoever says: 'I am better than Yunus bin Matta, then he has indeed lied
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Hasan Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Hasan Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3245</td></tr><tr><td>Arabic No</td><td>3245</td></tr><tr><td>Reference</td><td>Book 47 Hadith 297</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Abu Kuraib] telah menceritakan kepada kami [Abdah bin Sulaiman] telah menceritakan kepada kami [Muhammad bin Amru] telah menceritakan kepada kami [Abu Salamah] dari [Abu Hurairah] berkata: Seorang Yahudi di pasar Madinah berkata: Tidak, demi Yang memilih Musa atas seluruh manusia. Abu Hurairah berkata: Seorang Anshar mengangkat tangannya lalu menampar, ia berkata: Kau mengatakan itu sementara ditengah-tengah kita ada nabi Allah Shallallahu 'alaihi wa Salam. Rasulullah Shallallahu 'alaihi wa Salam bersabda: "Dan ditiuplah sangkakala, Maka matilah siapa yang di langit dan di bumi kecuali siapa yang dikehendaki Allah. Kemudian ditiup sangkakala itu sekali lagi Maka tiba-tiba mereka berdiri menunggu (putusannya masing-masing)." (Az Zumar: 68), aku adalah orang pertama yang mengangkat kepala, ternyata Musa memegangi salah satu tiang Arsy, aku tidak tahu apakah ia mengangat kepalanya sebelumku ataukah termasuk yang dikecualikan Allah (tidak mati) dan barangsiapa mengatakan aku lebih baik dari Yunus bin Mata berarti ia dusta." Abu Isa berkata: Hadits ini hasan shahih
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Hasan Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Hasan Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3245</td></tr><tr><td>Arabic No</td><td>3245</td></tr><tr><td>Reference</td><td>Book 47 Hadith 297</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ebû Hureyre (r.a.)’den rivâyete göre, şöyle demiştir: Yahudinin biri Medîne çarşısında alışveriş ederken: “Musa’yı bütün insanlardan üstün kılan, Allah hakkı için hayır…” demişti. Bunun üzerine Ensâr’dan bir adam elini kaldırıp Yahudinin suratına bir şamar indirerek şöyle dedi: “İçimizde Allah’ın Nebii olduğu halde sen bunu ne hakla söylüyorsun?” Sonra Rasûlullah (s.a.v.), Zümer sûresi 68. ayetini okuyarak şöyle buyurdu: “Başını kaldıranların ilki ben olacağım. Tam bu sırada Musa’yı arşın direklerinden birine yapışmış olarak göreceğim. Başını benden önce mi kaldırmıştır, yoksa Allah’ın istisna ettiğikimselerden midir? bilemiyorum. Kim benim Yunus b. Metta’dan hayırlı olduğunu söylerse yalan söylemiş olur.” Diğer tahric: Buharî, Ehadis-ül Enbiya; Müslim, Fedail Tirmizî: Bu hadis hasen sahihtir
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Hasan Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Hasan Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3245</td></tr><tr><td>Arabic No</td><td>3245</td></tr><tr><td>Reference</td><td>Book 47 Hadith 297</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ابوہریرہ رضی الله عنہ کہتے ہیں کہ ایک یہودی نے مدینہ کے بازار میں کہا: نہیں، قسم ہے اس ذات کی جس نے موسیٰ علیہ السلام کو تمام انسانوں میں سے چن لیا، ( یہ سنا ) تو ایک انصاری شخص نے ہاتھ اٹھا کر ایک طمانچہ اس کے منہ پر مار دیا، کہا: تو ایسا کہتا ہے جب کہ ( تمام انسانوں اور جنوں کے سردار ) نبی اکرم صلی اللہ علیہ وسلم ہمارے درمیان موجود ہیں۔ ( دونوں رسول اللہ صلی اللہ علیہ وسلم کے پاس پہنچے ) رسول اللہ صلی اللہ علیہ وسلم نے آیت: «ونفخ في الصور فصعق من في السموات ومن في الأرض إلا من شاء الله ثم نفخ فيه أخرى فإذا هم قيام ينظرون» ”جب صور پھونکا جائے گا آواز کی کڑک سے سوائے ان کے جنہیں اللہ چاہے گا آسمانوں و زمین کے سبھی لوگ غشی کھا جائیں گے، پھر دوبارہ صور پھونکا جائے گا، تو وہ کھڑے ہو کر دیکھتے ہوں گے ( کہ ان کے ساتھ ) کیا کیا جاتا ہے؟“ ( الزمر: ۶۹ ) ، پڑھی اور کہا: سب سے پہلا سر اٹھانے والا میں ہوں گا تو موسیٰ مجھے عرش کا ایک پایہ پکڑے ہوئے دکھائی دیں گے، میں نہیں کہہ سکتا کہ موسیٰ نے مجھ سے پہلے سر اٹھایا ہو گا یا وہ ان لوگوں میں سے ہوں گے جن کے بارے میں اللہ تعالیٰ نے «إلا من شاء الله» کہہ کر مستثنیٰ کر دیا ہے ۲؎ اور جس نے کہا: میں یونس بن متی علیہ السلام سے بہتر ہوں اس نے غلط کہا ۳؎۔ امام ترمذی کہتے ہیں: یہ حدیث حسن صحیح ہے۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Hasan Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Hasan Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3245</td></tr><tr><td>Arabic No</td><td>3245</td></tr><tr><td>Reference</td><td>Book 47 Hadith 297</td></tr></tbody></table></div>