## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا مُحَمَّدُ بْنُ عَمْرٍو السَّوَّاقُ، حَدَّثَنَا عَبْدُ الْعَزِيزِ بْنُ مُحَمَّدٍ، عَنْ عَمْرِو بْنِ أَبِي عَمْرٍو، عَنْ عِكْرِمَةَ، عَنِ ابْنِ عَبَّاسٍ، قَالَ قَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏"‏ مَنْ وَجَدْتُمُوهُ يَعْمَلُ عَمَلَ قَوْمِ لُوطٍ فَاقْتُلُوا الْفَاعِلَ وَالْمَفْعُولَ بِهِ ‏"‏ ‏.‏ قَالَ وَفِي الْبَابِ عَنْ جَابِرٍ وَأَبِي هُرَيْرَةَ ‏.‏ قَالَ أَبُو عِيسَى وَإِنَّمَا يُعْرَفُ هَذَا الْحَدِيثُ عَنِ ابْنِ عَبَّاسٍ عَنِ النَّبِيِّ صلى الله عليه وسلم مِنْ هَذَا الْوَجْهِ وَرَوَى مُحَمَّدُ بْنُ إِسْحَاقَ هَذَا الْحَدِيثَ عَنْ عَمْرِو بْنِ أَبِي عَمْرٍو فَقَالَ ‏"‏ مَلْعُونٌ مَنْ عَمِلَ عَمَلَ قَوْمِ لُوطٍ ‏"‏ ‏.‏ وَلَمْ يَذْكُرْ فِيهِ الْقَتْلَ وَذَكَرَ فِيهِ مَلْعُونٌ مَنْ أَتَى بَهِيمَةً ‏.‏ وَقَدْ رُوِيَ هَذَا الْحَدِيثُ عَنْ عَاصِمِ بْنِ عُمَرَ عَنْ سُهَيْلِ بْنِ أَبِي صَالِحٍ عَنْ أَبِيهِ عَنْ أَبِي هُرَيْرَةَ عَنِ النَّبِيِّ صلى الله عليه وسلم قَالَ ‏"‏ اقْتُلُوا الْفَاعِلَ وَالْمَفْعُولَ بِهِ ‏"‏ ‏.‏ قَالَ أَبُو عِيسَى هَذَا حَدِيثٌ فِي إِسْنَادِهِ مَقَالٌ وَلاَ نَعْرِفُ أَحَدًا رَوَاهُ عَنْ سُهَيْلِ بْنِ أَبِي صَالِحٍ غَيْرَ عَاصِمِ بْنِ عُمَرَ الْعُمَرِيِّ ‏.‏ وَعَاصِمُ بْنُ عُمَرَ يُضَعَّفُ فِي الْحَدِيثِ مِنْ قِبَلِ حِفْظِهِ ‏.‏ وَاخْتَلَفَ أَهْلُ الْعِلْمِ فِي حَدِّ اللُّوطِيِّ فَرَأَى بَعْضُهُمْ أَنَّ عَلَيْهِ الرَّجْمَ أَحْصَنَ أَوْ لَمْ يُحْصِنْ وَهَذَا قَوْلُ مَالِكٍ وَالشَّافِعِيِّ وَأَحْمَدَ وَإِسْحَاقَ ‏.‏ وَقَالَ بَعْضُ أَهْلِ الْعِلْمِ مِنْ فُقَهَاءِ التَّابِعِينَ مِنْهُمُ الْحَسَنُ الْبَصْرِيُّ وَإِبْرَاهِيمُ النَّخَعِيُّ وَعَطَاءُ بْنُ أَبِي رَبَاحٍ وَغَيْرُهُمْ قَالُوا حَدُّ اللُّوطِيِّ حَدُّ الزَّانِي وَهُوَ قَوْلُ الثَّوْرِيِّ وَأَهْلِ الْكُوفَةِ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1456</td></tr><tr><td>Arabic No</td><td>1456</td></tr><tr><td>Reference</td><td>Book 17 Hadith 40</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
১৪৫৬। ইবনু আব্বাস (রাঃ) হতে বর্ণিত আছে, তিনি বলেন, রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেছেনঃ তোমরা যে মানুষকে লুত সম্প্রদায়ের কুকর্মে (সমকামিতায়) নিয়োজিত পাবে সেই কুকর্মকারীকে এবং যার সাথে কুকর্ম করা হয়েছে তাকে মেরে ফেলবে। সহীহ, ইবনু মা-জাহ (২৫৬১) জাবির ও আবূ হুরাইরা (রাঃ) হতেও এ অনুচ্ছেদে হাদীস বর্ণিত আছে। আবূ ঈসা বলেন, হাদীসটি শুধু উল্লেখিত সনদসূত্রেই আমরা জেনেছি। এ হাদীসটি আমর ইবনু আবী আমরের সূত্রে মুহাম্মাদ ইবনু ইসহাক এভাবে বর্ণনা করেছেনঃ রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেছেনঃ "যে মানুষ লুত সম্প্রদায়ের কুকর্ম করে সে অভিশপ্ত।” এই বর্ণনায় হত্যা করার’ উল্লেখ নেই। এতে আরো আছেঃ "যে মানুষ পশুর সাথে কুকর্ম করে সেও অভিশপ্ত"। " উপরে উল্লেখিত হাদীসটিকে আসিম ইবনু উমার সুহাইল ইবনু আবূ সালিহ-এর সূত্রে, তিনি তার বাবার সূত্রে, তিনি আবূ হুরাইরা (রাঃ)-এর সূত্রে বর্ণনা করেছেন, রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেছেনঃ “এ কাজের কর্তা ও কর্ম দুজনকেই মেরে ফেল"। এ হাদীসের সনদ বিতর্কিত। সুহাইলের সূত্রে এ হাদীসটি আসিম ব্যতীত আর কেউ বর্ণনা করেছেন বলে আমাদের জানা নেই। আসিমের স্মরণশক্তি হাদীস শাস্ত্রে দুর্বল বলে সমালোচিত। অভিজ্ঞ আলিমদের মধ্যে লাওয়াতাতকারীর (সমকামীর) শাস্তির ব্যাপারে মতপার্থক্য আছে। কিছু বিশেষজ্ঞ মনে করেন, সমকামীকে রজম (পাথর মেরে হত্যা) করতে হবে, সে বিবাহিত বা অবিবাহিত যাই হোক। এই মত প্রকাশ করেছেন ইমাম মালিক, শাফিঈ, আহমাদ ও ইসহাক। আতা ইবনু আবূ রাবাহ প্রমুখ বলেছেন, সমকামীর শাস্তি যিনাকারীর শাস্তির মতই। এই মত সুফিয়ান সাওরী ও কূফাবাসীদের।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1456</td></tr><tr><td>Arabic No</td><td>1456</td></tr><tr><td>Reference</td><td>Book 17 Hadith 40</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated Ibn 'Abbas:That the Messenger of Allah (ﷺ) said: "Whomever you find doing the actions of the people of Lut then kill the one doing it, and the one it is done to
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1456</td></tr><tr><td>Arabic No</td><td>1456</td></tr><tr><td>Reference</td><td>Book 17 Hadith 40</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Muhammad bin Amr As Sawwaq], telah menceritakan kepada kami [Abdul Aziz bin Muhammad] dari [Amru bin Abu Amr] dari [Ikrimah] dari [Ibnu Abbas] ia berkata; Rasulullah shallallahu 'alaihi wasallam bersabda: "Barangsiapa yang kalian dapati melakukan perbuatan kaum Nabi Luth (yakni melakukan homoseksual), maka bunuhlah pelaku dan korbannya." Ia mengatakan; Dalam hal ini ada hadits serupa dari Jabir dan Abu Hurairah. Abu Isa berkata; Sesungguhnya hadits ini hanya diketahui dari Ibnu Abbas dari Nabi shallallahu 'alaihi wasallam dari jalur ini, namun [Muhammad bin Ishaq] meriwayatkan hadits ini dari [Amr bin Abu Amr], beliau bersabda: "Terlaknat orang yang melakukan perbuatan kaum Nabi Luth." Dan ia tidak menyebutkan pembunuhan, ia menyebutkan dalam hadits itu: "Terlaknat orang yang menggauli binatang." Hadits ini juga telah diriwayatkan dari ['Ashim bin Umar] dari [Suhail bin Abu Shalih] dari [ayahnya] dari [Abu Hurairah] dari Nabi shallallahu 'alaihi wasallam, beliau bersabda: "Bunuhlah orang yang melakukan dan yang menjadi korbannya." Abu Isa berkata; Hadits ini dalam isnadnya terdapat komentar dan kami tidak mengetahui seseorang pun meriwayatkannya dari Suhail bin Abu Shalih selain 'Ashim bin Umar Al Umari sedangkan 'Ashim bin Umar didla'ifkan dalam periwayatan hadits dari sisi hafalannya. Para ulama berselisih tentang hukuman liwath (homoseksual), sebagian mereka berpendapat; Bahwa ia harus dirajam baik sudah atau belum menikah, ini menjadi pendapat Malik, Asy Syafi'i, Ahmad dan Ishaq. Sedangkan sebagian ulama dari fuqaha tabi'in berpendapat di antaranya Al Hasan Al Bashri, Ibrahim An Nakha'i, 'Atha' bin Abu Rabah dan selain mereka berpendapat; Hukuman liwath seperti hukuman zina, ini menjadi pendapat Ats Tsauri dan ulama Kufah
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1456</td></tr><tr><td>Arabic No</td><td>1456</td></tr><tr><td>Reference</td><td>Book 17 Hadith 40</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>

</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1456</td></tr><tr><td>Arabic No</td><td>1456</td></tr><tr><td>Reference</td><td>Book 17 Hadith 40</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
عبداللہ بن عباس رضی الله عنہما کہتے ہیں کہ رسول اللہ صلی اللہ علیہ وسلم نے فرمایا: ”تم لوگ جسے قوم لوط کا عمل ( اغلام بازی ) کرتے ہوئے پاؤ تو فاعل اور مفعول ( بدفعلی کرنے اور کرانے والے ) دونوں کو قتل کر دو ۱؎۔ امام ترمذی کہتے ہیں: ۱- یہ حدیث بواسطہ ابن عباس رضی الله عنہما نبی اکرم صلی اللہ علیہ وسلم سے صرف اسی سند سے جانی جاتی ہے، محمد بن اسحاق نے بھی اس حدیث کو عمرو بن ابی عمرو سے روایت کیا ہے، ( لیکن اس میں ہے ) آپ نے فرمایا: ”قوم لوط کا عمل ( اغلام بازی ) کرنے والا ملعون ہے“، راوی نے اس حدیث میں قتل کا ذکر نہیں کیا، البتہ اس میں یہ بیان ہے کہ جانور سے وطی ( جماع ) کرنے والا ملعون ہے“، اور یہ حدیث بطریق: «عاصم بن عمر عن سهيل بن أبي صالح عن أبيه عن أبي هريرة عن النبي صلى الله عليه وسلم» روایت کی گئی ہے۔ ( اس میں ہے کہ ) آپ نے فرمایا: ”فاعل اور مفعول دونوں کو قتل کر دو“، ۲- اس حدیث کی سند میں کلام ہے، ہم نہیں جانتے کہ اسے سہیل بن ابی صالح سے عاصم بن عمر العمری کے علاوہ کسی اور نے روایت کیا ہے اور عاصم بن عمر کا حال یہ ہے کہ وہ اپنے حفظ کے تعلق سے حدیث بیان کرنے میں ضعیف ہیں، ۳- اس باب میں جابر اور ابوہریرہ رضی الله عنہما سے بھی احادیث آئی ہیں، ۴- اغلام بازی ( بدفعلی ) کرنے والے کی حد کے سلسلہ میں اہل علم کا اختلاف ہے، بعض کہتے ہیں: بدفعلی کرنے والا شادی شدہ ہو یا غیر شادی شدہ اس کی سزا رجم ہے، مالک شافعی، احمد اور اسحاق بن راہویہ کا یہی قول ہے، ۵- فقہاء تابعین میں سے بعض اہل علم نے جن میں حسن بصری، ابراہیم نخعی اور عطا بن ابی رباح وغیرہ شامل ہیں کہتے ہیں: بدفعلی کرنے والے کی سزا زانی کی سزا کی طرح ہے، ثوری اور اہل کوفہ کا یہی قول ہے۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Isnaad Hasan</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1456</td></tr><tr><td>Arabic No</td><td>1456</td></tr><tr><td>Reference</td><td>Book 17 Hadith 40</td></tr></tbody></table></div>