## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا أَبُو سَلَمَةَ، يَحْيَى بْنُ خَلَفٍ حَدَّثَنَا عَبْدُ الأَعْلَى، عَنْ سَعِيدٍ، عَنْ قَتَادَةَ، عَنِ الْحَسَنِ، عَنْ سَمُرَةَ بْنِ جُنْدَبٍ، أَنَّ النَّبِيَّ صلى الله عليه وسلم قَالَ ‏ "‏ إِذَا أَتَى أَحَدُكُمْ عَلَى مَاشِيَةٍ فَإِنْ كَانَ فِيهَا صَاحِبُهَا فَلْيَسْتَأْذِنْهُ فَإِنْ أَذِنَ لَهُ فَلْيَحْتَلِبْ وَلْيَشْرَبْ وَلاَ يَحْمِلْ وَإِنْ لَمْ يَكُنْ فِيهَا أَحَدٌ فَلْيُصَوِّتْ ثَلاَثًا فَإِنْ أَجَابَهُ أَحَدٌ فَلْيَسْتَأْذِنْهُ فَإِنْ لَمْ يُجِبْهُ أَحَدٌ فَلْيَحْتَلِبْ وَلْيَشْرَبْ وَلاَ يَحْمِلْ ‏"‏ ‏.‏ قَالَ وَفِي الْبَابِ عَنْ عُمَرَ وَأَبِي سَعِيدٍ ‏.‏ قَالَ أَبُو عِيسَى حَدِيثُ سَمُرَةَ حَدِيثٌ حَسَنٌ غَرِيبٌ ‏.‏ وَالْعَمَلُ عَلَى هَذَا عِنْدَ بَعْضِ أَهْلِ الْعِلْمِ وَبِهِ يَقُولُ أَحْمَدُ وَإِسْحَاقُ ‏.‏ قَالَ أَبُو عِيسَى وَقَالَ عَلِيُّ بْنُ الْمَدِينِيِّ سَمَاعُ الْحَسَنِ مِنْ سَمُرَةَ صَحِيحٌ ‏.‏ وَقَدْ تَكَلَّمَ بَعْضُ أَهْلِ الْحَدِيثِ فِي رِوَايَةِ الْحَسَنِ عَنْ سَمُرَةَ وَقَالُوا إِنَّمَا يُحَدِّثُ عَنْ صَحِيفَةِ سَمُرَةَ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1296</td></tr><tr><td>Arabic No</td><td>1296</td></tr><tr><td>Reference</td><td>Book 14 Hadith 98</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
১২৯৬। সামুরা ইবনু জুনদাব (রাঃ) হতে বর্ণিত আছে, নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেছেনঃ তোমাদের কোন লোক কোন পশু পালের নিকট এসে পড়লে সেখানে এর মালিককে পেলে (দুধ দোহনের জন্য) তার অনুমতি চাইবে। সে অনুমতি দিলে দুধ দোহাবে এবং পান করবে। কোন লোক যদি সেখানে উপস্থিত না থাকে তবে তিনবার ডাক দিবে। তার ডাকে কোন লোক সাড়া দিলে তবে তার নিকট অনুমতি চাইবে। তার ডাকে কোন লোক সাড়া না দিলে সে দুধ দোহাবে, তা পান করবে কিন্তু সাথে করে নিয়ে যেতে পারবে না। সহীহ, ইবনু মা-জাহ (২৩০০) উমার ও আবূ সাঈদ (রাঃ) হতেও এ অনুচ্ছেদে হাদীস বর্ণিত আছে। সামুরা (রাঃ) হতে বর্ণিত হাদীসটিকে আবূ ঈসা হাসান গারীব সহীহ বলেছেন। এ হাদীস অনুযায়ী একদল আলিম আমল করেছেন। ইমাম আহমাদ এবং ইসহাকও একথা বলেছেন। আলী ইবনু মাদীনী বলেন, সামুরা (রাঃ)-এর নিকট হাসান যে শুনেছেন তা সত্য। সামুরা (রাঃ)-এর নিকট হাসান বাসরীর হাদীস শুনার ব্যাপারে একদল হাদীস বিশারদ ভিন্নমত পোষণ করেন। তারা বলেছেন, সামুরা (রাঃ)-এর নিকট হতে হাসান (রাহঃ) সরাসরি শুনে বর্ণনা করেননি, বরঞ্চ তার পাণ্ডুলিপি হতে বর্ণনা করেছেন।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1296</td></tr><tr><td>Arabic No</td><td>1296</td></tr><tr><td>Reference</td><td>Book 14 Hadith 98</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated Samurah bin Jundab: That the Prophet (ﷺ) said: "When one of you comes upon livestock, if its owner is with it then seek his permission. If he permits him then let him milk it and drink. If there is no one with it then call out three times, if someone answers then seek his permission. If no one answers then let him milk it and drink without carrying (any of it away)." [He said:] There are narrations on this topic from Ibn 'Umar and Abu Sa'eed. [Abu 'Eisa said:] The Hadith of Samurah is a Hasan Gharib Sahih Hadith. This is acted upon according to some of the people of knowledge, and it is the view of Ahmad and Ishaq. [Abu 'Eisa said:] 'Ali bin Al-Madini said: "It is correct that Al-Hasan heard this from Samurah." Some of the people of Hadith criticized the narrations of Al-Hasan from Samurah, they said that he only narrated from a writing of Samurah
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1296</td></tr><tr><td>Arabic No</td><td>1296</td></tr><tr><td>Reference</td><td>Book 14 Hadith 98</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Abu Salamah Yahya bin Khalaf], telah menceritakan kepada kami [Abdul A'la] dari [Sa'id] dari [Qatadah] dari [Al Hasan] dari [Samurah bin Jundab] bahwa Nabi shallallahu 'alaihi wasallam bersabda: "Jika salah seorang dari kalian mendatangi hewan ternak, jika ada pemiliknya maka mintalah izin, jika ia memberi izin, ia boleh memerah susunya dan meminumnya. Jika tidak ada seorang pun, hendaklah ia berteriak (untuk meminta izin) tiga kali. Jika seseorang menyahutnya, hendaklah ia meminta izin namun jika tidak seorang pun menyahutnya, ia boleh memerah susunya dan meminumnya tetapi tidak boleh membawanya." Ia mengatakan; Dalam hal ini ada hadits serupa dari Umar dan Abu Sa'id. Abu Isa berkata; Hadits Samurah adalah hadits hasan gharib shahih dan menjadi pedoman amal menurut sebagian ulama, ini juga merupakan pendapat Ahmad dan Ishaq. Abu Isa berkata; Ali bin Al Madini berkata; Mendengarnya Al Hasan dari Samurah adalah shahih namun sebagian ahlul Hadits mengomentari riwayat Al Hasan dari Samurah, mereka mengatakan; Sesungguhnya Al Hasan hanya menyampaikan hadits dari buku milik Samurah
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1296</td></tr><tr><td>Arabic No</td><td>1296</td></tr><tr><td>Reference</td><td>Book 14 Hadith 98</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Semure b. Cündüp (r.a.)’den rivâyet edildiğine göre; Rasûlullah (s.a.v.) şöyle buyurmuştur: “Sizden biriniz sağmalı hayvanların bulunduğu bir sürüye uğradığında sahibi orada ise ondan izin alsın kendisine izin verildiğinde sütü sağıp içsin sürü başında kimse yoksa üç sefer seslenip sahibini arasın cevap veren olursa ondan izin alsın, hiç kimse cevap vermez ise sağıp içsin fakat kabına doldurup götürmesin.” Diğer tahric: Ebû Dâvûd, Cihad Tirmîzî: Bu konuda Ömer ve Ebû Saîd’den de hadis rivâyet edilmiştir. Tirmîzî: Semure hadisi hasen garibtir. Bazı ilim adamlarının uygulaması bu hadise göredir. Ahmed ve İshâk bunlardandır. Tirmîzî: Ali el Medînî diyor ki: Hasan’ın, Semure’den hadis işittiği doğrudur. Bazı hadisçiler Hasan’ın, Semure’den rivâyeti hakkında söz etmişler ve “Semure’nin sahifesinden hadis rivâyet ediyor” demişlerdir
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1296</td></tr><tr><td>Arabic No</td><td>1296</td></tr><tr><td>Reference</td><td>Book 14 Hadith 98</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
سمرہ بن جندب رضی الله عنہ سے روایت ہے کہ نبی اکرم صلی اللہ علیہ وسلم نے فرمایا: ”جب تم میں سے کوئی کسی ریوڑ کے پاس ( دودھ پینے ) آئے تو اگر ان میں ان کا مالک موجود ہو تو اس سے اجازت لے، اگر وہ اجازت دیدے تو دودھ پی لے۔ اگر ان میں کوئی نہ ہو تو تین بار آواز لگائے، اگر کوئی جواب دے تو اس سے اجازت لے لے، اور اگر کوئی جواب نہ دے تو دودھ پی لے لیکن ساتھ نہ لے جائے“ ۱؎۔ امام ترمذی کہتے ہیں: ۱- سمرہ کی حدیث حسن غریب ہے، ۲- اس باب میں عمر اور ابو سعید خدری سے بھی احادیث آئی ہیں، ۳- اہل علم کا اسی پر عمل ہے، احمد اور اسحاق بن راہویہ اسی کے قائل ہیں، ۴- علی بن مدینی کہتے ہیں کہ سمرہ سے حسن کا سماع ثابت ہے، ۵- بعض محدثین نے حسن کی روایت میں جسے انہوں نے سمرہ سے روایت کی ہے کلام کیا ہے، وہ لوگ کہتے ہیں کہ حسن سمرہ کے صحیفہ سے حدیث روایت کرتے تھے ۲؎۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1296</td></tr><tr><td>Arabic No</td><td>1296</td></tr><tr><td>Reference</td><td>Book 14 Hadith 98</td></tr></tbody></table></div>