## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا قُتَيْبَةُ، حَدَّثَنَا أَبُو خَالِدٍ الأَحْمَرُ، عَنِ الْحَسَنِ بْنِ عُبَيْدِ اللَّهِ، عَنْ سَعْدِ بْنِ عُبَيْدَةَ، أَنَّ ابْنَ عُمَرَ، سَمِعَ رَجُلاً، يَقُولُ لاَ وَالْكَعْبَةِ ‏.‏ فَقَالَ ابْنُ عُمَرَ لاَ يُحْلَفُ بِغَيْرِ اللَّهِ فَإِنِّي سَمِعْتُ رَسُولَ اللَّهِ صلى الله عليه وسلم يَقُولُ ‏"‏ مَنْ حَلَفَ بِغَيْرِ اللَّهِ فَقَدْ كَفَرَ أَوْ أَشْرَكَ ‏"‏ ‏.‏ قَالَ أَبُو عِيسَى هَذَا حَدِيثٌ حَسَنٌ ‏.‏ وَفُسِّرَ هَذَا الْحَدِيثُ عِنْدَ بَعْضِ أَهْلِ الْعِلْمِ أَنَّ قَوْلَهُ ‏"‏ فَقَدْ كَفَرَ أَوْ أَشْرَكَ ‏"‏ عَلَى التَّغْلِيظِ ‏.‏ وَالْحُجَّةُ فِي ذَلِكَ حَدِيثُ ابْنِ عُمَرَ أَنَّ النَّبِيَّ صلى الله عليه وسلم سَمِعَ عُمَرَ يَقُولُ وَأَبِي وَأَبِي ‏.‏ فَقَالَ ‏"‏ أَلاَ إِنَّ اللَّهَ يَنْهَاكُمْ أَنْ تَحْلِفُوا بِآبَائِكُمْ ‏"‏ ‏.‏ وَحَدِيثُ أَبِي هُرَيْرَةَ عَنِ النَّبِيِّ صلى الله عليه وسلم أَنَّهُ قَالَ ‏"‏ مَنْ قَالَ فِي حَلِفِهِ وَاللاَّتِ وَالْعُزَّى فَلْيَقُلْ لاَ إِلَهَ إِلاَّ اللَّهُ ‏"‏ ‏.‏ قَالَ أَبُو عِيسَى هَذَا مِثْلُ مَا رُوِيَ عَنِ النَّبِيِّ صلى الله عليه وسلم أَنَّهُ قَالَ ‏"‏ إِنَّ الرِّيَاءَ شِرْكٌ ‏"‏ ‏.‏ وَقَدْ فَسَّرَ بَعْضُ أَهْلِ الْعِلْمِ هَذِهِ الآيَة ‏:‏ ‏(‏ وَمَنْ كَانَ يَرْجُو لِقَاءَ رَبِّهِ فَلْيَعْمَلْ عَمَلاً صَالِحًا ‏)‏ الآيَةَ قَالَ لاَ يُرَائِي ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1535</td></tr><tr><td>Arabic No</td><td>1535</td></tr><tr><td>Reference</td><td>Book 20 Hadith 13</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
১৫৩৫। সা’দ ইবনু উবাইদা (রাঃ) হতে বর্ণিত আছে, ইবনু উমার (রাঃ) একজন লোককে বলতে শুনলেন, না, কাবার শপথ! ইবনু উমার (রাঃ) বললেন, আল্লাহ তা'আলার নাম ব্যতীত অন্য কিছুর নামে শপথ করা যাবে না। কেননা রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লামকে আমি বলতে শুনেছিঃ আল্লাহ তা'আলার নাম ব্যতীত অন্য কিছুর নামে যে লোক শপথ করল সে যেন কুফরী করল অথবা শিরক করল। সহীহ, ইরওয়া (২৫৬১), সহীহা (২০৪২) এ হাদীসটিকে আবূ ঈসা হাসান বলেছেন। এ হাদীসের ব্যাখ্যায় কয়েকজন অভিজ্ঞ আলিম বলেছেন, সে কুফরী করল অথবা শিরক করল’ কথাটি রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম ধমকি এবং শাসনের সুরে বলেছেন। তারা নিম্নের হাদীসটি নিজেদের দলীল হিসাবে গ্রহণ করেছেনঃ উমর (রাঃ)-কে তার আব্বার নামে শপথ করতে শুনে নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বললেনঃ সাবধান! তোমাদেরকে নিজেদের আব্বার নামে শপথ করতে আল্লাহ তা'আলা বারণ করেছেন। দ্বিতীয়তঃ আবূ হুরাইরা (রাঃ) বর্ণিত হাদীস-রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বললেনঃ “যে লোক নিজের শপথে বলে, লাতের শপথ! উযযার শপথ! সে যেন বলে, লা ইলাহা ইল্লাল্লাহ!” আবূ ঈসা বলেন, এ হাদীসের তাৎপর্য এরূপ যেমন রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেছেনঃ “লোক দেখানোর মনোবৃত্তি শিরকের সমতুল্য।" যেমন কয়েকজন অভিজ্ঞ আলিম সূরা কাহফের সর্বশেষ আয়াত- “যে লোক তার প্রতিপালকের সাথে সাক্ষাতের আশা রাখে সে যেন সৎকাজ করে এবং তার প্রভুর ইবাদাতের মধ্যে অন্য কাউকে শরীক না করে"-এর ব্যাখ্যায় বলেছেন, লোক দেখানোর উদ্দেশ্যে যেন ইবাদাত না করে।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1535</td></tr><tr><td>Arabic No</td><td>1535</td></tr><tr><td>Reference</td><td>Book 20 Hadith 13</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated Sa'd bin 'Ubaidah:That Ibn 'Umar heard a man saying: "No by the Ka'bah" so Ibn 'Umar said: "Nothing is sworn by other than Allah, for I heard the Messenger of Allah (ﷺ) say: 'Whoever swears by other than Allah, he has committed disbelief or shirk
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1535</td></tr><tr><td>Arabic No</td><td>1535</td></tr><tr><td>Reference</td><td>Book 20 Hadith 13</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Qutaibah] berkata, telah menceritakan kepada kami [Abu Khalid Al Ahmar] dari [Al Hasan bin Ubaidullah] dari [Sa'd bin Ubaidah] bahwa [Ibnu Umar] mendengar seorang laki-laki mengucapkan; "Tidak, demi Ka'bah." Ibnu Umar lalu berkata; "Tidak boleh bersumpah dengan selain Allah. Aku mendengar Rasulullah shallallahu 'alaihi wasallam bersabda: "Barangsiapa bersumpah dengan selain Allah maka ia telah kafir atau berbuat syirik." Abu Isa berkata; "Hadits ini derajatnya hasan. Sebagian ulama' menafsirkan hadits ini, bahwa perkataan Nabi 'telah kafir atau berbuat syirik', adalah untuk penegasan. Dasarnya adalah hadits Ibnu Umar, bahwa Nabi shallallahu 'alaihi wasallam pernah mendengar Umar mengatakan, "Demi bapakku, demi bapakku." Rasulullah pun bersabda: "Ketahuilah, sesungguhnya Allah melarang kalian bersumpah dengan bapak-bapak kalian." Juga, hadits Abu Hurairah dari Nabi shallallahu 'alaihi wasallam, Bahwasanya ketika ada orang yang berkata dalam sumpahnya, "Demi Lata dan Uzza." Beliau bersabda: "Hendaklah ia mengatakan 'Tidak ada Tuhan yang berhak disembah selain Allah'."Abu Isa berkata; "Hadits ini semisal dengan apa yang diriwayatkan dari nabi shallallahu 'alaihi wasallam, beliau bersabda: "Sesungguhnya riya itu syirik." Sebagian ulama' mentafsirkan ayat ini: (Barangsiapa mengharap perjumpaan dengan Tuhannya, maka hendaklah ia mengerjakan amal yang saleh) -Qs. Al Kahfi: 100-, yaitu tidak boleh riya
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1535</td></tr><tr><td>Arabic No</td><td>1535</td></tr><tr><td>Reference</td><td>Book 20 Hadith 13</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Sa’d b. Ubeyde (radıyallahü anh)’den rivâyete göre, İbn Ömer bir adamın “Ka’be’ye yemin olsun ki hayır” dediğimi işitince şöyle dedi: “Allah’tan başkası adına yemin edilmez. Rasûlüllah (sallallahü aleyhi ve sellem)’den işittim şöyle diyordu: Kim Allah’tan başkası adına yemin ederse kafir veya müşrik olmuş olur.” (Müslim, Eyman: 1; Ebû Dâvûd, Eyman: 4) Bu hadis hasendir. Bu hadis bazı ilim adamlarınca şöyle tefsir edilmiştir: “Kafir veya müşrik olmuş olur.” Sözü hükmü ağırlaştırmak için söylenmiştir. İbn Ömer hadisi buna delildir. Çünkü o hadiste: “Rasûlüllah (sallallahü aleyhi ve sellem), Ömer’in babam için babam adına diyerek yemin ettiğini duyunca Allah sizi bu tür yeminlerden de yasakladı” buyurmuştur. Yine aynı şekilde Ebû Hüreyre tarafından rivâyet edilen: “Kim yemininde lat ve uzza hakkı için derse hemen lailahe illallah desin” hadiste buna delil olabilir. Bu hadis Rasûlüllah (sallallahü aleyhi ve sellem)’den rivâyet edilen “Riya şirktir” hadisine de benzer. İlim adamlarından bazıları (18 Kehf: 110. âyet)’inde geçen “Vela yüşrik” kelimesini “Gösteriş yapmamak” şeklinde yorumlanmıştır
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1535</td></tr><tr><td>Arabic No</td><td>1535</td></tr><tr><td>Reference</td><td>Book 20 Hadith 13</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
سعد بن عبیدہ سے روایت ہے کہ ابن عمر رضی الله عنہما نے ایک آدمی کو کہتے سنا: ایسا نہیں قسم ہے کعبہ کی، تو اس سے کہا: غیر اللہ کی قسم نہ کھائی جائے، کیونکہ میں نے رسول اللہ صلی اللہ علیہ وسلم کو فرماتے سنا ہے: ”جس نے غیر اللہ کی قسم کھائی اس نے کفر کیا یا شرک کیا“۔ امام ترمذی کہتے ہیں: ۱- یہ حدیث حسن ہے، ۲- اس حدیث کی تفسیر بعض اہل علم کے نزدیک یہ ہے کہ نبی اکرم صلی اللہ علیہ وسلم کا فرمان «فقد كفر أو أشرك» تنبیہ و تغلیظ کے طور پر ہے، اس کی دلیل ابن عمر رضی الله عنہما کی حدیث ہے، نبی اکرم صلی اللہ علیہ وسلم نے عمر کو کہتے سنا: میرے باپ کی قسم، میرے باپ کی قسم! تو آپ صلی اللہ علیہ وسلم نے فرمایا: ”اللہ باپ، دادا کی قسم کھانے سے منع فرماتا ہے“، نیز ابوہریرہ رضی الله عنہ کی ( روایت ) کہ نبی اکرم صلی اللہ علیہ وسلم نے فرمایا: ”جس نے لات اور عزیٰ کی قسم کھائی وہ «لا إله إلا الله» کہے، امام ترمذی کہتے ہیں: ۳- یہ نبی اکرم صلی اللہ علیہ وسلم کے اس فرمان کی طرح ہے ”بیشک ریا، شرک ہے، ۴- بعض اہل علم نے آیت کریمہ «فمن كان يرجو لقاء ربه فليعمل عملا صالحا» ( الکہف: ۱۱۰ ) کی یہ تفسیر کی ہے کہ وہ ریا نہ کرے۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1535</td></tr><tr><td>Arabic No</td><td>1535</td></tr><tr><td>Reference</td><td>Book 20 Hadith 13</td></tr></tbody></table></div>