## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا الأَنْصَارِيُّ، حَدَّثَنَا مَعْنٌ، حَدَّثَنَا مَالِكُ بْنُ أَنَسٍ، عَنِ ابْنِ شِهَابٍ، عَنِ السَّائِبِ بْنِ يَزِيدَ، عَنِ الْمُطَّلِبِ بْنِ أَبِي وَدَاعَةَ السَّهْمِيِّ، عَنْ حَفْصَةَ، زَوْجِ النَّبِيِّ صلى الله عليه وسلم أَنَّهَا قَالَتْ مَا رَأَيْتُ رَسُولَ اللَّهِ صلى الله عليه وسلم صَلَّى فِي سُبْحَتِهِ قَاعِدًا حَتَّى كَانَ قَبْلَ وَفَاتِهِ صلى الله عليه وسلم بِعَامٍ فَإِنَّهُ كَانَ يُصَلِّي فِي سُبْحَتِهِ قَاعِدًا وَيَقْرَأُ بِالسُّورَةِ وَيُرَتِّلُهَا حَتَّى تَكُونَ أَطْوَلَ مِنْ أَطْوَلَ مِنْهَا ‏.‏ وَفِي الْبَابِ عَنْ أُمِّ سَلَمَةَ وَأَنَسِ بْنِ مَالِكٍ ‏.‏ قَالَ أَبُو عِيسَى حَدِيثُ حَفْصَةَ حَدِيثٌ حَسَنٌ صَحِيحٌ ‏.‏ وَقَدْ رُوِيَ عَنِ النَّبِيِّ صلى الله عليه وسلم أَنَّهُ كَانَ يُصَلِّي مِنَ اللَّيْلِ جَالِسًا فَإِذَا بَقِيَ مِنْ قِرَاءَتِهِ قَدْرُ ثَلاَثِينَ أَوْ أَرْبَعِينَ آيَةً قَامَ فَقَرَأَ ثُمَّ رَكَعَ ثُمَّ صَنَعَ فِي الرَّكْعَةِ الثَّانِيَةِ مِثْلَ ذَلِكَ ‏.‏ وَرُوِيَ عَنْهُ أَنَّهُ كَانَ يُصَلِّي قَاعِدًا فَإِذَا قَرَأَ وَهُوَ قَائِمٌ رَكَعَ وَسَجَدَ وَهُوَ قَائِمٌ وَإِذَا قَرَأَ وَهُوَ قَاعِدٌ رَكَعَ وَسَجَدَ وَهُوَ قَاعِدٌ ‏.‏ قَالَ أَحْمَدُ وَإِسْحَاقُ وَالْعَمَلُ عَلَى كِلاَ الْحَدِيثَيْنِ ‏.‏ كَأَنَّهُمَا رَأَيَا كِلاَ الْحَدِيثَيْنِ صَحِيحًا مَعْمُولاً بِهِمَا ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>373</td></tr><tr><td>Arabic No</td><td>373</td></tr><tr><td>Reference</td><td>Book 2 Hadith 225</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
৩৭৩। রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লামের স্ত্রী হাফসা (রাঃ) হতে বর্ণিত আছে, তিনি বলেন, রাসূলুল্লাহ সাল্লাল্লাহু 'আলাইহি ওয়াসাল্লামের ইন্তিকালের এক বছর পূর্ব পর্যন্ত আমি তাকে বসে বসে নফল নামায আদায় করতে দেখিনি। তারপর তিনি বসে বসে নফল নামায আদায় করতেন এবং সূরাসমূহ শান্ত-স্থিরভাবে থেমে থেমে পাঠ করতেন। এতে তা দীর্ঘ হতে দীর্ঘতর হত। —সহীহ। সিফাতুস সালাত- (৬০), মুসলিম। এ অনুচ্ছেদে উম্মু সালামা এবং আনাস ইবনু মালিক (রাঃ) হতেও হাদীস বর্ণিত আছে। আবু ঈসা বলেনঃ হাফসার হাদীসটি হাসান সহীহ। নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লামের নিকট হতে এরূপও বর্ণিত হয়েছেঃ “তিনি রাতের বেলা বসে নামায আদায় করতেন। কিরা'আতের তিরিশ অথবা চল্লিশ আয়াত বাকি থাকতে তিনি উঠে দাঁড়াতেন এবং তা পড়ে রুকূ-সিজদা করতেন। দ্বিতীয় রাকআতেও তিনি এরূপ করতেন। আরো বর্ণিত আছে, তিনি বসে নামায আদায় করতেন যখন তিনি দাড়িয়ে কিরা'আত পাঠ করতেন, রুকূ-সিজদাও দাঁড়িয়ে করতেন। তিনি বসে কিরা'আত পাঠ করলে রুকূ-সজদাহও বসে করতেন।” ইমাম আহমাদ ও ইসহাক বলেন, উভয় হাদীস অনুযায়ী আমল করা যায়। অর্থাৎ দু'টো হাদীসই সহীহ এবং তদনুযায়ী আমল করার যোগ্য।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>373</td></tr><tr><td>Arabic No</td><td>373</td></tr><tr><td>Reference</td><td>Book 2 Hadith 225</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Hafsah, the wife of the Prophet (S), narrated:"I did not see Allah's Messenger (S) praying voluntary prayers sitting until the year before he died. Then he would perform Salat for the voluntary prayers sitting, and he would recite a Surah and prolong it such that it would be longer than the longest of them
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>373</td></tr><tr><td>Arabic No</td><td>373</td></tr><tr><td>Reference</td><td>Book 2 Hadith 225</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Al Anshar] berkata; telah menceritakan kepada kami [Ma'n] berkata; telah menceritakan kepada kami [Malik bin Anas] dari [Ibnu Syihab] dari [As Sa'ib bin Yazid] dari [Al Muthallib bin Abu Wada'ah As Sahmi] dari [Hafshah] istri Nabi shallallahu 'alaihi wasallam, ia pernah berkata; "Aku tidak pernah melihat Rasulullah shallallahu 'alaihi wasallam shalat sunnah dengan duduk hingga setahun menjelang kewafatannya. Beliau melaksanakan shalat sunnah sambil duduk dengan membaca surah secara tartil hingga surah itu menjadi panjang dari yang terpanjang." Ia berkata; "Dalam bab ini juga ada riwayat dari Ummu Salamah dan Anas bin Malik." Abu Isa berkata; "Hadits Hafshah ini derajatnya hasan shahih. Telah diriwayatkan dari Nabi shallallahu 'alaihi wasallam bahwasanya beliau pernah shalat malam dengan duduk, maka ketika bacaannya tersisa kira-kira tiga puluh atau empat puluh ayat beliau berdiri dan membaca lagi, setelah itu rukuk. Beliau juga melakukan demikian di rakaat kedua." Diriwayatkan pula darinya bahwa Nabi shallallahu 'alaihi wasallam jika shalat dengan duduk, maka ketika membaca (surah) berliau berdiri, lalu rukuk dan sujud dengan berdiri. Ketika beliau membaca dalam keadaan duduk, maka beliau rukuk dan sujud dalam keadaan duduk. Ahmad dan Ishaq berpendapat atas dibolehkanya mengamalkan hadits ini. seakan-akan mereka berpandangan bahwa kedua hadits ini shahih dan boleh diamalkan
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>373</td></tr><tr><td>Arabic No</td><td>373</td></tr><tr><td>Reference</td><td>Book 2 Hadith 225</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Nebi’mizin hanımlarından Hafsa (r.anha)’dan rivâyet edildiğine göre, şöyle demiştir: “Rasûlullah (s.a.v.)’in vefatından bir yıl öncesine kadar nafile namazlarını oturarak kıldığını görmedim. Fakat bu süreden sonra nafile namazlarını oturarak kılar okuduğu sûreyi tertil üzere okur bu şekilde o okuduğu sûre kendisinden daha uzun sûrelerden daha uzun olurdu.” Diğer tahric: Müslim, Salat-ül Müsafirin; Nesâî, Kıyam-ül leyl Bu konuda Ümmü Seleme, Enes b. Mâlik’den de hadis rivâyet edilmiştir. Tirmîzî: Hafsa hadisi hasen sahihtir. Peygamber (s.a.v.)’den şöyle de rivâyet edilmiştir: “Geceleyin oturarak namaz kılar, okumasının bitmesine otuz kırk ayet kalınca ayağa kalkar kalan okumasını ayakta tamamlar sonra rükû’ a giderdi. İkinci rek’atta da aynı şekilde yapardı.” Rasûlullah (s.a.v.)’den şöyle de rivâyet edilmiştir: “Oturarak namaz kıldığı zaman, kıraat, rükû’ ve secdeleri oturduğu halde yapar, ayakta namaz kıldığında ise rükû’ ve secdeleri ayakta iken yapardı.” Ahmed ve İshâk diyorlar ki: Her iki hadisle de amel edilmiştir, iki hadiste sahih olup ikisiyle de amel edilmiştir
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>373</td></tr><tr><td>Arabic No</td><td>373</td></tr><tr><td>Reference</td><td>Book 2 Hadith 225</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ام المؤمنین حفصہ رضی الله عنہا کہتی ہیں کہ میں نے رسول اللہ صلی اللہ علیہ وسلم کو کبھی بیٹھ کر نفل نماز پڑھتے نہیں دیکھا، یہاں تک کہ جب وفات میں ایک سال رہ گیا تو آپ بیٹھ کر نفلی نماز پڑھنے لگے۔ اور سورت پڑھتے تو اس طرح ٹھہر ٹھہر کر پڑھتے کہ وہ لمبی سے لمبی ہو جاتی۔ امام ترمذی کہتے ہیں: ۱- حفصہ رضی الله عنہا کی حدیث حسن صحیح ہے، ۲- اس باب میں ام سلمہ اور انس بن مالک رضی الله عنہما سے بھی احادیث آئی ہے، ۳- نبی اکرم صلی اللہ علیہ وسلم سے مروی ہے کہ آپ رات کو بیٹھ کر نماز پڑھتے اور جب تیس یا چالیس آیتوں کے بقدر قرأت باقی رہ جاتی تو آپ کھڑے ہو جاتے اور قرأت کرتے پھر رکوع میں جاتے۔ پھر دوسری رکعت میں بھی اسی طرح کرتے۔ اور آپ سے یہ بھی مروی ہے کہ آپ بیٹھ کر نماز پڑھتے۔ اور جب کھڑے ہو کر قرأت کرتے تو رکوع اور سجدہ بھی کھڑے ہو کر کرتے اور جب بیٹھ قرأت کرتے تو رکوع اور سجدہ بھی بیٹھ ہی کر کرتے۔ ۴- احمد اور اسحاق بن راہویہ کہتے ہیں کہ دونوں حدیثیں صحیح اور معمول بہ ہیں ۱؎۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>373</td></tr><tr><td>Arabic No</td><td>373</td></tr><tr><td>Reference</td><td>Book 2 Hadith 225</td></tr></tbody></table></div>