## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا مَحْمُودُ بْنُ غَيْلاَنَ، حَدَّثَنَا عُثْمَانُ بْنُ عُمَرَ، حَدَّثَنَا شُعْبَةُ، عَنْ أَبِي جَعْفَرٍ، عَنْ عُمَارَةَ بْنِ خُزَيْمَةَ بْنِ ثَابِتٍ، عَنْ عُثْمَانَ بْنِ حُنَيْفٍ، أَنَّ رَجُلاً، ضَرِيرَ الْبَصَرِ أَتَى النَّبِيَّ صلى الله عليه وسلم فَقَالَ ادْعُ اللَّهَ أَنْ يُعَافِيَنِي ‏.‏ قَالَ ‏"‏ إِنْ شِئْتَ دَعَوْتُ وَإِنْ شِئْتَ صَبَرْتَ فَهُوَ خَيْرٌ لَكَ ‏"‏ ‏.‏ قَالَ فَادْعُهُ ‏.‏ قَالَ فَأَمَرَهُ أَنْ يَتَوَضَّأَ فَيُحْسِنَ وُضُوءَهُ وَيَدْعُوَ بِهَذَا الدُّعَاءِ ‏"‏ اللَّهُمَّ إِنِّي أَسْأَلُكَ وَأَتَوَجَّهُ إِلَيْكَ بِنَبِيِّكَ مُحَمَّدٍ نَبِيِّ الرَّحْمَةِ إِنِّي تَوَجَّهْتُ بِكَ إِلَى رَبِّي فِي حَاجَتِي هَذِهِ لِتُقْضَى لِي اللَّهُمَّ فَشَفِّعْهُ فِيَّ ‏"‏ ‏.‏ قَالَ هَذَا حَدِيثٌ حَسَنٌ صَحِيحٌ غَرِيبٌ لاَ نَعْرِفُهُ إِلاَّ مِنْ هَذَا الْوَجْهِ مِنْ حَدِيثِ أَبِي جَعْفَرٍ وَهُوَ غَيْرُ الْخَطْمِيِّ وَعُثْمَانُ بْنُ حُنَيْفٍ هُوَ أَخُو سَهْلِ بْنِ حُنَيْفٍ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3578</td></tr><tr><td>Arabic No</td><td>3578</td></tr><tr><td>Reference</td><td>Book 48 Hadith 209</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
৩৫৭৮। উসমান ইবনু হুনাইফ (রাযিঃ) হতে বর্ণিত আছে, এক অন্ধ ব্যক্তি নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর কাছে এসে বললেন, হে আল্লাহর নবী। আমার জন্য আল্লাহ তা'আলার নিকট দু'আ করুন, যেন আমাকে তিনি আরোগ্য দান করেন। তিনি বললেনঃ তুমি কামনা করলে আমি দুআ করব, আর তুমি চাইলে ধৈর্য ধারণ করতে পার, সেটা হবে তোমার জন্য উত্তম। সে বলল, তার নিকটে দু'আ করুন। বর্ণনাকারী বলেন, তিনি তাকে উত্তমভাবে উযূ করার হুকুম করলেন এবং এই দুআ করতে বললেন, “হে আল্লাহ! তোমার নিকট আমি প্রার্থনা করি এবং তোমার প্রতি মনোনিবেশ করি তোমার নবী, দয়ার নবী মুহাম্মাদ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর (দু'আর) মাধ্যমে। আমি তোমার দিকে ঝুঁকে পড়লাম, আমার প্রয়োজনের জন্য আমার প্রভুর দিকে ধাবিত হলাম, যাতে আমার এ প্রয়োজন পূর্ণ করে দেয়া হয়। হে আল্লাহ! আমার প্রসঙ্গে তুমি তার সুপারিশ কবুল কর”। সহীহঃ ইবনু মাজাহ (১৩৮৫)। আবূ ঈসা বলেন, এ হাদীসটি হাসান সহীহ গারীব। কেননা হাদীসটি আবূ জাফরের রিওয়ায়াত ছাড়া অপর কোন সনদে আমরা জানতে পারিনি। এই আবূ জাফর হলেন আল-খাতী, আর উসমান ইবনু হুনাইফ হলেন সাহল ইবনু হুনাইনের ভাই।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3578</td></tr><tr><td>Arabic No</td><td>3578</td></tr><tr><td>Reference</td><td>Book 48 Hadith 209</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Uthman bin Hunaif narrated that a blind man came to the Prophet (ﷺ) and said:“Supplicate to Allah to heal me.” He (ﷺ) said: “If you wish I will supplicate for you, and if you wish, you can be patient, for that is better for you.” He said: “Then supplicate to Him.” He said: “So he ordered him to perform Wudu’ and to make his Wudu’ complete, and to supplicate with this supplication: ‘O Allah, I ask You and turn towards You by Your Prophet Muhammad (ﷺ), the Prophet of Mercy. Indeed, I have turned to my Lord, by means of You, concerning this need of mine, so that it can be resolved, so O Allah so accept his intercession for me (Allāhumma innī as’aluka wa atawajjahu ilaika binabiyyka Muḥammadin nabi-ir-raḥmati, innī tawajjahtu bika ila rabbī fī ḥājatī hādhihī lituqḍā lī, Allāhumma fashaffi'hu fīyya).’”
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3578</td></tr><tr><td>Arabic No</td><td>3578</td></tr><tr><td>Reference</td><td>Book 48 Hadith 209</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Mahmud bin Ghailan] telah menceritakan kepada kami [Utsman bin Umar] telah menceritakan kepada kami [Syu'bah] dari [Abu Ja'far] dari ['Umarah bin Khuzaimah bin Tsabit] dari [Utsman bin Hunaif] bahwa seorang laki-laki yang buta matanya datang kepada Nabi shallallahu 'alaihi wasallam seraya berkata; "Berdo'alah kepada Allah agar menyembuhkanku." beliau bersabda: "jika kamu berkehendak maka saya akan mendo'akanmu, dan jika kamu berkehendak maka bersabarlah, karena hal itu lebih baik bagimu." laki-laki tersebut berkata; "berdo'alah (kepada Allah untukku)." Utsman bin Hunaif berkata; "Lalu beliau ia memerintahkannya untuk berwudhu, kemudian ia pun membaguskan wudhunya dan berdo'a dengan do'a berikut ini, "Ya Allah! Aku memohon kepada-Mu, menghadap kepada-Mu dengan (syafa'at) nabi-Mu Muhammad, nabi yang diutus dengan membawa rahmat." (laki-laki itu berkata); "Aku telah memohon syafa'atmu kepada Rab-ku untuk memenuhi kebutuhanku." (Sabda beliau): "Ya Allah! Terimalah syafa'atnya untukku." Abu Isa berkata; "Hadits ini derajatnya hadits hasan shahih gharib, kami tidak mengetahuinya kecuali dari jalur ini, yaitu dari hadits Abu Ja'far Al Khathmi, sedangkan Utsman bin Hunaif adalah saudara laki-lakinya Sahl bin Hunaif
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3578</td></tr><tr><td>Arabic No</td><td>3578</td></tr><tr><td>Reference</td><td>Book 48 Hadith 209</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Osman b. Huneyf (r.a.)’den rivâyete göre, Gözleri görmeyen bir adam Nebi (s.a.v)’e geldi ve: “Allah’ın bana afiyet vermesi için bana duâ et” dedi. Rasûlullah (s.a.v.)’de: “İstersen duâ edeyim ama sabretmen senin için daha hayırlıdır” buyurdu. Adam: “Duâ et” dedi. Bunun üzerine Rasûlullah (s.a.v.), ona güzelce abdest almasını ve şu duâlarla duâ etmesini emretti: “Allah’ım Rahmet Nebisi Nebin Muhammed ile senden istiyor ve sana yöneliyorum. Bu ihtiyacım konusunda ben rabbime yöneliyorum. Allah’ım o Nebiini bana şefaatçi kıl.”
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3578</td></tr><tr><td>Arabic No</td><td>3578</td></tr><tr><td>Reference</td><td>Book 48 Hadith 209</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
عثمان بن حنیف رضی الله عنہ سے روایت ہے کہ ایک نابینا شخص نبی اکرم صلی اللہ علیہ وسلم کے پاس آیا اور کہا: آپ دعا فرما دیجئیے کہ اللہ مجھے عافیت دے، آپ نے فرمایا: ”اگر تم چاہو تو میں دعا کروں اور اگر چاہو تو صبر کیے رہو، کیونکہ یہ تمہارے لیے زیادہ بہتر ( و سود مند ) ہے“۔ اس نے کہا: دعا ہی کر دیجئیے، تو آپ نے اسے حکم دیا کہ ”وہ وضو کرے، اور اچھی طرح سے وضو کرے اور یہ دعا پڑھ کر دعا کرے: «اللهم إني أسألك وأتوجه إليك بنبيك محمد نبي الرحمة إني توجهت بك إلى ربي في حاجتي هذه لتقضى لي اللهم فشفعه» ”اے اللہ! میں تجھ سے مانگتا ہوں اور تیرے نبی محمد جو نبی رحمت ہیں کے وسیلے سے تیری طرف متوجہ ہوتا ہوں، میں نے آپ کے واسطہ سے اپنی اس ضرورت میں اپنے رب کی طرف توجہ کی ہے تاکہ تو اے اللہ! میری یہ ضرورت پوری کر دے تو اے اللہ تو میرے بارے میں ان کی شفاعت قبول کر ۱؎“۔ امام ترمذی کہتے ہیں: ۱- یہ حدیث حسن صحیح غریب ہے اور ہم اسے صرف اسی سند سے جانتے ہیں یعنی ابو جعفر کی روایت سے، ۲- اور ابوجعفر خطمی ہیں ۳- اور عثمان بن حنیف یہ سہل بن حنیف کے بھائی ہیں۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Isnaad Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3578</td></tr><tr><td>Arabic No</td><td>3578</td></tr><tr><td>Reference</td><td>Book 48 Hadith 209</td></tr></tbody></table></div>