## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا سُوَيْدُ بْنُ نَصْرٍ، حَدَّثَنَا عَبْدُ اللَّهِ بْنُ الْمُبَارَكِ، أَخْبَرَنَا اللَّيْثُ بْنُ سَعْدٍ، أَخْبَرَنَا عَبْدُ رَبِّهِ بْنُ سَعِيدٍ، عَنْ عِمْرَانَ بْنِ أَبِي أَنَسٍ، عَنْ عَبْدِ اللَّهِ بْنِ نَافِعِ ابْنِ الْعَمْيَاءِ، عَنْ رَبِيعَةَ بْنِ الْحَارِثِ، عَنِ الْفَضْلِ بْنِ عَبَّاسٍ، قَالَ قَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏"‏ الصَّلاَةُ مَثْنَى مَثْنَى تَشَهَّدُ فِي كُلِّ رَكْعَتَيْنِ وَتَخَشَّعُ وَتَضَرَّعُ وَتَمَسْكَنُ وَتَذَرَّعُ وَتُقْنِعُ يَدَيْكَ يَقُولُ تَرْفَعُهُمَا إِلَى رَبِّكَ مُسْتَقْبِلاً بِبُطُونِهِمَا وَجْهَكَ وَتَقُولُ يَا رَبِّ يَا رَبِّ وَمَنْ لَمْ يَفْعَلْ ذَلِكَ فَهُوَ كَذَا وَكَذَا ‏"‏ ‏.‏ قَالَ أَبُو عِيسَى وَقَالَ غَيْرُ ابْنِ الْمُبَارَكِ فِي هَذَا الْحَدِيثِ ‏"‏ مَنْ لَمْ يَفْعَلْ ذَلِكَ فَهِيَ خِدَاجٌ ‏"‏ ‏.‏ قَالَ أَبُو عِيسَى سَمِعْتُ مُحَمَّدَ بْنَ إِسْمَاعِيلَ يَقُولُ رَوَى شُعْبَةُ هَذَا الْحَدِيثَ عَنْ عَبْدِ رَبِّهِ بْنِ سَعِيدٍ فَأَخْطَأَ فِي مَوَاضِعَ فَقَالَ عَنْ أَنَسِ بْنِ أَبِي أَنَسٍ وَهُوَ عِمْرَانُ بْنُ أَبِي أَنَسٍ وَقَالَ عَنْ عَبْدِ اللَّهِ بْنِ الْحَارِثِ وَإِنَّمَا هُوَ عَبْدُ اللَّهِ بْنُ نَافِعِ ابْنِ الْعَمْيَاءِ عَنْ رَبِيعَةَ بْنِ الْحَارِثِ ‏.‏ وَقَالَ شُعْبَةُ عَنْ عَبْدِ اللَّهِ بْنِ الْحَارِثِ عَنِ الْمُطَّلِبِ عَنِ النَّبِيِّ صلى الله عليه وسلم وَإِنَّمَا هُوَ عَنْ رَبِيعَةَ بْنِ الْحَارِثِ بْنِ عَبْدِ الْمُطَّلِبِ عَنِ الْفَضْلِ بْنِ عَبَّاسٍ عَنِ النَّبِيِّ صلى الله عليه وسلم ‏.‏ قَالَ مُحَمَّدٌ وَحَدِيثُ اللَّيْثِ بْنِ سَعْدٍ يَعْنِي أَصَحَّ مِنْ حَدِيثِ شُعْبَةَ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>385</td></tr><tr><td>Arabic No</td><td>385</td></tr><tr><td>Reference</td><td>Book 2 Hadith 237</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
৩৮৫। ফযল ইবনু আব্বাস (রাঃ) হতে বর্ণিত আছে, তিনি বলেনঃ রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেছেনঃ নামায দুই দুই রাকাআত; প্রতি দুই রাকাআত পর তাশাহহুদ পাঠ করতে হবে; নামায়ীকে বিনয়ী হতে হবে, মিনতির সাথে প্রার্থনা করতে হবে; কপর্দকহীন হতে হবে। কোন কিছুকে ওয়াসীলা করে চাইতে হবে। এ অবস্থায় তোমার প্রতিপালকের দরবারে নিজের দু'হাত তুলবে, হাতের তালু তোমার চেহারার দিকে থাকবে, তারপর বলবে, হে প্ৰভু, হে প্রতিপালক। যে ব্যক্তি এমনটি না করবে তার নামায এরূপ এবং এরূপ হবে। যঈফ, ইবনু মাজাহ (১৩২৫) আবূ ঈসা বলেনঃ ইবনুল মুবারাক ছাড়া অন্যান্য রাবীগণ হাদীসের শেষের অংশ এরূপ বর্ণনা করেছেনঃ যে ব্যক্তি এরূপ (বিনয়-নম্রতা অবলম্বন) করল না তার নামায পূর্ণাঙ্গ হল না। আবূ ঈসা বলেন, আমি মুহাম্মাদ ইবনু ইসমাঈল বুখারীকে বলতে শুনেছি, শুবা এ হাদীসটি আবদে রাব্বিহি ইবনু সাঈদের সূত্রে বর্ণনা করেছেন। কিন্তু তিনি কয়েকটি জায়গায় ভুল করেছেন। তিনি বলেছেন, আনাস ইবনু আবী আনাস হতে প্রকৃত পক্ষে তা হবে ইমরান ইবনু আবী আনাস, তিনি বলেছেন আব্দুল্লাহ ইবনুল হারিস হতে প্রকৃত পক্ষে তা হবে আব্দুল্লাহ ইবনু নাফি হতে তিনি রাবীয়া ইবনুল হারিস হতে। শুবা বলেছেন আব্দুল্লাহ ইবনুল হারিস হতে তিনি মুত্তালিব হতে তিনি নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম হতে। প্রকৃত পক্ষে তা হবে রাবীয়া ইবনুল হারিস ইবনু আব্দুল মুত্তালিব হতে, তিনি ফাযল ইবনুল আব্বাস হতে তিনি নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম হতে। মুহাম্মাদ (বুখারী) বলেছেন, শুবার বর্ণিত হাদীসের চেয়ে লাইসের বর্ণনাটি বেশি সহীহ।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>385</td></tr><tr><td>Arabic No</td><td>385</td></tr><tr><td>Reference</td><td>Book 2 Hadith 237</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Al-Fadl bin Al-'Abbas narrated that:Allah's Messenger (S) said: "As-Salat is two and two, with a Tashahhud for every two Rak'ah, with humility, imploring, having a sense of tranquility, pleading and showing helplessness and stretching out your hand" - he said: raising them - "to your Lord, with the insides of them facing your face, saying: 'O Lord! O Lord! And whoever does not do this, then it is like this or that
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>385</td></tr><tr><td>Arabic No</td><td>385</td></tr><tr><td>Reference</td><td>Book 2 Hadith 237</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Suwaid bin Nashr] berkata; telah menceritakan kepada kami [Abdullah bin Al Mubarak] berkata; telah mengabarkan kepada kami [Al Laits bin Sa'd] berkata; telah mengabarkan kepada kami [Abdu Rabbih bin Sa'id] dari [Imran bin Abu Anas] dari [Abdullah bin Nafi' bin Al Amya'] dari [Rabi'ah Ibnil Harits] dari [Al Fadll bin Abbas] ia berkata; "Rasulullah shallallahu 'alaihi wasallam bersabda: "Shalat itu dua rakaat dua rakaat, duduk tasyahud pada setiap dua rakaat, khusyu', tunduk, tenang dan menengadahkan kedua tanganmu." Beliau bersabda lagi: "Engkau angkat kedua tanganmu pada Rabbmu dengan menghadapkan bagian depan telapak tangan ke wajahmu. Engkau katakan, "Ya Rabb, Ya Rabb, " dan barangsiapa tidak melakukan hal itu maka ia begini dan begini." Abu Isa berkata; "Selain bin Al Mubarak dan juga yang mengatakan tentang hadits ini, "Barangsiapa tidak melakukan seperti itu maka shalatnya kurang (tidak sempurna)." Abu Isa berkata; "Aku mendengar Muhammd bin Isma'il berkata; "Syu'bah meriwayatkan hadits ini dari Abdu Rabbih bin Sa'id namun ia salah dalam beberapa tempat. Ia berkata; "Dari Anas bin Abu Anas, dia adalah Imran bin Abu Anas." Ia berkata; "Dari Abdullah bin Al Harits, padahal dia adalah Abdullan bin Nafi' bin Al Amya', dari Rabi'ah bin Al Harits." Syu'bah berkata dari Abdullah bin Al Harits, dari Abdul Muthallib, dari Al fall bin Abbas, dari Nabi shallallahu 'alaihi wasallam." Muhammad berkata; "Hadits Al Laits bin Sa'd derajatnya hasan shahih, yakni lebih shahih dari hadits Syu'bah
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>385</td></tr><tr><td>Arabic No</td><td>385</td></tr><tr><td>Reference</td><td>Book 2 Hadith 237</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Fadl b. Abbâs (r.a.)’den rivâyete göre, Rasûlullah (s.a.v.) şöyle buyurmuştur: “Namaz ikişer rek’attır her iki rek’atta bir oturum vardır. Allah’a sevgi ve saygıdan dolayı gönül huzuru, tevazu, yalvarma, aciz ve zayıf görünme vardır. Ellerin içini yüzüne doğru çevirip kaldırarak Ya Rabbi! Ya rabbi! Diye dua edersin kim böyle yapmazsa onun namazı şöyle böyledir.” Diğer tahric: Müsned: 16868 Tirmîzî: İbn’ül Mübarek’den başkası bu hadisin sonunda şöyle demişlerdir: “Her kim bu şekilde yapmazsa o namaz noksandır.” Tirmîzî: Muhammed b. İsmail’den işittim dedi ki: Şu’be bu hadisi Abdurabbih b. Saîd’den rivâyet eder ve bazı yerlerde hata etmiştir. Mesela Enes b. ebî Enes’den diyor halbuki o, Imrân b. Imrân b. ebî Enes’tir. Abdullah b. el Hâris’den diyor halbuki o Abdullah b. Nafi’ b. el Amya’nın Rabia b. Hâris’den rivâyetidir. Aynı şekilde Şu’be, Abdullah b. Hâris’den, Muttalib’den ve Peygamber (s.a.v.)’den diyor oysa o Rabia b. Hâris b. Abdulmuttalib, Fadl b. Abbâs ve Peygamber (s.a.v.)’den olacaktır. Muhammed diyor ki: Leys b. Sa’d’ın hadisi Şu’be’nin hadisinden daha sahihtir
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>385</td></tr><tr><td>Arabic No</td><td>385</td></tr><tr><td>Reference</td><td>Book 2 Hadith 237</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
فضل بن عباس رضی الله عنہما کہتے ہیں کہ رسول اللہ صلی اللہ علیہ وسلم نے فرمایا: ”نماز دو دو رکعت ہے اور ہر دو رکعت کے بعد تشہد ہے، نماز خشوع و خضوع، مسکنت اور گریہ وزاری کا اظہار ہے، اور تم اپنے دونوں ہاتھ اٹھاؤ۔ یعنی تم اپنے دونوں ہاتھ اپنے رب کے سامنے اٹھاؤ اس حال میں کہ ہتھیلیاں تمہارے منہ کی طرف ہوں اور کہہ: اے رب! اے رب! اور جس نے ایسا نہیں کیا وہ ایسا ایسا ہے“۔ امام ترمذی کہتے ہیں: ۱- ابن مبارک کے علاوہ اور لوگوں نے اس حدیث میں «من لم يفعل ذلك فهي خداج» ”جس نے ایسا نہیں کیا اس کی نماز ناقص ہے“ کہا ہے، ۲- میں نے محمد بن اسماعیل بخاری کو یہ کہتے ہوئے سنا کہ شعبہ نے یہ حدیث عبدربہ بن سعید سے روایت کی ہے اور ان سے کئی مقامات پر غلطیاں ہوئی ہیں: ایک تو یہ کہ انہوں نے انس بن ابی انس سے روایت کی حالانکہ وہ عمران بن ابی انس ہیں، دوسرے یہ کہ انہوں نے «عن عبدالله بن حارث» کہا ہے حالانکہ وہ «عبدالله بن نافع بن العمياء عن ربيعة بن الحارث» ہے، تیسرے یہ کہ شعبہ نے «عن عبدالله بن الحارث عن المطلب عن النبي صلى الله عليه وسلم» کہا ہے حالانکہ صحیح «عن ربيعة بن الحارث بن عبدالمطلب عن الفضل بن عباس عن النبي صلى الله عليه وسلم» ہے۔ محمد بن اسماعیل ( بخاری ) کہتے ہیں: لیث بن سعد کی حدیث صحیح ہے یعنی شعبہ کی حدیث سے زیادہ صحیح ہے ( ورنہ اصلاً تو ضعیف ہی ہے ) ۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>385</td></tr><tr><td>Arabic No</td><td>385</td></tr><tr><td>Reference</td><td>Book 2 Hadith 237</td></tr></tbody></table></div>