## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا قُتَيْبَةُ، حَدَّثَنَا اللَّيْثُ، عَنْ نَافِعٍ، عَنِ ابْنِ عُمَرَ، قَالَ قَطَعَ رَسُولُ اللَّهِ صلى الله عليه وسلم فِي مِجَنٍّ قِيمَتُهُ ثَلاَثَةُ دَرَاهِمَ ‏.‏ قَالَ وَفِي الْبَابِ عَنْ سَعْدٍ وَعَبْدِ اللَّهِ بْنِ عَمْرٍو وَابْنِ عَبَّاسٍ وَأَبِي هُرَيْرَةَ وَأَيْمَنَ ‏.‏ قَالَ أَبُو عِيسَى حَدِيثُ ابْنِ عُمَرَ حَدِيثٌ حَسَنٌ صَحِيحٌ ‏.‏ وَالْعَمَلُ عَلَى هَذَا عِنْدَ بَعْضِ أَهْلِ الْعِلْمِ مِنْ أَصْحَابِ النَّبِيِّ صلى الله عليه وسلم مِنْهُمْ أَبُو بَكْرٍ الصِّدِّيقُ قَطَعَ فِي خَمْسَةِ دَرَاهِمَ ‏.‏ وَرُوِيَ عَنْ عُثْمَانَ وَعَلِيٍّ أَنَّهُمَا قَطَعَا فِي رُبْعِ دِينَارٍ ‏.‏ وَرُوِيَ عَنْ أَبِي هُرَيْرَةَ وَأَبِي سَعِيدٍ أَنَّهُمَا قَالاَ تُقْطَعُ الْيَدُ فِي خَمْسَةِ دَرَاهِمَ ‏.‏ وَالْعَمَلُ عَلَى هَذَا عِنْدَ بَعْضِ فُقَهَاءِ التَّابِعِينَ وَهُوَ قَوْلُ مَالِكِ بْنِ أَنَسٍ وَالشَّافِعِيِّ وَأَحْمَدَ وَإِسْحَاقَ رَأَوُا الْقَطْعَ فِي رُبْعِ دِينَارٍ فَصَاعِدًا ‏.‏ وَقَدْ رُوِيَ عَنِ ابْنِ مَسْعُودٍ أَنَّهُ قَالَ لاَ قَطْعَ إِلاَّ فِي دِينَارٍ أَوْ عَشَرَةِ دَرَاهِمَ ‏.‏ وَهُوَ حَدِيثٌ مُرْسَلٌ رَوَاهُ الْقَاسِمُ بْنُ عَبْدِ الرَّحْمَنِ عَنِ ابْنِ مَسْعُودٍ وَالْقَاسِمُ لَمْ يَسْمَعْ مِنِ ابْنِ مَسْعُودٍ ‏.‏ وَالْعَمَلُ عَلَى هَذَا عِنْدَ بَعْضِ أَهْلِ الْعِلْمِ وَهُوَ قَوْلُ سُفْيَانَ الثَّوْرِيِّ وَأَهْلِ الْكُوفَةِ قَالُوا لاَ قَطْعَ فِي أَقَلَّ مِنْ عَشَرَةِ دَرَاهِمَ ‏.‏ وَرُوِيَ عَنْ عَلِيٍّ أَنَّهُ قَالَ لاَ قَطْعَ فِي أَقَلَّ مِنْ عَشَرَةِ دَرَاهِمَ ‏.‏ وَلَيْسَ إِسْنَادُهُ بِمُتَّصِلٍ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1446</td></tr><tr><td>Arabic No</td><td>1446</td></tr><tr><td>Reference</td><td>Book 17 Hadith 29</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
১৪৪৬। ইবনু উমার (রাঃ) হতে বর্ণিত আছে, তিনি বলেন, একটি ঢাল চুরির দায়ে রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম (চোরের) হাত কাটার হুকুম দেন, যার মূল্য ছিল তিন দিরহাম। সহীহ, ইবনু মা-জাহ (২৫৮৪), নাসা-ঈ সা’দ, আবদুল্লাহ ইবনু আমর, ইবনু আব্বাস, আবূ হুরাইরা ও আইমান (রাঃ) হতেও এ অনুচ্ছেদে হাদীস বর্ণিত আছে। ইবনু উমার (রাঃ) হতে বর্ণিত হাদীসটিকে আবূ ঈসা হাসান সহীহ বলেছেন। এ হাদীস মোতাবিক নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লামের একদল অভিজ্ঞ সাহাবী আমল করেছেন। তাদের মধ্যে আবূ বাকর সিদীক (রাঃ) অন্তর্ভুক্ত। তিনি পাঁচ দিরহাম পরিমাণ চুরির দায়ে চোরের হাত কেটেছেন। উসমান ও আলী (রাঃ) সম্বন্ধে বর্ণিত আছে যে, তারা দু’জনেই এক দীনারের এক-চতুর্থাংশ পরিমাণ চুরির দায়ে চোরের হাত কেটেছেন। আবূ হুরাইরা ও আবূ সাঈদ (রাঃ) প্রসঙ্গে বর্ণিত আছে যে, তারা উভয়ে বলেছেন, পাঁচ দিরহাম চুরি করলে হাত কেটে ফেলা বৈধ হবে। একদল ফিকহবিদ তাবিঈ এই বক্তব্য গ্রহণ করেছেন। এই মতটি দিয়েছেন ইমাম মালিক ইবনু আনাস, শাফিঈ, আহমাদ ও ইসহাক। তারা মনে, করেন এক। দীনারের এক-চতুর্থাংশ বা তার চেয়ে বেশি চুরি করলে হাত কাটা বৈধ হবে। ইবনু মাসউদ (রাঃ) সম্পর্কে বর্ণিত আছে, তিনি বলেছেন, “এক দীনার অথবা দশ দিরহাম পরিমাণ চুরি করলেই কেবল হাত কাটা যাবে।” এটি মুরসাল হাদীস। এ হাদীসটি ইবনু মাসউদ (রাঃ)-এর নিকট হতে কাসিম ইবনু আবদুর রাহমান বর্ণনা করেছেন বলে উল্লেখ আছে। অথচ ইবনু মাসউদ (রাঃ)-এর নিকট কাসিম (রাহঃ) কিছুই শুনেননি। এ হাদীস মোতাবিক একদল অভিজ্ঞ আলিম আমূল করেছেন। এই অভিমত দিয়েছেন সুফিয়ান সাওরী ও কূফাবাসীগণ। তারা বলেছেন, দশ দিরহামের কম পরিমাণ চুরিতে হাত কাটা বৈধ হবে না। আলী (রাঃ) হতেও বর্ণিত আছে যে, তিনি বলেছেন, দশ দিরহামের কম পরিমাণ চুরিতে হাত কাটা যাবে না। এর সনদ সূত্র মুত্তাসিল নয়।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1446</td></tr><tr><td>Arabic No</td><td>1446</td></tr><tr><td>Reference</td><td>Book 17 Hadith 29</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated Ibn 'Umar:"The Messenger of Allah (ﷺ) cut the hand for a shield worth three Dirham
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1446</td></tr><tr><td>Arabic No</td><td>1446</td></tr><tr><td>Reference</td><td>Book 17 Hadith 29</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Qutaibah], telah menceritakan kepada kami [Al Laits] dari [Nafi'] dari [Ibnu Umar] ia berkata; Rasulullah shallallahu 'alaihi wasallam memotong tangan dalam pencurian tameng besi senilai tiga dirham. Ia mengatakan; Dalam hal ini ada hadits serupa dari Sa'd, Abdullah bin Amr, Ibnu Abbas, Abu Hurairah dan Aiman. Abu Isa berkata; Hadits Ibnu Umar adalah hadits hasan shahih dan menjadi pedoman amal menurut sebagian ulama dari kalangan sahabat Nabi shallallahu 'alaihi wasallam di antaranya; Abu Bakr Ash Shiddiq memotong tangan dalam pencurian lima dirham, dan diriwayatkan dari Utsman dan Ali bahwa keduanya pernah memotong tangan dalam pencurian seperempat dinar dan diriwayatkan juga dari Abu Hurairah dan Abu Sa'id bahwa keduanya berkata; Tangan boleh dipotong dalam penduciran lima dirham. Hadits ini menjadi pedoman amal menurut sebagian fuqaha tabi'in, ini menjadi pendapat Malik bin Anas, Asy Syafi'i, Ahmad dan Ishaq, mereka membolehkan memotong tangan dalam pencurian seperempat dinar atau lebih. Telah diriwayatkan juga dari Ibnu Mas'ud bahwa ia berkata; Tidak dipotong tangan kecuali mencapai satu dinar atau sepuluh dirham. Ini adalah hadits mursal, Al Qasim bin Abdurrahman meriwayatkannya dari Ibnu Mas'ud padahal Al Qasim tidak mendengar dari Ibnu Mas'ud. Hadits ini menjadi pedoman amal menurut sebagian ulama, ini menjadi pendapat Sufyan Ats Tsauri dan ulama Kufah, mereka berpendapat; Tidak ada potong tangan kurang dari sepuluh dirham dan sanadnya tidak bersambung
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1446</td></tr><tr><td>Arabic No</td><td>1446</td></tr><tr><td>Reference</td><td>Book 17 Hadith 29</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
İbn Ömer (radıyallahü anh)’den rivâyete göre, şöyle demiştir: “Rasûlüllah (sallallahü aleyhi ve sellem), değeri üç dirhem olan bir kalkandan dolayı el kesmiştir.” (Buhârî, Hudûd: 14; Müslim, Hudûd: 1) Bu konuda Sa’d, Abdullah b. Amr, İbn Abbâs, Ebû Hüreyre ve Eymen’den de hadis rivâyet edilmiştir. İbn Ömer hadisi hasen sahihtir. Rasûlüllah (sallallahü aleyhi ve sellem)’in ashabından bazı ilim adamlarının uygulaması bu hadise göredir. Ebû Bekir es Sıddîk beş dirhemde el kesmiştir. Osman ve Ali’nin çeyrek dinarda el kestikleri rivâyet edilmektedir. Ebû Hüreyre ve Ebû Saîd’den rivâyete göre: “Beş dirhemde el kesilir.” Tabiin dönemi fıkıhçılarından bir kısmının uygulaması bu hadise göre olup Mâlik b. Enes, Şâfii, Ahmed ve İshâk bunlardan olup: “Çeyrek dinar ve fazlasından el kesilir” görüşündedirler. İbn Mes’ûd’tan rivâyete göre, şöyle demiştir: “El kesmek ancak bir dinar veya on dirhem değerindeki hırsızlıktan dolayıdır.” Bu hadis Kâsım b. Abdurrahman’ın, İbn Mes’ûd’tan rivâyet ettiği mürsel bir hadistir. Çünkü Kâsım, İbn Mes’ûd’tan hadis işitmemiştir. bazı ilim adamlarının uygulaması bu hadise göre olup Sûfyân es Sevrî ve Küfeliler aynı kanaattedirler ve şöyle derler: “On dirhemin altında el kesme yoktur.” Ali’den rivâyet edildiğine göre “On dirhemden aşağı miktarda el kesilmez” hadisinin senedi muttasıl değildir
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1446</td></tr><tr><td>Arabic No</td><td>1446</td></tr><tr><td>Reference</td><td>Book 17 Hadith 29</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
عبداللہ بن عمر رضی الله عنہما کہتے ہیں کہ رسول اللہ صلی اللہ علیہ وسلم نے ایک ڈھال کی چوری پر ہاتھ کاٹا جس کی قیمت تین درہم ۱؎ تھی۔ امام ترمذی کہتے ہیں: ۱- ابن عمر رضی الله عنہما کی حدیث حسن صحیح ہے، ۲- اس باب میں سعد، عبداللہ بن عمرو، ابن عباس، ابوہریرہ اور ایمن رضی الله عنہم سے بھی احادیث آئی ہیں، ۳- صحابہ میں سے بعض اہل علم کا اسی پر عمل ہے، ان میں ابوبکر رضی الله عنہ بھی شامل ہیں، انہوں نے پانچ درہم کی چوری پر ہاتھ کاٹا، ۴- عثمان اور علی رضی الله عنہما سے مروی ہے کہ ان لوگوں نے چوتھائی دینار کی چوری پر ہاتھ کاٹا، ۵- ابوہریرہ اور ابو سعید خدری رضی الله عنہما کہتے ہیں کہ پانچ درہم کی چوری پر ہاتھ کاٹا جائے گا، ۶- بعض فقہائے تابعین کا اسی پر عمل ہے، مالک بن انس، شافعی، احمد، اسحاق بن راہویہ کا یہی قول ہے، یہ لوگ کہتے ہیں: چوتھائی دینار اور اس سے زیادہ کی چوری پر ہاتھ کاٹا جائے گا، ۷- اور ابن مسعود رضی الله عنہ کہتے ہیں کہ ایک دینار یا دس درہم کی چوری پر ہی ہاتھ کاٹا جائے گا، لیکن یہ مرسل ( یعنی منقطع ) حدیث ہے اسے قاسم بن عبدالرحمٰن نے ابن مسعود رضی الله عنہ سے روایت کیا ہے، حالانکہ قاسم نے ابن مسعود سے نہیں سنا ہے، بعض اہل علم کا اسی پر عمل ہے، چنانچہ سفیان ثوری اور اہل کوفہ کا یہی قول ہے، یہ لوگ کہتے ہیں: دس درہم سے کم کی چوری پر ہاتھ نہ کاٹا جائے، ۸- علی رضی الله عنہ کہتے ہیں کہ دس درہم سے کم کی چوری پر ہاتھ نہیں کاٹا جائے گا، لیکن اس کی سند متصل نہیں ہے۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1446</td></tr><tr><td>Arabic No</td><td>1446</td></tr><tr><td>Reference</td><td>Book 17 Hadith 29</td></tr></tbody></table></div>