## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا أَحْمَدُ بْنُ مَنِيعٍ، قَالَ حَدَّثَنَا هُشَيْمٌ، قَالَ أَخْبَرَنَا حُصَيْنٌ، عَنْ هِلاَلِ بْنِ يِسَافٍ، عَنْ عَبْدِ اللَّهِ بْنِ ظَالِمٍ الْمَازِنِيِّ، عَنْ سَعِيدِ بْنِ زَيْدِ بْنِ عَمْرِو بْنِ نُفَيْلٍ، أَنَّهُ قَالَ أَشْهَدُ عَلَى التِّسْعَةِ أَنَّهُمْ فِي الْجَنَّةِ وَلَوْ شَهِدْتُ عَلَى الْعَاشِرِ لَمْ آثَمْ ‏.‏ قِيلَ وَكَيْفَ ذَلِكَ قَالَ كُنَّا مَعَ رَسُولِ اللَّهِ صلى الله عليه وسلم بِحِرَاءَ فَقَالَ ‏ "‏ اثْبُتْ حِرَاءُ فَإِنَّهُ لَيْسَ عَلَيْكَ إِلاَّ نَبِيٌّ أَوْ صِدِّيقٌ أَوْ شَهِيدٌ ‏"‏ ‏.‏ قِيلَ وَمَنْ هُمْ قَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم وَأَبُو بَكْرٍ وَعُمَرُ وَعُثْمَانُ وَعَلِيٌّ وَطَلْحَةُ وَالزُّبَيْرُ وَسَعْدٌ وَعَبْدُ الرَّحْمَنِ بْنُ عَوْفٍ ‏.‏ قِيلَ فَمَنِ الْعَاشِرُ قَالَ أَنَا ‏.‏ قَالَ أَبُو عِيسَى هَذَا حَدِيثٌ حَسَنٌ صَحِيحٌ وَقَدْ رُوِيَ مِنْ غَيْرِ وَجْهٍ عَنْ سَعِيدِ بْنِ زَيْدٍ عَنِ النَّبِيِّ صلى الله عليه وسلم ‏.‏ حَدَّثَنَا أَحْمَدُ بْنُ مَنِيعٍ، قَالَ حَدَّثَنَا الْحَجَّاجُ بْنُ مُحَمَّدٍ، قَالَ حَدَّثَنِي شُعْبَةُ، عَنِ الْحُرِّ بْنِ الصَّبَّاحِ، عَنْ عَبْدِ الرَّحْمَنِ بْنِ الأَخْنَسِ، عَنْ سَعِيدِ بْنِ زَيْدٍ، عَنِ النَّبِيِّ صلى الله عليه وسلم نَحْوَهُ بِمَعْنَاهُ ‏.‏ هَذَا حَدِيثٌ حَسَنٌ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3757</td></tr><tr><td>Arabic No</td><td>3757</td></tr><tr><td>Reference</td><td>Book 49 Hadith 154</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
৩৭৫৭। সাঈদ ইবনু যাইদ ইবনু আমর ইবনু নুফাইল (রাযিঃ) হতে বর্ণিত আছে, তিনি বলেন, নয়জন লোক প্রসঙ্গে আমি সাক্ষ্য দিচ্ছি যে, তারা জান্নাতী। যদি আমি দশম ব্যক্তি প্রসঙ্গেও সাক্ষ্য দেই তবে তাতেও আমি পাপী হব না। প্রশ্ন করা হল, তা কিভাবে? তিনি বললেন, রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর সাথে আমরা হেরা পর্বতের উপর অবস্থানরত ছিলাম। (হেরা কেঁপে উঠলে) তিনি বললেনঃ হেরা শান্ত হও। অবশ্যই তোমার উপরে একজন নবী কিংবা একজন সিদ্দীক (পরম সত্যবাদী) অথবা একজন শহীদ আছেন। বলা হল, তারা কারা তিনি বললেনঃ রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম, আবূ বকর, উমার, উসমান, আলী, তালহা, যুবাইর, সা’দ ও আবদুর রহমান ইবনু আওফ (রাযিঃ)। তাকে প্রশ্ন করা হল, দশম লোকটি কে? তিনি বললেন, আমি। সহীহঃ (৩৭৪৮) নং হাদীস পূর্বে বর্ণিত হয়েছে। আবূ ঈসা বলেন, এ হাদীসটি হাসান সহীহ। এ হাদীসটি সাঈদ ইবনু যাইদ (রাযিঃ)-এর বরাতে, নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম হতে একাধিক সূত্রে বর্ণিত হয়েছে। আহমাদ ইবনু মানী'-হাজ্জাজ ইবনু মুহাম্মাদ হতে, তিনি শু’বাহ হতে, তিনি তিনি সাঈদ ইবনু যাইদ (রাযিঃ) হতে উক্ত মর্মে নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম হতে একই রকম বর্ণনা করেছেন। এ শেষের সনদের হাদীসটি হাসান।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3757</td></tr><tr><td>Arabic No</td><td>3757</td></tr><tr><td>Reference</td><td>Book 49 Hadith 154</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated 'Abdullah bin Zalim Al-Mazini:that Sa'eed bin Zaid bin 'Amr bin Nufail said: "I bear witness for nine people, that they are in Paradise, and if I were to bear witness for a tenth, I would not be sinful." It was said: "How is that?" He said: "We were with the Messenger of Allah (ﷺ) at (mount) Hira when he said, 'Be firm, Hira! There is not upon you any but a Prophet, or a Siddiq, or a martyr." It was said: "And who were they?" He said: "The Messenger of Allah (ﷺ), Abu Bakr, 'Umar, 'Uthman, 'Ali, Talhah, Az-Zubair, Sa'd, and 'Abdur-Rahman bin 'Awf." It was said: "And who is the tenth?" He said: "Me
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3757</td></tr><tr><td>Arabic No</td><td>3757</td></tr><tr><td>Reference</td><td>Book 49 Hadith 154</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Ahmad bin Mani'] telah menceritakan kepada kami [Husyaim] telah mengabarkan kepada kami [Hushain] dari [Hilal bin Yasaf] dari [Abdullah bin Dlalim Al Mazini] dari [Sa'id bin Zaid bin 'Amru bin Nufail] bahwa dia berkata; "Saya bersaksi terhadap sembilan orang yang mereka telah dijamin masuk surga dan sekiranya aku bersaksi terhadap sepuluh orang, maka aku tidak akan berdosa." Dikatakan; "Bagaimana bisa begitu?." Dia menjawab; "Kami pernah bersama Rasulullah shallallahu 'alaihi wasallam di (goa) Hira', lalu beliau bersabda: "Tenanglah wahai (goa) Hira', tidaklah orang yang ada di atasmu melainkan seorang Nabi, shiddiq (jujur) atau orang yang syahid." Dikatakan; "Siapakah mereka?" Dia menjawab; (mereka adalah) Rasulullah shallallahu 'alaihi wasallam, Abu Bakar, Umar, Utsman, Ali, Thalhah, Zubair, Sa'ad dan Abdurrahman bin 'Auf." Dikatakan; "Siapa yang kesepuluh?" Dia menjawab; "Saya." Abu Isa berkata; "Hadits ini adalah hadits hasan shahih." Dan hadits ini telah diriwayatkan pula dari beberapa jalur dari Sa'id bin Zaid dari Nabi shallallahu 'alaihi wasallam." Telah menceritakan kepada kami [Ahmad bin Mani'] telah menceritakan kepada kami [Al Hajjaj bin Muhammad] telah menceritakan kepadaku [Syu'bah] dari [Al Hurr bin Ash Shayyah] dari [Abdurrahman bin Al Akhnas] dari [Sa'id bin Zaid] dari Nabi shallallahu 'alaihi wasallam seperti hadits di atas secara maknanya, dia berkata; "Hadits ini adalah hadits hasan
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3757</td></tr><tr><td>Arabic No</td><td>3757</td></tr><tr><td>Reference</td><td>Book 49 Hadith 154</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Saîd b. Zeyd b. Amr b. Nüfeyl (radıyallahü anh)’dan şöyle dediğini rivâyet edilmiştir: Dokuz kişinin Cennet’te olduklarına şâhidlik ederim, onuncu kişinin de Cennet’te olduğuna şâhidlik etsem günaha girmiş olmam. Bunun üzerine bu nasıl oluyor? Diye soruldu. Saîd b. Zeyd dedi ki: Peygamber (sallallahü aleyhi ve sellem) ile birlikte Hirâ dağında idik. Dağ sallanınca; “Yerinde dur Hirâ! Çünkü senin üzerinde bir peygamber bir sıddîk bir de şehîd vardır” buyurdu. Onlar kimlerdir diye sorulunca, Saîd dedi ki: “Rasûlüllah (sallallahü aleyhi ve sellem), Ebû Bekir, Ömer, Osman, Ali, Talha, Zübeyr, Sa’d, Abdurrahman b. Avf.” Sonra onuncusu kimdir? diye soruldu. Saîd: “Ben” dedi. (Ebû Dâvûd, Sünnet: 27; İbn Mâce, Mukaddime: 17) Bu hadis hasen sahihtir. hadis bir başka şekilde de Saîd b. Zeyd’den rivâyet edilmiştir
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3757</td></tr><tr><td>Arabic No</td><td>3757</td></tr><tr><td>Reference</td><td>Book 49 Hadith 154</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
سعید بن زید بن عمرو بن نفیل رضی الله عنہ کہتے ہیں کہ میں نو اشخاص کے سلسلے میں اس بات کی گواہی دیتا ہوں کہ یہ لوگ جنتی ہیں اور اگر میں دسویں کے سلسلے میں گواہی دوں تو بھی گنہگار نہیں ہوں گا، آپ سے کہا گیا: یہ کیسے ہے؟ ( ذرا اس کی وضاحت کیجئے ) تو انہوں نے کہا: ہم رسول اللہ صلی اللہ علیہ وسلم کے ساتھ حرا پہاڑ پر تھے تو آپ نے فرمایا: ”ٹھہرا رہ اے حرا! تیرے اوپر ایک نبی، یا صدیق، یا شہید ۱؎ کے علاوہ کوئی اور نہیں“، عرض کیا گیا: وہ کون لوگ ہیں جنہیں آپ نے صدیق یا شہید فرمایا ہے؟ ( انہوں نے کہا ) رسول اللہ صلی اللہ علیہ وسلم نے فرمایا: وہ ابوبکر، عمر، عثمان، علی، طلحہ، زبیر، سعد اور عبدالرحمٰن بن عوف ہیں رضی الله عنہم، پوچھا گیا: دسویں شخص کون ہیں؟ تو سعید نے کہا: وہ میں ہوں۔ امام ترمذی کہتے ہیں: ۱- یہ حدیث حسن صحیح ہے، ۲- یہ حدیث کئی سندوں سے سعید بن زید رضی الله عنہ کے واسطہ سے نبی اکرم صلی اللہ علیہ وسلم سے آئی ہے۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3757</td></tr><tr><td>Arabic No</td><td>3757</td></tr><tr><td>Reference</td><td>Book 49 Hadith 154</td></tr></tbody></table></div>