## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا قُتَيْبَةُ بْنُ سَعِيدٍ، قَالَ حَدَّثَنَا مُحَمَّدُ بْنُ سُلَيْمَانَ الأَصْبَهَانِيُّ، عَنْ يَحْيَى بْنِ عُبَيْدٍ، عَنْ عَطَاءِ بْنِ أَبِي رَبَاحٍ، عَنْ عُمَرَ بْنِ أَبِي سَلَمَةَ، رَبِيبِ النَّبِيِّ صلى الله عليه وسلم قَالَ نَزَلَتْ هَذِهِ الآيَةُ عَلَى النَّبِيِّ صلى الله عليه وسلمَّ ‏:‏ ‏(‏ إنمَا يُرِيدُ اللَّهُ لِيُذْهِبَ عَنْكُمُ الرِّجْسَ أَهْلَ الْبَيْتِ وَيُطَهِّرَكُمْ تَطْهِيرًا ‏)‏ فِي بَيْتِ أُمِّ سَلَمَةَ فَدَعَا النَّبِيُّ صلى الله عليه وسلم فَاطِمَةَ وَحَسَنًا وَحُسَيْنًا فَجَلَّلَهُمْ بِكِسَاءٍ وَعَلِيٌّ خَلْفَ ظَهْرِهِ فَجَلَّلَهُ بِكِسَاءٍ ثُمَّ قَالَ ‏"‏ اللَّهُمَّ هَؤُلاَءِ أَهْلُ بَيْتِي فَأَذْهِبْ عَنْهُمُ الرِّجْسَ وَطَهِّرْهُمْ تَطْهِيرًا ‏"‏ ‏.‏ قَالَتْ أُمُّ سَلَمَةَ وَأَنَا مَعَهُمْ يَا نَبِيَّ اللَّهِ قَالَ ‏"‏ أَنْتِ عَلَى مَكَانِكِ وَأَنْتِ إِلَيَّ خَيْرٍ ‏"‏ ‏. وَفِي الْبَابِ عَنْ أُمِّ سَلَمَةَ وَمَعْقِلِ بْنِ يَسَارٍ وَأَبِي الْحَمْرَاءِ وَأَنَسٍ بْنِ مَالِكٍ ‏.‏ وَهَذَا حَدِيثٌ غَرِيبٌ مِنْ هَذَا الْوَجْهِ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3787</td></tr><tr><td>Arabic No</td><td>3787</td></tr><tr><td>Reference</td><td>Book 49 Hadith 186</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
৩৭৮৭। নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর পোষ্য উমার ইবনু আবী সালামাহ (রাযিঃ) হতে বর্ণিত আছে, তিনি বলেন, উম্মু সালামাহ্ (রাযিঃ)-এর ঘরে এ আয়াত নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর উপর অবতীর্ণ হয় (অনুবাদ) “হে নবীর পরিবার। আল্লাহ তা'আলা তো চান তোমাদের হতে অপবিত্রতা দূর করতে এবং তোমাদেরকে সম্পূর্ণভাবে পবিত্র করতে”– (সূরা আহযাব ৩৩)। সে সময় নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম ফাতিমাহ, হাসান ও হুসাইন (রাযিঃ)-কে ডাকেন এবং তাদেরকে একখানা চাদরে আবৃত করেন। তার পেছনে আলী (রাযিঃ) ছিলেন। তিনি তাকেও চাদরে ঢেকে নেন, তারপর বললেনঃ “হে আল্লাহ! এরা আমার আহলে বাইত। অতএব তুমি তাদের হতে অপবিত্রতা অপসারণ করে দাও এবং তাদেরকে উত্তমভাবে পবিত্র কর”। সে সময় উম্মু সালামাহ্ (রাযিঃ) বললেন, হে আল্লাহর রাসূল! আমিও তাদের অন্তর্ভুক্ত কি? তিনি বললেনঃ তুমি স্বস্থানে আছ এবং তুমি কল্যাণের মাঝেই আছ। সহীহঃ ৩২০৫ নং হাদীস পূর্বে বর্ণিত হয়েছে। আবূ ঈসা বলেন, এ অনুচ্ছেদে উম্মু সালামাহ, মাকিল ইবনু ইয়াসার, আবূল হামরা ও আনাস ইবনু মালিক (রাযিঃ) কর্তৃকও হাদীস বর্ণিত আছে। এ হাদীসটি উপর্যুক্ত সনদে হাসান গারীব।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3787</td></tr><tr><td>Arabic No</td><td>3787</td></tr><tr><td>Reference</td><td>Book 49 Hadith 186</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated 'Umar bin Abi Salamah - the step-son of the Prophet (ﷺ):"When these Ayat were revealed to the Prophet (ﷺ): 'Allah only wishes to remove the Rijs from you, O members of the family, and to purify you with a thorough purification...' (33:33) in the home of Umm Salamah, he called for Fatimah, Hasan, Husain, and wrapped them in a cloak, and 'Ali was behind him, so he wrapped him in the cloak, then he said: 'O Allah! These are the people of my house, so remove the Rijs from them, and purify them with a thorough purification.' So Umm Salamah said: 'And am I with them O Messenger of Allah?' He said: 'You are in your place, and you are more virtuous to me
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3787</td></tr><tr><td>Arabic No</td><td>3787</td></tr><tr><td>Reference</td><td>Book 49 Hadith 186</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Qutaibah bin Sa'id] telah menceritakan kepada kami [Muhammad bin Sulaiman Al Ashbahani] dari [Yahya bin 'Ubaid] dari ['Atha' bin Abu Rabah] dari [Umar bin Abu Salamah] anak tiri Nabi shallallahu 'alaihi wasallam dia berkata; ayat ini yaitu; Sesungguhnya Allah bermaksud hendak menghilangkan dosa dari kamu, Hai ahlul bait dan membersihkan kamu sebersih-bersihnya QS Al Ahzab; 33 turun atas Nabi shallallahu 'alaihi wasallam di dalam rumah Ummu Salamah, lantas Nabi shallallahu 'alaihi wasallam memanggil Fathimah, Hasan dan Husain, lalu beliau menyelimuti mereka dengan selendang, sedangkan Ali berada di belakang beliau lalu beliau juga menyelimuti dengan selendang, kemudian beliau bersabda: "Ya Allah, mereka semua adalah ahli baitku, maka hilangkanlah dosa dari diri mereka dan sucikanlah mereka sebersih-bersihnya." Ummu Salamah berkata; "Saya juga bersama mereka wahai Nabi Allah?" beliau bersabda: "kamu tetap berada di posisimu, dan akan tetap mendapatkan suatu kebaikan." Perawi (Abu Isa) berkata; "Dan dalam bab ini, ada juga riwayat dari Ummu Salamah, Ma'qil bin Yasar, Abu Hamra' dan Anas." Ia melanjutkan; "Hadits ini derajatnya gharib melalui jalur ini
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3787</td></tr><tr><td>Arabic No</td><td>3787</td></tr><tr><td>Reference</td><td>Book 49 Hadith 186</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Nebi (s.a.v)’in üvey oğlu Ömer b. ebî Seleme (r.a.)’den rivâyete göre, şöyle demiştir: Ahzab sûresi: 33. ayeti; “… Ey Nebinin ev halkı, Allah sizin üzerinizden her türlü çirkinliği ve kirliliği gidermek ve sizi tertemiz yapmak istiyor.” Ümmü Seleme’nin evinde inmişti. Bunun üzerine Rasûlullah (s.a.v.), Fatıma, Hasan ve Hüseyin’i çağırdı onları bir örtü ile örttü. Ali de Rasûlü Ekrem’in arkasında bulunuyordu onu da bir başka örtü ile örttü ve şöyle duâ etti: “Allah’ım bunlar benim ehli beytimdir. Bunlardan pislik ve kötülükleri gider ve onları tertemiz eyle.” Ümmü Seleme: “Ey Allah’ın Nebii ben de onlardan mıyım?” dedi. Rasûlullah (s.a.v.): “Sen yerinde dur! Sen bana hayırlı kimselerdensin” buyurdu. Tirmizî rivâyet etmiştir. Tirmizî: Bu konuda Ümmü Seleme, Ma’kıl b. Yesâr, Ebû’l Hamra ve Enes’den de hadis rivâyet edilmiştir. Tirmizî: Bu hadis bu şekliyle garibtir
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3787</td></tr><tr><td>Arabic No</td><td>3787</td></tr><tr><td>Reference</td><td>Book 49 Hadith 186</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
نبی اکرم صلی اللہ علیہ وسلم کے «ربيب» (پروردہ) عمر بن ابی سلمہ رضی الله عنہ کہتے ہیں کہ جب آیت کریمہ «إنما يريد الله ليذهب عنكم الرجس أهل البيت ويطهركم تطهيرا» ”اے اہل بیت النبوۃ! اللہ چاہتا ہے کہ تم سے ( کفر و شرک ) کی گندگی دور کر دے، اور تمہاری خوب تطہیر کر دے“ ( الاحزاب: ۳۳ ) ، نبی اکرم صلی اللہ علیہ وسلم پر ام سلمہ رضی الله عنہا کے گھر میں اتریں تو آپ نے فاطمہ اور حسن و حسین رضی الله عنہم کو بلایا اور آپ نے انہیں ایک چادر میں ڈھانپ لیا اور علی رضی الله عنہ آپ کی پشت مبارک کے پیچھے تھے تو آپ نے انہیں بھی چادر میں چھپا لیا، پھر فرمایا: «اللهم هؤلاء أهل بيتي فأذهب عنهم الرجس وطهرهم تطهيرا» ”اے اللہ! یہ میرے اہل بیت ہیں تو ان کی ناپاکی کو دور فرما دے اور انہیں اچھی طرح پاک کر دے“، ام سلمہ نے عرض کیا: اللہ کے نبی! میں بھی انہیں کے ساتھ ہوں، آپ نے فرمایا: ”تو اپنی جگہ پر رہ اور تو بھی نیکی پر ہے“۔ امام ترمذی کہتے ہیں: ۱- یہ حدیث اس سند سے غریب ہے، ۲- اس باب میں ام سلمہ، معقل بن یسار، ابوحمراء اور انس رضی الله عنہم سے احادیث آئی ہیں۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3787</td></tr><tr><td>Arabic No</td><td>3787</td></tr><tr><td>Reference</td><td>Book 49 Hadith 186</td></tr></tbody></table></div>