## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا هَنَّادٌ، حَدَّثَنَا أَبُو الأَحْوَصِ، عَنْ بَيَانِ بْنِ بِشْرٍ، عَنْ قَيْسِ بْنِ أَبِي حَازِمٍ، عَنْ أَبِي هُرَيْرَةَ، قَالَ سَمِعْتُ رَسُولَ اللَّهِ صلى الله عليه وسلم يَقُولُ ‏ "‏ لأَنْ يَغْدُوَ أَحَدُكُمْ فَيَحْتَطِبَ عَلَى ظَهْرِهِ فَيَتَصَدَّقَ مِنْهُ فَيَسْتَغْنِيَ بِهِ عَنِ النَّاسِ خَيْرٌ لَهُ مِنْ أَنْ يَسْأَلَ رَجُلاً أَعْطَاهُ أَوْ مَنَعَهُ ذَلِكَ فَإِنَّ الْيَدَ الْعُلْيَا أَفْضَلُ مِنَ الْيَدِ السُّفْلَى وَابْدَأْ بِمَنْ تَعُولُ ‏"‏ ‏.‏ قَالَ وَفِي الْبَابِ عَنْ حَكِيمِ بْنِ حِزَامٍ وَأَبِي سَعِيدٍ الْخُدْرِيِّ وَالزُّبَيْرِ بْنِ الْعَوَّامِ وَعَطِيَّةَ السَّعْدِيِّ وَعَبْدِ اللَّهِ بْنِ مَسْعُودٍ وَمَسْعُودِ بْنِ عَمْرٍو وَابْنِ عَبَّاسٍ وَثَوْبَانَ وَزِيَادِ بْنِ الْحَارِثِ الصُّدَائِيِّ وَأَنَسٍ وَحُبْشِيِّ بْنِ جُنَادَةَ وَقَبِيصَةَ بْنِ مُخَارِقٍ وَسَمُرَةَ وَابْنِ عُمَرَ ‏.‏ قَالَ أَبُو عِيسَى حَدِيثُ أَبِي هُرَيْرَةَ حَدِيثٌ حَسَنٌ صَحِيحٌ غَرِيبٌ يُسْتَغْرَبُ مِنْ حَدِيثِ بَيَانٍ عَنْ قَيْسٍ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih Bukhari And Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>680</td></tr><tr><td>Arabic No</td><td>680</td></tr><tr><td>Reference</td><td>Book 7 Hadith 64</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
৬৮০। আবু হুরাইরা (রাঃ) হতে বর্ণিত আছে, তিনি বলেন, রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লামকে আমি বলতে শুনেছিঃ তোমাদের মাঝে কোন লোক সকালে গিয়ে কাঠ সংগ্রহ করে তা পিঠে করে বহন করে এনে তা হতে প্রাপ্ত উপার্জন হতে সে দান-খায়রাত করল এবং লোকদের নিকটে হাত পাতা হতে বিরত থাকল। তার জন্য এটা অনেক উত্তম অন্যের নিকটে সাহায্য প্রার্থনা করা হতে। আর অন্য লোকের নিকটে চাইলে সে তাকে দিতেও পারে আবার নাও দিতে পারে। কেননা, নিচের হাত হতে উপরের হাত (দান গ্রহণকারীর চেয়ে প্রদানকারী) উত্তম। নিজের প্রতিপাল্যদের নিকট হতে (অর্থ ব্যয় ও দান-খয়রাত) শুরু কর। — সহীহ, ইরওয়া (৮৩৪), মুসলিম হাকিম, ইবনু হিজাম, আবূ সাঈদ আল খুদরী, জুবাইর ইবনুল আওয়াম, আতিয়া আস-সা’দী, আবদুল্লাহ ইবনু মাসউদ, মাসউদ ইবনু আমর, ইবনু আব্বাস, সাওবান, যিয়াদ ইবনু হারিস আস-সুদাঈ, আনাস, হুবশী ইবনু জুনাদা, কাবীসা ইবনু মুখারিক, সামুরা ও ইবনু উমার (রাঃ) হতেও এ অনুচ্ছেদে হাদীস বর্ণিত আছে। আবু ঈসা এ হাদীসটিকে হাসান, সহীহ গারীব বলেছেন। কায়িস (রাহঃ) হতে বায়ান (রাহঃ)-এর বর্ণিত হাদীসটিকে গারীব হাদীস বলে গণ্য করা হয়েছে।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih Bukhari And Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>680</td></tr><tr><td>Arabic No</td><td>680</td></tr><tr><td>Reference</td><td>Book 7 Hadith 64</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Abu Hurairah narrated that he heard :the Messenger of Allah saying: "For one of you to go out early to gather firewood and carry it on his back so that he can give charity from it and be free of need from the people, is better for him than to ask a man who may give that to him or refuse. Indeed the upper hand (giving) is more virtuous than the lower hand (receiving), and begin with (those who are) your dependants
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih Bukhari And Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>680</td></tr><tr><td>Arabic No</td><td>680</td></tr><tr><td>Reference</td><td>Book 7 Hadith 64</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Hannad] telah menceritakan kepada kami [Abu Al Ahwash] dari [Bayan bin Bisyr] dari [Qais bin Abu Hazim] dari [Abu Hurairah] dia berkata, saya mendengar Rasulullah Shallallaahu 'alaihi wasallam bersabda: " Sungguh jika seseorang diantara kalian berangkat pagi hari untuk mencari kayu bakar dan dipikul diatas punggungnya, yang dengannya dia bisa bersedekah dan mencukupi kebutuhannya dari manusia, hal itu lebih baik daripada meminta-minta kepada orang lain sama saja apakah dia memberi kepadanya atau tidak, karena sesungguhnya tangan yang diatas lebih baik dari pada tangan yang dibawah dan mulailah memberi dari orang yang menjadi tanggunganmu". (perawi) berkata, dalam bab ini (ada juga riwayat -pent) dari Hakim bin Hizam, Abu Sa'id, Zubair bin Awwam, 'Athiyyah Assa'di, Abdullah bin Mas'ud, Mas'ud bin Amru, Ibnu Abbas, Tsauban, Ziyad bin Harits Ash Shuda'i, Anas, Hubsyi bin Junadah, Qabishah bin Mukhariq, Samrah dan Ibnu Umar. Abu 'Isa berkata, Hadits Abu Hurairah merupakan hadits hasan shahih gharib yang digharibkan dari hadits Bayan bin Qais
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih Bukhari And Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>680</td></tr><tr><td>Arabic No</td><td>680</td></tr><tr><td>Reference</td><td>Book 7 Hadith 64</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ebû Hureyre (r.a.)’den rivâyet edilmiştir. Demiştir ki: Rasûlullah (s.a.v.)’den işittim şöyle diyordu: “Sizden birinizin sabahleyin ormana giderek sırtında odun getirmesi ve onun parasını harcaması ve insanlara muhtaçlıktan kurtulması, versin vermesin bir kimseden istemekten daha hayırlıdır. Çünkü yüksekteki veren el alttaki alan elden daha hayırlıdır. Harcamaya, geçimini üstlendiğin kimselerden başla.” Diğer tahric: Ebû Dâvûd, Zekat; Müslim, Zekat Tirmîzî: Bu konuda Hakîm b. Hızâm, Ebû Saîd el Hudrî, Zübeyr b. Avvam, Atıyye es Sa’dî, Abdullah b. Mes’ûd, Mes’ûd b. Amr, İbn Abbâs, Sevbân, Ziyâd b. Hâris es Sudaî, Enes, Hubşî b. Cünade, Kabîsa b. Muhârik, Semure ve İbn Ömer’den de hadis rivâyet edilmiştir. Tirmîzî: Ebû Hureyre hadisi hasen sahih garibtir. Bu hadisin garib oluşu Beyan’ın, Kays’tan rivâyeti sebebiyledir
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih Bukhari And Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>680</td></tr><tr><td>Arabic No</td><td>680</td></tr><tr><td>Reference</td><td>Book 7 Hadith 64</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ابوہریرہ رضی الله عنہ کہتے ہیں کہ میں نے رسول اللہ صلی اللہ علیہ وسلم کو فرماتے سنا: ”تم میں سے کوئی شخص صبح سویرے جائے اور لکڑیوں کا گٹھر اپنی پیٹھ پر رکھ کر لائے اور اس میں سے ( یعنی اس کی قیمت میں سے ) صدقہ کرے اور اس طرح لوگوں سے بے نیاز رہے ( یعنی ان سے نہ مانگے ) اس کے لیے اس بات سے بہتر ہے کہ وہ کسی سے مانگے، وہ اسے دے یا نہ دے ۱؎ کیونکہ اوپر والا ہاتھ نیچے والے ہاتھ سے افضل ہے ۲؎، اور پہلے اسے دو جس کی تم خود کفالت کرتے ہو“۔ امام ترمذی کہتے ہیں: ۱- ابوہریرہ کی حدیث حسن صحیح غریب ہے، ۲- وہ بیان کی حدیث سے جسے انہوں نے قیس سے روایت کی ہے غریب جانی جاتی ہے، ۳- اس باب میں حکیم بن حزام، ابو سعید خدری، زبیر بن عوام، عطیہ سعدی، عبداللہ بن مسعود، مسعود بن عمرو، ابن عباس، ثوبان، زیاد بن حارث صدائی، انس، حبشی بن جنادہ، قبیصہ بن مخارق، سمرہ اور ابن عمر رضی الله عنہم سے بھی احادیث آئی ہیں۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Ahmad Muhammad Shakir</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Sahih</td><td>Bashar Awad Maarouf</td></tr><tr><td>Sahih Bukhari And Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>680</td></tr><tr><td>Arabic No</td><td>680</td></tr><tr><td>Reference</td><td>Book 7 Hadith 64</td></tr></tbody></table></div>