## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنِي زِيَادٌ، عَنْ مَالِكٍ، عَنْ يَزِيدَ بْنِ عَبْدِ اللَّهِ بْنِ الْهَادِ، عَنْ مُحَمَّدِ بْنِ إِبْرَاهِيمَ بْنِ الْحَارِثِ التَّيْمِيِّ، عَنْ أَبِي سَلَمَةَ بْنِ عَبْدِ الرَّحْمَنِ، عَنْ أَبِي سَعِيدٍ الْخُدْرِيِّ، أَنَّهُ قَالَ كَانَ رَسُولُ اللَّهِ صلى الله عليه وسلم يَعْتَكِفُ الْعَشْرَ الْوُسُطَ مِنْ رَمَضَانَ فَاعْتَكَفَ عَامًا حَتَّى إِذَا كَانَ لَيْلَةَ إِحْدَى وَعِشْرِينَ وَهِيَ اللَّيْلَةُ الَّتِي يَخْرُجُ فِيهَا مِنْ صُبْحِهَا مِنَ اعْتِكَافِهِ قَالَ ‏ "‏ مَنِ اعْتَكَفَ مَعِي فَلْيَعْتَكِفِ الْعَشْرَ الأَوَاخِرَ وَقَدْ رَأَيْتُ هَذِهِ اللَّيْلَةَ ثُمَّ أُنْسِيتُهَا وَقَدْ رَأَيْتُنِي أَسْجُدُ مِنْ صُبْحِهَا فِي مَاءٍ وَطِينٍ فَالْتَمِسُوهَا فِي الْعَشْرِ الأَوَاخِرِ وَالْتَمِسُوهَا فِي كُلِّ وِتْرٍ ‏"‏ ‏.‏ قَالَ أَبُو سَعِيدٍ فَأُمْطِرَتِ السَّمَاءُ تِلْكَ اللَّيْلَةَ وَكَانَ الْمَسْجِدُ عَلَى عَرِيشٍ فَوَكَفَ الْمَسْجِدُ - قَالَ أَبُو سَعِيدٍ - فَأَبْصَرَتْ عَيْنَاىَ رَسُولَ اللَّهِ صلى الله عليه وسلم انْصَرَفَ وَعَلَى جَبْهَتِهِ وَأَنْفِهِ أَثَرُ الْمَاءِ وَالطِّينِ مِنْ صُبْحِ لَيْلَةِ إِحْدَى وَعِشْرِينَ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>697</td></tr><tr><td>Arabic No</td><td>697</td></tr><tr><td>Reference</td><td>Book 19 Hadith 697</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>

</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>697</td></tr><tr><td>Arabic No</td><td>697</td></tr><tr><td>Reference</td><td>Book 19 Hadith 697</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Malik said, "There is no harm in someone who is in itikaf entering into a marriage contract as long as there is no physical relationship. A woman in itikaf may also be betrothed as long as there is no physical relationship. What is haram for someone in itikaf in relation to his womenfolk during the day is haram for him during the night." Yahya said that Ziyad said that Malik said, "It is not halal for a man to have intercourse with his wife while he is in itikaf, nor for him to take pleasure in her by kissing her, or whatever. However, I have not heard anyone disapproving of a man, or woman, in itikaf getting married as long as there is no physical relationship. Marriage is not disapproved of for someone fasting." "There is, however, a distinction between the marriage of someone in itikaf and that of someone who is muhrim, in that some one who is muhrim can eat, drink, visit the sick and attend funerals, but cannot put on perfume, whilst a man or woman in itikaf can put on oil and perfume and groom their hair, but cannot attend funerals or pray over the dead or visit the sick. Thus their situations with regard to marriage are different." "This is the sunna as it has come down to us regarding marriage for those who are muhrim, doing itikaf, or fasting. Yahya related to me from Malik from Yazid ibn Abdullah ibn al- Hadi from Muhammad ibn Ibrahim al-Harith at-Taymi from Abu Salama ibn Abd ar-Rahman that Abu Said al-Khudri said, "The Messenger of Allah, may Allah bless him and grant him peace, used to do itikaf in the middle ten days of Ramadan. One year he was doing itikaf and then, when it came to the night of the twenty-first, which was the night before the morning when he would normally have finished his itikaf, he said, 'Whoever has done i'tikaf with me should continue doing itikaf for the last ten days. I saw a certain night and then I was made to forget it. I saw myself prostrating the following morning in water and clay. Look for it in the last ten days, and look for it on the odd days.' " Abu Said continued, "The sky poured with rain that night and the mosque had a roof (made of palm fronds) and the mosque was soaked. With my own eyes I saw the Messenger of Allah, may Allah bless him and grant him peace, leave with traces of water and clay on his forehead and nose, in the morning after the night of the twenty- first
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>697</td></tr><tr><td>Arabic No</td><td>697</td></tr><tr><td>Reference</td><td>Book 19 Hadith 697</td></tr></tbody></table></div>

## French


<div dir="ltr" lang="fr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ibn Chéhab a rapporté que l'Envoyé d'Allah (salallahou alayhi wa salam) r (Sur lui la grâce et la paix d'Allah) durant sa retraite, se rendait chez lui, au cas ou il avait un besoin à satisfaire». Malek a dit: «Qui est en retraite spirituelle (itikaf) n'a pas à sortir de sa retraite, afin qu'il suive le convoi funèbre de ses parents ou autres». Chapitre V Du mariage durant la retraite spirituelle. Malek a dit: «Rien n'empêche de conclure un mariage durant la retraite spirituelle, à condition qu'il n'y ait pas des rapports charnels; il en est de même pour la femme en retraite, qui peut être demandée en mariage, sans que pour autant il y ait une cohabitation. On interdit au retraité d'avoir des rapports avec sa femme, aussi bien durant la nuit que durant le jour». Et Malek a ajouté: «Il est interdit à un homme en retraite de toucher à sa femme, ni même de l'embrasser. Et je n'ai pas entendu, interdire à une femme et à un homme en retraite de conclure un mariage, tant qu'il n'y ait pas des rapports charnels; à ce moment, il est à interdire. Tout de même, rien n'empêche au jeûneur de conclure un mariage au cours de son jeûne. D'autre part, il y a à faire la distinction entre le mariage conclu par un homme en retraite, et celui qui est fait par un homme en Ihram. Ce dernier peut manger, boire, visiter un malade, assister à des convois funèbres, mais ne se parfume pas. Par contre la femme et l'homme en retraite, (itikaf) peuvent s'oindre, se parfumer, et se peigner les cheveux, mais n'assistent guère aux convois funèbres, ne prient pas sur les morts, et ne rendent pas visite à un malade. Ainsi les conditions du mariage diffèrent de l'un à l'autre, et c'est d'ailleurs ce qui est traditionnellement suivi pour la question du mariage pour celui qui est en état d'Ihram, à celui qui est en itikaf, et finalement au jeûneur. Chapitre VI La nuit de Destin
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>697</td></tr><tr><td>Arabic No</td><td>697</td></tr><tr><td>Reference</td><td>Book 19 Hadith 697</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepadaku Ziyad dari Malik dari [Yazid bin Abdullah bin Al Had] dari [Muhammad bin Ibrahim bin Al Harits At Taimi] dari [Abu Salamah bin Abdurrahman] dari [Abu Sa'id al Khudri] berkata, "Rasulullah shallallahu 'alaihi wasallam memulai beri'tikaf pada sepuluh kedua pada bulan Ramadan. Beliau beri'tikaf pada tahun itu, hingga ketika tiba malam kedua puluh satu, yaitu hari di mana beliau keluar dari I'tikafnya setelah waktu subuh, beliau bersabda: 'Barangsiapa ingin melaksanakan I'tikaf bersamaku, hendaklah dia mengerjakannya pada sepuluh hari yang terakhir ini. Aku telah melihat dalam mimpiku, namun aku lupa. Aku mimpi pada waktu paginya aku bersujud pada air dan tanah. Carilah pada sepuluh hari yang terakhir, serta pada malam yang ganjil.' Abu Sa'id berkata; "Pada malam itu terjadi hujan, dan masjidnya berada pada bangsal, sehingga masjidnya bocor." Dia menambahkan; "Dengan kedua mataku, aku melihat Rasulullah shallallahu 'alaihi wasallam pergi, sementara pada dahi dan hidungnya ada bekas tanah dan air. Itu terjadi pada pagi hari malam ke dua puluh satu
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>697</td></tr><tr><td>Arabic No</td><td>697</td></tr><tr><td>Reference</td><td>Book 19 Hadith 697</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>

</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>697</td></tr><tr><td>Arabic No</td><td>697</td></tr><tr><td>Reference</td><td>Book 19 Hadith 697</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ابو سعید خدری سے روایت ہے کہ رسول اللہ صلی اللہ علیہ وسلم اعتکاف کیا کرتے تھے رمضان کے درمیانی عشرے کا تو ایک سال اعتکاف کیا جب اکیسویں رات آئی جس کی صبح کو آپ صلی اللہ علیہ وسلم اعتکاف سے باہر آیا کرتے تھے تو آپ صلی اللہ علیہ وسلم نے فرمایا جس شخص نے میرے ساتھ اعتکاف کیا ہے تو چاہیے اور دس دن تک اخیر میں اعتکاف کرے میں نے شب قدر کو معلوم کیا تھا پھر میں بھلا دیا گیا میں خیال کرتا ہوں کہ میں نے دیکھا کہ میں شب قدر کی صبح کو سجدہ کرتا ہوں کیچڑ اور پانی میں پس ڈھونڈو تم اس کو اخیر دس میں سے ہر طاق رات میں ابوسعید خدری نے کہا کہ اسی رات پانی برسا اور مسجد کی چھت پتوں اور شاخوں کی تھی تو ٹپکی مسجد ابوسعید نے کہا میری دونوں آنکھوں نے رسول اللہ صلی اللہ علیہ وسلم کو دیکھا آپ صلی اللہ علیہ وسلم نماز سے فارغ ہوئے اور پیشانی اور ناک مبارک پر آپ صلی اللہ علیہ وسلم کے مٹی اور پانی کا نشان تھا ۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>697</td></tr><tr><td>Arabic No</td><td>697</td></tr><tr><td>Reference</td><td>Book 19 Hadith 697</td></tr></tbody></table></div>