## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنِي يَحْيَى، عَنْ مَالِكٍ، عَنْ عَبْدِ رَبِّهِ بْنِ سَعِيدِ بْنِ قَيْسٍ، عَنْ أَبِي سَلَمَةَ بْنِ عَبْدِ الرَّحْمَنِ، أَنَّهُ قَالَ سُئِلَ عَبْدُ اللَّهِ بْنُ عَبَّاسٍ وَأَبُو هُرَيْرَةَ عَنِ الْمَرْأَةِ الْحَامِلِ يُتَوَفَّى عَنْهَا زَوْجُهَا فَقَالَ ابْنُ عَبَّاسٍ آخِرَ الأَجَلَيْنِ ‏.‏ وَقَالَ أَبُو هُرَيْرَةَ إِذَا وَلَدَتْ فَقَدْ حَلَّتْ ‏.‏ فَدَخَلَ أَبُو سَلَمَةَ بْنُ عَبْدِ الرَّحْمَنِ عَلَى أُمِّ سَلَمَةَ زَوْجِ النَّبِيِّ صلى الله عليه وسلم فَسَأَلَهَا عَنْ ذَلِكَ فَقَالَتْ أُمُّ سَلَمَةَ وَلَدَتْ سُبَيْعَةُ الأَسْلَمِيَّةُ بَعْدَ وَفَاةِ زَوْجِهَا بِنِصْفِ شَهْرٍ فَخَطَبَهَا رَجُلاَنِ أَحَدُهُمَا شَابٌّ وَالآخَرُ كَهْلٌ فَحَطَّتْ إِلَى الشَّابِّ فَقَالَ الشَّيْخُ لَمْ تَحِلِّي بَعْدُ ‏.‏ وَكَانَ أَهْلُهَا غَيَبًا وَرَجَا إِذَا جَاءَ أَهْلُهَا أَنْ يُؤْثِرُوهُ بِهَا فَجَاءَتْ رَسُولَ اللَّهِ صلى الله عليه وسلم فَقَالَ ‏ "‏ قَدْ حَلَلْتِ فَانْكِحِي مَنْ شِئْتِ ‏"‏ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1243</td></tr><tr><td>Arabic No</td><td>1243</td></tr><tr><td>Reference</td><td>Book 29 Hadith 1243</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
রেওয়ায়ত ৮৩. আবু সালমা ইবন আবদির রহমান (রহঃ) বলেনঃ ‘আবদুল্লাহ ইবন আব্বাস ও আবু হুরায়রা (রাঃ)-কে প্রশ্ন করা হইল এমন স্ত্রীলোক সম্বন্ধে, যে অস্তঃসত্ত্বা ও তাহার স্বামী ইন্তিকাল করিয়াছে। ইবন আব্বাস (রাঃ) উত্তরে বলিলেনঃ চার মাস দশ দিন এবং সন্তান প্রসব করা। নির্ধারিত এতদুভয় সময়ের মধ্যে যে সময় দীর্ঘ সে সময় ইদ্দতের সময় বলিয়া বিবেচিত হইবে। আবু হুরায়রা (রাঃ) বলিলেনঃ সন্তান প্রসব করিলে সে অন্যের জন্য হালাল হইবে। অতঃপর সালমা ইবন 'আবদির রহমান নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর পত্নী উম্মে সালমা (রাঃ)-এর সমীপে উপস্থিত হইলেন এবং তাহার নিকট এই ব্যাপারে প্রশ্ন করিলেন। উম্মে সালমা (রাঃ) বলিলেনঃ সুবাইয়া আসলামিয়া (রাঃ) তাহার স্বামীর ওফাতের অর্ধমাস পর সন্তান প্রসব করিলেন। ইহার পর দুই ব্যক্তি তাহাকে বিবাহ করার প্রস্তাব প্রেরণ করিলেন। তাহাদের একজন যুবক ও অপর জন হইতেছে আধাবয়সী, তিনি যুবকের (প্রস্তাবের) দিকে ঝুঁকিয়া পড়িলেন । আধাবয়সী (প্রস্তাবকারী) বললেন, তুমি এখন হালাল হও নাই। সুবাইয়ার পরিজন ছিল অনুপস্থিত। তাই তিনি আশা করিলেন যে, তাহারা আসিলে সুবাইয়া-(এর বিবাহ) সম্পর্কে তাহারা আধা বয়সী প্রস্তাবকারীকে অগ্রাধিকার দিবেন। সুবাইয়া রাসূলুল্লাহ সাল্লাল্লাহু আলায়হি ওয়া সাল্লামের খেদমতে উপস্থিত হইলেন এবং রাসূলুল্লাহ্ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর নিকট তাহার ব্যাপার উল্লেখ করিলেন। রাসূলুল্লাহ্ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম উত্তর দিলেনঃ তুমি হালাল হইয়া গিয়াছ, যাহাকে ইচ্ছা তুমি বিবাহ করিতে পার।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1243</td></tr><tr><td>Arabic No</td><td>1243</td></tr><tr><td>Reference</td><td>Book 29 Hadith 1243</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Yahya related to me from Malik from Abdu Rabbih ibn Said ibn Qays that Abu Salama ibn Abd ar-Rahman said that Abdullah ibn Abbas and Abu Hurayra were asked when a pregnant woman whose husband had died could remarry. Ibn Abbas said, "At the end of two periods." Abu Hurayra said, "When she gives birth, she is free to marry." Abu Salama ibn Abd ar-Rahman visited Umm Salama, the wife of the Prophet, may Allah bless him and grant him peace, and asked her about it Umm Salama said, ''Subaya al-Aslamiya gave birth half a month after the death of her husband, and two men asked to marry her. One was young and the other was old. She preferred the young man and so the older man said, 'You are not free to marry yet.' Her family were away and he hoped that when her family came, they would give her to him. She went to the Messenger of Allah, may Allah bless him and grant him peace, and he said, 'You are free to marry, so marry whomever you wish
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1243</td></tr><tr><td>Arabic No</td><td>1243</td></tr><tr><td>Reference</td><td>Book 29 Hadith 1243</td></tr></tbody></table></div>

## French


<div dir="ltr" lang="fr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Abou Salama Ibn Abdul Rahman a rapporté: «On demanda à Abdallah Ibn Abbas et Abou Houraira au sujet de la femme enceinte dont le mari meurt»? Ibn Abbas répondit: «Elle doit passer la période d'attente la plus longue» (On entend là, la période de deuil qui est de quatre mois et dix jours, ou attendre l'accouchement). Et Abou Houraira a dit à son tour: «Au cas, où elle accouche, elle pourra se marier de nouveau». Abou Salama Ibn Abdul-Rahman entra chez Oum Salama, la femme du Prophète (Sur lui la grâce et la paix d'Allah) et lui demanda à ce sujet. Oum Salama, répondit alors: «Soubai'a Al-Aslamia avait accouché une quinzaine de jours après la mort de son mari, deux hommes la demandèrent en mariage: L'un jeune, l'autre vieux, comme elle préférait le jeune, le vieux s'écria: «Tu ne peux pas encore te marier», les parents de la femme étant absents, il espérait qu'une fois qu'ils seraient présents, ils le préfrèront au jeune. Soubai'a vint trouver l'Envoyé d'Allah (salallahou alayhi wa salam) (Sur lui la grâce et la paix d'Allah) qui lui dit: «Tu es libre et tu pourras te marier avec celui que tu préfères»
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1243</td></tr><tr><td>Arabic No</td><td>1243</td></tr><tr><td>Reference</td><td>Book 29 Hadith 1243</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepadaku Yahya dari Malik dari [Abdu Rabbih bin Sa'id bin Qais] dari [Abu Salamah bin Abdurrahman] ia berkata; " [Ibnu Abbas] dan [Abu Hurairah] ditanya tentang seorang wanita hamil yang ditinggal mati oleh suaminya. Ibnu Abbas menjawab, "Iddahnya adalah yang paling lama waktunya di antara dua masa iddah." Dan Abu Hurairah menjawab, "Jika ia telah melahirkan bayinya, berarti masa iddahnya telah habis." Abu Salamah kemudian menemui Ummu Salamah, isteri Nabi shallallahu 'alaihi wasallam dan menanyakan hal tersebut kepadanya. [Ummu Salamah] lalu menjawab; "Subai'ah Al Aslamiyah telah melahirkan anaknya setengah bulan setelah ditinggal mati suaminya, lalu ada dua orang lelaki melamarnya, yang satu masih muda dan yang satu sudah tua. Lalu Subai'ah cenderung telah kepada laki-laki yang umurnya lebih muda, maka laki-laki yang umurnya lebih tua berkata, "Masa iddahmu belum selesai." (ia mengatakan begitu karena) Keluarga Shubai'ah sedang pergi, sehingga ketika mereka telah datang, mereka akan mengutamakan dirinya (atas laki-laki yang lebih muda) . Subai'ah kemudian menemui Rasulullah shallallahu 'alaihi wasallam, beliau pun bersabda: 'Masa iddahmu sudah lewat, nikahlah dengan siapa yang kamu mau
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1243</td></tr><tr><td>Arabic No</td><td>1243</td></tr><tr><td>Reference</td><td>Book 29 Hadith 1243</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Abdullah b. Abbas ve Ebu Hureyre'ye kocası ölen hamile kadının iddeti soruldu. İbn Abbas: «îki iddetin sonraya kalanı kadar başka kocayla evlenmesi helal olur.» dedi. Bunun üzerine Ebu Seleme b. Abdurrahman, Resulüllah Sallallahu Aleyhi ve Sellem'ın hanımı Ümmü Seleme'nin yanına giderek bu meseleyi ona sordu. Ümmü Seleme dedi ki: Sübey'a el-Eslemiyye kocası öldükten onbeş gün sonra doğurdu. Onunla biri genç, diğeri yaşlı iki kişi evlenmek is­tedi. Kadının gönlü gence meyletti. İhtiyar: «daha iddetin bitmedi» dedi. ihtiyarın ailesi seyahatte idi. Dönünce başkasından önce davranarak onu kendisine almalarını rica etti. Bunun üzerine kadın Resulüllah Sallallahu Aleyhi ve Sellem'a gelip durumu öğrenmek isteyince, Resulüllah Sallallahu Aleyhi ve Sellem: «İddetin bitti evlenebilirsin. İstediğinle evlen» buyurdu
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1243</td></tr><tr><td>Arabic No</td><td>1243</td></tr><tr><td>Reference</td><td>Book 29 Hadith 1243</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ابو سلمہ بن عبدالرحمن رضی اللہ تعالیٰ عنہ روایت ہے کہ عبداللہ بن عباس اور ابوہریرہ رضی اللہ تعالیٰ عنہ سوال ہوا کہ حاملہ عورت کا خاوند اگر مر جائے تو وہ کس حساب سے عدت کرے ابن عباس نے کہا کہ دونوں عدتوں میں سے جو عدت دور ہو اس کو اختیار کرے اور ابوہریرہ نے کہا کہ وضع حمل تک انتطار کرے پھر ابوسلمہ کے پاس گئیں اور ان سے جا کر پوچھا انہوں نے کہا کہ سبیعہ اسلمیہ اپنے خاوند کے مرنے کے بعد پندرہ دن میں جنی پھر دو شخصوں نے اس کو پیام بھیجا ایک نوجوان تھا دوسر ادھیڑ وہ نوجوان کی طرف مائل ہوئی ادھیڑ نے کہا تیری عدت ہی ابھی نہیں گزری اس خیال سے کہ اس کے عزیز وہاں نہ تھے جب وہ آئیں گے تو شاید اس عورت کو میری طرف مائل کر دیں پھر سبیعہ رسول اللہ صلی اللہ علیہ وسلم کے پاس آئی اور یہ حال بیان کیا آپ صلی اللہ علیہ وسلم نے فرمایا تیری عدت گرز گئی تو جس سے چاہے نکاح کر لے ۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1243</td></tr><tr><td>Arabic No</td><td>1243</td></tr><tr><td>Reference</td><td>Book 29 Hadith 1243</td></tr></tbody></table></div>