## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
وَحَدَّثَنِي عَنْ مَالِكٍ، عَنْ هِشَامِ بْنِ عُرْوَةَ، عَنْ عَبْدِ اللَّهِ بْنِ الزُّبَيْرِ، أَنَّهُ كَانَ يَقُولُ اعْلَمُوا أَنَّ عَرَفَةَ كُلَّهَا مَوْقِفٌ إِلاَّ بَطْنَ عُرَنَةَ وَأَنَّ الْمُزْدَلِفَةَ كُلَّهَا مَوْقِفٌ إِلاَّ بَطْنَ مُحَسِّرٍ ‏.‏ قَالَ مَالِكٌ قَالَ اللَّهُ تَبَارَكَ وَتَعَالَى ‏(‏فَلاَ رَفَثَ وَلاَ فُسُوقَ وَلاَ جِدَالَ فِي الْحَجِّ ‏)‏ قَالَ فَالرَّفَثُ إِصَابَةُ النِّسَاءِ وَاللَّهُ أَعْلَمُ قَالَ اللَّهُ تَبَارَكَ وَتَعَالَى ‏(‏أُحِلَّ لَكُمْ لَيْلَةَ الصِّيَامِ الرَّفَثُ إِلَى نِسَائِكُمْ ‏)‏ قَالَ وَالْفُسُوقُ الذَّبْحُ لِلأَنْصَابِ وَاللَّهُ أَعْلَمُ قَالَ اللَّهُ تَبَارَكَ وَتَعَالَى ‏(‏أَوْ فِسْقًا أُهِلَّ لِغَيْرِ اللَّهِ بِهِ‏)‏ ‏.‏ قَالَ وَالْجِدَالُ فِي الْحَجِّ أَنَّ قُرَيْشًا كَانَتْ تَقِفُ عِنْدَ الْمَشْعَرِ الْحَرَامِ بِالْمُزْدَلِفَةِ بِقُزَحَ وَكَانَتِ الْعَرَبُ وَغَيْرُهُمْ يَقِفُونَ بِعَرَفَةَ فَكَانُوا يَتَجَادَلُونَ يَقُولُ هَؤُلاَءِ نَحْنُ أَصْوَبُ وَيَقُولُ هَؤُلاَءِ نَحْنُ أَصْوَبُ فَقَالَ اللَّهُ تَعَالَى وَ ‏(‏لِكُلِّ أُمَّةٍ جَعَلْنَا مَنْسَكًا هُمْ نَاسِكُوهُ فَلاَ يُنَازِعُنَّكَ فِي الأَمْرِ وَادْعُ إِلَى رَبِّكَ إِنَّكَ لَعَلَى هُدًى مُسْتَقِيمٍ‏)‏ فَهَذَا الْجِدَالُ فِيمَا نُرَى وَاللَّهُ أَعْلَمُ وَقَدْ سَمِعْتُ ذَلِكَ مِنْ أَهْلِ الْعِلْمِ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Mauquf Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>874</td></tr><tr><td>Arabic No</td><td>874</td></tr><tr><td>Reference</td><td>Book 20 Hadith 874</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
রেওয়ায়ত ১৭০. আবদুল্লাহ্ ইবন যুবায়র (রাঃ) বলেনঃ তোমরা বিশ্বাস কর ‘বাতনে উরানা’ ব্যতীত সমগ্র আরাফাতের ময়দানই অবস্থান করার স্থান, এমনভাবে বাতনে মুহাসসির ব্যতীত মুযদালিফার সারাটা ময়দানেই অবস্থান করা যায়। মালিক (রহঃ) বলেনঃ আল্লাহ্ তা'আলা ইরশাদ করিয়াছেনঃ (فَلَا رَفَثَ وَلَا فُسُوقَ وَلَا جِدَالَ فِي الْحَجِّ) অর্থাৎ, হজের সময়ে স্ত্রীসম্ভোগ অন্যায় আচরণ ও কলহ-বিবাদ বিধেয় নহে। (বাকারাঃ ১৯৭) রাফাস অর্থ হইল স্ত্রীসম্ভোগ। আল্লাহ্‌রই অধিক জ্ঞাত। আল্লাহ্ তা'আলা অন্যত্র ইরশাদ করেনঃ (أُحِلَّ لَكُمْ لَيْلَةَ الصِّيَامِ الرَّفَثُ إِلَىٰ نِسَائِكُمْ) অর্থাৎ, সিয়ামের রাত্রে তোমাদের জন্য স্ত্রীসভোগ বৈধ করা হইয়াছে। (বাকারাঃ ১৮৭) মালিক (রহঃ) বলেনঃ ফুসুক অর্থ হইল, দেব-দেবীর নামে পশু উৎসর্গ করা, আল্লাহ্ই অধিক জ্ঞাত। আল্লাহ তা'আল ইরশাদ করেনঃ (أَوْ فِسْقًا أُهِلَّ لِغَيْرِ اللَّهِ بِهِ) অথবা যাহা অবৈধ, আল্লাহ ছাড় অন্যের নামে উৎসর্গের কারণে। (আল-আন’আমঃ ১৪৫) মালিক (রহঃ) বলেনঃ হজ্জে জিদাল বা ঝগড়া-বিবাদ হইল, কুরাইশ গোত্রের লোকজন তৎকালে হজ্জের সময় মুযদালিফার কুযাহ্ নামক স্থানে অবস্থান করিত। আর অন্যরা আরাফাতে অবস্থান করিত। উভয় দল তখন পরস্পর ঝগড়ায় লিপ্ত হইত, একদল বলিত, আমরাই সত্যপথের অনুসারী; অপর দল বলিত, আমরাই কেবল সত্যপথের অনুসারী। আল্লাহ্ তা'আলা আয়াত নাযিল করিয়া ইরশাদ করিলেনঃ لِكُلِّ أُمَّةٍ جَعَلْنَا مَنسَكًا هُمْ نَاسِكُوهُ فَلَا يُنَازِعُنَّكَ فِي الْأَمْرِ وَادْعُ إِلَىٰ رَبِّكَ إِنَّكَ لَعَلَىٰ هُدًى مُّسْتَقِيمٍ অর্থাৎ, আমি প্রত্যেক সম্প্রদায়ের জন্য নির্ধারিত করিয়া দিয়াছি ইবাদত পদ্ধতি যাহা উহারা অনুসরণ করে সুতরাং উহারা যেন তোমার সহিত বিতর্ক না করে এই ব্যাপারে। তুমি উহাদিগকে তোমার প্রতিপালকের দিকে আহবান কর। তুমিতো সরল পথেই প্রতিষ্ঠিত। (সূরা হাজ্জঃ ৬৭) হজ্জের সময় ঝগড়-বিবাদ বলিতে এই কথাই বোঝানো হইয়াছে। আল্লাহ অধিক জ্ঞাত। আলিমগণের নিকটও আমি এই ব্যাখ্যা শুনিয়াছি।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Mauquf Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>874</td></tr><tr><td>Arabic No</td><td>874</td></tr><tr><td>Reference</td><td>Book 20 Hadith 874</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Yahya related to me from Malik from Hisham ibn Urwa that Abdullah ibn az-Zubayr used to say, "Know that the whole of Arafa is a standing-place except for the middle of Urana, and that the wholeof Muzdalifa is a standing-place except for the middle of Muhassir." Malik said, "Allah, the Blessed and Exalted says, 'There is to be no rafath, no fusuq and no jidal during the hajj.' " (Sura 2 ayat 197). He added, "Rafath is sexual relations with women, and Allah knows best. Allah, the Blessed and Exalted says, 'Rafath with your women is permitted to you on the night of the fast.' (Sura 2 ayat 197). Fusuq are sacrifices made to idols, and Allah knows best. Allah, the Blessed and Exalted, says, 'Or a fisq offered up to other than Allah.' (Sura 2 ayat 197) Jidal (arguing) during the hajj refers to when the Quraysh used to stand near the mashar al-haram at Quzah in Muzdalifa, while the Arabs and others would stand at Arafa, and they would argue about who was the more correct. Allah, the Blessed and Exalted, says, 'And we appointed a method of sacrifice for every nation, which they followed, so let them not dispute with you about the matter, and call to your Lord. Surely you are on a straight guidance.' (Sura 22 ayat 67) This is what jidal refers to in our opinion, and Allah knows best. This I have heard from the people of knowledge
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Mauquf Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>874</td></tr><tr><td>Arabic No</td><td>874</td></tr><tr><td>Reference</td><td>Book 20 Hadith 874</td></tr></tbody></table></div>

## French


<div dir="ltr" lang="fr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Hicham a rapporté que Abdallah Ibn Al-Zoubair disait: «Sachez que Arafa dans son ensemble est une station, hormis la vallée de Ouranna; et que Al-Mouzdalifa est tout entière une station, exceptée la vallée de Mouhassar». Malek a dit: «Allah Béni et Très-Haut a dit le sens: «Le pèlerin doit s'abstenir de toute cohabitation avec une femme, de perversité et de disputes» Coran II, 197 . La cohabitaion est d'ailleurs tout rapport charnel avec la femme et c'est Allah qui en est le plus informé. Allah a aussi dit: le sens «la cohabitation avec vos femmes vous est permise durant la nuit qui suit le jeûne». Coran II, 187 . Et la perversité est tout ce qui a été immolé sur des pierres dressées et c'est Allah qui sait plus que quiconque, car il a aussi dit le sens: «Et ce qui, par perversité a été sacrifié à un autre que Allah». Coran VI, 145. Quant aux disputes (jidel) au cours du pèlerinage, il est un fait que les Qoraichites faisaient une station auprès du monument sacré à Mouzdalifa dans un lieu applelé Qouzah, alors que les Arabes faisaient la station à Arafa. Ils se disputèrent, les uns disant: «nous sommes sur la voie droite», les autres réclamaient, «non, c'est nous plutôt qui sommes sur la voie droite». "Allah Béni et Très-Haut, à leur sujet, a dit le sens: «Nous avons institué un rite pour chaque communauté; ses membres l'observent. Qu'ils ne discutent donc pas avec toi l'ordre reçu, Invoque ton Seigneur! Tu es sur une voie droite». Coran XXII, 67, 68 .C'est à cela que se réfere les disputes (jidel), que nous considérons comme tel et Allah est le plus informé. C'est bien ce que j'ai entendu dire des hommes versés». Chapitre LIV Des stations diverses de l'homme à l’état d'impureté et sur sa monture
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Mauquf Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>874</td></tr><tr><td>Arabic No</td><td>874</td></tr><tr><td>Reference</td><td>Book 20 Hadith 874</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepadaku dari Malik dari [Hisyam bin Urwah] dari [Abdullah bin Az Zubair] ia berkata, "Ketahuilah, Arafah seluruhnya adalah tempat wukuf, kecuali lembah Uranah. Muzdalifah semuanya adalah tempat wukuf kecuali lembah Muhassir
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Mauquf Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>874</td></tr><tr><td>Arabic No</td><td>874</td></tr><tr><td>Reference</td><td>Book 20 Hadith 874</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
İmam Malik bu konuda şöyle der: Allah Teala ayet- kerimede: «Hacda kadınlarla refes, füsuk kurban ve cidal / cedelleşme yoktur.»[Bakara, 197] buyurmaktadır. Allahu a'lem, bu ayeti kerimede geçen refes kelimesi cinsî münasebet olarak, fusuk kelimesi putlara kurban kesme olarak şu ayeti kerimelerde geçmektedir: «— Oruç tuttuğunu? günlerin geceleri kadınlarınıza yaklaşmanız (refes) size helal kılındı.»[Bakara, 187] «Veya Allah'tan başkası için ihrama girip kurban kesmek (fısk)...» Hacda Cidal'e gelince, cahiliyye devrinde Kureyşliler Muzde-life'deki Kuzah'da, diğer Araplar ve başkaları ise Arafatta durur, Kureyş: «Biz daha doğru yoldayız,» Araplar ve diğerleri: «Biz daha doğru yoldayız!» diye mücadele ederlerdi. Bunun için Allah şu ayeti inzal buyurdu: «— Her ümmet için kendisiyle amel ettikleri bir şeriat kıldık. Onun için bu konuda seninle niza* yapmasınlar. Sen onları rabbine çağır, çünkü sen en doğru yoldasın.»[Maide, 48] Bu ayette sözü edilen (niza') cidaldir. Ben bunu ehl-i ilimden işittim
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Mauquf Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>874</td></tr><tr><td>Arabic No</td><td>874</td></tr><tr><td>Reference</td><td>Book 20 Hadith 874</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
عبداللہ بن زبیر کہتے تھے جانو تم کہ عرفات سارا ٹھہرنے کی جگہ ہے مگر بطن محسر ۔ کہا مالک نے فرمایا اللہ تعالیٰ نے فلا رفث ولا فسوق ولاجدال فی الحج، نہ رفث ہے نہ فسق ہے نہ جھگڑا ہے حج میں، تو رفث کے معنی جماع کے ہیں اور اللہ خوب جانتا ہے فرمایا ہے احل لکم لیلة الصیام الرفث الی نساءکم حلال ہے تمہارے لئے روزوں کی رات میں جماع اپنی عورتوں سے یہاں پر رفث سے جماع مراد ہے۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Mauquf Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>874</td></tr><tr><td>Arabic No</td><td>874</td></tr><tr><td>Reference</td><td>Book 20 Hadith 874</td></tr></tbody></table></div>


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
کہا یحیی نے سوال ہوا امام مالک سے کہ عرفات میں یا مزدلفہ میں کوئی آدمی بے وضو ٹھہر سکتا ہے یا بے وضو کنکریاں مار سکتا ہے یا بے وضو صفا اور مروہ کے درمیان میں دوڑ سکتا ہے تو جواب دیا کہ جتنے ارکان حائضہ عورت کر سکتی ہے وہ سب کام مرد بے وضو کر سکتا ہے اور اس پر کچھ لازم نہیں آتا مگر افضل یہ ہے کہ ان سب کاموں میں باوضو ہو اور قصدا بے وضو ہونا اچھا نہیں ہے ۔ سوال ہوا امام مالک سے کہ عرفات میں سوار ہو کر ٹھہرے یا اتر کر، بولے سوار ہو کر مگر جب کوئی عذر ہو اس کو یا اس کے جانور کو تو اللہ جل جلالہ قبول کرنے والا ہے عذر کو۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>874.5</td></tr><tr><td>Arabic No</td><td>874.5</td></tr><tr><td>Reference</td><td>Book 0 Hadith 0</td></tr></tbody></table></div>