## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنِي يَحْيَى، عَنْ مَالِكٍ، عَنْ عَبْدِ اللَّهِ بْنِ يَزِيدَ، مَوْلَى الأَسْوَدِ بْنِ سُفْيَانَ عَنْ أَبِي سَلَمَةَ بْنِ عَبْدِ الرَّحْمَنِ بْنِ عَوْفٍ، عَنْ فَاطِمَةَ بِنْتِ قَيْسٍ، أَنَّ أَبَا عَمْرِو بْنَ حَفْصٍ، طَلَّقَهَا الْبَتَّةَ وَهُوَ غَائِبٌ بِالشَّامِ فَأَرْسَلَ إِلَيْهَا وَكِيلُهُ بِشَعِيرٍ فَسَخِطَتْهُ فَقَالَ وَاللَّهِ مَا لَكِ عَلَيْنَا مِنْ شَىْءٍ ‏.‏ فَجَاءَتْ إِلَى رَسُولِ اللَّهِ صلى الله عليه وسلم فَذَكَرَتْ ذَلِكَ لَهُ فَقَالَ ‏"‏ لَيْسَ لَكِ عَلَيْهِ نَفَقَةٌ ‏"‏ ‏.‏ وَأَمَرَهَا أَنْ تَعْتَدَّ فِي بَيْتِ أُمِّ شَرِيكٍ ثُمَّ قَالَ ‏"‏ تِلْكَ امْرَأَةٌ يَغْشَاهَا أَصْحَابِي اعْتَدِّي عِنْدَ عَبْدِ اللَّهِ ابْنِ أُمِّ مَكْتُومٍ فَإِنَّهُ رَجُلٌ أَعْمَى تَضَعِينَ ثِيَابَكِ عِنْدَهُ فَإِذَا حَلَلْتِ فَآذِنِينِي ‏"‏ ‏.‏ قَالَتْ فَلَمَّا حَلَلْتُ ذَكَرْتُ لَهُ أَنَّ مُعَاوِيَةَ بْنَ أَبِي سُفْيَانَ وَأَبَا جَهْمِ بْنَ هِشَامٍ خَطَبَانِي ‏.‏ فَقَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏"‏ أَمَّا أَبُو جَهْمٍ فَلاَ يَضَعُ عَصَاهُ عَنْ عَاتِقِهِ وَأَمَّا مُعَاوِيَةُ فَصُعْلُوكٌ لاَ مَالَ لَهُ انْكِحِي أُسَامَةَ بْنَ زَيْدٍ ‏"‏ ‏.‏ قَالَتْ فَكَرِهْتُهُ ثُمَّ قَالَ ‏"‏ انْكِحِي أُسَامَةَ بْنَ زَيْدٍ ‏"‏ ‏.‏ فَنَكَحْتُهُ فَجَعَلَ اللَّهُ فِي ذَلِكَ خَيْرًا وَاغْتَبَطْتُ بِهِ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1225</td></tr><tr><td>Arabic No</td><td>1225</td></tr><tr><td>Reference</td><td>Book 29 Hadith 1225</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
রেওয়ায়ত ৬৭. ফাতেমা বিনত কায়েস হইতে বর্ণিত, আবু আমর ইবন হাফস (রাঃ) তাহাকে তালাকে আল-বাত্তা দিলেন। তাহার স্বামী তখন সিরিয়াতে ছিলেন। অতঃপর তাহার উকীলকে গমসহ তাহার নিকট পাঠাইলেন। তিনি উহাকে অতি অল্প মনে করিলেন। তাহার উকীল বলিলেন, আমাদের নিকট তোমার প্রাপ্য আর কিছু নাই। তিনি (ফাতেমা) রাসূলুল্লাহ সাল্লাল্লাহু আলায়হি ওয়া সাল্লামের খেদমতে উপস্থিত হইলেন এবং এই ঘটনা উল্লেখ করিলে রাসূল সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলিলেন, তাহার জন্য তোমার খোরপোশ প্রদান জরুরী নহে, এবং ফাতেমাকে উম্মে শরীফের গৃহে ইদ্দত পালন করিতে তিনি নির্দেশ দিলেন। তারপর বলিলেনঃ (উম্মে শরীফ এমন একজন মহিলা) যাহার গৃহে আমার সাহবিগণ সর্বদা যাতায়াত করিয়া থাকেন। তুমি আবদুল্লাহ ইবন উম্মে মাকতুমের গৃহে ইদ্দত পালন কর, কারণ তিনি একজন অন্ধ ব্যক্তি। তোমার বস্ত্র তাহার নিকট উন্মুক্ত হইলেও (ইহাতে তোমার কোন অসুবিধা হইবে না)। ইদ্দত শেষ হওয়ার পর তুমি অন্যের জন্য হালাল হইয়া গেলে আমাকে খবর দিও। ফাতেমা বলিলেনঃ আমি হালাল হওয়ার পর রাসূলুল্লাহ্ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর নিকট আমার বিষয় উল্লেখ করিলাম এবং বলিলাম, মুয়াবিয়া ইবন আবি সুফিয়ান (রহঃ) ও আবু জাহম ইবন হিশাম (রাঃ)। তাহারা উভয়ে আমার নিকট বিবাহের প্রস্তাব দিয়াছেন। রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলিলেন, আবু জাহম তাহার গর্দান হইতে লাঠি নামায় না। আর মুয়াবিয়া দরিদ্র ব্যক্তি। তাহার ধন-সম্পদ নাই। তুমি উসামা ইবন যায়দ (রাঃ)-কে বিবাহ কর। ফাতেমা বলিলেন, আমি উসামাকে অপছন্দ করি। রাসূলুল্লাহ্ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম পুনরায় বলিলেনঃ তুমি উসামা ইবন যায়দ (রাঃ)-কে বিবাহ কর। তারপর আমি তাহাকে বিবাহ করি এবং আল্লাহ ইহাতে অনেক মঙ্গল দান করিয়াছেন, যাহার কারণে আমার প্রতি ঈর্ষা করা হইত।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1225</td></tr><tr><td>Arabic No</td><td>1225</td></tr><tr><td>Reference</td><td>Book 29 Hadith 1225</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Yahya related to me from Malik from Abdullah ibn Yazid, the mawla of al-Aswad ibn Sufyan from Abu Salama ibn Abd ar-Rahman ibn Awf from Fatima bint Qays that Abu Amr ibn Hafs divorced her absolutely while he was away in Syria. His agent sent her some barley and she was displeased with it, saying, "By Allah, I don't expect anything from you." She went to the Messenger of Allah, may Allah bless him and grant him peace, and mentioned it to him. He said, "You have no maintenance." He then ordered her to spend her idda in the house of Umm Sharik. Then he said, "This is a woman whom my companions visit. Spend the idda in the house of Ibn Umm Maktum. He is a blind man and you can undress at his home. When you are free to remarry, tell me." She continued, "When I was free to remarry, I mentioned to him that Muawiya ibn Abi Sufyan and Abu Jahm ibn Hisham had asked for me in marriage. The Messenger of Allah, may Allah bless him and grant him peace, said, 'As for Abu Jahm, he never puts down his stick from his shoulder (i.e. he is always travelling), and as for Muawiya he is a poor man with no property. Marry Usama ibn Zayd.' I objected to him and he said, 'Marry Usama ibn Zayd,' so I married him, and Allah put good in it and I was content with him
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1225</td></tr><tr><td>Arabic No</td><td>1225</td></tr><tr><td>Reference</td><td>Book 29 Hadith 1225</td></tr></tbody></table></div>

## French


<div dir="ltr" lang="fr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Abou Salama Ibn Abdul Rahman Ibn Awf a rapporté d'après Fatima Bint Qais que Abou Amr Ibn Hafs avait définitivement divorcé d'avec elle, alors qu'il était eu Syrie. Il lui envoya son agent avec une quantité d'orge, elle était répugnée et dit à l'agent "Par Allah je n'attend rien de vous", il lui répondit: «Par Allah, tu ne nous dois rien». Elle vint trouver l'Envoyé d'Allah (salallahou alayhi wa salam) r (Sur lui la grâce et la paix d'Allah) lui apprenant ce qui a eu lieu, il lui répondit: «Tu ne lui dois aucune dépense», et lui donna l'ordre de passer sa période d'attente à la maison de Oum Charik, puis lui dit: «Non, cette femme reçoit beaucoup de gens,il vaut mieux que tu passes cette période chez Abdallah Ibn Oum Mak-toum, car c'est un homme aveugle. Chez lui, tu pourras te dévoiler (changer tles habits). Une fois que tu termines ta période d'attente, apprends-le moi». Fatima continua: «Une fois que je fus à la fin de ma période d'attente je vins lui apprendre que Mou'awia IbnAbi Soufian et Abou Jahm Ibn Hicham me demandèrent en mariage». Alors l'Envoyé d'Allah (salallahou alayhi wa salam) (Sur lui la grâce et la paix d'Allah) répondit: «Quant à Abou Jahm, il a toujours sa canne sur son épaule (1) et pour Mou'awia, ce n'est qu'un homme dépourvu de tout bien. Epouse, Oussama Ibn Zaid». Elle dit:«Mais je ne m'accorde pas avec lui». Mais il reprit: «Epouse Oussama Ibn Zaid», et je me mariait avec.lui: Ainsi Allah m'accorda tant de biens et je mène avec lui une vie heureuse». (1) Il y a deux opinions différentes quand au sens de la canne sur son épaule (une c'est qu'il est sévère avec ses femmes et l'autre c'est qu'il est toujours en voyage)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1225</td></tr><tr><td>Arabic No</td><td>1225</td></tr><tr><td>Reference</td><td>Book 29 Hadith 1225</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepadaku Yahya dari Malik dari [Abdullah bin Yazid] mantan budak Al Aswad bin Sufyan, dari [Abu Salamah bin Abdurrahman bin Auf] dari [Fatimah binti Qais] bahwa Abu 'Amru bin Hafsh menjatuhkan talak ba'in kepadanya, padahal dia sedang berada di Syam. Lalu Abu Amru mengutus wakilnya untuk mengirimkan gandum kepadanya, hingga menjadikan Fatimah marah kepada. Abu Amru berkata, "Demi Allah, kamu tidak berhak atas apapun dariku." Fatimah bin Qais lantas mendatangi Rasulullah shallallahu 'alaihi wasallam dan mengkisahkan kejadian itu kepada beliau. Beliau lalu bersabda: "Kamu tidak berhak mendapatkan nafkah darinya." Kemudian beliau menyuruhnya untuk menunggu masa iddahnya di rumah Ummu Syarik. setelah itu beliau bersabda: "Dia adalah wanita yang sering dikunjungi oleh para sahabatku. Maka tunggulah masa iddahmu di rumah Abdullah bin Ummi Maktum, dia adalah seorang yang buta, sehingga kamu dapat meletakkan pakaianmu di sisinya. Jika masa iddahmu telah selesai maka beritahukanlah kepadaku." Fatimah berkata, "Ketika masa iddahku telah selesai, aku ceritakan kepada beliau bahwa Mu'awiyah bin Abu Sufyan dan Abu Jahm bin Hisyam telah melamarku. Rasulullah shallallahu 'alaihi wasallam lalu bersabda: "Jahm itu seorang laki-laki yang tidak pernah meletakkan tongkat dari pundaknya, sedangkan Mu'awiyah adalah seorang laki-laki miskin yang tidak mempunyai harta. Nikahlah dengan Usamah bin Zaid." Fatimah berkata, "Sebenarnya aku tidak menyukainya." Kemudian beliau berkata lagi: "Nikahlah dengan Usaman bin Zaid." Maka aku pun menikah dengannya, dan ternyata Allah menjadikan kebaikan di dalam pernikahan itu, hingga aku merasa bahagia
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1225</td></tr><tr><td>Arabic No</td><td>1225</td></tr><tr><td>Reference</td><td>Book 29 Hadith 1225</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Fatıma binti Kays şöyle dedi: Kocam Ebu Amr b. Hafsa Şam'da iken, beni üç talak ile boşadı. Bana, vekili arpa gönderdi. Ben de ona sinirlendim. Bana: «—Vallahi, bizde bir hakkın yok» dedi. Ben de Resulullah Sallallahu Aleyhi ve Sellem'a giderek meseleyi anlattım. Resulullah: «—Nafakan kocana ait değil» dedi ve Ümmü Şerîk'in evinde iddet beklememi emretti sonra şöyle dedi: «— Ashabım Ümmü Şerîk'e (iyi bir kadın olduğundan) çok gider gelirler. (Seni görmemeleri gerek) sen, Abdullah b. Ümmi Mektum'un yanında iddet bekle» zira o amadır, onun yanında örtünü çıkarır, serbest olabilirsin. İddetin bittiğinde bana haber ver.» îddetim bitince Resulullah'a, Mua-yiye b. Ebi Süfyan ve Ebu Cehm b. Hişam'm benimle evlenmek is­tediklerini söyledim. Resulullah Sallallahu Aleyhi ve Sellem : «— Ebu Cehm, asasını omzundan bırakmaz (yani karı­larını çok döver ya da çok seyahat eder), Muaviye de hiç malı olmayan (cimrinin) biri, sen Üsame b. Zeyd'le ev­len» buyurdu. Ben istemedim, sonra Resulullah: «— Üsame b. Zeyd'le evlen» buyurdular. Ben de evlendim. Allah, bu evliliği hayırlı kıldı ve onunla mesud oldum. Diğer tahric: Müslim, Talak; Şafiî, Risale, no: 756
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1225</td></tr><tr><td>Arabic No</td><td>1225</td></tr><tr><td>Reference</td><td>Book 29 Hadith 1225</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
فاطمہ بنت قیس کو ابوعمرو بن حفص نے طلاق بتہ دی اور وہ شام میں تھیں انہوں نے اپنے وکیل کو جو دے کر بھیجا فاطمہ بنت قیس خفا ہوئی وکیل بولا تمہارا تو کچھ نہیں دینا فاطمہ خفا ہو کر آپ صلی اللہ علیہ وسلم کے پاس آئیں آپ صلی اللہ علیہ وسلم نے فرمایا بے شک تیرا خرچ خاوند پر نہیں ہے ۔ اور تو شریک کے گھر میں عدت گزار آپ صلی اللہ علیہ وسلم نے فرمایا ام شریک کے گھر میں رات دن میرے اصحاب آیا جایا کرتے ہیں عبداللہ بن ام مکتوم کے گھر میں تو عدت کر کیونکہ وہ اندھا ہے تو اگر تو اپنے کپڑے اتارے گی تو بھی کچھ قباحت نہیں جب تیری عدت گزر جائے تو مجھے کہنا فاطمہ بنت قیس نے کہا جب میری عدت گزر گئی تو میں نے حضرت سے کہا کہ معاویہ بن ابوسفیان اور ابوفہم بن ہشام دونوں نے مجھے پیام دیا ہے آپ صلی اللہ علیہ وسلم نے فرمایا ابوجہم تو اپنی لکڑی کبھی ہاتھ سے رکھتا ہی نہیں اور معاویہ مفلس ہیں ان کے پاس مال نہیں تو اسامہ بن زید سے نکاح کر میں نے اسامہ کو ناپسند کیا آپ صلی اللہ علیہ وسلم نے پھر فرمایا تو اسامہ سے نکاح کر فاطمہ نے کہا میں نے اسامہ سے نکاح کر لیا اللہ نے اس میں برکت دی اور لوگ رشک کرنے لگے۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1225</td></tr><tr><td>Arabic No</td><td>1225</td></tr><tr><td>Reference</td><td>Book 29 Hadith 1225</td></tr></tbody></table></div>