## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
وَحَدَّثَنِي مَالِكٌ، عَنْ إِسْحَاقَ بْنِ عَبْدِ اللَّهِ بْنِ أَبِي طَلْحَةَ، أَنَّهُ سَمِعَ أَنَسَ بْنَ مَالِكٍ، يَقُولُ كَانَ أَبُو طَلْحَةَ أَكْثَرَ أَنْصَارِيٍّ بِالْمَدِينَةِ مَالاً مِنْ نَخْلٍ وَكَانَ أَحَبُّ أَمْوَالِهِ إِلَيْهِ بَيْرُحَاءَ وَكَانَتْ مُسْتَقْبِلَةَ الْمَسْجِدِ وَكَانَ رَسُولُ اللَّهِ صلى الله عليه وسلم يَدْخُلُهَا وَيَشْرَبُ مِنْ مَاءٍ فِيهَا طَيِّبٍ قَالَ أَنَسٌ فَلَمَّا أُنْزِلَتْ هَذِهِ الآيَةُ ‏(‏ لَنْ تَنَالُوا الْبِرَّ حَتَّى تُنْفِقُوا مِمَّا تُحِبُّونَ‏)‏ قَامَ أَبُو طَلْحَةَ إِلَى رَسُولِ اللَّهِ صلى الله عليه وسلم فَقَالَ يَا رَسُولَ اللَّهِ إِنَّ اللَّهَ تَبَارَكَ وَتَعَالَى يَقُولُ ‏(‏لَنْ تَنَالُوا الْبِرَّ حَتَّى تُنْفِقُوا مِمَّا تُحِبُّونَ‏)‏ وَإِنَّ أَحَبَّ أَمْوَالِي إِلَىَّ بَيْرُحَاءَ وَإِنَّهَا صَدَقَةٌ لِلَّهِ أَرْجُو بِرَّهَا وَذُخْرَهَا عِنْدَ اللَّهِ فَضَعْهَا يَا رَسُولَ اللَّهِ حَيْثُ شِئْتَ قَالَ فَقَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏ "‏ بَخْ ذَلِكَ مَالٌ رَابِحٌ ذَلِكَ مَالٌ رَابِحٌ وَقَدْ سَمِعْتُ مَا قُلْتَ فِيهِ وَإِنِّي أَرَى أَنْ تَجْعَلَهَا فِي الأَقْرَبِينَ ‏"‏ ‏.‏ فَقَالَ أَبُو طَلْحَةَ أَفْعَلُ يَا رَسُولَ اللَّهِ فَقَسَمَهَا أَبُو طَلْحَةَ فِي أَقَارِبِهِ وَبَنِي عَمِّهِ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1842</td></tr><tr><td>Arabic No</td><td>1842</td></tr><tr><td>Reference</td><td>Book 58 Hadith 1842</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
রেওয়ায়ত ২. আনাস ইবনে মালিক (রাঃ) বলেন, মদীনার আনসারগণের মধ্যে আবু তালহা (রাঃ) ছিলেন সর্বাধিক ধনী ব্যক্তি। তাঁহার সবচাইতে অধিক খেজুর বৃক্ষ ছিল। সমুদয় বাগানের মধ্যে ‘বাইরহা’ নামক বাগানটি ছিল তাহার (আবু তালহার) অধিক পছন্দনীয়। বাগানটি মসজিদে নববীর সামনেই অবস্থিত ছিল। রাসূলুল্লাহ সাল্লাল্লাহু আলায়হি ওয়া সাল্লাম সেই বাগানে প্রায়ই আসা-যাওয়া করিতেন। সেখানকার পানি খুবই উত্তম ছিল, তিনি তাহা পান করিতেন। আনাস (রাঃ) বলেন, যখন এই আয়াত নাযিল হইলঃ (لَنْ تَنَالُوا الْبِرَّ حَتَّى تُنْفِقُوا مِمَّا تُحِبُّونَ) অর্থাৎ যতক্ষণ তোমরা তোমাদের প্রিয় বস্তু (আল্লাহর রাহে) খরচ না করিবে, ততক্ষণ তোমরা সওয়াব পাইবে না)। তখন আবু তালহা (রাঃ) রাসূলুল্লাহ সাল্লাল্লাহু আলায়হি ওয়া সাল্লামের নিকট আসিয়া বলিলেন, ইয়া রাসূলাল্লাহ! আল্লাহ তা’আলা বলেন যে, যতক্ষণ তোমরা তোমাদের প্রিয় বস্তু (আল্লাহর রাহে) খরচ না করিবে, ততক্ষণ তোমরা সওয়াব পাইবে না। আর আমার প্রিয় বস্তু হইল এই ‘বাইরহা’। আমি ইহাকে আল্লাহর রাস্তায় সদকা করিলাম। ইহার বিনিময়ে আমি নেকীর আশা রাখি এবং ইহা আল্লাহর নিকট জমা রাখিতেছি। সুতরাং ইয়া রাসূলাল্লাহ্! আপনি ইহাকে যেভাবে ইচ্ছা কবুল করুন। অতঃপর রসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলিলেন, বাহবা! ইহা অত্যন্ত লাভজনক মাল, ইহা অত্যন্ত লাভজনক মাল। তুমি এই বাগান সম্বন্ধে যাহা কিছু বলিয়াছ আমি উহা শ্রবণ করিয়াছি। আমার মনে হয়, তুমি ইহাকে তোমার আত্মীয়-স্বজনদের মধ্যে বিতরণ করিয়া দাও। আবু তালহা বলিলেন, ইয়া রাসূলাল্লাহ! আমি উহা বিতরণ করিয়া দিব। অতএব আবু তালহা (রাঃ) তাহার আত্মীয়-স্বজন ও চাচাত ভাইগণের মধ্যে উহা বন্টন করিয়া দিলেন।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1842</td></tr><tr><td>Arabic No</td><td>1842</td></tr><tr><td>Reference</td><td>Book 58 Hadith 1842</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Malik related to me that Ishaq ibn Abdullah ibn Abi Talha heard Anas ibn Malik say, "Abu Talha had the greatest amount of property in palm-trees among the Ansar in Madina. The dearest of his properties to him was Bayruha which was in front of the mosque. The Messenger of Allah, may Allah bless him and grant him peace, used to go into it and drink from the pleasant water which was in it." Anas continued, "When this ayat was sent down 'You will not obtain rightness of action until you expend of what you love,' (Sura 2 ayat l76), Abu Talha went to the Messenger of Allah, may Allah bless him and grant him peace, and said, 'Messenger of Allah! Allah, the Blessed, the Exalted, has said, "You will not obtain until you expend of what you love." The property which I love the best is Bayruha. It is sadaqa for Allah. I hope for its good and for it to be stored up with Allah. Place it wherever you wish, Messengerof Allah. ' " "The Messenger of Allah, may Allah bless him and grant him peace, said, 'Well done! That is property which profits! That is property which profits. I have heard what you have said about it and I think that you should give it to your relatives.' Abu Talha said, 'I will do it, Messenger of Allah!' Abu Talha therefore divided it among his relatives and the children of his paternal uncle
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1842</td></tr><tr><td>Arabic No</td><td>1842</td></tr><tr><td>Reference</td><td>Book 58 Hadith 1842</td></tr></tbody></table></div>

## French


<div dir="ltr" lang="fr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Anas Ibn Malek a rapporté: «Abou Talha était l'un des Ansars à Médine, le plus riche en palmeraies, préférant de tous ses biens, celle qui se trouvait à Bairoha, située juste face à la mosquée. L'Envoyé d'Allah (salallahou alayhi wa salam) (Sur lui la grâce et la paix d'Allah) y entrait et buvait de son eau douce. Anas continuant, dit: «Et quand le verset suivant, fut révélé: ) لَن تَنَالُواْ الْبِرَّ حَتَّى تُنفِقُواْ مِمَّا تُحِبُّونَ وَمَا تُنفِقُواْ مِن شَيْءٍ فَإِنَّ اللّهَ بِهِ عَلِيمٌ( (le sens) «Vous n'atteindrez pas à la piété vraie tant que vous ne donnerez pas en aumône ce que vous aimez» (Coran III,92), Abou Talha se rendit chez l'Envoyé d'Allah r (salallahou alayhi wa salam) (Sur lui la grâce et la paix d'Allah) et lui dit: «Ô Envoyé d'Allah! Allah Y Béni et Très-Haut a dit: «Vous n'atteindrez pas à la piété vraie tant que vous ne donnerez pas en aumône ce que vous aimez», et ce qui m'est préféré de mes biens, c'est la palmeraie de Bairoha; je la donne pour aumône pour l'amour d'Allah Y , espérant que Allah Y agrée mon acte et me le réserve auprès de Lui. Ainsi, donne-la à qui tu voudras, Ô Envoyé d'Allah». L'Envoyé d'Allah r (salallahou alayhi wa salam) (Sur lui la grâce et la paix d'Allah) lui répondit: «Quelle merveille! Tel est un bien fructueux! Tel est un bien fructueux. J'ai bien saisi ce que tu as entendu dire à son sujet, et moi je préfère que tu la donnes à tes proches». Abou Talha dit: «Je le ferai, Ô Envoyé d'Allah et il l'a partagée entre ses proches et ses cousins»
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1842</td></tr><tr><td>Arabic No</td><td>1842</td></tr><tr><td>Reference</td><td>Book 58 Hadith 1842</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepadaku Malik dari [Ishaq bin Abdullah bin Abu Thalhah] Bahwasanya ia mendengar [Anas bin Malik] berkata, "Abu Thalhah adalah orang Anshar yang paling banyak hartanya di Madinah yang berupa kurma. Adapun harta yang paling dia sukai ialah Bairuha yang berada di depan masjid. Rasulullah shallallahu 'alaihi wasallam biasa memasukinya dan minum dari airnya yang jernih." Anas berkata; "Ketika ayat ini diturunkan: '(Kalian sekali-kali tidak akan mendapatkan kebaikan (yang sempurna) sehingga kalian menginfakkan sebagian harta yang kalian sukai) .' (Qs. Ali Imran: 92) Abu Thalhah berdiri menghadap Rasulullah shallallahu 'alaihi wasallam kemudian berkata; 'Wahai Rasulullah, Allah Tabaraka Wa Ta'ala berfirman: '(Kalian sekali-kali tidak akan mendapatkan kebaikan (yang sempurna) sehingga kalian menginfakkan sebagian harta yang kalian sukai) ', sungguh harta yang paling aku sukai adalah Bairuha, kebun itu saya infakkan karena Allah, aku harap kebaikannya dan penyimpanannya di sisi Allah. Wahai Rasulullah, pergunakanlah harta tersebut sebagaimana anda kehendaki." Anas berkata, "Kemudian Rasulullah shallallahu 'alaihi wasallam bersabda: "Hebat…! Itu adalah harta yang menguntungkan, itu adalah harta yang menguntungkan. Aku telah mendengar apa yang engkau katakan. Menurutku sebaiknya kamu memberikannya kepada karib kerabat.' Maka Abu Thalhah berkata, "Wahai Rasulullah, akan aku lakukan." Kemudian dia membaginya untuk keluarga dan anak pamannya
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1842</td></tr><tr><td>Arabic No</td><td>1842</td></tr><tr><td>Reference</td><td>Book 58 Hadith 1842</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ebu Talha'mn torunu îshak'dan, Enes b. Malik'in şöyle anlattığını işittiği rivayet edildi: Ebu Talha, Medine'de Ensar'dan en zengin hurmalığa sahip olanıydı. Kendisince en değerli malı da, Mescid-i Nebevi'nin karşısındaki «Beyruha» adındaki hurmalığı idi. Resulullah Sallallahu Aleyhi ve Sellem oraya girip tatlı suyundan içerdi. «Sevdiğiniz şeylerden infak et' medikçe iyiliği elde edemezsiniz.»[Al-i îmran, 92] ayet-i kerimesince, Ebu Talha, Resulullah Sallallahu Aleyhi ve Sellem'ın huzuruna çıkıp: «— Ya Resulallah! Allah Teala: «Sevdiğiniz şeylerden infak etmedikçe iyiliği elde edemezsiniz» buyuruyor. Bence mallarımın en değerlisi, Beyruha (denilen hurmalık)'dır. O Allah rızası için sadakadır. Allah katında onun hayır ve azığım olmasını umuyorum. İstediğin yere sarfet ya Resulallah!» deyince, Resulallah Sallallahu Aleyhi ve Sellem: «— Bu ne karlı maldır, bu ne karlı maldır. Onun hakkında söylediğini işittim. Onu yakınlarına vermeni uygun görüyorum.» buyurdu. Bunun üzerine Ebu Talha: «— Yapacağım ya Resulallah» dedi. Sonra hurmalığı akrabalarına ve amcasının oğullarına taksim etti
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1842</td></tr><tr><td>Arabic No</td><td>1842</td></tr><tr><td>Reference</td><td>Book 58 Hadith 1842</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
(انس بن مالک کہتے تھے کہ ابوطلحہ سب انصاریوں سے زیادہ مالدار تھے مدینے میں یعنی کھجور کے درخت سب سے زیادہ ان کے پاس تھے اور سب مالوں میں ان کو ایک باغ بہت پسند تھا جس کو بیر حاء کہتے تھے اور وہ مسجد نبوی کے سامنے تھا رسول اللہ صلی اللہ علیہ وآلہ وسلم اس میں جایا کرتے تھے اور وہاں کا صاف پانی پیا کرتے تھے، حضرت انس فرماتے ہیں کہ جب یہ آیت اتری "لَنْ تَنَالُوا الْبِرَّ حَتّٰى تُنْفِقُوْا مِمَّا تُحِبُّوْنَ" 3۔ ال عمران : 92) یعنی تم نیکی کو نہ پہنچو گے جب تک کہ تم خرچ نہ کرو گے اس مال میں سے جس کو تم چاہتے ہو تو ابوطلحہ رسول اللہ صلی اللہ علیہ وآلہ وسلم کے پاس آئے اور کہا یا رسول اللہ صلی اللہ علیہ وآلہ وسلم کیا آپ نے ارشاد فرمایا ہے لن تنالوا البر حتی تنفقوا مما تحبون اور مجھے اپنے سب مالوں میں بیر حاء پسند ہے وہ صدقہ ہے اللہ کی راہ میں اللہ سے اس کی بہتری اور جزاء چاہتا ہوں اور وہ بیر حاء ذخیرہ ہے اللہ کے پاس آپ نے فرمایا واہ واہ یہ مال تو بڑا اجر لانے والا ہے یا بڑے نفع والا ہے اور میں سن چکا ہوں جو تم نے اس مال کے بارے میں کہا ہے میرے نزدیک تم اس مال کو اپنے عزیزوں میں بانٹ دو ابوطلحہ نے کہا یا رسول اللہ صلی اللہ علیہ وآلہ وسلم بانٹ دوں پھر ابوطلحہ نے اس کو تقسیم کردیا اپنے عزیزں اور چچا کے بیٹوں میں۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1842</td></tr><tr><td>Arabic No</td><td>1842</td></tr><tr><td>Reference</td><td>Book 58 Hadith 1842</td></tr></tbody></table></div>