## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
وَحَدَّثَنِي عَنْ مَالِكٍ، عَنْ دَاوُدَ بْنِ الْحُصَيْنِ، عَنْ وَاقِدِ بْنِ عَمْرِو بْنِ سَعْدِ بْنِ مُعَاذٍ، أَنَّهُ أَخْبَرَهُ عَنْ مَحْمُودِ بْنِ لَبِيدٍ الأَنْصَارِيِّ، أَنَّ عُمَرَ بْنَ الْخَطَّابِ، حِينَ قَدِمَ الشَّامَ شَكَا إِلَيْهِ أَهْلُ الشَّامِ وَبَاءَ الأَرْضِ وَثِقَلَهَا وَقَالُوا لاَ يُصْلِحُنَا إِلاَّ هَذَا الشَّرَابُ ‏.‏ فَقَالَ عُمَرُ اشْرَبُوا هَذَا الْعَسَلَ ‏.‏ قَالُوا لاَ يُصْلِحُنَا الْعَسَلُ ‏.‏ فَقَالَ رَجُلٌ مِنْ أَهْلِ الأَرْضِ هَلْ لَكَ أَنْ نَجْعَلَ لَكَ مِنْ هَذَا الشَّرَابِ شَيْئًا لاَ يُسْكِرُ قَالَ نَعَمْ ‏.‏ فَطَبَخُوهُ حَتَّى ذَهَبَ مِنْهُ الثُّلُثَانِ وَبَقِيَ الثُّلُثُ فَأَتَوْا بِهِ عُمَرَ فَأَدْخَلَ فِيهِ عُمَرُ إِصْبَعَهُ ثُمَّ رَفَعَ يَدَهُ فَتَبِعَهَا يَتَمَطَّطُ فَقَالَ هَذَا الطِّلاَءُ هَذَا مِثْلُ طِلاَءِ الإِبِلِ ‏.‏ فَأَمَرَهُمْ عُمَرُ أَنْ يَشْرَبُوهُ فَقَالَ لَهُ عُبَادَةُ بْنُ الصَّامِتِ أَحْلَلْتَهَا وَاللَّهِ ‏.‏ فَقَالَ عُمَرُ كَلاَّ وَاللَّهِ اللَّهُمَّ إِنِّي لاَ أُحِلُّ لَهُمْ شَيْئًا حَرَّمْتَهُ عَلَيْهِمْ وَلاَ أُحَرِّمُ عَلَيْهِمْ شَيْئًا أَحْلَلْتَهُ لَهُمْ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Mauquf Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1550</td></tr><tr><td>Arabic No</td><td>1550</td></tr><tr><td>Reference</td><td>Book 42 Hadith 1550</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
রেওয়ায় ১৪. মাহমুদ ইবন লবীদ আনসারী (রহঃ) হইতে বর্ণিত, উমর (রাঃ) যখন শাম দেশে আগমন করিলেন তখন শামের বাসিন্দার মধ্যে কেহ তাহার নিকট শাম দেশের মহামারী ও আবহাওয়া সম্বন্ধে অভিযোগ করিল এবং বলিল, এখানে শরাব পান করা ছাড়া স্বাস্থ্য ঠিক থাকে না। উমর (রাঃ) বলিলেনঃ তোমরা মধু পান কর। তাহারা বলিল, মধুও স্বাস্থ্য ঠিক রাখিতে পারে না। এমন সময় এক ব্যক্তি বলিল, আমি উহা আপনার জন্য এমন এমনভাবে তৈরি করিব যাহাতে মাদকতা থাকিবে না। তিনি বলিলেন, হ্যাঁ। তাহারা উহাকে এমনভাবে বানাইল যে, উহার দুই-তৃতীয়াংশ শুকাইয়া এক-তৃতীয়াংশ রহিল। অতঃপর উহা উমর (রাঃ)-এর নিকট আনয়ন করিল। তিনি উহাতে আঙ্গুল দিয়া দেখিলেন, উহা চপ চপ করিতেছে! তিনি বলিলেন, এই রস তো উটের রসের মতোই হইল। তিনি উহা পান করিবার অনুমতি দান করিলেন। উবাদাহ ইবন সামিত (রাঃ) বলেন, আপনি কি উহা হালাল করিয়া দিলেন? উমর (রাঃ) বললেন, না, আল্লাহর কসম! হে আল্লাহ, আমি কখনও ঐ বস্তু হালাল করি নাই যাহা আপনি হারাম করিয়াছেন, আর না এমন বস্তু হারাম করিয়াছি যাহা আপনি হালাল করিয়াছেন।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Mauquf Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1550</td></tr><tr><td>Arabic No</td><td>1550</td></tr><tr><td>Reference</td><td>Book 42 Hadith 1550</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Yahya related to me from Malik from Da'ud ibn al-Husayn that Waqid ibn Amr ibn Sad ibn Muadh informed him from Mahmud ibn Labid al- Ansari that when Umar ibn al-Khattab went to ash-Sham, the people of ash-Sham complained to him about the bad air of their land and its heaviness. They said, "Only this drink helps." Umar said, "Drink this honey preparation." They said, "Honey does not help us." A man from the people of that land said, "Can we give you something of this drink which does not intoxicate?" He said, "Yes." They cooked it until two- thirds of it evaporated and one-third of it remained. Then they brought it to Umar. Umar put his finger in it and then lifted his head and extended it. He said, "This is fruit juice concentrated by boiling. This is like the distillation with which you smear the camel's scabs." Umar ordered them to drink it. Ubada ibn as-Samit said to him, "You have made it halal, by Allah!" Umar said, "No, by Allah! O Allah! I will not make anything halal for them which You have made haram for them! I will not make anything haram for them which You have made halal for them
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Mauquf Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1550</td></tr><tr><td>Arabic No</td><td>1550</td></tr><tr><td>Reference</td><td>Book 42 Hadith 1550</td></tr></tbody></table></div>

## French


<div dir="ltr" lang="fr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Mahmoud Ibn Labib al-Ansari a rapporté: «Une fois que Omar Ibn Al-Khattab fut arrivé à Cham (Damas), les habitants se lamentaient de la grave maladie qui avait frappé la ville, et disaient: «Rien ne peut nous remettre en bon état que cette boisson»; Omar leur dit: «Buvez du miel»; ils repondirent: «Le miel ne nous convient pas»; aussitôt l'un d'eux lui dit: «Veux-tu qu'on te prépare de cette boisson, qui n'enivre pas»? «Oui, répondit Omar». Alors, ils la mirent à bouillir, jusqu'à ce que les deux tiers soient évaporés, ne laissant que le tiers, qu'ils apportèrent à Omar. Il y trempa un doigt, puis en il retira la main, le liquide se dilata Omar dit: «C'est comme la préparation dont on enduit des chameaux», et il leur ordonna de le boire. Alors Oubada Ibn Al-Samett lui dit: «Par Allah! Tu l'as rendu licite»! Et Omar de reprendre: «Non, par Allah! Allah est Grand! Je ne leur rendrai jamais licite ce que Tu as interdit, et je ne leur interdirai pas non plus ce que Tu as rendu licite». (......) 15 - Abdallah Ibn Omar a rapporté que des hommes de l'Iraq lui dirent: «Ô Abou Abdul-Rahman, nous nous achetions des dattes et du raisin, puis nous en fabriquions du vin et nous le vendions». Alors Abdallah Ibn Omar leur dit : «Je prends comme témoins contre vous, Allah, Ses anges et tous ceux qui sont à l'écoute des génies et des hommes, que je ne vous ordonne pas de le vendre, ni de l'acheter, ni de le pressurer, ni de le boire, ni enfin de le donner à boire, car c'est une abomination inventée par Satan». MOUATTAA Au Nom d’Allah Le Clément Le Miséricordieux Livre 43 Le Livre du prix du sang Chapitre I Le prix du sang
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Mauquf Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1550</td></tr><tr><td>Arabic No</td><td>1550</td></tr><tr><td>Reference</td><td>Book 42 Hadith 1550</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepadaku dari Malik dari [Daud bin Al Hushain] dari [Waqid bin 'Amru bin Sa'ad bin Mu'adz] ia mengabarkan kepadanya, dari [Mahmud bin Labid Al Anshari] bahwa ketika [Umar bin Khattab] tiba di Syam, penduduk Syam mengeluh kepadanya tentang wabah penyakit yang semakin dahsyat. Mereka berkata; "Tidak ada yang menyembuhkan kita kecuali dengan minum air ini." Umar berkata; "Minumlah madu ini." Mereka menjawab; "Madu ini tidak manjur." Lalu ada seorang yang terkena wabah berkata; "Bisakah kita membuat dari minuman ini sesuatu yang tidak memabukkan?" 'Umar bin Khattab menjawab; "Ya." Mereka memasaknya hingga habis dua pertiganya dan tersisa sepertiganya, lalu mereka membawanya kepada Umar. Umar memasukkan jarinya dan mengangkat tangannya diikuti dengan lengketannya. Kemudian dia berkata; "Arak ini seperti halnya minyak unta." Maka Umar menyuruh mereka meminumnya." Ubadah bin Shamit berkata kepadanya; "Demi Allah, engkau telah menghalalkannya." Umar menjawab; "Sekali-kali tidak. Demi Allah, Ya Allah, sungguh aku tidak menghalalkan untuk mereka apa yang telah Engkau haramkan dan tidak mengharamkan untuk mereka sesuatu yang telah Engkau halalkan
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Mauquf Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1550</td></tr><tr><td>Arabic No</td><td>1550</td></tr><tr><td>Reference</td><td>Book 42 Hadith 1550</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Lebid oğlu Mahmud el-Ensarî'den: Ömer b. Hattab, Şam'a gelince, Şam halkı oranın havasının ağırlığından ve veba hastalığından şikayet ederek: «Bizi ancak şu içki iyileştiriyor» dediler. Ömer (r.a.): «— Şu bal şerbetini için» deyince, onlar: «— Bal bizi iyileştirmiyor» dediler, içlerinden biri de Hz. Ömer (r.a.)'e: «— Sen bu bal'dan sarhoş etmeyen bir şarap mı yapmamızı istiyorsun?» deyince, Hz. Ömer: «-— Evet» dedi. Onlar da üçte ikisi gidip biri kalıncaya kadar bal kaynatıp Hz. Ömer (r.a.)'e getirdiler Ömer (r.a.) parmağını şerbete batınp çıkarınca şerbet sünmeye başladı. Bunun üzerine Ömer (r.a.): «— Bu kaynatılmış üzüm şırası gibidir. Develere sürülen katran gibi katılaşmış» dedi ve bunu içmelerine müsaade etti. Ubade b. Samit, Ömer (r.a.)'e:» «— Vallahu bunu sen helal kıldın» deyince, Hz. Ömer (r.a.): «— Hayır! Vallahi» dedi. (ve şöyle dua etti): «Ey Allah'ım senin bunlara haram kıldığın hiçbir şeyi ben helal kılmıyorum. Senin helal kıldığın hiçbir şeyi de bunlara haram kılmıyorum.»
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Mauquf Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1550</td></tr><tr><td>Arabic No</td><td>1550</td></tr><tr><td>Reference</td><td>Book 42 Hadith 1550</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حضرت عمر بن خطاب رضی اللہ تعالیٰ عنہ جب شام کی طرف آئے تو لوگوں نے وبا اور آب و ہوا کے بھاری ہونے کا بیان کیا اور کہا بغیر اس شراب کے ہمارا مزاج اچھا نہیں رہتا آپ نے کہاشہد پیو انہوں نے کہا شہد موافق نہیں ایک شخص بولا ہم اسی کو اس طرح تیار کریں جس میں نشہ نہ ہو آپ نے کہا ہاں، انہوں نے اس کو پکایا اتنا کہ ایک تہائی رہ گیا دو تہائی جل گیا اس کو حضرت عمر رضی اللہ تعالیٰ عنہ کے پاس لائے انہوں نے انگلی ڈالی جب وہ چَپ چَپ کرنے لگا آپ نے فرمایا یہ طلا تو اونٹ کے طلا کے مشابہ ہے حضرت عمر رضی اللہ تعالیٰ عنہ نے اس کے پینے کی اجازت دی عبادہ بن صامت نے کہا آپ نے حلال کر دیا حضرت عمر رضی اللہ تعالیٰ عنہ نے کہا نہیں قسم اللہ کی یا اللہ میں نے کبھی اس چیز کو حلال نہیں کیا جس کو تو نے حرام کیا اور نہ حرام کیا جس کو تو نے حلال کیا ۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Mauquf Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1550</td></tr><tr><td>Arabic No</td><td>1550</td></tr><tr><td>Reference</td><td>Book 42 Hadith 1550</td></tr></tbody></table></div>