## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
وَحَدَّثَنِي عَنْ مَالِكٍ، عَنْ يَحْيَى بْنِ سَعِيدٍ، عَنِ الْقَاسِمِ بْنِ مُحَمَّدٍ، أَنَّهُ قَالَ هَلَكَتِ امْرَأَةٌ لِي فَأَتَانِي مُحَمَّدُ بْنُ كَعْبٍ الْقُرَظِيُّ يُعَزِّينِي بِهَا فَقَالَ إِنَّهُ كَانَ فِي بَنِي إِسْرَائِيلَ رَجُلٌ فَقِيهٌ عَالِمٌ عَابِدٌ مُجْتَهِدٌ وَكَانَتْ لَهُ امْرَأَةٌ - وَكَانَ بِهَا مُعْجَبًا وَلَهَا مُحِبًّا - فَمَاتَتْ فَوَجَدَ عَلَيْهَا وَجْدًا شَدِيدًا وَلَقِيَ عَلَيْهَا أَسَفًا حَتَّى خَلاَ فِي بَيْتٍ وَغَلَّقَ عَلَى نَفْسِهِ وَاحْتَجَبَ مِنَ النَّاسِ فَلَمْ يَكُنْ يَدْخُلُ عَلَيْهِ أَحَدٌ وَإِنَّ امْرَأَةً سَمِعَتْ بِهِ فَجَاءَتْهُ فَقَالَتْ إِنَّ لِي إِلَيْهِ حَاجَةً أَسْتَفْتِيهِ فِيهَا لَيْسَ يُجْزِينِي فِيهَا إِلاَّ مُشَافَهَتُهُ فَذَهَبَ النَّاسُ وَلَزِمَتْ بَابَهُ وَقَالَتْ مَا لِي مِنْهُ بُدٌّ ‏.‏ فَقَالَ لَهُ قَائِلٌ إِنَّ هَا هُنَا امْرَأَةً أَرَادَتْ أَنْ تَسْتَفْتِيَكَ وَقَالَتْ إِنْ أَرَدْتُ إِلاَّ مُشَافَهَتَهُ وَقَدْ ذَهَبَ النَّاسُ وَهِيَ لاَ تُفَارِقُ الْبَابَ ‏.‏ فَقَالَ ائْذَنُوا لَهَا ‏.‏ فَدَخَلَتْ عَلَيْهِ فَقَالَتْ إِنِّي جِئْتُكَ أَسْتَفْتِيكَ فِي أَمْرٍ ‏.‏ قَالَ وَمَا هُوَ قَالَتْ إِنِّي اسْتَعَرْتُ مِنْ جَارَةٍ لِي حَلْيًا فَكُنْتُ أَلْبَسُهُ وَأُعِيرُهُ زَمَانًا ثُمَّ إِنَّهُمْ أَرْسَلُوا إِلَىَّ فِيهِ أَفَأُؤَدِّيهِ إِلَيْهِمْ فَقَالَ نَعَمْ وَاللَّهِ ‏.‏ فَقَالَتْ إِنَّهُ قَدْ مَكَثَ عِنْدِي زَمَانًا ‏.‏ فَقَالَ ذَلِكَ أَحَقُّ لِرَدِّكِ إِيَّاهُ إِلَيْهِمْ حِينَ أَعَارُوكِيهِ زَمَانًا ‏.‏ فَقَالَتْ أَىْ يَرْحَمُكَ اللَّهُ أَفَتَأْسَفُ عَلَى مَا أَعَارَكَ اللَّهُ ثُمَّ أَخَذَهُ مِنْكَ وَهُوَ أَحَقُّ بِهِ مِنْكَ فَأَبْصَرَ مَا كَانَ فِيهِ وَنَفَعَهُ اللَّهُ بِقَوْلِهَا ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Maqtu Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>562</td></tr><tr><td>Arabic No</td><td>562</td></tr><tr><td>Reference</td><td>Book 16 Hadith 562</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
রেওয়ায়ত ৪৩. কাসিম ইবনে মুহাম্মদ (রহঃ) বলেনঃ আমার এক স্ত্রীর ইন্তিকাল হয়। মুহাম্মদ ইবন কা'ব কুরাজী (রহঃ) আমাকে তাহার (মৃত্যু) উপলক্ষে সান্তনা দিতে আসিলেন। তিনি বলিলেনঃ বনি ইসরাঈলের এক ব্যক্তি ছিলেন আলিম, ইবাদতগুযার, মুজতাহিদ, শরীয়তের মাসায়েলে পারদর্শী। তাহার এক স্ত্রী ছিল, তাহাদের উভয়ের মধ্যে গভীর ভালবাসা ছিল। (ঘটনাক্রমে) সেই স্ত্রীর মৃত্যু হয়। ইহাতে তিনি খুব মর্মাহত ও ব্যথিত হইলেন। এমন কি তিনি নিজেকে একটি গৃহে অন্তরীণ করিয়া ফেলিলেন এবং লোকের সংশ্ৰব বর্জন করিলেন। অতঃপর কেহ তাহার কাছে যাইত না। জনৈক মহিলা এই বৃত্তান্ত শুনিয়া তাহার নিকট উপস্থিত হইলেন। তিনি বলিলেনঃ তাহার কাছে আমার একটি আবশ্যক রহিয়াছে, যে বিষয়ে আমি তাহাকে জিজ্ঞাসা করিব। তাহার সহিত সামনাসামনি না হইলে আমার আবশ্যক পূর্ণ হইবে না। (তাহার গৃহদ্বার ত্যাগ করিয়া) সব লোক চলিয়া গেল, কিন্তু উক্ত মহিলা তাহার দ্বারে রহিয়াই গেলেন এবং বলিলেনঃ তাহার নিকট আমার প্রয়োজন রহিয়াছে। একজন লোক সেই ব্যক্তির নিকট বলিলঃ এইখানে একজন মহিলা আপনাকে কিছু জিজ্ঞাসা করিতে ইচ্ছুক। তিনি বলিতেছেনঃ আমি তাহার সাক্ষাতপ্রার্থী মাত্র। সকল লোক চলিয়া গিয়াছে কিন্তু তিনি দরজা ছাড়েন না। তিনি বলিলেনঃ তোমরা তাহাকে আসিতে অনুমতি দাও। (অনুমতি পাইয়া সেই মহিলা) প্রবেশ করিলেন এবং বলিলেন, আমি আপনার নিকট একটি বিষয়ে জিজ্ঞাসা করিতে আসিয়াছি। তিনি বলিলেনঃ সেই বিষয়টি কি? (উক্ত মহিলা) বলিলেনঃ আমার প্রতিবেশিনীর নিকট হইতে আমি একটি গহনা ধার নিলাম। অতঃপর আমি উহা পরিধান করিতাম এবং নির্দিষ্ট সময় পর্যন্ত উহা লোককে ধারস্বরূপ দিতাম। অতঃপর তাহারা উহার (ফেরত দেওয়ার) জন্য আমার নিকট লোক পাঠাইলেন। আমি উহা ফেরত দিব কি? তিনি বলিলেনঃ হ্যাঁ, আল্লাহর কসম। মহিলা বলিলেনঃ সেই গহনাটি যে বেশ কিছুদিন আমার কাছে ছিল। তিনি বলিলেনঃ এইজন্য আরও বেশি উচিত যে, তুমি উহা তাহাদের নিকট ফেরত দাও, তাহারা এতকাল পর্যন্ত তোমাকে ধার দিয়াছেন। তখন উক্ত মহিলা বলিলেনঃ ওহে! আপনার প্রতি আল্লাহ দয়া করুন, আপনি আফসোস করিতেছেন এমন বস্তুর উপর যাহা আল্লাহ আপনাকে ধার দিয়াছেন, অতঃপর তিনি উহা গ্রহণ করিয়াছেন আপনার নিকট হইতে। অথচ তিনি উহার হকদার বেশি আপনি অপেক্ষা। তবে ভাবিয়া দেখুন আপনি কোন হালতে আছেন। আল্লাহ এই মহিলার উপদেশ দ্বারা তাহাকে উপকৃত করিলেন।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Maqtu Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>562</td></tr><tr><td>Arabic No</td><td>562</td></tr><tr><td>Reference</td><td>Book 16 Hadith 562</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Yahya related to me from Malik from Yahya ibn Said that al-Qasim ibn Muhammad said, "One of my wives died and Muhammad ibn Kab al Quradhi came to console me about her. He told me of one among the Bani Israil who was a diligent, worshipping, knowing and understanding man who had a wife that he admired and loved, and she died. He grieved over her intensely and lamented her until he withdrew into a house and locked himself in, hidden from everyone, and no-one visited him. A woman heard about him and went to him, saying, 'I need him to give me an opinion. Nothing will satisfy me except what he says about it.' Everyone went away, but she stuck to his door and said, 'I must see him.' Someone said to him, 'There is a woman who wishes to ask your opinion about something,' and she insisted, 'I will only talk to him about it.' When everyone had gone away, and she still had not left his door, he said, 'Let her in.' So she went in and saw him and said, 'I have come to ask your opinion about something.' He said, 'What is it?' She said, 'I borrowed a piece of jewellery from a neighbour of mine, and I have worn it and used it for a long time. Then they sent to me for it. Should I let them have it back?' He said, 'Yes, by Allah.' She said, 'I have had it for a long time.' He said, 'It is more correct for you to return it to them, since they have lent it to you for such a long time.' She said, 'Yes. May Allah have mercy on you. Do you then grieve over what Allah has lent you and then taken from you, when He has a greater right to it than you?' Then he saw the situation he was in, and Allah helped him by her words
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Maqtu Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>562</td></tr><tr><td>Arabic No</td><td>562</td></tr><tr><td>Reference</td><td>Book 16 Hadith 562</td></tr></tbody></table></div>

## French


<div dir="ltr" lang="fr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Al-Kassem Ibn Mouhammad a raconté: «Une de mes femmes mourut; Mouhammad Ibn Ka'b Al-Quorzi vint me consoler et dit: «Parmi les hommes de Bani Israël, il y avait un homme versé dans la religion et un adorateur d'Allah. Il avait une femme dont il était émerveillé et l'aimait à la folie. Cette femme mourut, et son mari éprouva pour elle un grand chagrin et une peine insupportable à un tel point qu'il se renferma chez lui, s'isola des gens et nul n'entrait chez lui. Une femme entendant parler de lui, vint le trouver en disant: «J'ai besoin de lui, afin qu'il me conseille pour une affaire qui me préoccupe et rien ne me convaincra qu'un entretien direct avec lui». Les gens quittèrent la maison de cet homme, quant à la femme, elle resta à sa porte. On fit savoir à l'homme qu'une femme vint le consulter au sujet d'une affaire personnelle et insiste à te voir personnellement; alors que les gens étaient partis, elle resta, ne quittant pas la porte». L'homme dit: «Qu'elle entre». Elle entra chez lui et dit: «Je viens te demander ton avis sur un problème»; il lui demanda: «quel est ce problème»? Elle reprit: «J'avais emprunté de ma voisine des bijoux que je portais souvent et depuis longtemps, même je les prêtais quelquefois. On vient maintenant réclamer les bijoux, devrai-je les leur rendre»? Il rétorqua: «Par Allah! Oui». Elle reprit: «Mais, ça fait longtemps, que je les ai fardés»! Il lui répondit: «Ils ont, maintenant, plus de droit de les réclamer, du moment qu'ils te les ont prêtés depuis un bon temps»! La femme dit alors à l'homme «Que Allah te fasse miséricorde! Tu regrettes d'avoir rendu à Allah, ce qu'Il t'a prêté; puis qu'Il le reprenne, bien qu'Il en ait plus de droit que toi»? L'homme pensa aux paroles de la femme, se rendit compte de son état, et d'Allah qui fit que ces paroles soient d'une grande utilité pour lui». Chapitre XV De ceux qui fouillent les sépulcres
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Maqtu Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>562</td></tr><tr><td>Arabic No</td><td>562</td></tr><tr><td>Reference</td><td>Book 16 Hadith 562</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepadaku dari Malik dari [Yahya bin Said] dari [Al Qasim bin Muhammad] bahwa dia berkata, "Isteriku meninggal dunia. Lalu [Muhammad bin Ka'b Al Qurazhi] berta'ziyah kepadaku dan dia bercerita; 'Dulu di kalangan Bani Isra'il ada seorang laki-laki yang faqih, 'alim, 'abid dan mujtahid. Dia mempunyai seorang isteri yang dia cintai dan dia kagumi. Suatu ketika isterinya meninggal dunia, sehingga dia sangat terpukul dan sedih. Dia mengurung dirinya dan mengasingkan diri dari manusia. Tidak seorangpun yang masuk menemuinya. Lalu ada seorang wanita yang mendengar peristiwa tersebut, lalu wanita itu mendatanginya. Wanita itu berkata, "Aku ada perlu dengannya. Aku ingin meminta fatwanya. Aku tidak akan pernah puas hingga berbicara dengannya secara langsung." Orang-orang pun pergi meninggalkannya, namun dia tetap berada di depan pintu menunggunya dan berkata, "Aku tidak akan pergi sama sekali." Ada seseorang yang berkata pada orang bani Isra'il tersebut; "Di sini ada seorang wanita yang ingin meminta fatwamu, dan dia berkata, "Aku tidak mau kecuali berbicara dengannya secara langsung." Orang-orang telah pergi meninggalkannya, sedang dia tetap tidak meninggalkan pintu rumahmu. Orang tersebut berkata, "Ijinkan dia masuk." Wanita itupun masuk dan berkata, "Aku menemuimu untuk meminta fatwa atas suatu urusan." Orang itupun bertanya, "Apa itu?" Wanita tersebut berkata, "Aku meminjam perhiasan dari tetanggaku. Aku pun mengenakannya dan meminjamnya untuk beberapa waktu. Kemudian mereka mengutus utusan kepadaku untuk memintanya, apakah aku harus mengembalikannya?" Orang tersebut menjawab, "Ya." Wanita itu berkata lagi; "Demi Allah aku telah memakainya beberapa waktu." Orang tersebut berkata, "Begitulah, mereka berhak untuk menariknya kembali darimu setelah meminjamkannya padamu beberapa waktu." Wanita itu berkata, "Baiklah, semoga Allah merahmatimu. Apakah engkau juga tidak rela atas apa yang dipinjamkan Allah padamu, lalu Dia mengambilnya kembali. Padahal Dia lebih berhak atasnya dari dirimu." Maka sadarlah orang tersebut atas apa yang telah terjadi. Allah memberikan manfaat atasnya dengan perkataan wanita tersebut
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Maqtu Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>562</td></tr><tr><td>Arabic No</td><td>562</td></tr><tr><td>Reference</td><td>Book 16 Hadith 562</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Kasım b. Muhammed anlatıyor: Karım vefat etmişti, Muhammed b. Ka'b el-Kurazî ta'ziyeye gelerek bana şunları anlattı: İsrail oğullarından alim, anlayışlı, ibadetine düşkün müctehid bir adam vardı. Bunun bir de hanımı vardı. Birbirlerini çok seviyorlardı. Bir gün kadın vefat etti. Adam çok üzüldü; üzüntüsünden eve çekilip kapıyı kapattı, halktan tamamen uzaklaştı, öyle ki evine hiç kimse girip çıkmaz oldu. Bu durumu duyan bir kadın gelerek kapıcıya: «— Ona işim düştü, bir fetva soracağım, ancak mutlaka kendisiyle görüşmem lazım! dedi. Kapıya gelen herkes dönüp gittiği halde, kadın kapıdan ayrılmıyor ve: «— Mutlaka kendisiyle görüşmem lazım!» diye diretiyordu. Kapıcı durumu içerdeki zata bildirerek: «— Burada bir kadın var, sizden bir şey sormak istiyor ve mutlaka görüşmem şart diyor. Herkes dağıldığı halde o hala kapıdan ayrılmadı.» dedi. Bunun üzerine hanımı vefat eden zat: «— Alın içeri!» diye emir verdi. Kadın içeri girdi. «— Ben size bir konuda bir şey danışmak için geldim!» diye söze başladı. Adam: «— Nedir o mesele?» dedi. Kadın anlattı: «— Ben komşularımdan bir kadından (ödünç olarak) bir süs eşyası almıştım. Bunu bazen giyer, bazen de ödünç olarak başkalarına verirdim. Bir zaman sonra sahibi bu zinet eşyasını geri veı memi istedi. Geri vereyim mi?» Alim zat: «— Evet mutlaka vermelisin!» diye cevap verince kadın: «— Ama bu bende hayli zaman kaldı!» diye mukabele etti Adam: «— Aldığın gibi vermen de lazımdır.» dedi, kesti attı. Kadın: «— Mademki öyle, Allahu Teala'nın sana ödünç olarak veripde, sonra haklı olarak geri aldığı şeye neden böyle üzülüyorsun?» diyerek asıl maksadını belirtti. Alim zat durumdan ibret alarak kadın vasıtasiyle doğruyu gördü
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Maqtu Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>562</td></tr><tr><td>Arabic No</td><td>562</td></tr><tr><td>Reference</td><td>Book 16 Hadith 562</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
قاسم بن محمد سے روایت ہے کہ میری زوجہ مر گئی سو آئے محمد بن کعب قرظی تعزیت دینے مجھ کو اور کہا کہ بنی اسرائیل میں ایک شخص فقیہ عالم عابد مجتہد تھا اور اس کی ایک بیوی تھی جس پر وہ نہایت فریفتہ تھا اور اس کو بہت چاہتا تھا اتفاق سے وہ عورت مر گئی تو اس شخص کو نہایت رنج ہوا اور بڑا افسوس ہوا اور وہ ایک گھر میں دروازہ بند کر کے بیٹھ رہا اور لوگوں سے ملاقات چھوڑ دی تو اس کے پاس کوئی نہ جاتا تھا ایک عورت نے یہ قصہ سنا اور اس کے دروازے پر جا کر کہا کہ مجھ کو ایک مسئلہ پوچھنا ہے میں اسی سے پوچھوں گی بغیر اس سے ملے ہوئے یہ کام نہیں ہو سکتا تو اور جتنے لوگ آئے تھے وہ چلے گئے اور وہ عورت دروازے پر جمی رہی اور کہا کہ بغیر اس سے طے کئے کوئی علاج نہیں ہے سو ایک شخص نے اندر جا کر اس کو اطلاع دی اور بیان کیا کہ ایک عورت مسئلہ پوچھنے کو تم سے آئی ہے اور وہ کہتی ہے کہ میں تم سے ملنا چاہتی ہوں تو سب لوگ چلے گئے مگر وہ عورت دروازہ چھوڑ کر نہیں جاتی تب اس شخص نے کہا اچھا اس کو آنے دو پس آئی وہ عورت اس کے پاس اور کہا کہ میں ایک مسئلہ تجھ سے پوچھنے کو آئی ہوں وہ بولا کیا مسئلہ ہے اس عورت نے کہا میں نے اپنے ہمسایہ میں ایک عورت سے کچھ زیور مانگ کر لیا تھا تو میں نے ایک مدت تک اس کو پہنا اور لوگوں کو مانگنے پر بھی دیا اب اس عورت نے وہ زیور مانگ بھیجا ہے کیا میں اسے پھر واپس دے دوں اس شخص نے کہا ہاں قسم اللہ کی واپس دیدے عورت نے کہا کہ وہ زیور ایک مدت تک میرے پاس رہا ہے اس شخص نے کہا کہ اس سبب سے اور زیادہ تجھے واپس دینا ضروری ہے کیونکہ ایک زمانے تک تجھے اس نے مانگنے پر دیا عورت بولی اے فلانے اللہ تجھ پر رحم کرے تو کیوں افسوس کرتا ہے اس چیز پر جو اللہ جل جلالہ نے تجھے مستعار دی تھی پھر تجھ سے لے لی اللہ جل جلالہ زیادہ حقدار ہے تجھ سے جب اس شخص نے غور کیا تو عورت کی بات سے اللہ تعالیٰ نے اس کو نفع دیا۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Maqtu Sahih</td><td>Salim al-Hilali</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>562</td></tr><tr><td>Arabic No</td><td>562</td></tr><tr><td>Reference</td><td>Book 16 Hadith 562</td></tr></tbody></table></div>