## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا مُوسَى بْنُ إِسْمَاعِيلَ، حَدَّثَنَا حَمَّادٌ، أَخْبَرَنَا يَعْلَى بْنُ عَطَاءٍ، عَنْ أَبِي هَمَّامٍ عَبْدِ اللَّهِ بْنِ يَسَارٍ، أَنَّ أَبَا عَبْدِ الرَّحْمَنِ الْفِهْرِيَّ، قَالَ شَهِدْتُ مَعَ رَسُولِ اللَّهِ صلى الله عليه وسلم حُنَيْنًا فَسِرْنَا فِي يَوْمٍ قَائِظٍ شَدِيدِ الْحَرِّ فَنَزَلْنَا تَحْتَ ظِلِّ الشَّجَرَةِ فَلَمَّا زَالَتِ الشَّمْسُ لَبِسْتُ لأْمَتِي وَرَكِبْتُ فَرَسِي فَأَتَيْتُ رَسُولَ اللَّهِ صلى الله عليه وسلم وَهُوَ فِي فُسْطَاطِهِ فَقُلْتُ السَّلاَمُ عَلَيْكَ يَا رَسُولَ اللَّهِ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ قَدْ حَانَ الرَّوَاحُ فَقَالَ ‏"‏ أَجَلْ ‏"‏ ‏.‏ ثُمَّ قَالَ ‏"‏ يَا بِلاَلُ قُمْ ‏"‏ ‏.‏ فَثَارَ مِنْ تَحْتِ سَمُرَةٍ كَأَنَّ ظِلَّهُ ظِلُّ طَائِرٍ فَقَالَ لَبَّيْكَ وَسَعْدَيْكَ وَأَنَا فِدَاؤُكَ ‏.‏ فَقَالَ ‏"‏ أَسْرِجْ لِي الْفَرَسَ ‏"‏ ‏.‏ فَأَخْرَجَ سَرْجًا دَفَّتَاهُ مِنْ لِيفٍ لَيْسَ فِيهِ أَشَرٌ وَلاَ بَطَرٌ فَرَكِبَ وَرَكِبْنَا ‏.‏ وَسَاقَ الْحَدِيثَ ‏.‏ قَالَ أَبُو دَاوُدَ أَبُو عَبْدِ الرَّحْمَنِ الْفِهْرِيُّ لَيْسَ لَهُ إِلاَّ هَذَا الْحَدِيثُ وَهُوَ حَدِيثٌ نَبِيلٌ جَاءَ بِهِ حَمَّادُ بْنُ سَلَمَةَ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Hasan</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Hasan Lighairihi</td><td>Shuaib Al Arnaut</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5233</td></tr><tr><td>Arabic No</td><td>5233</td></tr><tr><td>Reference</td><td>Book 43 Hadith 461</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
মূসা ইবন ইসমাঈল (রহঃ) ..... আবূ আবদুর রহমান ফিহরী (রাঃ) থেকে বর্ণিত। তিনি বলেনঃ আমি হুনায়নের যুদ্ধের সময় রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর সংগে ছিলাম। আমরা এমন এক সময় সফর করি, যখন ছিল প্রচন্ড গরম। ফলে, আমরা একটি গাছের নীচে অবস্থান করি। এরপর সূর্য যখন পশ্চিম আকাশে ঢলে পড়ে, তখন আমি আমার লৌহবর্ম পরে, ঘোড়ায় চড়ে রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর কাছে আসি। তখন তিনি তাঁর তাঁবুর মাঝে অবস্থান করছিলেন। আমি বলিঃ ইয়া রাসূলাল্লাহ! আপনার প্রতি সালাম রহমত ও বরকত নাযিল হোক, এখন সফরের সময় উপস্থিত। তখন নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেনঃ হ্যাঁ! এরপর তিনি বলেনঃ হে বিলাল! উঠ! এ সময় বিলাল (রাঃ) একটা গাছের নীচ থেকে লাফিয়ে বেরিয়ে আসেন এবং তার শরীরের ছায়া ছিল পাখীর ন্যায়। বিলাল (রাঃ) বলেনঃ লাব্বায়ক অর্থাৎ আমি হাযির, সব ধরনের খিদমতের জন্য প্রস্তুত এবং আপনার জন্য উৎসর্গীত। তখন নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেনঃ আমার ঘোড়ার পিঠে জিন বাঁধ। এরপর বিলাল (রাঃ) জিন বের করেন, যার দু'পাশ খেজুরের পাতায় ভরা ছিল এবং তাতে অহংকার প্রকাশের মত কিছুই ছিল না। তারপর নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম সওয়ার হলে, আমরাও আমাদের বাহনে সওয়ার হই।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Hasan</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Hasan Lighairihi</td><td>Shuaib Al Arnaut</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5233</td></tr><tr><td>Arabic No</td><td>5233</td></tr><tr><td>Reference</td><td>Book 43 Hadith 461</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated AbuAbdurRahman al-Fihri: I was present with the Messenger of Allah at the battle of Hunayn. We travelled on a hot day when the heat was extreme. We halted under the shade of a tree. When the sun passed the meridian, I put on my coat of mail and rode on my horse. I came to the Messenger of Allah (ﷺ) who was in a tent. I said: Peace, Allah's mercy and His blessings be upon you! The time of departure has come. He said: Yes. He then said: Rise, Bilal. He jumped out from beneath a gum-acacia tree and its shade was like that of a bird. He said: I am at your service and at your pleasure, and I make myself a sacrifice for you. He said: Put the saddle on the horse for me. He then took out a saddle, both sides of which were stuffed with palm-leaves; it showed no arrogance and pride. So he rode and we also rode. He then mentioned the rest of the tradition. Abu Dawud said: Abu 'Abd al-Rahman al-Fihri did not transmit any tradition except this one. This is a tradition of an expert transmitted by Hammad b. Salamah
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Hasan</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Hasan Lighairihi</td><td>Shuaib Al Arnaut</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5233</td></tr><tr><td>Arabic No</td><td>5233</td></tr><tr><td>Reference</td><td>Book 43 Hadith 461</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Musa bin Isma'il] berkata, telah menceritakan kepada kami [Hammad] berkata, telah mengabarkan kepada kami [Ya'la bin Atha] dari [Abu Hammam Abdullah bin Yasar] bahwa [Abu 'Abdurrahman Al Fihri] berkata, "Aku pernah mengikuti perang Hunanin bersama Rasulullah shallallahu 'alaihi wasallam, lalu kami berjalan di hari yang sangat panas. Kemudian kami singgah di bawah pohon yang ridang, saat matahari telah condong ke arah barat aku segera mengenakan peralatan perangku dan naik ke atas kuda. Setelah itu aku mendatangi Rasulullah shallallahu 'alaihi wasallam di dalam kemahnya. Aku katakan kepada beliau, "Wahai Rasulullah, Assalamu Alaika wa rahmatullahi wa Barakatuh. Sesungguhnya waktu berangkat telah tiba." Beliau menjawab, "Benar." Setelah itu beliau berkata kepada Bilal: "Wahai Bilal, segeralah bangun." Maka Bilal pun bangun dari bawah pohon Samurah, seakan-akan bayangannya seperti bayangan burung. Bilal menjawab, "Aku penuhi panggilanmu dengan senang hati, dan aku sebagai tebusanmu." Rasulullah kemudian bersabda: "Pasanglah pelana kudaku." Bilal lalu mengeluarkan mngeluarkan pelana yang terbuat dari tumpukan rerumputan yang tidak ada bekas keburukan dan kesombongan. Beliau kemudian menaiki tungganyanya dan kami mengikutinya…. lalu ia menyebutkan hadits selengkapnya." Abu Dawud berkata, "Abu 'Abdurrahman Al Fihri tidak mempunyai hadits kecuali hanya ini, dan ini adalah hadits yang bagus; diriwayatkan oleh Hammad bin Salamah
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Hasan</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Hasan Lighairihi</td><td>Shuaib Al Arnaut</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5233</td></tr><tr><td>Arabic No</td><td>5233</td></tr><tr><td>Reference</td><td>Book 43 Hadith 461</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ebû Hemmâm Abdillah b. Yesar'den (rivayet edildiğine göre); Ebu Abdurrahman el-Fihrî şöyle demiştir: "Rasûlullah (s.a.v.)'le birlikte Huneyn'de bulundum. Şiddetli sıcağın iyice kızıştığı bir günde yolculuk ediyorduk. (Bir ara) bir ağacın gölgesi altına indik. Güneş (batıya) kayınca harp aletlerimi kuşandım ve atıma bindim. (Doğru) çadırında bulunan Rasûlullah (s.a.v.)'in yanına geldim: "Esselâmu aleyküm ya Rasûlullah ve rahmetullahi ve berekâtühu, (savaş için) öğle sonu yola çıkma vakti geldi dedim.Evet, dedi, sonra (Hz. Bilâl'e): Ey Bilal! haydi kalk, buyurdu. Bunun üzerine (Hz. Bilal) hemen: "Lebbeyk ve sadeyk ve ene fadâuk (:Buyur ben sana feda olayım)" diyerek ağacın altından (hızla) sıçradı. Sanki gölgesi bir kuş gölgesi gibi (küçük ve ince) idi. (Hz. Nebi de:) Bana atımı eğerle, buyurdu. (Hz. Bilal) hemen iki tarafı lifden olan böbürlenme ve gösterişten uzak bir eğer çıkardı (ve atı eğerledi). Hz. Peygamber de (ata) bindi. Biz de (atlarımıza) bindik (ve yol'a koyulduk). Sonra Ebu Abdurrahman hadisi (sonuna kadar) rivayet etti. Ebû Davud dedi ki: Ebu Abdurrahman el-Fihrî'nin bu hadisten başka (rivayet ettiği) bir hadis yoktur. Bu hadis (kendi sahasında) çok mahir (bir kimse) olan (Yala b. Atâ)nındır. Onu (kendisinden talebesi) Hammâd b. Seleme rivayet etti
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Hasan</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Hasan Lighairihi</td><td>Shuaib Al Arnaut</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5233</td></tr><tr><td>Arabic No</td><td>5233</td></tr><tr><td>Reference</td><td>Book 43 Hadith 461</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ابوعبدالرحمٰن فہری کہتے ہیں کہ میں غزوہ حنین میں رسول اللہ صلی اللہ علیہ وسلم کے ساتھ شریک تھا، ہم سخت گرمی کے دن میں چلے، پھر ایک درخت کے سایہ میں اترے، جب سورج ڈھل گیا تو میں نے اپنی زرہ پہنی اور اپنے گھوڑے پر سوار ہو کر رسول اللہ صلی اللہ علیہ وسلم کے پاس آیا، اس وقت آپ اپنے خیمہ میں تھے، میں نے کہا: «السلام عليك يا رسول الله ورحمة الله وبركاته» کوچ کا وقت ہو چکا ہے، آپ نے فرمایا: ہاں، پھر آپ نے فرمایا: اے بلال! اٹھو، یہ سنتے ہی بلال ایک درخت کے نیچے سے اچھل کر نکلے ان کا سایہ گویا چڑے کے سایہ جیسا تھا ۱؎ انہوں نے کہا: «لبيك وسعديك وأنا فداؤك» میں حاضر ہوں، حکم فرمائیے، میں آپ پر فدا ہوں آپ نے فرمایا: میرے گھوڑے پر زین کس دو تو انہوں نے زین اٹھایا جس کے دونوں کنارے خرما کے پوست کے تھے، نہ ان میں تکبر کی کوئی بات تھی نہ غرور کی ۲؎ پھر آپ سوار ہوئے اور ہم بھی سوار ہوئے ( اور چل پڑے ) پھر راوی نے پوری حدیث بیان کی۔ ابوداؤد کہتے ہیں: عبدالرحمٰن فہری سے اس حدیث کے علاوہ اور کوئی حدیث مروی نہیں ہے اور یہ ایک عمدہ اور قابل قدر حدیث ہے جسے حماد بن سلمہ نے بیان کیا ہے۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Hasan</td><td>Al-Albani</td></tr><tr><td>Hasan</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Hasan Lighairihi</td><td>Shuaib Al Arnaut</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5233</td></tr><tr><td>Arabic No</td><td>5233</td></tr><tr><td>Reference</td><td>Book 43 Hadith 461</td></tr></tbody></table></div>