## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا أَبُو الْوَلِيدِ الطَّيَالِسِيُّ، حَدَّثَنَا شُعْبَةُ، عَنِ الأَعْمَشِ، عَنْ أَبِي صَالِحٍ، عَنْ أَبِي هُرَيْرَةَ، قَالَ قَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏ "‏ لأَنْ يَمْتَلِئَ جَوْفُ أَحَدِكُمْ قَيْحًا خَيْرٌ لَهُ مِنْ أَنْ يَمْتَلِئَ شِعْرًا ‏"‏ ‏.‏ قَالَ أَبُو عَلِيٍّ بَلَغَنِي عَنْ أَبِي عُبَيْدٍ أَنَّهُ قَالَ وَجْهُهُ أَنْ يَمْتَلِئَ قَلْبُهُ حَتَّى يَشْغَلَهُ عَنِ الْقُرْآنِ وَذِكْرِ اللَّهِ فَإِذَا كَانَ الْقُرْآنُ وَالْعِلْمُ الْغَالِبُ فَلَيْسَ جَوْفُ هَذَا عِنْدَنَا مُمْتَلِئًا مِنَ الشِّعْرِ وَإِنَّ مِنَ الْبَيَانِ لَسِحْرًا ‏.‏ قَالَ كَأَنَّ الْمَعْنَى أَنْ يَبْلُغَ مِنْ بَيَانِهِ أَنْ يَمْدَحَ الإِنْسَانَ فَيَصْدُقَ فِيهِ حَتَّى يَصْرِفَ الْقُلُوبَ إِلَى قَوْلِهِ ثُمَّ يَذُمَّهُ فَيَصْدُقَ فِيهِ حَتَّى يَصْرِفَ الْقُلُوبَ إِلَى قَوْلِهِ الآخَرِ فَكَأَنَّهُ سَحَرَ السَّامِعِينَ بِذَلِكَ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5009</td></tr><tr><td>Arabic No</td><td>5009</td></tr><tr><td>Reference</td><td>Book 43 Hadith 237</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
আবূ ওয়ালীদ তায়ালিনী (রহঃ) ..... আবূ হুরায়রা (রাঃ) থেকে বর্ণিত। তিনি বলেনঃ রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেছেনঃ তোমাদের কারো পেট বমির দ্বারা পূর্ণ হওয়া, কবিতার দ্বারা পূর্ণ হওয়ার চাইতে উত্তম। (অর্থাৎ এমন কবিতা পাঠ না করা, যাতে ঈমান নষ্ট নয়।) রাবী আবূ আলী (রহঃ) বলেনঃ আবূ উবায়দ (রহঃ) থেকে জানতে পেরেছি, যিনি বলেছেনঃ এ হাদীছের মর্ম হলোঃ সে ব্যক্তি কুরআন-হাদীছ ও আল্লাহ্‌র যিকির বাদ দিয়ে কেবল কবিতার চর্চায় লিপ্ত থাকে। যদি সে ব্যক্তি কুরআন ও দীনি ইলম অধিক শিক্ষা করে এবং কবিতার চর্চা কম করে, তবে সে ব্যক্তি এর অন্তর্ভুক্ত নয়। আর ঐ উক্তি যে, 'কোন কোন বর্ণনায় যাদুকরী প্রভাব আছে', এর অর্থ হলোঃ যে ব্যক্তির বর্ণনা এ স্তরে পৌছবে যে, সে কারো প্রশংসা এতো বাড়িয়ে ও সুন্দরভাবে করে, যাতে লোকদের অন্তর তার প্রতি আকৃষ্ট হয়। আর যদি সে তার বদনাম করে, তখন লোকদের অন্তরে তার প্রতি ঘৃণার সৃষ্টি হয়। কাজেই, এ ধরনের বর্ণনার মধ্যে যাদুকরী প্রভাব থাকে।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5009</td></tr><tr><td>Arabic No</td><td>5009</td></tr><tr><td>Reference</td><td>Book 43 Hadith 237</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Abu Hurairah reported the Messenger of Allah (May peace be upon him) as saying :it is better for a man’s belly to be full of pus than to be full of poetry. Abu ‘Ali said : I have been told that Abu ‘Ubaid said : It means that his heart is full of poetry so much so that it makes him neglectful of the Quran and remembrance of Allah. If the Quran and the knowledge (of religion) are dominant, the belly will not be full of poetry in our opinion. Some eloquent speech is magic. It means that a man expresses his eloquence by praising another man, and he speaks the truth about him so much so that he attracts the hearts to his speech. He then condemns him and speaks the truth about him so much so that he attracts the hearts to another of his speech, as if he spelled the audience by it
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5009</td></tr><tr><td>Arabic No</td><td>5009</td></tr><tr><td>Reference</td><td>Book 43 Hadith 237</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Abul Walid Ath Thayalisi] berkata, telah menceritakan kepada kami [Syu'bah] dari [Al A'masy] dari [Abu Shalih] dari [Abu Hurairah] ia berkata, "Rasulullah shallallahu 'alaihi wasallam bersabda: "Sekiranya mulut kalian penuh dengan muntahan, maka itu lebih baik dari pada penuh dengan syair." Abu Ali berkata, "Telah sampai kepadaku dari Abu Ubaid, bahwa ia berkata, "Maksudnya adalah, hendaknya hatinya penuh dan tersibukkan dengan bacaan Al-Qur'an dan dzikir kepada Allah. Sebab menurut kami, jika hati itu terisi penuh dengan Al-Qur'an dan ilmu, maka kerongkongannya tidak akan terisi dengan syair. Dan sesungguhnya dalam kefasihan itu terdapat sihir. Ia berkata, "Seakan-akan makna dari 'penjelasan yang berlebihan' itu adalah dengan jalan memuji manusia dan meyakinkannya hingga hati orang lain berpaling kepada ucapannya. Lalu ia mencela orang lain dan meyakinkannya sehingga hati orang lain condong kepada perkataannya. Seolah-olah ia menyihir para pendengarnya dengan kefasihannya tersebut
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5009</td></tr><tr><td>Arabic No</td><td>5009</td></tr><tr><td>Reference</td><td>Book 43 Hadith 237</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Hz. Ebu Hureyre'den (rivayet edildiğine göre), RasûlulIah (s.a.v.) şöyle buyurmuştur: "Birinizin içinin irin ile dolması şiirle dolmasından daha hayırlıdır." (Musannif Ehıı Davud'un arkadaşlarından) Ebu Ali dedi ki: Bana ula­şan haberlere göfp Ebu Ubeyd şöyle demiştir: (Bu hadisin) manası (şudur: Kişinin kafasında) Kur’an(-ı Kerim) ve ilim daha fazla olunca bize göre bu kişinin içi şiir/e dolu değildir. "Mu­hakkak ki sözlerin bazıları sihir (gibi)dir." Sanki (bu cümle) deki mana şöyledir: (Bir kimsenin) diğer bir insanı övmekteki ifadesi o hale erişir ki (dinleyen kimse) onu doğrular nihayet (bu konuşan kimse) kalpleri kendi sözüne çevirir. Sonra (bu adam) daha önce övmüş olduğu kimseyi kötüler nihayet (bu sefer de yine bütün) kalpleri bu seferki sözüne çevirir (inan­dırır). Sanki bu haliyle dinleyenleri büyülemiş olur
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5009</td></tr><tr><td>Arabic No</td><td>5009</td></tr><tr><td>Reference</td><td>Book 43 Hadith 237</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ابوہریرہ رضی اللہ عنہ کہتے ہیں کہ رسول اللہ صلی اللہ علیہ وسلم نے فرمایا: تم میں سے کسی کے لیے اپنا پیٹ پیپ سے بھر لینا بہتر ہے اس بات سے کہ وہ شعر سے بھرے، ابوعلی کہتے ہیں: مجھے ابو عبید سے یہ بات پہنچی کہ انہوں نے کہا: اس کی شکل ( شعر سے پیٹ بھرنے کی ) یہ ہے کہ اس کا دل بھر جائے یہاں تک کہ وہ اسے قرآن، اور اللہ کے ذکر سے غافل کر دے اور جب قرآن اور علم اس پر چھایا ہوا ہو تو اس کا پیٹ ہمارے نزدیک شعر سے بھرا ہوا نہیں ہے ( اور آپ نے فرمایا ) بعض تقریریں جادو ہوتی ہیں یعنی ان میں سحر کی سی تاثیر ہوتی ہے، وہ کہتے ہیں: اس کے معنی گویا یہ ہیں کہ وہ اپنی تقریر میں اس مقام کو پہنچ جائے کہ وہ انسان کی تعریف کرے اور سچی بات ( تعریف میں ) کہے یہاں تک کہ دلوں کو اپنی بات کی طرف موڑ لے پھر اس کی مذمت کرے اور اس میں بھی سچی بات کہے، یہاں تک کہ دلوں کو اپنی دوسری بات جو پہلی بات کے مخالف ہو کی طرف موڑ دے، تو گویا اس نے سامعین کو اس کے ذریعہ سے مسحور کر دیا ۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5009</td></tr><tr><td>Arabic No</td><td>5009</td></tr><tr><td>Reference</td><td>Book 43 Hadith 237</td></tr></tbody></table></div>