## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا أَحْمَدُ بْنُ صَالِحٍ، حَدَّثَنَا عَبْدُ اللَّهِ بْنُ وَهْبٍ، أَخْبَرَنِي يُونُسُ بْنُ يَزِيدَ، عَنِ ابْنِ شِهَابٍ، حَدَّثَنِي عَبَّادُ بْنُ زِيَادٍ، أَنَّ عُرْوَةَ بْنَ الْمُغِيرَةِ بْنِ شُعْبَةَ، أَخْبَرَهُ أَنَّهُ، سَمِعَ أَبَاهُ الْمُغِيرَةَ، يَقُولُ عَدَلَ رَسُولُ اللَّهِ صلى الله عليه وسلم وَأَنَا مَعَهُ فِي غَزْوَةِ تَبُوكَ قَبْلَ الْفَجْرِ فَعَدَلْتُ مَعَهُ فَأَنَاخَ النَّبِيُّ صلى الله عليه وسلم فَتَبَرَّزَ ثُمَّ جَاءَ فَسَكَبْتُ عَلَى يَدِهِ مِنَ الإِدَاوَةِ فَغَسَلَ كَفَّيْهِ ثُمَّ غَسَلَ وَجْهَهُ ثُمَّ حَسَرَ عَنْ ذِرَاعَيْهِ فَضَاقَ كُمَّا جُبَّتِهِ فَأَدْخَلَ يَدَيْهِ فَأَخْرَجَهُمَا مِنْ تَحْتِ الْجُبَّةِ فَغَسَلَهُمَا إِلَى الْمِرْفَقِ وَمَسَحَ بِرَأْسِهِ ثُمَّ تَوَضَّأَ عَلَى خُفَّيْهِ ثُمَّ رَكِبَ فَأَقْبَلْنَا نَسِيرُ حَتَّى نَجِدَ النَّاسَ فِي الصَّلاَةِ قَدْ قَدَّمُوا عَبْدَ الرَّحْمَنِ بْنَ عَوْفٍ فَصَلَّى بِهِمْ حِينَ كَانَ وَقْتُ الصَّلاَةِ وَوَجَدْنَا عَبْدَ الرَّحْمَنِ وَقَدْ رَكَعَ بِهِمْ رَكْعَةً مِنْ صَلاَةِ الْفَجْرِ فَقَامَ رَسُولُ اللَّهِ صلى الله عليه وسلم فَصَفَّ مَعَ الْمُسْلِمِينَ فَصَلَّى وَرَاءَ عَبْدِ الرَّحْمَنِ بْنِ عَوْفٍ الرَّكْعَةَ الثَّانِيَةَ ثُمَّ سَلَّمَ عَبْدُ الرَّحْمَنِ فَقَامَ رَسُولُ اللَّهِ صلى الله عليه وسلم فِي صَلاَتِهِ ‏.‏ فَفَزِعَ الْمُسْلِمُونَ فَأَكْثَرُوا التَّسْبِيحَ لأَنَّهُمْ سَبَقُوا النَّبِيَّ صلى الله عليه وسلم بِالصَّلاَةِ فَلَمَّا سَلَّمَ رَسُولُ اللَّهِ صلى الله عليه وسلم قَالَ لَهُمْ ‏"‏ قَدْ أَصَبْتُمْ ‏"‏ ‏.‏ أَوْ ‏"‏ قَدْ أَحْسَنْتُمْ ‏"‏ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>149</td></tr><tr><td>Arabic No</td><td>149</td></tr><tr><td>Reference</td><td>Book 1 Hadith 149</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
আহমাদ ইবনু সালেহ্ ..... মুগীরা (রাঃ) হতে বর্ণিত। তিনি বলেন, তাবূকের যুদ্ধের সময় একদিন রাসূলুল্লাহ্ সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম ফজরের নামাযের পূর্বে স্থানান্তরে গমন করলেন এবং এ সময় আমিও তাঁর সাথে ছিলাম। অতঃপর নবী সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম তাঁর উষ্ট্রী বসালেন এবং মলমূত্র ত্যাগ করলেন। তা সমাপনান্তে ফিরে এলে আমি পাত্র হতে তাঁর হাতে পানি ঢেলে দেই। তিনি উভয় হাতের কব্জি পর্যন্ত এবং মুখমন্ডল ধৌত করেন। অতঃপর তিনি তার জুব্বার আস্তিন উপরের দিকে উঠাতে চেষ্টা করেন, কিন্তু তা সংকীর্ণ হওয়ায় তিনি তাঁর হাত তার জুব্বার আস্তিনের ভিতর হতে বের করে উভয় হাতের কনুই পর্যন্ত ধৌত করলেন। অতঃপর মাথা মাসেহ্ করলেন, অতঃপর মোজার উপর মাসেহ্ করলেন এবং উটের উপর আরোহণ করলেন। অতঃপর আমরা সেখান থেকে প্রত্যাবর্তন করে সকলকে নামাযে রত পেলাম। তারা আব্দুর রহমান ইবনু আওফ (রাঃ)-কে ইমাম নিযুক্ত করেছে। আব্দুর রহমান ইবনু আওফ (রাঃ) নামাযের সময় হওয়ায় তাদেরকে নিয়ে নামায আরম্ভ করেন এবং আমরা তাকে এমন অবস্থায় পাই যে, তিনি ফজরের নামাযের এক রাকাত (তখন) শেষ করেছেন। অতঃপর রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম মুসলিমদের সাথে কাতারে দাঁড়িয়ে আবদুর রহমান (রাঃ) এর পিছনে নামাযের দ্বিতীয় রাকাতে আদায় করলেন। আবদুর রহমান (রাঃ) নামাযের সালাম ফিরালে রাসূলুল্লাহ্ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম তাঁর বাকী নামায আদায়ের জন্য দন্ডায়মান হন। এতদ্দর্শনে সমবেত মুসলিমরা ভীত-সন্ত্রস্ত হয়ে অধিক পরিমাণে ‘সুবাহানাল্লাহ’ পাঠ করতে থাকে। কেননা তারা নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর জন্য অপেক্ষা না করে নামায আরম্ভ করে দিয়েছিল। অতঃপর রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম নামায সমাপনান্তে সাহাবীদের লক্ষ্য করে বলেনঃ তোমরা যথা সময়ে নামায আদায় করে ঠিকই করেছ অথবা উত্তম কাজই করেছ - (বুখারী, মুসলিম, নাসাঈ, ইবনু মাজাহ, তিরমিযী)।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>149</td></tr><tr><td>Arabic No</td><td>149</td></tr><tr><td>Reference</td><td>Book 1 Hadith 149</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Al-Mughirah b. Shu’bah reported:I was in the company of the Messenger of Allah (ﷺ) in the expedition of Tabuk. He abandoned the main road before the dawn prayer, and I also did the same along with him. The Prophet (ﷺ) made his camel kneel down and (went to ) relieve himself. He then came back and I poured water upon his hands from the skin-vessel. He then washed his hands and face. He tried to get his forearms out (of the gown), but the sleeves of the gown were too narrow, so he entered back both his hands, and brought them out from beneath the gown. He washed his forearms up to the elbows and wiped his head and wiped over his socks.80 He then mounted (his camel) and we began to proceed until we found people offering the prayer. They brought forward ‘Abd al-Rahman b. ‘Awf who was leading them in prayer. The Prophet(ﷺ) stood in the row side by side with other Muslims. He performed the second rak’ah of the prayer behind ‘Abd al-Rahman b. ‘Awf. Then ‘Abd al-Rahman uttered salutation. The Prophet(ﷺ) stood to perform the remaining rak’ah of the prayer. The Muslims were alarmed. They began to utter tasbih (Subhan Allah) presuming that they had offered prayer before the Prophet (ﷺ) had done. When he uttered the salutation (i.e. finished his prayer), he said: You were right, or (he said) you did well
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>149</td></tr><tr><td>Arabic No</td><td>149</td></tr><tr><td>Reference</td><td>Book 1 Hadith 149</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Ahmad bin Shalih] telah menceritakan kepada kami [Abdullah bin Wahb] telah mengabarkan kepada kami [Yunus bin Yazid] dari [Ibnu Syihab] telah menceritakan kepada saya ['Abbad bin Ziyad] bahwasanya ['Urwah bin Al-Mughirah bin Syu'bah] telah mengabarkan kepadanya, bahwa dia pernah mendengar [Ayahnya, Al-Mughirah] berkata; dia berkata, Pada waktu perang Tabuk sebelum fajar Rasulullah shallallahu 'alaihi wasallam pernah berjalan menyimpang dari jalan (para sahabat), maka aku turut menyimpang dari jalan menyertai beliau. Lalu Nabi shallallahu 'alaihi wasallam menderumkan kendaraan beliau, lalu beliau buang hajat. Setelah selesai, aku tuangkan ke tangan beliau air dari bejana. Beliau membasuh kedua telapak tangannya lalu mencuci muka. Setelah itu beliau menyingsingkan kedua lengan jubah beliau yang terbuka dan terasa sempit, maka beliau memasukkan keduanya kembali kemudian mengeluarkan keduanya dari bawah jubah, lantas beliau membasuh kedua tangan sampai ke siku, dan mengusap kepala, lalu mengusap bagian atas khuf beliau. Setelah itu beliau naik kendaraan, dan kami meneruskan perjalanan, hingga kami mendapati orang-orang (para sahabat) tengah mengerjakan shalat, mereka angkat Abdurrahman bin Auf sebagai imam, dia mengerjakan shalat bersama mereka pada awal waktunya dan kami mendapatkan Abdurrahman bin Auf telah mengerjakan satu rakaat Shalat Shubuh bersama mereka. Maka datanglah Rasulullah shallallahu 'alaihi wasallam dan masuk ke dalam shaf bersama kaum Muslimin dan mengerjakan shalat di belakang Abdurrahman bin Auf untuk rakaat yang kedua. Setelah Abdurrahman salam, Nabi shallallahu 'alaihi wasallam berdiri menyempurnakan shalat. Maka tiba-tiba kaum Muslimin terkejut, lalu banyak di antara mereka yang membaca "Subhaanallah", karena mereka telah mendahului Nabi shallallahu 'alaihi wasallam dalam shalat. Setelah Rasulullah shallallahu 'alaihi wasallam salam, beliau bersabda kepada mereka, "Benar apa yang kalian lakukan" atau "Bagus apa yang kalian lakukan
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>149</td></tr><tr><td>Arabic No</td><td>149</td></tr><tr><td>Reference</td><td>Book 1 Hadith 149</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Urve, babası el-Muğire b. Şu'be'nin şöyle dediğini işitmiştir: "Tebuk gazvesinde ben Rasulullah (s.a.v.)'in yanında bulunuyordum. Rasulullah (sallallahu aleyhi ve sellem) sabah namazından evvel yolunu değiştirdi. Ben de değiştirdim. Hemen devesini çöktürdü, ayak yoluna çıktı. Biraz sonra döndü. Ben de mataradan eline su döktüm, (önce) ellerini, sonra yüzünü yıkadı ve kollarını sıva (maya çalış) dı, cübbenin yenleri dar gelince ellerini (yenlerin) içine çekip cübbenin altından çıkardı ve dirseklerine kadar yıkadı. Sonra da başına mesh etti, daha sonra da, mestleri üzerine mesh verdi. Hayvanına bindi. Biz de yola düştük. Halkı namazda bulduk. Namaz vakti girdiğinden Abdurrahman b. Avf'ı öne geçirmişler onlara namaz kıldırıyordu. Abdurrahman'ı onlara sabah namazının bir rekatını kıldırmış halde bulduk. Rasulullah (sallallahu aleyhi ve sellem) namaza durup mü'minlerle beraber saf oldu. Abdurrahman b. Avf‘ın arkasında ikinci rekatı kıldı. Abdurrahman b. Avf selam verince Nebiyy (sallallahu aleyhi ve sellem) kalkıp namazına devam etti. Müslümanlar telaşlanıp "sübhanellah" deyip durmaya başladılar. Çünkü namaza Rasulullah’dan (s.a.v.) evvel başlamışlardı. Rasulullah (sallallahu aleyhi ve sellem) selam verince "doğru hareket ettiniz" veya "ne iyi ettiniz!" dedi. Diğer tahric: Buhari, vudu; Müslim, tahare, Nesai, tahare; İbn Mace, tahare. Tirmizî, tahare
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>149</td></tr><tr><td>Arabic No</td><td>149</td></tr><tr><td>Reference</td><td>Book 1 Hadith 149</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
مغیرہ بن شعبہ رضی اللہ عنہ کہتے ہیں کہ رسول اللہ صلی اللہ علیہ وسلم غزوہ تبوک میں فجر سے پہلے مڑے، میں آپ کے ساتھ تھا، میں بھی مڑا، پھر آپ صلی اللہ علیہ وسلم نے اونٹ بٹھایا اور قضائے حاجت کی، پھر آئے تو میں نے چھوٹے برتن ( لوٹے ) سے آپ کے ہاتھ پر پانی ڈالا، آپ صلی اللہ علیہ وسلم نے دونوں پہونچے دھوئے، پھر اپنا چہرہ دھویا، پھر آستین سے دونوں ہاتھ نکالنا چاہا مگر جبے کی آستین تنگ تھی اس لیے آپ نے ہاتھ اندر کی طرف کھینچ لیا، اور انہیں جبے کے نیچے سے نکالا، پھر دونوں ہاتھوں کو کہنیوں تک دھویا، اور اپنے سر کا مسح کیا، پھر دونوں موزوں پر مسح کیا، پھر سوار ہو گئے، پھر ہم چل پڑے، یہاں تک کہ ہم نے لوگوں کو نماز کی حالت میں پایا، ان لوگوں نے عبدالرحمٰن بن عوف رضی اللہ عنہ کو ( امامت کے لیے ) آگے بڑھا رکھا تھا، انہوں نے حسب معمول وقت پر لوگوں کو نماز پڑھائی، جب ہم پہنچے تو عبدالرحمٰن بن عوف فجر کی ایک رکعت پڑھا چکے تھے، رسول اللہ صلی اللہ علیہ وسلم مسلمانوں کے ساتھ صف میں شریک ہو گئے، آپ صلی اللہ علیہ وسلم نے عبدالرحمٰن بن عوف کے پیچھے دوسری رکعت پڑھی، پھر جب عبدالرحمٰن نے سلام پھیرا تو آپ صلی اللہ علیہ وسلم اپنی نماز پوری کرنے کے لیے کھڑے ہوئے، یہ دیکھ کر مسلمان گھبرا گئے، اور لوگ سبحان اللہ کہنے لگے، کیونکہ انہوں نے نبی اکرم صلی اللہ علیہ وسلم سے پہلے نماز شروع کر دی تھی، جب رسول اللہ صلی اللہ علیہ وسلم نے سلام پھیرا تو ان سے فرمایا: تم لوگوں نے ٹھیک کیا ، یا فرمایا: تم لوگوں نے اچھا کیا ۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>149</td></tr><tr><td>Arabic No</td><td>149</td></tr><tr><td>Reference</td><td>Book 1 Hadith 149</td></tr></tbody></table></div>