## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا أَحْمَدُ بْنُ حَنْبَلٍ، حَدَّثَنَا الْوَلِيدُ بْنُ مُسْلِمٍ، حَدَّثَنَا الأَوْزَاعِيُّ، حَدَّثَنِي يَحْيَى، - يَعْنِي ابْنَ أَبِي كَثِيرٍ - عَنْ أَبِي سَلَمَةَ، عَنْ أَبِي هُرَيْرَةَ، قَالَ لَمَّا فَتَحَ اللَّهُ تَعَالَى عَلَى رَسُولِ اللَّهِ صلى الله عليه وسلم مَكَّةَ قَامَ رَسُولُ اللَّهِ صلى الله عليه وسلم فِيهِمْ فَحَمِدَ اللَّهَ وَأَثْنَى عَلَيْهِ ثُمَّ قَالَ ‏"‏ إِنَّ اللَّهَ حَبَسَ عَنْ مَكَّةَ الْفِيلَ وَسَلَّطَ عَلَيْهَا رَسُولَهُ وَالْمُؤْمِنِينَ وَإِنَّمَا أُحِلَّتْ لِي سَاعَةً مِنَ النَّهَارِ ثُمَّ هِيَ حَرَامٌ إِلَى يَوْمِ الْقِيَامَةِ لاَ يُعْضَدُ شَجَرُهَا وَلاَ يُنَفَّرُ صَيْدُهَا وَلاَ تَحِلُّ لُقَطَتُهَا إِلاَّ لِمُنْشِدٍ ‏"‏ ‏.‏ فَقَامَ عَبَّاسٌ أَوْ قَالَ قَالَ الْعَبَّاسُ يَا رَسُولَ اللَّهِ إِلاَّ الإِذْخِرَ فَإِنَّهُ لِقُبُورِنَا وَبُيُوتِنَا ‏.‏ فَقَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏"‏ إِلاَّ الإِذْخِرَ ‏"‏ ‏.‏ قَالَ أَبُو دَاوُدَ وَزَادَنَا فِيهِ ابْنُ الْمُصَفَّى عَنِ الْوَلِيدِ فَقَامَ أَبُو شَاهٍ - رَجُلٌ مِنْ أَهْلِ الْيَمَنِ - فَقَالَ يَا رَسُولَ اللَّهِ اكْتُبُوا لِي ‏.‏ فَقَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏"‏ اكْتُبُوا لأَبِي شَاهٍ ‏"‏ ‏.‏ قُلْتُ لِلأَوْزَاعِيِّ مَا قَوْلُهُ ‏"‏ اكْتُبُوا لأَبِي شَاهٍ ‏"‏ ‏.‏ قَالَ هَذِهِ الْخُطْبَةَ الَّتِي سَمِعَهَا مِنْ رَسُولِ اللَّهِ صلى الله عليه وسلم ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Bukhari And Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2017</td></tr><tr><td>Arabic No</td><td>2017</td></tr><tr><td>Reference</td><td>Book 11 Hadith 297</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
আহমাদ ইবন হাম্বল (রহঃ) ..... আবূ হুরায়রা (রাঃ) হতে বর্ণিত। তিনি বলেন, আল্লাহ্ তা‘আলা যখন তাঁর রাসূলের উপর মক্কা বিজয় দান করেন, তখন নবী করীম সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম তাদের মধ্যে বক্তা হিসাবে দণ্ডায়মান হয়ে, আল্লাহ্ তা‘আলার প্রশংসা ও গুনাগুন করেন। অতঃপর তিনি বলেন, আল্লাহ্ তা‘আলা (আবরাহার) হস্তী বাহিনীর মক্কায় প্রবেশ করা প্রতিহত করেন। আর তিনি (মক্কার উপর) প্রাধান্য প্রদান করেন তাঁর রাসূল ও মু‘মিনদেরকে। আর আমার জন্য দিবসের একটি অংশকে (যখন তিনি তাঁর সৈন্যসহ সেখানে প্রবেশ করেন) হালাল করা হয়েছে। অতঃপর সেখানে (মক্কায়) কিয়ামত পর্যন্ত সকলের জন্য (যুদ্ধ-বিগ্রহ করা) হারাম। তার (সবুজ) বৃক্ষরাজি কর্তন করা যাবে না, সেখানে কিছু শিকার করা যাবে না এবং সেখানে পড়ে থাকা কোন বস্তু ঘোষক ব্যতীত অন্যের (প্রদান বা সাদকা করা) জন্য হালাল হবে না। তখন আব্বাস (রাঃ) দন্ডায়মান হন অথবা (রাবীর সন্দেহ) আব্বাস (রাঃ) বলেন, হে আল্লাহ্‌র রাসুল! ইযখির ব্যতীত, কেননা সেটা আমাদের গৃহ নির্মানের ও কবরের জন্য ব্যবহৃত হয়ে থাকে। তখন রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেন, হ্যাঁ, ইযখির ব্যতীত। ইমাম আবূ দাঊদ (রহঃ) বলেন, ইবন আল-মুসাফ্‌ফা, আল ওয়ালীদ হতে অতিরিক্ত বর্ণনা করেছেন যে, তখন আবূ শাহ্ নামক ইয়ামনের জনৈক ব্যক্তি দন্ডায়মান হয়ে বলেন, হে আল্লাহ্‌র রাসুল! এটা আমার জন্য লিখে দিন। তখন রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেন, তোমরা আবূ শাহ্-কে এটা লিখে দাও। রাবী (ওয়ালীদ) বলেন, তখন আমি আওয়া‘ঈকে এ সম্পর্কে বলি, তোমরা আবূ শাহকে যেটা লিখে দিচ্ছ তা কী? তিনি (আওয়া‘ঈ) বলেন, এটা ঐ খুতবা যা তিনি রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর নিকট হতে শুনেছেন।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Bukhari And Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2017</td></tr><tr><td>Arabic No</td><td>2017</td></tr><tr><td>Reference</td><td>Book 11 Hadith 297</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Abu Hurairah said “When Allah, the Exalted, granted the conquest of Makkah to his Apostle, the Prophet(ﷺ) stood among them(the people) and praised Allaah and extolled Him. He then said, Verily Allaah stopped the Elephant from Makkah, and gave His Apostle and the believers sway upon it and it has been made lawful for me only for one hour on one day then it will remain sacred till the Day of Resurrection. Its trees are not to be cut, its game is not to be molested and the things dropped there are to be picked up only by one who publicly announces it. ‘Abbas or Al ‘Abbas suggested “Apostle of Allaah(ﷺ) except the rush(idhkir) for it is useful for our graves and our houses. The Apostle of Allaah(ﷺ) said “Except the rush.” Abu Dawud said “Ibn Al Musaffa added on the authority of Al Walid Abu Shah a man from the people of the Yemen stood and said “Give me in writing, Apostle of Allaah(ﷺ)”. The Apostle of Allaah(ﷺ) said “Give in writing to Abu Shah. I said to Al Awza’i “What does the statement mean? Give Abu Shah in writing?” He said “This was an address which he heard from the Apostle of Allaah(ﷺ).”
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Bukhari And Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2017</td></tr><tr><td>Arabic No</td><td>2017</td></tr><tr><td>Reference</td><td>Book 11 Hadith 297</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Ahmad bin Hanbal], telah menceritakan kepada kami [Al Walid bin Muslim], telah menceritakan kepada kami [Al Auza'i], telah menceritakan kepadaku [Yahya bin Abu Katsir] dari [Abu Salamah], dari [Abu Hurairah], ia berkata; tatkala Allah Ta'ala menaklukkan Mekkah melalui Rasulullah shallallahu 'alaihi wasallam, beliau berdiri diantara mereka lalu memuji Allah kemudian berkata: "Sesungguhnya Allah telah menahan gajah dari Ka'bah, dan Allah menguasakan Ka'bah kepada rasulNya serta orang-orang mukmin. Sesungguhnya hal itu dihalalkan bagiku sesaat pada waktu siang, kemudian haram hingga hari Kiamat, tidak boleh pohonnya ditebang, tidak boleh hewan buruannya diusir, dan tidak halal barang temuannya kecuali bagi orang yang hendak mengumumkan." Kemudian Abbas berkata; wahai Rasulullah, kecuali idzkhir, karena tanaman tersebut untuk kuburan dan rumah kami. Kemudian Rasulullah shallallahu 'alaihi wasallam berkata: "Kecuali idzkhir." Abu Daud berkata; dan [Ibnu Al Mushthafa] menambahkan padanya dari [Al Walid]; kemudian Abu Syah yaitu seorang laki-laki dari penduduk Yaman berdiri dan berkata; wahai Rasulullah, tuliskan untukku! Kemudian Rasulullah shallallahu 'alaihi wasallam berkata: "Tuliskan untuk Abu Syah!" Aku katakan kepada Al Auza'i; apakah ucapan Rasulullah shallallahu 'alaihi wasallam: "Tuliskan untuk Abu Syah!" Ia berkata; khutbah yang ia dengar dari Rasulullah shallallahu 'alaihi wasallam. Telah menceritakan kepada kami [Utsman bin Abu Syaibah], telah menceritakan kepada kami [Jarir] dari [Manshur] dari [Mujahid] dari [Thawus] dari [Ibnu Abbas] mengenai kisah ini, ia berkata; dan tidak boleh dipotong tanamannya
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Bukhari And Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2017</td></tr><tr><td>Arabic No</td><td>2017</td></tr><tr><td>Reference</td><td>Book 11 Hadith 297</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ebû Hureyre (r.a.)'den; demiştir ki: Allah (c.c.) kendi elçisin'e Mekke'nin fethini nasibedince Peygamber (s.a.v.) halkın içinde ayağa kalkıp Allah'a hamd-ü senada bulunduktan sonra şöyle buyurdu: "Gerçekten Âllah (c.c) Fil Ordusunun Mekke(ye girmek)den men etmiş fakat Resulü ile mu'minleri Mekke'ye girmeye muzaffer kılmıştır. Allah teâla Mekke'yi sadece bana mahsus olmak üzere, gündüzün bir saatinde helâl kılmıştır. Sonra O (yine) kıyamete kadar haram (kıhnrmş)dır. Ağacı kesilemez kaybolan eşyası(nı almak) helâl olmaz, ilân edecek olan kimsenin dışında kaybolan eşyası(nı almak hiç kimse için) helâl değildir." Bunun üzerine Abbâs -Yahutta el-Abbas (Abbas kelimesinin "el" takısı ile mi yoksa el takısından tecrid edilerek mi rivayet edilmiş olduğunda râvi şüphe ediyor); Yalnız, izhir müstesna (değil mi) ya Resûlallah? Çünkü evlerimiz ve kabirlerimiz için (lâzım olmakta)dır, dedi. Bunun üzerine Resûlullah sallallahu aleyhi ve sellem de: "Yalnız izhir müstesna!" buyurdu. Ebû Dâvûd dedi ki: (Bu hadisi) el-Velid'den Îbnu'l-Musaffa da (rivayet etti ve hu rivayetine şunları da) ilâve etti: Bunun üzerine Yemen'li bir zât olan Ebu Şah ayağa kalkarak: Ya Resûlullah! Bunu bana yazınız, dedi. Resûlullah sallallahu aleyhi ve sellem.de, "(Bunu) Ebu Şah için yazınız" buyurdu. (Velid dedi ki) Ben Evzâî'ye (Hz. Peygamber) "Ebû Şah için yazınız" sözüyle neyi kastediyor? diye sordum da (Evzâî, Ebû Şah'ın); Resûlullah sallallahu aleyhi ve sellem'den işitmiş olduğu şu konuşmayı (yazınız anlamınadır)" diye cevap verdi
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Bukhari And Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2017</td></tr><tr><td>Arabic No</td><td>2017</td></tr><tr><td>Reference</td><td>Book 11 Hadith 297</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ابوہریرہ رضی اللہ عنہ کہتے ہیں کہ جب اللہ تعالیٰ نے رسول اللہ صلی اللہ علیہ وسلم کو مکہ فتح کرا دیا، تو آپ لوگوں میں کھڑے ہوئے، اللہ کی حمد و ثنا بیان کی پھر فرمایا: اللہ نے ہی مکہ سے ہاتھیوں کو روکا، اور اس پر اپنے رسول اور مومنین کا اقتدار قائم کیا، میرے لیے دن کی صرف ایک گھڑی حلال کی گئی اور پھر اب قیامت تک کے لیے حرام کر دی گئی، نہ وہاں ( مکہ ) کا درخت کاٹا جائے، نہ اس کا شکار بدکایا جائے، اور نہ وہاں کا لقطہٰ ( پڑی ہوئی چیز ) کسی کے لیے حلال ہے، بجز اس کے جو اس کی تشہیر کرے ، اتنے میں عباس رضی اللہ عنہ نے کہا: اللہ کے رسول! سوائے اذخر کے ۱؎ ( یعنی اس کا کاٹنا درست ہونا چاہیئے ) اس لیے کہ وہ ہماری قبروں اور گھروں میں استعمال ہوتی ہے، رسول اللہ صلی اللہ علیہ وسلم نے فرمایا: سوائے اذخر کے ۔ ابوداؤد کہتے ہیں: ابن مصفٰی نے ولید سے اتنا اضافہ کیا ہے: تو اہل یمن کے ایک شخص ابوشاہ کھڑے ہوئے اور عرض کیا: اللہ کے رسول! مجھے لکھ کر دے دیجئیے، رسول اللہ صلی اللہ علیہ وسلم نے فرمایا: ابو شاہ کو لکھ کر دے دو ، ( ولید کہتے ہیں ) میں نے اوزاعی سے پوچھا: «اكتبوا لأبي شاه» سے کیا مراد ہے، وہ بولے: یہی خطبہ ہے جو انہوں نے رسول اللہ صلی اللہ علیہ وسلم سے سنا۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Bukhari And Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2017</td></tr><tr><td>Arabic No</td><td>2017</td></tr><tr><td>Reference</td><td>Book 11 Hadith 297</td></tr></tbody></table></div>