## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا عُبَيْدُ اللَّهِ بْنُ عُمَرَ بْنِ مَيْسَرَةَ الْجُشَمِيُّ، حَدَّثَنَا عَبْدُ الْوَارِثِ بْنُ سَعِيدٍ، قَالَ حَدَّثَنَا مُحَمَّدُ بْنُ جُحَادَةَ، حَدَّثَنِي عَبْدُ الْجَبَّارِ بْنُ وَائِلِ بْنِ حُجْرٍ، قَالَ كُنْتُ غُلاَمًا لاَ أَعْقِلُ صَلاَةَ أَبِي قَالَ فَحَدَّثَنِي وَائِلُ بْنُ عَلْقَمَةَ عَنْ أَبِي وَائِلِ بْنِ حُجْرٍ قَالَ صَلَّيْتُ مَعَ رَسُولِ اللَّهِ صلى الله عليه وسلم فَكَانَ إِذَا كَبَّرَ رَفَعَ يَدَيْهِ - قَالَ - ثُمَّ الْتَحَفَ ثُمَّ أَخَذَ شِمَالَهُ بِيَمِينِهِ وَأَدْخَلَ يَدَيْهِ فِي ثَوْبِهِ قَالَ فَإِذَا أَرَادَ أَنْ يَرْكَعَ أَخْرَجَ يَدَيْهِ ثُمَّ رَفَعَهُمَا وَإِذَا أَرَادَ أَنْ يَرْفَعَ رَأْسَهُ مِنَ الرُّكُوعِ رَفَعَ يَدَيْهِ ثُمَّ سَجَدَ وَوَضَعَ وَجْهَهُ بَيْنَ كَفَّيْهِ وَإِذَا رَفَعَ رَأْسَهُ مِنَ السُّجُودِ أَيْضًا رَفَعَ يَدَيْهِ حَتَّى فَرَغَ مِنْ صَلاَتِهِ ‏.‏ قَالَ مُحَمَّدٌ فَذَكَرْتُ ذَلِكَ لِلْحَسَنِ بْنِ أَبِي الْحَسَنِ فَقَالَ هِيَ صَلاَةُ رَسُولِ اللَّهِ صلى الله عليه وسلم فَعَلَهُ مَنْ فَعَلَهُ وَتَرَكَهُ مَنْ تَرَكَهُ ‏.‏ قَالَ أَبُو دَاوُدَ رَوَى هَذَا الْحَدِيثَ هَمَّامٌ عَنِ ابْنِ جُحَادَةَ لَمْ يَذْكُرِ الرَّفْعَ مَعَ الرَّفْعِ مِنَ السُّجُودِ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Shadh</td><td>Shuaib Al Arnaut</td></tr><tr><td>Shadh</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>723</td></tr><tr><td>Arabic No</td><td>723</td></tr><tr><td>Reference</td><td>Book 2 Hadith 333</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
উবায়দুল্লাহ্ ইবনু উমার ..... আবূ ওয়ায়েল ইবনু হূজর (রাঃ) হতে বর্ণিত। তিনি বলেন, আমি রাসূলুল্লাহ্ সাল্লাল্লাহু আলাইহি ওয়া সাল্লামের সাথে নামায আদায় করি তাকবীর বলার সময় নিজের দুই হাত উঠাতেন, পরে তিনি তার হাত কাপড়ের মধ্যে প্রবেশ করিয়ে ডান হাত দিয়ে বাম হাত ধরতেন। রাবী বলেন, অতঃপর যখন রুকূর ইরাদা করেন, তখন স্বীয় হাত দু’খানা বের করে উপরে উঠাতেন। তিনি রুকু হতে মাথা উঠানোর সময়ও দুই হাত উপরে উঠান। অতঃপর তিনি সিজদায় যান এবং স্বীয় চেহারা দুই হাতের তালুর মধ্যবর্তী স্থানে স্থাপন করেন। অতঃপর তিনি সিজদা হতে মাথা উঠাবার সময়ও স্বীয় হাত দুইখানা উত্তোলন করেন। এভাবে তিনি তাঁর নামায শেষ করেন। রাবী মুহাম্মাদ বলেন, এ সম্পর্কে আমি হাসান ইবনু আবূল হাসানকে জিজ্ঞেস করলে তিনি বলেন, এমনি ছিল রাসূলুল্লাহ সল্লাল্লাহু আলাইহি ওয়া সাল্লামের নামায আদায়ের নিয়ম। যে ব্যক্তি এর অনুসরণ করেছে, সে তো করেছে এবং যে ব্যক্তি তা ত্যাগ করেছে- সে তো তা ত্যাগ করেছে- (মুসলিম)। ইমাম আবূ দাউদ (রহঃ) বলেন, হাম্মাম-ইবনু জাহাদা হতে বর্ণনা করেছেন। কিন্তু ঐ বর্ণনায় সিজদা হতে মাথা উঠানোর সময় হাত উঠাবার কথা উল্লেখ নেই।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Shadh</td><td>Shuaib Al Arnaut</td></tr><tr><td>Shadh</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>723</td></tr><tr><td>Arabic No</td><td>723</td></tr><tr><td>Reference</td><td>Book 2 Hadith 333</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
‘Abd al-Jabbar b. Wa’il (b.Hujr) said:I was a small boy and I did not understand the prayer of my father. So Wa’Il b. ‘Alqamah reported Wa’il b. Hujr as saying: I offered prayer along with the Messenger of Allah (ﷺ). He used to raise his hands when he pronounced the takbir (Allah is most great), then pulled his garment around him, then placed his right hand on his left, and entered his hands in his garment. When he was about to bow he took his hands out of his garment, and then raised them. And when he raised his head after bowing, he raised his hands. He then prostrated himself and placed his face (forehead on the ground) between his hands. And when he raised his head after prostration, he also raised his hands until he finished his prayer. Muhammad (a narrator) said: I mentioned it to al-Hasan b. Abu al-Hasan who said: This is how the Messenger of Allah(ﷺ) offered prayer; some did it and others abandoned it. Abu Dawud said: This tradition has been narrated by Hammam from ibn Juhadah, but he did not mention the raising of hands after he raised his head at the end of the prostration
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Shadh</td><td>Shuaib Al Arnaut</td></tr><tr><td>Shadh</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>723</td></tr><tr><td>Arabic No</td><td>723</td></tr><tr><td>Reference</td><td>Book 2 Hadith 333</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami ['Ubaidullah bin Umar bin Maisarah Al Jusyami] telah menceritakan kepada kami [Abdul Warits bin Sa'id] dia berkata; telah menceritakan kepada kami [Muhammad bin Juhadah] telah menceritakan kepadaku [Abdul Jabbar bin Wa'il bin Hujr] dia berkata; "Aku adalah seorang anak yang belum mengerti shalat yang di kerjakan ayahku, katanya; maka ["Wa'il bin 'Alqamah] telah menceritakan kepadaku, dari ayahku [Wa'il bin Hujr] dia berkata; "Aku shalat bersama Rasulullah shallallahu 'alaihi wasallam, apabila beliau hendak bertakbir, maka beliau mengangkat kedua tangannya." Katanya; "Kemudian beliau melipatkan pakaiannya, lalu tangan kanannya memegang tangan kirinya dan memasukkan kedua tangannya ke dalam pakaian beliau." dia melanjutkan; "Apabila beliau hendak ruku', beliau mengeluarkan kedua tangannya dan mengangkatnya, dan apabila beliau hendak mengangkat kepalanya dari ruku' (i'tidal), beliau mengangkat kedua tangannya, barulah beliau sujud dengan meletakkan wajahnya sejajar dengan kedua telapak tangannya, apabila beliau hendak mengangkat kepalanya dari sujud, maka beliau juga mengangkat kedua tangannya lagi sampai selesai shalat." Muhammad mengatakan; "Lalu aku menyebutkan hal itu kepada Al Hasan bin Abu Al Hasan, maka dia berkata; "Itu adalah shalat Rasulullah shallallahu 'alaihi wasallam yang di kerjakan oleh orang yang suka mengerjakan dan di tinggalkan oleh orang yang suka meninggalkannya." Abu Daud mengatakan; "Hadits ini di riwayatkan juga oleh [Hammam] dari [Ibnu Juhadah], namun dia tidak menyebutkan 'juga mengangkat tangan ketika bangkit dari sujud
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Shadh</td><td>Shuaib Al Arnaut</td></tr><tr><td>Shadh</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>723</td></tr><tr><td>Arabic No</td><td>723</td></tr><tr><td>Reference</td><td>Book 2 Hadith 333</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Vail b. Hucr'den; demiştir ki: Resulullah (Sallallahu aleyhi ve Sellem) ile beraber namaz kıldım, (iftitah) tekbiri(ni) aldığı zaman, ellerini kaldırırdı. Sonra (elbisesine) sarınır (ellerini elbisesinin içine sokarak) sağ eli ile sol elini tutardı. Rüku'a varmak istediği zaman da ellerini (elbisesinden) çıkarır ve onları kaldırırdı. Başını rüku'dan kaldırmak istediği zaman da ellerini kaldırır, sonra secdeye varırdı ve yüzünü iki eleri arasına koyardı. Başını secdeden kaldırmak isteyince de aynı şekilde ellerini kaldırırdı. (Bu hal) namaza bitirinceye kadar (böyle) devam ederdi. Muhammed (b. Cuhade) dedi ki: Ben bu durumu Hasan b. Ebî'l-Hasen'e söyledim. (O da bana şöyle) dedi: "Bu Hz. Nebiin namazıdır. Bunu yapan yaptı, yapmayan yapmadı." Ebü Davud dedi ki: Bu hadisi (bir de) Hemmam, İbn Cuhade’den nakletti,(ancak) Hemmam (Hz. Nebi'nin) secdeden kalkarken ellerini kaldırdığından bahsetmedi. Diğer tahric: Buharî, salat; Müslim, salat; Ahmed b. Hanbel, II, 380; VI-342
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Shadh</td><td>Shuaib Al Arnaut</td></tr><tr><td>Shadh</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>723</td></tr><tr><td>Arabic No</td><td>723</td></tr><tr><td>Reference</td><td>Book 2 Hadith 333</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
وائل بن حجر رضی اللہ عنہ کہتے ہیں کہ میں نے رسول اللہ صلی اللہ علیہ وسلم کے ساتھ نماز پڑھی، جب آپ نے تکبیر ( تحریمہ ) کہی تو اپنے دونوں ہاتھ اٹھائے، پھر آپ صلی اللہ علیہ وسلم نے اپنے داہنے ہاتھ سے بائیں ہاتھ کو پکڑا، اور انہیں اپنے کپڑے میں داخل کر لیا، جب آپ نے رکوع کا ارادہ کیا تو اپنے دونوں ہاتھ ( چادر سے ) نکالے پھر رفع یدین کیا، اور جب رکوع سے اپنا سر اٹھانے کا ارادہ کیا تو رفع یدین کیا، پھر سجدہ کیا اور اپنی پیشانی کو دونوں ہتھیلیوں کے بیچ میں رکھا، اور جب سجدے سے اپنا سر اٹھایا تو رفع یدین ۱؎ کیا یہاں تک کہ آپ صلی اللہ علیہ وسلم نماز سے فارغ ہو گئے۔ محمد کہتے ہیں: میں نے حسن بصری سے اس کا ذکر کیا، تو انہوں نے کہا: یہی رسول اللہ صلی اللہ علیہ وسلم کی نماز ہے، کرنے والوں نے ایسا ہی کیا اور چھوڑنے والوں نے اسے چھوڑ دیا۔ أبوداود کہتے ہیں: اس حدیث کو ہمام نے بھی ابن جحادہ سے روایت کیا ہے، لیکن انہوں نے سجدے سے اٹھتے وقت رفع یدین کا ذکر نہیں کیا ہے۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Shadh</td><td>Shuaib Al Arnaut</td></tr><tr><td>Shadh</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>723</td></tr><tr><td>Arabic No</td><td>723</td></tr><tr><td>Reference</td><td>Book 2 Hadith 333</td></tr></tbody></table></div>