## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا هِشَامُ بْنُ عَمَّارٍ، وَسُلَيْمَانُ بْنُ عَبْدِ الرَّحْمَنِ الدِّمَشْقِيُّ، وَيَحْيَى بْنُ الْفَضْلِ السِّجِسْتَانِيُّ، قَالُوا حَدَّثَنَا حَاتِمٌ، - يَعْنِي ابْنَ إِسْمَاعِيلَ - حَدَّثَنَا يَعْقُوبُ بْنُ مُجَاهِدٍ أَبُو حَزْرَةَ، عَنْ عُبَادَةَ بْنِ الْوَلِيدِ بْنِ عُبَادَةَ بْنِ الصَّامِتِ، قَالَ أَتَيْنَا جَابِرًا - يَعْنِي ابْنَ عَبْدِ اللَّهِ - قَالَ سِرْتُ مَعَ النَّبِيِّ صلى الله عليه وسلم فِي غَزْوَةٍ فَقَامَ يُصَلِّي وَكَانَتْ عَلَىَّ بُرْدَةٌ ذَهَبْتُ أُخَالِفُ بَيْنَ طَرَفَيْهَا فَلَمْ تَبْلُغْ لِي وَكَانَتْ لَهَا ذَبَاذِبُ فَنَكَسْتُهَا ثُمَّ خَالَفْتُ بَيْنَ طَرَفَيْهَا ثُمَّ تَوَاقَصْتُ عَلَيْهَا لاَ تَسْقُطُ ثُمَّ جِئْتُ حَتَّى قُمْتُ عَنْ يَسَارِ رَسُولِ اللَّهِ صلى الله عليه وسلم فَأَخَذَ بِيَدِي فَأَدَارَنِي حَتَّى أَقَامَنِي عَنْ يَمِينِهِ فَجَاءَ ابْنُ صَخْرٍ حَتَّى قَامَ عَنْ يَسَارِهِ فَأَخَذَنَا بِيَدَيْهِ جَمِيعًا حَتَّى أَقَامَنَا خَلْفَهُ قَالَ وَجَعَلَ رَسُولُ اللَّهِ صلى الله عليه وسلم يَرْمُقُنِي وَأَنَا لاَ أَشْعُرُ ثُمَّ فَطِنْتُ بِهِ فَأَشَارَ إِلَىَّ أَنْ أَتَّزِرَ بِهَا فَلَمَّا فَرَغَ رَسُولُ اللَّهِ صلى الله عليه وسلم قَالَ ‏"‏ يَا جَابِرُ ‏"‏ ‏.‏ قَالَ قُلْتُ لَبَّيْكَ يَا رَسُولَ اللَّهِ ‏.‏ قَالَ ‏"‏ إِذَا كَانَ وَاسِعًا فَخَالِفْ بَيْنَ طَرَفَيْهِ وَإِذَا كَانَ ضَيِّقًا فَاشْدُدْهُ عَلَى حِقْوِكَ ‏"‏ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>634</td></tr><tr><td>Arabic No</td><td>634</td></tr><tr><td>Reference</td><td>Book 2 Hadith 244</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
হিশাম ইবনু আম্মার .... উবাদা ওয়ালীদ হতে বর্ণিত। তিনি বলেন, আমরা জাবের ইবনু আবদুল্লাহ্ (রাঃ) এর নিকট উপস্থিত হলে তিনি বলেন, আমি রাসূলুল্লাহ্ সাল্লাল্লাহু আলাইহি ওয়া সাল্লামের সাথে কোন এক যুদ্ধে যাই। তিনি নামায পড়ার জন্য দন্ডায়মান হন। এ সময় আমার গায়ে একটি ছোট চাঁদর ছিল। আমি তা আমার কাঁধের দুই পাশে রাখার জন্য চেষ্টা করি, কিন্তু তা ছোট থাকায় কাঁধ পর্যন্ত পৌছেনি। আমার চাঁদরের লম্বা আচল ছিল, আমি সামান্য নত হয়ে ঐ আচলদ্বয় (কাঁধের) উপর এমনভাবে বেধে দেই, যাতে তা সরে না পড়তে পারে। অতঃপর এ অবস্থায় আমি রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়া সাল্লামের বাম পাশে গিয়ে নামাযে দাঁড়াই। তিনি আমার হাত ধরে ঘুরিয়ে তাঁর ডান পাশে দাঁড় করান। এ সময় ইবনু সাখর (রহঃ) এসে তাঁর বাম পাশে দাঁড়ান। অতঃপর তিনি নিজের দুই হাত আমাদের উভয়কে ধরে তাঁর পিছনে দাঁড় করান। রাবী বলেন, অতঃপর রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম আমার প্রতি ইংগিতপূর্ণ দৃষ্টিতে তাকান, কিন্তু আমি এর অর্থ বুঝতে সক্ষম হই নাই, পরে আমি হৃদয়ংগম করতে পারি। তখন আমার প্রতি ইশারা করে বলেনঃ তোমার চাঁদর কোমরের সাথে ভাল করে বাঁধ। অতঃপর নামাযান্তে রাসূলুল্লাহ্ সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম বলেনঃ হে জাবের! আমি বলি- লাব্বাইকা, ইয়া রাসূলাল্লাহ্! তিনি বলেনঃ যখন তোমার চাদর বড় হবে তখন তা তুমি তোমার কাঁধের দুই পাশে জড়িয়ে রাখবে। আর যখন তা ছোট হবে তখন তা কোমরের সাথে শক্তভাবে বেধে রাখবে। (মুসলিম)।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>634</td></tr><tr><td>Arabic No</td><td>634</td></tr><tr><td>Reference</td><td>Book 2 Hadith 244</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
‘Ubadah b. al-Samit said:we came to Jabir b. ‘Abd Allah. He said : I (Jabir) accompanied the Messenger of Allah (ﷺ) in a battle. He got up to pray. I had a sheet of cloth upon me, and I began to cross both the ends, but they did not reach (my shoulders). It had fringes which I turned over and crossed the two ends, and bowed down retaining it with my neck lest it should fall down. Then I came and stood on the left side of the Messenger of Allah (ﷺ). He then took and brought me around him and set me on his right side. Then Ibn Sakhr came and stood on his left side. he then took us with his both hands and made us stand behind him. The Messenger of Allah (ﷺ) began to look at me furtive glances, but I could not understand. When I understood, he hinted at me tie the wrapper. When the Messenger of Allah (ﷺ) finished the prayer, he said (to me): O Jabir. I said; Yes, Messenger of Allah. He said; if it (the sheet) is wide, cross both its ends (over the shoulders); if it is tight, tie it over your loins
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>634</td></tr><tr><td>Arabic No</td><td>634</td></tr><tr><td>Reference</td><td>Book 2 Hadith 244</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Hisyam bin Ammar] dan [Sulaiman bin Abdurrahman Ad-Dimasyqi] dan [Yahya bin Al-Fadll As-Sijistani] mereka berkata; Telah menceritakan kepada kami [Hatim bin Isma'il] telah menceritakan kepada kami [Ya'qub bin Mujahid, Abu Hazrah] dari [Ubadah bin Al-Walid bin Ubadah bin Ash-Shamit] dia berkata; Kami pernah mengunjungi [Jabir bin Abdullah], dia berkata; Saya pernah pergi bersama Nabi shallallahu 'alaihi wasallam dalam suatu peperangan. Lalu beliau berdiri mengerjakan shalat, sementara saya memakai kain selimut yang saya silangkan kedua ujungnya, namun tidak memadai untukku. Kain itu berumbai bagian bawahnya, maka saya membaliknya, lalu saya silangkan kedua ujungnya, kemudian saya apit (dengan leher) supaya tidak jatuh. Lalu saya datang sehingga saya berdiri di sebelah kiri Rasulullah shallallahu 'alaihi wasallam, maka beliau memegang tanganku, dan memindahkanku sehingga saya ditempatkan di sebelah kanan beliau, tiba tiba datang Ibnu Sakhr langsung berdiri di sebelah kiri beliau, maka beliau memegang kami berdua dengan kedua tangannya, sampai beliau menempatkan kami di belakang. Kata Jabir; Rasulullah menatapku, sedangkan saya tidak merasa, akhirnya saya juga dapat memahaminya. Beliau kemudian memberi isyarat kepadaku supaya saya memakai kain tersebut sebagai sarung. Setelah Rasulullah shallallahu 'alaihi wasallam selesai shalat, beliau bersabda: "Wahai Jabir." Kata Jabir; Aku jawab, ya Rasulullah. Beliau bersabda: "Apabila kain itu longgar, maka silangkanlah kedua ujungnya, dan apabila sempit, ikatlah pada pinggangmu
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>634</td></tr><tr><td>Arabic No</td><td>634</td></tr><tr><td>Reference</td><td>Book 2 Hadith 244</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ubade b. el-Velid b. Ubade b. Es-Samit'den; demiştir ki: Biz Cabir'in yani İbn Abdillah'ın yanına varmıştık. (Bize şunları) söyledi: "Bir gece Resulullah (Sallallahu aleyhi ve Sellem)'le beraber düşmanı takibe çıkmıştım. Resulullah (Sallallahu aleyhi ve Sellem) namaza kalktı. Benim üzerimde de bir örtü vardı. Bir ucunu sağ omuzuma, öbür ucunu da sol omuzuma atmaya uğraştımsa da yetişmedi (dar geldi). Aynı zamanda saçakları vardı. (Bir de) altını üstüne getirdikten sonra her iki ucundan birini sağ, öbürünü de sol omuzuma aldım, sonra da düşmemesi için üzerine eğildim (ve çenemle tuttum). Gelip Resulullah (Sallallahu aleyhi ve Sellem)'in soluna durdum. Resul-i Ekrem de (hemen) elimi tutup (arkasından) dolandırarak beni sağına durdurdu. (Çok geçmeden) İbn Sahr geldi, o da soluna durdu. (Hz. Nebi) her ikimizi de elleriyle tutup beraberce arkasına durdurdu. (Cabir) dedi ki: Resulullah (Sallallahu aleyhi ve Sellem) gözlerini bana dikmişti. Bense hissetmiyordum. Sonra bunun farkına vardım. Bana bu örtüyü belime bağlamamı işaret etti. Resul-i Ekrem (Sallallahu aleyhi ve Sellem) namazı bitirince bana (hitab ederek); "Ey Cabir" dedi, ben de: "Buyur, ey Allah'ın Resulü" dedim. "Elbise bol olunca iki uçlarını omuzlarına at. Dar olunca da beline bağla" buyurdu." Diğer tahric: Müslim, zuhd; Ahmed b. Hanbel, IH, 335
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>634</td></tr><tr><td>Arabic No</td><td>634</td></tr><tr><td>Reference</td><td>Book 2 Hadith 244</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
عبادہ بن ولید بن عبادہ بن صامت کہتے ہیں کہ ہم جابر بن عبداللہ رضی اللہ عنہما کے پاس آئے تو انہوں نے کہا: میں ایک غزوہ میں رسول اللہ صلی اللہ علیہ وسلم کے ساتھ چلا ( رات میں میں کسی غرض سے آپ کی خدمت میں حاضر ہوا تو دیکھا کہ ) آپ صلی اللہ علیہ وسلم کھڑے نماز پڑھ رہے ہیں، اس وقت میرے جسم پر صرف ایک چادر تھی، میں اس کے دائیں کنارے کو بائیں کندھے پر اور بائیں کو دائیں کندھے پر ڈالنے لگا تو وہ میرے لیے ناکافی ہوئی، البتہ اس میں کچھ گوٹ اور کناریاں لگی تھیں تو میں نے اسے الٹ لیا اور اس کے دونوں کناروں کو ادھر ادھر ڈال لیا اور گردن سے اسے روکے رکھا تاکہ گرنے نہ پائے، پھر میں آ کر رسول اللہ صلی اللہ علیہ وسلم کی بائیں طرف کھڑا ہو گیا تو آپ نے میرا ہاتھ پکڑا اور مجھے گھما کر اپنی داہنی طرف کھڑا کر لیا۔ پھر ابن صخر رضی اللہ عنہ آئے، وہ آپ صلی اللہ علیہ وسلم کی بائیں طرف کھڑے ہو گئے، آپ نے اپنے دونوں ہاتھوں سے ہم دونوں کو پکڑ کر اپنے پیچھے کھڑا کر دیا، مجھے آپ صلی اللہ علیہ وسلم کنکھیوں سے دیکھنے لگے، میں سمجھ نہیں پا رہا تھا ( کہ آپ مجھ سے کیا کہنا چاہتے ہیں ) ، پھر بات میری سمجھ میں آ گئی، آپ صلی اللہ علیہ وسلم نے مجھے تہہ بند باندھنے کا اشارہ کیا، پھر جب آپ نماز سے فارغ ہوئے تو فرمایا: جابر! ، میں نے کہا: اللہ کے رسول! فرمائیے، حاضر ہوں، آپ صلی اللہ علیہ وسلم نے فرمایا: جب چادر کشادہ ہو تو اس کے دونوں کناروں کو ادھر ادھر ڈال لو، اور جب تنگ ہو تو اسے اپنی کمر پر باندھ لیا کرو ۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Sahih Muslim</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>634</td></tr><tr><td>Arabic No</td><td>634</td></tr><tr><td>Reference</td><td>Book 2 Hadith 244</td></tr></tbody></table></div>