## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا يَحْيَى بْنُ مَعِينٍ، وَهَنَّادُ بْنُ السَّرِيِّ، وَعُثْمَانُ بْنُ أَبِي شَيْبَةَ، عَنْ عَبْدِ السَّلاَمِ بْنِ حَرْبٍ، - وَهَذَا لَفْظُ حَدِيثِ يَحْيَى - عَنْ أَبِي خَالِدٍ الدَّالاَنِيِّ، عَنْ قَتَادَةَ، عَنْ أَبِي الْعَالِيَةِ، عَنِ ابْنِ عَبَّاسٍ، أَنَّ رَسُولَ اللَّهِ صلى الله عليه وسلم كَانَ يَسْجُدُ وَيَنَامُ وَيَنْفُخُ ثُمَّ يَقُومُ فَيُصَلِّي وَلاَ يَتَوَضَّأُ ‏.‏ قَالَ فَقُلْتُ لَهُ صَلَّيْتَ وَلَمْ تَتَوَضَّأْ وَقَدْ نِمْتَ فَقَالَ ‏"‏ إِنَّمَا الْوُضُوءُ عَلَى مَنْ نَامَ مُضْطَجِعًا ‏"‏ ‏.‏ زَادَ عُثْمَانُ وَهَنَّادٌ ‏"‏ فَإِنَّهُ إِذَا اضْطَجَعَ اسْتَرْخَتْ مَفَاصِلُهُ ‏"‏ ‏.‏ قَالَ أَبُو دَاوُدَ قَوْلُهُ ‏"‏ الْوُضُوءُ عَلَى مَنْ نَامَ مُضْطَجِعًا ‏"‏ ‏.‏ هُوَ حَدِيثٌ مُنْكَرٌ لَمْ يَرْوِهِ إِلاَّ يَزِيدُ أَبُو خَالِدٍ الدَّالاَنِيُّ عَنْ قَتَادَةَ وَرَوَى أَوَّلَهُ جَمَاعَةٌ عَنِ ابْنِ عَبَّاسٍ وَلَمْ يَذْكُرُوا شَيْئًا مِنْ هَذَا وَقَالَ كَانَ النَّبِيُّ صلى الله عليه وسلم مَحْفُوظًا وَقَالَتْ عَائِشَةُ - رضى الله عنها - قَالَ النَّبِيُّ صلى الله عليه وسلم ‏"‏ تَنَامُ عَيْنَاىَ وَلاَ يَنَامُ قَلْبِي ‏"‏ ‏.‏ وَقَالَ شُعْبَةُ إِنَّمَا سَمِعَ قَتَادَةُ مِنْ أَبِي الْعَالِيَةِ أَرْبَعَةَ أَحَادِيثَ حَدِيثَ يُونُسَ بْنِ مَتَّى وَحَدِيثَ ابْنِ عُمَرَ فِي الصَّلاَةِ وَحَدِيثَ الْقُضَاةُ ثَلاَثَةٌ وَحَدِيثَ ابْنِ عَبَّاسٍ حَدَّثَنِي رِجَالٌ مَرْضِيُّونَ مِنْهُمْ عُمَرُ وَأَرْضَاهُمْ عِنْدِي عُمَرُ ‏.‏ قَالَ أَبُو دَاوُدَ وَذَكَرْتُ حَدِيثَ يَزِيدَ الدَّالاَنِيِّ لأَحْمَدَ بْنِ حَنْبَلٍ فَانْتَهَرَنِي اسْتِعْظَامًا لَهُ وَقَالَ مَا لِيَزِيدَ الدَّالاَنِيِّ يُدْخِلُ عَلَى أَصْحَابِ قَتَادَةَ وَلَمْ يَعْبَأْ بِالْحَدِيثِ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Daif</td><td>Shuaib Al Arnaut</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>202</td></tr><tr><td>Arabic No</td><td>202</td></tr><tr><td>Reference</td><td>Book 1 Hadith 202</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ইয়াহইইয়া ইবনু মুঈন .... ইবনু আব্বাস (রাঃ) হতে বর্ণিত। রাসুলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম সিজদা করতেন (অর্থাৎ সালাত পড়তেন) এবং ঘুম যেতেন এবং নাক ডাকতেন, অতঃপর দাঁড়িয়ে পুনরায় উযূ (ওজু/অজু/অযু) করা ব্যাতিরেকে সালাত আদায় করতেন। রাবী বলেন, আমি তাকে বলি, আপনি ঘুমানোর পর উযূ (ওজু/অজু/অযু) না করে সালাত আদায় করলেন? তিনি বলেন, উযূ (ওজু/অজু/অযু) করা ঐ ব্যাক্তির জন্য প্রয়োজন, যে আরামের সাথে হেলান দিয়ে ঘুমায়। উসমান ও হান্নাদের বর্ণনায় আরও আছে যে, “কেননা কেউ পার্শদেশে ভর দিয়ে শয়ন করলে তাঁর দেহের বাধন ঢিলা হয়ে যায়”। আবূ দাউদ (রহঃ) বলেন, যে ব্যাক্তি পার্শদেশে ভর দিয়ে ঘুমায় তাকে উযূ (ওজু/অজু/অযু) করতে হবে” – হাদিসের এই অংশটুকু মুনকার (প্রত্যাখ্যাত)। কাতাদার সুত্রে ইয়াজীদ আদ-দালানী ব্যাতিত অপর কেউ তা বর্ণনা করেনি। কিন্তু হাদিসের প্রথমাংশ একদল রাবী ইবনু আব্বাস (রাঃ)-এর সুত্রে রিওয়ায়াত করেছেন এবং তারা উপরোক্ত কথার কিছুই উল্লেখ করেননি। ইবনু আব্বাস (রাঃ) বলেন, রাসুল সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম (অসতর্কতা থেকে) নিরাপদ ছিলেন। আয়িশা (রাঃ) বলেন, রাসুল সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেছেনঃ আমার এই দুই চোখ ঘুমালেও আমার অন্তর ঘুমায় না। শোবা বলেন, কাতাদা (রহঃ) আবূল আলিয়ার নিকট চারটি হাদিস শুনেনঃ ইউনুস ইবনু মাত্তার হাদিস, সালাত সম্পর্কে ইবনু উমার (রাঃ) এর হাদীস, তৃতীয় হাদিস বিচারক তিন শ্রেণীর এবং চতুর্থ ইবনু আব্বাস (রাঃ) এর হাদিস।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Daif</td><td>Shuaib Al Arnaut</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>202</td></tr><tr><td>Arabic No</td><td>202</td></tr><tr><td>Reference</td><td>Book 1 Hadith 202</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated Abdullah ibn Abbas: The Messenger of Allah (ﷺ) used to prostrate and sleep (in prostration) and produce puffing sounds (during sleep). Then he would stand and pray and would not perform ablution. I said to him: you prayed but did not perform ablution though you slept (in prostration). He replied: Ablution is necessary for one who sleeps while he is lying down. Uthman and Hannad added: For when he lies down, his joints are relaxed. Abu Dawud said: The statement "ablution is necessary for one who sleeps while one is lying down" is a munkar (rejected) tradition. It has been narrated only by Yazid Abu Khalid al-Dalani, on the authority of Qatadah. And its earlier part has been narrated by a group (of narrators) from Ibn 'Abbas; they did not mention anything about it. He (Ibn 'Abbas) said: The Prophet (ﷺ) was protected (during his sleep). 'Aishah reported: The Prophet (ﷺ) said: My eyes sleep, but my heart does not sleep. Shu'bah said: Qatadah heard from Abu'l-'Aliyah only four traditions: the tradition about Jonah son of Matthew, the tradition reported by Ibn 'Umar about prayer, the tradition stating that the judges are three, and the tradition narrated by Ibn 'Abbas saying: (This tradition) has been narrated to me by reliable persons ; 'Umar is one of them, and the most reliable of them in my opinion is 'Umar. Abu Dawud said: I asked Ahmad b. Hanbal about the tradition narrated by Yazid al-Dalani. He rebuked me out of respect for him. Then he said: Yazid al-Dalani does not add anything to what has been narrated by the teachers of Qatadah. He did not care of this tradition (due to its weakness)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Daif</td><td>Shuaib Al Arnaut</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>202</td></tr><tr><td>Arabic No</td><td>202</td></tr><tr><td>Reference</td><td>Book 1 Hadith 202</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Yahya bin Ma'in] dan [Hannad bin As Sariy] dan [Utsman bin Abu Syaibah] dari [Abdussalam bin Harb] dan ini adalah lafazh hadits Yahya dari [Abu Khalid Ad- Dalani] dari [Qatadah] dari [Abu Al-'Aliyah] dari [Ibnu Abbas] bahwa Rasulullah shallallahu 'alaihi wasallam pernah sujud dan tidur serta mengeluarkan suara, kemudian beliau bangkit untuk shalat dan tidak berwudhu kembali. Dia (Ibnu Abbas) berkata; Maka saya tanyakan kepada beliau; Baginda shalat dan tidak berwudhu, padahal baginda telah tidur. Maka beliau bersabda: "Sesungguhnya wudhu hanyalah wajib bagi orang yang tidur dengan berbaring." [Utsman] dan [Hannad] menambahkan dengan lafadl; "Karena apabila dia tidur berbaring, maka seluruh persendiannya loyo." Abu Dawud berkata; Hadits tentang berwudhu bagi orang yang tidur berbaring adalah hadits munkar, tidak ada yang meriwayatkannya kecuali Yazid Abu Khalid Ad-Dalani dari Qatadah. Awal Hadits ini diriwayatkan oleh Jama'ah dari Ibnu Abbas, dan mereka tidak menyebutkan sedikit pun tentang ini (berwudhu bagi yang tidur berbaring), dan dia berkata; Nabi shallallahu 'alaihi wasallam terpelihara (dari tidurnya hati). Dan Aisyah radliallahu 'anha berkata; Nabi shallallahu 'alaihi wasallam bersabda: "Kedua mataku tertidur akan tetapi hatiku tidak." Syu'bah berkata; Sesungguhnya Qatadah mendengar dari Abu Al Aliyah hanya empat hadits, yaitu: Hadits Yunus bin Matta, hadits Ibnu Umar tentang shalat, Hadits tentang keterangan bahwa para hakim itu ada tiga golongan, dan hadits Ibnu Abbas, telah menceritakan kepada saya orang-orang yang diridhai yang diantaranya Umar, dan yang lebih diridhai menurutku adalah Umar. Abu Dawud berkata; Saya pernah menyebutkan hadits Yazid Ad-Dalani kepada Ahmad bin Hanbal, maka dia memperingatkanku dengan keras karena pengingkarannya yang begitu besar pada riwayat tersebut, dan dia berkata; Apa urusan Yazid Ad-Dalani dengan memasukkan pada para sahabat Qatadah apa-apa yang tidak mereka riwayatkan. Dia (Ahmad) tidak mempedulikan hadits tersebut
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Daif</td><td>Shuaib Al Arnaut</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>202</td></tr><tr><td>Arabic No</td><td>202</td></tr><tr><td>Reference</td><td>Book 1 Hadith 202</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
İbn Abbas (r.a) demiştir ki; Resulullah (sallallahu aleyhi ve sellem) secde ediyor, uyuyor, horluyor sonra kalkıp abdest almadan namaz kılıyordu. Kendisine; "Uyuduğun halde abdest almadan namaz kıldın" dedim. O: "Abdest sadece uzanarak uyuyana lazımdır" buyurdu, Osman ve Hennad, (rivayetlerinde): "Çünkü (insan) uzanarak uyuduğu zaman mafsalları gevşer” ibaresini ilave ettiler. Ebu Davud dedi ki;'Abdest yanı üzerine uzanana lazımdır." Sözü münker bir hadisdir. (Çünkü) onu Katade'den; Yezid ed-Dalani'den başkası rivayet etmemiştir. Hadisin baş tarafını ibn Abbas'tan bir cemaat rivayet etmiş, bu hususta hiçbir şey zikretmemişlerdir. İbn Abbas (veya Ikrime: "Resulullah (secdede iken kendisinden abdest bozacak bir şey çıkmasından) korunmuştur" dedi. Aişe radiyallahu anha da Resulullah'ın, "Benim gözlerim uyur kalbim uyumaz"buyurduğunu nakletti. Şube şöyle demiştir: "Katade Ebu'l-Aliye'den dört hadis işitmiştir. Bunlar; 1- Yunus b. Metta hadisi, 2- Namaz hakkında ibn Ömer hadisi, 3- Kadılar üçtür hadisi, 4- ibnAbbas'ın; "Kendilerine güvenilir kişiler bana bu hadisi nakletti. Onlardan biri ve en güvenilir olanı Hz. Ömer'dir" diye başlayan hadisidir. Ebu Davud devamla şöyle der; Yezid ed-Dalani'nin hadisini Ahmed b. Hanbel'e sordum. Yezid'in hadisini (rivayetini bana) yakıştırmayarak beni azarladı ve "Yezid ed-Dalani'ye ne oluyor? (Kendisini de başkalarını da) Katade'nin ashabı arasına sokuyor?" deyip, onun hadisini önemsemedi. Diğer tahric: Tirmizi, tahare
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Daif</td><td>Shuaib Al Arnaut</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>202</td></tr><tr><td>Arabic No</td><td>202</td></tr><tr><td>Reference</td><td>Book 1 Hadith 202</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
عبداللہ بن عباس رضی اللہ عنہما کہتے ہیں کہ رسول اللہ صلی اللہ علیہ وسلم سجدہ کرتے اور (سجدہ میں) سو جاتے، اور خراٹے لینے لگتے تھے، پھر اٹھتے اور نماز پڑھتے، اور وضو نہیں کرتے تھے، (ایک بار) میں نے آپ صلی اللہ علیہ وسلم سے کہا: آپ نے نماز پڑھی اور وضو نہی ان لوگوں نے اس میں سے کچھ ذکر نہیں کیا ہے۔ نیز ابن عباس رضی اللہ عنہما کہتے ہیں کہ نبی اکرم صلی اللہ علیہ وسلم اس طرح ( غفلت ) کی نیند سے محفوظ تھے۔ اور ام المؤمنین عائشہ رضی اللہ عنہا کہتی ہیں کہ نبی اکرم صلی اللہ علیہ وسلم نے فرمایا: میری دونوں آنکھیں سوتی ہیں، لیکن میرا دل نہیں سوتا ۔ اور شعبہ کہتے ہیں کہ قتادہ نے ابوالعالیہ سے صرف چار حدیثیں سنی ہیں: ایک یونس بن متی کی، دوسری ابن عمر رضی اللہ عنہما کی جو نماز کے باب میں مروی ہے، تیسری حدیث «القضاة ثلاثة» ہے، اور چوتھی ابن عباس رضی اللہ عنہما کی حدیث: «حدثني رجال مرضيون منهم عمر وأرضاهم عندي عمر» ہے۔ ابوداؤد کہتے ہیں: میں نے یزید دالانی کی روایت کا احمد بن حنبل سے ذکر کیا، تو انہوں نے مجھے اسے بڑی بات سمجھتے ہوئے ڈانٹا: اور کہا یزید دالانی کو کیا ہے؟ وہ قتادہ کے شاگردوں کی طرف ایسی باتیں منسوب کر دیتے ہیں جنہیں ان لوگوں نے روایت نہیں کی ہیں، امام احمد نے ( دالانی کے ضعیف ہونے کی وجہ سے ) اس حدیث کی پرواہ نہیں کی۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Daif</td><td>Al-Albani</td></tr><tr><td>Daif</td><td>Muhammad Muhyi Al-Din Abdul Hamid</td></tr><tr><td>Daif</td><td>Shuaib Al Arnaut</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>202</td></tr><tr><td>Arabic No</td><td>202</td></tr><tr><td>Reference</td><td>Book 1 Hadith 202</td></tr></tbody></table></div>