## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا الْمَكِّيُّ بْنُ إِبْرَاهِيمَ، حَدَّثَنَا يَزِيدُ بْنُ أَبِي عُبَيْدٍ، عَنْ سَلَمَةَ، قَالَ خَرَجْنَا مَعَ النَّبِيِّ صلى الله عليه وسلم إِلَى خَيْبَرَ فَقَالَ رَجُلٌ مِنْهُمْ أَسْمِعْنَا يَا عَامِرُ مِنْ هُنَيْهَاتِكَ‏.‏ فَحَدَا بِهِمْ، فَقَالَ النَّبِيُّ صلى الله عليه وسلم ‏"‏ مَنِ السَّائِقُ ‏"‏ قَالُوا عَامِرٌ‏.‏ فَقَالَ ‏"‏ رَحِمَهُ اللَّهُ ‏"‏‏.‏ فَقَالُوا يَا رَسُولَ اللَّهِ هَلاَّ أَمْتَعْتَنَا بِهِ‏.‏ فَأُصِيبَ صَبِيحَةَ لَيْلَتِهِ فَقَالَ الْقَوْمُ حَبِطَ عَمَلُهُ، قَتَلَ نَفْسَهُ‏.‏ فَلَمَّا رَجَعْتُ وَهُمْ يَتَحَدَّثُونَ أَنَّ عَامِرًا حَبِطَ عَمَلُهُ، فَجِئْتُ إِلَى النَّبِيِّ صلى الله عليه وسلم فَقُلْتُ يَا نَبِيَّ اللَّهِ فَدَاكَ أَبِي وَأُمِّي، زَعَمُوا أَنَّ عَامِرًا حَبِطَ عَمَلُهُ‏.‏ فَقَالَ ‏"‏ كَذَبَ مَنْ قَالَهَا، إِنَّ لَهُ لأَجْرَيْنِ اثْنَيْنِ، إِنَّهُ لَجَاهِدٌ مُجَاهِدٌ، وَأَىُّ قَتْلٍ يَزِيدُهُ عَلَيْهِ ‏"‏‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6891</td></tr><tr><td>Arabic No</td><td>6891</td></tr><tr><td>Reference</td><td>Book 87 Hadith 29</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
সালামা (রাঃ) হতে বর্ণিত। তিনি বলেন, আমরা নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর সঙ্গে খায়বারের পথে রওয়ানা হলাম। তখন তাদের এক ব্যক্তি বলল, হে আমির! তোমরা আমাদেরকে উট চালনার কিছু গান শোনাও। সে তাদেরকে তা গেয়ে শোনাল। তখন নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বললেনঃ চালকটি কে? তারা বলল, আমির। তিনি বললেন আল্লাহ্ তাকে রহম করুন। তারা বলল, হে আল্লাহর রাসূল! আমাদেরকে তার থেকে দীর্ঘকাল উপকার লাভের সুযোগ করে দিন। পরদিন সকালে আমির নিহত হল। তখন লোকেরা বলতে লাগল তার ‘আমল বিনষ্ট হয়ে গেছে, সে নিজেকে হত্যা করেছে। যখন আমি ফিরলাম, আর লোকেরা বলাবলি করছিল যে, আমিরের ‘আমল বিনষ্ট হয়ে গেছে, তখন আমি নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর নিকট এলাম এবং বললাম, হে আল্লাহর নবী! আমার পিতা-মাতা আপনার প্রতি কুরবান। তাদের ধারণা, আমিরের ‘আমল নষ্ট হয়ে গেছে। তিনি বললেনঃ যে এ কথা বলেছে মিথ্যা বলেছে। কারণ, আমিরের জন্য দ্বিগুণ পুরস্কার। কারণ সে আল্লাহর পথে সাধ্যমত চেষ্টা করেছে, অন্য কোন্ প্রকারের হত্যা তাকে এর চেয়ে অধিক পুরস্কারের অধিকারী করত? [২৪৭৭] (আধুনিক প্রকাশনী- ৬৪১১, ইসলামিক ফাউন্ডেশন- ৬৪২৪)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6891</td></tr><tr><td>Arabic No</td><td>6891</td></tr><tr><td>Reference</td><td>Book 87 Hadith 29</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated Salama:We went out with the Prophet (ﷺ) to Khaibar. A man (from the companions) said, "O 'Amir! Let us hear some of your Huda (camel-driving songs.)" So he sang some of them (i.e. a lyric in harmony with the camels walk). The Prophet (ﷺ) said, "Who is the driver (of these camels)?" They said, "Amir." The Prophet said, "May Allah bestow His Mercy on him !" The people said, "O Allah's Messenger (ﷺ)! Would that you let us enjoy his company longer!" Then 'Amir was killed the following morning. The people said, "The good deeds of 'Amir are lost as he has killed himself." I returned at the time while they were talking about that. I went to the Prophet (ﷺ) and said, "O Allah's Prophet! Let my father be sacrificed for you! The people claim that 'Amir's good deeds are lost." The Prophet (ﷺ) said, "Whoever says so is a liar, for 'Amir will have a double reward as he exerted himself to obey Allah and fought in Allah's Cause. No other way of killing would have granted him greater reward
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6891</td></tr><tr><td>Arabic No</td><td>6891</td></tr><tr><td>Reference</td><td>Book 87 Hadith 29</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Makki bin Ibrahim] telah menceritakan kepada kami [Yazid bin Abi 'Ubaid] dari [Salamah bin Al Akwa'] mengatakan, Dahulu kami berangkat bersama Nabi Shallallahu'alaihiwasallam ke Khaibar. Salah seorang pasukan berujar; 'Wahai Amir, perdengarkan syair-syairmu kepada kami! ' Lantas Amir Ibn Al Akwa' memperdengarkan bait-bait syairnya sehingga terdengar oleh mereka. Selanjutnya Nabi shallallahu 'alaihi wasallam bertanya; "Siapa yang menggiring unta-unta kita?" 'Sahabat kita, Amir bin Al akwa' Jawab para sahabat. Nabi Terus memanjatkan doa: "Semoga Allah merahmati dia!" Para sahabat berujar; 'Ya Rasulullah, apakah engkau memberi kami kenyamanan lewat perantaraannya' pagi harinya ia meninggal, selanjutnya para sahabat berkomentar (mengenai peristiwa 'Amir); 'Sungguh amir sia-sia amalnya, ia telah membunuh dirinya.' Ketika aku pulang, para sahabat berbincang-bincang dengan mengatakan bahwa Amir bin Al Akwa' sia-sia amalnya karena telah membunuh dirinya sendiri. Maka kudatangi Nabi shallallahu 'alaihi wasallam dan aku berkata; 'ya Nabiyullah, demi ayahku dan ibuku menjadi tebusanmu, orang-orang beranggapan bahwa saudaraku, Amir, sia-sia amalnya! ' maka Beliau bersabda: "Bohong semua yang mengatakan seperti itu, bahkan ia memperoleh dua pahala, sungguh ia orang yang bersungguh-sungguh sekaligus menjadi mujahid, mana ada pembunuhan yang lebih sadis dari seperti yang dialaminya?
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6891</td></tr><tr><td>Arabic No</td><td>6891</td></tr><tr><td>Reference</td><td>Book 87 Hadith 29</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
சலமா பின் அல்அக்வஉ (ரலி) அவர்கள் கூறியதாவது: நாங்கள் நபி (ஸல்) அவர்களுடன் கைபரை நோக்கி (போருக்காக)ப் புறப்பட்டோம். அப்போது மக்களில் ஒருவர் (என் தந்தையின் சகோதரரிடம்) “ஆமிரே! உங்கள் கவிதைகளில் சிலவற்றை(ப் பாடி) எங்களைச் செவியுறச் செய்யமாட்டீர்களா?” என்று கூறினார். ஆகவே, ஆமிர் (ரலி) அவர்கள் (சில கவிதைகளைப் பாடி) மக்களின் ஒட்டகங்களை விரைந்தோடச் செய்தார்கள். அப்போது நபி (ஸல்) அவர்கள், “இந்த ஒட்டகவோட்டி யார்?” என்று கேட்டார்கள். “ஆமிர் பின் அல்அக்வஉ” என்று மக்கள் பதிலளித்தனர். அப்போது நபி (ஸல்) அவர்கள், “அவருக்கு அல்லாஹ் அருள்புரிவானாக” என்று கூறினார்கள். (அந்தப் பிரார்த்தனையின் பொருளைப் புரிந்துகொண்ட) மக்கள், “அவர் (நீண்ட காலம் உயிர் வாழ்வதன்) மூலம் எங்களுக்குப் பயன் கிடைக்க (பிரார்த்தனை) செய்யக் கூடாதா (அல்லாஹ்வின் தூதரே!)?” என்று கேட்டார்கள். அவர் அன்றைய இரவின் (அடுத்த நாள்) காலையில் (தமது முழங்காலில் தமது வாளாலேயே) தாக்கப்பட்டு இறந்தார். அப்போது மக்கள், “ஆமிரின் நற்செயல்கள் அழிந்துவிட்டன; அவர் (தமது வாளால் தம்மைத்தாமே குத்திக்கொண்டு) தற்கொலை செய்துகொண்டார்” என்று பேசினர். (கைபரிலிருந்து) நான் திரும்பியபோது “ஆமிரின் நற்செயல்கள் அழிந்துபோயின” என்று மக்கள் பேசிக்கொண்டனர். ஆகவே, நான் நபி (ஸல்) அவர்களிடம் சென்று, “அல்லாஹ்வின் தூதரே! என் தந்தையும் என் தாயும் தங்களுக்கு அர்ப்பணமாகட்டும்! (என் தந்தையின் சகோதரர்) ஆமிர் (ரலி) அவர்களின் நற்செயல்கள் அழிந்துவிட்டன என்று மக்கள் கருதுகின்றனர்” என்று சொன்னேன். அதற்கு நபி (ஸல்) அவர்கள், “இதைக் கூறியவர் உண்மைக்குப் புறம்பாகக் கூறிவிட்டார். ஆமிருக்கு நிச்சயமாக (நற்செயல்கள் புரிந்த நன்மை, அறப்போர் புரிந்த நன்மை ஆகிய) இரண்டு நன்மைகள் உண்டு. அவர் துன்பங்களைத் தாங்கினார்; (இறைவழியில்) அறப்போரும் புரிந்தார். அவர் பெற்ற நற்பலனைவிட அதிகமான நற்பலனைப் பெற்றுத்தரும் (வீர) மரணம் எது?” என்று கேட்டார்கள்.30 அத்தியாயம் : 87
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6891</td></tr><tr><td>Arabic No</td><td>6891</td></tr><tr><td>Reference</td><td>Book 87 Hadith 29</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Seleme şöyle demiştir: Resulullah Sallallahu Aleyhi ve Sellem'la birlikte Hayber'e çıkmıştık. Onlardan birisi "Ey Amir! Bize kısa şiirlerinden bir şeyler söyle" dedi. O kişi de bunları şiir söyleyerek götürdü. Bunun üzerine Nebi Sallallahu Aleyhi ve Sellem "Sevkeden kimdir?" diye sordu. Oradakiler "Amir' dir" dediler. Resulullah Sallallahu Aleyhi ve Sellem 'Iillah ona rahmet eylesin" dedi. İnsanlar "Ya Resulallah! Keşke bizi ondan biraz daha yararlandırsaydınız!" dediler. Amir, o gecenin sabahında yaralandı. İnsanlar "Amir'in ameli boşa gitti. Kendi kendini öldürdü" dediler. Onlar Amir'in ameli boşa gitti derken ben döndüm ve Resulullah Sallallahu Aleyhi ve Sellem'e dedim ki: "Ya Resulallah! Anam babam sana feda olsun! İnsanlar Amir'in amelinin boşa gittiğini söylüyorlar." Resulullah Sallallahu Aleyhi ve Sellem "Bunu söyleyenler yalan söylerler. Onun iki sevabı var. O hem cahid ve hem de mücahiddir. Hangi katil onun ecrine ecir katabilir" dedi. Fethu'l-Bari Açıklaması: "Kendisini yanlışlıkla öldürenin diyetinin olmadığı" konusunda İsma1li şöyle der: Kendisini teammüden öldüren e de diyet yoktur. Netice olarak "yanlışlık" kelimesinin anlama kattığı herhangi bir farklılık mevcut değildir. Öyle anlaşılıyor ki İmam BuhM' öldürmeyi "yanlışlık" kelimesiyle bu konunun ihtilaflı olması dolayısıyla kayıtlamışhr. İbn Battal şöyle der: Evzaı, Ahmed b. Hanbel ve İshak, bu durumdaki kimsenin akilesinin diyetini ödemesi gerekir demişlerdir. Böyle bir kimse yaşadığı takdirde bu diyeti onlardan alır, öldüğü takdirde diyeti varislerinindir. Çoğunluğu oluşturan fıkıh bilginleri şöyle der: Bu konuda herhangi bir şey vermek gerekli değildir. Burada yer verdiğimiz Amir olayı çoğunluğu destekleyen bir delildir. Zira Nebi Sallallahu Aleyhi ve Sellem'in bu olayda Amir için herhangi bir şey vermesi gerektiğine hükmettiği nakledilmemiştir. Şayet bir şey vermek gerekseydi, Resulullah Sallallahu Aleyhi ve Sellem bunu açıklardı. Zira ihtiyaç anında açıklamayı ertelerrek caiz değildir. Bilginler bir kimse teammüden veya yanlışlıkla bir tarafını kestiği takdirde ona herhangi bir şey vermek gerekmediği noktasında görüş birliği etmişlerdir. İbn Battal şöyle demiştir: Bu rivayet yolunda Amir'in kendisini ne şekilde öldürdüğü belirtilmemektedir. Bu konu Edep bölümünde daha önce geçmişti. Orada şöyle demiştik: "Amir'in kılıcı kısaydı. Bir yahudiye saldırmak üzere kılıcını eline almıştı. Kılıcın ucu döndü ve onun dizine geldi
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6891</td></tr><tr><td>Arabic No</td><td>6891</td></tr><tr><td>Reference</td><td>Book 87 Hadith 29</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ہم سے مکی بن ابراہیم نے بیان کیا، کہا ہم سے یزید بن ابی عبید نے، اور ان سے سلمہ رضی اللہ عنہ نے بیان کیا کہ ہم نبی کریم صلی اللہ علیہ وسلم کے ساتھ خیبر کی طرف نکلے۔ جماعت کے ایک صاحب نے کہا عامر! ہمیں اپنی حدی سنائیے۔ انہوں نے حدی خوانی شروع کی تو نبی کریم صلی اللہ علیہ وسلم نے پوچھا کہ کون صاحب گا گا کر اونٹوں کو ہانک رہے ہیں؟ لوگوں نے کہا کہ عامر ہیں۔ نبی کریم صلی اللہ علیہ وسلم نے فرمایا، اللہ ان پر رحم کرے۔ صحابہ نے عرض کیا: یا رسول اللہ! آپ نے ہمیں عامر سے فائدہ کیوں نہیں اٹھانے دیا۔ چنانچہ عامر رضی اللہ عنہ اسی رات کو اپنی ہی تلوار سے شہید ہو گئے۔ لوگوں نے کہا کہ ان کے اعمال برباد ہو گئے، انہوں نے خودکشی کر لی ( کیونکہ ایک یہودی پر حملہ کرتے وقت خود اپنی تلوار سے زخمی ہو گئے تھے ) جب میں واپس آیا اور میں نے دیکھا کہ لوگ آپس میں کہہ رہے ہیں کہ عامر کے اعمال برباد ہو گئے تو میں نبی کریم صلی اللہ علیہ وسلم کی خدمت میں حاضر ہوا اور عرض کیا: اے اللہ کے نبی! آپ پر میرے باپ اور ماں فدا ہوں، یہ لوگ کہتے ہیں کہ عامر کے سارے اعمال برباد ہوئے۔ نبی کریم صلی اللہ علیہ وسلم نے فرمایا کہ جو شخص یہ کہتا ہے غلط کہتا ہے۔ عامر کو دوہرا اجر ملے گا وہ ( اللہ کے راستہ میں ) مشقت اٹھانے والے اور جہاد کرنے والے تھے اور کس قتل کا اجر اس سے بڑھ کر ہو گا؟
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6891</td></tr><tr><td>Arabic No</td><td>6891</td></tr><tr><td>Reference</td><td>Book 87 Hadith 29</td></tr></tbody></table></div>