## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا إِسْحَاقُ بْنُ مَنْصُورٍ، حَدَّثَنَا رَوْحُ بْنُ عُبَادَةَ، حَدَّثَنَا حُسَيْنٌ، عَنْ يَحْيَى بْنِ أَبِي كَثِيرٍ، عَنْ أَبِي سَلَمَةَ بْنِ عَبْدِ الرَّحْمَنِ، عَنْ عَبْدِ اللَّهِ بْنِ عَمْرٍو، قَالَ دَخَلَ عَلَىَّ رَسُولُ اللَّهِ صلى الله عليه وسلم فَقَالَ ‏"‏ أَلَمْ أُخْبَرْ أَنَّكَ تَقُومُ اللَّيْلَ وَتَصُومُ النَّهَارَ ‏"‏‏.‏ قُلْتُ بَلَى‏.‏ قَالَ ‏"‏ فَلاَ تَفْعَلْ، قُمْ وَنَمْ، وَصُمْ وَأَفْطِرْ، فَإِنَّ لِجَسَدِكَ عَلَيْكَ حَقًّا، وَإِنَّ لِعَيْنِكَ عَلَيْكَ حَقًّا، وَإِنَّ لِزَوْرِكَ عَلَيْكَ حَقًّا، وَإِنَّ لِزَوْجِكَ عَلَيْكَ حَقًّا، وَإِنَّكَ عَسَى أَنْ يَطُولَ بِكَ عُمُرٌ، وَإِنَّ مِنْ حَسْبِكَ أَنْ تَصُومَ مِنْ كُلِّ شَهْرٍ ثَلاَثَةَ أَيَّامٍ، فَإِنَّ بِكُلِّ حَسَنَةٍ عَشْرَ أَمْثَالِهَا فَذَلِكَ الدَّهْرُ كُلُّهُ ‏"‏‏.‏ قَالَ فَشَدَّدْتُ فَشُدِّدَ عَلَىَّ فَقُلْتُ فَإِنِّي أُطِيقُ غَيْرَ ذَلِكَ‏.‏ قَالَ ‏"‏ فَصُمْ مِنْ كُلِّ جُمُعَةٍ ثَلاَثَةَ أَيَّامٍ ‏"‏‏.‏ قَالَ فَشَدَّدْتُ فَشُدِّدَ عَلَىَّ قُلْتُ أُطِيقُ غَيْرَ ذَلِكَ‏.‏ قَالَ ‏"‏ فَصُمْ صَوْمَ نَبِيِّ اللَّهِ دَاوُدَ ‏"‏‏.‏ قُلْتُ وَمَا صَوْمُ نَبِيِّ اللَّهِ دَاوُدَ قَالَ ‏"‏ نِصْفُ الدَّهْرِ ‏"‏‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6134</td></tr><tr><td>Arabic No</td><td>6134</td></tr><tr><td>Reference</td><td>Book 78 Hadith 161</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
‘আবদুল্লাহ ইবনু ‘আমর (রাঃ) হতে বর্ণিত। তিনি বলেন, একদিন নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম আমার নিকট এসে বললেনঃ আমাকে কি এ খবর জানানো হয়নি যে, তুমি সারা রাত সালাতে অতিবাহিত কর। আর সারা দিন সিয়াম পালন কর। তিনি বললেনঃ তুমি (এ রকম) করো না। রাতের কিয়দংশ সালাত আদায় কর, আর ঘুমাও। কয়েকদিন সওম পালন কর, আর কয়েকদিন ইফতার কর (সওম ভঙ্গ কর)। তোমার উপর তোমার শরীরের হক আছে। তোমার উপর তোমার চোখের হক আছে, তোমার উপর তোমার মেহ্মানের হক আছে, আর তোমার উপর তোমার স্ত্রীরও হক আছে। নিশ্চয়ই তুমি তোমার আয়ু দীর্ঘ হবার আশা কর। কাজেই প্রতি মাসে তিন দিন সিয়াম পালনই তোমার পক্ষে যথেষ্ট। কেননা, নিশ্চয়ই প্রতিটি নেক কাজের পরিবর্তে তার দশগুণ সাওয়াব দেয়া হয়। সুতরাং এভাবে সারা বছরেই সিয়ামের সওয়াব পাওয়া যায়। তখন আমি কঠোর ব্যবস্থা চাইলে, আমাকে কঠোর ব্যবস্থা দেয়া হলো। আমি বললামঃ এর চেয়েও অধিক পালনের সামর্থ্য আমার আছে। তিনি বললেনঃ তা হলে তুমি প্রতি সপ্তাহে তিন দিন সিয়াম পালন কর। তখন আমি আরও কঠোর ব্যবস্থা চাইলে, আমাকে কঠোর দেয়া হলো। আমি বললামঃ আমি এর চেয়ে অধিক সিয়ামের সামর্থ্য রাখি। তিনি বললেনঃ তবে তুমি আল্লাহর নবী দাঊদ (আ.)-এর সিয়াম পালন কর। আমি বললামঃ হে আল্লাহর নবী! দাঊদ (আ.)-এর সিয়াম কী রকম? তিনি বললেন, আধা বছর সিয়াম পালন। [১১৩১] (আধুনিক প্রকাশনী- ৫৬৯৪, ইসলামিক ফাউন্ডেশন- ৫৫৯১)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6134</td></tr><tr><td>Arabic No</td><td>6134</td></tr><tr><td>Reference</td><td>Book 78 Hadith 161</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated 'Abdullah bin 'Amr:Allah's Messenger (ﷺ) entered upon me and said, "Have I not been informed that you offer prayer all the night and fast the whole day?" I said, "Yes." He said, "Do not do so; Offer prayer at night and also sleep; Fast for a few days and give up fasting for a few days because your body has a right on you, and your eye has a right on you, and your guest has a right on you, and your wife has a right on you. I hope that you will have a long life, and it is sufficient for you to fast for three days a month as the reward of a good deed, is multiplied ten times, that means, as if you fasted the whole year." I insisted (on fasting more) so I was given a hard instruction. I said, "I can do more than that (fasting)" The Prophet said, "Fast three days every week." But as I insisted (on fasting more) so I was burdened. I said, "I can fast more than that." The Prophet (ﷺ) said, "Fast as Allah's prophet David used to fast." I said, "How was the fasting of the prophet David?" The Prophet (ﷺ) said, "One half of a year (i.e. he used to fast on alternate days)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6134</td></tr><tr><td>Arabic No</td><td>6134</td></tr><tr><td>Reference</td><td>Book 78 Hadith 161</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Ishaq bin Manshur] telah menceritakan kepada kami [Rauh bin 'Ubadah] telah menceritakan kepada kami [Husain] dari [Yahya bin Abu Katsir] dari [Abu Salamah bin Abdurrahman] dari [Abdullah bin 'Amru] dia berkata; "Rasulullah shallallahu 'alaihi wasallam menemuiku, lalu beliau bersabda: "Aku memperoleh berita bahwa kamu bangun di malam hari dan berpuasa di siang hari, benarkah itu?" Aku menjawab; "Benar." Beliau bersabda: "Jangan kamu lakukannya; namun tidur dan bangunlah, berpuasa dan berbukalah. Karena tubuhmu memiliki hak atas dirimu, kedua matamu memiliki hak atas dirimu, tamumu memiliki hak atas dirimu, istrimu memiliki hak atas dirimu. Sungguh, semoga panjang umur dan cukup bagimu berpuasa tiga hari dalam setiap bulan, dan suatu kebaikan akan dibalas dengan sepuluh kali lipatnya, itulah puasa Dahr." Abdullah bin 'Amru berkata; "Aku bersikap keras dan beliau pun bersikap keras kepadaku, lalu kataku; "Sungguh aku masih kuat melakukan lebih dari itu?". Beliau bersabda: "Berpuasalah tiga hari setiap Jum'at." Abdullah bin 'Amru berkata; "Aku bersikap keras dan beliau pun bersikap keras kepadaku, lalu kataku; "Sungguh aku masih kuat melakukan lebih dari itu?" Beliau bersabda: "Kalau begitu, berpuasalah seperti puasanya Nabiyullah Daud." Aku bertanya; "Bagaimana puasa Nabiyullah Daud?" Beliau bersabda: "Yaitu puasa setengah zaman (sehari puasa sehari berbuka)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6134</td></tr><tr><td>Arabic No</td><td>6134</td></tr><tr><td>Reference</td><td>Book 78 Hadith 161</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
அப்துல்லாஹ் பின் அம்ர் (ரலி) அவர்கள் கூறியதாவது: அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் என்னிடம் வந்து, “நீர் இரவெல்லாம் நின்று வணங்குவதாகவும் பகலெல்லாம் நோன்பு நோற்பதாகவும் எனக்குத் தெரிவிக்கப்பட்டதே! (அது உண்மை தானா?)” என்று கேட்டார்கள். நான், “ஆம்” என்று பதிலளித்தேன். (அதற்கு) நபி (ஸல்) அவர்கள், “அவ்வாறு செய்யாதீர்! (சிறிது நேரம்) தொழுவீராக! (சிறிது நேரம்) உறங்குவீராக! (சிலநாட்கள்) நோன்பு நோற்பீராக! (சில நாட்கள் நோன்பை) விட்டுவிடுவீராக! ஏனெனில், உமது உடலுக்குச் செய்ய வேண்டிய கடமையும் உமக்கு உண்டு; உமது கண்ணுக்குச் செய்ய வேண்டிய கடமையும் உமக்கு உண்டு; உம்முடைய விருந்தினருக்குச் செய்ய வேண்டிய கடமையும் உமக்கு உண்டு; உம்முடைய துணைவிக்குச் செய்ய வேண்டிய கடமையும் உமக்கு உண்டு. உமது வயது நீளக்கூடும். (அப்போது உம்மால் தொடர்நோன்பும் தொடர் வழிபாடும் சாத்தியப்படாமல்போகலாம். ஆகவே) ஒவ்வொரு மாதமும் (ஏதேனும்) மூன்று நாட்கள் நோன்பு நோற்பது உமக்குப் போதுமானதாகும். ஏனெனில், ஒவ்வொரு நற்செயலுக்கும் பிரதியாக அது போன்ற பத்து மடங்கு (நற்பலன்)கள் உண்டு. (இதன்படி மாதத்தில் மூன்று நாட்கள் நோன்பு நோற்பது மாதம் முழுவதும் நோற்றதற்குச் சமமாகும்.) எனவே, இது காலமெல்லாம் நோற்றதாக அமையும்” என்று கூறினார்கள். ஆனால், நான் சிரமத்தை வலிந்து ஏற்றுக்கொண்டேன்; அதனால் என்மீது சிரமம் சுமத்தப்பட்டது. நான் “(அல்லாஹ்வின் தூதரே!) இதற்கு மேலும் என்னால் முடியும்” என்றேன். நபி (ஸல்) அவர்கள், “அவ்வாறாயின், வாரத்திற்கு மூன்று நோன்பு நோற்றுக்கொள்க” என்றார்கள். நான் (மறுபடியும்) சிரமத்தை வலிந்து ஏற்றுக்கொண்டேன்; அதனால் என்மீது சிரமம் சுமத்தப்பட்டது. “இதற்கு மேலும் என்னால் முடியும் (அல்லாஹ்வின் தூதரே!)” என்றேன். நபி (ஸல்) அவர்கள், “அவ்வாறாயின், இறைத்தூதர் தாவூத் (அலை) அவர்கள் நோற்றவாறு நோன்பு நோற்றுக்கொள்வீராக” என்றார்கள். “இறைத்தூதர் தாவூத் (அலை) அவர்களின் நோன்பு எது?” என்று கேட்டேன். “(ஒருநாள் விட்டு ஒருநாள் நோற்பதால்) வருடத்தில் பாதி நாட்கள் நோற்பதாகும்” என்று பதிலளித்தார்கள்.151 அத்தியாயம் : 78
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6134</td></tr><tr><td>Arabic No</td><td>6134</td></tr><tr><td>Reference</td><td>Book 78 Hadith 161</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Abdullah İbn Amr'dan, dedi ki: "Resulullah Sallallahu Aleyhi ve Sellem yanıma girip: Bütün gece namaz kıldığın, gündüzleri de oruç tuttuğun bana haber verilmedi mi (sanıyorsun), buyurdu. Ben, öyledir, dedim. O: Hayır, böyle yapma! Bir süre namaz kıl, bir süreuyu. Hem oruç tut, hem ye. Şüphesiz senin bedeninin senin üzerinde bir hakkı vardır, gözünün senin üzerinde bir hakkı vardır, seni ziyarete gelenlerin senin üzerinde bir hakkı vardır, zevcenin senin üzerinde bir hakkı vardır. Gerçekten senin uzun bir ömrünün olacağını ümit ediyorum. Bu sebeple her ay üç gün oruç tutman senin için yeterlidir. Çünkü her bir hasene on misli ile mükafat1andırılır. Böylelikle bu, senenin tümü demek olur, buyurdu. Abdullah İbn Amr dedi ki: Ben işi sıkı tuttukça benim aleyhime de zorlaştınldı. Benim bundan fazlasına gücüm yeter, dedim. O: O halde her Cuma (her hafta) üç gün. oruç tut, dedi. Abdullah İbn Amr: Ben işi sıkı tuttum, bundan dolayı iş aleyhime daha da ağırlaştınldı. Benim bundan başkasına da gücüm yeter deyince, Allah Rasulü: O halde Allah'ın Nebii Davud'un orucunu tut, buyurdu. Ben: Allah'ın Nebii Davud'un orucu ne demektir, diye sordum. O: Yılın yarısıdır, buyurdu." Hadis, açıklamalarıyla birlikte Oruç bölümünde (1974.hadiste) geçmiş bulunmaktadır. Burada zikredilmesinden maksat ise: "Ve şÜphesiz seni ziyarete gelenlerin de senin üzerinde bir hakkı vardır." buyruğudur
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6134</td></tr><tr><td>Arabic No</td><td>6134</td></tr><tr><td>Reference</td><td>Book 78 Hadith 161</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ہم سے اسحاق بن منصور نے بیان کیا، کہا ہم سے روح بن عبادہ نے، کہا ہم سے حسین نے، ان سے یحییٰ بن ابی بکر نے، ان سے ابوسلمہ بن عبدالرحمٰن نے اور ان سے عبداللہ بن عمرو رضی اللہ عنہما نے بیان کیا کہ نبی کریم صلی اللہ علیہ وسلم میرے پاس تشریف لائے اور فرمایا، کیا یہ میری خبر صحیح ہے کہ تم رات بھر عبادت کرتے رہتے ہو اور دن میں روزے رکھتے ہو؟ میں نے کہا کہ جی ہاں یہ صحیح ہے۔ نبی کریم صلی اللہ علیہ وسلم نے فرمایا کہ ایسا نہ کرو، عبادت بھی کرو اور سو بھی، روزے بھی رکھو اور بلا روزے بھی رہو، کیونکہ تمہارے جسم کا بھی تم پر حق ہے، تمہاری آنکھوں کا بھی تم پر حق ہے، تم سے ملاقات کے لیے آنے والوں کا بھی تم پر حق ہے، تمہاری بیوی کا بھی تم پر حق ہے، امید ہے کہ تمہاری عمر لمبی ہو گی، تمہارے لیے یہی کافی ہے کہ ہر مہینہ میں تین روزے رکھو، کیونکہ ہر نیکی کا بدلہ دس گناہ ملتا ہے، اس طرح زندگی بھر کا روزہ ہو گا۔ انہوں نے بیان کیا کہ میں نے سختی چاہی تو آپ نے میرے اوپر سختی کر دی۔ میں نے عرض کیا کہ میں اس سے زیادہ کی طاقت رکھتا ہوں۔ نبی کریم صلی اللہ علیہ وسلم نے فرمایا کہ پھر ہر ہفتے تین روزہ رکھا کر، بیان کیا کہ میں نے اور سختی چاہی اور آپ نے میرے اوپر سختی کر دی۔ میں نے عرض کیا کہ میں اس سے بھی زیادہ کی طاقت رکھتا ہوں۔ نبی کریم صلی اللہ علیہ وسلم نے فرمایا کہ پھر اللہ کے نبی داؤد علیہ السلام جیسا روزہ رکھ۔ میں نے پوچھا، اللہ کے نبی داؤد علیہ السلام کا روزہ کیسا تھا۔ نبی کریم صلی اللہ علیہ وسلم نے فرمایا کہ ایک دن روزہ ایک دن افطار گویا آدھی عمر کے روزے۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6134</td></tr><tr><td>Arabic No</td><td>6134</td></tr><tr><td>Reference</td><td>Book 78 Hadith 161</td></tr></tbody></table></div>