## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
وَزَادَنَا عَمْرٌو قَالَ أَخْبَرَنَا عَبْدُ الرَّحْمَنِ بْنُ عَبْدِ اللَّهِ بْنِ دِينَارٍ، عَنْ أَبِيهِ، عَنْ أَبِي صَالِحٍ، عَنْ أَبِي هُرَيْرَةَ، عَنِ النَّبِيِّ صلى الله عليه وسلم قَالَ ‏ "‏ تَعِسَ عَبْدُ الدِّينَارِ وَعَبْدُ الدِّرْهَمِ وَعَبْدُ الْخَمِيصَةِ، إِنْ أُعْطِيَ رَضِيَ، وَإِنْ لَمْ يُعْطَ سَخِطَ، تَعِسَ وَانْتَكَسَ، وَإِذَا شِيكَ فَلاَ انْتَقَشَ، طُوبَى لِعَبْدٍ آخِذٍ بِعِنَانِ فَرَسِهِ فِي سَبِيلِ اللَّهِ، أَشْعَثَ رَأْسُهُ مُغْبَرَّةٍ قَدَمَاهُ، إِنْ كَانَ فِي الْحِرَاسَةِ كَانَ فِي الْحِرَاسَةِ، وَإِنْ كَانَ فِي السَّاقَةِ كَانَ فِي السَّاقَةِ، إِنِ اسْتَأْذَنَ لَمْ يُؤْذَنْ لَهُ، وَإِنْ شَفَعَ لَمْ يُشَفَّعْ ‏"‏‏.‏ قَالَ أَبُو عَبْدِ اللَّهِ لَمْ يَرْفَعْهُ إِسْرَائِيلُ وَمُحَمَّدُ بْنُ جُحَادَةَ عَنْ أَبِي حَصِينٍ وَقَالَ تَعْسًا‏.‏ كَأَنَّهُ يَقُولُ فَأَتْعَسَهُمُ اللَّهُ‏.‏ طُوبَى فُعْلَى مِنْ كُلِّ شَىْءٍ طَيِّبٍ، وَهْىَ يَاءٌ حُوِّلَتْ إِلَى الْوَاوِ وَهْىَ مِنْ يَطِيبُ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2887</td></tr><tr><td>Arabic No</td><td>2887</td></tr><tr><td>Reference</td><td>Book 56 Hadith 102</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
আবূ হুরাইরাহ্ (রাঃ) থেকে আমাদের অতিরিক্ত বর্ণনা করেন যে, নবী (সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম) বলেছেন, লাঞ্ছিত হোক দ্বীনারের গোলাম, দিরহামের গোলাম এবং শালের গোলাম। তাকে দেয়া হলে সন্তুষ্ট হয়, না দেয়া হলে অসন্তুষ্ট হয়। এরা লাঞ্ছিত হোক, অপমানিত হোক। (তাদের পায়ে) কাঁটা বিদ্ধ হলে তা কেউ তুলে দিবে না। ঐ ব্যক্তির জন্য সুসংবাদ, যে ঘোড়ার লাগাম ধরে জিহাদের জন্য প্রস্তুত রয়েছে, যার মাথার চুল উস্ক খুস্ক এবং পা ধূলি মলিন। তাকে পাহারায় নিয়োজিত করলে পাহারায় থাকে আর (দলের) পেছনে পেছনে রাখলে পেছনেই থাকে। সে কারো সাক্ষাতের অনুমতি চাইলে তাকে অনুমতি দেয়া হয় না এবং কোন বিষয়ে সুপারিশ করলে তার সুপারিশ কবূল করা হয় না। وَقَالَ فَتَعْسًا كَأَنَّهُ يَقُوْلُ فَأَتْعَسَهُمْ اللهُ طُوْبَى فُعْلَى مِنْ كُلِّ شَيْءٍ طَيِّبٍ وَهِيَ يَاءٌ حُوِّلَتْ إِلَى الْوَاوِ وَهِيَ مِنْ يَطِيْبُ فَتَعْسًا বলা হয়فَأَتْعَسَهُمْ اللهُ অর্থাৎ আল্লাহ তাদের অপমানিত করুক। طُوْبَى অর্থ উত্তম। فُعْلَى... এর কাঠামোতে গঠিত। মূলত طيبى ছিল। يَاءٌ কে وَاوِ দ্বারা পরিবর্তন করা হয়েছে। (২৮৮৬) (আধুনিক প্রকাশনীঃ ২৬৭৪, ইসলামিক ফাউন্ডেশনঃ ২৬৮৫ শেষাংশ)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2887</td></tr><tr><td>Arabic No</td><td>2887</td></tr><tr><td>Reference</td><td>Book 56 Hadith 102</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated Abu Huraira:The Prophet (ﷺ) said, " Let the slave of Dinar and Dirham, of Quantify and Khamisa perish as he is pleased if these things are given to him, and if not, he is displeased. Let such a person perish and relapse, and if he is pierced with a thorn, let him not find anyone to take it out for him. Paradise is for him who holds the reins of his horse to strive in Allah's Cause, with his hair unkempt and feet covered with dust: if he is appointed in the vanguard, he is perfectly satisfied with his post of guarding, and if he is appointed in the rearward, he accepts his post with satisfaction; (he is so simple and unambiguous that) if he asks for permission he is not permitted, and if he intercedes, his intercession is not accepted
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2887</td></tr><tr><td>Arabic No</td><td>2887</td></tr><tr><td>Reference</td><td>Book 56 Hadith 102</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah bercerita kepada kami [Yahya binYusuf] telah mengabarkan kepada kami [Abu Bakar. Yaitu Ibnu 'Ayyasy] dari [Abu Hashin] dari [Abu Shalih] dari [Abu Hurairah radliallahu 'anhu] dari Nabi shallallahu 'alaihi wasallam bersabda: "Binasalah hamba dinar, dirham, kain tebal dan sutra. Jika diberi maka ia ridha jika tidak diberi maka ia tidak ridha". [Israil] tidak memarfu'kannya dan [Muhammad bin Juhadah] dari [Abi Hashin] dan ['Amru] menambahkan kepada kami, dia berkata telah mengabarkan kepada kami ['Abdur Rahman bin 'Abdullah bin Dinar] dari [bapaknya] dari [Abu Shalih] dari [Abu Hurairah radliallahu 'anhu] dari Nabi Sallallhu 'Alaihi Wasallam bersabda: "Binasalah hamba dinar, dirham, kain tebal dan sutra, jika diberi maka ia ridha jika tidak diberi maka ia mencela. Binasalah dan merugilah ia, jika tertusuk duri maka ia tidak akan terlepas darinya. Beruntunglah hamba yang mengambil tali kendali kuda fii sabilillah, rambutnya kusut dan kakinya berdebu. Jika ia menjaga maka ia benar-benar menjaga, jika ia berada dibarisan belakang maka ia benar-benar menjaga barisan belakang, jika ia meminta izin maka ia tidak akan diberi izin, jika ia menengahi maka penengahannya tidak diterima" (karena menghindari riya' dan pamer dan tidak punya ambisi apapun). Firman Allah fata'san maksudnya Allah berfirman: "Maka Allah membinasakan mereka". Kata thuubaa mengikuti wazan (suku kata) fu'laa yang artinya kebaikan yang diberikan. Kata itu menggunakan huruf ي (ya') yang diubah ke huruf و (wau) berasal dari kata yathibu (baik)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2887</td></tr><tr><td>Arabic No</td><td>2887</td></tr><tr><td>Reference</td><td>Book 56 Hadith 102</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
அபூஹுரைரா (ரலி) அவர்கள் கூறியதாவது: பொற்காசின் அடிமையும், வெள்ளிக் காசின் அடிமையும், கோடுபோட்ட சதுர கறுப்புத் துணியின் அடிமையும் அழிந் தான். அவனுக்கு (செல்வம்) கொடுக்கப் பட்டால் திருப்தியடைவான்; (செல்வம்) வழங்கப்படாவிட்டால் கோபமடைவான். அவன் இழப்புக்குரியவனாகட்டும்! அவன் அழியட்டும். அவனுக்கு முள் தைத்துவிட்டால் அதை எடுக்க ஆளில்லாமல் தவிக்கட்டும்! இறைவழியில் (போர் புரிந்திட) தமது குதிரையின் கடிவாளத்தைக் கையில் பிடித்துக்கொண்டு, பரட்டைத் தலையுடன் இரு கால்களும் புழுதியடைந்தவராகச் செல்கின்ற அடியாருக்கு வாழ்த்துகள்! (அவர் எத்தகையவர் என்றால்) அவர் (படையின் முன்னணிக்) காவல் அணியில் நியமிக்கப்பட்டிருப்பாராயின் அதிலேயே (ஆட்சேபணை ஏதுமின்றி) இருப்பார்; பின்னணிப் படையில் நியமிக்கப்பட்டிருப்பாராயின் அதிலும் (எந்த முணுமுணுப்புமின்றி திருப்தியுடன்) இருப்பார். அவர் (யாரையும் சந்திக்க) அனுமதி கேட்டால் அவருக்கு அனுமதி தரப்படாது; அவர் பரிந்துரை செய்தால் அது (மக்களால்) ஏற்கப்படாது. (அந்த அளவுக்கு சாமானியராக, எளியவராகக் கருதப்படுவார்.) அபூஅப்தில்லாஹ் (புகாரீ) கூறுகி றேன்: (‘அழியட்டும்!› என்பதைக் குறிக்க) மூலத்தில் யிதஇஸ’ எனும் சொல் ஆளப்பட் டுள்ளது. இதற்கு, ‘அவனை அல்லாஹ் அழிக்கட்டும்!› என்பது பொருளாகும். (யிவாழ்த்து’ என்பதைக் குறிக்க) யிதூபா’ எனும் சொல் ஆளப்பட்டுள்ளது. இது யிதய்யிப்’ (நல்லது, தூயது) என்பதன் யிஃபுஅலா’ வாய்ப்பாட்டில் அமைந்ததாகும். யிதுய்பா’ என்பதே யிதூபா’ என யிவாவு’ உள்ளதாக மருவியுள்ளது. அத்தியாயம் : 56
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2887</td></tr><tr><td>Arabic No</td><td>2887</td></tr><tr><td>Reference</td><td>Book 56 Hadith 102</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ebu Hureyre'nin naklettiğine göre Resul-i Ekrem Sallallahu Aleyhi ve Sellem şöyle buyurdu: "Altın'a ve gümüş'e kul olan kahrolsun, sürünsün! Kadifeye ve işlemeli kumaşlara kul olan kahrolsun, sürünsün! Böyle menfaat düşkünü insanlara bir şey versen hoşuna gider fakat hiçbir şey vermezsen razı olmaz." Hadisin ravilerinden İsrail ve Muhammed İbn Cuhade bu hadisi Ebu Husayn'dan merfu olarak rivayet etmemişlerdir. [-2887-] Ebu Hureyre'nin naklettiğine göre Resul-i Ekrem Sallallahu Aleyhi ve Sellem şöyle buyurdu: "Altın'a ve gümüş'e kul olan kahrolsun, sürünsün, bedbaht olsun! İşlemeli kumaşlara kul olan kahrolsun, sürünsün, bedbaht olsun! Böyle menfaat düşkünü insanlara bir şey versen hoşuna gider fakat hiçbir şey vermezsen öfkelenir. Kahrolsun böylesi, perişan olsun! Ayaklarına diken batsa bunu çıkaracak yardımcı bulamasın!. Buna karşılık saçı başı dağınık ve ayakları tozlar içinde olsa bile Allah yolunda savaşırken atının yularına yapışarak mücadele eden kul'a ne mutlu; bütün güzellikler onundur. Bu mücahit eğer görev verilirse öncü birliklerle ileri gidip nöbet tutar; yok geri hizmeti yapacaksa bu görevini de en iyi şekilde yerine getirir. Buna rağmen bir yere girmek üzere izin isteyecek olsa kendisine izin verilmez, herhangi bir hususta aracılık etse aracılığı kabul olunmaz." İmam Buhari şöyle demiştir: "Hadisin ravilerinden İsrail ve Muhammed İbn Cuhade bu hadisi Ebu Husayn'dan merfu' olarak rivayet etmemişlerdir. Bu rivayet: "Allah onları kahretsin!" diye de nakledilmiştir. (Ne mutlu! diye tercüme ettiğimiz) طوبى (Tuba) kelimesi فعلى (Fu'la) veznindedir ve her şeyin temiz, hoş olanı anlamına gelir. يطيب fiilinden türemiş olan bu kelimenin aynü'l-fiil denen ortadaki harfi . ...... (ya), ....... (vav)'a dönüşmüştür
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2887</td></tr><tr><td>Arabic No</td><td>2887</td></tr><tr><td>Reference</td><td>Book 56 Hadith 102</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
اور عمرو ابن مرزوق نے ہم سے بڑھا کر بیان کیا، انہوں نے کہا ہم کو عبدالرحمٰن بن عبداللہ بن دینار نے خبر دی، انہوں نے اپنے باپ سے، انہوں نے ابوصالح سے، انہوں نے ابوہریرہ رضی اللہ عنہ سے، انہوں نے نبی کریم صلی اللہ علیہ وسلم سے، آپ صلی اللہ علیہ وسلم نے فرمایا ”اشرفی کا بندہ اور روپے کا بندہ اور کمبل کا بندہ تباہ ہوا، اگر اس کو کچھ دیا جائے تب تو خوش جب نہ دیا جائے تو غصہ ہو جائے، ایسا شخص تباہ سرنگوں ہوا۔ اس کو کانٹا لگے تو اللہ کرے پھر نہ نکلے۔ مبارک کا مستحق ہے وہ بندہ جو اللہ کے راستے میں ( غزوہ کے موقع پر ) اپنے گھوڑے کی لگام تھامے ہوئے ہے، اس کے سر کے بال پراگندہ ہیں اور اس کے قدم گرد و غبار سے اٹے ہوئے ہیں، اگر اسے چوکی پہرے پر لگا دیا جائے تو وہ اپنے اس کام میں پوری تندہی سے لگا رہے اور اگر لشکر کے پیچھے ( دیکھ بھال کے لیے ) لگا دیا جائے تو اس میں بھی پوری تندہی اور فرض شناسی سے لگا رہے۔ ( اگرچہ زندگی میں غربت کی وجہ سے اس کی کوئی اہمیت بھی نہ ہو کہ ) اگر وہ کسی سے ملاقات کی اجازت چاہے تو اسے اجازت بھی نہ ملے اور اگر کسی کی سفارش کرے تو اس کی سفارش بھی قبول نہ کی جائے۔ ابوعبداللہ ( امام بخاری رحمہ اللہ ) نے کہا کہ اسرائیل اور محمد بن جحادہ نے ابوحصین سے یہ روایت مرفوعاً نہیں بیان کی ہے اور کہا کہ قرآن مجید میں جو لفظ «تعسا‏» آیا ہے گویا یوں کہنا چاہئے کہ «فأتعسهم الله‏.‏» ( اللہ انہیں گرائے ہلاک کرے ) «طوبى فعلى» کے وزن پر ہے ہر اچھی اور طیب چیز کے لیے۔ واو اصل میں یا تھا ( طیبیٰ ) پھر یا کو واو سے بدل دیا گیا اور یہ طیب سے نکلا ہے۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2887</td></tr><tr><td>Arabic No</td><td>2887</td></tr><tr><td>Reference</td><td>Book 56 Hadith 102</td></tr></tbody></table></div>