## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا ابْنُ أَبِي الأَسْوَدِ، حَدَّثَنَا مُعْتَمِرٌ، وَحَدَّثَنِي خَلِيفَةُ، حَدَّثَنَا مُعْتَمِرٌ، قَالَ سَمِعْتُ أَبِي، عَنْ أَنَسٍ ـ رضى الله عنه ـ قَالَ كَانَ الرَّجُلُ يَجْعَلُ لِلنَّبِيِّ صلى الله عليه وسلم النَّخَلاَتِ حَتَّى افْتَتَحَ قُرَيْظَةَ وَالنَّضِيرَ، وَإِنَّ أَهْلِي أَمَرُونِي أَنْ آتِيَ النَّبِيَّ صلى الله عليه وسلم فَأَسْأَلَهُ الَّذِينَ كَانُوا أَعْطَوْهُ أَوْ بَعْضَهُ‏.‏ وَكَانَ النَّبِيُّ صلى الله عليه وسلم قَدْ أَعْطَاهُ أُمَّ أَيْمَنَ، فَجَاءَتْ أُمُّ أَيْمَنَ فَجَعَلَتِ الثَّوْبَ فِي عُنُقِي تَقُولُ كَلاَّ وَالَّذِي لاَ إِلَهَ إِلاَّ هُوَ لاَ يُعْطِيكَهُمْ وَقَدْ أَعْطَانِيهَا، أَوْ كَمَا قَالَتْ، وَالنَّبِيُّ صلى الله عليه وسلم يَقُولُ ‏"‏ لَكِ كَذَا ‏"‏‏.‏ وَتَقُولُ كَلاَّ وَاللَّهِ‏.‏ حَتَّى أَعْطَاهَا، حَسِبْتُ أَنَّهُ قَالَ ‏"‏ عَشَرَةَ أَمْثَالِهِ ‏"‏‏.‏ أَوْ كَمَا قَالَ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4120</td></tr><tr><td>Arabic No</td><td>4120</td></tr><tr><td>Reference</td><td>Book 64 Hadith 164</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
আনাস (রাঃ) হতে বর্ণিত। তিনি বলেন, লোকেরা নবী সাল্লাল্লাহু ‘আলাইহি ওয়াসাল্লাম-কে খেজুর গাছ হাদিয়া দিতেন। অতঃপর যখন তিনি বানু নাযীর এবং বানু কুরাইযাহর উপর জয়লাভ করলেন তখন আমার পরিবারের লোকেরা আমাকে নির্দেশ দিল, যেন আমি নবী সাল্লাল্লাহু ‘আলাইহি ওয়াসাল্লাম-এর কাছে গিয়ে তাদের দেয়া সবগুলো খেজুর গাছ অথবা কিছু সংখ্যক খেজুর গাছ তাঁর নিকট থেকে ফেরত গ্রহণের ব্যাপারে নিবেদন করি। আর নবী সাল্লাল্লাহু ‘আলাইহি ওয়াসাল্লাম ঐ গাছগুলো উম্মু আইমান (রাঃ)-কে দান করেছিলেন। উম্মু আইমান (রাঃ) আসলেন এবং আমার গলায় কাপড় লাগিয়ে বললেন, এটা কক্ষনো হতে পারে না। সেই আল্লাহর কসম! যিনি ব্যতীত কোন ইলাহ নেই। তিনি ঐ গাছগুলো তোমাকে আর দেবেন না। তিনি এগুলো আমাকে দিয়ে দিয়েছেন। অথবা (রাবীর সন্দেহ) যেমন তিনি বলেছেন। এদিকে নবী সাল্লাল্লাহু ‘আলাইহি ওয়াসাল্লাম বলছিলেন, তুমি ঐ গাছগুলোর বদলে আমার নিকট থেকে এত এত পাবে। কিন্তু উম্মু আইমান (রাঃ) বলছিলেন, আল্লাহর কসম! এটা কক্ষনো হতে পারে না। অবশেষে নবী সাল্লাল্লাহু ‘আলাইহি ওয়াসাল্লাম তাকে দিলেন। বর্ণনাকারী আনাস (রাঃ) বলেন, আমার মনে হয় নবী সাল্লাল্লাহু ‘আলাইহি ওয়াসাল্লাম বললেন, এর দশগুণ অথবা যেমন তিনি বলেছেন। [২৬৩০; মুসলিম ৩২/২৪, হাঃ ১৭৭১] (আধুনিক প্রকাশনীঃ ৩৮১৪, ইসলামিক ফাউন্ডেশনঃ ৩৮১৭)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4120</td></tr><tr><td>Arabic No</td><td>4120</td></tr><tr><td>Reference</td><td>Book 64 Hadith 164</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated Anas:Some (of the Ansar) used to present date palm trees to the Prophet (ﷺ) till Banu Quraiza and Banu An- Nadir were conquered (then he returned to the people their date palms). My people ordered me to ask the Prophet (ﷺ) to return some or all the date palms they had given to him, but the Prophet (ﷺ) had given those trees to Um Aiman. On that, Um Aiman came and put the garment around my neck and said, "No, by Him except Whom none has the right to be worshipped, he will not return those trees to you as he (i.e. the Prophet (ﷺ) ) has given them to me." The Prophet (ﷺ) go said (to her), "Return those trees and I will give you so much (instead of them)." But she kept on refusing, saying, "No, by Allah," till he gave her ten times the number of her date palms
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4120</td></tr><tr><td>Arabic No</td><td>4120</td></tr><tr><td>Reference</td><td>Book 64 Hadith 164</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Ibnu Abu Al Aswad] telah menceritakan kepada kami [Mu'tamir]. -Dan diriwayatkan dari jalur lain- telah menceritakan kepadaku [Khalifah] telah menceritakan kepada kami [Mu'tamir], ia berkata; aku mendengar [Bapakku] dari [Anas radliallahu 'anhu], ia berkata; 'Seseorang memberikan kebun kurma kepada Nabi shallallahu 'alaihi wasallam, ketika Bani Quraizhah dan Bani Nazhir dapat ditaklukkan. Orang itu berkata; "Sesungguhnya keluargaku menyuruh aku untuk menemui Nabi shallallahu 'alaihi wasallam lalu meminta apa yang telah aku berikan atau sebagiannya." Sementara Nabi shallallahu 'alaihi wasallam telah memberikan kebun kurma itu kepada Ummu Aiman. Lalu Ummu Aiman datang dan meletakkan kain di leherku seraya berkata; "Sekali-kali tidak. Demi Dzat Yang tidak ada sesembahan selain Dia, janganlah tuan berikan kepada mereka karena tuan telah memberikannya kepadaku." Atau sebagaimana yang telah dikatakan. Maka Nabi shallallahu 'alaihi wasallam bersabda: "Kamu mendapatkan bagian segini." Ummu Aiman berkata; "Tidak, demi Allah." Akhirnya beliau memberikan kepadanya. Perawi berkata; "Aku kira dia Anas berkata; "Sepuluh kali lipat atau sekitar itu atau sebagaimana yang telah dikatakan
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4120</td></tr><tr><td>Arabic No</td><td>4120</td></tr><tr><td>Reference</td><td>Book 64 Hadith 164</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
அனஸ் (ரலி) அவர்கள் கூறிய தாவது: நபி (ஸல்) அவர்கள் பனூ குறைழா மற்றும் பனுந் நளீர் குலத்தாரை வெற்றி கொள்ளும்வரை, நபி (ஸல்) அவர்களுக்கு, (அன்சாரிகள்) சிலர் பேரீச்ச மரங்களை(ப் பயன்படுத்திக்கொள்ளும்படி அன்பளிப்பாக)க் கொடுத்திருந்தனர். (பனூ குறைழா, பனுந் நளீர் குலத்தாரை நபி (ஸல்) அவர்கள் வெற்றி கொண்ட பின்னர் அன்சாரிகளிடமே அந்த மரங்களைத் திருப்பிக் கொடுத்துவிட்டார்கள்.194 (அந்தச் சமயத்தில்) என் குடும்பத்தார் என்னை நபி (ஸல்) அவர்களிடம் சென்று நபி (ஸல்) அவர்களுக்குத் தாங்கள் கொடுத்திருந்த மரங்கள் அனைத்தையும், அல்லது அவற்றில் சிலவற்றை (திரும்பத் தரும்படி) கேட்குமாறு எனக்கு உத்தரவிட்டனர். நபி (ஸல்) அவர்கள் அந்த மரங்களை (பராமரிக்கும் பொறுப்பைத் தம் வளர்ப்புத் தாய்) உம்மு அய்மன் (ரலி) அவர்களிடம் கொடுத்திருந்தார்கள். (நான் அந்த மரங்களை நபி (ஸல்) அவர்களிடம் திரும்பத் தரும்படி கேட்டுக் கொண்டிருந்தபோது அங்கு) உம்மு அய்மன் (ரலி) அவர்கள் வந்தார்கள். எனது கழுத்தின் மீது துணியைப் போட்டு, “முடியாது! யாரைத் தவிர வேறு இறைவன் இல்லையோ அவன்மீது சத்தியமாக! நபி (ஸல்) அவர்கள் உங்களுக்கு (அவற்றைத்) தரமாட்டார் கள். (ஏனெனில்,) அவற்றை அவர்கள் எனக்கு (உரிமையாக்கித்) தந்துவிட்டார்கள்” என்றோ அல்லது இது போல வேறொரு வார்த்தையையோ கூறினார்கள். நபி (ஸல்) அவர்கள் (உம்மு அய்மன் (ரலி) அவர்களைப் பார்த்து அவற்றைக் கொடுத்துவிடுங்கள். அதற்குப் பகரமாக) உங்களுக்கு இந்த அளவு தருகிறேன்” என்று கூறினார்கள். (அப்போது) உம்மு அய்மன் (ரலி) அவர்கள் (என்னைப் பார்த்து), “அல்லாஹ்வின் மீதாணையாக! அந்த அளவு நபி (ஸல்) அவர்கள் எனக்குத் தரும்வரை (அவற்றை உங்க ளிடம் திருப்பித் தர) முடியாது” என்று கூறினார்கள். (அறிவிப்பாளர்களில் ஒருவரான சுலைமான் பின் தர்கான் (ரஹ்) அவர்கள் கூறுகிறார்கள்:) அனஸ் (ரலி) அவர்கள், “அது போன்று பத்து மடங்கு (தருவதாக' நபி (ஸல்) அவர்கள் கூறியதாகவோ) அல்லது அதுபோன்ற வேறொரு வார்த்தையைக் கூறியதாகவோ நான் எண்ணுகிறேன். இந்த ஹதீஸ் இரு அறிவிப்பாளர் தொடர்களில் வந்துள்ளது. அத்தியாயம் : 64
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4120</td></tr><tr><td>Arabic No</td><td>4120</td></tr><tr><td>Reference</td><td>Book 64 Hadith 164</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Enes r.a. dedi ki: "(Hurma bahçeleri olanlardan) bir kimse Nebi Sallallahu Aleyhi ve Sellem'e bazı hurma ağaçlarını tahsis ederdi. Nihayet AlIah Kurayza ve Nadir oğulları diyarlarını fethetmeyi nasip etti. Benim aile haIkım da bana Nebi Sallallahu Aleyhi ve Sellem'e gidip daha önce kendisine verdikIerini ya da bir kısmını istememi emrettiler. Nebi Sallallahu Aleyhi ve Sellem da o payı Ümmü Eymen'e vermişti. Ümmü Eymen gelip eIbiseyi boynuma daIayarak dedi ki: Kendisinden başka hiçbir ilah oImayana yemin ediyorum ki asIa onu bana vermişken size (onu geri) vermeyecektir -ya da buna benzer bir söz söyIedi.- Nebi Sallallahu Aleyhi ve Sellem ise: Sana şunu vereceğim, diyor. O, asla AlIah'a yemin ederim oImaz diyordu. Nihayet ona -zannederim- on mislini -ya da bana nasıl söyIediyse öyIe- verdL" Fethu'l-Bari Açıklaması: Bu hadisin ifade ettiği şundan ibarettir: Ensar mahsullerinden yararlanmaIarı için hurma ağaçIarının bazlIarını muhacirlere vererek onIarı gözetmeye çalışmışIardı. Şanı yüce Allah önce Nadir oğulları, sonra da Kurayza oğulları diyarını fethetmeyi nasip edince onIardan alınan ganimetIerin pek çoğu muhacirIer arasında payIaştırıIdı. AlI ah ResuIü de onIara daha önce Ensara ait oIan mallarını geri vermeIerini emrettL Çünkü bunIara ihtiyaçIarı kalmamıştı. Ayrıca Ensar o hurma ağaçIarının kendilerini onIara müIk oIarak vermemişIerdi. Ancak Ümmü Eymen ağaçIara da malik oIduğunu düşünerek kendisine meyvesinden istifade etsin diye verilmiş oIan ağaçIarı geri vermeyi kabuI etmedi. Nebi Sallallahu Aleyhi ve Sellem de üzerindeki dadılık hakkı doIayısı ile ona yumuşak davrandı ve nihayet elinde buIunana karşılık razı edecek kadarını ona verdi. Hadisten malın kendisini değil de sadece menfaatini hibe etmenin meşru olduğu, Nebi sallalltıhu aleyhi ve sellern'in ileri derecede cömert olup, son derece tahammülkar ve iyiliğe karşılık veren birisi olduğu da anlaşılmaktadır. Ayrıca Ümmü Eymen'in Nebi sallaHahu aleyhi ve sellern'in nezdindeki konumu da anlaşılmaktadır. Ümmü Eymen, Üsame b. Zeyd'in annesidir. Oğlu Eymen de aynı şekilde ashabdandır ve Huneyn'de şehit düşmüştür. Üsame'den yaşlı idi. Ümmü Eymen, Nebi sallalltıhu aleyhi ve sellern'den sonra kısa bir süre yaamıştır. Allah hepsinden razı olsun
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4120</td></tr><tr><td>Arabic No</td><td>4120</td></tr><tr><td>Reference</td><td>Book 64 Hadith 164</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ہم سے عبداللہ ابی الاسود نے بیان کیا ‘ کہا ہم سے معتمر بن سلیمان نے بیان کیا (دوسری سند امام بخاری رحمہ اللہ فرماتے ہیں) اور مجھ سے خلیفہ بن خیاط نے بیان کیا ‘ کہا ہم سے معتمر بن سلیمان نے بیان کیا ‘ کہ میں نے اپنے والد سے سنا اور ان سے انس رضی اللہ عنہ نے بیان کیا کہ بطور ہدیہ صحابہ رضی اللہ عنہم اپنے باغ میں سے نبی کریم صلی اللہ علیہ وسلم کے لیے چند کھجور کے درخت مقرر کر دیئے تھے یہاں تک کہ بنو قریظہ اور بنو نضیر کے قبائل فتح ہو گئے ( تو نبی کریم صلی اللہ علیہ وسلم نے ان ہدایا کو واپس کر دیا ) میرے گھر والوں نے بھی مجھے اس کھجور کو، تمام کی تمام یا اس کا کچھ حصہ لینے کے لیے آپ صلی اللہ علیہ وسلم کی خدمت میں بھیجا۔ آپ صلی اللہ علیہ وسلم نے وہ کھجور ام ایمن رضی اللہ عنہا کو دے دی تھی۔ اتنے میں وہ بھی آ گئیں اور کپڑا میری گردن میں ڈال کر کہنے لگیں ‘ قطعاً نہیں۔ اس ذات کی قسم! جس کے سوا کوئی معبود نہیں یہ پھل تمہیں نہیں ملیں گے۔ یہ نبی کریم صلی اللہ علیہ وسلم مجھے عنایت فرما چکے ہیں۔ یا اسی طرح کے الفاظ انہوں نے بیان کئے۔ اس پر نبی کریم صلی اللہ علیہ وسلم نے ان سے فرمایا کہ تم مجھ سے اس کے بدلے میں اتنے لے لو۔ ( اور ان کا مال انہیں واپس کر دو ) لیکن وہ اب بھی یہی کہے جا رہی تھیں کہ قطعاً نہیں، خدا کی قسم! یہاں تک کہ نبی کریم صلی اللہ علیہ وسلم نے انہیں، میرا خیال ہے کہ انس رضی اللہ عنہ نے بیان کیا کہ اس کا دس گنا دینے کا وعدہ فرمایا ( پھر انہوں نے مجھے چھوڑا ) یا اسی طرح کے الفاظ انس رضی اللہ عنہ نے بیان کئے۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4120</td></tr><tr><td>Arabic No</td><td>4120</td></tr><tr><td>Reference</td><td>Book 64 Hadith 164</td></tr></tbody></table></div>