## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا عَلِيُّ بْنُ عَبْدِ اللَّهِ، حَدَّثَنَا سُفْيَانُ، عَنِ الزُّهْرِيِّ، قَالَ سَمِعْتُهُ مِنْ، فِيهِ عَنْ حُمَيْدِ بْنِ عَبْدِ الرَّحْمَنِ، عَنْ أَبِي هُرَيْرَةَ، قَالَ جَاءَ رَجُلٌ إِلَى النَّبِيِّ صلى الله عليه وسلم فَقَالَ هَلَكْتُ‏.‏ قَالَ ‏"‏ مَا شَأْنُكَ ‏"‏‏.‏ قَالَ وَقَعْتُ عَلَى امْرَأَتِي فِي رَمَضَانَ‏.‏ قَالَ ‏"‏ تَسْتَطِيعُ تُعْتِقُ رَقَبَةً ‏"‏‏.‏ قَالَ لاَ‏.‏ قَالَ ‏"‏ فَهَلْ تَسْتَطِيعُ أَنْ تَصُومَ شَهْرَيْنِ مُتَتَابِعَيْنِ ‏"‏‏.‏ قَالَ لاَ‏.‏ قَالَ ‏"‏ فَهَلْ تَسْتَطِيعُ أَنْ تُطْعِمَ سِتِّينَ مِسْكِينًا ‏"‏‏.‏ قَالَ لاَ‏.‏ قَالَ ‏"‏ اجْلِسْ ‏"‏‏.‏ فَجَلَسَ فَأُتِيَ النَّبِيُّ صلى الله عليه وسلم بِعَرَقٍ فِيهِ تَمْرٌ ـ وَالْعَرَقُ الْمِكْتَلُ الضَّخْمُ ـ قَالَ ‏"‏ خُذْ هَذَا، فَتَصَدَّقْ بِهِ ‏"‏‏.‏ قَالَ أَعَلَى أَفْقَرَ مِنَّا، فَضَحِكَ النَّبِيُّ صلى الله عليه وسلم حَتَّى بَدَتْ نَوَاجِذُهُ قَالَ ‏"‏ أَطْعِمْهُ عِيَالَكَ ‏"‏‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6709</td></tr><tr><td>Arabic No</td><td>6709</td></tr><tr><td>Reference</td><td>Book 84 Hadith 2</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
وقَوْلِهِ تَعَالَى (قَدْ فَرَضَ اللهُ لَكُمْ تَحِلَّةَ أَيْمَانِكُمْ وَاللهُ مَوْلاَكُمْ وَهُوَ الْعَلِيْمُ الْحَكِيْمُ) আল্লাহর বাণীঃ আল্লাহ তোমাদের জন্য নিজেদের কসমের বাধ্যবাধকতা থেকে নিস্কৃতি পাওয়ার ব্যবস্থা করেছেন, আল্লাহ তোমাদের মালিক-মনিব-রক্ষক, আর তিনি সর্বজ্ঞাতা, মহা প্রজ্ঞার অধিকারী- (সূরাহ আল-বাক্বারাহ ৬৬/১-২)। ৬৭০৯. আবূ হুরাইরাহ (রাঃ) হতে বর্ণিত। তিনি বলেন, নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর কাছে এক লোক এসে বলল, আমি ধ্বংস হয়ে গেছি। তিনি বললেনঃ তোমার কী হয়েছে? লোকটি বলল, রমযানে (দিনের বেলা) আমি আমার স্ত্রীর সঙ্গে যৌন সঙ্গম করেছি। তিনি বললেনঃ তুমি কি একটি গোলাম আযাদ করতে পার? লোকটি বলল, না। তিনি বললেনঃ তাহলে তুমি কি এক নাগাড়ে দু’ মাস সওম পালন করতে পার? সে বলল, না। তিনি বললেনঃ তা হলে কি তুমি ষাটজন মিস্কীনকে খানা খাওয়াতে পারবে? সে বলল, না। তিনি বললেনঃ বস। লোকটি বসল। তারপর নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর কাছে এক ‘আরক’ আনা হলো যাতে ছিল খেজুর। আর ‘আরক’ হল মাপ করার জন্য বড় ধরণের পাত্র। তিনি বললেনঃ এটা নিয়ে যাও এবং তা সদাকাহ করে দাও। লোকটি বলল, আমার চেয়েও অভাবীকে (তা দান করব)? তখন নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম হেসে ফেললেনঃ এমন কি তাঁর মাড়ির দাঁত পর্যন্ত দেখা গেল। তিনি বললেনঃ এটা তোমার পরিজনকেই খাওয়াও।[1] [১৯৩৬] (আধুনিক প্রকাশনী- ৬২৪২, ইসলামিক ফাউন্ডেশন- ৬২৫২)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6709</td></tr><tr><td>Arabic No</td><td>6709</td></tr><tr><td>Reference</td><td>Book 84 Hadith 2</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated Abu Huraira:A man came to the Prophet (ﷺ) and said, "I am ruined!" The Prophet (ﷺ) said, "What is the matter with you?" He said, "I had sexual relation with my wife (while I was fasting) in Ramadan." The Prophet (ﷺ) said, "Have you got enough to manumit a slave?" He said, "No." The Prophet (ﷺ) said, "Can you fast for two successive months?" The man said, "No." The Prophet (ﷺ) said, "Can you feed sixty poor persons?" The man said, "No." Then the Prophet (ﷺ) said to him, "Sit down," and he sat down. Afterwards an 'Irq, i.e., a big basket containing dates was brought to the Prophet (ﷺ) and the Prophet (ﷺ) said to him, "Take this and give it in charity." The man said, "To poorer people than we?" On that, the Prophet (ﷺ) smiled till his premolar teeth became visible, and then told him, "Feed your family with it." (See Hadith No. 157, Vol 3)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6709</td></tr><tr><td>Arabic No</td><td>6709</td></tr><tr><td>Reference</td><td>Book 84 Hadith 2</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Ali bin Abdullah] telah menceritakan kepada kami [Sufyan] dari [Az Zuhri], Sufyan berkata; aku mendengarnya dari mulutnya, dari [Humaid bin Abdurrahman] dari [Abu Hurairah] mengatakan, Seorang lelaki menemui Nabi shallallahu 'alaihi wasallam dan berujar; 'celaka aku! ' "kenapa denganmu?" Tanya Nabi, dia Jawab; 'Aku menyetubuhi istriku di bulan Ramadhan.' Nabi bertanya; "mampukah kamu membebaskan seorang budak?" 'Tidak, ' Jawabnya. Tanya Nabi: "Apakah kamu bisa berpuasa dua bulan secara berturut-turut?" 'Tidak' jawabnya. Tanya Nabi: "Apakah kamu bisa memberi makan enam puluh orang miskin?" 'Tidak, ' Jawabnya. Nabi bersabda: "Kalau begitu duduklah." Orang itu pun duduk, dan Nabi membawakan segantang penuh kurma dan berujar: "Ambillah kurma ini dan pergunakanlah untuk bersedekah!" Orang tadi menjawab; 'Apakah kepada orang yang lebih miskin dari kami? ' Nabi shallallahu 'alaihi wasallam pun tertawa hingga terlihat gigi serinya dan bersabda: "berilah makan keluargamu dengannya
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6709</td></tr><tr><td>Arabic No</td><td>6709</td></tr><tr><td>Reference</td><td>Book 84 Hadith 2</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
அபூஹுரைரா (ரலி) அவர்கள் கூறியதாவது: நபி (ஸல்) அவர்களிடம் ஒரு மனிதர் வந்து, “அல்லாஹ்வின் தூதரே! நான் அழிந்துவிட்டேன்” என்றார். நபி (ஸல்) அவர்கள். “உமக்கு என்ன நேர்ந்தது?” என்று கேட்டார்கள். “நான் ரமளானில் (நோன்பு வைத்துக்கொண்டே) என் மனைவியுடன் தாம்பத்திய உறவு கொண்டுவிட்டேன்” என்று அவர் சொன்னார். நபி (ஸல்) அவர்கள் “ஓர் அடிமையை விடுதலை செய்ய உம்மால் முடியுமா?” என்று கேட்டார்கள். அவர் “இல்லை” என்றார். “தொடர்ந்து இரு மாதங்கள் நோன்பு நோற்க உம்மால் முடியுமா?” என்று நபி (ஸல்) அவர்கள் கேட்டார்கள். அவர் “இல்லை” என்றார். “அறுபது ஏழைகளுக்கு உணவளிக்க உம்மால் முடியுமா?” என்று நபி (ஸல்) அவர்கள் கேட்க, அதற்கும் அவர் “இல்லை” என்றார். நபி (ஸல்) அவர்கள் “அமர்வீராக!” என்றார்கள். அவரும் அமர்ந்தார். பின்னர் நபி (ஸல்) அவர்களிடம் பேரீச்சம்பழம் நிறைந்த ‘அரக்’ ஒன்று கொண்டுவரப்பட்டது. -’அரக்’ என்பது பெரிய கூடை ஆகும்.- அப்போது நபி (ஸல்) அவர்கள் “இதைப் பெற்று தர்மம் செய்வீராக!” என்று கூறினார்கள். அம்மனிதர், “(அல்லாஹ்வின் தூதரே!) என்னைவிட ஏழையாக இருப்போருக்கா (நான் தர்மம் செய்ய வேண்டும்)?” என்று கேட்டார். அப்போது நபி (ஸல்) அவர்கள் தம் கடைவாய்ப் பற்கள் தெரியும் அளவுக்குச் சிரித்தார்கள். பிறகு “இதை உம்முடைய குடும்பத்தாருக்கே உண்ணக் கொடுத்துவிடுவீராக!” என்றார்கள்.5 அத்தியாயம் : 86
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6709</td></tr><tr><td>Arabic No</td><td>6709</td></tr><tr><td>Reference</td><td>Book 84 Hadith 2</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ebu Hureyre r.a. şöyle anlatır: Adam'ın biri Nebi Sallallahu Aleyhi ve Sellem'e gelerek "mahvoldum" dedi. Resulullah Sallallahu Aleyhi ve Sellem "Derdin nedir?" diye sordu. Adam "Ramazan günü oruçlu iken eşimle ilişkide bulundum" dedi. Resulullah Sallallahu Aleyhi ve Sellem "Bir köleyi özgürlüğüne kavuşturabilir misin?" deyince adam "hayır" diye cevap verdi. Nebi Sallallahu Aleyhi ve Sellem "İki ay peşpeşe oruç tutabilir misin?" diye sordu. Adam "hayır" dedi. Resulullah Sallallahu Aleyhi ve Sellem ''Altmış fakiri doyurmaya gücün yeter mi?" deyince, adam "hayır" dedi. ResuluIlah Sallallahu Aleyhi ve Sellem "Otur" dedi ve adam oturdu. O arada Resulullah Sallallahu Aleyhi ve Sellem'e bir arak hurma getirildi. Arak büyükçe bir kabın adıdır. Nebi Sallallahu Aleyhi ve Sellem O kişiye : "Bunu al ve tasadduk et" buyurdu. Adam "Bizden daha fakirine mi?" deyince, Nebi Sallallahu Aleyhi ve Sellem azı dişleri görülecek kadar güldü ve "Bunu al da çoluk çocuğuna yedir" buyurdu. Fethu'l-Bari Açıklaması: İmam Buhari', bu konuda, ramazan günü oruçlu iken eşiyleilişkide bulunan kimsenin durumuna değinen hadise yer verdi. Bu hadisin açıklaması oruç bölümünde uzun uzadıya geçmişti. O bölümde kefaret verecek bir şey bulamayan ve oruç da tutamayan kimseden bu yükümlülüğün düşeceği veya zimmetinde borç olarak kalacağı konusundaki farklı görüşlere de yer vermiştik. İbnü'l-Müneyyir şöyle der: İmam Buhari'nin maksadı, eşiyle ilişkide bulunan kocaya kefaretin o günahı işlemesi nedeniyle farz olması gibi, yemini bozmakla farz olduğu noktasına dikkat çekmektir. İmam Buhari, fakirin zimmetinden kefaret yükümlülüğünün düşmediğine işaret etmektedir. Çünkü Resulullah Sallallahu Aleyhi ve Sellem kendisine gelen kişinin fakir olduğunu biliyordu. Bununla birlikte ona -tıpkı bir fakire borcunu ödemesi için para vermesi örneğinde olduğu gibi- kefaretini ödemesi için o hurmayı verdi
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6709</td></tr><tr><td>Arabic No</td><td>6709</td></tr><tr><td>Reference</td><td>Book 84 Hadith 2</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ہم سے علی بن عبداللہ مدینی نے بیان کیا، کہا ہم سے سفیان بن عیینہ نے بیان کیا، ان سے زہری نے بیان کیا، کہا کہ میں نے ان کی زبان سے سنا وہ حمید بن عبدالرحمٰن سے بیان کرتے تھے، ان سے ابوہریرہ رضی اللہ عنہ نے بیان کیا کہ ایک شخص نبی کریم صلی اللہ علیہ وسلم کی خدمت میں حاضر ہوا اور عرض کیا، میں تو تباہ ہو گیا۔ نبی کریم صلی اللہ علیہ وسلم نے دریافت فرمایا کہ کیا بات ہے؟ عرض کیا کہ میں نے رمضان میں اپنی بیوی سے ہمبستری کر لی۔ نبی کریم صلی اللہ علیہ وسلم نے دریافت فرمایا کہ کیا تم ایک غلام آزاد کر سکتے ہو؟ انہوں نے کہا کہ نہیں۔ نبی کریم صلی اللہ علیہ وسلم نے پوچھا کیا دو مہینے متواتر روزے رکھ سکتا ہے۔ انہوں نے عرض کیا کہ نہیں۔ نبی کریم صلی اللہ علیہ وسلم نے پوچھا کیا ساٹھ مسکینوں کو کھانا کھلا سکتا ہے؟ انہوں نے کہا کہ نہیں۔ اس پر نبی کریم صلی اللہ علیہ وسلم نے فرمایا کہ بیٹھ جاؤ وہ صاحب بیٹھ گئے۔ پھر نبی کریم صلی اللہ علیہ وسلم کے پاس ایک ٹوکرا لایا گیا جس میں کھجوریں تھیں ( «عرق» ایک بڑا پیمانہ ہے ) نبی کریم صلی اللہ علیہ وسلم نے فرمایا کہ لے جا اور اسے پورا صدقہ کر دے۔ انہوں نے پوچھا، کیا اپنے سے زیادہ محتاج پر ( صدقہ کر دوں ) ؟ اس پر نبی کریم صلی اللہ علیہ وسلم ہنس دئیے اور آپ کے سامنے کے دانت مبارک دکھائی دینے لگے اور پھر آپ صلی اللہ علیہ وسلم نے فرمایا کہ اپنے بچوں ہی کو کھلا دینا۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6709</td></tr><tr><td>Arabic No</td><td>6709</td></tr><tr><td>Reference</td><td>Book 84 Hadith 2</td></tr></tbody></table></div>