## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا أَبُو الْيَمَانِ، أَخْبَرَنَا شُعَيْبٌ، عَنِ الزُّهْرِيِّ،‏.‏ وَحَدَّثَنَا إِسْمَاعِيلُ، قَالَ حَدَّثَنِي أَخِي، عَنْ سُلَيْمَانَ، عَنْ مُحَمَّدِ بْنِ أَبِي عَتِيقٍ، عَنِ ابْنِ شِهَابٍ، عَنْ عَلِيِّ بْنِ الْحُسَيْنِ، أَنَّ صَفِيَّةَ بِنْتَ حُيَىٍّ، زَوْجَ النَّبِيِّ صلى الله عليه وسلم أَخْبَرَتْهُ أَنَّهَا جَاءَتْ رَسُولَ اللَّهِ صلى الله عليه وسلم تَزُورُهُ وَهْوَ مُعْتَكِفٌ فِي الْمَسْجِدِ فِي الْعَشْرِ الْغَوَابِرِ مِنْ رَمَضَانَ، فَتَحَدَّثَتْ عِنْدَهُ سَاعَةً مِنَ الْعِشَاءِ ثُمَّ قَامَتْ تَنْقَلِبُ، فَقَامَ مَعَهَا النَّبِيُّ صلى الله عليه وسلم يَقْلِبُهَا حَتَّى إِذَا بَلَغَتْ باب الْمَسْجِدِ الَّذِي عِنْدَ مَسْكَنِ أُمِّ سَلَمَةَ زَوْجِ النَّبِيِّ صلى الله عليه وسلم مَرَّ بِهِمَا رَجُلاَنِ مِنَ الأَنْصَارِ فَسَلَّمَا عَلَى رَسُولِ اللَّهِ صلى الله عليه وسلم ثُمَّ نَفَذَا، فَقَالَ لَهُمَا رَسُولُ اللَّهِ صلى الله عليه وسلم ‏"‏ عَلَى رِسْلِكُمَا، إِنَّمَا هِيَ صَفِيَّةُ بِنْتُ حُيَىٍّ ‏"‏‏.‏ قَالاَ سُبْحَانَ اللَّهِ يَا رَسُولَ اللَّهِ‏.‏ وَكَبُرَ عَلَيْهِمَا‏.‏ قَالَ ‏"‏ إِنَّ الشَّيْطَانَ يَجْرِي مِنِ ابْنِ آدَمَ مَبْلَغَ الدَّمِ، وَإِنِّي خَشِيتُ أَنْ يَقْذِفَ فِي قُلُوبِكُمَا ‏"‏‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6219</td></tr><tr><td>Arabic No</td><td>6219</td></tr><tr><td>Reference</td><td>Book 78 Hadith 243</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
‘আলী ইবনু হুসায়ন (রহঃ) হতে বর্ণিত যে, নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর স্ত্রী সফীয়্যাহ বিন্ত হুইয়াই (রাঃ) বর্ণনা করেন যে, রমাযানের শেষ দশ দিনে মসজিদে রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর ই’তিকাফের অবস্থায় তিনি তাঁর সঙ্গে সাক্ষাৎ করতে গেলেন। তিনি রাতের প্রথম ভাগে কিছু সময় তাঁর সঙ্গে কথাবার্তার পর ফিরে যাবার জন্য উঠে দাঁড়ালেন। নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম তাঁকে এগিয়ে দেয়ার জন্য উঠে দাঁড়ালেন। শেষে যখন তিনি মসজিদের দরজার নিকট পৌঁছলেন, যা নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর বিবি উম্মু সালামাহর ঘরের নিকটে অবস্থিত, তখন তাঁদের পাশ দিয়ে আনসারের দু’জন লোক যাচ্ছিল। তাঁরা দু’জনেই রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-কে সালাম দিল এবং নিজ পথে রওয়ানা হল। তখন রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম তাদের বললেনঃ ধীরে চল। ইনি হলেন সফীয়্যাহ বিন্ত হুইয়াই। তারা বললোঃ সুবহানাল্লাহ! হে আল্লাহর রাসূল। তাদের দু’জনের মনে তা গুরুত্বপূর্ণ মনে হল। তিনি বললেনঃ নিশ্চয়ই শয়ত্বন মানুষের রক্তের ভিতর চলাচল করে থাকে। তাই আমার আশঙ্কা হলো যে, সম্ভবতঃ সে তোমাদের অন্তরে সন্দেহ জাগিয়ে দিতে পারে। [২০৩৫] (আধুনিক প্রকাশনী- ৫৭৭৭,৫৭৭৮, ইসলামিক ফাউন্ডেশন- ৫৬৭৩)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6219</td></tr><tr><td>Arabic No</td><td>6219</td></tr><tr><td>Reference</td><td>Book 78 Hadith 243</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated Safiya bint Huyai:The wife of the Prophet (ﷺ) that she went to Allah's Messenger (ﷺ) while he was in I'tikaf (staying in the mosque) during the last ten nights of the month of Ramadan. She spoke to him for an hour (a while) at night and then she got up to return home. The Prophet (ﷺ) got up to accompany her, and when they reached the gate of the mosque opposite the dwelling place of Um Salama, the wife of the Prophet, two Ansari men passed by, and greeting Allah's Messenger (ﷺ) , they quickly went ahead. Allah's Messenger (ﷺ) said to them, "Do not be in a hurry She is Safiya, the daughter of Huyai." They said, "Subhan Allah! O Allah's Messenger (ﷺ) (how dare we suspect you)." That was a great thing for both of them. The Prophet (ﷺ) then said, "Satan runs in the body of Adam's son (i.e. man) as his blood circulates in it, and I was afraid that he (Satan) might insert an evil thought in your hearts
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6219</td></tr><tr><td>Arabic No</td><td>6219</td></tr><tr><td>Reference</td><td>Book 78 Hadith 243</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Abu Al Yaman] telah mengabarkan kepada kami [Syu'aib] dari [Az Zuhri] dan diriwayatkan dari jalur lain, telah menceritakan kepada kami [Isma'il] dia berkata; telah menceritakan kepadaku [Saudaraku] dari [Sulaiman] dari [Muhammad bin Abu 'Atiq] dari [Ibnu Syihab] dari [Ali bin Al Hasan] bahwa [Shafiyah binti Huyay isteri Nabi] shallallahu 'alaihi wasallam telah mengabarkan kepadanya, bahwa dia pernah datang mengunjungi Rasulullah shallallahu 'alaihi wasallam saat beliau tengah beri'tikaf di Masjid pada sepuluh hari terakhir bulan Ramadlan. Lalu dia berbincang-bincang dengan Nabi hingga menjelang Isya', setelah itu dia beranjak untuk kembali pulang, maka Nabi shallallahu 'alaihi wasallam ikut pergi bersamanya hingga ketika sampai agak jauh dari pintu masjid dan dekat rumah Ummu Salamah, istri Nabi shallallahu 'alaihi wasallam, dua orang laki-laki kaum Anshar lewat dan keduanya memberi salam kepada Rasulullah shallallahu 'alaihi wasallam, kemudian bergegas pergi. Maka Rasulullah shallallahu 'alaihi wasallam bersabda kepada keduanya: "Kenapa terburu-buru? sesungguhnya dia adalah Shafiyah binti Huyay." Kedua orang itu berkata; "Maha suci Allah, wahai Rasulullah." Maka dengan ucapan dua orang tersebut, beliau jadi tercengang. (sabdanya): "Sesungguhnya syetan masuk kepada manusia lewat aliran darah dan aku khawatir bila syetan telah membisikkan sesuatu dalam hati kalian berdua
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6219</td></tr><tr><td>Arabic No</td><td>6219</td></tr><tr><td>Reference</td><td>Book 78 Hadith 243</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
நபி (ஸல்) அவர்களின் துணைவியார் ஸஃபிய்யா பின்த் ஹுயை (ரலி) அவர்கள் கூறியதாவது: அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் ரமளான் மாதத்தின் இறுதிப் பத்து நாட்களில் (மஸ்ஜிதுந் நபவீ) பள்ளிவாசலில் ‘இஃதிகாஃப்’ இருந்துகொண்டிருந்தபோது அவர்களைச் சந்திப்பதற்காக நான் (பள்ளிவாசலுக்குச்) சென்றேன். (அந்த) இரவில் சிறிது நேரம் பேசிவிட்டு நான் திரும்பிச் செல்ல எழுந்தபோது, என்னை அனுப்பிவைப்பதற்காக என்னுடன் நபி (ஸல்) அவர்களும் எழுந்தார்கள். நான் நபி (ஸல்) அவர்களின் (மற்றொரு) துணைவியாரான உம்மு சலமா (ரலி) அவர்களின் இல்லத்தை ஒட்டியிருந்த பள்ளிவாசலின் வாயில் அருகில் வந்தபோது அன்சாரிகளில் இருவர் எங்களைக் கடந்து சென்றனர். அவர்கள் இருவரும் அல்லாஹ்வின் தூதர் (ஸல்) அவர்களுக்கு முகமன் கூறிவிட்டுப் போய்க் கொண்டேயிருந்தனர். உடனே அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் இருவரையும் பார்த்து, “சற்று பொறுங்கள்! (என்னுடன் இருக்கும்) இந்தப் பெண் ஸஃபிய்யா பின்த் ஹுயைதான்” என்றார்கள். அந்த இருவரும் (வியப்புடன்) ‘சுப்ஹானல்லாஹ்’ (அல்லாஹ் தூயவன்), அல்லாஹ்வின் தூதரே!” என்றனர். நபி (ஸல்) அவர்கள் சொன்ன வார்த்தை அவர்கள் இருவருக்கும் பளுவாக இருந்தது. நபி (ஸல்) அவர்கள் “ஷைத்தான் ஆதமின் மகனின் (மனிதனின்) இரத்த நாளங்களில்(கூட) ஓடுகின்றான். உங்கள் உள்ளங்களில் (சந்தேகம் அல்லது தீய எண்ணம் எதையாவது) அவன் போட்டுவிடுவானோ என நான் அஞ்சினேன்” என்று சொன்னார்கள்.254 அத்தியாயம் : 78
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6219</td></tr><tr><td>Arabic No</td><td>6219</td></tr><tr><td>Reference</td><td>Book 78 Hadith 243</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ali İbn el-Huseyn'den rivayete göre "Nebi Sallallahu Aleyhi ve Sellem'in zevcesi Huyey kızı Safiyye'nin kendisine haber verdiğine göre, Nebi Sallallahu Aleyhi ve Sellem, Ramazanın son on gününde mescidde itikafta bulunuyorken Resulullah'ı ziyaret etmek üzere gitmişti. Yatsıdan sonra bir süre yanında kalıp konuşmuş, sonra da dönmek üzere kalkmıştı. Nebi Sallallahu Aleyhi ve Sellem de onu eve geçirmek için onunla birlikte kalkmıştı. Nihayet Nebi Sallallahu Aleyhi ve Sellem'in zevcesi Ümmü Selemelnin meskeni yanında bulunan mescidin kapısına ulaştığında yanlarından ensardan iki adam geçti. Resulullah Sallallahu Aleyhi ve Sellem'e selam verdikten sonra yürüyüp gitmişlerdi. Resulullah Sallallahu Aleyhi ve Sellem her ikisine de: Yavaş olun, acele etmeyin. Bu Huyey kızı Safiyye'dir, buyurdu. Ensardan olan o iki sahabiye onun bu sözleri ağır geldiğinden: Subhanallah! Ey Allah'ın Rasulü, dediler. Allah Rasulü de: Şüphesiz şeytan, Ademoğlunun içinden kanın ulaştığı yere kadar akar gider. Ben de kalplerinize bir şüphe bırakmasından korktum, buyurdu." Fethu'l-Bari Açıklaması: "Hayret ve şaşkınlık dolayısıyla tekbir ve tesbih getirmek." İbn Battal dedi ki: Tesbih ve tekbir, Allah'ın tazim edilmesi, kötülükten tenzih edilmesi demektir. Hayrete düşüldüğü ve bir işin büyüklüğünün görülmesi halinde kullanılması güzeldir. Böylelikle dil, Allah'ı zikretmeye de alışmış olur. Bu güzel bir açıklamadır. Sanki Buhari bu başlık ile bunu kabul etmeyen kimselerin kanaatlerinin reddedileceğine işaret etmiş gibidir. "Son on gün" ile burada kasıt, Ramazan'dan geriye kalan on gündür. Buradaki (son anlamında kullanılan el-ğaviibir lafzı) aynı zamanda geçen günler hakkında da kullanılır. O halde bu lafız zıt anlamlı lafızlardandır. "Hazineler" lafzıyla rahmeti dile getirmiştir. Nitekim: "Rabbimin rahmetinin hazineleri" sözü de buna benzemektedir. Nitekim "fitneler"den de azap diye söz etmiştir. Çünkü fitneler, azaba götüren sebeplerdir. Yahut "hazineler"den kasıt, ümmetinin fethedeceği ülkelerden ganimet yoluyla elde edecekleri mallardır. Şüphesiz ki fitneler de bundan ortaya çıkar. Bu da Nebi Sallallahu Aleyhi ve Sellem'in meydana gelmeden önce haber verdiği hususlar arasındadır. Beyhaki de bu hususu "Oeliiilu'n-Nubuvve" adlı eserinde ele almıştır
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6219</td></tr><tr><td>Arabic No</td><td>6219</td></tr><tr><td>Reference</td><td>Book 78 Hadith 243</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ہم سے ابوالیمان نے بیان کیا، انہوں نے کہا ہم کو شعیب نے خبر دی، انہیں زہری نے (دوسری سند) اور ہم سے اسماعیل بن ابی اویس نے بیان کیا، انہوں نے کہا کہ مجھ سے میرے بھائی عبدالحمید نے بیان کیا، ان سے سلیمان نے بیان کیا، ان سے محمد بن ابی عتیق نے بیان کیا، ان سے ابن شہاب نے بیان کیا، ان سے امام زین العابدین علی بن حسین نے کہ نبی کریم صلی اللہ علیہ وسلم کی زوجہ مطہرہ صفیہ بنت حی رضی اللہ عنہا نے انہیں خبر دی کہ وہ نبی کریم صلی اللہ علیہ وسلم کے پاس ملنے آئیں۔ نبی کریم صلی اللہ علیہ وسلم اس وقت مسجد میں رمضان کے آخری عشرہ میں اعتکاف کئے ہوئے تھے۔ عشاء کے وقت تھوڑی دیر انہوں نے نبی کریم صلی اللہ علیہ وسلم سے باتیں کیں اور واپس لوٹنے کے لیے اٹھیں تو نبی کریم صلی اللہ علیہ وسلم بھی انہیں چھوڑ آنے کے لیے کھڑے ہو گئے۔ جب وہ مسجد کے اس دروازہ کے پاس پہنچیں جہاں نبی کریم صلی اللہ علیہ وسلم کی زوجہ مطہرہ ام سلمہ رضی اللہ عنہا کا حجرہ تھا، تو ادھر سے دو انصاری صحابی گزرے اور نبی کریم صلی اللہ علیہ وسلم کو سلام کیا اور آگے بڑھ گئے۔ لیکن نبی کریم صلی اللہ علیہ وسلم نے ان سے فرمایا کہ تھوڑی دیر کے لیے ٹھہر جاؤ۔ یہ صفیہ بنت حی میری بیوی ہیں۔ ان دونوں صحابہ نے عرض کیا: سبحان اللہ، یا رسول اللہ۔ ان پر بڑا شاق گزرا۔ لیکن آپ صلی اللہ علیہ وسلم نے فرمایا کہ شیطان انسان کے اندر خون کی طرح دوڑتا رہتا ہے، اس لیے مجھے خوف ہوا کہ کہیں وہ تمہارے دل میں کوئی شبہ نہ ڈال دے۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6219</td></tr><tr><td>Arabic No</td><td>6219</td></tr><tr><td>Reference</td><td>Book 78 Hadith 243</td></tr></tbody></table></div>