## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا إِبْرَاهِيمُ بْنُ مُوسَى، أَخْبَرَنَا عِيسَى، عَنْ هِشَامٍ، عَنْ أَبِيهِ، عَنْ عَائِشَةَ ـ رضى الله عنها ـ قَالَتْ سُحِرَ النَّبِيُّ صلى الله عليه وسلم‏.‏ وَقَالَ اللَّيْثُ كَتَبَ إِلَىَّ هِشَامٌ أَنَّهُ سَمِعَهُ وَوَعَاهُ عَنْ أَبِيهِ عَنْ عَائِشَةَ قَالَتْ سُحِرَ النَّبِيُّ صلى الله عليه وسلم حَتَّى كَانَ يُخَيَّلُ إِلَيْهِ أَنَّهُ يَفْعَلُ الشَّىْءَ وَمَا يَفْعَلُهُ، حَتَّى كَانَ ذَاتَ يَوْمٍ دَعَا وَدَعَا، ثُمَّ قَالَ ‏"‏ أَشَعَرْتِ أَنَّ اللَّهَ أَفْتَانِي فِيمَا فِيهِ شِفَائِي أَتَانِي رَجُلاَنِ، فَقَعَدَ أَحَدُهُمَا عِنْدَ رَأْسِي وَالآخَرُ عِنْدَ رِجْلَىَّ، فَقَالَ أَحَدُهُمَا لِلآخَرِ مَا وَجَعُ الرَّجُلِ قَالَ مَطْبُوبٌ‏.‏ قَالَ وَمَنْ طَبَّهُ قَالَ لَبِيدُ بْنُ الأَعْصَمِ‏.‏ قَالَ فِي مَاذَا قَالَ فِي مُشُطٍ وَمُشَاقَةٍ وَجُفِّ طَلْعَةٍ ذَكَرٍ‏.‏ قَالَ فَأَيْنَ هُوَ قَالَ فِي بِئْرِ ذَرْوَانَ ‏"‏‏.‏ فَخَرَجَ إِلَيْهَا النَّبِيُّ صلى الله عليه وسلم ثُمَّ رَجَعَ فَقَالَ لِعَائِشَةَ حِينَ رَجَعَ ‏"‏ نَخْلُهَا كَأَنَّهَا رُءُوسُ الشَّيَاطِينِ ‏"‏‏.‏ فَقُلْتُ اسْتَخْرَجْتَهُ فَقَالَ ‏"‏ لاَ أَمَّا أَنَا فَقَدْ شَفَانِي اللَّهُ، وَخَشِيتُ أَنْ يُثِيرَ ذَلِكَ عَلَى النَّاسِ شَرًّا، ثُمَّ دُفِنَتِ الْبِئْرُ ‏"‏‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3268</td></tr><tr><td>Arabic No</td><td>3268</td></tr><tr><td>Reference</td><td>Book 59 Hadith 78</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
وَقَالَ مُجَاهِدٌ يُقْذَفُوْنَ يُرْمَوْنَ دُحُوْرًا مَطْرُوْدِيْنَ وَاصِبٌ دَائِمٌ وَقَالَ ابْنُ عَبَّاسٍ مَدْحُوْرًا مَطْرُوْدًا يُقَالُ مَرِيْدًا مُتَمَرِّدًا بَتَّكَهُ قَطَّعَهُ وَاسْتَفْزِزْ اسْتَخِفَّ بِخَيْلِكَ الْفُرْسَانُ وَالرَّجْلُ الرَّجَّالَةُ وَاحِدُهَا رَاجِلٌ مِثْلُ صَاحِبٍ وَصَحْبٍ وَتَاجِرٍ وَتَجْرٍ لَاحْتَنِكَنَّ لَاسْتَأْصِلَنَّ قَرِيْنٌ شَيْطَانٌ মুজাহিদ (রহ.) বলেন, يُقْذَفُوْنَ তাদের নিক্ষেপ করা হবে। دُحُوْرًا তাদের হাঁকিয়ে বের করে দেয়া হবে। وَاصِبٌ স্থায়ী। আর ইবনু ‘আব্বাস (রাঃ) বলেন, مَدْحُوْرًا হাঁকিয়ে বের করা অবস্থায়। مَرِيْدًا বিদ্রোহীরূপে। بَتَّكَهُ তাকে ছিন্ন করেছে। وَاسْتَفْزِزْ তুমি ভয় দেখাও। بِخَيْلِكَ অশ্বারোহী। وَالرَّجْلُ পদাতিকগণ। এর একবচন رَاجِلٌ যেমন صَاحِب এর বহুবচন صَحْب আর تَاجِر এর বহুবচনاتَجْرٍ لَاحْتَنِكَنَّ অবশ্যই আমি সমূলে উৎপাটন করব। قَرِيْنٌ শয়তান। ৩২৬৮. ‘আয়িশাহ (রাঃ) হতে বর্ণিত। তিনি বলেন, নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-কে যাদু করা হয়েছিল। লায়স (রহ.) বলেন, আমার নিকট হিশাম পত্র লিখেন, তাতে লেখা ছিল যে, তিনি তাঁর পিতার সূত্রে ‘আয়িশাহ (রাঃ) হতে হাদীস শুনেছেন এবং তা ভালভাবে মুখস্থ করেছেন। ‘আয়িশাহ (রাঃ) বলেন, নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম কে যাদু করা হয়। এমনকি যাদুর প্রভাবে তাঁর খেয়াল হতো যে, তিনি স্ত্রীগণের বিষয়ে কোন কাজ করে ফেলেছেন অথচ তিনি তা করেননি। শেষ পর্যন্ত একদা তিনি রোগ আরোগ্যের জন্য বারবার দু‘আ করলেন, অতঃপর তিনি আমাকে বললেন, তুমি কি জান আল্লাহ আমাকে জানিয়ে দিয়েছেন, যাতে আমার রোগের আরোগ্য আছে? আমার নিকট দু’জন লোক আসল। তাদের একজন মাথার নিকট বসল আর অপরজন আমার পায়ের নিকট বসল। অতঃপর একজন অন্যজনকে জিজ্ঞেস করল, এ ব্যক্তির রোগটা কী? জিজ্ঞাসিত লোকটি জবাব দিল, তাকে যাদু করা হয়েছে। প্রথম লোকটি বলল, তাকে যাদু কে করল? সে বলল, লবীদ ইবনু আ‘সাম। প্রথম ব্যক্তি বলল, কিসের দ্বারা? দ্বিতীয় ব্যক্তি বলল, তাকে যাদু করা হয়েছে, চিরুনি, সুতার তাগা এবং খেজুরের খোসায়। প্রথম ব্যক্তি জিজ্ঞেস করল, এগুলো কোথায় আছে? দ্বিতীয় ব্যক্তি জবাব দিল, যারওয়ান কূপে। তখন নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম সেখানে গেলেন এবং ফিরে আসলেন, অতঃপর তিনি ‘আয়িশাহ (রাঃ)-কে বললেন, কূপের কাছের খেজুর গাছগুলো যেন এক একটা শয়তানের মাথা। তখন আমি জিজ্ঞেস করলাম, আপনি কি সেই যাদু করা জিনিসগুলো বের করতে পেরেছেন? তিনি বলেন, না। তবে আল্লাহ আমাকে আরোগ্য দিয়েছেন। আমার আশংকা হয়েছিল এসব জিনিস বের করলে মানুষের মধ্যে ফাসাদ সৃষ্টি হতে পারে। অতঃপর সেই কূপটি বন্ধ করে দেয়া হল। (৩১৭৫) (আধুনিক প্রকাশনীঃ ৩০২৭, ইসলামিক ফাউন্ডেশনঃ ৩০৩৭)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3268</td></tr><tr><td>Arabic No</td><td>3268</td></tr><tr><td>Reference</td><td>Book 59 Hadith 78</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated 'Aisha:Magic was worked on the Prophet (ﷺ) so that he began to fancy that he was doing a thing which he was not actually doing. One day he invoked (Allah) for a long period and then said, "I feel that Allah has inspired me as how to cure myself. Two persons came to me (in my dream) and sat, one by my head and the other by my feet. One of them asked the other, "What is the ailment of this man?" The other replied, 'He has been bewitched" The first asked, 'Who has bewitched him?' The other replied, 'Lubaid bin Al-A'sam.' The first one asked, 'What material has he used?' The other replied, 'A comb, the hair gathered on it, and the outer skin of the pollen of the male date-palm.' The first asked, 'Where is that?' The other replied, 'It is in the well of Dharwan.' " So, the Prophet (ﷺ) went out towards the well and then returned and said to me on his return, "Its date-palms (the date-palms near the well) are like the heads of the devils." I asked, "Did you take out those things with which the magic was worked?" He said, "No, for I have been cured by Allah and I am afraid that this action may spread evil amongst the people." Later on the well was filled up with earth
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3268</td></tr><tr><td>Arabic No</td><td>3268</td></tr><tr><td>Reference</td><td>Book 59 Hadith 78</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah bercerita kepada kami [Ibrahim bin Musa] telah mengabarkan kepada kami ['Isa] dari [Hisyam] dari [bapaknya] dari ['Aisyah Radliallahu 'anha] berkata; "Nabi shallallahu 'alaihi wasallam tekah disihir". Dan berkata [Al Laits]; " [Hisyam] menulis surat kepadaku bahwa dia mendengarnya, dia anggap dari [bapaknya] dari ['Aisyah radliallahu 'anhuma] berkata; "Nabi shallallahu 'alaihi wasallam telah disihir hingga terbayang oleh beliau seolah-olah berbuat sesuatu padahal tidak. Hingga pada suatu hari Beliau memanggil-manggil kemudian berkata: "Apakah kamu menyadari bahwa Allah telah memutuskan tentang kesembuhanku?. Telah datang kepadaku dua orang, satu diantaranya duduk dekat kepalaku dan yang satu lagi duduk di dekat kakiku. Yang satu bertanya kepada yang lainnya; "Sakit apa orang ini?". Yang lain menjawab; "Kena sihir". Yang satu bertanya lagi; "Siapa yang menyihirnya?". Yang lain menjawab; "Labid bin Al A'sham". Yang satu bertanya lagi; "Dengan cara apa?". DIjawab; "Dengan cara melalui sisir, rambut yang rontok saat disisir dan putik kembang kurma jantan". Yang satu bertanya lagi; "Sekarang sihir itu diletakkan dimana?". Yang lain menjawab; "Di sumur Dzarwan". Maka Nabi shallallahu 'alaihi wasallam pergi mendatangi tempat tersebut kemudian kembali dan berkata kepada 'Aisyah setelah kembali; "Putik kurmanya bagaikan kepala-kepala syetan". Aku bertanya; "Apakah telah baginda keluarkan?". Beliau berkata: "Tidak, karena Allah telah menyembuhkan aku. Namun aku khawatir bekasnya itu dapat mempengaruhi manusia maka sumur itu aku urug (timbun)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3268</td></tr><tr><td>Arabic No</td><td>3268</td></tr><tr><td>Reference</td><td>Book 59 Hadith 78</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ஆயிஷா (ரலி) அவர்கள் கூறியதாவது: நபி (ஸல்) அவர்களுக்குச் சூனியம் வைக்கப்பட்டது. எந்த அளவுக்கென்றால் அவர்கள் ஒரு செயலைச் செய்யாமலிருக்க, அதைச் செய்ததைப் போன்று அவர்களுக்கு பிரமையூட்டப்பட்டது. இறுதியில் ஒருநாள், அவர்கள் பிரார்த்தனை செய்தவண்ணமிருந்தார்கள். பிறகு சொன்னார்கள்: ‘‘என்(மீது செய்யப்பட்டுள்ள சூனியத்திற்கான) நிவாரணம் எதில் உள்ளதோ அதை எனக்கு அல்லாஹ் அறிவித்துவிட்டதை நீ அறிவாயா? என்னிடம் (கனவில்) இரண்டு பேர் (இரு வானவர்களான ஜிப்ரீலும் மீக்காயிலும்) வந்தனர். அவர்களில் ஒருவர் (ஜிப்ரீல்) என் தலைமாட்டில் அமர்ந்தார். மற்றொருவர் (மீக்காயீல்) எனது கால்மாட்டில் அமர்ந்தார். ஒருவர் மற்றொருவரிடம் (மீக்காயீல் ஜிப்ரீலிடம்), ‘‘இந்த மனிதரைப் பீடித்துள்ள நோய் என்ன?” என்று கேட்டார். மற்றொருவர் (ஜிப்ரீல்), ‘‘இவருக்குச் சூனியம் வைக்கப்பட்டுள்ளது” என்று பதிலளித்தார். அதற்கு அவர், ‘‘இவருக்குச் சூனியம் வைத்தவர் யார்?” என்று கேட்க, (ஜிப்ரீல்) அவர்கள், ‘‘லபீத் பின் அஃஸம் (என்னும் யூதன்)” என்று பதிலளித்தார். ‘‘(அவன் சூனியம் வைத்தது) எதில்?” என்று அவர் (மீக்காயீல்) கேட்க அதற்கு, ‘‘சீப்பிலும், (இவரது) முடியிலும், ஆண் (பேரீச்சம்) பாளையின் உறையிலும்” என்று (ஜிப்ரீல்) பதிலளித்தார். அதற்கு அவர், ‘‘அது எங்கே இருக்கிறது?” என்று கேட்க, ‘‘(பனூ ஸுரைக் குலத்தாரின் தோட்டத்திலுள்ள) யிதர்வான்’ எனும் கிணற்றில்” என்று பதிலளித்தார். (இதைச் சொல்லி முடித்த)பிறகு, நபி (ஸல்) அவர்கள் அந்தக் கிணற்றை நோக்கிப் புறப்பட்டார்கள்; பிறகு திரும்பி வந்தார்கள். திரும்பி வந்தபோது என்னிடம், ‘‘அந்தக் கிணற்றிலிருக்கும் பேரீச்ச மரங்கள் ஷைத்தான்களின் தலைகளைப் போல் உள்ள”’ என்று கூறினார்கள். நான், ‘‘அதைத் தாங்கள் வெளியே எடுத்தீர்களா?” என்று கேட்டேன். அதற்கு அவர்கள், ‘‘இல்லை. என்னை அல்லாஹ் குணப்படுத்திவிட்டான். (அதை வெளியே எடுத்தால்) அது மக்களிடையே (சூனியக் கலை பரவக் காரணமாகி) குழப்பத்தைக் கிளப்பிவிடும் என்று நான் அஞ்சினேன்” என்று பதிலளித்தார்கள். பிறகு, அந்தக் கிணறு தூர்க்கப்பட்டுவிட்டது.72 இந்த ஹதீஸ் இரு அறிவிப்பாளர்தொடர்களில் வந்துள்ளது. அத்தியாயம் : 59
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3268</td></tr><tr><td>Arabic No</td><td>3268</td></tr><tr><td>Reference</td><td>Book 59 Hadith 78</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Hz. Aişe: "Nebi Sallallahu Aleyhi ve Sellem'e sihir yapıldı" demiştir. Bu rivayeti nakledenlerden Leys şöyle demiştir: "Hişam bana bir mektup yazarak bunu Aişe r.anha'dan işitip ezberlediğini bildirdi. Söylediğine göre Hz. Aişe şunları anlatmıştı: Nebi Sallallahu Aleyhi ve Sellem'e sihir yapıldı. Hatta bu yüzden bazen aslında yapmadığı bir şeyi yaptığını zannediyordu. Bir gün dua üstüne dua etti sonra şöyle buyurdu: Ya Aişe, sen de hissettin mi? Allah bana rahatsızlığımı giderecek, şifa bulmamı sağlayacak yolu gösterdi! Yanıma iki kişi geldi. Bunlardan biri baş ucuma diğeri de ayak ucuma oturdu ve konuşmaya başladılar: - Bu zatın hastalığı, rahatsızlığı nedir? - Kendisine sihir yapılmış! - Peki bu büyüyü ona yapan kim? - Lebid İbnü'I-A'sam! - Büyüyü ne ile yapmış peki? - Bir tarak, saç ve sakal tarantısı, erkek hurmanın kurumuş çiçek kapçığı ile! - Büyü yaptığı bu parçalar şimdi nerede? - Zervan kuyusunda! Daha sonra Resulullah Sallallahu Aleyhi ve Sellem O kuyuya gitti ve döndüğünde bana: "O kuyudan sulanan hurma ağaçlarının uçları adeta şeytanların başlarına benziyor!" dedi. Ben: "Kuyudan o büyüyü çıkarıp çözdünüz mü?" diye sorunca şöyle buyurdu: "Hayır çıkarmadım. Allah beni bu rahatsızlıktan kurtarıp bana şifa verdi. Ben sihir yapılan bu parçaların insanlara zarar vereceğinden endişe duydum." Daha sonra bu kuyu kapatıldı
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3268</td></tr><tr><td>Arabic No</td><td>3268</td></tr><tr><td>Reference</td><td>Book 59 Hadith 78</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ہم سے ابراہیم بن موسیٰ نے بیان کیا، کہا ہم کو عیسیٰ بن یونس نے خبر دی، انہیں ہشام نے، انہیں ان کے والد عروہ نے اور ان سے عائشہ رضی اللہ عنہما نے بیان کیا کہ نبی کریم صلی اللہ علیہ وسلم پر ( جب آپ صلی اللہ علیہ وسلم حدیبیہ سے لوٹے تھے ) جادو ہوا تھا۔ اور لیث بن سعد نے بیان کیا کہ مجھے ہشام نے لکھا تھا، انہوں نے اپنے والد سے سنا تھا اور یاد رکھا تھا اور ان سے عائشہ رضی اللہ عنہا نے بیان کیا تھا کہ نبی کریم صلی اللہ علیہ وسلم پر جادو کیا گیا تھا۔ آپ کے ذہن میں بات ہوتی تھی کہ فلاں کام میں کر رہا ہوں حالانکہ آپ اسے نہ کر رہے ہوتے۔ آخر ایک دن آپ نے دعا کی پھر دعا کی کہ اللہ پاک اس جادو کا اثر دفع کرے۔ اس کے بعد آپ نے عائشہ رضی اللہ عنہا سے فرمایا کہ تمہیں معلوم بھی ہوا اللہ تعالیٰ نے مجھے وہ تدبیر بتا دی ہے جس میں میری شفا مقدر ہے۔ میرے پاس دو آدمی آئے، ایک تو میرے سر کی طرف بیٹھ گئے اور دوسرا پاؤں کی طرف۔ پھر ایک نے دوسرے سے کہا، انہیں بیماری کیا ہے؟ دوسرے آدمی نے جواب دیا کہ ان پر جادو ہوا ہے۔ انہوں نے پوچھا، جادو ان پر کس نے کیا ہے؟ جواب دیا کہ لبید بن اعصم یہودی نے، پوچھا کہ وہ جادو ( ٹونا ) رکھا کس چیز میں ہے؟ کہا کہ کنگھے میں، کتان میں اور کھجور کے خشک خوشے کے غلاف میں۔ پوچھا، اور یہ چیزیں ہیں کہاں؟ کہا بئر دوران میں۔ پھر نبی کریم صلی اللہ علیہ وسلم وہاں تشریف لے گئے اور واپس آئے تو عائشہ رضی اللہ عنہا سے فرمایا، وہاں کے کھجور کے درخت ایسے ہیں جیسے شیطان کی کھوپڑی۔ میں نے آپ صلی اللہ علیہ وسلم سے پوچھا، وہ ٹونا آپ نے نکلوایا بھی؟ آپ صلی اللہ علیہ وسلم نے فرمایا کہ نہیں مجھے تو اللہ تعالیٰ نے خود شفا دی اور میں نے اسے اس خیال سے نہیں نکلوایا کہ کہیں اس کی وجہ سے لوگوں میں کوئی جھگڑا کھڑا کر دوں۔ اس کے بعد وہ کنواں بند کر دیا گیا۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3268</td></tr><tr><td>Arabic No</td><td>3268</td></tr><tr><td>Reference</td><td>Book 59 Hadith 78</td></tr></tbody></table></div>