## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا عَبْدَانُ، وَمُحَمَّدٌ، قَالاَ أَخْبَرَنَا عَبْدُ اللَّهِ، أَخْبَرَنَا عَاصِمُ بْنُ سُلَيْمَانَ، عَنْ أَبِي عُثْمَانَ، قَالَ حَدَّثَنِي أُسَامَةُ بْنُ زَيْدٍ ـ رضى الله عنهما ـ قَالَ أَرْسَلَتِ ابْنَةُ النَّبِيِّ صلى الله عليه وسلم إِلَيْهِ إِنَّ ابْنًا لِي قُبِضَ فَائْتِنَا‏.‏ فَأَرْسَلَ يُقْرِئُ السَّلاَمَ وَيَقُولُ ‏"‏ إِنَّ لِلَّهِ مَا أَخَذَ وَلَهُ مَا أَعْطَى وَكُلٌّ عِنْدَهُ بِأَجَلٍ مُسَمًّى، فَلْتَصْبِرْ وَلْتَحْتَسِبْ ‏"‏‏.‏ فَأَرْسَلَتْ إِلَيْهِ تُقْسِمُ عَلَيْهِ لَيَأْتِيَنَّهَا، فَقَامَ وَمَعَهُ سَعْدُ بْنُ عُبَادَةَ وَمُعَاذُ بْنُ جَبَلٍ وَأُبَىُّ بْنُ كَعْبٍ وَزَيْدُ بْنُ ثَابِتٍ وَرِجَالٌ، فَرُفِعَ إِلَى رَسُولِ اللَّهِ صلى الله عليه وسلم الصَّبِيُّ وَنَفْسُهُ تَتَقَعْقَعُ ـ قَالَ حَسِبْتُهُ أَنَّهُ قَالَ ـ كَأَنَّهَا شَنٌّ‏.‏ فَفَاضَتْ عَيْنَاهُ‏.‏ فَقَالَ سَعْدٌ يَا رَسُولَ اللَّهِ مَا هَذَا فَقَالَ ‏"‏ هَذِهِ رَحْمَةٌ جَعَلَهَا اللَّهُ فِي قُلُوبِ عِبَادِهِ، وَإِنَّمَا يَرْحَمُ اللَّهُ مِنْ عِبَادِهِ الرُّحَمَاءَ ‏"‏‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1284</td></tr><tr><td>Arabic No</td><td>1284</td></tr><tr><td>Reference</td><td>Book 23 Hadith 44</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
لِقَوْلِ اللَّهِ تَعَالَى: (قُوا أَنْفُسَكُمْ وَأَهْلِيكُمْ نَارًا). وَقَالَ النَّبِيُّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ: «كُلُّكُمْ رَاعٍ، وَمَسْئُولٌ عَنْ رَعِيَّتِهِ». فَإِذَا لَمْ يَكُنْ مِنْ سُنَّتِهِ، فَهُوَ كَمَا قَالَتْ عَائِشَةُ رَضِيَ اللَّهُ عَنْهَا: (لاَ تَزِرُ وَازِرَةٌ وِزْرَ أُخْرَى). وَهُوَ كَقَوْلِهِ: (وَإِنْ تَدْعُ مُثْقَلَةٌ) ذُنُوبًا (إِلَى حِمْلِهَا لاَ يُحْمَلْ مِنْهُ شَيْءٌ) وَمَا يُرَخَّصُ مِنَ الْبُكَاءِ فِي غَيْرِ نَوْحٍ. وَقَالَ النَّبِيُّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ: «لاَ تُقْتَلُ نَفْسٌ ظُلْمًا إِلاَّ كَانَ عَلَى ابْنِ آدَمَ الأَوَّلِ كِفْلٌ مِنْ دَمِهَا». وَذَلِكَ لأَنَّهُ أَوَّلُ مَنْ سَنَّ الْقَتْلَ. কারণ আল্লাহ্ তা‘আলা ইরশাদ করেনঃ (যার অর্থ) ‘‘তোমরা নিজেদেরকে এবং তোমাদের পরিবার পরিজনকে জাহান্নামের আগুন থেকে রক্ষা কর।’’ (তাহরীমঃ ৬)। এবং নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেছেনঃ তোমাদের প্রত্যেকেই দায়িত্বশীল এবং প্রত্যেকেই তার নিজ দায়িত্ব সম্পর্কে জিজ্ঞাসিত হবে। কিন্তু তা যদি তার অভ্যাস না হয়ে থাকে তবে তার বিধান হবে যা ‘আয়িশাহ্ (রাযি.) ব্যক্ত করেছেনঃ (যার অর্থ) ‘‘নিজ বোঝা বহনকারী কোন ব্যক্তি অপরের বোঝা বহন করবে না’’- (আল-আন‘আমঃ ১৬৪)। আর এ হলো আল্লাহ্ তা‘আলার এ বাণীর ন্যায় ‘‘কোন (গুনাহের) বোঝা বহনকারী ব্যক্তি যদি কাউকেও তা বহন করার আহবান জানায় তবে তা থেকে কিছুই বহন করা হবে না- (ফাতিরঃ ১৮)। আর বিলাপ ব্যতীত ক্রন্দনের অনুমতি প্রদান করা হয়েছে। নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেছেনঃ অন্যায়ভাবে কাউকে হত্যা করা হলে সে হত্যার অপরাধের অংশ প্রথম আদম সন্তান (কাবিল) এর উপর বর্তাবে। আর সেটা এ কারণে যে, সেই প্রথম ব্যক্তি যে হত্যার প্রবর্তন করেছে। ১২৮৪. উসামাহ ইবনু যায়দ (রাঃ) হতে বর্ণিত। তিনি বলেন, নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম -এর জনৈকা কন্যা (যায়নাব) তাঁর (সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম ) নিকট লোক পাঠালেন যে, আমার এক পুত্র মরণাপন্ন অবস্থায় রয়েছে, তাই আপনি আমাদের নিকট আসুন। তিনি বলে পাঠালেন, (তাঁকে) সালাম দিবে এবং বলবেঃ আল্লাহ্‌রই অধিকারে যা কিছু তিনি নিয়ে যান আর তাঁরই অধিকারে যা কিছু তিনি দান করেন। তাঁর নিকট সকল কিছুরই একটি নির্দিষ্ট সময় আছে। কাজেই সে যেন ধৈর্য ধারণ করে এবং সাওয়াবের অপেক্ষায় থাকে। তখন তিনি তাঁর কাছে কসম দিয়ে পাঠালেন, তিনি যেন অবশ্যই আগমন করেন। তখন তিনি দন্ডায়মান হলেন এবং তাঁর সাথে ছিলেন সা’দ ইবনু উবাদাহ, মু‘আয ইবনু জাবাল, উবাই ইবনু কা’ব, যাইদ ইবনু সাবিত (রাঃ) এবং আরও কয়েকজন। তখন শিশুটিকে রাসূলুল্লাহ্ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম -এর কাছে তুলে দেয়া হল। তখন সে ছটফট করছিল। বর্ণনাকারী বলেন, আমার ধারণা যে, তিনি এ কথা বলেছিলেন, যেন তার শ্বাস মশকের মত (শব্দ হচ্ছিল)। আর নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম -এর দু’ চক্ষু বেয়ে অশ্রু ঝরছিল। সা’দ (রাঃ) বললেন, হে আল্লাহ্‌র রাসূল! একি? তিনি বললেনঃ এ হচ্ছে রহমত, যা আল্লাহ্ তাঁর বান্দার অন্তরে গচ্ছিত রেখেছেন। আর আল্লাহ্ তো তাঁর দয়ালু বান্দাদের প্রতিই দয়া করেন। (৫৬৫৫, ৬৬০২, ৬৬৫৫, ৭৩৭৭, ৭৪৪৮, মুসলিম ১১/৬, হাঃ ৯২৩, আহমাদ ২১৮৫৮) (আধুনিক প্রকাশনীঃ ১২০১, ইসলামিক ফাউন্ডেশনঃ ১২০৯)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1284</td></tr><tr><td>Arabic No</td><td>1284</td></tr><tr><td>Reference</td><td>Book 23 Hadith 44</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated Usama bin Zaid:The daughter of the Prophet (p.b.u.h) sent (a messenger) to the Prophet (ﷺ) requesting him to come as her child was dying (or was gasping), but the Prophet (ﷺ) returned the messenger and told him to convey his greeting to her and say: "Whatever Allah takes is for Him and whatever He gives, is for Him, and everything with Him has a limited fixed term (in this world) and so she should be patient and hope for Allah's reward." She again sent for him, swearing that he should come. The Prophet (ﷺ) got up, and so did Sa'd bin 'Ubada, Mu'adh bin Jabal, Ubai bin Ka'b, Zaid bin Thabit and some other men. The child was brought to Allah's Messenger (ﷺ) while his breath was disturbed in his chest (the sub-narrator thinks that Usama added: ) as if it was a leather water-skin. On that the eyes of the Prophet (p.b.u.h) started shedding tears. Sa'd said, "O Allah's Messenger (ﷺ)! What is this?" He replied, "It is mercy which Allah has lodged in the hearts of His slaves, and Allah is merciful only to those of His slaves who are merciful (to others)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1284</td></tr><tr><td>Arabic No</td><td>1284</td></tr><tr><td>Reference</td><td>Book 23 Hadith 44</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami ['Abdan] dan [Muhammad] keduanya berkata, telah mengabarkan kepada kami ['Abdullah] telah mengabarkan kepada kami ['Ashim bin Sulaiman] dari [Abu 'Utsman] berkata, telah menceritakan kepada saya [Usamah bin Zaid radliallahu 'anhuma] berkata; Putri Nabi Shallallahu'alaihiwasallam datang untuk menemui Beliau dan mengabarkan bahwa; "Anakku telah meninggal, maka datanglah kepada kami". Maka Nabi Shallallahu'alaihiwasallam memerintahkannya untuk menyampaikan salam lalu bersabda: "Sesungguhnya milik Allah apa yang diambilNya dan apa yang diberiNya. Dan segala sesuatu disisiNya sesudah ditentukan ajalnya, maka bersabarlah engkau karenanya dan mohonkanlah pahala darinya." Kemudian dia datang lagi kepada Beliau dan meminta dengan sangat agar Beliau bisa datang. Maka Beliau berangkat, bersamanya ada Sa'ad bin 'Ubadah, Mu'adz bin Jabal, Ubay bin Ka'ab, Zaid bin Tsabit dan beberapa orang lain. Kemudian bayi tersebut diserahkan kepada Nabi Shallallahu'alaihiwasallam dan hati Beliau nampak berguncang (karena bersedih). Aku menduga dia berkata,: Seakan dia seperti geriba yang kosong. Maka mengalirlah air mata Beliau. Sa'ad berkata,: "Wahai Rasulullah, mengapakah engkau menangis? Beliau berkata,: "Inilah rahmat yang Allah berikan kepada hati hamba-hambaNya dan sesungguhnya Allah akan merahmati diantara hamba-hambaNya mereka yang saling berkasih sayang
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1284</td></tr><tr><td>Arabic No</td><td>1284</td></tr><tr><td>Reference</td><td>Book 23 Hadith 44</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
உசாமா பின் ஸைத் (ரலி) அவர்கள் கூறியதாவது: நபி (ஸல்) அவர்களின் மகள் (ஸைனப்-ரலி) தம் மகன் இறக்கும் தறுவாயில் இருப்பதால் உடனே வரும்படி நபியவர்களுக்குச் செய்தியனுப்பினார். நபி (ஸல்) அவர்கள், தம் மகளுக்கு சலாம் கூறி அனுப்பியதோடு, “எடுத்ததும் கொடுத்ததும் அல்லாஹ்வுக்குரியதே! ஒவ்வொன்றுக்கும் அவனிடம் ஒரு குறிப்பிட்ட தவணை உண்டு. எனவே, பொறுமையாக இருந்து நன்மையை எதிர்பார்ப்பீராக!” என்றும் கூறி அனுப்பினார்கள். அப்போது அவர்களுடைய மகள் அல்லாஹ்வின் மீது ஆணையிட்டு, கண்டிப்பாக வரவேண்டும் எனக் கூறியனுப்பினார். உடனே நபி (ஸல்) அவர்கள் எழுந்தார்கள். அவர்களுடன் சஅத் பின் உபாதா, முஆத் பின் ஜபல், உபை பின் கஅப், ஸைத் பின் ஸாபித் (ரலி) ஆகியோரும் மற்றும் பலரும் எழுந் தனர். (வீட்டுக்குச் சென்ற) அல்லாஹ்வின் தூதர் (ஸல்) அவர்களிடம், சுவாசிக்க முடியாமல் மூச்சுத் திணறிக்கொண்டி ருந்த குழந்தை எடுத்துத் தரப்பட்டது. இற்றுப்போன பழைய தோல்துருத்தி போல் (குழந்தையின் மார்பு ஏறி இறங்கியது.) நபி (ஸல்) அவர்களின் கண்கள் நீர் சொரிந்தன. அப்போது “அல்லாஹ்வின் தூதரே! என்ன இது (அழுகிறீர்கள்)?” என சஅத் (ரலி) அவர்கள் கேட்டார்கள். அதற்கு நபி (ஸல்) அவர்கள், “இது, அல்லாஹ் தன் அடியார்களின் உள்ளங்களில் ஏற்படுத்திய இரக்க உணர்வாகும். நிச்சயமாக அல்லாஹ் தன் அடியார் களில் இரக்கமுடையவர்க்கே இரக்கம் காட்டுகிறான்” என்றார்கள். அத்தியாயம் : 23
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1284</td></tr><tr><td>Arabic No</td><td>1284</td></tr><tr><td>Reference</td><td>Book 23 Hadith 44</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Usame İbn Zeyd r.a. şöyle demiştir: Nebi Sallallahu Aleyhi ve Sellem'in kızı (Zeynep r.anha) "Oğlum ölmek üzere, bize geliniz" diye Resulullah'a haber gönderdi. Resulullah Sallallahu Aleyhi ve Sellem kızına selam gönderip şöyle cevap yolladı: "Aldığı da verdiği de Allah'a aittir. Her şey'in Allah katında bir eceli vardır. Sabret! Sabrının sevabını Allah'tan bekle." (Zeynep) and vererek Nebi Sallallahu Aleyhi ve Sellem'in gelmesi için bir kez daha haber yolladı. Bunun üzerine Nebi Sallallahu Aleyhi ve Sellem yanında Sa'd İbn Muaz, Muaz İbn Cebel, Ubey İbn Ka'b, Zeyd İbn Sabit ve başka kimseler bulunduğu halde (Zeyneb'in yanına) gitti. Çocuk (can çekişme halinde) çırpınırken Resulullah Sallallahu Aleyhi ve Sellem'e verildi. Nebi (Sallallahu aleyhi ve Sellem)’in mubarek gözlerinden yaşlar boşalıyordu. Sa'd: "Ey Allah'ın Resulü! Bu ağlama neyin nesi?" dîye sordu. Nebi Sallallahu Aleyhi ve Sellem: Bu, Allah'ın kullarının kalplerine koyduğu rahmettir. Allah kullarından yalnızca merhamet sahibi olanlara merhamet eder. Tekrar: 5655, 6602, 6655, 7277, 7448
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1284</td></tr><tr><td>Arabic No</td><td>1284</td></tr><tr><td>Reference</td><td>Book 23 Hadith 44</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ہم سے عبد ان اور محمد بن مقاتل نے بیان کیا ‘ انہوں نے کہا کہ ہمیں امام عبداللہ بن مبارک نے خبر دی ‘ کہا کہ ہم کو عاصم بن سلیمان نے خبر دی ‘ انہیں ابوعثمان عبدالرحمٰن نہدی نے ‘ کہا کہ مجھ سے اسامہ بن زید رضی اللہ عنہما نے بیان کیا کہ نبی کریم صلی اللہ علیہ وسلم کی ایک صاحبزادی ( زینب رضی اللہ عنہا ) نے آپ صلی اللہ علیہ وسلم کو اطلاع کرائی کہ میرا ایک لڑکا مرنے کے قریب ہے ‘ اس لیے آپ صلی اللہ علیہ وسلم تشریف لائیں۔ آپ صلی اللہ علیہ وسلم نے انہیں سلام کہلوایا اور کہلوایا کہ اللہ تعالیٰ ہی کا سارا مال ہے ‘ جو لے لیا وہ اسی کا تھا اور جو اس نے دیا وہ بھی اسی کا تھا اور ہر چیز اس کی بارگاہ سے وقت مقررہ پر ہی واقع ہوتی ہے۔ اس لیے صبر کرو اور اللہ تعالیٰ سے ثواب کی امید رکھو۔ پھر زینب رضی اللہ عنہا نے قسم دے کر اپنے یہاں بلوا بھیجا۔ اب رسول اللہ صلی اللہ علیہ وسلم جانے کے لیے اٹھے۔ آپ صلی اللہ علیہ وسلم کے ساتھ سعد بن عبادہ ‘ معاذ بن جبل ‘ ابی بن کعب ‘ زید بن ثابت اور بہت سے دوسرے صحابہ رضی اللہ عنہم بھی تھے۔ بچے کو رسول اللہ صلی اللہ علیہ وسلم کے سامنے کیا گیا۔ جس کی جانکنی کا عالم تھا۔ ابوعثمان نے کہا کہ میرا خیال ہے کہ اسامہ رضی اللہ عنہ نے فرمایا کہ جیسے پرانا مشکیزہ ہوتا ہے ( اور پانی کے ٹکرانے کی اندر سے آواز ہوتی ہے۔ اسی طرح جانکنی کے وقت بچہ کے حلق سے آواز آ رہی تھی ) یہ دیکھ کر رسول اللہ صلی اللہ علیہ وسلم کی آنکھوں سے آنسو بہ نکلے۔ سعد رضی اللہ عنہ بول اٹھے کہ یا رسول اللہ! یہ رونا کیسا ہے؟ آپ صلی اللہ علیہ وسلم نے فرمایا کہ یہ تو اللہ کی رحمت ہے کہ جسے اللہ تعالیٰ نے اپنے ( نیک ) بندوں کے دلوں میں رکھا ہے اور اللہ تعالیٰ بھی اپنے ان رحم دل بندوں پر رحم فرماتا ہے جو دوسروں پر رحم کرتے ہیں۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1284</td></tr><tr><td>Arabic No</td><td>1284</td></tr><tr><td>Reference</td><td>Book 23 Hadith 44</td></tr></tbody></table></div>