## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا عَلِيُّ بْنُ عَبْدِ اللَّهِ، قَالَ حَدَّثَنَا سُفْيَانُ، قَالَ حَدَّثَنَا أَبُو حَازِمٍ، قَالَ سَأَلُوا سَهْلَ بْنَ سَعْدٍ مِنْ أَىِّ شَىْءٍ الْمِنْبَرُ فَقَالَ مَا بَقِيَ بِالنَّاسِ أَعْلَمُ مِنِّي هُوَ مِنْ أَثْلِ الْغَابَةِ، عَمِلَهُ فُلاَنٌ مَوْلَى فُلاَنَةَ لِرَسُولِ اللَّهِ صلى الله عليه وسلم، وَقَامَ عَلَيْهِ رَسُولُ اللَّهِ صلى الله عليه وسلم حِينَ عُمِلَ، وَوُضِعَ، فَاسْتَقْبَلَ الْقِبْلَةَ كَبَّرَ وَقَامَ النَّاسُ خَلْفَهُ، فَقَرَأَ وَرَكَعَ وَرَكَعَ النَّاسُ خَلْفَهُ، ثُمَّ رَفَعَ رَأْسَهُ، ثُمَّ رَجَعَ الْقَهْقَرَى، فَسَجَدَ عَلَى الأَرْضِ، ثُمَّ عَادَ إِلَى الْمِنْبَرِ، ثُمَّ قَرَأَ ثُمَّ رَكَعَ، ثُمَّ رَفَعَ رَأْسَهُ، ثُمَّ رَجَعَ الْقَهْقَرَى حَتَّى سَجَدَ بِالأَرْضِ، فَهَذَا شَأْنُهُ‏.‏ قَالَ أَبُو عَبْدِ اللَّهِ قَالَ عَلِيُّ بْنُ عَبْدِ اللَّهِ سَأَلَنِي أَحْمَدُ بْنُ حَنْبَلٍ ـ رَحِمَهُ اللَّهُ ـ عَنْ هَذَا الْحَدِيثِ، قَالَ فَإِنَّمَا أَرَدْتُ أَنَّ النَّبِيَّ صلى الله عليه وسلم كَانَ أَعْلَى مِنَ النَّاسِ، فَلاَ بَأْسَ أَنْ يَكُونَ الإِمَامُ أَعْلَى مِنَ النَّاسِ بِهَذَا الْحَدِيثِ‏.‏ قَالَ فَقُلْتُ إِنَّ سُفْيَانَ بْنَ عُيَيْنَةَ كَانَ يُسْأَلُ عَنْ هَذَا كَثِيرًا فَلَمْ تَسْمَعْهُ مِنْهُ قَالَ لاَ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>377</td></tr><tr><td>Arabic No</td><td>377</td></tr><tr><td>Reference</td><td>Book 8 Hadith 29</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
قَالَ أَبُو عَبْد اللهِ وَلَمْ يَرَ الْحَسَنُ بَأْسًا أَنْ يُصَلَّى عَلَى الْجُمْدِ وَالْقَنَاطِرِ وَإِنْ جَرَى تَحْتَهَا بَوْلٌ أَوْ فَوْقَهَا أَوْ أَمَامَهَا إِذَا كَانَ بَيْنَهُمَا سُتْرَةٌ وَصَلَّى أَبُو هُرَيْرَةَ عَلَى سَقْفِ الْمَسْجِدِ بِصَلاَةِ الْإِمَامِ وَصَلَّى ابْنُ عُمَرَ عَلَى الثَّلْجِ আবূ ‘আবদুল্লাহ (ইমাম বুখারী) (রহ.) বলেনঃ হাসান বাসরী (রহ.) বরফ ও পুলের উপর সালাত আদায় করা দোষের মনে করতেন না- যদিও তার নীচ দিয়ে, উপর দিয়ে অথবা সামনের দিক দিয়ে পেশাব প্রবাহিত হয়; যদি উভয়ের মাঝে কোন ব্যবধান থাকে। আবূ হুরাইরাহ্ (রাযি.) মসজিদের ছাদে ইমামের সাথে সালাত আদায় করেছিলেন। ইবনু ‘উমার (রাযি.) বরফের উপর সালাত আদায় করেছেন। ৩৭৭. আবূ হাযিম (রহ.) হতে বর্ণিত যে, লোকেরা সাহল ইবনু সা‘দ (রাযি.)-কে জিজ্ঞেস করল (নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর) মিম্বার কিসের তৈরি ছিল? তিনি বললেনঃ এ বিষয়ে আমার চেয়ে বেশি জ্ঞাত আর কেউ নেই। তা ছিল গাবা নামক স্থানের ঝাউগাছের কাঠ দিয়ে তৈরি। অমুক মহিলার আযাদকৃত দাস অমুক ব্যক্তি আল্লাহর রাসূল সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম -এর জন্যে তা তৈরি করেছিল। তা পুরোপুরি তৈরি ও স্থাপিত হবার পর আল্লাহর রাসূল সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম তার উপর দাঁড়িয়ে ক্বিবলা (কিবলা/কেবলা)হর দিকে মুখ করে তাকবীর বললেন। লোকেরা তাঁর পেছনে দাঁড়িয়ে গেলেন। অতঃপর তিনি কিরাআত পড়লেন ও রুকূতে গেলেন। সকলেই তাঁর পেছনে রুকূতে গেলেন। অতঃপর তিনি মাথা তুলে পেছনে সরে গিয়ে মাটিতে সিজদা করলেন। পুনরায় মিম্বারে ফিরে আসলেন এবং কিরাআত পড়ে রুকূতে গেলেন। অতঃপর তাঁর মাথা তুললেন এবং পেছনে সরে গিয়ে মাটিতে সিজদা করলেন। এ হলো মিম্বারের ইতিহাস। আবূ ‘আবদুল্লাহ (ইমাম বুখারী) (রহ.) বলেনঃ ‘আলী ইবনু ‘আবদুল্লাহ(রহ.) বলেছেন যে, আমাকে আহমদ ইবনু হাম্বাল (রহ.) এ হাদীস সম্পর্কে জিজ্ঞেস করেছিলেন এবং বলেছিলেনঃ আমার ধারণা, নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম সবচাইতে উঁচু স্থানে ছিলেন। সুতরাং ইমামের মুক্তাদীদের চেয়ে উঁচু স্থানে দাঁড়ানোতে কোন দোষ নেই। ‘আলী ইবনু ‘আবদুল্লাহ (রহ.) বলেনঃ আমি আহমাদ ইবনু হাম্বল (রহ.)-কে বললামঃ সুফইয়ান ইবনু ‘উয়াইনাহ (রহ.)-কে এ বিষয়ে বহুবার জিজ্ঞেস করা হয়েছে, আপনি তাঁর নিকট এ বিষয়ে কিছু শোনেননি? তিনি জবাব দিলেনঃ না। (৪৪৮, ৯১৭, ২০৯৪, ২৫৬৯; মুসলিম ৫/১০, হাঃ ৫৪৪, আহমাদ ২২৯৩৪ দ্রষ্টব্য) (আধুনিক প্রকাশনীঃ ৩৬৪, ইসলামিক ফাউন্ডেশনঃ ৩৭০)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>377</td></tr><tr><td>Arabic No</td><td>377</td></tr><tr><td>Reference</td><td>Book 8 Hadith 29</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated Abu Hazim:Sahl bin Sa'd was asked about the (Prophet's) pulpit as to what thing it was made of? Sahl replied: "None remains alive amongst the people, who knows about it better than I. It was made of tamarisk (wood) of the forest. So and so, the slave of so and so prepared it for Allah's Messenger (ﷺ) . When it was constructed and place (in the Mosque), Allah's Messenger (ﷺ) stood on it facing the Qibla and said 'Allahu Akbar', and the people stood behind him (and led the people in prayer). He recited and bowed and the people bowed behind him. Then he raised his head and stepped back, got down and prostrated on the ground and then he again ascended the pulpit, recited, bowed, raised his head and stepped back, got down and prostrate on the ground. So, this is what I know about the pulpit." Ahmad bin Hanbal said, "As the Prophet (ﷺ) was at a higher level than the people, there is no harm according to the above-mentioned Hadith if the Imam is at a higher level than his followers during the prayers
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>377</td></tr><tr><td>Arabic No</td><td>377</td></tr><tr><td>Reference</td><td>Book 8 Hadith 29</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami ['Ali bin 'Abdullah] berkata, telah menceritakan kepada kami [Sufyan] berkata, telah menceritakan kepada kami [Abu Hazim] berkata, "Orang-orang bertanya kepada [Sahal bin Sa'd] tentang terbuat dari apa mimbar Rasulullah? Maka dia berkata, "Tidak ada seorangpun yang masih hidup dari para sahabat yang lebih mengetahui masalah ini selain aku. Mimbar itu terbuat dari batang pohon hutan yang tak berduri, mimbar itu dibuat oleh seorang budak wanita untuk Rasulullah shallallahu 'alaihi wasallam. Ketika selesai dibuat dan diletakkan, Rasulullah shallallahu 'alaihi wasallam berdiri pada mimbar tersebut menghadap kiblat. Beliau bertakbir dan orang-orang pun ikut shalat dibelakangnya, beliau lalu membaca surat lalu rukuk, dan orang-orang pun ikut rukuk di belakangnya. Kemudian beliau mengangkat kepalanya, lalu mundur ke belakang turun dan sujud di atas tanah. Kemudian beliau kembali ke atas mimbar dan rukuk, kemudian mengangkat kepalnya lalu turun kembali ke tanah pada posisi sebelumnya dan sujud di tanah. Itulah keberadaan mimbar." Abu 'Abdullah berkata, 'Ali Al Madini berkata, Ahmad bin Hambal rahimahullah bertanya kepadaku tentang hadits ini. Ia katakan, "Yang aku maksudkan bahwa Nabi shallallahu 'alaihi wasallam posisinya lebih tinggi daripada orang-orang. Maka tidak mengapa seorang imam posisinya lebih tinggi daripada Makmum berdasarkan hadits ini." Sahl bin Sa'd berkata, "Aku katakan, "Sesungguhnya Sufyan bin 'Uyainah sering ditanya tentang masalah ini, 'Apakah kamu tidak pernah mendengarnya? ' Ahmad bin Hambal rahimahullah menjawab, "Tidak
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>377</td></tr><tr><td>Arabic No</td><td>377</td></tr><tr><td>Reference</td><td>Book 8 Hadith 29</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
அபூஹாஸிம் (சலமா பின் தீனார்- ரஹ்) அவர்கள் கூறியதாவது: (மக்களில் சிலர்) சஹ்ல் பின் சஅத் (ரலி) அவர்களிடம், “(நபி (ஸல்) அவர்கள் பயன்படுத்திய) அந்தச் சொற்பொழிவு மேடை (மிம்பர்) எதனால் செய்யப்பட்டது?” என்று வினவினர். அதற்கு சஹ்ல் (ரலி) அவர்கள் கூறினார்கள்: மக்களில் என்னைவிட (இது பற்றி) நன்கு தெரிந்தவர்கள் யாரும் (இப்போது) எஞ்சியிருக்கவில்லை. அது ஒரு வகை சவுக்கு மரத்தால் செய்யப்பட்டதாகும்; அதை இன்ன பெண்மணியின் அடிமையான இன்னாரே அல்லாஹ்வின் தூதர் (ஸல்) அவர்களுக்காகச் செய்(து கொடுத்)தார். அது செய்யப்பட்டு (உரிய இடத்தில்) வைக்கப்பட்டபோது அதன்மீது அல்லாஹ் வின் தூதர் (ஸல்) அவர்கள் (ஏறி) நின்று கிப்லாவை முன்னோக்கி (தொழுகைக்காக) தக்பீர் (தஹ்ரீமா) சொன்னார்கள். மக்களும் அவர்களுக்குப் பின்னால் (தொழுகையில்) நின்றார்கள். அப்போது அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் (குர்ஆன் வசனங் களை) ஓதிவிட்டு, ‘ருகூஉ’ செய்தார்கள். மக்களும் அவர்களுக்குப் பின்னால் ருகூஉ செய்தனர். பிறகு நபி (ஸல்) அவர்கள் தலையை உயர்த்தி (நிமிர்ந்து நின்றுவிட்டு)ப் பிறகு (முதுகைத் திருப்பாமல்) பின்வாக்கில் நகர்ந்து தரையில் (இறங்கி) சஜ்தா செய்தார்கள். பிறகு திரும்பவும் மேடைக் குத் திரும்பினார்கள். பிறகு (இரண்டாவது ரக்அத்தில் குர்ஆன் வசனங்களை) ஓதினார்கள். பிறகு ருகூஉ செய்தார்கள். அதன் பின்னர் தலையை உயர்த்தி (நிமிர்ந்து நின்று விட்டு)ப் பிறகு (முதுகைத் திருப்பாமல்) பின்வாக்கில் நகர்ந்து வந்து தரையின்மீது சஜ்தா (சிரவணக்கம்) செய்தார்கள். இதுதான் நடந்த நிகழ்ச்சியாகும். அபூஅப்தில்லாஹ் (புகாரீ ஆகிய நான்) கூறுகிறேன். அலீ பின் அப்தில்லாஹ் அல்மதீனீ (ரஹ்) அவர்கள் கூறினார்கள்: என்னிடம் அஹ்மத் பின் ஹம்பல் (ரஹ்) அவர்கள் இந்த ஹதீஸ் பற்றிக் கூறுகையில், “(தொழுகையில்) நபி (ஸல்) அவர்கள், (பின்பற்றித் தொழுத) மக்களை விட உயரமான இடத்தில் (நின்றுகொண்டு) இருந்தார்கள் என்று கூறும் இந்த ஹதீஸிலிருந்து ‘மக்களைவிட உயரமான இடத்தில் இமாம் இருப்பதில் தவறில்லை’ என்றே நான் கருதுகிறேன்” என்றார்கள். அப்போது நான், “(இது சம்பந்தமாக) சுஃப்யான் பின் உயைனா (ரஹ்) அவர்களிடம் அதிகமாகக் கேட்கப்படுகிறதாமே! அவரிடமிருந்து இந்த ஹதீஸை நீங்கள் செவியுறவில்லையா?” என்று கேட்டேன். அதற்கு அஹ்மத் பின் ஹம்பல் (ரஹ்) அவர்கள், “இல்லை (நான் அவரிடமிருந்து இந்த ஹதீஸைச் செவியுறவில்லை)” என்று பதிலளித்தார்கள். அத்தியாயம் : 8
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>377</td></tr><tr><td>Arabic No</td><td>377</td></tr><tr><td>Reference</td><td>Book 8 Hadith 29</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ebu Hâzim'den şöyle nakledilmiştir: "Sehl b. Sa'd'a Nebi (Sallallahu aleyhi ve Sellem)'in minberinin neden yapıldığı soruldu. O da şöyle cevap verdi: İnsanlar arasında bunu benden iyi bilen biri kalmadı. Söz konusu minber, ormandan getirilen bir ağaçtan yapıldı. Onu Falanca kadının filanca kölesi Allah Resulü için yaptı. Yapılıp yerine konduktan sonra Rasûlullah (Sallallahu aleyhi ve Sellem) onun üstüne çıkıp kıbleye yöneldi ve tekbir getirip namaza başladı, insanlar da onun arkasında namaza durdu. (Fatiha ve zammı sureden oluşan) Kur'ân'ı okuduktan sonra rüku'a gitti. Peşi sıra cemaat da rüku'a eğildi. Sonra başını kaldırdı. Yönünü kıbleden çevirmeden minberden indi ve yere secde etti. Sonra tekrar minbere çıktı. Rüku'a eğilip kalktı. Yine yönünü kıbleden çevirmeden indi ve yere secde etti." (Sehl) İşte minberin hikayesi böyle (dedi)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>377</td></tr><tr><td>Arabic No</td><td>377</td></tr><tr><td>Reference</td><td>Book 8 Hadith 29</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ہم سے علی بن عبداللہ مدینی نے بیان کیا، کہا کہ ہم سے سفیان بن عیینہ نے بیان کیا، کہا کہ ہم سے ابوحازم سلمہ بن دینار نے بیان کیا۔ کہا کہ لوگوں نے سہل بن سعد ساعدی سے پوچھا کہ منبرنبوی کس چیز کا تھا۔ آپ نے فرمایا کہ اب ( دنیائے اسلام میں ) اس کے متعلق مجھ سے زیادہ جاننے والا کوئی باقی نہیں رہا ہے۔ منبر غابہ کے جھاؤ سے بنا تھا۔ فلاں عورت کے غلام فلاں نے اسے رسول اللہ صلی اللہ علیہ وسلم کے لیے بنایا تھا۔ جب وہ تیار کر کے ( مسجد میں ) رکھا گیا تو رسول اللہ صلی اللہ علیہ وسلم اس پر کھڑے ہوئے اور آپ نے قبلہ کی طرف اپنا منہ کیا اور تکبیر کہی اور لوگ آپ کے پیچھے کھڑے ہو گئے۔ پھر آپ نے قرآن مجید کی آیتیں پڑھیں اور رکوع کیا۔ آپ کے پیچھے تمام لوگ بھی رکوع میں چلے گئے۔ پھر آپ نے اپنا سر اٹھایا۔ پھر اسی حالت میں آپ الٹے پاؤں پیچھے ہٹے۔ پھر زمین پر سجدہ کیا۔ پھر منبر پر دوبارہ تشریف لائے اور قرآت رکوع کی، پھر رکوع سے سر اٹھایا اور قبلہ ہی کی طرف رخ کئے ہوئے پیچھے لوٹے اور زمین پر سجدہ کیا۔ یہ ہے منبر کا قصہ۔ ابوعبداللہ ( امام بخاری رحمہ اللہ ) نے کہا کہ علی بن عبداللہ مدینی نے کہا کہ مجھ سے امام احمد بن حنبل نے اس حدیث کو پوچھا۔ علی نے کہا کہ میرا مقصد یہ ہے کہ نبی کریم صلی اللہ علیہ وسلم نماز میں لوگوں سے اونچے مقام پر کھڑے ہوئے تھے اس لیے اس میں کوئی حرج نہ ہونا چاہیے کہ امام مقتدیوں سے اونچی جگہ پر کھڑا ہو۔ علی بن مدینی کہتے ہیں کہ میں نے امام احمد بن حنبل سے کہا کہ سفیان بن عیینہ سے یہ حدیث اکثر پوچھی جاتی تھی، آپ نے بھی یہ حدیث ان سے سنی ہے تو انہوں نے جواب دیا کہ نہیں۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>377</td></tr><tr><td>Arabic No</td><td>377</td></tr><tr><td>Reference</td><td>Book 8 Hadith 29</td></tr></tbody></table></div>