## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا مُسَدَّدٌ، قَالَ حَدَّثَنَا عَبْدُ الْوَارِثِ، عَنْ أَبِي التَّيَّاحِ، عَنْ أَنَسٍ، قَالَ قَدِمَ النَّبِيُّ صلى الله عليه وسلم الْمَدِينَةَ فَنَزَلَ أَعْلَى الْمَدِينَةِ، فِي حَىٍّ يُقَالُ لَهُمْ بَنُو عَمْرِو بْنِ عَوْفٍ‏.‏ فَأَقَامَ النَّبِيُّ صلى الله عليه وسلم فِيهِمْ أَرْبَعَ عَشْرَةَ لَيْلَةً، ثُمَّ أَرْسَلَ إِلَى بَنِي النَّجَّارِ فَجَاءُوا مُتَقَلِّدِي السُّيُوفِ، كَأَنِّي أَنْظُرُ إِلَى النَّبِيِّ صلى الله عليه وسلم عَلَى رَاحِلَتِهِ، وَأَبُو بَكْرٍ رِدْفُهُ، وَمَلأُ بَنِي النَّجَّارِ حَوْلَهُ، حَتَّى أَلْقَى بِفِنَاءِ أَبِي أَيُّوبَ، وَكَانَ يُحِبُّ أَنْ يُصَلِّيَ حَيْثُ أَدْرَكَتْهُ الصَّلاَةُ، وَيُصَلِّي فِي مَرَابِضِ الْغَنَمِ، وَأَنَّهُ أَمَرَ بِبِنَاءِ الْمَسْجِدِ، فَأَرْسَلَ إِلَى مَلإٍ مِنْ بَنِي النَّجَّارِ فَقَالَ ‏"‏ يَا بَنِي النَّجَّارِ ثَامِنُونِي بِحَائِطِكُمْ هَذَا ‏"‏‏.‏ قَالُوا لاَ وَاللَّهِ، لاَ نَطْلُبُ ثَمَنَهُ إِلاَّ إِلَى اللَّهِ‏.‏ فَقَالَ أَنَسٌ فَكَانَ فِيهِ مَا أَقُولُ لَكُمْ، قُبُورُ الْمُشْرِكِينَ، وَفِيهِ خَرِبٌ، وَفِيهِ نَخْلٌ، فَأَمَرَ النَّبِيُّ صلى الله عليه وسلم بِقُبُورِ الْمُشْرِكِينَ فَنُبِشَتْ، ثُمَّ بِالْخَرِبِ فَسُوِّيَتْ، وَبِالنَّخْلِ فَقُطِعَ، فَصَفُّوا النَّخْلَ قِبْلَةَ الْمَسْجِدِ، وَجَعَلُوا عِضَادَتَيْهِ الْحِجَارَةَ، وَجَعَلُوا يَنْقُلُونَ الصَّخْرَ، وَهُمْ يَرْتَجِزُونَ، وَالنَّبِيُّ صلى الله عليه وسلم مَعَهُمْ وَهُوَ يَقُولُ ‏"‏ اللَّهُمَّ لاَ خَيْرَ إِلاَّ خَيْرُ الآخِرَهْ فَاغْفِرْ لِلأَنْصَارِ وَالْمُهَاجِرَهْ ‏"‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>428</td></tr><tr><td>Arabic No</td><td>428</td></tr><tr><td>Reference</td><td>Book 8 Hadith 78</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
আনাস ইবনু মালিক (রাযি.) হতে বর্ণিত। তিনি বলেনঃ নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম মদিনা্য় পৌঁছে প্রথমে মদিনার উচ্চ এলাকায় অবস্থিত বানূ ‘আমর ইবনু ‘আওফ নামক গোত্রে উপনীত হন। তাদের সঙ্গে নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম চৌদ্দ দিন (অপর বর্ণনায় চবিবশ দিন) অবস্থান করেন। অতঃপর তিনি বানূ নাজ্জারকে ডেকে পাঠালেন। তারা কাঁধে তলোয়ার ঝুলিয়ে উপস্থিত হলো। আমি যেন এখনো সে দৃশ্য দেখতে পাচ্ছি যে, নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম ছিলেন তাঁর বাহনের উপর, আবূ বাকর (রাযি.) সে বাহনেই তাঁর পেছনে আর বানূ নাজ্জারের দল তাঁর আশেপাশে। অবশেষে তিনি আবূ আয়্যূব আনসারী (রাযি.)-র ঘরের সাহানে অবতরণ করলেন। নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম যেখানেই সালাতের ওয়াক্ত হয় সেখানেই সালাত আদায় করতে পছন্দ করতেন এবং তিনি ছাগল-ভেড়ার খোঁয়াড়েও সালাত আদায় করতেন। এখন তিনি মাসজিদ তৈরি করার নির্দেশ দেন। তিনি বানূ নাজ্জারকে ডেকে বললেনঃ হে বানূ নাজ্জার! তোমরা আমার কাছ হতে তোমাদের এই বাগিচার মূল্য নির্ধারণ কর। তারা বললোঃ না, আল্লাহর কসম, আমরা এর দাম নেব না। এর দাম আমরা একমাত্র আল্লাহর নিকটই আশা করি। আনাস (রাযি.) বলেনঃ আমি তোমাদের বলছি, এখানে মুশরিকদের কবর এবং ভগ্নাবশেষ ছিল। আর ছিল খেজুর গাছ। নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম -এর নির্দেশে মুশরিকদের কবর খুঁড়ে ফেলা হলো, অতঃপর ভগ্নাবশেষ সমতল করে দেয়া হলো, খেজুর গাছগুলো কেটে ফেলা হলো অতঃপর মসজিদের কিবলায় সারিবদ্ধ করে রাখা হলো এবং তার দুই পাশে পাথর বসানো হলো। সাহাবীগণ পাথর তুলতে তুলতে ছন্দোবদ্ধ কবিতা আবৃত্তি করছিলেন। আর নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম -ও তাঁদের সাথে ছিলেন। তিনি তখন বলছিলেনঃ ‘‘হে আল্লাহ! আখিরাতের কল্যাণ ব্যতীত (প্রকৃত) আর কোন কল্যাণ নেই। তুমি আনসার ও মুহাজিরগণকে ক্ষমা কর।’’ (আধুনিক প্রকাশনীঃ ৪১০, ইসলামিক ফাউন্ডেশনঃ ৪১৬)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>428</td></tr><tr><td>Arabic No</td><td>428</td></tr><tr><td>Reference</td><td>Book 8 Hadith 78</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated Anas:When the Prophet (ﷺ) arrived Medina he dismounted at 'Awali-i-Medina amongst a tribe called Banu 'Amr bin 'Auf. He stayed there For fourteen nights. Then he sent for Bani An-Najjar and they came armed with their swords. As if I am looking (just now) as the Prophet (ﷺ) was sitting over his Rahila (Mount) with Abu Bakr riding behind him and all Banu An-Najjar around him till he dismounted at the courtyard of Abu Aiyub's house. The Prophet (ﷺ) loved to pray wherever the time for the prayer was due even at sheep-folds. Later on he ordered that a mosque should be built and sent for some people of Banu-An-Najjar and said, "O Banu An-Najjar! Suggest to me the price of this (walled) piece of land of yours." They replied, "No! By Allah! We do not demand its price except from Allah." Anas added: There were graves of pagans in it and some of it was unleveled and there were some date-palm trees in it. The Prophet (ﷺ) ordered that the graves of the pagans be dug out and the unleveled land be level led and the date-palm trees be cut down . (So all that was done). They aligned these cut date-palm trees towards the Qibla of the mosque (as a wall) and they also built two stone side-walls (of the mosque). His companions brought the stones while reciting some poetic verses. The Prophet (ﷺ) was with them and he kept on saying, "There is no goodness except that of the Hereafter, O Allah! So please forgive the Ansars and the emigrants
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>428</td></tr><tr><td>Arabic No</td><td>428</td></tr><tr><td>Reference</td><td>Book 8 Hadith 78</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Musaddad] berkata, telah menceritakan kepada kami ['Abdul Warits] dari [Abu At Tayyah] dari [Anas bin Malik] berkata, "Nabi shallallahu 'alaihi wasallam tiba di Madinah lalu singgah di perkampungan bani 'Amru bin 'Auf, Nabi shallallahu 'alaihi wasallam tinggal di sana selama empat belas malam. Kemudian beliau mengutus seseorang menemui bani Najjar, maka mereka pun datang dengan pedang di badan mereka. Aku melihat Nabi shallallahu 'alaihi wasallam di atas tunggangannya sedangkan Abu Bakar membonceng di belakangnya dan para pembesar bani Najjar berada di sekelilingnya hingga sampai di sumur milik Abu Ayyub. Beliau suka segera shalat saat waktu shalat sudah masuk, maka beliau pun shalat di kandang kambing. Kemudian beliau memerintahkan untuk membangun masjid, beliau mengutus seseorang menemui pembesar bani Najjar. utusan itu menyampaikan: "Wahai bani Najjar, sebutkan berapa harga kebun kalian ini?" Mereka menjawab, "Tidak, demi Allah. Kami tidak akan menjualnya kecuali kepada Allah!" Anas berkata, "Aku beritahu kepada kalian bahwa pada kebun itu banyak terdapat kuburan orang-orang musyrik, juga ada sisa-sisa reruntuhan rumah dan pohon-pohon kurma. Maka Nabi shallallahu 'alaihi wasallam memerintahkan untuk membongkar kuburan-kuburan tersebut, reruntuhan rumah diratakan dan pohon-pohon kurma ditumbangkan lalu dipindahkan di depan arah kiblat masjid. Maka lalu membuat pintu masjid dari pohon dan mengangkut batu bata sambil menyanyikan nasyid. Dan Nabi shallallahu 'alaihi wasallam ikut bekerja pula bersama mereka sambil mengucapkan: "Ya Allah. Tidak ada kebaikan kecuali kebaikan akhirat, maka ampunilah kaum Anshar dan Muhajirin
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>428</td></tr><tr><td>Arabic No</td><td>428</td></tr><tr><td>Reference</td><td>Book 8 Hadith 78</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
அனஸ் (ரலி) அவர்கள் கூறியதாவது: நபி (ஸல்) அவர்கள் (புலம்பெயர்ந்து) மதீனாவுக்கு வந்தபோது, மதீனாவின் மேட்டுப்பாங்கான பகுதியில் ‘பனூ அம்ர் பின் அவ்ஃப்’ என்றழைக்கப்பட்டுவந்த ஒரு குடும்பத்தாரிடம் இறங்கி, அவர்களி டையே பதினான்கு நாட்கள் தங்கினார்கள். பிறகு ‘பனூ நஜ்ஜார்’ கூட்டத்தாருக்கு ஆளனுப்பினார்கள். ‘பனூ நஜ்ஜார்’ கூட்டத்தார் (நபியவர்களை வரவேற்கும் முகமாகத் தம்) வாட்களைத் தொங்கவிட்டபடி வந்தனர். அப்போது அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் தமது வாகனத்தில் அமர்ந்திருக்க, அபூபக்ர் (ரலி) அவர்கள் அவர்களுக்குப் பின்னே அமர்ந்திருக்க, ‘பனூ நஜ்ஜார்’ கூட்டத்தார் அவர்களைச் சுற்றிலும் குழுமியிருந்த (அந்தக் காட்சி)தனை (இப்போதும்) நான் காண்பதைப் போன்றுள்ளது. நபி (ஸல்) அவர்களின் ஊர்தி ஒட்டகம் அபூஅய்யூப் (ரலி) அவர்களின் வீட்டு முற்றத்தில் அவர்களை இறக்கியது.- அப்போதெல்லாம் தொழுகை நேரம் தம்மை வந்தடையும் இடத்திலேயே நபி (ஸல்) அவர்கள் தொழுகையை நிறைவேற்று வார்கள்; ஆட்டுத் தொழுவங்களிலும் தொழுவார்கள்- பிறகு நபி (ஸல்) அவர்கள் பள்ளிவாசல் கட்டும்படி பணித்தார்கள். பனூ நஜ்ஜார் கூட்டத்தாருக்கு ஆளனுப்பி னார்கள். (அவர்கள் வந்தபோது), “பனூ நஜ்ஜார் கூட்டத்தாரே! உங்களின் இந்தத் தோட்டத்திற்கு என்னிடம் விலை கூறுங்கள்” என்று கேட்டார்கள். அதற்கு அவர்கள், “இல்லை. அல்லாஹ்வின் மீதாணையாக! இதற்கான விலையை நாங்கள் அல்லாஹ்விடமே கோருவோம்” என்று பதில் (கூறி, அந்தத் தோட்டத்தை) அளித்தனர். நான் உங்களிடம் கூறப்போகின்றவை தான் அ(ந்தத் தோட்டத்)தில் இருந்தன: அதில் இணைவைப்பாளர்களின் சமாதிகள் இருந்தன; அதில் இடிபாடுகள் இருந்தன; சில பேரீச்ச மரங்களும் அதில் இருந்தன. எனவே, (அங்கு பள்ளிவாசல் கட்டுவதற்கு வசதியாக) நபி (ஸல்) அவர்களின் ஆணையின் பேரில் (அங்கிருந்த) இணைவைப்பாளர்களின் சமாதிகள் தோண்டப்பட்டு, இடிபாடுகள் அகற்றப்பட்டு சமப்படுத்தப்பட்டன. பேரீச்ச மரங்கள் வெட்டப்பட்டன. பின்னர் பள்ளிவாச-ன் கிப்லா திசையில் பேரீச்ச மரங்களை வரிசையாக நட்டனர். பள்ளிவாச-ன் (கதவின்) இரு நிலைக் கால்களாகக் கல்லை (நட்டு) வைத்தனர். ‘ரஜ்ஸ்’ எனும் ஈரசைச்சீர் வகைப் பாடலை பாடிக்கொண்டே அந்தக் கல்லை எடுத்துவரலாயினர். “இறைவா! மறுமையின் நன்மையைத் தவிர வேறு நன்மை கிடையாது; ஆகவே, (மறுமையின் நன்மைகளுக்காகப் பாடுபடும்) அன்சாரிகளுக்கும் முஹாஜிர்களுக்கும் நீ மன்னிப்பு அளிப்பாயாக!” என்று நபி (ஸல்) அவர்கள் கூறியவாறு அவர்களுடன் (சேர்ந்து பாறைகளை அப்புறப்படுத்துபவர்களாக) இருந்தார்கள். அத்தியாயம் : 8
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>428</td></tr><tr><td>Arabic No</td><td>428</td></tr><tr><td>Reference</td><td>Book 8 Hadith 78</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Enes İbn Malik'ten şöyle nakledildi: "Hz. Peygamber (Sallallahu aleyhi ve Sellem), Medine'ye geldi. Şehrin yukarı kesimlerinde bulunan ve kendilerine Benu Amr İbn Avf denilen ailenin mahallesinde konakladı. Burada on dört gece kaldı. Sonra Neccaroğulları'na haber saldı. Onlar da kılıçlarını kuşanmış bir vaziyette geldiler. Nebi (Sallallahu aleyhi ve Sellem) bir binek üzerinde, Ebu Bekir ise onun terkinde idi. Neccaroğullarının ileri gelenleri ise, onun etrafındaydı. Bu tablo hala gözümün önündedir. Nihayet Allah Resulü (Sallallahu aleyhi ve Sellem) Ebu Eyyub'un evinin önündeki bahçede durdu. Nerede namaz vakti girerse oracıkta namazını kılmayı severdi. Koyun ağıllarında bile kıldığı olurdu. Nihayet mescidin yapılmasını emretti. Neccaroğulları'nın ileri gelenlerine (gelmeleri için) haber yolladı. (Gelince) onlara 'Şu arsanız ve duvarınızın değerini bana söyleyin' buyurdu. Onlar da, 'Hayır Allah'a yemin ederiz ki bunun bedelini istemiyoruz. Biz, onu Allah için bağışlamak istiyoruz' diye karşılık verdiler." Enes şöyle dedi: "O arsada, şu an size anlattığım gibi, müşriklerin kabirleri, harabeler, duvarlar ve hurma ağaçları vardı. Allah Resulü (Sallallahu aleyhi ve Sellem) müşriklerin kabirlerinin çıkarılıp başka bir yere nakledilmesini emretti. Harabeler düzlendi. Hurma ağaçları ise söküldü. Hurma ağaçlarının gövdeleri, kıble istikametine diziidi. Kapının etrafı taşlarla örüldü. Ashab-ı kiram, recez vezninden beyitler söyleyerek taş taşımaya başladı. Allah Resulü (Sallallahu aleyhi ve Sellem) de, onlarla birlikte çalışıyordu. Bir yandan da şu beyti söylüyordu: Allah'ım! Yoktur hayır ahiret hayrından başka Ensar ve muhacirleri sen bağışla" Allahumme la hayrun illa hayrun ahreti fağfiru’l-Ensari vel Muhacire
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>428</td></tr><tr><td>Arabic No</td><td>428</td></tr><tr><td>Reference</td><td>Book 8 Hadith 78</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ہم سے مسدد نے بیان کیا، انہوں نے کہا ہم سے عبدالوارث نے بیان کیا، انہوں نے ابوالتیاح کے واسطہ سے بیان کیا، انہوں نے انس بن مالک رضی اللہ عنہ سے، انہوں نے کہا کہ جب نبی کریم صلی اللہ علیہ وسلم مدینہ تشریف لائے تو یہاں کے بلند حصہ میں بنی عمرو بن عوف کے یہاں آپ اترے اور یہاں چوبیس راتیں قیام فرمایا۔ پھر آپ صلی اللہ علیہ وسلم نے بنونجار کو بلا بھیجا، تو وہ لوگ تلواریں لٹکائے ہوئے آئے۔ انس نے کہا، گویا میری نظروں کے سامنے نبی کریم صلی اللہ علیہ وسلم اپنی سواری پر تشریف فرما ہیں، جبکہ ابوبکر صدیق رضی اللہ عنہ آپ صلی اللہ علیہ وسلم کے پیچھے بیٹھے ہوئے ہیں اور بنو نجار کے لوگ آپ صلی اللہ علیہ وسلم کے چاروں طرف ہیں۔ یہاں تک کہ آپ صلی اللہ علیہ وسلم ابوایوب کے گھر کے سامنے اترے اور آپ صلی اللہ علیہ وسلم یہ پسند کرتے تھے کہ جہاں بھی نماز کا وقت آ جائے فوراً نماز ادا کر لیں۔ آپ بکریوں کے باڑوں میں بھی نماز پڑھ لیتے تھے، پھر آپ نے یہاں مسجد بنانے کے لیے حکم فرمایا۔ چنانچہ بنو نجار کے لوگوں کو آپ صلی اللہ علیہ وسلم نے بلوا کر فرمایا کہ اے بنو نجار! تم اپنے اس باغ کی قیمت مجھ سے لے لو۔ انہوں نے جواب دیا نہیں یا رسول اللہ! اس کی قیمت ہم صرف اللہ سے مانگتے ہیں۔ انس رضی اللہ عنہ نے بیان کیا کہ میں جیسا کہ تمہیں بتا رہا تھا یہاں مشرکین کی قبریں تھیں، اس باغ میں ایک ویران جگہ تھی اور کچھ کھجور کے درخت بھی تھے پس نبی کریم صلی اللہ علیہ وسلم نے مشرکین کی قبروں کو اکھڑوا دیا ویرانہ کو صاف اور برابر کرایا اور درختوں کو کٹوا کر ان کی لکڑیوں کو مسجد کے قبلہ کی جانب بچھا دیا اور پتھروں کے ذریعہ انہیں مضبوط بنا دیا۔ صحابہ پتھر اٹھاتے ہوئے رجز پڑھتے تھے اور نبی کریم صلی اللہ علیہ وسلم بھی ان کے ساتھ تھے اور یہ کہہ رہے تھے کہ اے اللہ! آخرت کے فائدہ کے علاوہ اور کوئی فائدہ نہیں پس انصار و مہاجرین کی مغفرت فرمانا۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>428</td></tr><tr><td>Arabic No</td><td>428</td></tr><tr><td>Reference</td><td>Book 8 Hadith 78</td></tr></tbody></table></div>