## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا مَحْمُودٌ، حَدَّثَنَا أَبُو أُسَامَةَ، حَدَّثَنَا هِشَامٌ، قَالَ أَخْبَرَنِي أَبِي، عَنْ أَسْمَاءَ بِنْتِ أَبِي بَكْرٍ ـ رضى الله عنهما ـ قَالَتْ تَزَوَّجَنِي الزُّبَيْرُ، وَمَا لَهُ فِي الأَرْضِ مِنْ مَالٍ، وَلاَ مَمْلُوكٍ، وَلاَ شَىْءٍ غَيْرَ نَاضِحٍ، وَغَيْرَ فَرَسِهِ، فَكُنْتُ أَعْلِفُ فَرَسَهُ، وَأَسْتَقِي الْمَاءَ، وَأَخْرِزُ غَرْبَهُ وَأَعْجِنُ، وَلَمْ أَكُنْ أُحْسِنُ أَخْبِزُ، وَكَانَ يَخْبِزُ جَارَاتٌ لِي مِنَ الأَنْصَارِ وَكُنَّ نِسْوَةَ صِدْقٍ، وَكُنْتُ أَنْقُلُ النَّوَى مِنْ أَرْضِ الزُّبَيْرِ الَّتِي أَقْطَعَهُ رَسُولُ اللَّهِ صلى الله عليه وسلم عَلَى رَأْسِي، وَهْىَ مِنِّي عَلَى ثُلُثَىْ فَرْسَخٍ، فَجِئْتُ يَوْمًا وَالنَّوَى عَلَى رَأْسِي فَلَقِيتُ رَسُولَ اللَّهِ صلى الله عليه وسلم وَمَعَهُ نَفَرٌ مِنَ الأَنْصَارِ فَدَعَانِي ثُمَّ قَالَ ‏ "‏ إِخْ إِخْ ‏"‏‏.‏ لِيَحْمِلَنِي خَلْفَهُ، فَاسْتَحْيَيْتُ أَنْ أَسِيرَ مَعَ الرِّجَالِ، وَذَكَرْتُ الزُّبَيْرَ وَغَيْرَتَهُ، وَكَانَ أَغْيَرَ النَّاسِ، فَعَرَفَ رَسُولُ اللَّهِ صلى الله عليه وسلم أَنِّي قَدِ اسْتَحْيَيْتُ فَمَضَى، فَجِئْتُ الزُّبَيْرَ فَقُلْتُ لَقِيَنِي رَسُولُ اللَّهِ صلى الله عليه وسلم وَعَلَى رَأْسِي النَّوَى، وَمَعَهُ نَفَرٌ مِنْ أَصْحَابِهِ، فَأَنَاخَ لأَرْكَبَ، فَاسْتَحْيَيْتُ مِنْهُ وَعَرَفْتُ غَيْرَتَكَ‏.‏ فَقَالَ وَاللَّهِ لَحَمْلُكِ النَّوَى كَانَ أَشَدَّ عَلَىَّ مِنْ رُكُوبِكِ مَعَهُ‏.‏ قَالَتْ حَتَّى أَرْسَلَ إِلَىَّ أَبُو بَكْرٍ بَعْدَ ذَلِكَ بِخَادِمٍ يَكْفِينِي سِيَاسَةَ الْفَرَسِ، فَكَأَنَّمَا أَعْتَقَنِي‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5224</td></tr><tr><td>Arabic No</td><td>5224</td></tr><tr><td>Reference</td><td>Book 67 Hadith 157</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
আসমা বিনতে আবূ বাকর (রাঃ) হতে বর্ণিত। তিনি বলেন, যখন যুবায়র (রাঃ) আমাকে বিয়ে করলেন, তখন তার কাছে কোন ধন-সম্পদ ছিল না, এমন কি কোন স্থাবর জমি-জমা, দাস-দাসীও ছিল না; শুধুমাত্র কুয়ো থেকে পানি উত্তোলনকারী একটি উট ও একটি ঘোড়া ছিল। আমি তাঁর উট ও ঘোড়া চরাতাম, পানি পান করাতাম এবং পানি উত্তোলনকারী মশক ছিঁড়ে গেলে সেলাই করতাম, আটা পিষতাম; কিন্তু ভালো রুটি তৈরি করতে পারতাম না। তাই আনসারী প্রতিবেশী মহিলারা আমার রুটি তৈরিতে সাহায্য করত। আর তারা ছিল খুবই উত্তম নারী। রাসূল সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম যুবায়র (রাঃ)-কে একখন্ড জমি দিয়েছিলেন। আমি সেখান থেকে মাথায় করে খেজুরের আঁটির বোঝা বহন করে আনতাম। ঐ জমির দূরত্ব ছিল প্রায় দু’মাইল। একদিন আমি মাথায় করে খেজুরের আঁটি বহন করে নিয়ে আসছিলাম। এমন সময় রাসূলুল্লাহ্ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর সাক্ষাৎ হল, তখন রাসূল সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর সঙ্গে কয়েকজন আনসারও ছিল। নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম আমাকে ডাকলেন এবং আমাকে তাঁর উটের পিঠে বসার জন্য তাঁর উটকে আখ্! আখ্! বললেন, যাতে উটটি বসে এবং আমি তাঁর পিঠে আরোহণ করতে পারি। আমি পরপুরুষের সঙ্গে একত্রে যাওয়ার ব্যাপারে লজ্জাবোধ করতে লাগলাম এবং যুবায়র (রাঃ)-এর আত্মসম্মানবোধের কথা আমার মনে পড়ল। কেননা, সে ছিল খুব আত্মমর্যাদাসম্পন্ন ব্যক্তি। রাসূলুল্লাহ্ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বুঝতে পারলেন, আমি খুব লজ্জাবোধ করছি। সুতরাং তিনি এগিয়ে চললেন। আমি যুবায়র (রাঃ)-এর কাছে পৌঁছলাম এবং বললাম, আমি খেজুরের আঁটির বোঝা মাথায় নিয়ে আসার সময় পথিমধ্যে রাসূল সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর সঙ্গে আমার দেখা হয় এবং তাঁর সঙ্গে কিছু সংখ্যক সাহাবী ছিলেন। তিনি তাঁর উটকে হাঁটু গেড়ে বসালেন, যেন আমি তাতে সওয়ার হতে পারি। কিন্তু আমি তোমার আত্মসম্মানের কথা চিন্তা করে লজ্জা অনুভব করলাম। এ কথা শুনে যুবায়র (রাঃ) বললেন, আল্লাহর কসম! খেজুরের আঁটির বোঝা মাথায় বহন করা তাঁর সঙ্গে উটে চড়ার চেয়ে আমার কাছে অধিক লজ্জাজনক। এরপর আবূ বাকর সিদ্দীক (রাঃ) ঘোড়ার দেখাশুনার জন্য আমার সাহায্যের নিমিত্ত একজন খাদিম পাঠিয়ে দিলেন। এরপরই আমি যেন মুক্ত হলাম। [৩১৫১; মুসলিম ৩৯/১৪, হাঃ ২১৮২, আহমাদ ২৭০০৩] (আধুনিক প্রকাশনী- ৪৮৪১, ইসলামিক ফাউন্ডেশন- ৪৮৪৪)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5224</td></tr><tr><td>Arabic No</td><td>5224</td></tr><tr><td>Reference</td><td>Book 67 Hadith 157</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated Asma' bint Abu Bakr:When Az-Zubair married me, he had no real property or any slave or anything else except a camel which drew water from the well, and his horse. I used to feed his horse with fodder and drew water and sew the bucket for drawing it, and prepare the dough, but I did not know how to bake bread. So our Ansari neighbors used to bake bread for me, and they were honorable ladies. I used to carry the date stones on my head from Zubair's land given to him by Allah's Messenger (ﷺ) and this land was two third Farsakh (about two miles) from my house. One day, while I was coming with the date stones on my head, I met Allah's Messenger (ﷺ) along with some Ansari people. He called me and then, (directing his camel to kneel down) said, "Ikh! Ikh!" so as to make me ride behind him (on his camel). I felt shy to travel with the men and remembered Az-Zubair and his sense of Ghira, as he was one of those people who had the greatest sense of Ghira. Allah's Messenger (ﷺ) noticed that I felt shy, so he proceeded. I came to Az-Zubair and said, "I met Allah's Messenger (ﷺ) while I was carrying a load of date stones on my head, and he had some companions with him. He made his camel kneel down so that I might ride, but I felt shy in his presence and remembered your sense of Ghira (See the glossary). On that Az-Zubair said, "By Allah, your carrying the date stones (and you being seen by the Prophet (ﷺ) in such a state) is more shameful to me than your riding with him." (I continued serving in this way) till Abu Bakr sent me a servant to look after the horse, whereupon I felt as if he had set me free
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5224</td></tr><tr><td>Arabic No</td><td>5224</td></tr><tr><td>Reference</td><td>Book 67 Hadith 157</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Mahmud] Telah menceritakan kepada kami [Abu Usamah] Telah menceritakan kepada kami [Hisyam] ia berkata; Telah mengabarkan kepadaku [bapakku] dari [Asma' binti Abu Bakar radliallahu 'anhuma] ia berkata; Az Zubair bin Awwam menikahiku. Saat itu, ia tidak memiliki harta dan tidak juga memiliki budak serta tidak memiliki apa-apa kecuali alat penyiram lahan dan seekor kuda. Maka akulah yang memberi makan dan minum kudanya, menjahit timbanya serta membuatkan adonan roti. Padahal aku bukanlah seorang yang pandai membuat roti. Karena itu, para tetanggaku dari kaum Anshar-lah yang membuatkan roti. Aku memindahkan biji kurma dari kebun Az Zubair yang telah ditetapkan oleh Rasulullah shallallahu 'alaihi wasallam di atas kepalaku. Tanah itu dariku atas duapertiga Farsakh. Suatu hari aku datang sementara biji kurma ada di atas kepalaku. Lalu aku berjumpa dengan Rasulullah shallallahu 'alaihi wasallam yang sedang bersama beberapa orang dari kaum Anshar. Beliau kemudian memanggilku dan bersabda: "Hei, hei, rupanya beliau berhasrat untuk menaikkanku diatas kendaraan di belakangnya. Namun, aku malu untuk berjalan bersama para lelaki dan aku ingat akan kecemburuan Az Zubair, ia adalah orang yang paling pencemburu. Maka Rasulullah shallallahu 'alaihi wasallam pun tahu bahwa aku malu, hingga beliau pun berlalu. Setelah itu, aku pun menemui Az Zubair dan berkata, "Rasulullah shallallahu 'alaihi wasallam menemuiku sementara di atas kepalaku ada biji kurma. Sedangkan beliau sedang bersama beberapa orang dari kalangan Anshar, lalu beliau mempersilahkan agar aku naik kendaraan, namun aku malu dan juga tahu akan kecemburuanmu." Maka Az Zubair pun berkata, "Demi Allah, kamu membawa biji kurma itu adalah lebih besar bagiku daripada engkau naik kendaraan bersama beliau." Akhirnya Abu Bakar pun mengutuskan seorang khadim yang dapat mencukupi pekerjaanku untuk mengurusi kuda. Dan seolah-olah ia telah membebaskanku
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5224</td></tr><tr><td>Arabic No</td><td>5224</td></tr><tr><td>Reference</td><td>Book 67 Hadith 157</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
அஸ்மா பின்த் அபீபக்ர் (ரலி) அவர்கள் கூறியதாவது: என்னை ஸுபைர் பின் அல்அவ்வாம் (ரலி) அவர்கள் (மக்காவிலிருக்கும்போதே) மணந்துகொண்டார்கள். இந்தப் பூமியில் அவருக்குத் தண்ணீர் இறைக்கும் ஓர் ஒட்டகத்தையும் அவரது குதிரையையும் தவிர வேறு எந்தச் சொத்துபத்துகளும் அடிமைகளும் உடைமைகளும் இருக்க வில்லை. அந்தக் குதிரைக்கு நான் தீனிபோடுவேன்; தண்ணீர் இறைப்பேன்; அவரது தோல் கமலையைத் தைப்பேன்; மாவு குழைப்பேன். ஆனால், எனக்கு நன்றாக ரொட்டிசுடத் தெரியாது. என் அண்டைவீட்டு அன்சாரிப் பெண்களே எனக்கு ரொட்டிசுட்டுத் தருவார்கள். அந்தப் பெண்கள் உண்மையாளர்களாயிருந்தனர். அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் என் கணவருக்கு வருவாய் மானியமாய்த் தந்த நிலத்திலிருந்து நானே பேரீச்சங் கொட்டைகளை(ப் பொறுக்கி) என் தலைமீது வைத்துச் சுமந்து வருவேன். அந்த நிலம் இங்கிருந்து இரண்டு மைல் தொலைவில் இருந்தது.152 (ஒருநாள்) நான் என் தலைமீது பேரீச்சங் கொட்டைகளை வைத்து வந்து கொண்டிருந்தேன். (வழியில்) நான், அல்லாஹ்வின் தூதர் (ஸல்) அவர்களை, (அவர்தம் தோழர்களான) அன்சாரிகளில் சிலர் அவர்களுடன் இருக்கச் சந்தித்தேன். அப்போது அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் என்னை அழைத்தார்கள். என்னைத் தமக்குப் பின்னால் அமர்த்திக் கொள்வதற்காக ‘‘இஃக், இஃக்” என்று சொல்லித் தமது ஒட்டகத்தை மண்டியிட வைத்தார்கள். (ஆனால்,) நான் ஆண்களுடன் செல்ல வெட்கப்பட்டேன். மேலும், நான் (என் கணவர்) ஸுபைர் (ரலி) அவர்களையும், அவரது ரோஷத்தையும் நினைத்துப் பார்த் தேன். அவர் மக்களில் மிகவும் ரோஷக் காரராக இருந்தார். நான் வெட்கப்படு வதைப் புரிந்துகொண்ட அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் சென்று விட்டார்கள். நான் (என் கணவர்) ஸுபைரிடம் வந்து ‘‘(வழியில்) அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் என் தலையில் பேரீச்சங்கொட்டைகளிருக்க என்னைச் சந்தித்தார்கள். அவர்களுடன் அவர்களுடைய தோழர்கள் சிலரும் இருந்தனர். நான் ஏறிக்கொள்வதற்காக(த் தமது ஒட்டகத்தை) மண்டியிடச் செய்தார்கள். நான் அவர்களைக் கண்டு வெட்கப்பட்டேன். மேலும், உங்களின் ரோஷத்தை நான் அறிந்துள்ளேன்” என்று கூறினேன். அதற்கு என் கணவர், ‘‘அல்லாஹ்வின் மீதாணையாக! நபி (ஸல்) அவர்களுடன் நீ வாகனத்தில் வருவதைவிட பேரீச்சங்கொட்டைகளை நீ சுமந்து வந்ததுதான் எனக்குக் கடினமானதாக இருக்கிறது” என்று கூறினார். (இவ்வாறாக வீட்டுப் பணிகளில் பெரும் பகுதியை நானே மேற்கொண்டு வந்தேன்.) அதற்குப் பிறகு (என் தந்தை) அபூபக்ர் (ரலி) அவர்கள் எனக்கு ஓர் அடிமையை (உதவிக்காக) அனுப்பி வைத்தார்கள். அந்த அடிமை குதிரையைப் பராமரிக்கும் பொறுப்பை ஏற்றுக்கொண்டார். என்னவோ எனக்கு விடுதலை கிடைத்ததுபோல் இருந்தது. அத்தியாயம் : 67
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5224</td></tr><tr><td>Arabic No</td><td>5224</td></tr><tr><td>Reference</td><td>Book 67 Hadith 157</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ebu Bekr'in kızı Esma R.A.a'dan, dedi ki: "ez-Zubeyr benimle evlendiğinde yeryüzünde mal namına, köle namına hiçbir şeyi yoktu. Su çeken bir devesi ile atı dışında hiçbir şeye sahip değildi. Bundan dolayı atının yemini ben koyar, suyu ben çekerdim. Su kovasını ben onarıp dikerdim, hamuru ben yoğururdum. Ancak güzel ekmek pişiremezdim. Ensardan bazı hanım komşularım benim ekmeğimi pişirirdi. Bunlar oldukça sadakatli kadınlardı. Rasulullah Sallallahu Aleyhi ve Sellem'in ez-Zubeyr'e ikta' olarak verdiği araziden hurma çekirdeğini başımın üzerinde taşırdım. Bu arazi evimden üçte iki fersahlık mesafede idi. Bir gün hurma çekirdekleri başımın üzerinde olduğu halde geliyordum. Rasulullah Sallallahu Aleyhi ve Sellem ile karşılaştım. Beraberinde ensardan da birkaç kişi vardı. Beni çağırdı. Sonra da beni arkasına, terkisine bindirmek için (devesini çöktürmek amacıyla) "ıh ıh" dedi. Ancak ben erkeklerle beraber yürümekten utandım. Ayrıca ez-Zubeyr'i ve onun kıskançlığını da hatırladım. -ez-Zubeyr insanların en kıskancı idi- Rasulullah Sallallahu Aleyhi ve Sellem benim utandığımı anladığından yoluna devam etti. Zübeyr'e gelerek: Rasulullah Sallallahu Aleyhi ve Sellem beni gördü. Hurma çekirdeklerini başımın üzerine koymuş taşıyordum. Beraberinde de ashabından birkaç kişi vardı. Arkasına bineyim diye devesini çöktürdü, ben de ondan utandım ve senin kıskançlığını da hatırladım, dedim. Zübeyr bana şu cevabı verdi: Allah'a yemin ederim, senin hurma çekirdeklerini taşıman, onunla beraber binmenden bana daha ağır gelir. Esma dedi ki: (Bu halim) sonunda Ebu Bekr bana atın bakımını üstlenen bir hizmetçi gönderinceye kadar sürdü. Onu göndermekle sanki beni kölelikten kurtarmış oldu
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5224</td></tr><tr><td>Arabic No</td><td>5224</td></tr><tr><td>Reference</td><td>Book 67 Hadith 157</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ہم سے محمود بن غیلان نے بیان کیا، کہا ہم سے ابواسامہ نے بیان کیا، کہا ہم سے ہشام بن عروہ نے بیان کیا، کہا کہ مجھے میرے والد نے خبر دی اور ان سے اسماء بنت ابی بکر رضی اللہ عنہما نے بیان کیا کہ زبیر رضی اللہ عنہ نے مجھ سے شادی کی تو ان کے پاس ایک اونٹ اور ان کے گھوڑے کے سوا روئے زمین پر کوئی مال، کوئی غلام، کوئی چیز نہیں تھی۔ میں ہی ان کا گھوڑا چراتی، پانی پلاتی، ان کا ڈول سیتی اور آٹا گوندھتی۔ میں اچھی طرح روٹی نہیں پکا سکتی تھی۔ انصار کی کچھ لڑکیاں میری روٹی پکا جاتی تھیں۔ یہ بڑی سچی اور باوفا عورتیں تھیں۔ زبیر رضی اللہ عنہ کی وہ زمین جو رسول اللہ صلی اللہ علیہ وسلم نے انہیں دی تھی، اس سے میں اپنے سر پر کھجور کی گٹھلیاں گھر لایا کرتی تھی۔ یہ زمین میرے گھر سے دو میل دور تھی۔ ایک روز میں آ رہی تھی اور گٹھلیاں میرے سر پر تھیں کہ راستے میں رسول اللہ صلی اللہ علیہ وسلم سے ملاقات ہو گئی۔ نبی کریم صلی اللہ علیہ وسلم کے ساتھ قبیلہ انصار کے کئی آدمی تھے۔ نبی کریم صلی اللہ علیہ وسلم نے مجھے بلایا پھر ( اپنے اونٹ کو بٹھانے کے لیے ) کہا اخ اخ۔ نبی کریم صلی اللہ علیہ وسلم چاہتے تھے کہ مجھے اپنی سواری پر اپنے پیچھے سوار کر لیں لیکن مجھے مردوں کے ساتھ چلنے میں شرم آئی اور زبیر رضی اللہ عنہ کی غیرت کا بھی خیال آیا۔ زبیر رضی اللہ عنہ بڑے ہی باغیرت تھے۔ نبی کریم صلی اللہ علیہ وسلم بھی سمجھ گئے کہ میں شرم محسوس کر رہی ہوں۔ اس لیے آپ آگے بڑھ گئے۔ پھر میں زبیر رضی اللہ عنہ کے پاس آئی اور ان سے واقعہ کا ذکر کیا کہ نبی کریم صلی اللہ علیہ وسلم سے میری ملاقات ہو گئی تھی۔ میرے سر پر گٹھلیاں تھیں اور نبی کریم صلی اللہ علیہ وسلم کے ساتھ آپ کے چند صحابہ بھی تھے۔ نبی کریم صلی اللہ علیہ وسلم نے اپنا اونٹ مجھے بٹھانے کے لیے بٹھایا لیکن مجھے اس سے شرم آئی اور تمہاری غیرت کا بھی خیال آیا۔ اس پر زبیر نے کہا کہ اللہ کی قسم! مجھ کو تو اس سے بڑا رنج ہوا کہ تو گٹھلیاں لانے کے لیے نکلے اگر تو نبی کریم صلی اللہ علیہ وسلم کے ساتھ سوار ہو جاتی تو اتنی غیرت کی بات نہ تھی ( کیونکہ اسماء رضی اللہ عنہا آپ کی سالی اور بھاوج دونوں ہوتی تھیں ) اس کے بعد میرے والد ابوبکر رضی اللہ عنہ نے ایک غلام میرے پاس بھیج دیا وہ گھوڑے کا سب کام کرنے لگا اور میں بےفکر ہو گئی گویا والد ماجد ابوبکر رضی اللہ عنہ نے ( غلام بھیج کر ) مجھ کو آزاد کر دیا۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5224</td></tr><tr><td>Arabic No</td><td>5224</td></tr><tr><td>Reference</td><td>Book 67 Hadith 157</td></tr></tbody></table></div>