## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا قُتَيْبَةُ، حَدَّثَنَا اللَّيْثُ، عَنْ نَافِعٍ، أَنَّ ابْنَ عُمَرَ بْنِ الْخَطَّابِ ـ رضى الله عنهما ـ طَلَّقَ امْرَأَةً لَهُ وَهْىَ حَائِضٌ تَطْلِيقَةً وَاحِدَةً، فَأَمَرَهُ رَسُولُ اللَّهِ صلى الله عليه وسلم أَنْ يُرَاجِعَهَا، ثُمَّ يُمْسِكَهَا حَتَّى تَطْهُرَ، ثُمَّ تَحِيضَ عِنْدَهُ حَيْضَةً أُخْرَى، ثُمَّ يُمْهِلَهَا حَتَّى تَطْهُرَ مِنْ حَيْضِهَا، فَإِنْ أَرَادَ أَنْ يُطَلِّقَهَا فَلْيُطَلِّقْهَا حِينَ تَطْهُرُ مِنْ قَبْلِ أَنْ يُجَامِعَهَا، فَتِلْكَ الْعِدَّةُ الَّتِي أَمَرَ اللَّهُ أَنْ تُطَلَّقَ لَهَا النِّسَاءُ‏.‏ وَكَانَ عَبْدُ اللَّهِ إِذَا سُئِلَ عَنْ ذَلِكَ قَالَ لأَحَدِهِمْ إِنْ كُنْتَ طَلَّقْتَهَا ثَلاَثًا فَقَدْ حَرُمَتْ عَلَيْكَ، حَتَّى تَنْكِحَ زَوْجًا غَيْرَهُ‏.‏ وَزَادَ فِيهِ غَيْرُهُ عَنِ اللَّيْثِ حَدَّثَنِي نَافِعٌ قَالَ ابْنُ عُمَرَ لَوْ طَلَّقْتَ مَرَّةً أَوْ مَرَّتَيْنِ، فَإِنَّ النَّبِيَّ صلى الله عليه وسلم أَمَرَنِي بِهَذَا‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5332</td></tr><tr><td>Arabic No</td><td>5332</td></tr><tr><td>Reference</td><td>Book 68 Hadith 77</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
নাফি‘ (রহ.) হতে বর্ণিত যে, ইবনু ‘উমার (রাঃ) তাঁর স্ত্রীকে ঋতুমতী অবস্থায় এক তালাক দেন। রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম তাকে আদেশ দিলেন, তিনি যেন তার স্ত্রীকে ফিরিয়ে আনেন এবং মহিলা পবিত্র হয়ে আবার ঋতুমতী হয়ে পরবর্তী পবিত্রা অবস্থা আসা পর্যন্ত তাকে নিজের কাছে রাখেন। পবিত্র অবস্থায় যদি তাকে তালাক দিতে চায় তবে সঙ্গমের পূর্বে তালাক দিতে হবে। এটাই ইদ্দাত, যে সময় স্ত্রীদেরকে তালাক দেয়ার জন্য আল্লাহ আদেশ দিয়েছেন। ‘আবদুল্লাহকে এ সম্পর্কে জিজ্ঞেস করা হলে তিনি তাদের বলেনঃ তুমি যদি তাকে তিন তালাক দিয়ে দাও, তবে স্ত্রীলোকটি অন্য স্বামী গ্রহণ না করা পর্যন্ত তোমার জন্য হারাম হয়ে যাবে। অন্য বর্ণনায় ইবন ‘উমার (রাঃ) বলতেন, ‘তুমি যদি এক বা দু’ তালাক দিতে’, কারণ নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম আমাকে এরকমই নির্দেশ দিয়েছেন। [৪৯০৮] (আধুনিক প্রকাশনী- ৪৯৩৭, ইসলামিক ফাউন্ডেশন- ৪৮৩৩)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5332</td></tr><tr><td>Arabic No</td><td>5332</td></tr><tr><td>Reference</td><td>Book 68 Hadith 77</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated Nafi':Ibn 'Umar bin Al-Khattab divorced his wife during her menses. Allah's Messenger (ﷺ) ordered him to take her back till she became clean, and when she got another period while she was with him, she should wait till she became clean again and only then, if he wanted to divorce her, he could do so before having sexual relations with her. And that is the period Allah has fixed for divorcing women. Whenever 'Abdullah (bin 'Umar) was asked about that, he would say to the questioner, "If you divorced her thrice, she is no longer lawful for you unless she marries another man (and the other man divorces her in his turn).' Ibn 'Umar further said, 'Would that you (people) only give one or two divorces, because the Prophet (ﷺ) has ordered me so
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5332</td></tr><tr><td>Arabic No</td><td>5332</td></tr><tr><td>Reference</td><td>Book 68 Hadith 77</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Qutaibah] Telah menceritakan kepada kami [Al Laits] dari [Nafi'] bahwa [Ibnu Umar bin Al Khaththab] radliallahu 'anhuma menceraikan isterinya dalam keadaan haidl dengan talak satu. Kemudian Rasulullah shallallahu 'alaihi wasallam memerintahkan agar ia meruju'nya kembali lalu menahannya hingga ia suci, kemudian haid lagi dan menunggunya hingga ia suci kembali dari haidlnya. Maka bila ia mau menceraikannya, maka hendaklah ia menceraikannya saat dalam keadaan suci dan sebelum menjima'nya. Itulah Al 'Iddah yang diperintahkan Allah, agar para wanita diceraikan pada masa itu. Dan apabila Abdullah ditanya tentang hal itu, maka ia kan berkata kepada salah seorang dari mereka, "Jika kamu menceraikannya dengan talak tiga, maka sungguh wanita itu telah diharamkan atasmu hingga ia menikah dengan laki-laki lain selainmu." Dan selainnya menambahkan; Dari Al Laits Telah menceritakan kepadaku Nafi' Telah berkata Ibnu Umar; "Bila kamu menceraikan dengan sekali atau dua kali talak, maka Nabi shallallahu 'alaihi wasallam telah memerintahkanku seperti itu
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5332</td></tr><tr><td>Arabic No</td><td>5332</td></tr><tr><td>Reference</td><td>Book 68 Hadith 77</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
நாஃபிஉ (ரஹ்) அவர்கள் கூறியதாவது: இப்னு உமர் (ரலி) அவர்கள் தம் மனைவியை, அவர் மாதவிடாயிலிருந்த சமயத்தில் ஒரு தலாக் சொல்லிவிட்டார்கள். அப்போது அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் இப்னு உமர் (ரலி) அவர்களுக்கு(ப் பின்வருமாறு) கட்டளை யிட்டார்கள்: அவர் தம் மனைவியைத் திருப்பி அழைத்துக்கொள்ள வேண்டும். பிறகு மனைவி மாதவிடாயிலிருந்து தூய்மையாகும்வரை தம்மிடமே வைத்துக்கொள்ள வேண்டும். பிறகு தம்மிடம் இருக்கும் அவளுக்கு இரண்டாம் முறை மாதவிடாய் ஏற்பட்டு, அதன் பிறகு அந்த மாதவிடாயிலிருந்து அவள் தூய்மையடையும்வரை காத்திருந்துவிட்டு, அவர் அவளை தலாக் சொல்ல விரும்பினால் அவளுடன் உடலுறவு கொள்வதற்கு முன்னால் அவள் (மாதவிடாய் காலத்தில் இல்லாமல்) தூய்மையானவளாய் இருக்கும்போது தலாக் சொல்லிக் கொள்ளட்டும்! இதுவே, பெண்களை மணவிலக்குச் செய்ய அல்லாஹ் உத்தரவிட்டுள்ள காலமாகும். இப்னு உமர் (ரலி) அவர்களிடம் இது குறித்து வினவப்பட்டால், ‘‘உன் மனைவியை நீ மூன்று முறை தலாக் சொல்லிவிட்டால் வேறொரு கணவரை அவள் மணந்து (உடலுறவு) கொள்ளும்வரை அவள் உனக்கு விலக்கப்பட்டவளாக ஆகிவிடுவாள்” என்று பதிலளிப்பார்கள். மற்றோர் அறிவிப்பில் கூடுதலாகக் காணப்படுவதாவது: இப்னு உமர் (ரலி) அவர்கள் ‘‘நீ ஒரு முறை, அல்லது இரு முறை தலாக் சொல்லியிருந்தால் (அவளைத் திருப்பி அழைத்துக்கொள்ளலாம்). இவ்வாறு (திருப்பி அழைத்துக்கொள்ளுமாறு)தான் நபி (ஸல்) அவர்கள் எனக்குக் கட்டளை யிட்டார்கள்” என்று கூறுவார்கள்.90 அத்தியாயம் : 68
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5332</td></tr><tr><td>Arabic No</td><td>5332</td></tr><tr><td>Reference</td><td>Book 68 Hadith 77</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Nafi'den rivayete göre; "Ömer İbn el-Hattab'ın oğlu r.a. altındaki bir hanımı ay hali iken bir talak ile boşadı. Rasulullah Sallallahu Aleyhi ve Sellem ona karısına dönmesini, sonra da temizleninceye kadar nikahı altında tutmasını, sonra onun yanında iken bir daha ay hali oluncaya kadar bekletmesini, daha sonra da o ay halinden temizleninceye kadar ona mühlet vermesini emir buyurdu. Eğer onu boşamak isterse onunla dma' etmeden önce temizleneceği zaman onu boşasın. İşte şanı yüce Allah'ın kadınların boşanmasını emir buyurduğu iddet budur. Abdullah'a bu husus sorulduğuvakit, soranlardan birisine şu cevabı verirdi: Şayet sen karını üç talak ile boşamış isen senden başka bir koca ile nikahlanmadıkça sana haram olur. Bu hadiste ondan (ravilerden olan Kuteybe'den) başkası el-leys'ten şu fazlalığı da zikretmiştir: Bana Nafi tahdis etti, İbn Ömer dedi ki: "Eğer bir ya da iki defa talak vermişsen (karına dönebilirsin). Çünkü Nebi Sallallahu Aleyhi ve Sellem bana bu şekilde hareket etmemi emir buyurmuştur." Fethu'l-Bari Açıklaması: İddet içerisinde "kocaları onları geri almaya daha çok hak sahibidirler" buyruğu. Hadiste geçen "Allah'ın emrine boyun eğdi" ifadesi, Allah'a itaat etti ve emrin gereğini yerine getirdi anlamındadır. İlim adamlarının icma'ına göre hür bir kimse zifafa girdikten sonra hür karısını bir ya da iki talak ile boşadığı takdirde, -kadın bundan hoşlanmazsa dahi- onu ric'at ile geri almaya daha bir hak sahibidir. Eğer iddet bitinceye kadar karısına dönmeyecek olursa onun için yabancı bir kadın olur. Yeni bir nikah yapılmadıkça ona tekrar hela! olmaz. Selef erkeğin ne yaptığı takdirde ric'at (hanımına talaktan vazgeçipdönmüş) olacağı hususunda görüş ayrılığı içerisindedir. el-Evzaı: Karısı ile cima' edecek olursa ona ric'at yapmış olur, demektedir. Bu görüş aynı şekilde tabiinden bazılarından da rivayet edilmiştir. Malik ve İshak da bununla ric'ati niyet etmek şartı ile böyle demişlerdir. Kufeli ilim adamları da el-Evzaı gibi demiş ve şunu eklemişlerdir: Şehvetle . ona dokunsa yahut şehvetle fercine baksa da ric'at yapmış olur. Şafii de: Ric'at, ancak söz ile olur, demiştir. Cinsel ilişki kurmanın caiz ya da haram olduğu, bu husustaki görüş ayrılıklarına dayanır. Şafii'nin delili şudur: Talak nikahı ortadan kaldırır. Bunun ilk olarak açıkça etkilediği husus ise cinsel ilişkinin helalolup olmamasıdır. Çünkü helal oluş, nikahta söz konusu olması caiz olan bir anlamdır. Müşriklerden birisinin Müslüman olması, daha sonra ise iddet içerisinde diğerinin Müslüman olması halinde olduğu gibi. Aynı şekilde oruç, ihram ve ay hali gibi hallerde söz konusu olamayacağı da bu türdendir. Ama daha sonra bu hususların ortadan kalkması ile dma' tekrar helal olur. Caiz olduğunu söyleyenler de nikahın zeval bulması halinde kadının ancak yenibir akit ile tekrar alınabileceğini, ric'l talak ile boşanmış bir kadın ile hul' yapmanın sahih olacağını ve (birinciden sonra) ikinci talakın da vuku bulacağını delil göstermişlerdir
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5332</td></tr><tr><td>Arabic No</td><td>5332</td></tr><tr><td>Reference</td><td>Book 68 Hadith 77</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ہم سے قتیبہ نے بیان کیا، کہا ہم سے لیث بن سعد نے بیان کیا، ان سے نافع نے اور ان سے ابن عمر بن خطاب رضی اللہ عنہما نے کہ انہوں نے اپنی بیوی کو ایک طلاق دی تو اس وقت وہ حائضہ تھیں۔ رسول اللہ صلی اللہ علیہ وسلم نے ان کو حکم دیا کہ رجعت کر لیں اور انہیں اس وقت تک اپنے ساتھ رکھیں جب تک وہ اس حیض سے پاک ہونے کے بعد پھر دوبارہ حائضہ نہ ہوں۔ اس وقت بھی ان سے کوئی تعرض نہ کریں اور جب وہ اس حیض سے بھی پاک ہو جائیں تو اگر اس وقت انہیں طلاق دینے کا ارادہ ہو تو طہر میں اس سے پہلے کہ ان سے ہمبستری کریں، طلاق دیں۔ پس یہی وہ وقت ہے جس کے متعلق اللہ تعالیٰ نے حکم دیا ہے کہ اس میں عورتوں کو طلاق دی جائے اور عبداللہ بن عمر رضی اللہ عنہما سے اگر اس کے ( مطلقہ ثلاثہ کے ) بارے میں سوال کیا جاتا تو سوال کرنے والے سے وہ کہتے کہ اگر تم نے تین طلاقیں دے دی ہیں تو پھر تمہاری بیوی تم پر حرام ہے۔ یہاں تک کہ وہ تمہارے سوا دوسرے شوہر سے نکاح کرے۔ «غير قتيبة» ( ابوالجہم ) کے اس حدیث میں لیث سے یہ اضافہ کیا ہے کہ ( انہوں نے بیان کیا کہ ) مجھ سے نافع نے بیان کیا اور ان سے ابن عمر رضی اللہ عنہما نے کہا کہ اگر تم نے اپنی بیوی کو ایک یا دو طلاق دے دی ہو۔ ( تو تم اسے دوبارہ اپنے نکاح میں لا سکتے ہو ) کیونکہ نبی کریم صلی اللہ علیہ وسلم نے مجھے اس کا حکم دیا تھا۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5332</td></tr><tr><td>Arabic No</td><td>5332</td></tr><tr><td>Reference</td><td>Book 68 Hadith 77</td></tr></tbody></table></div>