## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا عَبْدُ اللَّهِ بْنُ يُوسُفَ، أَخْبَرَنَا مَالِكٌ، عَنْ زَيْدِ بْنِ أَسْلَمَ، عَنْ عَطَاءِ بْنِ يَسَارٍ، عَنْ عَبْدِ اللَّهِ بْنِ عَبَّاسٍ، أَنَّهُ قَالَ خَسَفَتِ الشَّمْسُ عَلَى عَهْدِ رَسُولِ اللَّهِ صلى الله عليه وسلم فَصَلَّى رَسُولُ اللَّهِ صلى الله عليه وسلم وَالنَّاسُ مَعَهُ، فَقَامَ قِيَامًا طَوِيلاً نَحْوًا مِنْ سُورَةِ الْبَقَرَةِ، ثُمَّ رَكَعَ رُكُوعًا طَوِيلاً، ثُمَّ رَفَعَ فَقَامَ قِيَامًا طَوِيلاً وَهْوَ دُونَ الْقِيَامِ الأَوَّلِ، ثُمَّ رَكَعَ رُكُوعًا طَوِيلاً وَهْوَ دُونَ الرُّكُوعِ الأَوَّلِ، ثُمَّ سَجَدَ، ثُمَّ قَامَ فَقَامَ قِيَامًا طَوِيلاً وَهْوَ دُونَ الْقِيَامِ الأَوَّلِ، ثُمَّ رَكَعَ رُكُوعًا طَوِيلاً وَهْوَ دُونَ الرُّكُوعِ الأَوَّلِ، ثُمَّ رَفَعَ فَقَامَ قِيَامًا طَوِيلاً وَهْوَ دُونَ الْقِيَامِ الأَوَّلِ، ثُمَّ رَكَعَ رُكُوعًا طَوِيلاً وَهْوَ دُونَ الرُّكُوعِ الأَوَّلِ، ثُمَّ رَفَعَ ثُمَّ سَجَدَ، ثُمَّ انْصَرَفَ، وَقَدْ تَجَلَّتِ الشَّمْسُ، فَقَالَ ‏"‏ إِنَّ الشَّمْسَ وَالْقَمَرَ آيَتَانِ مِنْ آيَاتِ اللَّهِ لاَ يَخْسِفَانِ لِمَوْتِ أَحَدٍ وَلاَ لِحَيَاتِهِ، فَإِذَا رَأَيْتُمْ ذَلِكَ فَاذْكُرُوا اللَّهَ ‏"‏‏.‏ قَالُوا يَا رَسُولَ اللَّهِ رَأَيْنَاكَ تَنَاوَلْتَ شَيْئًا فِي مَقَامِكَ هَذَا، ثُمَّ رَأَيْنَاكَ تَكَعْكَعْتَ‏.‏ فَقَالَ ‏"‏ إِنِّي رَأَيْتُ الْجَنَّةَ ـ أَوْ أُرِيتُ الْجَنَّةَ ـ فَتَنَاوَلْتُ مِنْهَا عُنْقُودًا وَلَوْ أَخَذْتُهُ لأَكَلْتُمْ مِنْهُ مَا بَقِيَتِ الدُّنْيَا، وَرَأَيْتُ النَّارَ فَلَمْ أَرَ كَالْيَوْمِ مَنْظَرًا قَطُّ وَرَأَيْتُ أَكْثَرَ أَهْلِهَا النِّسَاءَ ‏"‏‏.‏ قَالُوا لِمَ يَا رَسُولَ اللَّهِ قَالَ ‏"‏ بِكُفْرِهِنَّ ‏"‏‏.‏ قِيلَ يَكْفُرْنَ بِاللَّهِ قَالَ ‏"‏ يَكْفُرْنَ الْعَشِيرَ، وَيَكْفُرْنَ الإِحْسَانَ، وَلَوْ أَحْسَنْتَ إِلَى إِحْدَاهُنَّ الدَّهْرَ، ثُمَّ رَأَتْ مِنْكَ شَيْئًا قَالَتْ مَا رَأَيْتُ مِنْكَ خَيْرًا قَطُّ ‏"‏‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5197</td></tr><tr><td>Arabic No</td><td>5197</td></tr><tr><td>Reference</td><td>Book 67 Hadith 131</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
فِيهِ عَنْ أَبِي سَعِيدٍ عَنْ النَّبِيِّ صلى الله عليه وسلم. এ প্রসঙ্গে আবূ সা‘ঈদ (রাঃ) রাসূলুল্লাহ্সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম থেকে হাদীস বর্ণনা করেন। ৫১৯৭. ‘আবদুল্লাহ্ ইবনু ‘আব্বাস (রাঃ) হতে বর্ণিত যে, রাসূলুল্লাহ্ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর জীবদ্দশায় একদিন সূর্য গ্রহণ আরম্ভ হলো। রাসূলুল্লাহ্ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম সালাতুল খুসুফ বা সূর্যগ্রহণের সালাত পড়লেন এবং লোকেরাও তাঁর সঙ্গে অংশগ্রহণ করল। তিনি এত দীর্ঘক্ষণ কিয়াম করলেন, যাতে সূরা বাকারাহর পরিমাণ কুরআন পাঠ করা যায়। এরপর তিনি দীর্ঘক্ষণ রুকূ করলেন এবং মাথা তুলে দাঁড়িয়ে থাকলেন; এটা প্রথম কিয়ামের চেয়ে কম সময়ের ছিল। তারপর কুরআন তিলাওয়াত করলেন, পুনরায় দীর্ঘক্ষণ রুকূ করলেন। কিন্তু এবারের রুকূর পরিমাণ পূর্বের চেয়ে সংক্ষিপ্ত ছিল। এরপর তিনি দাঁড়ালেন এবং সাজদায় গেলেন। এরপর তিনি কিয়াম করলেন, কিন্তু এবারের সময় ছিল পূর্বের কিয়ামের চেয়ে স্বল্পস্থায়ী। এরপর পুনরায় তিনি রুকূতে গেলেন, কিন্তু এবারের রুকূর সময় পূর্ববর্তী রুকূর সময়ের চেয়ে কম ছিল। এরপর পুনরায় তিনি দাঁড়ালেন।কিন্তু এবারে দাঁড়াবার সময় ছিল পূর্বের চেয়েও কম। এরপরে রুকূতে গেলেন, এবারের রুকূর সময় পুর্ববর্তী রুকূর চেয়ে কম ছিল। তারপর সিজদায় গেলেন এবং সালাত শেষ করলেন। ততক্ষণে সূর্যগ্রহণ শেষ হয়ে গেছে। এরপর নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বললেন, চন্দ্র এবং সূর্য এ দু’টি আল্লাহর নিদর্শনের অন্যতম। কারো জন্মবা মৃত্যুর কারণে এদের গ্রহণ হয় না। তাই তোমরা যখন প্রথম গ্রহণ দেখতে পাও, তখন আল্লাহকে স্মরণ কর। এরপর তাঁরা বলল, হে আল্লাহর রাসূল! আমরা আপনাকে দেখতে পেলাম যে, আপনি কিছু নেয়ার জন্য হাত বাড়িয়েছেন, এরপর আবার আপনাকে দেখতে পেলাম যে, আপনি পিছনের দিকে সরে এলেন। নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বললেন, আমি জান্নাত দেখতে পেলাম অথবা আমাকে জান্নাত দেখানো হয়েছে এবং আমি সেখান থেকে আঙ্গুরের থোকা ছিঁড়ে আনার জন্য হাত বাড়ালাম এবং তা যদি আমি ধরতে পারতাম, তবে তোমরা তা থেকে পৃথিবীর শেষ দিন পর্যন্ত খেতে পারতে। এরপর আমি জাহান্নামের আগুন দেখতে পেলাম। আমি এর পূর্বে কখনও এত ভয়াবহ দৃশ্য দেখিনি এবং আমি আরও দেখতে পেলাম যে, তার অধিকাংশ অধিবাসীই নারী। লোকেরা জিজ্ঞেস করল, হে আল্লাহর রাসূল!এর কারণ কী? তিনি বললেন, এটা তাদের অকৃতজ্ঞতার ফল। লোকেরা বলল, তারা কি আল্লাহ্ তা‘আলার সঙ্গে নাফরমানী করে? তিনি বললেন, তারা তাদের স্বামীদের প্রতি অকৃতজ্ঞ এবং তাদের প্রতি যে অনুগ্রহ দেখানো হয়, তার জন্য তাদের শোকর নেই। তোমরা যদি সারা জীবন তাদের সঙ্গে ভাল ব্যবহার কর; কিন্তু তারা যদি কখনও তোমার দ্বারা কষ্টদায়ক কোন ব্যবহার দেখতে পায়, তখন ব'লে বসে, আমি তোমার থেকে জীবনে কখনও ভাল ব্যবহার পেলাম না। (আধুনিক প্রকাশনী- ৪৮১৫, ইসলামিক ফাউন্ডেশন- ৪৮১৮)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5197</td></tr><tr><td>Arabic No</td><td>5197</td></tr><tr><td>Reference</td><td>Book 67 Hadith 131</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated 'Abdullah bin 'Abbas:During the lifetime of Allah's Messenger (ﷺ), the sun eclipsed. Allah's Messenger (ﷺ) offered the prayer of (the) eclipse) and so did the people along with him. He performed a long Qiyam (standing posture) during which Surat-al-Baqara could have been recited; then he performed a pro-longed bowing, then raised his head and stood for a long time which was slightly less than that of the first Qiyam (and recited Qur'an). Then he performed a prolonged bowing again but the period was shorter than the period of the first bowing, then he stood up and then prostrated. Again he stood up, but this time the period of standing was less than the first standing. Then he performed a prolonged bowing but of a lesser duration than the first, then he stood up again for a long time but for a lesser duration than the first. Then he performed a prolonged bowing but of lesser duration than the first, and then he again stood up, and then prostrated and then finished his prayer. By then the sun eclipse had cleared. The Prophet (ﷺ) then said, "The sun and the moon are two signs among the signs of Allah, and they do not eclipse because of the death or birth of someone, so when you observe the eclipse, remember Allah (offer the eclipse prayer)." They (the people) said, "O Allah's Messenger (ﷺ)! We saw you stretching your hand to take something at this place of yours, then we saw you stepping backward." He said, "I saw Paradise (or Paradise was shown to me), and I stretched my hand to pluck a bunch (of grapes), and had I plucked it, you would have eaten of it as long as this world exists. Then I saw the (Hell) Fire, and I have never before, seen such a horrible sight as that, and I saw that the majority of its dwellers were women." The people asked, "O Allah's Messenger (ﷺ)! What is the reason for that?" He replied, "Because of their ungratefulness." It was said. "Do they disbelieve in Allah (are they ungrateful to Allah)?" He replied, "They are not thankful to their husbands and are ungrateful for the favors done to them. Even if you do good to one of them all your life, when she seems some harshness from you, she will say, "I have never seen any good from you
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5197</td></tr><tr><td>Arabic No</td><td>5197</td></tr><tr><td>Reference</td><td>Book 67 Hadith 131</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Abdullah bin Yusuf] Telah mengabarkan kepada kami [Malik] dari [Zaid bin Aslam] dari [Atha' bin Yasar] dari [Abdullah bin Abbas] bahwa ia berkata; Pernah terjadi gerhana matahari di masa Rasulullah shallallahu 'alaihi wasallam. Maka Rasulullah shallallahu 'alaihi wasallam melaksanakan shalat bersama kaum muslimin. Beliau berdiri dengan berdiri yang sangat panjang sebagaimana panjangnya bacaan surat Al Baqarah. Kemudian beliau ruku' dengan ruku' yang panjang pula. Sesudah itu beliau bangkit dari ruku' lalu berdiri lagi dengan sangat panjang namun tidak sebagaimana panjangnya berdiri beliau yang pertama. Kemudian beliau ruku' dengan panjang, namun tidak sepanjang ruku'nya yang pertama. Lalu beliau teruskan dengan sujud. Setelah itu, beliau bangkit kembali dan berdiri dengan panjang, namun tidak sepanjang berdirinya pertama kali. Kemudian ruku' dengan panjang, tetapi tidak sebagaimana ruku'nya yang pertama. Kemudian beliau bangkit lagi dan berdiri dengan lama, namun tidak selama berdirinya yang pertama. Lalu beliau ruku' kembali dengan lama, tetapi tidak seperti ruku'nya yang pertama. Kemudian beliau bangkit lalu sujud. Setelah beliau selesai shalat matahari pun kembali menampakkan cahaya. Maka beliau pun bersabda: "Sesungguhnya matahari dan bulan adalah dua tanda dari tanda-tanda Allah, tidaklah terjadi gerhana pada keduanya karena kematian seseorang atau pun karena kehidupannya. Jika kalian melihat hal itu, maka berdzikirlah kepada Allah." Para sahabat berkata, "Wahai Rasulullah, kamu melihat bahwa Anda sepertinya mendapatkan sesuatu di tempat Anda berdiri, lalu kami melihat bahwa Anda tertahan." Maka beliau pun bersabda: "Sesungguhnya aku melihat surga -atau- surga telah diperlihatkan padaku, lalu aku pun hendak mengambil seranting darinya, sekiranya kau dapat mengambilnya niscaya kalian akan memakannya selama dunia masih ada. Kemudian aku melihat neraka, maka aku tidak pernah melihat pemandangan seperti yang terjadi pada hari ini. Aku melihat kebanyakan penghuninya adalah wanita." Mereka bertanya lagi, "Kenapa wahai Rasulullah." Beliau menjawab: "Karena kekufuran mereka." Para sahabat bertanya lagi, "Apakah lantaran kekafiran mereka kepada Allah?" beliau menjawab: "Mereka mengkufuri perlakuan dan kebaikan suaminya. Sekiranya kamu berbuat baik kepada salah seorang dari mereka selama setahun penuh, lalu ia melihat sesuatu yang tidak baik darimu, ia pun akan berkata, 'Aku tidak melihat kebaikan sedikit pun darimu
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5197</td></tr><tr><td>Arabic No</td><td>5197</td></tr><tr><td>Reference</td><td>Book 67 Hadith 131</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
அப்துல்லாஹ் பின் அப்பாஸ் (ரலி) அவர்கள் கூறியதாவது: அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் காலத்தில் சூரிய கிரகணம் ஏற்பட்டது. அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் (கிரகணத் தொழுகை) தொழுதார்கள். அவர்களுடன் (சேர்ந்து) மக்களும் தொழுதார்கள். அத்தொழுகையில் ‘அல்பகரா’ எனும் (2ஆவது) அத்தியாயம் ஓதுமளவுக்கு வெகுநேரம் நின்றார்கள். பின்பு நீண்ட நேரம் (குனிந்து) ‘ருகூஉ’ செய்தார்கள். பின்பு (‘ருகூஉ’விலிருந்து) நிமிர்ந்து (நிலைக்கு வந்து) நீண்ட நேரம் நின்றார்கள். இ(ந்த நிலையான)து, முதலாவது நிலையைவிடக் குறைவானதாகவே இருந்தது. பின்னர் நீண்ட நேரம் ‘ருகூஉ’ செய்தார்கள். இ(ந்த இரண்டாம் ருகூஉவான)து, முதலாம் ‘ருகூஉ’வைவிடக் குறைவானதாக இருந்தது. பிறகு (‘ருகூஉ’விலிருந்து) நிமிர்ந்தார்கள். பிறகு ‘சஜ்தா’ (சிரவணக்கம்) செய்தார்கள். பின்னர் (சஜ்தாவிலிருந்து) எழுந்து (நிலையில்) நீண்ட நேரம் நின்றார்கள். இ(ந்த நிலையான)து, முந்தைய நிலையைவிடக் குறைவானதாக இருந்தது. பிறகு நீண்ட நேரம் ‘ருகூஉ’ செய்தார்கள். இ(ந்த ‘ருகூஉ’வான)து, முந்தைய ‘ருகூஉ’வைவிடக் குறைவானதாக இருந்தது. பின்னர் (‘ருகூஉ’விலிருந்து) எழுந்து நீண்ட நேரம் நின்றார்கள். இ(ந்த நிலையான)து முந்தைய நிலையைவிடக் குறைவானதாக இருந்தது. பிறகு நீண்ட நேரம் ‘ருகூஉ’ செய்தார்கள். இ(ந்த ‘ருகூஉ’வான)து முந்தைய ‘ருகூஉ’வைவிடக் குறைவானதாக இருந்தது. பிறகு (‘ருகூஉ’விலிருந்து) நிமிர்ந்தார்கள். பின்னர் ‘சஜ்தா’ செய்தார்கள். பிறகு, (கிரகணம் விலகி) சூரியன் பிரகாசித்துவிட்டிருந்த நிலையில் தொழுது முடித்தார்கள். பிறகு, ‘‘சூரியனும் சந்திரனும் அல்லாஹ்வின் சான்றுகளில் இரண்டு சான்றுகளாகும். எவரது இறப்பிற்காகவோ பிறப்பிற்காகவோ அவற்றுக்குக் கிரகணம் ஏற்படுவதில்லை. எனவே, இ(த்தகைய கிரகணத்)தை நீங்கள் கண்டால் அல்லாஹ்வை நினைவுகூருங்கள்” என்று நபி (ஸல்) அவர்கள் சொன்னார்கள். அப்போது மக்கள், ‘‘அல்லாஹ்வின் தூதரே! நீங்கள் (தொழுதுகொண்டி ருக்கையில்) இதோ இந்த இடத்தில் எதையோ பிடிக்க முயன்றதைக் கண்டோம். பிறகு (அந்த முயற்சியிலிருந்து) பின்வாங்கியதையும் கண்டோமே! (அது ஏன்?)” என்று கேட்டார்கள். அதற்கு நபி (ஸல்) அவர்கள், ‘‘நான் (தொழுதுகொண்டிருக்கையில்) ‘சொர்க்கத் தைக் கண்டேன்’ அல்லது ‘சொர்க்கம் எனக்குக் காட்டப்பட்டது’. அதிலிருந்து (பழக்) குலையொன்றை எடுக்க முயன்றேன். அதை நான் எடுத்திருந்தால் இந்த உலகம் உள்ளவரை நீங்கள் அதிலிருந்(த பழத்திலிருந்)து புசித்திருப்பீர்கள். மேலும், நான் (தொழுதுகொண்டி ருக்கையில்) நரகத்தையும் கண்டேன். இன்றைய தினத்தைப் போன்று (ஒரு பயங்கரமான) காட்சி எதையும் ஒருபோதும் நான் கண்டதேயில்லை. மேலும், நரகவாசிகளில் அதிகமாகப் பெண்களையே கண்டேன்” என்று கூறினார்கள். மக்கள், ‘‘ஏன் (அது?) அல்லாஹ்வின் தூதரே!” என்று கேட்டார்கள். அதற்கு நபி (ஸல்) அவர்கள், ‘‘பெண்களின் நிராகரிப்பே காரணம்” என்றார்கள். அப்போது ‘‘பெண்கள் அல்லாஹ்வையா நிராகரிக்கி றார்கள்?” என வினவப்பட்டது. அதற்கு ‘‘கணவன்மார்களை நிராகரி(த்து நிந்தி)க் கிறார்கள். (கணவன் செய்த) உதவிகளுக்கு நன்றி காட்ட மறுக்கிறார்கள். காலமெல்லாம் ஒருத்திக்கு நீ உதவி செய்து, பிறகு உன்னிடம் ஏதேனும் (குறை) ஒன்றை அவள் கண்டால் ‘உன்னிடமிருந்து எந்த நலனையும் நான் கண்டதேயில்லை’ என்று சொல்லிவிடுவாள்” எனப் பதிலளித்தார்கள்.132 அத்தியாயம் : 67
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5197</td></tr><tr><td>Arabic No</td><td>5197</td></tr><tr><td>Reference</td><td>Book 67 Hadith 131</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Abdullah İbn Abbas'tan şöyle dediği rivayet edilmiştir: "RasuluIlah Sallallahu Aleyhi ve Sellem döneminde güneş tutuldu. Rasulullah Sallallahu Aleyhi ve Sellem, beraberinde insanlar da bulunduğu halde namaz kıl(dır)dı. Bakara slıresi okunacak kadar uzunca bir süre kıyamda durdu. Daha sonra uzunca bir rüklı' yaptı, sonra başını rüklı'dan kaldırdı ve uzun bir süre ayakta durdu; ama bu ilk ayakta duruşundan daha az idi. Sonra bir daha rüklı'a vardı, bu da ilk rüklı'dan daha kısa sürdü. Sonra başını rüklı'dan kaldırdı, secdeye vardı. Daha sonra uzunca bir kıyamda durdu, bu da ilk kıyamdan daha az sürdü. Sonra uzunca bir rüklı' yaptı, bu da ilk rüklı'dan daha az sürdü. Sonra başını kaldırıp uzunca kıyamda kalarak ayakta durdu, ama bu da birinci kıyamdan daha az sürdü. Sonra uzunca bir rüklı' yaptı ve bu da ilk rüklı'dan daha az sürdü. Sonra başını kaldırdı, sonra secde yaptı. Sonra da namazdan Çıktı. Güneş de açılmış bulunuyordu. Allah Rasulü şöyle buyurdu: Şüphesiz güneş ve ay Allah'ın ayetlerinden iki ayettir. Herhangi bir kimsenin ölümü ya da hayatı dolayısıyla tutulmazlar. Böyle bir şey gördüğünüz takdirde hemen Allah'ı zikrediniz. Ey Allah'ın Rasulü, dediler, biz bu esnada ayakta dururken bir şeyalmak üzere elini uzattığını gördük, sonra geriye doğru çekildiğini gördük. Şöyle buyurdu: "Ben cenneti gördüm -ya da bana cennet gösterildi-, oradan elimi bir salkıma uzattım. Onu almış olsaydım, dünya kaldığı sürece ondan yiyip duracaktımz. Cehennemi de gördüm. Fakat bugün gördüğüm manzara gibisini asla görmüş değilim Cehennem ahalisinin çoğunun da kadınlar olduğunu gördüm. "Neden ey Allah'ın Rasulü", diye sordular. O: "Küfürleri sebebiyle", diye buyurdu. Ona: "Allah 'a mı kafir oluyorlar" diye sorulunca, şöyle buyurdu: "Hayır, onlar kocalarına karşı kafirlik (nankörlük) ve iyiliğe karşı kafirlik (nankörlük) ediyorlar. Zaman durdukça onlardan birisine ihsan da bulunsan, sonra da senden (hoşlanmadığı) bir şey görecek olursa, senden en ufak bir hayır görmedim, der
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5197</td></tr><tr><td>Arabic No</td><td>5197</td></tr><tr><td>Reference</td><td>Book 67 Hadith 131</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ہم سے عبداللہ بن یوسف نے بیان کیا، انہوں نے کہا ہم کو امام مالک نے خبر دی، انہیں زید بن اسلم نے، انہیں عطاء بن یسار نے اور انہیں عبداللہ بن عباس رضی اللہ عنہما نے، انہوں نے بیان کیا کہ نبی کریم صلی اللہ علیہ وسلم کے زمانہ میں سورج گرہن ہوا تو نبی کریم صلی اللہ علیہ وسلم نے لوگوں کے ساتھ اس کی نماز پڑھی۔ آپ نے بہت لمبا قیام کی اتنا طویل کہ سورۃ البقرہ پڑھی جا سکے پھر طویل رکوع کیا۔ رکوع سے سر اٹھا کر بہت دیر تک قیام کیا۔ یہ قیام پہلے قیام سے کچھ کم تھا۔ پھر آپ نے دوسرا طویل رکوع کیا۔ یہ رکوع طوالت میں پہلے رکوع سے کچھ کم تھا۔ پھر سر اٹھایا اور سجدہ کیا۔ پھر دوبارہ قیام کیا اور بہت دیر تک حالت قیام میں رہے۔ یہ قیام پہلی رکعت کے قیام سے کچھ کم تھا۔ پھر طویل رکوع کیا، یہ رکوع پہلے رکوع سے کچھ کم طویل تھا۔ پھر سر اٹھایا اور طویل قیام کیا۔ یہ قیام پہلے قیام سے کچھ کم تھا۔ پھر رکوع کیا، طویل رکوع۔ اور یہ رکوع پہلے رکوع سے کچھ کم طویل تھا۔ پھر سر اٹھایا اور سجدہ میں گئے۔ جب آپ نماز سے فارغ ہوئے تو گرہن ختم ہو چکا تھا۔ اس کے بعد آپ صلی اللہ علیہ وسلم نے فرمایا کہ سورج اور چاند اللہ کی نشانیوں میں سے دو نشانیاں ہیں۔ ان میں گرہن کسی کی موت یا کسی کی حیات کی وجہ سے نہیں ہوتا۔ اس لیے جب تم گرہن دیکھو تو اللہ کو یاد کرو۔ صحابہ نے عرض کیا: یا رسول اللہ! ہم نے آپ کو دیکھا کہ آپ نے اپنی جگہ سے کوئی چیز بڑھ کر لی۔ پھر ہم نے دیکھا کہ آپ ہم سے ہٹ گئے۔ نبی کریم صلی اللہ علیہ وسلم نے فرمایا کہ میں نے جنت دیکھی تھی یا ( نبی کریم صلی اللہ علیہ وسلم نے فرمایا راوی کو شک تھا ) مجھے جنت دکھائی گئی تھی۔ میں نے اس کا خوشہ توڑنے کے لیے ہاتھ بڑھایا تھا اور اگر میں اسے توڑ لیتا تو تم رہتی دنیا تک اسے کھاتے اور میں نے دوزخ دیکھی آج کا اس سے زیادہ ہیبت ناک منظر میں نے کبھی نہیں دیکھا اور میں نے دیکھا کہ اس میں عورتوں کی تعداد زیادہ ہے۔ صحابہ نے عرض کیا: یا رسول اللہ! ایسا کیوں ہے؟ نبی کریم صلی اللہ علیہ وسلم نے فرمایا کہ وہ شوہر کی ناشکری کرتی ہیں اور ان کے احسان کا انکار کرتی ہیں، اگر تم ان میں سے کسی ایک کے ساتھ زندگی بھر بھی حسن سلوک کا معاملہ کرو پھر بھی تمہاری طرف سے کوئی چیز اس کے لیے ناگواری خاطر ہوئی تو کہہ دے گی کہ میں نے تو تم سے کبھی بھلائی دیکھی ہی نہیں۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>5197</td></tr><tr><td>Arabic No</td><td>5197</td></tr><tr><td>Reference</td><td>Book 67 Hadith 131</td></tr></tbody></table></div>