## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا إِسْمَاعِيلُ، قَالَ حَدَّثَنِي مَالِكٌ، عَنْ ثَوْرِ بْنِ زَيْدٍ الدِّيلِيِّ، عَنْ أَبِي الْغَيْثِ، مَوْلَى ابْنِ مُطِيعٍ عَنْ أَبِي هُرَيْرَةَ، قَالَ خَرَجْنَا مَعَ رَسُولِ اللَّهِ صلى الله عليه وسلم يَوْمَ خَيْبَرَ فَلَمْ نَغْنَمْ ذَهَبًا وَلاَ فِضَّةً إِلاَّ الأَمْوَالَ وَالثِّيَابَ وَالْمَتَاعَ، فَأَهْدَى رَجُلٌ مِنْ بَنِي الضُّبَيْبِ يُقَالُ لَهُ رِفَاعَةُ بْنُ زَيْدٍ لِرَسُولِ اللَّهِ صلى الله عليه وسلم غُلاَمًا يُقَالُ لَهُ مِدْعَمٌ، فَوَجَّهَ رَسُولُ اللَّهِ صلى الله عليه وسلم إِلَى وَادِي الْقُرَى حَتَّى إِذَا كَانَ بِوَادِي الْقُرَى بَيْنَمَا مِدْعَمٌ يَحُطُّ رَحْلاً لِرَسُولِ اللَّهِ صلى الله عليه وسلم إِذَا سَهْمٌ عَائِرٌ فَقَتَلَهُ، فَقَالَ النَّاسُ هَنِيئًا لَهُ الْجَنَّةُ‏.‏ فَقَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏"‏ كَلاَّ وَالَّذِي نَفْسِي بِيَدِهِ إِنَّ الشَّمْلَةَ الَّتِي أَخَذَهَا يَوْمَ خَيْبَرَ مِنَ الْمَغَانِمِ، لَمْ تُصِبْهَا الْمَقَاسِمُ، لَتَشْتَعِلُ عَلَيْهِ نَارًا ‏"‏‏.‏ فَلَمَّا سَمِعَ ذَلِكَ النَّاسُ جَاءَ رَجُلٌ بِشِرَاكٍ أَوْ شِرَاكَيْنِ إِلَى النَّبِيِّ صلى الله عليه وسلم فَقَالَ ‏"‏ شِرَاكٌ مِنْ نَارٍ ـ أَوْ ـ شِرَاكَانِ مِنْ نَارٍ ‏"‏‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6707</td></tr><tr><td>Arabic No</td><td>6707</td></tr><tr><td>Reference</td><td>Book 83 Hadith 84</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
وَقَالَ ابْنُ عُمَرَ قَالَ عُمَرُ لِلنَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ أَصَبْتُ أَرْضًا لَمْ أُصِبْ مَالاً قَطُّ أَنْفَسَ مِنْهُ قَالَ إِنْ شِئْتَ حَبَّسْتَ أَصْلَهَا وَتَصَدَّقْتَ بِهَا وَقَالَ أَبُو طَلْحَةَ لِلنَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ أَحَبُّ أَمْوَالِي إِلَيَّ بَيْرُحَاءَ لِحَائِطٍ لَهُ مُسْتَقْبِلَةِ الْمَسْجِدِ এবং ইবনু ‘উমার (রাঃ)-এর হাদীস। তিনি বলেন নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর কাছে একবার উমর (রাঃ) আরয করলেন যে, আমি এমন এক টুকরো জমি পেয়েছি যার চেয়ে উৎকৃষ্ট কোন মাল কক্ষনো পাইনি। তিনি বললেনঃ তুমি যদি চাও তবে তার মূল স্বত্ব রেখে তার (উৎপাদন) দান করে দিতে পার। আবু ত্বলহা (রাঃ) নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর কাছে আরয করেছিলেন, আমার কাছে বায়রুহা নামক আমার বাগানটি সর্বাধিক প্রিয়, যার দেয়ালটি মসজিদে নববীর সম্মুখে অবস্থিত। ৬৭০৭. আবূ হুরাইরাহ (রাঃ) হতে বর্ণিত। তিনি বলেন, আমরা রাসূলুল্লাহ্ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর সঙ্গে খায়বারের যুদ্ধের দিন বের হলাম। আমরা মাল, আসবাবপত্র ও কাপড়-চোপড় ছাড়া সোনা বা রুপা গণীমত হিসাবে পাইনি। যুবায়র গোত্রের রিফাআ ইবনু যায়দ নামক এক লোক রাসূলুল্লাহ্ সাল্লাল্লাহু আলাইহি ওয়াসাল্লামকে একটি গোলাম হাদিয়া দিলেন, যার নাম ছিল মিদ‘আম। রাসূলুল্লাহ্ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম ওয়াদি উল কুরার দিকে রওয়ানা হলেন। তিনি যখন ওয়াদিউল কুরায় পৌঁছলেন, তখন মিদ‘আম রাসূলুল্লাহ্ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর সওয়ারীর হাওদা থেকে মালপত্র নামাচ্ছিলেন। তখন হঠাৎ একটি তীর এসে তার গায়ে বিঁধল এবং তাতে সে মারা গেল। লোকেরা বলল, সে জান্নাত লাভ করুক। তখন রাসূলুল্লাহ্ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বললেন কক্ষনো না, কসম ঐ সত্তার, যাঁর হাতে আমার প্রাণ! খায়বারের যুদ্ধের দিন গনীমতের মাল থেকে বণ্টনের পূর্বে যে চাদরটি সে নিয়ে গিয়েছিল তার গায়ে তা আগুনের শিখা হয়ে জ্বলবে। যখন লোকেরা এটা শুনল, তখন এক লোক একটি বা দু’টি ফিতা নিয়ে নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর কাছে এসে হাযির হল। তখন তিনি বললেনঃ এ হচ্ছে জাহান্নামের একটি ফিতা বা জাহান্নামের দু’টি ফিতা।[1] [৪২৩৪] (আধুনিক প্রকাশনী- ৬২৩৪, ইসলামিক ফাউন্ডেশন- ৬২৫০)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6707</td></tr><tr><td>Arabic No</td><td>6707</td></tr><tr><td>Reference</td><td>Book 83 Hadith 84</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated Abu Huraira:We went out in the company of Allah's Messenger (ﷺ) on the day of (the battle of) Khaibar, and we did not get any gold or silver as war booty, but we got property in the form of things and clothes. Then a man called Rifa'a bin Zaid, from the tribe of Bani Ad-Dubaib, presented a slave named Mid'am to Allah's Apostle. Allah's Messenger (ﷺ) headed towards the valley of Al-Qura, and when he was in the valley of Al- Qura an arrow was thrown by an unidentified person, struck and killed Mid'am who was making a she-camel of Allah's Messenger (ﷺ) kneel down. The people said, "Congratulations to him (the slave) for gaining Paradise." Allah's Messenger (ﷺ) said, "No! By Him in Whose Hand my soul is, for the sheet which he stole from the war booty before its distribution on the day of Khaibar, is now burning over him." When the people heard that, a man brought one or two Shiraks (leather straps of shoes) to the Prophet. The Prophet (ﷺ) said, "A Shirak of fire, or two Shiraks of fire
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6707</td></tr><tr><td>Arabic No</td><td>6707</td></tr><tr><td>Reference</td><td>Book 83 Hadith 84</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Isma'il] mengatakan; telah menceritakan kepadaku [Malik] dari [Tsaur bin Zaid ad Daili] dari [Abul Ghaits maula Ibnu Muthi'] dari [Abu Hurairah] mengatakan: kami berangkat bersama Rasulullah Shallallahu'alaihiwasallam saat perang khaibar. Kami tidak memperoleh ghanimah berupa emas dan perak, hanya kami mendapat harta, pakaian dan perabot. Seorang dari bani dhubaib yang dikenal dengan nama Rifa'ah bin Zaid memberi hadiah Rasulullah Shallallahu'alaihiwasallam berupa seorang pelayan namanya Mid'am. Kemudian Rasulullah Shallallahu'alaihiwasallam mengutus Mid'am ke Wadil qura, hingga ketika ia sampai di Wadil qura, tepatnya ketika Mid'am mengendarai hewan tunggangan Rasulullah Shallallahu'alaihiwasallam, sebatang anak panah nyasar mengenai dirinya hingga terbunuh. Para sahabat kemudian berseru; 'sungguh bahagia, baginya surga! ' langsung Rasulullah Shallallahu'alaihiwasallam menegur dengan bersabda: "Sekali-kali tidak, demi dzat yang jiwaku berada di tangan-NYA, baju yang diambilnya dari ghanimah yang belum dibagi di hari Khaibar telah menyalakan api baginya." Ketika para sahabat mendengar sabda beliau, tiba-tiba seseorang membawa seutas tali atau sepasang tali kepada Nabi shallallahu 'alaihi wasallam, dan Nabi bersabda: "seutas tali neraka, atau sepasang tali neraka
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6707</td></tr><tr><td>Arabic No</td><td>6707</td></tr><tr><td>Reference</td><td>Book 83 Hadith 84</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
அபூஹுரைரா (ரலி) அவர்கள் கூறியதாவது: நாங்கள் அல்லாஹ்வின் தூதர் (ஸல்) அவர்களுடன் ‘கைபர்’ தினத்தன்று (வெற்றி கண்டு) புறப்பட்டோம். நாங்கள் (அந்தப் போரில்) பொன்னையோ வெள்ளியையோ போர்ச்செல்வமாகப் பெறவில்லை. (அவையல்லா கால்நடைச்) செல்வங்கள், ஆடைகள், உபயோகப் பொருட்கள் ஆகியவற்றையே பெற்றோம். ‘பனுள்ளுபைப்’ எனும் குலத்தாரில் ரிஃபாஆ பின் ஸைத் என்ற ஒருவர் அல்லாஹ்வின் தூதர் (ஸல்) அவர்களுக்கு ‘மித்அம்’ எனப்படும் ஓர் அடிமையை அன்பளிப்பாக வழங்கினார். அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் ‘வாதில் குரா’ எனும் இடத்தை நோக்கிச் சென்று, அந்த இடத்திற்கு வந்துசேர்ந்த போது ‘மித்அம்’ என்ற அந்த அடிமை அல்லாஹ்வின் தூதர் (ஸல்) அவர்களின் சிவிகையை (ஒட்டகத்திலிருந்து) இறக் கிக்கொண்டிருந்தார். அப்போது எங்கிருந்தோ வந்த அம்பு ஒன்று மித்அமை(த் தாக்கி)க் கொன்றுவிட்டது. இதைக் கண்ட மக்கள் “அவருக்குச் சொர்க்கம் கிடைத்துவிட்டது; வாழ்த்துகள்” என்றனர். உடனே அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள், “அப்படிச் சொல்லாதீர்கள். என்னுயிர் எவன் கையிலுள்ளதோ அவன்மீது சத்தியமாக! போர்ச் செல்வங்கள் பங்கிடப்படும் முன்பே அவற்றிலிருந்து கைபர் அன்று அவர் எடுத்துக்கொண்டுவிட்ட போர்வை அவர்மீது நரக நெருப்பாக எரிந்துகொண்டிருக்கிறது” என்று கூறினார்கள். இதை மக்கள் செவியுற்றபோது, ஒருவர் நபி (ஸல்) அவர்களிடம் ‘ஒரு செருப்பு வாரை’ அல்லது ‘இரு வார்களைக்’ கொண்டுவந்தார். அப்போது நபி (ஸல்) அவர்கள் “(இதைத் திருப்பித் தராமல் இருந்திருந்தால் இது சாதாரண செருப்புவாராக இருந்திராது. மாறாக,) ‘நெருப்புவாராக’ அல்லது ‘இரு நெருப்புவார்களாக’ மாறியிருக்கும்” என்று கூறினார்கள்.109 அத்தியாயம் : 83
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6707</td></tr><tr><td>Arabic No</td><td>6707</td></tr><tr><td>Reference</td><td>Book 83 Hadith 84</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ebu Hureyre şöyle anlatmıştır: Nebi Sallallahu Aleyhi ve Sellem'e birlikte Hayber günü yola çıktık Ne altın, ne gümüş ganimet aldık. Biz oradan birçok mallar (hayvan sürüleri), elbise, eşya ganimeti aldık. Dubeyb oğullarından Rifaa b. Zeyd, Mid'am adında bir köleyi Nebi Sallallahu Aleyhi ve Sellem'e hediye etti. Resulullah Sallallahu Aleyhi ve Sellem onu Vadi'l-Kura'ya gönderdi. Mid'am oraya vardığında Nebi Sallallahu Aleyhi ve Sellem'in eşyasını indirirken kendisine kimin attığı bilinmeyen bir ok isabet etti ve onu öldürdü. İnsanlar "Cennet ona mübarek olsunı" dediler. Resulullah Sallallahu Aleyhi ve Sellem; "Hayır! Hayber gününde ganimetler bölüşülmeden almış olduğu bir örtü şimdi onun üzerinde bir ateş o/up yanmaktadır" dedi. İnsanlar korktu. Bunun üzerinebirisi bir veya iki ayakkabı tasmasını geri getirdi. Nebi Sallallahu Aleyhi ve Sellem "Ateşten bir ayakkabı tasması veya iki ayakkabı tasması" dedi. Fethu'l-Bari Açıklaması: İbn Abdülberr ve onun görüşünde olan bazıları şu görüşü benimsemişlerdir. Ebu Hureyre'nin kabilesi olan Dev's lehçesinde "el-mal" kelimesi mal ve kumaş gibi ayn olmayan şeylere denir. Bir grup bilgine göre "el-mal" altın ve gümüş gibi ayn denilen maddelere verilen isimdir. Arapların kullanımından bilinen, insanın malolarak mülkiyetine geçirdiği ve malik olduğu her şeye "mal" denilir. İmam Buhari attığı başlıkta zikrettiği hadislerle birlikte bu görüşü tercih ettiğine işaret etmektedir. Hz. Ömer'in "Öyle bir toprak parçası elime geçti ki daha önce bundan daha nefis bir mala sahip olmadım", Ebu Talha'nın" Bence mallarımın en sevimlisi Beyruha'da bulunanlardır" ve Ebu Hureyre'nin "Ne altın, ne gümüş ganimet aldık" cümleleri buna örnektir. Bu görüşü Allahu Teala'ın "Allah'ın geçiminize dayanak kı/dığı mallarınızı aklı ermez/ere vermeyin"(Nisa 5) ayet-i kerimesi de bu görüşü teyid etmektedir. Çünkü ayette geçen "mal" kelimesi insanın malik olduğu her şeyi kapsamaktadır. Dilcilerin "Araplar mal kelimesini mutlak olarak kullandıklarında nazarlarında şerefli olduğu için sadece deve için kullanırlar" şeklindeki ifadelerine gelince, bu cümle onların deveden başkasına mal demelerini ortadan kaldırmaz. Araplar deve dışındaki diğer hayvanlara da mal demişlerdir
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6707</td></tr><tr><td>Arabic No</td><td>6707</td></tr><tr><td>Reference</td><td>Book 83 Hadith 84</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ہم سے اسماعیل نے بیان کیا، انہوں نے کہا کہ مجھ سے امام مالک نے بیان کیا، ان سے ثور بن زید دیلی نے بیان کیا، ان سے ابن مطیع کے غلام ابوالغیث نے بیان کیا، ان سے ابوہریرہ رضی اللہ عنہ نے بیان کیا کہ ہم نبی کریم صلی اللہ علیہ وسلم کے ساتھ خیبر کی لڑائی کے لیے نکلے۔ اس لڑائی میں ہمیں سونا، چاندی غنیمت میں نہیں ملا تھا بلکہ دوسرے اموال، کپڑے اور سامان ملا تھا۔ پھر بنی خبیب کے ایک شخص رفاعہ بن زید نامی نے نبی کریم صلی اللہ علیہ وسلم کو ایک غلام ہدیہ میں دیا غلام کا نام مدعم تھا۔ پھر نبی کریم صلی اللہ علیہ وسلم وادی قریٰ کی طرف متوجہ ہوئے اور جب آپ وادی القریٰ میں پہنچ گئے تو مدعم کو جب کہ وہ نبی کریم صلی اللہ علیہ وسلم کا کجاوہ درست کر رہا تھا۔ ایک انجان تیر آ کر لگا اور اس کی موت ہو گئی۔ لوگوں نے کہا کہ جنت اسے مبارک ہو، لیکن نبی کریم صلی اللہ علیہ وسلم نے فرمایا کہ ہرگز نہیں، اس ذات کی قسم جس کے ہاتھ میں میری جان ہے وہ کمبل جو اس نے تقسیم سے پہلے خیبر کے مال غنیمت میں سے چرا لیا تھا، وہ اس پر آگ کا انگارہ بن کر بھڑ رہا ہے۔ جب لوگوں نے یہ بات سنی تو ایک شخص چپل کا تسمہ یا دو تسمے لے کر نبی کریم صلی اللہ علیہ وسلم کی خدمت میں حاضر ہوا، نبی کریم صلی اللہ علیہ وسلم نے فرمایا کہ یہ آگ کا تسمہ ہے یا دو تسمے آگ کے ہیں۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6707</td></tr><tr><td>Arabic No</td><td>6707</td></tr><tr><td>Reference</td><td>Book 83 Hadith 84</td></tr></tbody></table></div>