## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا عَلِيٌّ، حَدَّثَنَا بِشْرُ بْنُ الْمُفَضَّلِ، حَدَّثَنَا يَحْيَى بْنُ أَبِي إِسْحَاقَ، عَنْ أَنَسِ بْنِ مَالِكٍ ـ رضى الله عنه أَنَّهُ أَقْبَلَ هُوَ وَأَبُو طَلْحَةَ مَعَ النَّبِيِّ صلى الله عليه وسلم وَمَعَ النَّبِيِّ صلى الله عليه وسلم صَفِيَّةُ مُرْدِفَهَا عَلَى رَاحِلَتِهِ، فَلَمَّا كَانُوا بِبَعْضِ الطَّرِيقِ عَثَرَتِ النَّاقَةُ، فَصُرِعَ النَّبِيُّ صلى الله عليه وسلم وَالْمَرْأَةُ، وَإِنَّ أَبَا طَلْحَةَ ـ قَالَ أَحْسِبُ قَالَ ـ اقْتَحَمَ عَنْ بَعِيرِهِ فَأَتَى رَسُولَ اللَّهِ صلى الله عليه وسلم فَقَالَ يَا نَبِيَّ اللَّهِ جَعَلَنِي اللَّهُ فِدَاءَكَ، هَلْ أَصَابَكَ مِنْ شَىْءٍ قَالَ ‏"‏ لاَ، وَلَكِنْ عَلَيْكَ بِالْمَرْأَةِ ‏"‏‏.‏ فَأَلْقَى أَبُو طَلْحَةَ ثَوْبَهُ عَلَى وَجْهِهِ، فَقَصَدَ قَصْدَهَا فَأَلْقَى ثَوْبَهُ عَلَيْهَا، فَقَامَتِ الْمَرْأَةُ، فَشَدَّ لَهُمَا عَلَى رَاحِلَتِهِمَا فَرَكِبَا، فَسَارُوا حَتَّى إِذَا كَانُوا بِظَهْرِ الْمَدِينَةِ ـ أَوْ قَالَ أَشْرَفُوا عَلَى الْمَدِينَةِ ـ قَالَ النَّبِيُّ صلى الله عليه وسلم ‏"‏ آيِبُونَ تَائِبُونَ عَابِدُونَ لِرَبِّنَا حَامِدُونَ ‏"‏‏.‏ فَلَمْ يَزَلْ يَقُولُهَا حَتَّى دَخَلَ الْمَدِينَةَ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3086</td></tr><tr><td>Arabic No</td><td>3086</td></tr><tr><td>Reference</td><td>Book 56 Hadith 290</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
আনাস ইবনু মালিক (রাঃ) হতে বর্ণিত যে, তিনি ও আবূ ত্বলহা (রাঃ) নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর সঙ্গে চলছিলেন। আর নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর সঙ্গে সাফিয়্যাহ (রাঃ)-ও ছিলেন। তিনি তাঁকে নিজ সাওয়ারীতে তাঁর পেছনে বসিয়ে ছিলেন। পথিমধ্যে এক জায়গায় উটনীটির পা পিছলে গেল। এতে নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম ও সাফিয়্যাহ (রাঃ) ছিটকে পড়ে গেলেন। আর আবূ ত্বলহা (রাঃ) তার উট হতে তাড়াতাড়ি নেমে রাসূলূল্লাহ্ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর নিকট বললেন, ‘হে আল্লাহর নবী! আল্লাহ তা‘আলা আমাকে আপনার জন্য কুরবান করুন। আপনার কি কোন আঘাত লেগেছে?’ আল্লাহর রাসূল সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বললেন, ‘না। তবে তুমি মহিলাটির খোঁজ নাও।’ আবূ ত্বলহা (রাঃ) একখানা কাপড় দিয়ে মুখমন্ডল ঢেকে তাঁর নিকট গেলেন আর সেই কাপড় দিয়ে তাঁকে ঢেকে দিলেন। তখন সাফিয়্যাহ (রাঃ) উঠে দাঁড়ালেন। অতঃপর তিনি আবূ ত্বলহা (রাঃ) তাঁদের উভয়ের জন্য সাওয়ারীটি উত্তমরূপে বাঁধলেন। আর তাঁরা উভয়ে (তার উপর) আরোহণ করে চলতে শুরু করেন। অবশেষে যখন তাঁরা মদিনার উপকন্ঠে পৌঁছলেন অথবা বর্ণনাকারী বলেন, যখন মদিনার নিকটবর্তী হলেন, তখন নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এ দু‘আ পড়লেন, ‘‘আমরা প্রত্যাবর্তনকারী, তাওবাকারী, ‘ইবাদাতকারী এবং আমাদের প্রতিপালকের প্রশংসাকারী।’ আর মদিনা্য় প্রবেশ করা পর্যন্ত তিনি এ দু‘আ পড়তে থাকেন। (৩৭১) (আধুনিক প্রকাশনীঃ ২৮৫৪, ইসলামিক ফাউন্ডেশনঃ ২৮৬৫)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3086</td></tr><tr><td>Arabic No</td><td>3086</td></tr><tr><td>Reference</td><td>Book 56 Hadith 290</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated Anas bin Malik:That he and Abu Talha came in the company of the Prophet (ﷺ) and Safiya was accompanying the Prophet, who let her ride behind him on his she-camel. During the journey, the she-camel slipped and both the Prophet (ﷺ) and (his) wife fell down. Abu Talha (the sub-narrator thinks that Anas said that Abu Talha jumped from his camel quickly) said, "O Allah's Messenger (ﷺ)! May Allah sacrifice me for your sake! Did you get hurt?" The Prophet (ﷺ) replied,"No, but take care of the lady." Abu Talha covered his face with his garment and proceeded towards her and covered her with his garment, and she got up. He then set right the condition of their she-camel and both of them (i.e. the Prophet (ﷺ) and his wife) rode and proceeded till they approached Medina. The Prophet (ﷺ) said, "We are returning with repentance and worshipping and praising our Lord." The Prophet (ﷺ) kept on saying this statement till he entered Medina
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3086</td></tr><tr><td>Arabic No</td><td>3086</td></tr><tr><td>Reference</td><td>Book 56 Hadith 290</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah bercerita kepada kami ['Ali] telah bercerita kepada kami [Bisyir bin Al Mufadldlol] telah bercerita kepada kami [Yahya bin Abu Ishaq] dari [Anas bin Malik radliallahu 'anhu] bahwa dia dan Abu Tholhah datang menghadap Nabi Shallallahu'alaihiwasallam sedang saat itu bersama Nabi Shallallahu'alaihiwasallam ada Shofiyah membonceng pada hewan tunggangan (unta) Beliau. Ketika di tengah perjalanan, unta tersebut tergelincir sehingga menjatuhkan Nabi Shallallahu'alaihiwasallam dan wanita itu (Shofiyah). Abu Tholhah katakan, seingatku (Yahya) berkata; " Ia tersungkur dari untanya, lantas ia datangi Rasulullah Shallallahu'alaiwasallam seraya berkata; "Wahai Nabi Allah, biarlah Allah menjadikanku sebagai tebusan baginda, apakah Baginda terluka?". Beliau menjawab: "Tidak, tetapi coba kamu tolong wanita (Shofiyah) ". Maka Abu Tholhah menutup wajahnya dengan selembar baju dan menghampiri Shofiyah, seterusnya dia lempar bajunya ke arah Shofiyah (maksudnya untuk menutup wajahnya), dan Shofiyah pun bisa berdiri. Lalu Abu Tholhah memperbaiki pelana hewan tunggangan Beliau tersebut, hingga keduanya dapat mengendarai kembali. Lalu mereka melanjutkan perjalanan hingga ketika sudah nampak kota Madinah, atau (perawi) berkata sudah hampir mendekati kota Madinah, Beliau berdo'a: "Aayibuuna taa'ibuuna 'aabiduuna li robbinaa haamiduuna. (Kita kembali sebagai hamba yang bertaubat, ber'ibadah kepada Robb kita dan memuji-Nya"). Beliau serus saja membaca do'a itu hingga memasuki kota Madinah
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3086</td></tr><tr><td>Arabic No</td><td>3086</td></tr><tr><td>Reference</td><td>Book 56 Hadith 290</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
அனஸ் பின் மாலிக் (ரலி) அவர்கள் கூறியதாவது: நானும் அபூதல்ஹா (ரலி) அவர்களும் நபி (ஸல்) அவர்களுடன் (போரிலிருந்து) மதீனா நோக்கிச் சென்றுகொண்டிருந்தோம். நபி (ஸல்) அவர்களுடன் ஸஃபிய்யா (ரலி) அவர்களும் இருந்தார்கள். அவர்களை நபி (ஸல்) அவர்கள் தமது வாகனத்தில் தமக்குப் பின்னால் அமர்த்திக்கொண்டிருந்தார்கள். அவர்கள் சிறிதளவு தூரத்தைக் கடந்து வந்துகொண்டிருந்தபோது வழியில் வாகனம் சறுக்கி விழுந்தது. நபி (ஸல்) அவர்களும் அவர்களின் துணைவியாரும் கீழே விழுந்தார்கள். அறிவிப்பாளர் யஹ்யா பின் அபீஇஸ்ஹாக் (ரஹ்) அவர்கள் கூறுகிறார்கள்: அனஸ் (ரலி) அவர்கள் பின்வருமாறு கூறினார்கள் என்று எண்ணுகிறேன்: அபூதல்ஹா (ரலி) அவர்கள் தமது ஒட்டகத்திலிருந்து குதித்து இறங்கி அல்லாஹ்வின் தூதர் (ஸல்) அவர்களிடம் வந்து, ‘‘அல்லாஹ்வின் தூதரே! என்னை அல்லாஹ் தங்களுக்கு அர்ப்பணமாக்குவானாக! தங்களுக்குக் காயம் எதுவும் ஏற்பட்டதா?” என்று கேட்டார்கள். அதற்கு நபி (ஸல்) அவர்கள், ‘‘இல்லை. ஆயினும், நீ அந்தப் பெண்ணைக் கவனி” என்று கூறினார்கள். உடனே அபூதல்ஹா (ரலி) அவர்கள் தமது துணியைத் தம் முகத்தின் மீது போட்டு மூடிக்கொண்டு ஸஃபிய்யா (ரலி) அவர்கள் இருந்த திசையை நோக்கி நடந்து சென்று அவர்கள்மீது அத்துணி யைப் போட்டார்கள். உடனே அப் பெண்மணி (ஸஃபிய்யா (ரலி) அவர்கள்) எழுந்துகொண்டார்கள். பிறகு அபூதல்ஹா அவர்கள், அவர்கள் (நபியவர்கள் மற்றும் அன்னை ஸஃபிய்யா) இருவருக்காகவும் அவர்களின் வாகனத்தைச் சீராக்கித் தந்தவுடன் இருவரும் ஏறிக்கொண்ட னர். பிறகு, அனைவரும் பயணத்தைத் தொடர்ந்தனர். மதீனாவின் அருகே வந்த போது நபி (ஸல்) அவர்கள், ‘‘பாவமன்னிப் புக் கோரியவர்களாக, எங்கள் இறைவனை வழிபட்டவர்களாக, (அவனைப் போற்றிப்) புகழ்ந்தவர்களாக நாங்கள் திரும்பிக் கொண்டிருக்கின்றோம்” என்று கூறினார்கள். நபி (ஸல்) அவர்கள் மதீனாவிற்குள் நுழையும்வரை இவ்வாறு கூறிக்கொண்டே யிருந்தார்கள். அத்தியாயம் : 56
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3086</td></tr><tr><td>Arabic No</td><td>3086</td></tr><tr><td>Reference</td><td>Book 56 Hadith 290</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Enes İbn Malik r.a.'in şöyle dediği nakledilmiştir: "Ben ve Ebu Talha Resulullah Sallallahu Aleyhi ve Sellem ile beraberdik Bu sırada Nebi Sallallahu Aleyhi ve Sellem bineği üzerinde idi ve terkisinde de Safiyye binti Huyey vardı. Yolculuk sırasında bir yerlerde Resul-i Ekrem Sallallahu Aleyhi ve Sellem'in devesi tökezleyince ikisi de yere düştü. Ebu Talha hemen devesinden sıçrayıp indi ve yardıma koştu. Resulullah Sallallahu Aleyhi ve Sellem'in yanına varınca: "Ey Allah'ın Resulü, Allah beni sana feda eylesin! bir şeyiniz yok ya!" dedi. Nebi Sallallahu Aleyhi ve Sellem ise: "Ben iyiyim, sen kadınla ilgilen!" buyurdu. Bunun üzerine Ebu Talha yüzünü bir örtü ile kapatıp Safiyye'ye doğru gitti ve bu örtüyü onun üzerine attı. Safiyye de üzeri örtülünce düştüğü yerden kalktı. Ebu Talha daha sonra deveyi tekrar binilecek şekilde hazırladı, koşumlarını bağladı. Resulullah Sallallahu Aleyhi ve Sellem ile Safiyye hazırlanan deveye tekrar bindi ve yola koyuldular. Medine'ye yaklaştığımızda Resul-i Ekrem Sallallahu Aleyhi ve Sellem şöyle buyurdu: "Biz Allah'a dönenleriz, günahlarından tevbe edenleriz, Rabbimize kulluk edenleriz, hamd ile meşgul olanlarız." Resulullah Sallallahu Aleyhi ve Sellem Medine'ye girene kadar bunları söylemeye devam etti
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3086</td></tr><tr><td>Arabic No</td><td>3086</td></tr><tr><td>Reference</td><td>Book 56 Hadith 290</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ہم سے علی بن عبداللہ مدینی نے بیان کیا ‘ کہا ہم سے بشر بن مفضل نے بیان کیا ‘ کہا ہم سے یحییٰ بن ابی اسحاق نے بیان کیا اور ان سے انس بن مالک رضی اللہ عنہ نے بیان کیا کہ وہ اور ابوطلحہ رضی اللہ عنہ نبی کریم صلی اللہ علیہ وسلم کے ساتھ تھے، ام المؤمنین صفیہ رضی اللہ عنہا کو آپ صلی اللہ علیہ وسلم نے اپنی سواری پر پیچھے بٹھا رکھا تھا۔ راستے میں اتفاق سے آپ کی اونٹنی پھسل گئی اور آپ صلی اللہ علیہ وسلم گر گئے اور ام المؤمنین بھی گر گئیں۔ ابوطلحہ رضی اللہ عنہ نے یوں کہا کہ میں سمجھتا ہوں ‘ انہوں نے اپنے آپ کو اونٹ سے گرا دیا اور آپ صلی اللہ علیہ وسلم کے قریب پہنچ کر عرض کیا: اے اللہ کے رسول! اللہ مجھے آپ پر قربان کرے کوئی چوٹ تو آپ کو نہیں آئی؟ آپ صلی اللہ علیہ وسلم نے فرمایا کہ نہیں لیکن تم عورت کی خبر لو۔ چنانچہ انہوں نے ایک کپڑا اپنے چہرے پر ڈال لیا ‘ پھر ام المؤمنین کی طرف بڑھے اور وہی کپڑا ان پر ڈال دیا۔ اب ام المؤمنین کھڑی ہو گئیں۔ پھر ابوطلحہ رضی اللہ عنہ نے آپ دونوں کے لیے اونٹنی کو مضبوط کیا۔ تو آپ سوار ہوئے اور سفر شروع کیا۔ جب مدینہ منورہ کے سامنے پہنچ گئے یا راوی نے یہ کہا کہ جب مدینہ دکھائی دینے لگا تو نبی کریم صلی اللہ علیہ وسلم نے یہ دعا پڑھی «آيبون تائبون عابدون لربنا حامدون‏ ‏‏.‏» ”ہم اللہ کی طرف لوٹنے والے ہیں۔ توبہ کرنے والے ‘ اپنے رب کی عبادت کرنے والے اور اس کی تعریف کرنے والے ہیں!“ آپ صلی اللہ علیہ وسلم یہ دعا برابر پڑھتے رہے ‘ یہاں تک کی مدینہ میں داخل ہو گئے۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3086</td></tr><tr><td>Arabic No</td><td>3086</td></tr><tr><td>Reference</td><td>Book 56 Hadith 290</td></tr></tbody></table></div>