## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
أَخْبَرَنَا قُتَيْبَةُ، عَنْ مَالِكٍ، عَنْ عَبْدِ الرَّحْمَنِ بْنِ الْقَاسِمِ، عَنْ أَبِيهِ، عَنْ عَائِشَةَ، قَالَتْ خَرَجْنَا مَعَ رَسُولِ اللَّهِ صلى الله عليه وسلم فِي بَعْضِ أَسْفَارِهِ حَتَّى إِذَا كُنَّا بِالْبَيْدَاءِ أَوْ ذَاتِ الْجَيْشِ انْقَطَعَ عِقْدٌ لِي فَأَقَامَ رَسُولُ اللَّهِ صلى الله عليه وسلم عَلَى الْتِمَاسِهِ وَأَقَامَ النَّاسُ مَعَهُ وَلَيْسُوا عَلَى مَاءٍ وَلَيْسَ مَعَهُمْ مَاءٌ فَأَتَى النَّاسُ أَبَا بَكْرٍ - رضى الله عنه - فَقَالُوا أَلاَ تَرَى مَا صَنَعَتْ عَائِشَةُ أَقَامَتْ بِرَسُولِ اللَّهِ صلى الله عليه وسلم وَبِالنَّاسِ وَلَيْسُوا عَلَى مَاءٍ وَلَيْسَ مَعَهُمْ مَاءٌ ‏.‏ فَجَاءَ أَبُو بَكْرٍ - رضى الله عنه - وَرَسُولُ اللَّهِ صلى الله عليه وسلم وَاضِعٌ رَأْسَهُ عَلَى فَخِذِي قَدْ نَامَ فَقَالَ حَبَسْتِ رَسُولَ اللَّهِ صلى الله عليه وسلم وَالنَّاسَ وَلَيْسُوا عَلَى مَاءٍ وَلَيْسَ مَعَهُمْ مَاءٌ ‏.‏ قَالَتْ عَائِشَةُ فَعَاتَبَنِي أَبُو بَكْرٍ وَقَالَ مَا شَاءَ اللَّهُ أَنْ يَقُولَ وَجَعَلَ يَطْعُنُ بِيَدِهِ فِي خَاصِرَتِي فَمَا مَنَعَنِي مِنَ التَّحَرُّكِ إِلاَّ مَكَانُ رَسُولِ اللَّهِ صلى الله عليه وسلم عَلَى فَخِذِي فَنَامَ رَسُولُ اللَّهِ صلى الله عليه وسلم حَتَّى أَصْبَحَ عَلَى غَيْرِ مَاءٍ فَأَنْزَلَ اللَّهُ عَزَّ وَجَلَّ آيَةَ التَّيَمُّمِ ‏.‏ فَقَالَ أُسَيْدُ بْنُ حُضَيْرٍ مَا هِيَ بِأَوَّلِ بَرَكَتِكُمْ يَا آلَ أَبِي بَكْرٍ ‏.‏ قَالَتْ فَبَعَثْنَا الْبَعِيرَ الَّذِي كُنْتُ عَلَيْهِ فَوَجَدْنَا الْعِقْدَ تَحْتَهُ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Abu Ghuddah</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>310</td></tr><tr><td>Arabic No</td><td>310</td></tr><tr><td>Reference</td><td>Book 1 Hadith 311</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
হাদিস একাডেমি নাম্বারঃ ৩১০, আন্তর্জাতিক নাম্বারঃ ৩১১ ৩১০. কুতায়বাহ্ (রহ.) ..... ‘আয়িশাহ্ (রাঃ) হতে বর্ণিত। তিনি বলেন, আমরা রাসূলুল্লাহ (সা.) -এস সাথে কোন এক সফরে বের হলাম। আমরা যখন বায়দা অথবা যাতুল জায়শ নামক স্থানে ছিলাম তখন আমার একটি (গলার) হার হারিয়ে গেল। রাসূলুল্লাহ (সা.) তাঁর সঙ্গীগণ তার (গলার হারের) খোঁজে সেখানে অবস্থান করলেন। তাদের অবস্থান পানির কাছে ছিল না এবং তাদের সাথেও পানি ছিল না। লোকজন আবূ বাকর (রাঃ) -এর কাছে এসে বলল, আপনি কি দেখেছেন ‘আয়িশাহ্ কি করলেন? তিনি রাসূলুল্লাহ (সা.) -কে এবং অন্যান্য লোকেদের এমন স্থানে আটকিয়ে রেখেছেন যার নিকটে কোন পানি নেই এবং লোকেদের সাথেও কোন পানি নেই। তখন আবূ বাকর (রাঃ) আমার কাছে এলেন। রাসূলুল্লাহ (সা.) তখন আমার উরুর উপর মাথা রেখে ঘুমিয়ে পড়ছিলেন। আবূ বাকর (রাঃ) বললেন- তুমি রাসূলুল্লাহ (সা.) এবং অন্যান্য লোকেদের এমন জায়গায় আটকিয়ে রাখলে যেখানে পানির কোন উৎস নেই আর তাদের সাথেও পানি নেই। আয়িশাহ্ (রাঃ) বললেন, তিনি আমাকে খুব তিরস্কার করলেন আর আল্লাহর যা ইচ্ছা ছিল তাই বললেন এবং তাঁর হাত দিয়ে আমার কোমড়ে খোঁচা দিতে লাগলেন। রাসূলুল্লাহ (সা.)-এর মাথা আমার উরুর উপর থাকার কারণে আমি নড়তে পারছিলাম না। রাসূলুল্লাহ (সা.) নিদ্রায় রইলেন এমনকি পানির কোন ব্যবস্থা ছাড়াই সকাল হয়ে গেল। তখন আল্লাহ তাআলা তায়াম্মুমের আয়াত অবতীর্ণ করলেন। এতে উসায়দ ইবনু হুযায়র (রাঃ) বলেন, হে আবূ বাকরের পরিজন! এ তোমাদের প্রথম বারাকাত নয়। আয়িশাহ্ (রাঃ) বলেন, আমি যে উটের উপর ছিলাম তা উঠালে তার নিচেই আমার হারটি পেলাম। সহীহ: বুখারী ৩৩৪, মুসলিম ৩৬৭।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Abu Ghuddah</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>310</td></tr><tr><td>Arabic No</td><td>310</td></tr><tr><td>Reference</td><td>Book 1 Hadith 311</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
It was narrated that 'Aishah said:"We went out with the Messenger of Allah (ﷺ) on one of his journeys, and when we were in Al-Baida' or Dhat Al-Jaish, a necklace of mine broke and fell. The Messenger of Allah (ﷺ) stayed there looking for it and the people stayed with him. There was no water near them, and they did not have water with them. The people came to Abu Bakr, may Allah be pleased with him, and said: 'Do you see what 'Aishah has done? She has made the Messenger of Allah (ﷺ) and the people stop and they are not near any water and they do not have water with them.' Abu Bakr, may Allah be pleased with him, came while the Messenger of Allah (ﷺ) was resting his head on my thigh and had gone to sleep. He said: 'You have detained the Messenger of Allah (ﷺ) and the people, and they are not near any water and they do not have any water with them.'" 'Aishah said: "Abu Bakr rebuked me and said whatever Allah willed he would say. He started poking me on my hip, and the only thing that prevented me from moving was the fact that the Messenger of Allah (ﷺ) was resting on my thigh. The Messenger of Allah (ﷺ) slept until morning when he woke up without any water. Then Allah, the Mighty and Sublime revealed the verse of Tayammum. Usaid bin Hudair said: 'This is not the first time we have been blessed because of you, O family of Abu Bakr!'" She said: "Then we made the camel that I had been riding stand up, and we found the necklace beneath it
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Abu Ghuddah</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>310</td></tr><tr><td>Arabic No</td><td>310</td></tr><tr><td>Reference</td><td>Book 1 Hadith 311</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah mengabarkan kepada kami [Qutaibah] dari [Malik] dari [Abdurrahman bin Al Qasim] dari [Bapaknya] dari [Aisyah] Radliyallahu'anha dia berkata; "Kami pernah bersama Rasulullah shallallahu 'alaihi wasallam dalam sebagian perjalanannya, dan saat kami sampai di Al Baida -atau di Dzatuljaisy-- kalungku hilang, maka Rasulullah shallallahu 'alaihi wasallam berhenti untuk mencarinya dan para sahabat juga ikut bersamanya. Mereka tidak mempunyai air dan juga Rasulullah shallallahu 'alaihi wasallam. Para sahabat datang kepada Abu Bakar Radliyallhu'anhu dan berkata, 'Apakah kamu tidak melihat apa yang diperbuat Aisyah?! Ia menghentikan (menahan) Rasulullah shallallahu 'alaihi wasallam dan para sahabat, padahal mereka tidak pada tempat yang ada airnya dan mereka juga tidak mempunyai air'. Abu Bakar Radliyallahu'anhu lalu datang (kepadaku) dan Rasulullah shallallahu 'alaihi wasallam berbaring meletakkan kepalanya di atas pahaku dan beliau tertidur. Ia berkata, 'Kamu menahan Rasulullah shallallahu 'alaihi wasallam dan manusia pada tempat yang tidak ada airnya dan mereka juga tidak mempunyai air?" Aisyah berkata, "Abu Bakar mencelaku dan beliau mengatakan sebagaimana yang dikehendaki Allah dan ia menekan lambungku dengan tangannya. Tidak ada yang menghalangiku untuk bergerak kecuali keadaan Rasulullah shallallahu 'alaihi wasallam yang berada di atas pahaku! Rasulullah shallallahu 'alaihi wasallam tertidur hingga pagi, tanpa ada air. Kemudian Allah Azza wa Jalla menurunkan ayat tayamum." Usaid bin Hudhair berkata; "Ini bukan keberkahan keluargamu yang pertama wahai keluarga Abu Bakar!" Aisyah berkata, "Lalu kami membangunkan unta yang kami tunggangi, dan kalung tersebut ternyata ada di bawahnya
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Abu Ghuddah</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>310</td></tr><tr><td>Arabic No</td><td>310</td></tr><tr><td>Reference</td><td>Book 1 Hadith 311</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Âişe (radıyallahü anha)’dan rivâyete göre, şöyle demiştir: Rasûlüllah (sallallahü aleyhi ve sellem) ile beraber seferlerden birine çıkmıştık. Beyda veya Zat-ül Ceyş bölgesine geldiğimizde gerdanlığım kayboldu. Rasûlüllah (sallallahü aleyhi ve sellem) onu aramak için orada konakladı. Diğer insanlar da O’nunla birlikte konaklamış oldular. Orası bir su başı değildi. Yanlarında da su yoktu. İnsanlar, Ebû Bekir’e gelerek: Âişe’nin yaptığını görmüyor musun? Rasûlüllah (sallallahü aleyhi ve sellem) ve insanların bu susuz yerde konaklamalarına sebep olmuştur. Yanlarında su kalmamıştır. üzerine; babam Ebû Bekir, yanıma geldi. Rasûlüllah (sallallahü aleyhi ve sellem), başını dizimin üzerine koymuş uyuya kalmıştı. Bana şöyle dedi: Rasûlüllah (sallallahü aleyhi ve sellem) ve bu insanları bu susuz yerde, burada alıkoydun yanlarında da suları yok. diyor ki: Ebû Bekir beni böylece azarladı, ağzına geleni söyledi ve eliyle böğrüme dürttü. Rasûlüllah (sallallahü aleyhi ve sellem)’in dizimde uyuması hareket etmemi engelliyordu.) Rasûlüllah (sallallahü aleyhi ve sellem) uyudu ve sabah oldu fakat su yoktu. Bunun üzerine Allah teyemmüm ayetini indirdi. O zaman Üseyd b. Hudayr: Ebû Bekir ailesi, bu sizin ilk bereketiniz değildir) dedi. (radıyallahü anha) diyor ki: sırada üzerine bindiğimiz deveyi kaldırınca gerdanlığı devenin altında bulduk.) (Buhârî, Teyemmüm: 1; İbn Mâce, Tahara: 90)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Abu Ghuddah</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>310</td></tr><tr><td>Arabic No</td><td>310</td></tr><tr><td>Reference</td><td>Book 1 Hadith 311</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ام المؤمنین عائشہ رضی اللہ عنہا کہتی ہیں کہ ہم رسول اللہ صلی اللہ علیہ وسلم کے ساتھ ایک سفر میں نکلے، یہاں تک کہ جب ہم مقام بیداء یا ذات الجیش میں پہنچے، تو میرا ہار ٹوٹ کر گر گیا، تو آپ صلی اللہ علیہ وسلم اسے تلاش کرنے کے لیے ٹھہر گئے، آپ کے ساتھ لوگ بھی ٹھہر گئے، نہ وہاں پانی تھا اور نہ ہی لوگوں کے پاس پانی تھا، تو لوگ ابوبکر رضی اللہ عنہ کے پاس آئے، اور ان سے کہنے لگے کہ عائشہ نے جو کیا ہے کیا آپ اسے دیکھ نہیں رہے ہیں؟ انہوں نے رسول اللہ صلی اللہ علیہ وسلم کو اور لوگوں کو ایک ایسی جگہ ٹھہرا دیا جہاں پانی نہیں ہے، اور نہ ان کے پاس ہی پانی ہے، چنانچہ ابوبکر رضی اللہ عنہ آئے، اور رسول اللہ صلی اللہ علیہ وسلم میری ران پر سر رکھ کر سوئے ہوئے تھے، تو وہ کہنے لگے: تم نے رسول اللہ صلی اللہ علیہ وسلم کو اور لوگوں کو ایسی جگہ روک دیا جہاں پانی نہیں ہے، نہ ہی ان کے پاس پانی ہے، ام المؤمنین عائشہ رضی اللہ عنہا کہتی ہیں کہ تو ابوبکر رضی اللہ عنہ نے میری سرزنش کی، اور اللہ تعالیٰ نے ان سے جو کہلوانا چاہا انہوں نے کہا، اور اپنے ہاتھ سے میری کوکھ میں کچوکے لگانے لگے، میں صرف اس وجہ سے نہیں ہلی کہ میری ران پر رسول اللہ صلی اللہ علیہ وسلم کا سر تھا، آپ صلی اللہ علیہ وسلم سوئے رہے یہاں تک کہ بغیر پانی کے صبح ہو گئی، پھر اللہ عزوجل نے تیمم کی آیت نازل فرمائی، اس پر اسید بن حضیر رضی اللہ عنہ کہنے لگے: اے آل ابوبکر! یہ آپ کی پہلی ہی برکت نہیں، پھر ہم نے اس اونٹ کو جس پر میں سوار تھی اٹھایا، تو ہمیں ہار اسی کے نیچے ملا۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Abu Ghuddah</td></tr><tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>310</td></tr><tr><td>Arabic No</td><td>310</td></tr><tr><td>Reference</td><td>Book 1 Hadith 311</td></tr></tbody></table></div>