## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
أَخْبَرَنَا أَبُو بَكْرِ بْنُ عَلِيٍّ، قَالَ حَدَّثَنَا إِسْحَاقُ، قَالَ حَدَّثَنَا أَبُو عُمَارَةَ، حَمْزَةُ بْنُ الْحَارِثِ بْنِ عُمَيْرٍ قَالَ سَمِعْتُ أَبِي يَذْكُرُ، عَنْ عُبَيْدِ اللَّهِ بْنِ عُمَرَ، عَنْ سَعِيدِ بْنِ أَبِي سَعِيدٍ الْمَقْبُرِيِّ، عَنْ أَبِي هُرَيْرَةَ، قَالَ بَيْنَمَا النَّبِيُّ صلى الله عليه وسلم مَعَ أَصْحَابِهِ جَاءَ رَجُلٌ مِنْ أَهْلِ الْبَادِيَةِ قَالَ أَيُّكُمُ ابْنُ عَبْدِ الْمُطَّلِبِ قَالُوا هَذَا الأَمْغَرُ الْمُرْتَفِقُ - قَالَ حَمْزَةُ الأَمْغَرُ الأَبْيَضُ مُشْرَبٌ حُمْرَةً - فَقَالَ إِنِّي سَائِلُكَ فَمُشْتَدٌّ عَلَيْكَ فِي الْمَسْأَلَةِ قَالَ ‏"‏ سَلْ عَمَّا بَدَا لَكَ ‏"‏ ‏.‏ قَالَ أَسْأَلُكَ بِرَبِّكَ وَرَبِّ مَنْ قَبْلَكَ وَرَبِّ مَنْ بَعْدَكَ آللَّهُ أَرْسَلَكَ قَالَ ‏"‏ اللَّهُمَّ نَعَمْ ‏"‏ ‏.‏ قَالَ فَأَنْشُدُكَ بِهِ آللَّهُ أَمَرَكَ أَنْ تُصَلِّيَ خَمْسَ صَلَوَاتٍ فِي كُلِّ يَوْمٍ وَلَيْلَةٍ قَالَ ‏"‏ اللَّهُمَّ نَعَمْ ‏"‏ ‏.‏ قَالَ فَأَنْشُدُكَ بِهِ آللَّهُ أَمَرَكَ أَنْ تَأْخُذَ مِنْ أَمْوَالِ أَغْنِيَائِنَا فَتَرُدَّهُ عَلَى فُقَرَائِنَا قَالَ ‏"‏ اللَّهُمَّ نَعَمْ ‏"‏ ‏.‏ قَالَ فَأَنْشُدُكَ بِهِ آللَّهُ أَمَرَكَ أَنْ تَصُومَ هَذَا الشَّهْرَ مِنَ اثْنَىْ عَشَرَ شَهْرًا قَالَ ‏"‏ اللَّهُمَّ نَعَمْ ‏"‏ ‏.‏ قَالَ فَأَنْشُدُكَ بِهِ آللَّهُ أَمَرَكَ أَنْ يَحُجَّ هَذَا الْبَيْتَ مَنِ اسْتَطَاعَ إِلَيْهِ سَبِيلاً قَالَ ‏"‏ اللَّهُمَّ نَعَمْ ‏"‏ ‏.‏ قَالَ فَإِنِّي آمَنْتُ وَصَدَّقْتُ وَأَنَا ضِمَامُ بْنُ ثَعْلَبَةَ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih Isnaad</td><td>Abu Ghuddah</td></tr><tr><td>Sahih Isnaad</td><td>Al-Albani</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2094</td></tr><tr><td>Arabic No</td><td>2094</td></tr><tr><td>Reference</td><td>Book 22 Hadith 5</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>

</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih Isnaad</td><td>Abu Ghuddah</td></tr><tr><td>Sahih Isnaad</td><td>Al-Albani</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2094</td></tr><tr><td>Arabic No</td><td>2094</td></tr><tr><td>Reference</td><td>Book 22 Hadith 5</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
It was narrated that Abu Hurairah said:"While the Prophet was with his Companions a man from among the desert people came and said: 'Which of you is the son of 'Abdul-Muttalib?' They said: 'This Anghar man who is reclining on a pillow.' (One of the narrators) Hamzah said: "Amghar means white with a reddish complexion.'- The man said: 'I am going to ask you questions and I will be harsh in asking.' He said: 'ask whatever you like.' He said: 'I ask you by your Lord and the Lord of those who came before you, and the Lord of those who will come after you; has Allah sent you?' He said: 'By Allah, yes.' He said: 'I adjure you by Him, has Allah commanded you to offer five prayers each day and night?' He said: 'By Allah, yes.; He said: 'I adjure you by Him, has Allah commanded you to take from the wealth of our rich and give it to our poor?' he said: 'By Allah, yes He said: 'I adjure you by Allah, has Allah commanded you to fast this month out of the twelve months?' He said: 'By Allah, yes.' He said: 'I adjure you by Him, has Allah commanded you to go on pilgrimage to this House, where can afford it?' He said: 'By Allah yes.' He said: 'I belive, and I am Dimam bin Thalabah
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih Isnaad</td><td>Abu Ghuddah</td></tr><tr><td>Sahih Isnaad</td><td>Al-Albani</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2094</td></tr><tr><td>Arabic No</td><td>2094</td></tr><tr><td>Reference</td><td>Book 22 Hadith 5</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah mengabarkan kepada kami [Abu Bakr bin 'Ali] dia berkata; telah menceritakan kepada kami [Ishaq] dia berkata; telah menceritakan kepada kami [Abu 'Umarah Hamzah bin Al Harits bin 'Umair] dia berkata; aku mendengar [bapakku] menyebutkan dari ['Ubaidullah bin 'Umar] dari [Sa'id bin Abu Sa'id Al Maqburi] dari [Abu Hurairah] dia berkata; "Ketika Nabi bersama para sahabat, datanglah seorang dari penduduk kampung seraya bertanya; "Manakah di antara kalian yang menjadi anak Abdul Muththallib?" Mereka menjawab, "Orang putih yang sedang bersandar ini!" Hamzah (perawi hadits ini) berkata; "Orang putih artinya putih kemerah-merahan". Lalu ia berkata; "Sungguh aku akan bertanya kepadamu, dan aku betul-betul serius dalam bertanya ini." Beliau bersabda: "Tanyakanlah apa yang terlintas dalam pikiranmu." Lalu orang itu bertanya; "Aku bersumpah atas nama Rabbmu dan Rabb orang-orang sebelum kamu, apakah Allah telah mengutusmu kepada seluruh manusia?" Beliau menjawab: "Ya Allah, ya." Ia bertanya; "Aku bersumpah atas nama Allah, apakah Allah telah memerintahkanmu untuk mengerjakan shalat lima waktu dalam sehari semalam? Rasulullah shallallahu 'alaihi wasallam menjawab: "Ya Allah, ya." Ia bertanya; "Aku bersumpah atas nama Allah, apakah Allah telah memerintahkanmu untuk mengambil zakat ini dari orang-orang kaya di antara kami, lalu dibagikan kepada orang-orang fakir di antara kami? Rasulullah shallallahu 'alaihi wasallam menjawab: "Ya Allah, Ya." Ia bertanya; "Aku bersumpah atas nama Allah, apakah Allah telah memerintahkanmu untuk melaksanakan puasa pada bulan ini di setiap tahunnya? Rasulullah shallallahu 'alaihi wasallam menjawab: "Ya Allah, Ya." Ia bertanya; "Aku bersumpah atas nama Allah, apakah Allah telah memerintahkanmu untuk menunaikan haji ke Baitullah ini bagi orang yang mampu mengadakan perjalanannya? Beliau menjawab, "Ya Allah, Ya." Ia itu berkata, "Maka sungguh aku telah beriman dan percaya dan aku adalah Dhimam bin Tsa'labah
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih Isnaad</td><td>Abu Ghuddah</td></tr><tr><td>Sahih Isnaad</td><td>Al-Albani</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2094</td></tr><tr><td>Arabic No</td><td>2094</td></tr><tr><td>Reference</td><td>Book 22 Hadith 5</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>

</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih Isnaad</td><td>Abu Ghuddah</td></tr><tr><td>Sahih Isnaad</td><td>Al-Albani</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2094</td></tr><tr><td>Arabic No</td><td>2094</td></tr><tr><td>Reference</td><td>Book 22 Hadith 5</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ابوہریرہ رضی الله عنہ کہتے ہیں نبی اکرم صلی اللہ علیہ وسلم اپنے صحابہ کے ساتھ تھے کہ اسی دوران دیہاتیوں میں ایک شخص آیا، اور اس نے پوچھا: تم میں عبدالمطلب کے بیٹے کون ہیں؟ لوگوں نے کہا: یہ گورے رنگ والے جو تکیہ پر ٹیک لگائے ہوئے ہیں ( حمزہ کہتے ہیں: «الأمغر» سرخی مائل کو کہتے ہیں ) تو اس شخص نے کہا: میں آپ سے کچھ پوچھنے ولا ہوں، اور پوچھنے میں آپ سے سختی کروں گا، تو آپ صلی اللہ علیہ وسلم نے کہا: ”پوچھو جو چاہو“، اس نے کہا: میں آپ سے آپ کے رب کا اور آپ سے پہلے لوگوں کے رب کا اور آپ کے بعد کے لوگوں کے رب کا واسطہ دے کر پوچھتا ہوں: کیا اللہ نے آپ کو رسول بنا کر بھیجا ہے؟ آپ صلی اللہ علیہ وسلم نے فرمایا: ”اے اللہ تو گواہ رہ، ہاں“، اس نے کہا: تو میں اسی کا واسطہ دے کر آپ سے پوچھتا ہوں کیا اللہ نے آپ کو حکم دیا ہے کہ آپ روزانہ پانچ وقت کی نماز پڑھیں؟ آپ نے کہا: ”اے اللہ تو گواہ رہ، ہاں“، اس نے کہا: کیا اللہ نے آپ کو حکم دیا ہے کہ آپ ہمارے مالداروں کے مالوں میں سے ( زکاۃ ) لیں، پھر اسے ہمارے فقیروں کو لوٹا دیں، آپ صلی اللہ علیہ وسلم نے فرمایا: ”اے اللہ تو گواہ رہنا، ہاں“، اس نے کہا: میں آپ کو اللہ کی قسم دلاتا ہوں، کیا اللہ تعالیٰ نے آپ کو سال کے بارہ مہینوں میں سے اس مہینہ میں روزے رکھنے کا حکم دیا ہے؟ تو آپ صلی اللہ علیہ وسلم نے کہا: ”اے اللہ تو گواہ رہنا، ہاں“، اس نے کہا: میں آپ کو اللہ کی قسم دلاتا ہوں کیا اللہ تعالیٰ نے آپ حکم دیا ہے کہ جو اس خانہ کعبہ تک پہنچنے کی طاقت رکھے وہ اس کا حج کرے؟ آپ صلی اللہ علیہ وسلم نے کہا: ”اے اللہ گواہ رہنا ہاں“، تب اس شخص نے کہا: میں ایمان لایا اور میں نے تصدیق کی، میں ضمام بن ثعلبہ ہوں۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih Isnaad</td><td>Abu Ghuddah</td></tr><tr><td>Sahih Isnaad</td><td>Al-Albani</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2094</td></tr><tr><td>Arabic No</td><td>2094</td></tr><tr><td>Reference</td><td>Book 22 Hadith 5</td></tr></tbody></table></div>