## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا هِشَامُ بْنُ عَمَّارٍ، حَدَّثَنَا عَبْدُ الْعَزِيزِ بْنُ أَبِي حَازِمٍ، عَنْ أَبِيهِ، عَنْ سَهْلِ بْنِ سَعْدٍ السَّاعِدِيِّ، أَنَّ امْرَأَةً، جَاءَتْ إِلَى رَسُولِ اللَّهِ ـ صلى الله عليه وسلم ـ بِبُرْدَةٍ - قَالَ وَمَا الْبُرْدَةُ قَالَ الشَّمْلَةُ - قَالَتْ يَا رَسُولَ اللَّهِ إِنِّي نَسَجْتُ هَذِهِ بِيَدِي لأَكْسُوَكَهَا ‏.‏ فَأَخَذَهَا رَسُولُ اللَّهِ ـ صلى الله عليه وسلم ـ مُحْتَاجًا إِلَيْهَا فَخَرَجَ عَلَيْنَا فِيهَا وَإِنَّهَا لإِزَارُهُ فَجَاءَ فُلاَنُ بْنُ فُلاَنٍ - رَجُلٌ سَمَّاهُ يَوْمَئِذٍ - فَقَالَ يَا رَسُولَ اللَّهِ مَا أَحْسَنَ هَذِهِ الْبُرْدَةَ اكْسُنِيهَا ‏.‏ قَالَ ‏ "‏ نَعَمْ ‏"‏ ‏.‏ فَلَمَّا دَخَلَ طَوَاهَا وَأَرْسَلَ بِهَا إِلَيْهِ فَقَالَ لَهُ الْقَوْمُ وَاللَّهِ مَا أَحْسَنْتَ كُسِيَهَا النَّبِيُّ ـ صلى الله عليه وسلم ـ مُحْتَاجًا إِلَيْهَا ثُمَّ سَأَلْتَهُ إِيَّاهَا وَقَدْ عَلِمْتَ أَنَّهُ لاَ يَرُدُّ سَائِلاً ‏.‏ فَقَالَ إِنِّي وَاللَّهِ مَا سَأَلْتُهُ إِيَّاهَا لأَلْبَسَهَا وَلَكِنْ سَأَلْتُهُ إِيَّاهَا لِتَكُونَ كَفَنِي ‏.‏ فَقَالَ سَهْلٌ فَكَانَتْ كَفَنَهُ يَوْمَ مَاتَ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3555</td></tr><tr><td>Arabic No</td><td>3555</td></tr><tr><td>Reference</td><td>Book 32 Hadith 6</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
৬/৩৫৫৫। সাহল ইবনে সাদ আস-সাইদী (রাঃ) থেকে বর্ণিত। এক মহিলা একখানা চাদরসহ রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর নিকট এসে বললো, ইয়া রাসূলাল্লাহ! আপনার পরার জন্য আমি নিজ হাতে এটা বুনেছি। চাদরের প্রয়োজন অনুভব করে রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম তা গ্রহণ করলেন, অতঃপর সেটাকে লুঙ্গীর মত করে পরিধান করে আমাদের নিকট আসলেন। তখন অমুকের পুত্র অমুক এসে বললো, হে আল্লাহর রাসূল! চাদরটা কী চমৎকার। এটা আমাকে পরতে দিন। রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেনঃ আচ্ছা। তিনি ভিতর বাড়িতে গিয়ে চাদরটা ভাঁজ করে তার নিকট পাঠিয়ে দিলেন। লোকজন তাকে বললো, আল্লাহর শপথ! কাজটা তুমি ভালো করোনি। নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম প্রয়োজন অনুভব করেই তা পরেছিলেন। আর তুমি তাঁর নিকট থেকে সেটা চেয়ে নিলে! অথচ তুমি জানো যে, তিনি কোন প্রার্থীকেই বিমুখ করেন না। সে বললো, আল্লাহর শপথ! আমি এটা পরার জন্য তাঁর থেকে চেয়ে নেইনি, বরং আমার কাফন বানানোর জন্য চেয়ে নিয়েছি। সাহল (রাঃ) বলেন, লোকটা যেদিন মারা গেল সেদিন সেটিই তার কাফন হলো।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3555</td></tr><tr><td>Arabic No</td><td>3555</td></tr><tr><td>Reference</td><td>Book 32 Hadith 6</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
It was narrated from Sahl bin Sa’d Sa’idi that a woman came to the Messenger of Allah (ﷺ) with a woven sheet – he said:* “What type of woven sheet?” He said: “A Shamlah.” She said: “O Messenger of Allah, I have woven this with my own hands for you to wear.” The Messenger of Allah (ﷺ) took it, since he needed it. He came out to us wearing it as a lower wrap. So-and-so the son of so-and-so.” – a man whose name he told that day – said: “O Messenger of Allah, how beautiful this sheet is! Let me wear it.” He said: “Yes.” When he went inside he folded it up and sent it to him. The people said to him: “By Allah, you have not done well. The Prophet (ﷺ) wore it because he needed it, then you asked for it, and you knew that he would not refuse anyone who asked him for something.” He said: “By Allah, I did not ask for it so that I could wear it, rather I asked for it so that it could be my shroud.” Sahl said: “And it became his shroud the day he died.”
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3555</td></tr><tr><td>Arabic No</td><td>3555</td></tr><tr><td>Reference</td><td>Book 32 Hadith 6</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Hisyam bin 'Ammar] Telah menceritakan kepada kami [Abdul Aziz bin Abu Hazim] dari [Ayahnya] dari [Sahl bin Sa'd As Sa'idi], bahwa seorang wanita datang kepada Nabi shallallahu 'alaihi wasallam dengan membawa kain burdah -perawai berkata, 'Apakah kain burdah itu? Ia Dijawab, 'Yaitu kain mantel.'- Wanita itu berkata, "Wahai Rasulullah, sungguh aku telah merajut sendiri jubah ini supaya anda memakainya." Kemudian Rasulullah shallallahu 'alaihi wasallam mengambilnya karena beliau butuh jubah tersebut, kemudian beliau memperlihatkan jubah tersebut kepada kami yang bentuknya seperti kain. Lalu datanglah fulan bin fulan -seorang laki-laki yang di kenal masa itu- seraya berkata, "Wahai Rasulullah, sungguh sangat indah jubah ini, pakaikanlah untukku! " Beliau menjawab: "Baiklah." Beliau kemudian masuk dan melipat kain tersebut, lalu mengirimkannya kepada laki-laki tersebut, orang-orang lalu berkata kepadanya, "Demi Allah, sungguh beruntung kamu, (padahal) Nabi shallallahu 'alaihi wasallam memakainya karena butuh terhadap jubah itu, kemudian kamu memintanya. Kamu sebenarnya sangat tahu bahwa beliau tidak pernah bisa menolak orang yang meminta." Laki-laki itu berkata, "Demi Allah, sesungguhnya aku tidaklah meminta jubah itu untuk aku pakai, tetapi aku minta itu untuk aku pakai sebagai kain kafanku." Sahl berkata, "Maka jubah itu pun menjadi kain kafan lelaki tersebut ketika ia meninggal dunia
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3555</td></tr><tr><td>Arabic No</td><td>3555</td></tr><tr><td>Reference</td><td>Book 32 Hadith 6</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Sehl bin Sa'd es-Sâidî (r.a.)'dan; Şöyle demiştir: Bir kadın, Resulullah Sallallahu Aleyhi ve Sellem'e bir bürde getirdi. (Sehl: Bürde nedir? diye —orada bulunanlara — sordu —da sözüne devamla — Bürdedir —yâni ihram gibi dikişsizdir— diye sorusunu kendisi cevabladı.) Bürdeyi getiren kadın : Yâ Resûlallah, bu bürdeyi sana giydireyim diye kendi elimle dokudum, dedi. Resulullah (Sallallahu Aleyhi ve Sellem) de bürdeyi aldı. Zâten kendisinin böyle bir bürdeye ihtiyacı vardı. Sonra Resulullah (Sallallahu Aleyhi ve Sellem) o bürdeyi izâr (yâni belden aşağı vücûduna sarmış) olarak giyip (evden) yanımıza çıktı. Sonra falan oğlu falan (Sehl'in o gün ismini söylediği bir adam) gelerek: Yâ Resulallah, bu bürde ne güzeldir! Bunu bana giydir, dedi. Resul-i Ekrem (Sallallahu Aleyhi ve Sellem) de: Peki buyurdu. Sonra eve girince bürdeyi dürüp o adam'a gönderdi. Orada hazır olan cemâat adama: Vallahi sen iyi etmedin. Nebi (Sallallahu Aleyhi ve Sellem)'e bu bürde ihtiyacı olarak giydirildi. Sonra sen kendisinin bir şey isteyen hiç bir kimseyi reddetmediğini bildiğin halde Ondan bürdeyi istedin, dediler. Adam da (bu yadırgamaya karşılık): Vallahi ben bu bürdeyi giymek için istemedim. Ve lâkin (öldüğümde) kefenim olsun diye istedim, dedi. Sehl demiştir ki: Sonra bu zât'ın vefat ettiği gün hakikaten o bürde onun kefeni oldu
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3555</td></tr><tr><td>Arabic No</td><td>3555</td></tr><tr><td>Reference</td><td>Book 32 Hadith 6</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
سہل بن سعد ساعدی رضی اللہ عنہ سے روایت ہے کہ ایک عورت رسول اللہ صلی اللہ علیہ وسلم کی خدمت میں «بردہ» ( چادر ) لے کر آئی ( ابوحازم نے پوچھا«بردہ» کیا چیز ہے؟ ان کے شیخ نے کہا: «بردہ» شملہ ہے جسے اوڑھا جاتا ہے ) اور کہا: اللہ کے رسول! اسے میں نے اپنے ہاتھ سے بنا ہے تاکہ میں آپ کو پہناؤں، رسول اللہ صلی اللہ علیہ وسلم نے اسے لے لیا کیونکہ آپ کو اس کی ضرورت تھی، پھر آپ اسے پہن کر کے ہمارے درمیان نکل کر آئے، یہی آپ کا تہبند تھا، پھر فلاں کا بیٹا فلاں آیا ( اس شخص کا نام حدیث بیان کرنے کے دن سہل نے لیا تھا لیکن ابوحازم اسے بھول گئے ) اور عرض کیا: اللہ کے رسول! یہ چادر کتنی اچھی ہے، یہ آپ مجھے پہنا دیجئیے، فرمایا: ٹھیک ہے ، پھر جب آپ اندر گئے تو اسے ( اتار کر ) تہ کیا، اور اس کے پاس بھجوا دی، لوگوں نے اس سے کہا: اللہ کی قسم! تم نے اچھا نہیں کیا، نبی اکرم صلی اللہ علیہ وسلم کو اس نے اس لیے پہنائی تھی کہ آپ کو اس کی حاجت تھی، پھر بھی تم نے اسے آپ سے مانگ لیا، حالانکہ تمہیں معلوم تھا کہ آپ کسی سائل کو نامراد واپس نہیں کرتے تو اس شخص نے جواب دیا: اللہ کی قسم! میں نے آپ سے اسے پہننے کے لیے نہیں مانگا ہے بلکہ اس لیے مانگا ہے کہ وہ میرا کفن ہو، سہل کہتے ہیں: جب وہ مرے تو یہی چادر ان کا کفن تھی ۱؎۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3555</td></tr><tr><td>Arabic No</td><td>3555</td></tr><tr><td>Reference</td><td>Book 32 Hadith 6</td></tr></tbody></table></div>