## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا مُحَمَّدُ بْنُ بَشَّارٍ، حَدَّثَنَا مُحَمَّدُ بْنُ جَعْفَرٍ، حَدَّثَنَا عَوْفٌ، عَنِ الْحَسَنِ، حَدَّثَنَا أَسِيدُ بْنُ الْمُتَشَمِّسِ، قَالَ حَدَّثَنَا أَبُو مُوسَى، حَدَّثَنَا رَسُولُ اللَّهِ ـ صلى الله عليه وسلم ـ ‏"‏ إِنَّ بَيْنَ يَدَىِ السَّاعَةِ لَهَرْجًا ‏"‏ ‏.‏ قَالَ قُلْتُ يَا رَسُولَ اللَّهِ مَا الْهَرْجُ قَالَ ‏"‏ الْقَتْلُ ‏"‏ ‏.‏ فَقَالَ بَعْضُ الْمُسْلِمِينَ يَا رَسُولَ اللَّهِ إِنَّا نَقْتُلُ الآنَ فِي الْعَامِ الْوَاحِدِ مِنَ الْمُشْرِكِينَ كَذَا وَكَذَا ‏.‏ فَقَالَ رَسُولُ اللَّهِ ـ صلى الله عليه وسلم ـ ‏"‏ لَيْسَ بِقَتْلِ الْمُشْرِكِينَ وَلَكِنْ يَقْتُلُ بَعْضُكُمْ بَعْضًا حَتَّى يَقْتُلَ الرَّجُلُ جَارَهُ وَابْنَ عَمِّهِ وَذَا قَرَابَتِهِ ‏"‏ ‏.‏ فَقَالَ بَعْضُ الْقَوْمِ يَا رَسُولَ اللَّهِ وَمَعَنَا عُقُولُنَا ذَلِكَ الْيَوْمَ فَقَالَ رَسُولُ اللَّهِ ـ صلى الله عليه وسلم ـ ‏"‏ لاَ تُنْزَعُ عُقُولُ أَكْثَرِ ذَلِكَ الزَّمَانِ وَيَخْلُفُ لَهُ هَبَاءٌ مِنَ النَّاسِ لاَ عُقُولَ لَهُمْ ‏"‏ ‏.‏ ثُمَّ قَالَ الأَشْعَرِيُّ وَايْمُ اللَّهِ إِنِّي لأَظُنُّهَا مُدْرِكَتِي وَإِيَّاكُمْ وَايْمُ اللَّهِ مَا لِي وَلَكُمْ مِنْهَا مَخْرَجٌ إِنْ أَدْرَكَتْنَا فِيمَا عَهِدَ إِلَيْنَا نَبِيُّنَا ـ صلى الله عليه وسلم ـ إِلاَّ أَنْ نَخْرُجَ كَمَا دَخَلْنَا فِيهَا ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Hasan</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3959</td></tr><tr><td>Arabic No</td><td>3959</td></tr><tr><td>Reference</td><td>Book 36 Hadith 34</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
৩/৩৯৫৯। আবূ মূসা আল-আশআরী (রাঃ) থেকে বর্ণিত। তিনি বলেন, রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম আমাদেরকে বললেনঃ কিয়ামতের নিকটবর্তী সময়ে ‘‘হারজ’’ হবে। রাবী বলেন, আমি বললাম, হে আল্লাহর রাসূল! ‘‘হারজ’’ কী? তিনি বলেনঃ ব্যাপক গণহত্যা। কতক মুসলিম বললেন, হে আল্লাহর রাসূল! আমরা এখন এই এক বছরে এত মুশরিককে হত্যা করেছি। রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেনঃ তা মুশরিকদের হত্যা করা নয়, বরং তোমরা পরস্পরকে হত্যা করবে; এমনকি কোন ব্যক্তি তার প্রতিবেশীকে, চাচাতো ভাইকে এবং নিকট আত্মীয়-স্বজনকে পর্যন্ত হত্যা করবে। কতক লোক বললো, হে আল্লাহর রাসূল! তখন কি আমাদের বিবেক-বুদ্ধি লোপ পাবে? রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেনঃ অধিকাংশ লোকের জ্ঞান লোপ পাবে এবং অবশিষ্ট থাকবে নির্বোধ ও মুর্খ। অতঃপর আবূ মূসা আল-আশআরী (রাঃ) বলেন, আল্লাহর শপথ! আমি ধারণা করেছিলাম যে, হয়তো এ যুগ তোমাদেরকে ও আমাকে পেতো, তাহলে তা থেকে আমার ও তোমাদের বের হয়ে আসা মুশকিল হয়ে যেতো, যেমন নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম আমাদের জোর দিয়ে বলেছিলেন যে, আমরা ঐ অনাচারে যতো সহজে জড়িয়ে পড়বো তা থেকে আমাদের নিষ্ক্রমণ ততোধিক দুষ্কর হবে।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Hasan</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3959</td></tr><tr><td>Arabic No</td><td>3959</td></tr><tr><td>Reference</td><td>Book 36 Hadith 34</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Abu Musa narrated that the Messenger of Allah (ﷺ) said:“Before the Hour comes there will be Harj.” I said: “O Messenger of Allah, what is Harj?” He said: “Killing.” Some of the Muslims said: “O Messenger of Allah, now we kill such and such a number of idolaters in one year.” The Messenger of Allah (ﷺ) said: “That will not be like killing the idolaters, rather you will kill one another, until a man will kill his neighbor and son of the cousin and a relative.” Some of the people said: “O Messenger of Allah, will we be in our right minds that day?” The Messenger of Allah (ﷺ) said: “No, reason will be taken away from most of the people at that time, and there will be left the insignificant people who have no reason.”
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Hasan</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3959</td></tr><tr><td>Arabic No</td><td>3959</td></tr><tr><td>Reference</td><td>Book 36 Hadith 34</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Muhammad bin Basysyar] telah menceritakan kepada kami [Muhammad bin Ja'far] telah menceritakan kepada kami ['Auf] dari [Al Hasan] telah menceritakan kepada kami [Asid bin Al Mutasyammas] dia berkata; telah menceritakan kepada kami [Abu Musa] telah menceritakan kepada kami Rasulullah shallallahu 'alaihi wasallam, beliau bersabda "Sesungguhnya di antara (tanda-tanda) hari Kiamat adalah terjadinya kekacauan." Abu Musa berkata, "Saya bertanya, "Wahai Rasulullah, apakah yang di maksudkan kekacauan?" beliau menjawa: "Pembunuhan." Sebagian kaum Muslimin lalu bertanya, "Wahai Rasulullah, dalam satu tahun ini kami telah membunuh kaum Musyrikin begini dan begini." Maka Rasulullah shallallahu 'alaihi wasallam bersabda: "Bukannya membunuh kaum Musyrikin, akan tetapi kalianlah yang akan saling bunuh sesama kalian, sehingga seseorang membunuh tetangganya, anak pamannya, dan kerabat dekatnya sendiri." Sebagian yang lain lalu bertanya, "Wahai Rasulullah, mekipun saat itu para ulama masih bersama kami?! Rasulullah shallallahu 'alaihi wasallam menjawab: "Tidak, para ulama akan dimatikan lalu diganti dengan orang-orang hina dan bodoh." Kemudian Abu Musa Al Asy'ari berkata, "Demi Allah, sesungguhnya aku memastikan bahwa perkara itu akan menimpa kita dan kalian. Demi Allah, tidak ada jalan keluar bagiku dan kalian, jika apa yang telah di janjikan Rasulullah shallallahu 'alaihi wasallam itu menimpa kita, kecuali jika kita keluar sebagaimana kita masuk ke dalamnya
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Hasan</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3959</td></tr><tr><td>Arabic No</td><td>3959</td></tr><tr><td>Reference</td><td>Book 36 Hadith 34</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ebu Musa (el-Eş'ari) (r.a.)'den; şöyle demigtir; Resulullah (Sallallahu Aleyhi ve Sellem) bize Kıyamete yakın dönemde şüphesiz bir here olur,» buyurdu. Ebu Musa demiştir ki: Ben: Ya Resulallah! Here nedir? diye sordum. O: «Katildir,» buyurdu. Bunun üzerine bazı müslümanlar: Ya Resulallah! Biz şu anda tek bir yılda müşriklerden şu kadarımı öldürürüz, dediler. Resulullah (Sallallahu Aleyhi ve Sellem) bu söze cevaben: «Herc, müşrikleri öldürmek deglldir. Lakin bazınız bazınızi öldürecek, hatta adam komşusunu, amcasının oğlunu ve akrabasını öldürecektir,» buyurdu. Sonra orada bulunanların bazısı: O gün akıllarınız beraberimizde (yani başımızda) olduğu halde mi (biribirimizi öldüreceğiz)? diye sordu. Resulullah (Sallallahu Aleyhi ve Sellem): «Hayır. O zaman (daki halk)ın çoğunun akılları alınacak ve akılsız bir takım adi insanlar o dönemin adamları olacaktır,» buyurdu. Sonra el-Eş'ari (r.a.) dedi ki: Allah'a yemin ederim ben o vaziyetin bana ve sizlere yetişeceğini (yani o günleri göreceğiinizi) cidden kuvvetle sanırım. Allah'a and olsun ki o vaziyet bize ulaşırsa Nebi (Sallallahu Aleyhi ve Sellem)'in bize tavsiyesine göre ona girdiğimiz gibi (suç işlemeden) çıkmamızdan başka hiç-bir çıkar yol ne benim için ne de sizler için vardır. Not: Bu hadis Zevaid türündendir. AÇIKLAMA 3962’de
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Hasan</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3959</td></tr><tr><td>Arabic No</td><td>3959</td></tr><tr><td>Reference</td><td>Book 36 Hadith 34</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ابوموسیٰ اشعری رضی اللہ عنہ کہتے ہیں کہ رسول اللہ صلی اللہ علیہ وسلم نے ہم سے بیان کیا: قیامت سے پہلے «ہرج» ہو گا ، میں نے پوچھا: اللہ کے رسول!«ہرج» کیا ہے؟ آپ صلی اللہ علیہ وسلم نے فرمایا: قتل ، کچھ مسلمانوں نے عرض کیا: اللہ کے رسول! ہم تو اب بھی سال میں اتنے اتنے مشرکوں کو قتل کرتے ہیں، آپ صلی اللہ علیہ وسلم نے فرمایا: مشرکین کا قتل مراد نہیں بلکہ تم آپس میں ایک دوسرے کو قتل کرو گے، حتیٰ کہ آدمی اپنے پڑوسی، اپنے چچا زاد بھائی اور قرابت داروں کو بھی قتل کرے گا ، تو کچھ لوگوں نے عرض کیا: اللہ کے رسول! کیا اس وقت ہم لوگ عقل و ہوش میں ہوں گے کہ نہیں ؟ آپ صلی اللہ علیہ وسلم نے فرمایا: نہیں، بلکہ اس زمانہ کے اکثر لوگوں کی عقلیں سلب کر لی جائیں گی، اور ان کی جگہ ایسے کم تر لوگ لے لیں گے جن کے پاس عقلیں نہیں ہوں گی ۔ پھر ابوموسیٰ اشعری رضی اللہ عنہ نے کہا: قسم اللہ کی! میں سمجھتا ہوں کہ شاید یہ زمانہ مجھے اور تم کو پا لے، اللہ کی قسم! اگر ایسا زمانہ مجھ پر اور تم پر آ گیا تو ہمارے اور تمہارے لیے اس سے نکلنے کا کوئی راستہ نہ ہو گا، جیسا کہ ہمارے نبی اکرم صلی اللہ علیہ وسلم نے ہمیں وصیت کی ہے، سوائے اس کے کہ ہم اس سے ویسے ہی نکلیں جیسے داخل ہوئے
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Hasan</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3959</td></tr><tr><td>Arabic No</td><td>3959</td></tr><tr><td>Reference</td><td>Book 36 Hadith 34</td></tr></tbody></table></div>