## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا مُحَمَّدُ بْنُ الصَّبَّاحِ، حَدَّثَنَا عَبْدُ الْعَزِيزِ بْنُ أَبِي حَازِمٍ، حَدَّثَنِي أَبِي، عَنْ سَهْلِ بْنِ سَعْدٍ السَّاعِدِيِّ، قَالَ مَرَّ عَلَى رَسُولِ اللَّهِ ـ صلى الله عليه وسلم ـ رَجُلٌ فَقَالَ النَّبِيُّ ـ صلى الله عليه وسلم ـ ‏"‏ مَا تَقُولُونَ فِي هَذَا الرَّجُلِ قَالُوا رَأْيَكَ فِي ‏.‏ هَذَا نَقُولُ هَذَا مِنْ أَشْرَافِ النَّاسِ هَذَا حَرِيٌّ إِنْ خَطَبَ أَنْ يُخَطَّبَ وَإِنْ شَفَعَ أَنْ يُشَفَّعَ وَإِنْ قَالَ أَنْ يُسْمَعَ لِقَوْلِهِ ‏.‏ فَسَكَتَ النَّبِيُّ ـ صلى الله عليه وسلم ـ وَمَرَّ رَجُلٌ آخَرُ فَقَالَ النَّبِيُّ ـ صلى الله عليه وسلم ـ ‏"‏ مَا تَقُولُونَ فِي هَذَا ‏"‏ ‏.‏ قَالُوا نَقُولُ وَاللَّهِ يَا رَسُولَ اللَّهِ هَذَا مِنْ فُقَرَاءِ الْمُسْلِمِينَ هَذَا حَرِيٌّ إِنْ خَطَبَ لَمْ يُنْكَحْ وَإِنْ شَفَعَ لاَ يُشَفَّعْ وَإِنْ قَالَ لاَ يُسْمَعْ لِقَوْلِهِ فَقَالَ النَّبِيُّ ـ صلى الله عليه وسلم ـ ‏"‏ لَهَذَا خَيْرٌ مِنْ مِلْءِ الأَرْضِ مِثْلَ هَذَا ‏"‏ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4120</td></tr><tr><td>Arabic No</td><td>4120</td></tr><tr><td>Reference</td><td>Book 37 Hadith 21</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
১/৪১২০। সাহল ইবনে সাদ আল-সাইদী (রাঃ) থেকে বর্ণিত। তিনি বলেন, এক ব্যক্তি রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর নিকট দিয়ে যাচ্ছিল। নবী রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম জিজ্ঞেস করলেনঃ তোমরা এ লোকটি সম্পর্কে কী বলো? সাহাবীগণ বলেন, তার সম্পর্কে আপনার অভিমত হবে যথার্থ। আমরা বলি, সে সুপারিশ করলে তা মঞ্জুর করা হয়। সে কথা বললে তা শোনা হয়। নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম চুপ থাকলেন। ইত্যবসরে আরেক ব্যক্তি সেখান দিয়ে অতিক্রম করলো। নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম জিজ্ঞেস করলেনঃ এই ব্যক্তি সম্পর্কে তোমরা কী বলো? সাহাবীগণ বলেন, আল্লাহর শপথ, হে আল্লাহর রাসূল! আমরা বলি যে, এ ব্যক্তি তো দীনহীন মুসলিমদের অন্তর্ভুক্ত। সে এতই যোগ্য যে, সে বিবাহের প্রস্তাব দিলে তা প্রত্যাখ্যান করা হয়, সুপারিশ করলে তা মঞ্জুর করা হয় না এবং কথা বললে তার কথায় কেউ কর্ণপাত করে না। নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেনঃ প্রথমোক্ত শ্রেণীর লোকের দ্বারা পৃথিবী ভরে গেলেও শেষোক্ত ব্যক্তি তাদের চেয়ে উত্তম।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4120</td></tr><tr><td>Arabic No</td><td>4120</td></tr><tr><td>Reference</td><td>Book 37 Hadith 21</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
It was narrated that Sahl bin Sa’d As-Sa’idi said:“A man passed by the Messenger of Allah (ﷺ) and the Prophet (ﷺ) said: ‘What do you say about this man?’ They said: ‘We agree with your opinion concerning him. We say: He is one of the noblest of people. If he proposes marriage, his proposal deserves to be accepted; and if he intercedes, his intercession deserves to be accepted; and if he speaks, he deserves to be listened to.’ The Prophet (ﷺ) remained silent, and another man passed by. The Prophet (ﷺ) said: ‘What do you think about this man?’ We said: ‘By Allah, O Messenger of Allah, this is one of the poor Muslims. If he proposes marriage, he does not deserve to get married; and if he intercedes, his intercession does not deserve to be accepted; and if he speaks, he does not deserve to be listened to.’ The Prophet (ﷺ) said: ‘This one is better than an earthful of (men like) the other man.’”
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4120</td></tr><tr><td>Arabic No</td><td>4120</td></tr><tr><td>Reference</td><td>Book 37 Hadith 21</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Muhammad bin As Shabah] telah menceritakan kepada kami [Abdul Aziz bin Abu Hazim] telah menceritakan kepadaku [Ayahku] dari [Sahl bin Sa'd As Sa'idi] dia berkata, "Seorang laki-laki melintasi Rasulullah shallallahu 'alaihi wasallam, lantas Nabi shallallahu 'alaihi wasallam bersabda: "Apa pendapat kalian dengan laki-laki ini?" mereka menjawab, "Pendapat kami bahwa dia dari bangsawan, apabila meminang pasti akan di terima, dan bila dimintai bantuan pasti akan membantu, dan jika berkata pasti perkataannya akan di dengar." Nabi shallallahu 'alaihi wasallam diam. Beberapa saat kemudian lewatlah seorang laki-laki di hadapan beliau, lalu Nabi shallallahu 'alaihi wasallam bertanya: "Apa pendapat kalian dengan orang ini?" Mereka menjawab, "Menurut kami, demi Allah, wahai Rasulullah… orang ini adalah orang termiskin dari kalangan kaum Muslimin, apabila ia meminang pasti pinangannya akan di tolak, jika dimintai pertolongan dia tidak akan menolong, dan apabila berkata maka perkataannya tidak akan di dengar." Kemudian Rasulullah shallallahu 'alaihi wasallam bersabda: "Sungguh, orang ini (orang yang terlihat miskin) lebih baik dari dunia dan seisinya daripada orang yang ini (yaitu orang yang kelihatanya bangsawan)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4120</td></tr><tr><td>Arabic No</td><td>4120</td></tr><tr><td>Reference</td><td>Book 37 Hadith 21</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Sehl bin Sa'd es-Sâidî (r.a.)'den; Şöyle demiştir: Bir kere Resulullah (Sallallahu Aleyhi ve Sellem)'in yanından (zengin) bir adam geçti. Bunun üzerine Nebi (Sallallahu Aleyhi ve Sellem) (yanında bulunanlara): Bu (zengin) adam hakkında ne dersiniz? buyurdu. Orada bulunanlar: Bu adam hakkında senin görüşüne uygun söz söyleriz. (Dış görünüşe göre ve dünyalık açısından ise) şöyle söyleriz: Bu adam İnsanların en şereflilerindendir. Bu adam (bir kız - kadın ile) evlenmek isterse evlenilmeye, (bir şey için) şefaatçi (aracı) olursa, şefaatçiliği (aracılığı) kabul edilmeye, bir şey söylerse sözü dinlenmeye lâyık bir kimsedir, dediler. Nebi (Sallallahu Aleyhi ve Sellem) de sustu. Bu esnada (fakir olan) başka bir adam geçti. Bunun üzerine Nebi (Sallallahu Aleyhi ve Sellem): Bu adam hakkında ne dersiniz? diye sordu. Orada bulunanlar: Vallahi Yâ Resulallah! Biz şöyle deriz: Bu adam, müslümanların fakirlerindendir. Bu şuna layıktır! (Bir kız-kadın ile) evlenmeye taIip olursa onunla evlenilmez, (bir şey için) şefaatçi (aracı) olursa şefaatçiliği (aracılığı) kabul edilmez ve bir şey söylerse sözü dinlenmez, dediler. Bunun üzerine Nebi (Sallallahu Aleyhi ve Sellem): «Bu (fakir) şüphesiz, öbür (zengin) adam gibi dünya dolusu insanlardan hayırlıdır» buyurdu. Diğer tahric: Bu hadisi Buhari, Nikah ve Rikak bölümlerinde rivayet etmiştir
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4120</td></tr><tr><td>Arabic No</td><td>4120</td></tr><tr><td>Reference</td><td>Book 37 Hadith 21</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
سہل بن سعد ساعدی رضی اللہ عنہ کہتے ہیں کہ ایک شخص رسول اللہ صلی اللہ علیہ وسلم کے پاس سے گزرا تو آپ صلی اللہ علیہ وسلم نے فرمایا: اس شخص کے بارے میں تمہارا کیا خیال ہے ؟ لوگوں نے کہا: جو آپ کی رائے ہے وہی ہماری رائے ہے، ہم تو سمجھتے ہیں کہ یہ شریف لوگوں میں سے ہے، یہ اس لائق ہے کہ اگر کہیں یہ نکاح کا پیغام بھیجے تو اسے قبول کیا جائے، اگر سفارش کرے تو اس کی سفارش قبول کی جائے، اگر کوئی بات کہے تو اس کی بات سنی جائے، نبی اکرم صلی اللہ علیہ وسلم خاموش رہے، پھر ایک دوسرا شخص گزرا تو آپ صلی اللہ علیہ وسلم نے فرمایا: اس شخص کے بارے میں تمہارا کیا خیال ہے؟ لوگوں نے جواب دیا: اللہ کی قسم! یہ تو مسلمانوں کے فقراء میں سے ہے، یہ اس لائق ہے کہ اگر کہیں نکاح کا پیغام دے تو اس کا پیغام قبول نہ کیا جائے، اگر کسی کی سفارش کرے تو اس کی سفارش قبول نہ کی جائے، اور اگر کچھ کہے تو اس کی بات نہ سنی جائے، تو نبی اکرم صلی اللہ علیہ وسلم نے فرمایا: یہ اس پہلے جیسے زمین بھر آدمیوں سے بہتر ہے ۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4120</td></tr><tr><td>Arabic No</td><td>4120</td></tr><tr><td>Reference</td><td>Book 37 Hadith 21</td></tr></tbody></table></div>