## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا مُحَمَّدُ بْنُ رُمْحٍ، أَنْبَأَنَا اللَّيْثُ بْنُ سَعْدٍ، عَنْ يَحْيَى بْنِ سَعِيدٍ، عَنِ ابْنِ حَبَّانَ، - هُوَ مُحَمَّدُ بْنُ يَحْيَى بْنِ حَبَّانَ - عَنْ أَنَسِ بْنِ مَالِكٍ، عَنْ خَالَتِهِ أُمِّ حَرَامٍ بِنْتِ مِلْحَانَ، أَنَّهَا قَالَتْ نَامَ رَسُولُ اللَّهِ صلى الله عليه وسلم يَوْمًا قَرِيبًا مِنِّي ثُمَّ اسْتَيْقَظَ يَبْتَسِمُ فَقُلْتُ يَا رَسُولَ اللَّهِ مَا أَضْحَكَكَ قَالَ ‏"‏ نَاسٌ مِنْ أُمَّتِي عُرِضُوا عَلَىَّ يَرْكَبُونَ ظَهْرَ هَذَا الْبَحْرِ كَالْمُلُوكِ عَلَى الأَسِرَّةِ ‏"‏ ‏.‏ قَالَتْ فَادْعُ اللَّهَ أَنْ يَجْعَلَنِي مِنْهُمْ ‏.‏ قَالَ فَدَعَا لَهَا ثُمَّ نَامَ الثَّانِيَةَ فَفَعَلَ مِثْلَهَا ثُمَّ قَالَتْ مِثْلَ قَوْلِهَا فَأَجَابَهَا مِثْلَ جَوَابِهِ الأَوَّلِ ‏.‏ قَالَتْ فَادْعُ اللَّهَ أَنْ يَجْعَلَنِي مِنْهُمْ قَالَ ‏"‏ أَنْتِ مِنَ الأَوَّلِينَ ‏"‏ ‏.‏ قَالَ فَخَرَجَتْ مَعَ زَوْجِهَا عُبَادَةَ بْنِ الصَّامِتِ غَازِيَةً أَوَّلَ مَا رَكِبَ الْمُسْلِمُونَ الْبَحْرَ مَعَ مُعَاوِيَةَ بْنِ أَبِي سُفْيَانَ فَلَمَّا انْصَرَفُوا مِنْ غَزَاتِهِمْ قَافِلِينَ فَنَزَلُوا الشَّامَ فَقُرِّبَتْ إِلَيْهَا دَابَّةٌ لِتَرْكَبَ فَصَرَعَتْهَا فَمَاتَتْ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2776</td></tr><tr><td>Arabic No</td><td>2776</td></tr><tr><td>Reference</td><td>Book 24 Hadith 24</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
১/২৭৭৬। আনাস ইবনে মালেক (রাঃ) এর খালা উম্মু হারাম বিনতে মিলহান (রাঃ) থেকে বর্ণিত। তিনি বলেন, রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এক দিন আমার ঘরে ঘুমালেন। তিনি হাসতে হাসতে জাগ্রত হলেন। আমি বললাম, ইয়া রাসূলাল্লাহ! আপনাকে কে হাসালো? তিনি বলেনঃ আমার উম্মাতের কতক লোককে সমুদ্রপৃষ্ঠে উপবিষ্ট অবস্থায় আমার সামনে পেশ করা হয়েছে, যেভাবে বাদশাহ সিংহাসনে উপবিষ্ট থাকে। উম্মু হারাম (রাঃ) বলেন, আপনি আল্লাহর নিকট দোয়া করুন যাতে তিনি আমাকে তাদের অন্তর্ভুক্ত করেন। আনাস (রাঃ) বলেন, তিনি তার জন্য দোয়া করলেন। তিনি পুনরায় ঘুমিয়ে পড়লেন, অতঃপর পূর্বের ন্যায় জাগ্রত হলেন। উম্মু হারাম (রাঃ) জিজ্ঞাসা করলে রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম পূর্বানুরূপ জবাব দেন। উম্মু হারাম (রাঃ) বলেন, আপনি আল্লাহর নিকট দোয়া করুন যাতে তিনি আমাকে তাদের অন্তর্ভুক্ত করেন। রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেনঃ তুমি প্রথম দলের অন্তর্ভুক্ত থাকবে। আনাস (রাঃ) বলেন, মুসলিমগণ মুআবিয়া ইবনে আবূ সুফিয়ান (রাঃ)-র নেতৃত্বে সর্বপ্রথম নৌযুদ্ধে রওয়ানা হলে উম্মু হারাম (রাঃ)ও তার স্বামী উবাদা ইবনুস সামিত (রাঃ)-এর সাথে জিহাদে রওয়ানা হলেন। তারা জিহাদ থেকে ফিরে এসে সিরিয়ায় অবতরণ করেন। আরোহণের জন্য তার নিকট একটি জন্তুযান আনা হলো। জন্তুটি তাকে ছুড়ে ফেলে দিলে তিনি তাতে নিহত হন।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2776</td></tr><tr><td>Arabic No</td><td>2776</td></tr><tr><td>Reference</td><td>Book 24 Hadith 24</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
It was narrated from Anas bin Malik that his maternal aunt Umm Harim bint Milhan said:“The Messenger of Allah (ﷺ) slept near me one day, then he woke up smiling. I said: ‘O Messenger of Allah, what has made you smile?’ He said: ‘People of my nation who were shown to me (in my dream) riding across this sea like kings on thrones.’ I said: ‘Supplicate to Allah to make me one of them.’” So he prayed for her. Then he slept again, and did likewise, and she said the same as she said before, and he replied in the same manner. She said: “Pray to Allah to make me one of them,” and he said: “You will be one of the first ones.” He said: “Then she went out with her husband, ‘Ubadah bin Samit, as a fighter, the first time that the Muslims crossed the sea with Mu’awiyah bin Abu Sufyan. On their way back, after they had finished fighting, they stopped in Sham. An animal was brought near for her to ride it, but it threw her off, and she died.”
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2776</td></tr><tr><td>Arabic No</td><td>2776</td></tr><tr><td>Reference</td><td>Book 24 Hadith 24</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Muhammad bin Rumh]; telah memberitakan kepada kami [Al Laits] dari [Yahya bin Sa'id] dari [Ibnu Hibban] yaitu Muhammad bin Yahya bin Habban dari [Anas bin Malik] dari bibinya [Ummi Haram binti Milhan], ia berkata; pada suatu hari Rasulullah shallallahu 'alaihi wasallam tertidur di dekatku, kemudian beliau bangun dan tersenyum, maka aku bertanya; "Wahai Rasulullah, apa yang membuatmu tertawa?" Rasulullah shallallahu 'alaihi wasallam menjawab: 'Sekelompok umatku telah diperlihatkan kepadaku dimana mereka menaiki bahtera lautan ini seperti para raja yang berada di atas singgasana.' Ummi Haram berkata; 'Berdoalah kepada Allah agar menjadikanku bagian dari mereka.' Rasulullah shallallahu 'alaihi wasallam lalu berdo'a, dan kemudian beliau tidur kembali. Kemudian terjadi kembali hal itu untuk kedua kalinya. Rasulullah melakukan hal serupa dan Ummi Haram berkata kembali seperti ucapannya tadi. Rasulullah pun menjawab seperti jawaban yang pertama. Ummi Haram berkata; 'Berdoalah kepada Allah agar menjadikanku bagian dari mereka.' Rasulullah menjawab: 'Engkau termasuk para pemula.' (perawi berkata) menuturkan; 'Ummi Haram keluar dari kediamannya bersama suaminya 'Ubadah bin Shamit untuk berperang, peristiwa pertama kali umat Islam menaiki kapal adalah dengan Muawiyah bin Abu Sufyan. Setelah mereka kembali dari peperangan secara berkelompok, mereka singgah di kota Syam. Namun ketika hewan tunggangannya telah di hadapkan kepada Ummu Haram untuk ia naiki, ia terjatuh hingga kemudian ia meninggal
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2776</td></tr><tr><td>Arabic No</td><td>2776</td></tr><tr><td>Reference</td><td>Book 24 Hadith 24</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Enes bin Mâlik'in teyzesi Ümmü Haram bint-i Milhan (r.anha)'dan; Şöyle demiştir: Resulullah (Sallallahu Aleyhi ve Sellem) bir gün benim yakınımda uyudu. Sonra gülümsiyerek uyandı. Ben: Yâ Resûlallah! Seni ne güldürdü? diye sordum. Resul-i Ekrem (Sallallahu Aleyhi ve Sellem): «Rü'yâmda bana ümmetimden bir grup şu deniz üstünde padişahların tahtlarına kuruldukları gibi gemilere binerek (Allah yolunda savaşa) gittikleri durumda bana gösterildi (de ona güldüm)» buyurdu. Ümmü Haram: (Yâ Resûlallah!) Benim de o deniz gazilerinden olmakhğım için Allah'a duâ et, diye ricada bulundu. Enes demiştir ki: Resul-i Ekrem (Sallallahu Aleyhi ve Sellem) onun için duâ etti. Sonra Resul-i Ekrem (Sallallahu Aleyhi ve Sellem) tekrar uyudu. Bir süre sonra yine gülümsiyerek uyandı. Ümmü Haram da (ilk) sözünün mislini söyledi. Resul-i Ekrem (Sallallahu Aleyhi ve Sellem) de birinci cevâbının mislini ona söyledi. Ümmü Haram da: (Yâ Resulallah!) Beni o gazilerden eylemesi için Allah'a duâ et, dedi. Resul-i Ekrem (Sallallahu Aleyhi ve Sellem) (ona): «Sen birincilerdensin» buyurdu. Enes demiştir ki: Hakikaten Ümmü Haram, kocası Ubâde bin es-Sâmıt ile beraber Muâviye bin Ebî Süfyân'ın kumandasında (ve Şâm valiliği zamanında) müslümanların düzenledikleri ilk deniz savaşına katıldılar. Müslümanlar savaşlarından (zaferle) dönüp (denizden) Şâm (toprakların) a çıkınca Ümmü Haram binsin diye kendisine bir hayvan (katır) yaklaştırıldı. (Ümmü Haram bineceği esnada) hayvan onu (yere) düşürdü ve o böylece şehid oldu
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2776</td></tr><tr><td>Arabic No</td><td>2776</td></tr><tr><td>Reference</td><td>Book 24 Hadith 24</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
انس بن مالک رضی اللہ عنہ اپنی خالہ ام حرام بنت ملحان رضی اللہ عنہا سے روایت کرتے ہیں وہ کہتی ہیں کہ رسول اللہ صلی اللہ علیہ وسلم ایک روز میرے قریب سوئے، پھر آپ صلی اللہ علیہ وسلم مسکراتے ہوئے بیدار ہوئے، میں نے پوچھا: اللہ کے رسول! آپ کس بات پر مسکرا رہے ہیں؟ آپ صلی اللہ علیہ وسلم نے فرمایا: میری امت کے کچھ لوگ میرے سامنے لائے گئے جو اس سمندر کے اوپر اس طرح سوار ہو رہے ہیں جیسے بادشاہ تختوں پر بیٹھتے ہیں ، ام حرام رضی اللہ عنہا نے کہا: اللہ سے آپ دعا کر دیجئیے کہ وہ مجھے بھی ان ہی لوگوں میں سے کر دے، انس رضی اللہ عنہ کہتے ہیں کہ آپ صلی اللہ علیہ وسلم نے ان کے لیے دعا فرما دی، پھر آپ صلی اللہ علیہ وسلم دوبارہ سو گئے، پھر ویسے ہی ہوا، آپ اٹھے تو ہنستے ہوئے، اور ام حرام رضی اللہ عنہا نے وہی پوچھا جو پہلی بار پوچھا تھا، اور آپ صلی اللہ علیہ وسلم نے انہیں وہی جواب دیا جو پہلی بار دیا تھا، اس بار بھی انہوں نے عرض کیا: آپ اللہ سے دعا کر دیجئیے کہ وہ مجھے بھی انہی لوگوں میں سے کر دے، آپ صلی اللہ علیہ وسلم نے فرمایا: تم پہلے لوگوں میں سے ہو ۔ انس رضی اللہ عنہ بیان کرتے ہیں کہ وہ اپنے شوہر عبادہ بن صامت رضی اللہ عنہ کے ہمراہ جہاد کے لیے نکلیں، یہ پہلا موقع تھا کہ معاویہ بن ابی سفیان رضی اللہ عنہما کے ساتھ مسلمان بحری جہاد پر گئے تھے چنانچہ جب لوگ جہاد سے لوٹ رہے تھے تو شام میں رکے، ام حرام رضی اللہ عنہا کی سواری کے لیے ایک جانور لایا گیا، جس نے انہیں گرا دیا، اور وہ فوت ہو گئیں ۱؎۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>2776</td></tr><tr><td>Arabic No</td><td>2776</td></tr><tr><td>Reference</td><td>Book 24 Hadith 24</td></tr></tbody></table></div>