## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا أَيُّوبُ بْنُ مُحَمَّدٍ الرَّقِّيُّ، حَدَّثَنَا مُعَمَّرُ بْنُ سُلَيْمَانَ، حَدَّثَنَا عَبْدُ اللَّهِ بْنُ بِشْرٍ، عَنِ الأَعْمَشِ، عَنْ عَمْرِو بْنِ مُرَّةَ، عَنْ يَحْيَى بْنِ الْجَزَّارِ، عَنِ ابْنِ أُخْتِ، زَيْنَبَ امْرَأَةِ عَبْدِ اللَّهِ عَنْ زَيْنَبَ، قَالَتْ كَانَتْ عَجُوزٌ تَدْخُلُ عَلَيْنَا تَرْقِي مِنَ الْحُمْرَةِ وَكَانَ لَنَا سَرِيرٌ طَوِيلُ الْقَوَائِمِ وَكَانَ عَبْدُ اللَّهِ إِذَا دَخَلَ تَنَحْنَحَ وَصَوَّتَ فَدَخَلَ يَوْمًا فَلَمَّا سَمِعَتْ صَوْتَهُ احْتَجَبَتْ مِنْهُ فَجَاءَ فَجَلَسَ إِلَى جَانِبِي فَمَسَّنِي فَوَجَدَ مَسَّ خَيْطٍ فَقَالَ مَا هَذَا فَقُلْتُ رُقًى لِي فِيهِ مِنَ الْحُمْرَةِ فَجَذَبَهُ وَقَطَعَهُ فَرَمَى بِهِ وَقَالَ لَقَدْ أَصْبَحَ آلُ عَبْدِ اللَّهِ أَغْنِيَاءَ عَنِ الشِّرْكِ سَمِعْتُ رَسُولَ اللَّهِ ـ صلى الله عليه وسلم ـ يَقُولُ ‏"‏ إِنَّ الرُّقَى وَالتَّمَائِمَ وَالتِّوَلَةَ شِرْكٌ ‏"‏ ‏.‏ قُلْتُ فَإِنِّي خَرَجْتُ يَوْمًا فَأَبْصَرَنِي فُلاَنٌ فَدَمَعَتْ عَيْنِي الَّتِي تَلِيهِ فَإِذَا رَقَيْتُهَا سَكَنَتْ دَمْعَتُهَا وَإِذَا تَرَكْتُهَا دَمَعَتْ ‏.‏ قَالَ ذَاكِ الشَّيْطَانُ إِذَا أَطَعْتِيهِ تَرَكَكِ وَإِذَا عَصَيْتِيهِ طَعَنَ بِإِصْبَعِهِ فِي عَيْنِكِ وَلَكِنْ لَوْ فَعَلْتِ كَمَا فَعَلَ رَسُولُ اللَّهِ ـ صلى الله عليه وسلم ـ كَانَ خَيْرًا لَكِ وَأَجْدَرَ أَنْ تَشْفِينَ تَنْضَحِينَ فِي عَيْنِكِ الْمَاءَ وَتَقُولِينَ ‏"‏ أَذْهِبِ الْبَاسْ رَبَّ النَّاسْ اشْفِ أَنْتَ الشَّافِي لاَ شِفَاءَ إِلاَّ شِفَاؤُكَ شِفَاءً لاَ يُغَادِرُ سَقَمًا ‏"‏ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3530</td></tr><tr><td>Arabic No</td><td>3530</td></tr><tr><td>Reference</td><td>Book 31 Hadith 95</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
১/৩৫৩০। আবদুল্লাহ (রাঃ)-র স্ত্রী যয়নব (রাঃ) থেকে বর্ণিত। তিনি বলেন, এক বৃদ্ধা আমাদের একানে আসতো এবং সে চমপ্রদাহের ঝাড়ফুঁক করতো। আমাদের একটি লম্বা পা-বিশিষ্ট খাট ছিল। আবদুললাহ (রাঃ) ঘরে প্রবেশের সময় সশব্দে কাশি দিতেন। একদিন তিনি আমার নিকট প্রবেশ করলেন। সে তার গলার আওয়াজ শুনতে পেয়ে একটু আড়াল হলো। তিনি এসে আমার পাশে বসলেন এবং আমাকে স্পর্শ করলে এক গাছি সুতার স্পর্শ পেলেন। তিনি জিজ্ঞেস করলেন, এটা কী? আমি বললাম, চর্মপ্রদাহের জন্য সূতা পড়া বেঁধেছি। তিনি সেটা আমার গলা থেকে টেনে ছিঁড়ে ফেললেন এবং তা ছুঁড়ে ফেলে দিয়ে বললেন, আবদুল্লাহর পরিবার শিরকমুক্ত হলো। আমি রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম কে বলতে শুনেছিঃ‘‘মন্ত্র, রক্ষাকবচ, গিটযুক্ত মন্ত্রপূত সূতা হলো শিরকের অন্তর্ভুক্ত’’। আমি বললাম, আমি একদিন বাইরে যাচ্ছিলাম, তখন অমুক লোক আমাকে দেখে ফেললো। আমার যে চোখের দৃষ্টি তার উপর পড়লো তা দিয়ে পানি ঝরতে লাগলো। আমি তার মন্ত্র পড়ে ফুঁ দিলে তা থেকে পানি ঝরা বন্ধ হলো এবং মন্ত্র পড়া বন্ধ করলেই আবার পানি পড়তে লাগলো। তিনি বলেন, এটা শয়তানের কাজ। তুমি শয়তানের আনুগত্য করলে সে তোমাকে রেহাই দেয় এবং তার আনুগত্য না করলে সে তোমার চোখে তার আঙ্গুলের খোঁচা মারে। কিন্তু তুমি যদি তাই করতে, যা রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম করেছিলেন, তবে তা তোমার জন্য উপাকারী হতো এবং আরোগ্য লাভেও অধিক সহায়ক হতো।। তুমি নিন্নোক্ত দোয়া পড়ে পানিতে ফুঁ দিয়ে তা তোমার চোখে ছিটিয়ে দাওঃ ‘‘আযহিবিল বাস রব্বান নাস, ইশফি আনতাশ শাফী, লা শিফাআ ইল্লা শিফাউকা শিফাআন লা ইউগাদিরু সাকামান’’ ( হে মানুষের প্রভু! কষ্ট দূর করে দাও, আরোগ্য দান করো, তুমিই আরোগ্য দানকারী, তোমার আরোগ্যদান ছাড়া আরোগ্য লাভ করা যায় না, এমনভাবে আরোগ্য দান করো যা কোন রোগকে ছাড়ে না)।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3530</td></tr><tr><td>Arabic No</td><td>3530</td></tr><tr><td>Reference</td><td>Book 31 Hadith 95</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
It was narrated that Zainab said:“There was an old woman who used to enter upon us and perform Ruqyah from erysipelas: Contagious disease which causes fever and leaves a red coloration of the skin. We had a bed with long legs, and when ‘Abdullah entered he would clear his throat and make noise. He entered one day and when she heard his voice she veiled herself from him. He came and sat beside me, and touched me, and he found a sting. He said: ‘What is this?’ I said: ‘An amulet against erysipelas.’ He pulled it, broke it and threw it away, and said: ‘The family of ‘Abdullah has no need of polytheism.’ I heard the Messenger of Allah (ﷺ) say: “Ruqyah (i.e., which consist of the names of idols and devils etc.), amulets and Tiwalah (charms) are polytheism.’” “I said: ‘I went out one day and so-and-so looked at me, and my eye began to water on the side nearest him. When I recited Ruqyah for it, it stopped, but if I did not recite Ruqyah it watered again.’ He said: ‘That is Satan, if you obey him he leaves you alone but if you disobey him he pokes you with his finger in your eye. But if you do what the Messenger of Allah (ﷺ) used to do, that will be better for you and more effective in healing. Sprinkle water in your eye and say: Adhhibil-bas Rabban-nas, washfi Antash-Shafi, la shifa’a illa shafi’uka, shafi’an la yughadiru saqaman (Take away the pain, O Lord of mankind, and grant healing, for You are the Healer, and there is no healing but Your healing that leaves no trace of sickness).’”
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3530</td></tr><tr><td>Arabic No</td><td>3530</td></tr><tr><td>Reference</td><td>Book 31 Hadith 95</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Ayyub bin Muhammad Ar Raqi] telah menceritakan kepada kami [Mu'ammar bin Sulaiman] telah menceritakan kepada kami [Abdullah bin Bisyr] dari [Al A'masy] dari ['Amru bin Murrah] dari [Yahya bin Al Jazzar] dari puteri saudarinya [Zainab] isterinya Abdullah, dari [Zainab] dia berkata, "Seorang wanita tua menemui kami hendak menjampi-jampi dari penyakit demam. Dan kami memiliki dipan yang panjang kaki-kakinya, dan apabila Abdullah hendak masuk maka ia akan berdehem dan bersuara. Suatu hari ia masuk, ketika wanita tua itu mendengar suaranya, maka ia bersembunyi. Kemudian Abdullah datang dan duduk di sampingku dan membelaiku, ternyata ia menyentuh suatu jahitan benang, maka dia berkata, 'Apa ini? ' aku lalu menjawab, 'Jimat, di dalamnya terdapat jampi-jampiku untuk pengobatan penyakit demam." [Abdullah] lalu menariknya dengan paksa, kemudian ia putus dan membuangnya seraya berkata, "Sungguh saat ini keluarga Abdullah telah melakukan praktek kesyirikkan, saya mendengar Rasulullah shallallahu 'alaihi wasallam bersabda: "Sesungguhnya jampi-jampi, jimat dan pelet adalah syirik." Aku berkata, "Suatu hari aku keluar, lantas si fulan memandangiku hingga mataku selalu berair, jika mataku di jampi maka air matanya akan berhenti, namun jika tidak di jampi maka ia akan selalu berair." Abdullah berkata, "Itu adalah (perbuatan) setan, jika kamu mentaatinya maka setan akan meninggalkanmu, tapi jika kamu tidak mentaatinya maka ia akan menusuk matamu dengan jari-jarinya. Akan tetapi sekiranya kamu melakukan apa yang pernah di lakukan oleh Rasulullah shallallahu 'alaihi wasallam maka itu akan lebih baik bagimu dan lebih layak mendapatkan kesembuhan, kamu mengguyur kedua matamu dengan air sambil membaca: 'ADZHIBIL BA'SA RABBANNASI ISYFI ANTA SYAAFI LAA SYIFAA'A ILLA SYIFAA'UKA SYIFAA'AN LAA YUGHAADIRU SAQAMA (Hilangkanlah kesusahan, wahai Rabb manusia, sembuhkanlah. Sebab Engkaulah Maha penyembuh, yang tidak ada kesembuhan melainkan kesembuhan dari-Mu, kesembuhan yang tidak meninggalkan rasa sakit)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3530</td></tr><tr><td>Arabic No</td><td>3530</td></tr><tr><td>Reference</td><td>Book 31 Hadith 95</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Abdullah (bin Mes'ud)'un zevcesi Zeyneb (r.anha)'dan; Şöyle demiştir: Yaşlı bir kadın yanımıza girip humre (denilen bir nevi veba) hastalığına okurdu. Ayakları vKun bir divanımız vardı. (Eşim) Abdmllah ev'e gireceği zaman (geldiğini sezdirmek için) öksürüp seslenirdi. Günün birinde Abdullah ev'e girdi. Okuyucu yaşlı kadın onun s«sîai duyunca ondan saklandı. Abdallah da gelip yanıma oturdu ve eli bana dokununca bir ipliğe değdi. Sonra: Bu nedir? dedi. Ben de : Hunrre (denilen) hastalığa benim için bu ipliğe okundu, dedim. Bunun ürerine Abdullah ipliği çakip keserek attı ve: Abdullah'ın ev halkmıa şirk sayılan bir şeyi kullanmaya ihtiyaçları yoktur. Ben, Resulullah (Sallallahu Aleyhi ve Sellem)'den: «Rukyeler, nazarlıklar ve büyü şüphesiz bir şirk (yâni Allah'a ortak koşmak)tır» buyurduğunu işittim, dedi. Ben: Bir gün dışarı çıktım da falan adam beni gördü. Bunun üzerine onun tarafındaki gözüm yaşardı. O günden beri gözüme okutturduğum zaman gözümün yaşı durur ve okutmayı bıraktığım zaman gözüm yaşarır, dedim. Abdullah: O, şeytandır. Sen ona itaat ettiğin zaman seni bırakır ve ona isyan ettiğin zaman parmağı ile senin gözüne dürtüyor. Lâkin eğer sen, Resulullah (Sallallahu Aleyhi ve Sellem)'in yaptığı gibi yapsaydın senin için hayırlı ve şifâya kavuşman için çok münâsip olurdu: Gözüne su serpip şöyle dersin: Bu hastalığı gider, Ey insanların Rabbi. Şifâ ver. Ancak sen şifâ verirsin. Senin şifandan başka hiçbir şifâ yoktur. Hiçbir hastalık bırakmayan bir şifâ ihsan buyur, dedi. Not: Zevaid'de şöyle denilmiştir: Ebü Davud bu hadisin bir kısnunı rivayet etmiştir. Hakim de el-Müstedrek'te bunu rivayet etmiştir
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3530</td></tr><tr><td>Arabic No</td><td>3530</td></tr><tr><td>Reference</td><td>Book 31 Hadith 95</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
زینب زوجہ عبداللہ بن مسعود رضی اللہ عنہ کہتی ہیں کہ ہمارے پاس ایک بڑھیا آیا کرتی تھیں، وہ «حمرہ» ۱؎ کا دم کرتی تھیں، ہمارے پاس بڑے پایوں کی ایک چارپائی تھی، اور عبداللہ بن مسعود رضی اللہ عنہ کا معمول تھا کہ جب گھر آتے تو کھنکھارتے اور آواز دیتے، ایک دن وہ گھر کے اندر آئے جب اس بڑھیا نے ان کی آواز سنی تو ان سے پردہ کر لیا، عبداللہ بن مسعود رضی اللہ عنہ آ کر میری ایک جانب بیٹھ گئے اور مجھے چھوا تو ان کا ہاتھ ایک گنڈے سے جا لگا، پوچھا: یہ کیا ہے؟ میں نے عرض کیا: یہ سرخ بادے ( «حمرہ» ) کے لیے دم کیا ہوا گنڈا ہے، یہ سن کر انہوں نے اسے کھینچا اور کاٹ کر پھینک دیا اور کہا: عبداللہ کے گھرانے کو شرک کی حاجت نہیں ہے، میں نے رسول اللہ صلی اللہ علیہ وسلم کو فرماتے سنا ہے: دم، تعویذ، گنڈے اور ٹونا شرک ہیں ۱؎، ایک دن میں باہر نکلی تو مجھ پر فلاں شخص کی نظر پڑ گئی، تو میری اس آنکھ سے جو اس سے قریب تر تھی آنسو بہہ نکلے، جب میں اس پر دم کرتی تو اس کے آنسو رک جاتے، اور جب میں دم کرنا چھوڑ دیتی تو آنسو بہنے لگتے، انہوں نے کہا: یہی تو شیطان ہے، جب تم اس کی اطاعت کرتی ہو تو وہ تم کو چھوڑ دیتا ہے، اور جب تم اس کی نافرمانی کرتی ہو تو وہ تمہاری آنکھ میں اپنی انگلی چبھو دیتا ہے، لیکن اگر تم وہ عمل کرتیں جو رسول اللہ صلی اللہ علیہ وسلم نے ایسے موقع پر کیا تو تمہارے حق میں بہتر ہوتا، اور تم ٹھیک ہو جاتیں، تم اپنی آنکھ میں پانی کے چھینٹے مارا کرو، اور یہ دعا پڑھا کرو: «أذهب الباس رب الناس اشف أنت الشافي لا شفاء إلا شفاؤك شفاء لا يغادر سقما» اے لوگوں کے رب، مصیبت دور فرما، شفاء عطا کر، تو ہی شفاء عطا کرنے والا ہے، تیری شفاء کے سوا اور کوئی شفاء ہے بھی نہیں، ایسی شفاء دے کہ کوئی بیماری باقی رہ نہ جائے ۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Daif</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3530</td></tr><tr><td>Arabic No</td><td>3530</td></tr><tr><td>Reference</td><td>Book 31 Hadith 95</td></tr></tbody></table></div>