## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا أَبُو بَكْرِ بْنُ خَلاَّدٍ الْبَاهِلِيُّ، حَدَّثَنَا أَبُو عَامِرٍ، عَنْ عِيسَى بْنِ حَفْصِ بْنِ عَاصِمِ بْنِ عُمَرَ بْنِ الْخَطَّابِ، حَدَّثَنِي أَبِي قَالَ، كَنَّا مَعَ ابْنِ عُمَرَ فِي سَفَرٍ فَصَلَّى بِنَا ثُمَّ انْصَرَفْنَا مَعَهُ وَانْصَرَفَ ‏.‏ قَالَ فَالْتَفَتَ فَرَأَى أُنَاسًا يُصَلُّونَ فَقَالَ مَا يَصْنَعُ هَؤُلاَءِ قُلْتُ يُسَبِّحُونَ ‏.‏ قَالَ لَوْ كُنْتُ مُسَبِّحًا لأَتْمَمْتُ صَلاَتِي يَا ابْنَ أَخِي إِنِّي صَحِبْتُ رَسُولَ اللَّهِ ـ صلى الله عليه وسلم ـ فَلَمْ يَزِدْ عَلَى رَكْعَتَيْنِ فِي السَّفَرِ حَتَّى قَبَضَهُ اللَّهُ ثُمَّ صَحِبْتُ أَبَا بَكْرٍ فَلَمْ يَزِدْ عَلَى رَكْعَتَيْنِ ثُمَّ صَحِبْتُ عُمَرَ فَلَمْ يَزِدْ عَلَى رَكْعَتَيْنِ ثُمَّ صَحِبْتُ عُثْمَانَ فَلَمْ يَزِدْ عَلَى رَكْعَتَيْنِ حَتَّى قَبَضَهُمُ اللَّهُ وَاللَّهُ يَقُولُ ‏(لَقَدْ كَانَ لَكُمْ فِي رَسُولِ اللَّهِ أُسْوَةٌ حَسَنَةٌ ‏)‏ ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1071</td></tr><tr><td>Arabic No</td><td>1071</td></tr><tr><td>Reference</td><td>Book 5 Hadith 269</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
১/১০৭১। হাফস্ ইবনু আসেম (রহ ) বলেন, আমরা এক সফরে ইবনু উমার (রাঃ) এর সাথে ছিলাম। তিনি আমাদের নিয়ে সালাত (নামায/নামাজ) পড়েন। অতঃপর আমরা সেখান থেকে তার সাথে ফিরে আসি। রাবী বলেন, তিনি একদল লোককে সালাত আদায় করতে দেখে বলেন, ঐ সকল লোক কী করছে? আমি বললাম, তারা নফল সালাত পড়ছে। তিনি বলেন, সফরে নফল সালাত পড়া জরুরী মনে করলে, আমি আমার ফরয সালাত পুরাটাই পড়তাম। হে ভাতিজা! আমি রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর সফরসঙ্গী ছিলাম। তিনি তাঁর ইন্তেকাল পর্যন্ত সফরে দু রাকআতের অধিক সালাত পড়েননি। তারপর আমি আবূ বাকর (রাঃ) এর সফরসঙ্গী ছিলাম, তিনিও দু রাকআতের অধিক সালাত পড়েননি। এরপর আমি উমার (রাঃ) এর সফরসঙ্গী ছিলাম এবং তিনিও দু রাকআতের অধিক সালাত পড়েননি। অতঃপর আমি উসমান (রাঃ) এর সফরসঙ্গী ছিলাম, তিনিও দু রাকআতের অধিক সালাত পড়েননি। এই অবস্থায় তারা ইন্তেকাল করেন। আল্লাহ তাআলা বলেন, রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এর মধ্যে অবশ্যি তোমাদের জন্য রয়েছে উত্তম আদর্শ (সূরাহ আহযাব: ২১)।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1071</td></tr><tr><td>Arabic No</td><td>1071</td></tr><tr><td>Reference</td><td>Book 5 Hadith 269</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
It was narrated from ‘Isa bin Hafs bin ‘Asim bin ‘Umar bin Khattab that his father told him:“We were with Ibn ‘Umar on a journey, and he led us in prayer. Then we finished with him and he finished turning around, and saw some people praying. He said: ‘What are these people doing?’ I said: ‘Glorifying Allah.’* He said: ‘If I wanted to glorify Allah (perform voluntary prayer) I would have completed my prayer. O son of my brother! I accompanied the Messenger of Allah (ﷺ) and he never prayed more than two Rak’ah when he was traveling, until Allah took his soul. Then I accompanied Abu Bakr and he never prayed more than two Rak’ah (when he was traveling), until Allah took his soul. Then I accompanied ‘Umar and he never prayed more than two Rak’ah, until Allah took his soul. Then I accompanied ‘Uthman and he never prayed more than two Rak’ah, until Allah took his soul. Allah says: ‘Indeed in the Messenger of Allah (Muhammad (ﷺ)) you have a good example to follow.’” [33:21] * Meaning, they were offering voluntary prayer
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1071</td></tr><tr><td>Arabic No</td><td>1071</td></tr><tr><td>Reference</td><td>Book 5 Hadith 269</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Abu Bakar bin Khallad Al Bahili] berkata, telah menceritakan kepada kami [Abu Amir] dari [Isa bin Hafsh bin Ashim bin Umar Ibnul Khaththab] berkata, telah menceritakan kepadaku [Bapakku] ia berkata, "Kami bersama [Ibnu Umar] dalam sebuah perjalanan, lalu ia shalat bersama kami, kemudian kami beranjak pergi bersamanya. " Ia berkata lagi, "Ibnu Umar menoleh dan melihat beberapa orang melaksanakan shalat, lalu Ibnu Umar bertanya, "Apa yang dilakukan oleh orang-orang itu?" aku menjawab, "Mereka melaksanakan shalat sunnah. " Ibnu Umar berkata, "Wahai putera saudaraku, jika aku melaksanakan shalat sunnah maka akan aku sempurnakan. Aku pernah menemani Rasulullah shallallahu 'alaihi wasallam, dan beliau tidak pernah melebihkan dari dua raka'at ketika safar hingga Allah mewafatkannya. Kemudian aku menemani Abu Bakar, dan ia juga tidak melebihkan dari dua raka'at. Kemudian aku menemani Umar, dan ia juga tidak melebihkan dari dua raka'at. Kemudian aku menemani Utsman, dan ia juga tidak melebihkan dari dua raka'at hingga Allah mewafatkannya. Demi Allah, ia mengatakan, "Sungguh pada diri Rasulullah shallallahu 'alaihi wasallam ada teladan yang baik
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1071</td></tr><tr><td>Arabic No</td><td>1071</td></tr><tr><td>Reference</td><td>Book 5 Hadith 269</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Hafs bin Asım bin Ömer bin el-Hattab (r.a.)'den; şöyle demiştir: Biz yolculukta (amcam Abdullah) bin Ömer (r.a.)'in beraberindeydik. İbn-i Ömer (r.a.) bize namaz kıldırdı. Farz'dan sonra (sünnet kılmadan) kendisi de, biz de dönüp gittik. İbn-i Ömer (r.a.) dönüşünde cemaatin bir kısmının (kalkıp) namaz'a durduklarını görünce: Bunlar ne yapıyorlar? diye sordu. Ben de: Sünnet kılıyorlar, dedim. İbn-i Ömer (r.a.): 'Eğer ben (yolculukta) Sünnet kılmış olsaydım farzımı (kasırlı değil) tam kılardım. Ey kardeşimin oğlu! Ben Resulullah (Sallallahu Aleyhi ve Sellem) ile arkadaşlık ettim. Vefat edinceye kadar yolculukta iki rek'at (farz) dan fazla (sünnet namaz) kılmadı. Sonra Ebu Bekir (r.a.) ile arkadaşlık ettim. O da iki rekat'ten fazla kılmadı. Sonra Ömer (r.a.) ile arkadaşlık ettim. Kendisi de iki rek'at'ten fazla kılmadı. Ondan sonra Osman (r.a.) ile arkadaşlık ettim. O da iki rek'at'ten fazla kılmadı. Bu zatlar vefat edinceye kadar durum böyleydi. Allah Teala da: لقد كان لكم في رسول الله أسوة حسنة «Ey Mu'minler! Andolsun ki sizin için Resulullah en güzel örnektir.» [Ahzab 21] buyuruyor' dedi." Diğer tahric: Buhari, Müslim, Ebu Davud, Nesai, Malik ve Beyhaki
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1071</td></tr><tr><td>Arabic No</td><td>1071</td></tr><tr><td>Reference</td><td>Book 5 Hadith 269</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حفص بن عاصم بن عمر بن خطاب کہتے ہیں کہ ہم ابن عمر رضی اللہ عنہما کے ساتھ ایک سفر میں تھے، انہوں نے ہمیں نماز پڑھائی، پھر ہم ان کے ساتھ لوٹے، انہوں نے مڑ کر دیکھا تو کچھ لوگ نماز پڑھ رہے تھے، پوچھا: یہ لوگ کیا کر رہے ہیں؟ میں نے کہا: سنت پڑھ رہے ہیں، انہوں نے کہا: اگر مجھے نفلی نماز ( سنت ) پڑھنی ہوتی تو میں پوری نماز پڑھتا، میرے بھتیجے! میں رسول اللہ صلی اللہ علیہ وسلم کے ساتھ رہا، آپ صلی اللہ علیہ وسلم نے سفر میں دو رکعت سے زیادہ نہ پڑھی، یہاں تک کہ اللہ تعالیٰ نے آپ کو وفات دے دی، پھر میں ابوبکر رضی اللہ عنہ کے ساتھ رہا، انہوں نے بھی دو رکعت سے زیادہ نہ پڑھی، پھر میں عمر رضی اللہ عنہ کے ساتھ رہا، تو انہوں نے بھی دو رکعت سے زیادہ نہ پڑھی، پھر میں عثمان رضی اللہ عنہ کے ساتھ رہا تو انہوں نے بھی دو رکعت سے زیادہ نہ پڑھی، اور پوری زندگی ان سب لوگوں کا یہی عمل رہا یہاں تک کہ اللہ تعالیٰ نے ان کو وفات دے دی، اور اللہ تعالیٰ فرماتا ہے: «لقد كان لكم في رسول الله أسوة حسنة» تمہارے لیے رسول اللہ صلی اللہ علیہ وسلم کی زندگی میں بہترین نمونہ ہے ( سورۃ الاحزاب: ۲۱ ) ۱؎۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>Grade</th> <th></th> </tr> </thead> <tbody> <tr><td>Sahih</td><td>Al-Albani</td></tr><tr><td>Sahih</td><td>Muhammad Fouad Abd al-Baqi</td></tr><tr><td>Sahih</td><td>Shuaib Al Arnaut</td></tr><tr><td>Hasan Or Sahih</td><td>Zubair Ali Zai</td></tr></tbody></table><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1071</td></tr><tr><td>Arabic No</td><td>1071</td></tr><tr><td>Reference</td><td>Book 5 Hadith 269</td></tr></tbody></table></div>