## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا مُعَاذُ بْنُ فَضَالَةَ، حَدَّثَنَا هِشَامٌ، عَنْ يَحْيَى، عَنْ هِلاَلِ بْنِ أَبِي مَيْمُونَةَ، حَدَّثَنَا عَطَاءُ بْنُ يَسَارٍ، أَنَّهُ سَمِعَ أَبَا سَعِيدٍ الْخُدْرِيَّ ـ رضى الله عنه ـ يُحَدِّثُ أَنَّ النَّبِيَّ صلى الله عليه وسلم جَلَسَ ذَاتَ يَوْمٍ عَلَى الْمِنْبَرِ وَجَلَسْنَا حَوْلَهُ فَقَالَ ‏"‏ إِنِّي مِمَّا أَخَافُ عَلَيْكُمْ مِنْ بَعْدِي مَا يُفْتَحُ عَلَيْكُمْ مِنْ زَهْرَةِ الدُّنْيَا وَزِينَتِهَا ‏"‏‏.‏ فَقَالَ رَجُلٌ يَا رَسُولَ اللَّهِ أَوَيَأْتِي الْخَيْرُ بِالشَّرِّ فَسَكَتَ النَّبِيُّ صلى الله عليه وسلم فَقِيلَ لَهُ مَا شَأْنُكَ تُكَلِّمُ النَّبِيَّ صلى الله عليه وسلم وَلاَ يُكَلِّمُكَ فَرَأَيْنَا أَنَّهُ يُنْزَلُ عَلَيْهِ‏.‏ قَالَ ـ فَمَسَحَ عَنْهُ الرُّحَضَاءَ فَقَالَ ‏"‏ أَيْنَ السَّائِلُ ‏"‏ وَكَأَنَّهُ حَمِدَهُ‏.‏ فَقَالَ ‏"‏ إِنَّهُ لاَ يَأْتِي الْخَيْرُ بِالشَّرِّ، وَإِنَّ مِمَّا يُنْبِتُ الرَّبِيعُ يَقْتُلُ أَوْ يُلِمُّ إِلاَّ آكِلَةَ الْخَضْرَاءِ، أَكَلَتْ حَتَّى إِذَا امْتَدَّتْ خَاصِرَتَاهَا اسْتَقْبَلَتْ عَيْنَ الشَّمْسِ، فَثَلَطَتْ وَبَالَتْ وَرَتَعَتْ، وَإِنَّ هَذَا الْمَالَ خَضِرَةٌ حُلْوَةٌ، فَنِعْمَ صَاحِبُ الْمُسْلِمِ مَا أَعْطَى مِنْهُ الْمِسْكِينَ وَالْيَتِيمَ وَابْنَ السَّبِيلِ ـ أَوْ كَمَا قَالَ النَّبِيُّ صلى الله عليه وسلم ـ وَإِنَّهُ مَنْ يَأْخُذُهُ بِغَيْرِ حَقِّهِ كَالَّذِي يَأْكُلُ وَلاَ يَشْبَعُ، وَيَكُونُ شَهِيدًا عَلَيْهِ يَوْمَ الْقِيَامَةِ ‏"‏‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1465</td></tr><tr><td>Arabic No</td><td>1465</td></tr><tr><td>Reference</td><td>Book 24 Hadith 67</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
আবূ সাঈদ খুদরী (রাঃ) থেকে বর্ণিত। তিনি বলেন, একদা নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম মিম্বরে বসলেন এবং আমরা তাঁর আশেপাশে বসলাম। তিনি বললেনঃ আমার পরে তোমাদের ব্যাপারে আমি যা আশঙ্কা করছি তা হলো এই যে দুনিয়ার চাকচিক্য ও সৌন্দর্য (ধন-সম্পদ) তোমাদের সামনে খুলে দেয়া হবে। এক সাহাবী বললেন, হে আল্লাহর রাসূল! কল্যাণ কি কখনো অকল্যাণ বয়ে আনে? এতে নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম নীরব হলেন। প্রশ্নকারীকে বলা হলো, তোমার কী হয়েছে? তুমি নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম -এর সাথে কথা বলছ, কিন্তু তিনি তোমাকে জওয়াব দিচ্ছেন না? তখন আমরা অনুভব করলাম যে, নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম -এর উপর ওয়াহী নাযিল হচ্ছে। বর্ণনাকারী বলেন, এরপর তিনি তাঁর ঘাম মুছলেন এবং বললেনঃ প্রশ্নকারী কোথায়? যেন তার প্রশ্নকে প্রশংসা করে বললেন, কল্যাণ কখনো অকল্যাণ বয়ে আনে না। অবশ্য বসন্ত মৌসুম যে ঘাস উৎপন্ন করে তা (সবটুকুই সুস্বাদু ও কল্যাণকর বটে তবে) অনেক সময় হয়ত (ভোজনকারী প্রাণীর) জীবন নাশ করে অথবা তাকে মৃত্যুর কাছাকাছি নিয়ে যায়। তবে ঐ তৃণভোজী জন্তু, যে পেট ভরে খাওয়ার পর সূর্যের তাপ গ্রহণ করে এবং মল ত্যাগ করে, প্রস্রাব করে এবং পুনরায় চলে (সেই মৃত্যু থেকে রক্ষা পায় তেমনি) এই সম্পদ হলো আকর্ষণীয় সুস্বাদু। কাজেই সে-ই ভাগ্যবান মুসলিম, যে এই সম্পদ থেকে মিসকীন, ইয়াতীম ও মুসাফিরকে দান করে অথবা নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম যেরূপ বলেছেন, আর যে ব্যক্তি এই সম্পদ অন্যায়ভাবে উপার্জন করে, সে ঐ ব্যক্তির ন্যায়, যে খেতে থাকে এবং তার পেট ভরে না। ক্বিয়ামাত (কিয়ামত) দিবসে ঐ সম্পদ তার বিপক্ষে সাক্ষ্য দিবে। (আধুনিক প্রকাশনীঃ ১৩৭১, ইসলামিক ফাউন্ডেশনঃ ১৩৭৭)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1465</td></tr><tr><td>Arabic No</td><td>1465</td></tr><tr><td>Reference</td><td>Book 24 Hadith 67</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated Abu Sa'id Al-Khudri:Once the Prophet (ﷺ) sat on a pulpit and we sat around him. Then he said, "The things I am afraid of most for your sake (concerning what will befall you after me) is the pleasures and splendors of the world and its beauties which will be disclosed to you." Somebody said, "O Allah's Messenger (ﷺ)! Can the good bring forth evil?" The Prophet (ﷺ) remained silent for a while. It was said to that person, "What is wrong with you? You are talking to the Prophet (p.b.u.h) while he is not talking to you." Then we noticed that he was being inspired divinely. Then the Prophet (ﷺ) wiped off his sweat and said, "Where is the questioner?" It seemed as if the Prophet (ﷺ) liked his question. Then he said, "Good never brings forth evil. Indeed it is like what grows on the banks of a water-stream which either kill or make the animals sick, except if an animal eats its fill the Khadira (a kind of vegetable) and then faces the sun, and then defecates and urinates and grazes again. No doubt this wealth is sweet and green. Blessed is the wealth of a Muslim from which he gives to the poor, the orphans and to needy travelers. (Or the Prophet said something similar to it) No doubt, whoever takes it illegally will be like the one who eats but is never satisfied, and his wealth will be a witness against him on the Day of Resurrection
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1465</td></tr><tr><td>Arabic No</td><td>1465</td></tr><tr><td>Reference</td><td>Book 24 Hadith 67</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Mu'adz bin Fadhalah] telah menceritakan kepada kami [Hisyam] dari [Yahya] dari [Hilal bin Abu Maimunah] telah menceritakan kepada kami ['Atha' bin Yasar] bahwa dia mendengar [Abu Sa'id Al Khudriy radliallahu 'anhu] menceritakan bahwa Nabi Shallallahu'alaihiwasallam suatu hari duduk diatas mimbar dan kami pun duduk didekatnya lalu Beliau berkata,: "Sesungguhnya diantara yang aku khawatirkan terjadi pada kalian sepeninggalku adalah apabila telah dibuka untuk kalian (keindahan) dunia serta perhiasannya". Tiba-tiba ada seorang laki-laki berkata,: "Wahai Rasulullah, apakah kebaikan dapat mendatangkan keburukan?". Maka Nabi Shallallahu'alaihiwasallam terdiam. Dikatakan kepada orang yang bertanya tadi; "Apa yang telah kamu lakukan, kamu mengajak Nabi Shallallahu'alaihiwasallam berbicara yang membuat Beliau tidak berbicara kepadamu". Maka kami melihat bahwa wahyu sedang turun kepada Beliau. Abu Said berkata,: "Beliau mengusap keringatnya yang banyak lalu berkata,: "Mana orang yang bertanya tadi?". Lalu nampak Beliau memuji Allah seraya bersabda: "Kebaikan tidak akan mendatangkan keburukan. Sesungguhnya apa yang ditumbuhkan pada musim semi dapat membinasakan atau dapat mendekatkan kepada kematian kecuali seperti (ternak) pemakan dedaunan hijau yang apabila sudah kenyang dia akan memandang matahari lalu mencret kemudian kencing lalu dia kembali merumput (makan lagi). Dan sungguh harta itu seperti dedaunan hijau yang manis. Maka beruntunglah seorang muslim yang dengan hartanya dia memberi orang-orang miskin, anak yatim dan ibnu sabil (musafir yang kehabisan bekal) ". Atau seperti yang didabdakan oleh Nabi Shallallahu'alaihiwasallam: "Dan sesungguhnya barangsiapa yang mengambil harta dunia tanpa hak ia seperti orang yang memakan namun tidak pernah kenyang dan harta itu akan menjadi saksi yang menuntutnya pada hari qiyamat
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1465</td></tr><tr><td>Arabic No</td><td>1465</td></tr><tr><td>Reference</td><td>Book 24 Hadith 67</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
அபூசயீத் அல்குத்ரீ (ரலி) அவர்கள் கூறியதாவது: ஒரு நாள் நபி (ஸல்) அவர்கள் சொற்பொழிவு மேடைமீது அமர்ந்தார்கள். நாங்களும் அவர்களைச் சுற்றி அமர்ந் தோம். அப்போது அவர்கள், “எனக்குப் பின் உங்களுக்கிடையே உலக வளங் களும் அதன் கவர்ச்சிப் பொருட்களும் தாராளமாகத் திறந்துவிடப்படுவதைப் பற்றியே நான் அஞ்சுகிறேன்” எனக் கூறினார்கள். ஒருவர், “அல்லாஹ்வின் தூதரே! (செல்வம் என்ற) நன்மை தீமையை உருவாக்குமா?” எனக் கேட்டதும் நபி (ஸல்) அவர்கள் மௌனமாக இருந்தார்கள். அப்போது அந்த மனிதரிடம், “உமது நிலைமை என்ன? நீர் நபி (ஸல்) அவர்களிடம் பேசுகிறீர்; ஆனால், நபி (ஸல்) அவர்களோ உம்மிடம் பேசாம லிருக்கிறார்களே!” எனக் கேட்கப்பட்டது. நாங்கள் நபி (ஸல்) அவர்களுக்கு வேத அறிவிப்பு (வஹீ) அருளப்படுகிறது எனக் கருதினோம். அப்போது நபி (ஸல்) அவர்கள் வியர்வையைத் துடைத்து விட்டு, “கேள்வி கேட்டவர் எங்கே?” என அவரைப் பாராட்டுவதைப் போன்று கேட்டார்கள். பிறகு, “நன்மையானது தீமையை உருவாக்காதுதான்; வசந்த காலத்தில் விளைகின்ற (பயிர்கள்) ஒவ்வொன்றும் (கால்நடைகளை, வயிறு புடைக்கத் தின்னவைத்துக்) கொன்றுவிடுகின்றன; அல்லது கொல்லும் அளவுக்குச் சென்றுவிடுகின்றன; பச்சைப் புற்களைத் தின்னும் கால்நடையைத் தவிர. (அது மடிவதில்லை; ஏனெனில்) அது (பச்சைப் புற்களைத்) தின்று வயிறு நிரம்பிவிடும்போது சூரியனை நேராக நோக்கி(ப் படுத்துக்கொண்டு அசைபோடுகின்றது) சாணமிட்டு சிறுநீரும் கழிக்கின்றது. பின்னர் (வயிறு காலியானவுடன் மீண்டும் சென்று) மேய்கிறது. (இது போலவே உலகிலுள்ள) இந்தச் செல்வம் பசுமையானதும் இனிமையானதும் ஆகும். எனவே, ஒரு முஸ்லிம், தமது செல்வத்திலிருந்து ஏழைகளுக்கும் அநாதைகளுக்கும் வழிப்போக்கர்களுக்கும் கொடுத்துக்கொண்டிருக்கும்வரை, அது அவருக்குச் சிறந்த தோழனாகும். யார் முறையின்றி அதை எடுத்துக்கொள்கி றாரோ - அவர் உண்டும் வயிறு நிரம்பாத வனைப் போன்றவர் ஆவார். மேலும், மறுமை நாளில் அந்தச் செல்வம் அவருக்கு எதிரான சாட்சியாக அமையும்” எனக் கூறினார்கள். அத்தியாயம் : 24
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1465</td></tr><tr><td>Arabic No</td><td>1465</td></tr><tr><td>Reference</td><td>Book 24 Hadith 67</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ebu Saîd el-Hudrî r.a. şöyle anlatır: Bir gün Resûlullah Sallallahu Aleyhi ve Sellem minbere oturmuştu. Biz de etrafına oturduk. Sonra: "Benden sonra, sizin için endişe ettiğim şeylerden biri dünya güzelliklerinin sizin için açılmasıdır" buyurdu. Bir sahabî, "Ey Allah'ın Resulü! Hayırlı bir şey şer getirir mi?" diye sordu. Bunun üzerine Nebi Sallallahu Aleyhi ve Sellem bir süre sustu. Etraftaki sahabîler soru soran kimseye, "Neden Nebi ile konuşuyorsun? O seninle konuşmuyor ki" dedi. Bir de baktık ki Resûlullah Sallallahu Aleyhi ve Sellem'e vahiy iniyor. Sonra terini sildi ve soru soran kişiyi över bir tavırla, "Soruyu soran nerede? Gerçekte, hayır şer getirmez. Muhakkak ki baharın yeşerttiği bitkilerden bazıları öldürücü veya zehirlidir. Fakat yeşil ot yiyen (hayvan) böyle değildir. Yeşil otu yer, kalçaları üzerine oturur, güneşlenir. Dışkısını ve idrarını rahatça yapar. Sonra yine bol bol yer. İşte mal da yeşil ot gibi tatlıdır. Malından, miskine, yetime ve yolda kalmışa veren kimseye ne mutlu! (Ravî, ya da buna benzer şey söylediğini belirtir). Malları, haksız yolla elde eden, yiyip yiyip de doymayan kimse gibidir. Bunlar, kıyamet günü onun aleyhine şahitlik edecektir" buyurdu
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1465</td></tr><tr><td>Arabic No</td><td>1465</td></tr><tr><td>Reference</td><td>Book 24 Hadith 67</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ہم سے معاذ بن فضالہ نے بیان کیا ‘ کہا کہ مجھ سے ہشام دستوائی نے ‘ یحییٰ سے بیان کیا۔ ان سے ہلال بن ابی میمونہ نے بیان کیا ‘ کہا کہ ہم سے عطاء بن یسار نے بیان کیا ‘ اور انہوں نے ابو سعید خدری رضی اللہ عنہ سے سنا ‘ وہ کہتے تھے کہ نبی کریم صلی اللہ علیہ وسلم ایک دن منبر پر تشریف فرما ہوئے۔ ہم بھی آپ صلی اللہ علیہ وسلم کے اردگرد بیٹھ گئے۔ آپ صلی اللہ علیہ وسلم نے فرمایا کہ میں تمہارے متعلق اس بات سے ڈرتا ہوں کہ تم پر دنیا کی خوشحالی اور اس کی زیبائش و آرائش کے دروازے کھول دئیے جائیں گے۔ ایک شخص نے عرض کیا۔ یا رسول اللہ! کیا اچھائی برائی پیدا کرے گی؟ اس پر نبی کریم صلی اللہ علیہ وسلم خاموش ہو گئے۔ اس لیے اس شخص سے کہا جانے لگا کہ کیا بات تھی۔ تم نے نبی کریم صلی اللہ علیہ وسلم سے ایک بات پوچھی لیکن نبی کریم صلی اللہ علیہ وسلم تم سے بات نہیں کرتے۔ پھر ہم نے محسوس کیا کہ آپ صلی اللہ علیہ وسلم پر وحی نازل ہو رہی ہے۔ بیان کیا کہ پھر نبی کریم صلی اللہ علیہ وسلم نے پسینہ صاف کیا ( جو وحی نازل ہوتے وقت آپ صلی اللہ علیہ وسلم کو آنے لگتا تھا ) پھر پوچھا کہ سوال کرنے والے صاحب کہاں ہیں۔ ہم نے محسوس کیا کہ آپ صلی اللہ علیہ وسلم نے اس کے ( سوال کی ) تعریف کی۔ پھر آپ صلی اللہ علیہ وسلم نے فرمایا کہ اچھائی برائی نہیں پیدا کرتی ( مگر بے موقع استعمال سے برائی پیدا ہوتی ہے ) کیونکہ موسم بہار میں بعض ایسی گھاس بھی اگتی ہیں جو جان لیوا یا تکلیف دہ ثابت ہوتی ہیں۔ البتہ ہریالی چرنے والا وہ جانور بچ جاتا ہے کہ خوب چرتا ہے اور جب اس کی دونوں کوکھیں بھر جاتی ہیں تو سورج کی طرف رخ کر کے پاخانہ پیشاب کر دیتا ہے اور پھر چرتا ہے۔ اسی طرح یہ مال و دولت بھی ایک خوشگوار سبزہ زار ہے۔ اور مسلمان کا وہ مال کتنا عمدہ ہے جو مسکین ‘ یتیم اور مسافر کو دیا جائے۔ یا جس طرح نبی کریم صلی اللہ علیہ وسلم نے ارشاد فرمایا۔ ہاں اگر کوئی شخص زکوٰۃ حقدار ہونے کے بغیر لیتا ہے تو اس کی مثال ایسے شخص کی سی ہے جو کھاتا ہے لیکن اس کا پیٹ نہیں بھرتا۔ اور قیامت کے دن یہ مال اس کے خلاف گواہ ہو گا۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1465</td></tr><tr><td>Arabic No</td><td>1465</td></tr><tr><td>Reference</td><td>Book 24 Hadith 67</td></tr></tbody></table></div>