## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا مُعَاذُ بْنُ فَضَالَةَ، حَدَّثَنَا هِشَامٌ، عَنْ قَتَادَةَ، عَنْ أَنَسٍ ـ رضى الله عنه ـ قَالَ سَأَلُوا النَّبِيَّ صلى الله عليه وسلم حَتَّى أَحْفَوْهُ بِالْمَسْأَلَةِ، فَصَعِدَ النَّبِيُّ صلى الله عليه وسلم ذَاتَ يَوْمٍ الْمِنْبَرَ فَقَالَ ‏"‏ لاَ تَسْأَلُونِي عَنْ شَىْءٍ إِلاَّ بَيَّنْتُ لَكُمْ ‏"‏‏.‏ فَجَعَلْتُ أَنْظُرُ يَمِينًا وَشِمَالاً، فَإِذَا كُلُّ رَجُلٍ رَأْسُهُ فِي ثَوْبِهِ يَبْكِي، فَأَنْشَأَ رَجُلٌ كَانَ إِذَا لاَحَى يُدْعَى إِلَى غَيْرِ أَبِيهِ فَقَالَ يَا نَبِيَّ اللَّهِ مَنْ أَبِي فَقَالَ ‏"‏ أَبُوكَ حُذَافَةُ ‏"‏‏.‏ ثُمَّ أَنْشَأَ عُمَرُ فَقَالَ رَضِينَا بِاللَّهِ رَبًّا، وَبِالإِسْلاَمِ دِينًا، وَبِمُحَمَّدٍ رَسُولاً، نَعُوذُ بِاللَّهِ مِنْ سُوءِ الْفِتَنِ‏.‏ فَقَالَ النَّبِيُّ صلى الله عليه وسلم ‏"‏ مَا رَأَيْتُ فِي الْخَيْرِ وَالشَّرِّ كَالْيَوْمِ قَطُّ، إِنَّهُ صُوِّرَتْ لِي الْجَنَّةُ وَالنَّارُ حَتَّى رَأَيْتُهُمَا دُونَ الْحَائِطِ ‏"‏‏.‏ قَالَ قَتَادَةُ يُذْكَرُ هَذَا الْحَدِيثُ عِنْدَ هَذِهِ الآيَةِ ‏(‏يَا أَيُّهَا الَّذِينَ آمَنُوا لاَ تَسْأَلُوا عَنْ أَشْيَاءَ إِنْ تُبْدَ لَكُمْ تَسُؤْكُمْ‏)‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>7089</td></tr><tr><td>Arabic No</td><td>7089</td></tr><tr><td>Reference</td><td>Book 92 Hadith 40</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
আনাস (রাঃ) থেকে বর্ণনা করেন যে, তিনি বলেছেন, লোকেরা নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর কাছে প্রশ্ন করত। এমন কি প্রশ্ন করতে করতে তারা তাঁকে বিরক্ত করে তুলত। একদিন নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম মিম্বারে আরোহণ করলেন এবং বললেনঃ তোমরা (আজ) আমাকে যে প্রশ্নই করবে, আমি তারই উত্তর দিব। আনাস (রাঃ) বলেন, আমি ডানে বামে তাকাচ্ছিলাম। দেখতে পেলাম প্রত্যেকেই আপন বস্ত্রে মাথা গুঁজে কাঁদছে। তখন এমন এক লোক পারস্পরিক ঝগড়ার সময় যাকে অন্য এক লোকের (যে আসলে তার পিতা নয়) সন্তান বলে সম্বোধন করা হত উঠে জিজ্ঞেস করল, হে আল্লাহর নবী! আমার পিতা কে? তিনি বললেনঃ হুযাফা তোমার পিতা। এরপর ‘উমার (রাঃ) সম্মুখে এলেন আর বললেন, আমরা রব হিসেবে আল্লাহকে, দ্বীন হিসাবে ইসলামকে এবং মুহাম্মাদ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-কে রাসূল হিসেবে মেনে পরিতুষ্ট। ফিতনার অনিষ্ট থেকে আমরা আল্লাহর নিকট আশ্রয় প্রার্থনা করছি। এরপর নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বললেনঃ আজকের মত এত উত্তম বস্তু এবং এত খারাপ বস্তু আমি ইতোপূর্বে কখনো দেখিনি। আমার সামনে জান্নাত ও জাহান্নামের ছবি পেশ করা হয়েছিল। এমনকি আমি সে দু’টোকে এ দেয়ালের পাশেই দেখতে পাচ্ছিলাম। ক্বাতাদাহ বলেন, উপরে বর্ণিত হাদীসটি নিম্নোক্ত আয়াত প্রসঙ্গে বলে উল্লেখ করা হয়। ইরশাদ হলোঃ ‘‘হে ঈমানদারগণ! তোমরা এমন বিষয়ে প্রশ্ন করো না, যা তোমাদের কাছে প্রকাশ করা হলে তা তোমাদেরকে কষ্ট দিবে ’’- (সূরাহ আল-মায়িদাহ ৫/১০১)। [৯৩] (আধুনিক প্রকাশনী- ৬৫৯৬, ইসলামিক ফাউন্ডেশন- ৬৬১০)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>7089</td></tr><tr><td>Arabic No</td><td>7089</td></tr><tr><td>Reference</td><td>Book 92 Hadith 40</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated Anas:The people started asking the Prophet (ﷺ) too many questions importunately. So one day he ascended the pulpit and said, "You will not ask me any question but I will explain it to you." I looked right and left, and behold, every man was covering his head with his garment and weeping. Then got up a man who, whenever quarreling with somebody, used to be accused of not being the son of his father. He said, "O Allah's Messenger (ﷺ)! Who is my father?" The Prophet (ﷺ) replied, "Your father is Hudhaifa." Then 'Umar got up and said, "We accept Allah as our Lord, Islam as our religion and Muhammad as our Apostle and we seek refuge with Allah from the evil of afflictions." The Prophet (ﷺ) said, " I have never seen the good and bad like on this day. No doubt, Paradise and Hell was displayed in front of me till I saw them in front of that wall," Qatada said: This Hadith used to be mentioned as an explanation of this Verse:-- 'O you who believe! Ask not questions about things which, if made plain to you, may cause you trouble.' (5.101)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>7089</td></tr><tr><td>Arabic No</td><td>7089</td></tr><tr><td>Reference</td><td>Book 92 Hadith 40</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Mu'adz bin Fadhalah] telah menceritakan kepada kami [Hisyam] dari [Qotadah] dari [Anas] radliallahu 'anhu mengatakan, para sahabat banyak bertanya kepada Nabi shallallahu 'alaihi wasallam sehingga mereka setengah memaksa dengan pertanyaan-pertanyaan. Maka Nabi shallallahu 'alaihi wasallam suatu hari naik ke mimbar dan bersabda: "Tidaklah kalian bertanya kepadaku mengenai sesuatu, selain kujelaskan kepada kalian, " lantas aku melihat ke kanan-kiri, tak tahunya setiap orang membungkus kepalanya di pakaiannya sambil menangis, muncullah seseorang yang jika berdebat dia dipanggil dengan nasab selain ayahnya, orang itu berujar; 'Wahai Nabiyullah siapakah ayahku? ' Nabi menjawab: "ayahmu adalah Hudzafah." Kontan Umar bergegas mengucapkan; 'RADHIINA BILLAHI RABBAN WABIL ISLAAMI DIINAN WABI MUHAMMADIN RASUULAN NA'UUDZU BILLAH MIN SUUIL FITANI (Kami ridha Allah sebagai rabb, Islam sebagai agama, dan Muhammad sebagai utusan, kami berlindung kepada Allah dari keburukan fitnah), " Nabi shallallahu 'alaihi wasallam bersabda; "Sama sekali belum pernah kulihat keburukan dan kebaikan seperti hari ini, sebab hari ini surga dan neraka digambarkan kepadaku sehingga aku melihat kedua-duanya dibalik dinding ini." Dan Qatadah selalu menyebutkan hadits ini berkaitan dengan ayat: 'Wahai orang-orang yang beriman, janganlah kalian bertanya tentang sesuatu yang sekiranya diungkapkan kepada kalian, justru malah menyusahkan kalian (QS. Almaidah; 101). [Abbas An Narsi] mengatakan, Telah menceritakan kepada kami [Yazid bin Zurai'] telah menceritakan kepada kami [Sa'id] telah menceritakan kepada kami [Qotadah], bahwasanya [Anas] menceritakan kepada mereka; bahwa Nabiyullah Shallallahu'alaihiwasallam besabda masalah ini dengan redaksi: Setiap orang membungkus kepalanya dalam bajunya sambil menangis, dan ia mengatakan dengan redaksi: 'aaidzan billah min suu'il fitan (aku berlindung kepada Allah dari keburukan fitnah) atau ia mengatakan; 'a'uudzu billah min sau'atil fitan (Saya berlindung kepada Allah dari keburukan-keburukan fitnah). Sedang [Khalifah] mengatakan kepadaku Telah menceritakan kepada kami [Yazid bin Zurai'] telah menceritakan kepada kami [Sa'id] dan [Mu'tamir] dari [ayahnya] dari [Qotadah], bahwasanya [Anas] menceritakan kepada mereka, dari Nabi shallallahu 'alaihi wasallam dengan Hadits ini dan dia mengatakan dengan redaksi; 'aaidzan billah min syarril fitan (berlindung kepada Allah dari keburukan fitnah)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>7089</td></tr><tr><td>Arabic No</td><td>7089</td></tr><tr><td>Reference</td><td>Book 92 Hadith 40</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
அனஸ் (ரலி) அவர்கள் கூறியதாவது: நபித்தோழர்கள் (சிலர்) நபி (ஸல்) அவர்களிடம் (அவர்களுக்குப் பிடிக்காத) சில விஷயங்கள் குறித்து வற்புறுத்திக் கேட்டுக்கொண்டிருந்தார்கள். ஆகவே, நபி (ஸல்) அவர்கள் ஒருநாள் சொற்பொழிவு மேடையின் மீதேறி, “(இன்று) நீங்கள் என்னிடம் எதைப் பற்றிக் கேட்டாலும் அதைப் பற்றி நான் உங்களுக்குத் தெளிவுபடுத்தாமல் இருக்கப்போவதில்லை” என்று (கோபத்துடன்) கூறினார்கள். உடனே நான்வலப் பக்கமும் இடப் பக்கமும் திரும்பிப் பார்க்கத் தலைப்பட்டபோது அங்கிருந்த ஒவ்வொருவரும் தமது ஆடையால் தலையைச் சுற்றிப் போர்த்தியவாறு அழுதுகொண்டிருந்தார்கள். அப்போது ஒரு மனிதர் பேசத் தொடங்கினார். அம்மனிதர் (பிறருடன்) சண்டைசச்சரவு செய்யும்போது அவருடைய தந்தையல்லாத மற்றொரு வரின் மகன் என அழைக்கப்பட்டுவந்தார். ஆகவே அவர், “அல்லாஹ்வின் நபியே! என் தந்தை யார்?” என்று கேட்டார். நபி (ஸல்) அவர்கள், “உன் தந்தை ஹுதாஃபா” என்று சொன்னார்கள். பிறகு உமர் (ரலி) அவர்கள், “நாங்கள் அல்லாஹ்வை இறைவனாகவும், இஸ்லாத்தை மார்க்கமாகவும், முஹம்மத் (ஸல்) அவர்களை இறைத்தூதராகவும் மனநிறைவுடன் ஏற்றுக்கொண்டோம். குழப்பங்களின் தீங்கிலிருந்து (எங்களை) பாதுகாக்கும்படி அல்லாஹ்விடம் கோருகின்றோம்” என்று கூறினார்கள். அப்போது நபி (ஸல்) அவர்கள், “நன்மையிலும் தீமையிலும் இன்றைய தினத்தைப் போன்று எந்த நாளையும் ஒருபோதும் நான் கண்டதில்லை. எனக்கு (இன்று) சொர்க்கமும் நரகமும் காட்டப்பட்டன. அவற்றை (மிஹ்ராபின்) இந்தச் சுவருக்கு அப்பால் நான் கண்டேன்” என்று சொன்னார்கள். (அறிவிப்பாளர்களில் ஒருவரான) கத்தாதா (ரஹ்) அவர்கள் கூறுகிறார்கள்: இந்த நபிமொழி, “இறைநம்பிக்கை கொண்டவர்களே! சில விஷயங்களைக் குறித்துக் கேட்காதீர்கள். அவை உங்களுக்கு வெளிப்படுத்தப்பட்டால் உங்களுக்கு மன வருத்தத்தை ஏற்படுத்தும்” எனும் (5:101ஆவது) இறை வசனத்தை ஓதும்போது நினைவுகூரப்படுவது வழக்கம்.28 அத்தியாயம் : 92
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>7089</td></tr><tr><td>Arabic No</td><td>7089</td></tr><tr><td>Reference</td><td>Book 92 Hadith 40</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Enes şöyle demiştir: Sahabiler Nebi Sallallahu Aleyhi ve Sellem'e birtakım sorular sordular ve nihayet işi ısrar derecesine vardırdılar. Bunun üzerine Resulullah Sallallahu Aleyhi ve Sellem bir gün minbere çıktı. "Bana soracağınız her şeyi açıklayacağım" dedi. Bu sırada ben sağa ve sola bakmaya başladım. Bir de ne göreyim herkes başını elbisesinin içine gömmüş ağ.lıyordu. Bu arada birisi söze başladı. Bu kişi, birisi ile tartıştığı zaman yüzüne babasının başkası olduğu iddia ediliyordu. O kişi "Ey Allah'ın Nebii! Benim babam kimdir?" diye sordu. Resulullah Sallallahu Aleyhi ve Sellem "Baban Huzafe'dir!" dedi. Bunun üzerine Ömer söze başlayıp "Biz Allah Teala'yı Rab, İslam'ı din, Muhammed'i Resul olarak kabul ve tasdik ettik. Bizler fitnelerin kötülüğünden Allah'a sığınırız!" dedi. Bu sözü üzerine Nebi Sallallahu Aleyhi ve Sellem "Ben hayırda ve şerde asla bugünün benzerini görmüş değilim. Şu muhakkak ki cennet ve ceh8nnem' benim önümde canlandırıldı da nihayet bu ikisini şu duvarın önünde gördüm" buyurdu
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>7089</td></tr><tr><td>Arabic No</td><td>7089</td></tr><tr><td>Reference</td><td>Book 92 Hadith 40</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ہم سے معاذ بن فضالہ نے بیان کیا، کہا ہم سے ہشام نے بیان کیا، ان سے قتادہ نے اور ان سے انس رضی اللہ عنہ نے کہ نبی کریم صلی اللہ علیہ وسلم نے لوگوں سے سوالات کئے آخر جب لوگ باربار سوال کرنے لگے تو نبی کریم صلی اللہ علیہ وسلم منبر پر ایک دن چڑھے اور فرمایا کہ آج تم مجھ سے جو سوال بھی کرو گے میں تمہیں اس کا جواب دوں گا۔ انس رضی اللہ عنہ نے بیان کیا کہ پھر میں دائیں بائیں دیکھنے لگا تو ہر شخص کا سر اس کے کپڑے میں چھپا ہوا تھا اور وہ رو رہا تھا۔ آخر ایک شخص نے خاموشی توڑی۔ اس کا جب کسی سے جھگڑا ہوتا تو انہیں ان کے باپ کے سوا دوسرے باپ کی طرف پکارا جاتا۔ انہوں نے کہا: یا رسول اللہ! میرے والد کون ہیں؟ فرمایا تمہارے والد حذافہ ہیں۔ پھر عمر رضی اللہ عنہ سامنے آئے اور عرض کیا ہم اللہ سے کہ وہ رب ہے، اسلام سے کہ وہ دین ہے، محمد صلی اللہ علیہ وسلم سے کہ وہ رسول ہیں راضی ہیں اور آزمائش کی برائی سے ہم اللہ کی پناہ مانگتے ہیں۔ پھر نبی کریم صلی اللہ علیہ وسلم نے فرمایا کہ میں نے خیر و شر آج جیسا دیکھا، کبھی نہیں دیکھا تھا۔ میرے سامنے جنت و دوزخ کی صورت پیش کی گئی اور میں نے انہیں دیوار کے قریب دیکھا۔ قتادہ نے بیان کیا کہ یہ بات اس آیت کے ساتھ ذکر کی جاتی ہے «يا أيها الذين آمنوا لا تسألوا عن أشياء إن تبد لكم تسؤكم‏» کہ ”اے لوگو! جو ایمان لائے ہو ایسی چیزوں کے بارے میں سوال نہ کرو اگر وہ ظاہر کر دی جائیں تو تمہیں بری معلوم ہوں۔“
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>7089</td></tr><tr><td>Arabic No</td><td>7089</td></tr><tr><td>Reference</td><td>Book 92 Hadith 40</td></tr></tbody></table></div>