## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا قُتَيْبَةُ، حَدَّثَنَا عَبْدُ الْعَزِيزِ، عَنْ أَبِي حَازِمٍ، عَنْ سَهْلِ بْنِ سَعْدٍ ـ رضى الله عنه ـ قَالَ بَلَغَ رَسُولَ اللَّهِ صلى الله عليه وسلم أَنَّ بَنِي عَمْرِو بْنِ عَوْفٍ بِقُبَاءٍ كَانَ بَيْنَهُمْ شَىْءٌ، فَخَرَجَ يُصْلِحُ بَيْنَهُمْ فِي أُنَاسٍ مِنْ أَصْحَابِهِ، فَحُبِسَ رَسُولُ اللَّهِ صلى الله عليه وسلم وَحَانَتِ الصَّلاَةُ، فَجَاءَ بِلاَلٌ إِلَى أَبِي بَكْرٍ ـ رضى الله عنهما ـ فَقَالَ يَا أَبَا بَكْرٍ، إِنَّ رَسُولَ اللَّهِ صلى الله عليه وسلم قَدْ حُبِسَ وَقَدْ حَانَتِ الصَّلاَةُ، فَهَلْ لَكَ أَنْ تَؤُمَّ النَّاسَ قَالَ نَعَمْ إِنْ شِئْتَ‏.‏ فَأَقَامَ بِلاَلٌ الصَّلاَةَ، وَتَقَدَّمَ أَبُو بَكْرٍ ـ رضى الله عنه ـ فَكَبَّرَ لِلنَّاسِ، وَجَاءَ رَسُولُ اللَّهِ صلى الله عليه وسلم يَمْشِي فِي الصُّفُوفِ يَشُقُّهَا شَقًّا، حَتَّى قَامَ فِي الصَّفِّ، فَأَخَذَ النَّاسُ فِي التَّصْفِيحِ‏.‏ قَالَ سَهْلٌ التَّصْفِيحُ هُوَ التَّصْفِيقُ‏.‏ قَالَ وَكَانَ أَبُو بَكْرٍ ـ رضى الله عنه ـ لاَ يَلْتَفِتُ فِي صَلاَتِهِ، فَلَمَّا أَكْثَرَ النَّاسُ الْتَفَتَ فَإِذَا رَسُولُ اللَّهِ صلى الله عليه وسلم فَأَشَارَ إِلَيْهِ، يَأْمُرُهُ أَنْ يُصَلِّيَ، فَرَفَعَ أَبُو بَكْرٍ ـ رضى الله عنه ـ يَدَهُ، فَحَمِدَ اللَّهَ، ثُمَّ رَجَعَ الْقَهْقَرَى وَرَاءَهُ حَتَّى قَامَ فِي الصَّفِّ، وَتَقَدَّمَ رَسُولُ اللَّهِ صلى الله عليه وسلم فَصَلَّى لِلنَّاسِ، فَلَمَّا فَرَغَ أَقْبَلَ عَلَى النَّاسِ فَقَالَ ‏"‏ يَا أَيُّهَا النَّاسُ مَا لَكُمْ حِينَ نَابَكُمْ شَىْءٌ فِي الصَّلاَةِ أَخَذْتُمْ بِالتَّصْفِيحِ إِنَّمَا التَّصْفِيحُ لِلنِّسَاءِ، مَنْ نَابَهُ شَىْءٌ فِي صَلاَتِهِ فَلْيَقُلْ سُبْحَانَ اللَّهِ ‏"‏‏.‏ ثُمَّ الْتَفَتَ إِلَى أَبِي بَكْرٍ ـ رضى الله عنه ـ فَقَالَ ‏"‏ يَا أَبَا بَكْرٍ، مَا مَنَعَكَ أَنْ تُصَلِّيَ لِلنَّاسِ حِينَ أَشَرْتُ إِلَيْكَ ‏"‏‏.‏ قَالَ أَبُو بَكْرٍ مَا كَانَ يَنْبَغِي لاِبْنِ أَبِي قُحَافَةَ أَنْ يُصَلِّيَ بَيْنَ يَدَىْ رَسُولِ اللَّهِ صلى الله عليه وسلم‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1218</td></tr><tr><td>Arabic No</td><td>1218</td></tr><tr><td>Reference</td><td>Book 21 Hadith 22</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
সাহল ইবনু সা‘দ (রাযি.) হতে বর্ণিত। তিনি বলেন, আল্লাহর রাসূল সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম -এর নিকট এ সংবাদ পৌঁছল যে, কুবায় বনূ আমর ইবনু আওফ গোত্রে কোন ব্যাপার ঘটেছে। তাদের মধ্যে মীমাংসার উদ্দেশে তিনি কয়েকজন সাহাবীসহ বেরিয়ে গেলেন। আল্লাহর রাসূল সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম সেখানে কর্মব্যস্ত হয়ে পড়েন। ইতোমধ্যে সালাতের সময় হয়ে গেল। বিলাল (রাযি.) আবূ বাকর (রাযি.)-এর নিকট এসে বললেন, হে আবূ বাকর! আল্লাহর রাসূল সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম কর্মব্যস্ত রয়েছেন। এদিকে সালাতের সময় উপস্থিত। আপনি কি লোকদের ইমামাত করবেন? তিনি বললেন, হাঁ, যদি তুমি চাও। তখন বিলাল (রাযি.) সালাতের ইক্বামাত(ইকামত/একামত) বললেন এবং আবূ বাকর (রাযি.) এগিয়ে গেলেন এবং তাকবীর বললেন। তখন আল্লাহর রাসূল সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম আনলেন এবং কাতার ফাঁক করে সামনে এগিয়ে গিয়ে কাতারে দাঁড়ালেন। মুসল্লীগণ তখন তাস্ফীহ্ করতে লাগলেন। সাহল (রাযি.) বলেন, তাসফীহ্ মানে তাস্ফীক (হাতে তালি দেয়া) তিনি আরো বললেন, আবূ বাকর (রাযি.) সালাতে এদিক সেদিক তাকাতেন না। মুসল্লীগণ অধিক (তালি দেয়া) করবে, তিনি লক্ষ্য করে রাসূলুল্লাহ্ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম -কে দেখতে পেলেন। তিনি তাঁকে ইঙ্গিতে সালাত আদায় করার আদেশ দিলেন। তখন আবূ বাকর (রাযি.) তাঁর দু’হাত তুললেন এবং আল্লাহর হাম্দ বর্ণনা করলেন। অতঃপর পিছু হেঁটে পিছনে চলে এসে কাতারে দাঁড়ালেন। আর আল্লাহর রাসূল সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম সামনে এগিয়ে গেলেন এবং মুসল্লীগণকে নিয়ে সালাত আদায় করলেন। সালাত শেষ করে তিনি মুসল্লীগণের দিকে মুখ করে বললেনঃ হে লোক সকল! তোমাদের কী হয়েছে? সালাতে কোন ব্যাপার ঘটলে তোমরা হাত চাপড়াতে শুরু কর কেন? হাত চাপড়ানো তো মেয়েদের জন্য। সালাতে আদায়রত অবস্থায় কারো কিছু ঘটলে পুরুষরা সুব্হানাল্লাহ্ বলবে। অতঃপর তিনি আবূ বাকর (রাযি.)-এর দিকে লক্ষ্য করে তাঁকে জিজ্ঞেস করলেন, হে আবূ বাকর! তোমাকে আমি ইঙ্গিত করা সত্ত্বেও কিসে তোমাকে সালাত আদায়ে বাধা দিল? আবূ বাকর (রাযি.) বললেন, আল্লাহর রাসূল সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম -এর সামনে দাঁড়িয়ে সালাত আদায় করা ইবনু আবূ কুহাফার* জন্য সমীচীন নয়। (৬৮৪) (আধুনিক প্রকাশনী-ঃ ১১৩৯, ইসলামিক ফাউন্ডেশনঃ ১১৪৫)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1218</td></tr><tr><td>Arabic No</td><td>1218</td></tr><tr><td>Reference</td><td>Book 21 Hadith 22</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated Sahl bin Sa'd:The news about the differences amongst the people of Bani 'Amr bin 'Auf at Quba reached Allah's Apostle and so he went to them along with some of his companions to affect a reconciliation. Allah's Apostle was delayed there and the time for the prayer became due. Bilal came to Abu Bakr! and said, "O Abu Bakr! Allah's Messenger (ﷺ) is detained (there) and the time for the prayer is due. Will you lead the people in prayer?" Abu Bakr replied, "Yes, if you wish." So Bilal pronounced the Iqama and Abu Bakr went forward and the people said Takbir. In the meantime, Allah's Messenger (ﷺ) came piercing through the rows till he stood in the (first) row and the people started clapping. Abu Bakr, would never look hither and thither during the prayer but when the people clapped much he looked back and saw Allah's Messenger (ﷺ). The Prophet (ﷺ) beckoned him to carry on. Abu Bakr raised both his hands, praised Allah and retreated till he stood in the row and Allah's Messenger (ﷺ) went forward and led the people in the prayer. When he had finished the prayer, he addressed the people and said, "O people! Why did you start clapping when something happened to you in the prayer? Clapping is for women. Whenever one is confronted with something unusual in the prayer one should say, 'Sub Han Allah'." Then the Prophet looked towards Abu Bakr and asked, "What prevented you from leading the prayer when I beckoned you to carry on?" Abu Bakr replied, "It does not befit the son of Al Quhafa to lead the prayer in the presence of Allah's Messenger (ﷺ)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1218</td></tr><tr><td>Arabic No</td><td>1218</td></tr><tr><td>Reference</td><td>Book 21 Hadith 22</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Qutaibah] telah menceritakan kepada kami ['Abdul 'Aziz] dari [Abu Hazim] dari [Sahal bin Sa'ad radliallahu 'anhu] berkata; Telah sampai kabar kepada Rasulullah shallallahu 'alaihi wasallam bahwa pada suku Bani 'Amru bin 'Auf bin Al Harits di Quba' timbul masalah diantara mereka. Maka Beliau bersama para sahabat Beliau berangkat kesana untuk menyelesaikan masalah. Ternyata Rasulullah shallallahu 'alaihi wasallam tertahan lama disana sedangkan waktu shalat sudah masuk. Maka Bilal menemui Abu Bakar radliallahu 'anhuma seraya berkata: "Wahai Abu Bakar, Rasulullah shallallahu 'alaihi wasallam terlambat hadir sedangkan waktu shalat sudah masuk, apakah engkau bersedia memimpin shalat berjama'ah? Dia (Abu Bakar) menjawab: "Ya bersedia, jika kamu menghendaki". Maka Bilal membacakan iqamat shalat dan Abu Bakar maju dan memulai takbir memimpin shalat bersama orang banyak. Tak lama kemudian datang Nabi shallallahu 'alaihi wasallam berjalan di tengah-tengan shaf membelah barisan hingga sampai di shaf. Maka orang-orang memberi isyarat dengan bertepuk tangan. Sahal berkata: "At-Tashfiih sama maksudnya dengan At-Tashfiiq. Dia berkata: "Saat itu Abu Bakar tidak bereaksi dalam shalatnya. Ketika suara tepukan semakin nyaring terdengar, Abu Bakar baru berbalik dan ternyata ada Rasulullah shallallahu 'alaihi wasallam. Maka Nabi memberi isyarat kepadanya agar tetap meneruskan shalatnya. Lalu Abu Bakar mengangkat kedua tangannya lalu memuji Allah kemudian dia mundur ke belakang dan berdiri di barisan, lalu Rasulullah shallallahu 'alaihi wasallam maju untuk memimpin shalat berjama'ah. Setelah selesai Nabi berbalik menghadap jama'ah lalu bersabda: "Wahai sekalian manusia, mengapa kalian ketika mendapatkan sesuatu dalam shalat, kalian melakukannya dengan bertepuk tangan? Sesungguhnya bertepuk tangan itu adalah isyarat yang dilakukan bagi kaum wanita. Maka siapa yang mendapatkan sesuatu yang keliru dalam shalat hendaklah mengucapkan Subhaanallah". Kemudian Beliau memandang ke arah Abu Bakar radliallahu 'anhu seraya berkata: "Wahai Abu Bakar, apa yang menghalangimu untuk melanjutkan memimpin shalat berjama'ah bersama orang banyak ketika aku sudah memberi isyarat kepadamu (agar meneruskannya)?" Abu Bakar menjawab: "Tidak patut bagi Ibnu Abu Quhafah memimpin shalat di hadapan Rasulullah shallallahu 'alaihi wasallam
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1218</td></tr><tr><td>Arabic No</td><td>1218</td></tr><tr><td>Reference</td><td>Book 21 Hadith 22</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
சஹ்ல் பின் சஅத் (ரலி) அவர்கள் கூறியதாவது: ‘குபா’வில் குடியிருந்த பனூ அம்ர் பின் அவ்ஃப் கூட்டத்தாரிடையே ஏதோ (தகராறு) இருப்பதாக நபி (ஸல்) அவர்களுக்குச் செய்தி கிடைத்தது. அவர்களி டையே சமரசம் செய்வதற்காக நபி (ஸல்) அவர்கள் தம் தோழர்கள் சிலருடன் புறப்பட்டார்கள். நபி (ஸல்) அவர்கள் (திரும்பி) வரத் தாமதமானது. தொழுகை நேரம் நெருங்கியது. அப்போது பிலால் (ரலி) அவர்கள், அபூபக்ர் (ரலி) அவர்களிடம் வந்து, “அபூபக்ரே! அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் வருவதற்குத் தாமதமாகிறது; தொழுகை நேரம் நெருங்கிவிட்டது. எனவே, மக்களுக்கு நீங்கள் தொழுகை நடத்துகிறீர்களா?” என்று கேட்டார்கள். “நீர் விரும்பினால் நடத்துகிறேன்” என்று அபூபக்ர் (ரலி) அவர்கள் கூறினார்கள். பிலால் (ரலி) அவர்கள் தொழு கைக்கு இகாமத் சொன்னதும் அபூபக்ர் (ரலி) அவர்கள் முன்னே சென்றார்கள். மக்களுக்கு (தொழுகை நடத்த) தக்பீர் (தஹ்ரீமா) கூறினார்கள். அப்போது நபி (ஸல்) அவர்கள் வரிசைகளைப் பிளந்து கொண்டு வந்து (முதல்) வரிசையில் நின்றார்கள். உடனே மக்கள் (அபூபக்ர் (ரலி) அவர்களுக்கு உணர்த்தும் முகமாக) கைதட்டலானார்கள். அபூபக்ர் (ரலி) அவர்கள் தொழுகையில் திரும் பிப் பார்க்கமாட்டார்கள். ஆயினும், மக்கள் அதிகமாகக் கைதட்டியதால் திரும்பிப் பார்த்தார்கள். (வரிசையில்) நபி (ஸல்) அவர்கள் நின்றிருந்தார்கள். தொழுகையைத் தொடருமாறு நபி (ஸல்) அவர்கள் அபூபக்ர் (ரலி) அவர்களுக்கு சைகை செய்தார்கள். அபூபக்ர் (ரலி) அவர்கள் தமது கையை உயர்த்தி அல்லாஹ்வைப் புகழ்ந்து, (திரும்பாமல்) அப்படியே பின்னால் நகர்ந்து வரிசையில் நின்றுகொண்டார்கள். நபி (ஸல்) அவர்கள் முன்னே சென்று மக்களுக்குத் தொழுவித்தார்கள். தொழுது முடித்ததும் மக்களை நோக்கி “மக்களே! தொழுகையில் ஏதும் பிரச்சினை ஏற்பட்டால் ஏன் கைகளைத் தட்டுகிறீர்கள்? கைதட்டுதல் பெண் களுக்குரியதாகும். எனவே, தொழும் போது ஒருவருக்குப் பிரச்சினை ஏற்பட்டால் அவர் ‘சுப்ஹானல்லாஹ்’ (அல்லாஹ் தூயவன்) எனக் கூறட்டும்” என்றார்கள். பிறகு அபூபக்ர் (ரலி) அவர்களை நோக்கி, “அபூபக்ரே! நான் உங்களுக்கு சைகை செய்த பிறகும் மக்களுக்குத் தொழுகை நடத்த மறுத்ததேன்?” எனக் கேட்டார்கள். அதற்கு அபூபக்ர் (ரலி) அவர்கள், “அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் முன்னிலையில் அபூகுஹா ஃபாவின் மகனுக்குத் தொழுகை நடத்தும் தகுதியில்லை” எனக் கூறி னார்கள்.13 அத்தியாயம் : 21
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1218</td></tr><tr><td>Arabic No</td><td>1218</td></tr><tr><td>Reference</td><td>Book 21 Hadith 22</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Sehl İbn Sa'd r.a. şöyle demiştir: Kuba'da yaşayan Ben-i Amr İbn Avf kabilesinin mensupları arasında bir anlaşmazlık çıktığı haberi Resulullah Sallallahu Aleyhi ve Sellem'a ulaştı. O da ashabından birkaç kişi ile birlikte onların arasını düzeltmek için gitti. Namaz vakti geldiği halde Resulullah Sallallahu Aleyhi ve Sellem dönemedi. Bilal, Ebu Bekir'e r.a. gelerek: "Ey Ebu Bekir! Resulullah Sallallahu Aleyhi ve Sellem dönemedi, namaz vakti de girdi. Sen insanlara imamlık yapar mısın?" diye sordu. Ebu Bekir: "Evet, İsterseniz yaparım" dedi. Bilal namaz için kamet getirdi, Ebu Bekir mihrab'a geçerek tekbir aldı. Tam o sırada Nebi Sallallahu Aleyhi ve Sellem geldi. Safları yara yara ilk saf'a kadar ulaştı ve orada namaz'a durdu. Cemaat (Ebu Bekir'i uyarmak için) ellerini çırpmaya başladı. Ebu Bekir namaz kılarken sağ'a sol'a bakmıyordu. Cemaattekiler ellerini çokça çırpmaya devam edince onlara döndü. Bir de baktı ki Resulullah Sallallahu Aleyhi ve Sellem orada! Nebi Sallallahu Aleyhi ve Sellem eliyle ona namazı kıldırmaya devam etmesini işaret etti. Ancak Ebu Bekir ellerini kaldırarak Allah'a hamd etti sonra da yavaşça geriye gelerek saf'a girdi. Resulullah Sallallahu Aleyhi ve Sellem da ön'e çıkarak namazı kıldırdı. Nebi Sallallahu Aleyhi ve Sellem namaz'ı bitirince cemaat'e dönerek şöyle buyurdu: "Ey insanlar! Namazda iken bir durumla karşılaştığınızda niçin ellerinizi çırpmaya başladınız? El çırpmak kadınlara özgüdür. Namazda iken bir durumla karşılaşan kişi 'Sübhanallah' desin." Sonra Ebu Bekir'e dönerek: "Ya Eba Bekr! Ben sana işaret ettiğimde niçin namazı kıldırmaya devam etmedin?" diye sordu. Ebu Bekir: "Ebu Kuhafe'nin oğlunun, Resulullah'ın önünde namaz kılması yakışık almaz" dedi
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1218</td></tr><tr><td>Arabic No</td><td>1218</td></tr><tr><td>Reference</td><td>Book 21 Hadith 22</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ہم سے قتیبہ بن سعید نے بیان کیا، انہوں نے کہا کہ ہم سے عبدالعزیز بن ابی حازم نے بیان کیا، ان سے ابوحازم سلمہ بن دینار نے اور ان سے سہل بن سعد رضی اللہ عنہ نے کہ رسول اللہ صلی اللہ علیہ وسلم کو یہ خبر پہنچی کہ قباء کے قبیلہ بنو عمرو بن عوف میں کوئی جھگڑا ہو گیا ہے۔ اس لیے آپ صلی اللہ علیہ وسلم کئی اصحاب کو ساتھ لے کر ان میں صلح کرانے کے لیے تشریف لے گئے۔ وہاں آپ صلی اللہ علیہ وسلم صلح صفائی کے لیے ٹھہر گئے۔ ادھر نماز کا وقت ہو گیا تو بلال رضی اللہ عنہ نے ابوبکر رضی اللہ عنہ سے کہا کہ رسول اللہ صلی اللہ علیہ وسلم نہیں آئے اور نماز کا وقت ہو گیا، تو کیا آپ لوگوں کو نماز پڑھائیں گے؟ آپ نے جواب دیا کہ ہاں اگر تم چاہتے ہو تو پڑھا دوں گا۔ چنانچہ بلال رضی اللہ عنہ نے تکبیر کہی اور ابوبکر رضی اللہ عنہ نے آگے بڑھ کر نیت باندھ لی۔ اتنے میں رسول اللہ صلی اللہ علیہ وسلم بھی تشریف لے آئے اور صفوں سے گزرتے ہوئے آپ صلی اللہ علیہ وسلم پہلی صف میں آ کھڑے ہوئے، لوگوں نے ہاتھ پر ہاتھ مارنے شروع کر دیئے۔ ( سہل نے کہا کہ «تصفيح» کے معنی «تصفيق» کے ہیں ) آپ نے بیان کیا کہ ابوبکر رضی اللہ عنہ نماز میں کسی طرف متوجہ نہیں ہوتے تھے۔ لیکن جب لوگوں نے بہت دستکیں دیں تو انہوں نے دیکھا کہ رسول اللہ صلی اللہ علیہ وسلم کھڑے ہیں۔ نبی کریم صلی اللہ علیہ وسلم نے اشارہ سے ابوبکر کو نماز پڑھانے کے لیے کہا۔ اس پر ابوبکر رضی اللہ عنہ نے ہاتھ اٹھا کر اللہ تعالیٰ کا شکر ادا کیا اور پھر الٹے پاؤں پیچھے کی طرف چلے آئے اور صف میں کھڑے ہو گئے اور رسول اللہ صلی اللہ علیہ وسلم نے آگے بڑھ کر نماز پڑھائی۔ نماز سے فارغ ہو کر آپ صلی اللہ علیہ وسلم لوگوں کی طرف متوجہ ہوئے اور فرمایا کہ لوگو! یہ کیا بات ہے کہ جب نماز میں کوئی بات پیش آتی ہے تو تم تالیاں بجانے لگتے ہو۔ یہ مسئلہ تو عورتوں کے لیے ہے۔ تمہیں اگر نماز میں کوئی حادثہ پیش آئے تو «سبحان الله» کہا کرو۔ اس کے بعد آپ صلی اللہ علیہ وسلم ابوبکر رضی اللہ عنہ کی طرف متوجہ ہوئے اور فرمایا کہ ابوبکر! میرے کہنے کے باوجود تم نے نماز کیوں نہیں پڑھائی؟ ابوبکر رضی اللہ عنہ نے عرض کیا کہ ابوقحافہ کے بیٹے کو زیب نہیں دیتا کہ رسول اللہ صلی اللہ علیہ وسلم کی موجودگی میں نماز پڑھائے۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>1218</td></tr><tr><td>Arabic No</td><td>1218</td></tr><tr><td>Reference</td><td>Book 21 Hadith 22</td></tr></tbody></table></div>