## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا أَبُو الْيَمَانِ، أَخْبَرَنَا شُعَيْبٌ، عَنِ الزُّهْرِيِّ، ح وَحَدَّثَنِي مَحْمُودُ بْنُ غَيْلاَنَ، حَدَّثَنَا عَبْدُ الرَّزَّاقِ، أَخْبَرَنَا مَعْمَرٌ، عَنِ الزُّهْرِيِّ، عَنِ ابْنِ الْمُسَيَّبِ، عَنْ أَبِي هُرَيْرَةَ ـ رضى الله عنه ـ قَالَ شَهِدْنَا مَعَ رَسُولِ اللَّهِ صلى الله عليه وسلم فَقَالَ لِرَجُلٍ مِمَّنْ يَدَّعِي الإِسْلاَمَ ‏"‏ هَذَا مِنْ أَهْلِ النَّارِ ‏"‏‏.‏ فَلَمَّا حَضَرَ الْقِتَالُ قَاتَلَ الرَّجُلُ قِتَالاً شَدِيدًا، فَأَصَابَتْهُ جِرَاحَةٌ فَقِيلَ يَا رَسُولَ اللَّهِ، الَّذِي قُلْتَ إِنَّهُ مِنْ أَهْلِ النَّارِ فَإِنَّهُ قَدْ قَاتَلَ الْيَوْمَ قِتَالاً شَدِيدًا وَقَدْ مَاتَ‏.‏ فَقَالَ النَّبِيُّ صلى الله عليه وسلم ‏"‏ إِلَى النَّارِ ‏"‏‏.‏ قَالَ فَكَادَ بَعْضُ النَّاسِ أَنْ يَرْتَابَ، فَبَيْنَمَا هُمْ عَلَى ذَلِكَ إِذْ قِيلَ إِنَّهُ لَمْ يَمُتْ، وَلَكِنَّ بِهِ جِرَاحًا شَدِيدًا‏.‏ فَلَمَّا كَانَ مِنَ اللَّيْلِ لَمْ يَصْبِرْ عَلَى الْجِرَاحِ، فَقَتَلَ نَفْسَهُ، فَأُخْبِرَ النَّبِيُّ صلى الله عليه وسلم بِذَلِكَ فَقَالَ ‏"‏ اللَّهُ أَكْبَرُ، أَشْهَدُ أَنِّي عَبْدُ اللَّهِ وَرَسُولُهُ ‏"‏‏.‏ ثُمَّ أَمَرَ بِلاَلاً فَنَادَى بِالنَّاسِ ‏"‏ إِنَّهُ لاَ يَدْخُلُ الْجَنَّةَ إِلاَّ نَفْسٌ مُسْلِمَةٌ، وَإِنَّ اللَّهَ لَيُؤَيِّدُ هَذَا الدِّينَ بِالرَّجُلِ الْفَاجِرِ ‏"‏‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3062</td></tr><tr><td>Arabic No</td><td>3062</td></tr><tr><td>Reference</td><td>Book 56 Hadith 267</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
আবূ হুরাইরাহ্ (রাঃ) হতে বর্ণিত। তিনি বলেন, আমরা আল্লাহর রাসূল সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর সঙ্গে এক যুদ্ধে উপস্থিত ছিলাম। তখন তিনি ইসলামের দাবীদার এক ব্যক্তিকে লক্ষ্য করে বললেন, এ ব্যক্তি জাহান্নামী অথচ যখন যুদ্ধ শুরু হল, তখন সে লোকটি ভীষণ যুদ্ধ করল এবং আহত হল। তখন বলা হল, হে আল্লাহর রাসূল! যে লোকটি সম্পর্কে আপনি বলেছিলেন সে লোকটি জাহান্নামী, আজ সে ভীষণ যুদ্ধ করেছে এবং মারা গেছে। নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বললেন, সে জাহান্নামে গেছে। রাবী বলেন, একথার উপর কারো কারো অন্তরে এ বিষয়ে সন্দেহ সৃষ্টির উপক্রম হয় এবং তাঁরা এ সম্পর্কিত কথাবার্তায় রয়েছেন, এ সময় খবর এল যে, লোকটি মরে যায়নি বরং মারাত্মকভাবে আহত হয়েছে। যখন রাত্রি হল, সে আঘাতের কষ্টে ধৈর্যধারণ করতে পারল না এবং আত্মহত্যা করল। তখন নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর নিকট এ সংবাদ পৌঁছানো হল, তিনি বলে উঠলেন, আল্লাহ্ আকবার! আমি সাক্ষ্য দিচ্ছি যে, আমি অবশ্যই আল্লাহ তা‘আলার বান্দা এবং তাঁর রাসুল। অতঃপর নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বিলাল (রাঃ)-কে আদেশ করলেন, তখন তিনি লোকদের মধ্যে ঘোষণা দিলেন যে, মুসলিম ব্যতীত কেউ বেহেশ্তে প্রবেশ করবে না। আর আল্লাহ তা‘আলা (কখনো কখনো) এই দ্বীনকে মন্দ লোকের দ্বারাও সাহায্য করেন। (৪২০৪, ৬৬০৬) (মুসলিম ১/৪৭ হাঃ ১১১, ) (আধুনিক প্রকাশনীঃ ২৮৩২, ইসলামিক ফাউন্ডেশনঃ ২৮৪৩)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3062</td></tr><tr><td>Arabic No</td><td>3062</td></tr><tr><td>Reference</td><td>Book 56 Hadith 267</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated Az-Zuhri:as follows in Hadith 297. Narrated Abu Huraira: We were in the company of Allah's Messenger (ﷺ) in a Ghazwa, and he remarked about a man who claimed to be a Muslim, saying, "This (man) is from the people of the (Hell) Fire." When the battle started, the man fought violently till he got wounded. Somebody said, "O Allah's Messenger (ﷺ)! The man whom you described as being from the people of the (Hell) Fire fought violently today and died." The Prophet (ﷺ) said, "He will go to the (Hell) Fire." Some people were on the point of doubting (the truth of what the Prophet had said) while they were in this state, suddenly someone said that he was still alive but severely wounded. When night fell, he lost patience and committed suicide. The Prophet (ﷺ) was informed of that, and he said, "Allah is Greater! I testify that I am Allah's Slave and His Apostle." Then he ordered Bilal to announce amongst the people: 'None will enter Paradise but a Muslim, and Allah may support this religion (i.e. Islam) even with a disobedient man
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3062</td></tr><tr><td>Arabic No</td><td>3062</td></tr><tr><td>Reference</td><td>Book 56 Hadith 267</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah bercerita kepada kami [Abu Al Yaman] telah mengabarkan kepada kami [Syu'aib] dari [Az Zuhriy]. Dan diriwayatkan pula, telah bercerita kepadaku [Mahmud bin Ghailan] telah bercerita kepada kami ['Abdur Razzaq] telah mengabarkan kepada kami [Ma'mar] dari [Az Zuhriy] dari [Ibnu Al Musayyab] dari [Abu Hurairah radliallahu 'anhu] berkata; "Ketika kami sedang ikut dalam suatu peperangan bersama Rasulullah Shallallahu'alaiwasallam, Beliau berkata kepada seseorang yang mengaku dirinya telah masuk Islam; "Orang ini termasuk penduduk neraka". Ketika terjadi peperangan orang tadi berperang dengan sangat berani lalu dia terluka kemudian dikatakan (kepada Beliau); "Wahai Rasulullah, orang yang Baginda maksudkan tadi sebagai penduduk neraka, dia telah berperang hari ini dengan sangat berani dan dia telah gugur". Maka Nabi Shallallahu'alaihiwasallam berkata: "Dia akan masuk neraka". (Abu Hurairah) berkata; "Orang-orang semuanya jadi Ragu. Ketika dalam keraguan seperti itu, ada orang yang mengabarkan bahwa orang yang berperang tadi tidaklah mati melainkan setelah mendapatkan luka yang sangat parah namun ketika pada malam harinya dia tidak shabar atas luka yang dideritanya hingga akhirnya dia bunuh diri. Kejadian ini kemudian dikabarkan kepada Nabi Shallallahu'alaihiwasallam, maka Nabi Shallallahu'alaihiwasallam bersabda: "Allahu Akbar, aku bersaksi bahwa aku ini hamba Allah dan Rasul-Nya". Kemudian Beliau memerintahkan Bilal agar menyerukan manusia bahwa tidak akan masuk surga melainkan jiwa yang pasrah dan Allah bisa jadi menolong agama ini melalui seorang yang berdosa
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3062</td></tr><tr><td>Arabic No</td><td>3062</td></tr><tr><td>Reference</td><td>Book 56 Hadith 267</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
அபூஹுரைரா (ரலி) அவர்கள் கூறியதாவது: அல்லாஹ்வின் தூதர் (ஸல்) அவர் களுடன் நாங்கள் (ஹுனைன் அல்லது கைபர் போரில்) கலந்துகொண்டோம். தம்மை முஸ்லிம் என்று கூறிக்கொண்ட ஒரு மனிதரைக் குறித்து அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள், ‘‘இவர் நரகவாசி களில் ஒருவர்” என்று கூறினார்கள். போரிடும் நேரம் வந்தபோது அம்மனிதர் கடுமையாகப் போரிட்டார். அப்போது அவருக்குக் காயம் ஏற்பட்டது. நபி (ஸல்) அவர்களிடம், ‘‘அல்லாஹ்வின் தூதரே! தாங்கள் எவரைக் குறித்து, யிஇவர் நரகவாசிகளில் ஒருவர்’ என்று குறிப்பிட்டீர் களோ அவர் இன்று கடுமையாகப் போரிட்டு மடிந்துவிட்டார்” என்று கூறப்பட்டது. அப்போதும் நபி (ஸல்) அவர்கள், ‘‘அவர் நரகத்திற்கே செல்வார்” என்று கூறினார்கள். மக்களில் சிலர் (நபி (ஸல்) அவர்களின் இந்த அறிவிப்பைச்) சந்தேகப்படலாயினர். அவர்கள் இவ்வாறு இருக்க, ‘‘அவர் (போரில் கொல்லப்பட்டு) இறக்கவில்லை. ஆயினும், அவருக்குக் கடுமையான காயம் ஏற்பட்டது. இரவு வந்தபோது, காயத்தின் வேதனையை அவரால் தாங்க முடியாமல் தற்கொலை செய்துகொண்டார்” என்று கூறப்பட்டது. நபி (ஸல்) அவர்களுக்கு இந்தச் செய்தி தெரிவிக்கப்பட்டது. அப்போது அவர்கள், ‘‘அல்லாஹ் மிகப் பெரியவன். நான் அல்லாஹ்வின் அடியாரும் அவனுடைய தூதரும் ஆவேன் என்பதற்கு நானே சாட்சியம் கூறுகிறேன்” என்று கூறினார்கள். பிறகு, பிலால் (ரலி) அவர்களுக்குக் கட்டளையிட, அவர்கள் மக்களிடையே, ‘‘முஸ்லிமான ஆன்மாதான் சொர்க்கத்திற்குச் செல்ல முடியும். அல்லாஹ் இந்த மார்க்கத் திற்குப் பாவியான மனிதராலும் வலுவூட்டு கின்றான்” என்று பொதுஅறிவிப்புச் செய்தார்கள்.179 இந்த ஹதீஸ் இரு அறிவிப்பாளர்தொடர்களில் வந்துள்ளது. அத்தியாயம் : 56
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3062</td></tr><tr><td>Arabic No</td><td>3062</td></tr><tr><td>Reference</td><td>Book 56 Hadith 267</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Ebu Hureyre r.a.'in şöyle dediği nakledilmiştir: "Biz Resul-i Ekrem Sallallahu Aleyhi ve Sellem ile birlikte bir savaşta bulunmuştuk. Nebi Sallallahu Aleyhi ve Sellem Müslüman olduğunu iddia eden ve İslam saflarında çarpışan birisi için: "Bu cehennemliktir!" buyurdu. Savaş başlayınca bu adam kahramanca çarpıştı ve çok ağır bir yara aldı. Bunun üzerine Resulullah Sallallahu Aleyhi ve Sellem'e: "Ey Allah'ın Resulü, demin cehennemlik olduğunu söylediğiniz adam bu gün olağanüstü bir kahramanlık gösterdi ve öldü" diyenler oldu. Nebi Sallallahu Aleyhi ve Sellem ise: "Cehenneme gitti!" buyurdu, Fakat bazı kimseler neredeyse O'nun s.a.v.'in bu sözünden kuşku duymaya başladılar, Onlar bu şekilde konuşurlarken o adamın ölmediği fakat çok ağır bir yara aldığı ve gece olduğunda acılarına daha fazla dayanamayıp kendisini öldürdüğü haberi ulaştı. Resul-i Ekrem Sallallahu Aleyhi ve Sellem'e bunlar anlatıldı ve O Sallallahu Aleyhi ve Sellem de: "Şehadet ederim ki ben Allah'ın kulu ve Resulüyüm!" deyip Bilal'e insanlara şöyle demesini emretti: "Cennete sadece Müslüman olan kimseler girer. Allah Teala dinini günahkar (facir) bir insanla bile destekleyebilir. " Tekrar: 4203, 4204, 6606
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3062</td></tr><tr><td>Arabic No</td><td>3062</td></tr><tr><td>Reference</td><td>Book 56 Hadith 267</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ہم سے ابوالیمان نے بیان کیا ‘ کہا ہم کو شعیب نے خبر دی، انہیں زہری نے (دوسری سند) مجھ سے محمود بن غیلان نے بیان کیا، کہا ہم سے عبدالرزاق نے بیان کیا ‘ انہیں معمر نے خبر دی ‘ انہیں زہری نے ‘ انہیں ابن مسیب نے اور ان سے ابوہریرہ رضی اللہ عنہ نے بیان کیا کہ ہم رسول اللہ صلی اللہ علیہ وسلم کے ساتھ ایک غزوہ میں موجود تھے۔ آپ صلی اللہ علیہ وسلم نے ایک شخص کے متعلق جو اپنے کو مسلمان کہتا تھا ‘ فرمایا کہ یہ شخص دوزخ والوں میں سے ہے۔ جب جنگ شروع ہوئی تو وہ شخص ( مسلمانوں کی طرف ) بڑی بہادری کے ساتھ لڑا اور وہ زخمی بھی ہو گیا۔ صحابہ نے عرض کیا ‘ یا رسول اللہ! جس کے متعلق آپ نے فرمایا تھا کہ وہ دوزخ میں جائے گا۔ آج تو وہ بڑی بے جگری کے ساتھ لڑا ہے اور ( زخمی ہو کر ) مر بھی گیا ہے۔ آپ صلی اللہ علیہ وسلم نے اب بھی وہی جواب دیا کہ جہنم میں گیا۔ ابوہریرہ رضی اللہ عنہ نے بیان کیا ‘ کہ ممکن تھا کہ بعض لوگوں کے دل میں کچھ شبہ پیدا ہو جاتا۔ لیکن ابھی لوگ اسی غور و فکر میں تھے کہ کسی نے بتایا کہ ابھی وہ مرا نہیں ہے۔ البتہ زخم کاری ہے۔ پھر جب رات آئی تو اس نے زخموں کی تاب نہ لا کر خودکشی کر لی۔ جب آپ صلی اللہ علیہ وسلم کو اس کی خبر دی گئی تو آپ صلی اللہ علیہ وسلم نے فرمایا: اللہ اکبر! میں گواہی دیتا ہوں کہ میں اللہ کا بندہ اور اس کا رسول ہوں۔ پھر آپ صلی اللہ علیہ وسلم نے بلال رضی اللہ عنہ کو حکم دیا ‘ اور انہوں نے لوگوں میں اعلان کر دیا کہ مسلمان کے سوا جنت میں کوئی اور داخل نہیں ہو گا اور اللہ تعالیٰ کبھی اپنے دین کی امداد کسی فاجر شخص سے بھی کرا لیتا ہے۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3062</td></tr><tr><td>Arabic No</td><td>3062</td></tr><tr><td>Reference</td><td>Book 56 Hadith 267</td></tr></tbody></table></div>