## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا عَبْدُ اللَّهِ بْنُ مُحَمَّدٍ، حَدَّثَنَا أَبُو حَفْصٍ، عَمْرٌو حَدَّثَنَا الأَوْزَاعِيُّ، حَدَّثَنِي ابْنُ شِهَابٍ، عَنْ عُبَيْدِ اللَّهِ بْنِ عَبْدِ اللَّهِ بْنِ عُتْبَةَ بْنِ مَسْعُودٍ، عَنِ ابْنِ عَبَّاسٍ ـ رضى الله عنهما ـ أَنَّهُ تَمَارَى هُوَ وَالْحُرُّ بْنُ قَيْسِ بْنِ حِصْنٍ الْفَزَارِيُّ فِي صَاحِبِ مُوسَى أَهُوَ خَضِرٌ، فَمَرَّ بِهِمَا أُبَىُّ بْنُ كَعْبٍ الأَنْصَارِيُّ، فَدَعَاهُ ابْنُ عَبَّاسٍ فَقَالَ إِنِّي تَمَارَيْتُ أَنَا وَصَاحِبِي هَذَا فِي صَاحِبِ مُوسَى الَّذِي سَأَلَ السَّبِيلَ إِلَى لُقِيِّهِ، هَلْ سَمِعْتَ رَسُولَ اللَّهِ صلى الله عليه وسلم يَذْكُرُ شَأْنَهُ قَالَ نَعَمْ إِنِّي سَمِعْتُ رَسُولَ اللَّهِ صلى الله عليه وسلم يَقُولُ ‏ "‏ بَيْنَا مُوسَى فِي مَلإِ بَنِي إِسْرَائِيلَ إِذْ جَاءَهُ رَجُلٌ فَقَالَ هَلْ تَعْلَمُ أَحَدًا أَعْلَمَ مِنْكَ فَقَالَ مُوسَى لاَ‏.‏ فَأُوحِيَ إِلَى مُوسَى بَلَى عَبْدُنَا خَضِرٌ‏.‏ فَسَأَلَ مُوسَى السَّبِيلَ إِلَى لُقِيِّهِ، فَجَعَلَ اللَّهُ لَهُ الْحُوتَ آيَةً وَقِيلَ لَهُ إِذَا فَقَدْتَ الْحُوتَ فَارْجِعْ فَإِنَّكَ سَتَلْقَاهُ‏.‏ فَكَانَ مُوسَى يَتْبَعُ أَثَرَ الْحُوتِ فِي الْبَحْرِ فَقَالَ فَتَى مُوسَى لِمُوسَى أَرَأَيْتَ إِذْ أَوَيْنَا إِلَى الصَّخْرَةِ فَإِنِّي نَسِيتُ الْحُوتَ وَمَا أَنْسَانِيهِ إِلاَّ الشَّيْطَانُ أَنْ أَذْكُرَهُ، قَالَ مُوسَى ذَلِكَ مَا كُنَّا نَبْغِي، فَارْتَدَّا عَلَى آثَارِهِمَا قَصَصًا فَوَجَدَا خَضِرًا، وَكَانَ مِنْ شَأْنِهِمَا مَا قَصَّ اللَّهُ ‏"‏‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>7478</td></tr><tr><td>Arabic No</td><td>7478</td></tr><tr><td>Reference</td><td>Book 97 Hadith 104</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ইবনু ‘আব্বাস (রাঃ) হতে বর্ণিত। তিনি এবং হুর ইবনু কায়স ইবনু হিস্‌ন ফাযারী (রাঃ) মূসা (আঃ)-এর সঙ্গীর ব্যাপারে দ্বিমত করছিলেন যে, তিনি কি খাযির ছিলেন? এমন সময় তাদের পাশ দিয়ে উবায় ইবনু কা‘ব আনসারী (রাঃ) যাচ্ছিলেন। ‘আবদুল্লাহ্ ইবনু ‘আব্বাস (রাঃ) তাঁকে ডেকে বললেন, আমি এবং আমার এ বন্ধু মূসা (আঃ)-এর সঙ্গী সম্পর্কে বিতর্ক করেছি মূসা (আঃ) যার সঙ্গে সাক্ষাতের পথের সন্ধান চেয়েছিলেন। আপনি কি রাসূলুল্লাহ্ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-কে তাঁর সম্পর্কে কিছু বলতে শুনেছেন? তিনি বললেন, হ্যাঁ। অবশ্যই আমি রাসূলুল্লাহ্ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-কে তার ব্যাপারে উল্লেখ করে বলতে শুনেছি যে, এক সময় মূসা (আঃ) বনী ইসরাঈলের একদল লোকের মাঝে ছিলেন। এমন সময় এক লোক তাঁর কাছে এসে জিজ্ঞেস করলো, মূসা! আপনি কি জানেন, আপনার চেয়ে বেশি জ্ঞানী কেউ আছেন? মূসা (আঃ) বললেন, না। তারপর মূসা (আঃ)-এর কাছে ওয়াহী নাযিল হল যে, হ্যাঁ আছেন, আমার বান্দা খাযির। তখন মূসা (আঃ) তাঁর সঙ্গে দেখা করার পথ সম্পর্কে জানতে চাইলেন। সুতরাং আল্লাহ্ সেজন্য একটি মাছকে নির্দেশ হিসেবে ঠিক করলেন এবং তাকে বলা হল, মাছটিকে যখন হারিয়ে ফেলবে, তখন সেদিকে ফিরে যাবে, তবে তুমি তাঁর দেখা পাবে। এরই প্রেক্ষাপটে মূসা (আঃ) সাগরে মাছের চিহ্ন ধরে খোঁজ করতে থাকলে মূসার সঙ্গীটি বলল, ‘আপনি কি লক্ষ্য করেছেন, আমরা যখন শিলাখন্ডে (বসে) ছিলাম তখন আমি মাছের কথা ভুলে গিয়েছিলাম। সেটার কথা আপনাকে বলতে শয়তানই আমাকে ভুলিয়ে দিয়েছিল- (সূরাহ কাহাফ ১৮/৬৩)। মূসা বলল, ‘এটাই তো সে জায়গা যেটা আমরা খুঁজছি।’ কাজেই তারা তাদের পায়ের চিহ্ন ধরে ফিরে গেল। তখন তারা পেল- (সূরাহ কাহাফ ১৮/৬৪-৬৫)। তাদের এ দু’জনের ঘটনা যা ঘটেছিল, আল্লাহ্ তারই বর্ণনা দিয়েছেন। [৭৪] (আধুনিক প্রকাশনী- ৬৯৬০, ইসলামিক ফাউন্ডেশন- ৬৯৭০)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>7478</td></tr><tr><td>Arabic No</td><td>7478</td></tr><tr><td>Reference</td><td>Book 97 Hadith 104</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated Ibn 'Abbas:That he differed with Al-Hurr bin Qais bin Hisn Al-Fazari about the companion of Moses, (i.e., whether he was Kha,dir or not). Ubai bin Ka'b Al-Ansari passed by them and Ibn 'Abbas called him saying, 'My friend (Hur) and I have differed about Moses' Companion whom Moses asked the way to meet. Did you hear Allah's Messenger (ﷺ) mentioning anything about him?" Ubai said, "Yes, I heard Allah's Apostle saying, "While Moses was sitting in the company of some Israelites a man came to him and asked, 'Do you know Someone who is more learned than you (Moses)?' Moses said, 'No.' So Allah sent the Divine inspiration to Moses:-- 'Yes, Our Slave Khadir is more learned than you' Moses asked Allah how to meet him ( Khadir) So Allah made the fish as a sign for him and it was said to him, 'When you lose the fish, go back (to the place where you lose it) and you will meet him.' So Moses went on looking for the sign of the fish in the sea. The boy servant of Moses (who was accompanying him) said to him, 'Do you remember (what happened) when we betook ourselves to the rock? I did indeed forget to tell you (about) the fish. None but Satan made me forget to tell you about it' (18.63) Moses said: 'That is what we have been seeking." Sa they went back retracing their footsteps. (18.64). So they both found Kadir (there) and then happened what Allah mentioned about them (in the Qur'an)!' (See 18.60- 82)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>7478</td></tr><tr><td>Arabic No</td><td>7478</td></tr><tr><td>Reference</td><td>Book 97 Hadith 104</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>

</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>7478</td></tr><tr><td>Arabic No</td><td>7478</td></tr><tr><td>Reference</td><td>Book 97 Hadith 104</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
உபைதுல்லாஹ் பின் அப்தில் லாஹ் (ரஹ்) அவர்கள் கூறியதாவது: ‘மூசா (அலை) (அவர்கள் கல்வி கற்பதற்காக ஓர் அடியாரைத் தேடிச் சென்றதாக அல்லாஹ் குறிப்பிடுகின்ற) அவர்களுடைய அந்தத் தோழர் யார்? அவர் ‘களிர்’ அவர்கள்தானா?’ என்பது தொடர்பாக இப்னு அப்பாஸ் (ரலி) அவர்களும் ஹுர்ரு பின் கைஸ் அல் ஃபஸாரிய்யு என்பாரும் கருத்து வேறுபாடு கொண்டு தர்க்கித்துக்கொண்டார்கள். அப்போது உபை பின் கஅப் (ரலி) அவர்கள் அவ்வழியாகச் சென்றார்கள். அன்னாரை இப்னு அப்பாஸ் (ரலி) அவர்கள் அழைத்து, “நானும் என்னுடைய இந்தத் தோழரும் மூசா (அலை) அவர்கள் எவரைச் சந்திக்கச் செல்வதற்கு இறைவனிடம் வழி கேட்டார்களோ அந்தத் தோழர் யார் என்பது தொடர்பாகத் தர்க்கித்துக் கொண்டோம். அவரது நிலை குறித்து அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் சொல்ல நீங்கள் கேட்டிருக்கிறீர்களா?” என்று வினவினார்கள். உபை பின் கஅப் (ரலி) அவர்கள் (பின்வருமாறு) பதிலளித் தார்கள்: ஆம். அல்லாஹ்வின் தூதர் (ஸல்) அவர்கள் சொல்ல நான் கேட்டிருக்கிறேன்: இஸ்ரவேலர்களில் ஒரு கூட்டத்தாரிடையே மூசா (அலை) அவர்கள் இருந்தபோது ஒரு மனிதர் வந்து “உங்களைவிட அறிந்தவர் எவரும் இருப்பது உங்களுக்குத் தெரியுமா?” என்று கேட்க, மூசா (அலை) அவர்கள், “இல்லை (என்னைவிட அறிந்தவர் எவரும் இருப்பதாகத் தெரிய வில்லை)” என்று சொன்னார்கள். உடனே மூசா (அலை) அவர்களுக்கு, “இருக்கிறார். அவர்தான் நம் அடியார் ‘களிர்’ ஆவார்” என்று வஹீ அறிவிக்கப்பட்டது. அப்போது மூசா (அலை) அவர்கள் களிர் அவர்களைச் சந்திக்கச் செல்லும் வழியைக் கேட்டார்கள். அப்போது அல்லாஹ் மீன் ஒன்றை அவர்களுக்கு அடையாளமாக ஆக்கினான். அவர்களிடம், “நீங்கள் எந்த இடத்தில் மீனைத் தொலைக்கிறீர்களோ அந்த இடத்திலிருந்து (வந்த வழியே) திரும்பச் செல்லுங்கள். அங்கு களிர் அவர்களைச் சந்திப்பீர்கள்” என்று கூறப்பட்டது. அவ்வாறே மூசா (அலை) அவர்கள் கடலில் மீனின் சுவட்டைப் பின்பற்றியபடியே சென்றுகொண்டிருந்தார்கள். அப்போது மூசா (அலை) அவர்களுடைய பணியாள் மூசா (அலை) அவர்களிடம், “நாம் அந்தப் பாறையின் பக்கம் (ஓய்வெடுக்க) ஒதுங்கினோமே பார்த்தீர்களா? அங்கேதான் நான் மீனை மறந்துவிட்டேன். அதை (உங்களுக்கு)க் கூறவிடாமல் ஷைத்தான்தான் எனக்கு மறதியைத் தந்துவிட்டான்; அது (அவ்விடத்தில் கடலில் செல்ல) விந்தையான விதத்தில் தனது வழியை அமைத்துக்கொண்டது” என்று சொன்னார். மூசா (அலை) அவர்கள், “அதுதான் நாம் தேடி வந்த இடம்” என்று சொல்ல, இருவருமாகத் தாம் வந்த வழியை நோக்கித் திரும்பிச் சென்றார்கள். அங்கே களிர் (அலை) அவர்களைக் கண்டார்கள் (18:63-65). பிறகு அவ்விருவர் தொடர்பாக அல்லாஹ் எடுத்துரைத்த நிகழ்ச்சிகள் நடைபெற்றன.120 அத்தியாயம் : 97
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>7478</td></tr><tr><td>Arabic No</td><td>7478</td></tr><tr><td>Reference</td><td>Book 97 Hadith 104</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
İbn Abbas ile el-Hurr b. Kays b. Hısn el-Fezari arasında Musa'nın birlikte yolculuk ettiği kişinin Hızır olup olmadığı konusunda bir tartışma çıktı. Bu sırada onların yanından Ubey b. Ka'b el-Ensarı geçti. İbn Abbas, Ka'b'ı çağırarak "Ben ve şu arkadaşım Musa Nebiin buluşmak için yol sorduğu kişi hakkında münakaşa ettik. Sen Resulullah Sallallahu Aleyhi ve Sellemtan onun halini zikrederken bir şey işittin mi?" dedi. Ubey b. Ka'b; "Ben Resulullah Sallallahu Aleyhi ve Sellemtan işittim şöyle buyuruyordu: 'Musa Nebi İsrailoğullarından bir topluluk içinde bulunduğu sırada bir adam geldi ve 'Senden daha alim bir kimse biliyor musun' diye sordu. Musa da 'Hayır bilmiyorum' dedi. Bu cevap üzerine Musa'ya 'Evet, benim kulum Hadr vardır. (O senden bazı hususlarda daha alimdir)' diye vahiy geldi. Bunun üzerine Musa Nebi o daha alim kul ile buluşma yolunu istedi. Allah da ona (Hızır'ın mekanı ve buluşma yerine alamet olmak üzere) balığı bir alamet, bir nişan kıldı ve Musa'ya 'Ya Musa! Balığı kaybettiği n zaman hemen geri dön. Çünkü sen o kula orada kavuşacaksın!' dedi. Artık Musa balığın kaybolduğu denizin içinde balığın izini takip edecekti. Yola devam ettiler. Bir yerde Musa'nın hizmetçisi olan genç Musa'ya 'Ne dersin? Kayanın yanında barındığımız zaman (balığın denize düşüp hareket ettiğini görmüştüm.) Ben balığı unuttum. Onu hatırlamamı bana unutturan ancak şeytandır' dedi. Musa 'Zaten istediğimiz bu idi' dedi. Bunun üzerine kendi izlerine baka baka geriye döndüler. Sonunda taşın yanında Hadr'ı buldular. Onunla Musa arasında Yüce Allah 'ın el-Kehf suresinde aktardığı bazı olaylar oldu
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>7478</td></tr><tr><td>Arabic No</td><td>7478</td></tr><tr><td>Reference</td><td>Book 97 Hadith 104</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ہم سے عبداللہ بن محمد نے بیان کیا، انہوں نے کہا ہم سے ابوحفص عمرو نے بیان کیا، ان سے اوزاعی نے بیان کیا ان سے ابن شہاب نے بیان کیا، ان سے عبیداللہ بن عبداللہ بن عقبہ بن مسعود نے بیان کیا اور ان سے عبداللہ بن عباس رضی اللہ عنہما نے بیان کیا کہ وہ اور حر بن قیس بن حصین الفزاری، موسیٰ علیہ السلام کے ساتھی کے بارے میں اختلاف کر رہے تھے کہ کیا وہ خضر علیہ السلام ہی تھے۔ اتنے میں ابی بن کعب رضی اللہ عنہ کا ادھر سے گزر ہوا اور ابن عباس رضی اللہ عنہما نے انہیں بلایا اور ان سے کہا کہ میں اور میرا یہ ساتھی اس بارے میں شک میں ہیں کہ موسیٰ علیہ السلام کے وہ صاحب کون تھے جن سے ملاقات کے لیے موسیٰ علیہ السلام نے راستہ پوچھا تھا۔ کیا آپ نے رسول اللہ صلی اللہ علیہ وسلم سے اس سلسلہ میں کوئی حدیث سنی ہے انہوں نے کہا کہ ہاں۔ میں نے رسول اللہ صلی اللہ علیہ وسلم سے سنا ہے۔ آپ صلی اللہ علیہ وسلم نے فرمایا کہ موسیٰ علیہ السلام بنی اسرائیل کے ایک مجمع میں تھے کہ ایک شخص نے آ کر پوچھا کیا آپ کسی ایسے شخص کو جانتے ہیں جو آپ سے زیادہ علم رکھتا ہو؟ موسیٰ علیہ السلام نے کہا کہ نہیں۔ چنانچہ آپ پر وحی نازل ہوئی کہ کیوں نہیں ہمارا بندہ خضر ہے۔ موسیٰ علیہ السلام نے ان سے ملاقات کا راستہ معلوم کیا اور اللہ تعالیٰ نے اس کے لیے مچھلی کو نشان قرار دیا اور آپ سے کہا گیا کہ جب تم مچھلی کو گم پاؤ تو لوٹ جانا کہ وہیں ان سے ملاقات ہو گی۔ چنانچہ موسیٰ علیہ السلام مچھلی کا نشان دریا میں ڈھونڈنے لگے اور آپ کے ساتھی نے آپ کو بتایا کہ آپ کو معلوم ہے۔ جب ہم نے چٹان پر ڈیرہ ڈالا تھا تو وہیں میں مچھلی بھول گیا اور مجھے شیطان نے اسے بھلا دیا۔ موسیٰ علیہ السلام نے کہا کہ یہ جگہ وہی ہے جس کی تلاش میں ہم سرگرداں ہیں پس وہ دونوں اپنے قدموں کے نشانوں پر واپس لوٹے اور انہوں نے خضر علیہ السلام کو پا لیا ان ہی دونوں کا یہ قصہ ہے جو اللہ نے بیان فرمایا۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>7478</td></tr><tr><td>Arabic No</td><td>7478</td></tr><tr><td>Reference</td><td>Book 97 Hadith 104</td></tr></tbody></table></div>