## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنِي فَرْوَةُ بْنُ أَبِي الْمَغْرَاءِ، أَخْبَرَنَا عَلِيُّ بْنُ مُسْهِرٍ، عَنْ هِشَامٍ، عَنْ أَبِيهِ، عَنْ عَائِشَةَ ـ رضى الله عنها ـ قَالَتْ أَسْلَمَتِ امْرَأَةٌ سَوْدَاءُ لِبَعْضِ الْعَرَبِ، وَكَانَ لَهَا حِفْشٌ فِي الْمَسْجِدِ قَالَتْ فَكَانَتْ تَأْتِينَا فَتَحَدَّثُ عِنْدَنَا فَإِذَا فَرَغَتْ مِنْ حَدِيثِهَا قَالَتْ وَيَوْمُ الْوِشَاحِ مِنْ تَعَاجِيبِ رَبِّنَا أَلاَ إِنَّهُ مِنْ بَلْدَةِ الْكُفْرِ أَنْجَانِي فَلَمَّا أَكْثَرَتْ قَالَتْ لَهَا عَائِشَةُ وَمَا يَوْمُ الْوِشَاحِ قَالَتْ خَرَجَتْ جُوَيْرِيَةٌ لِبَعْضِ أَهْلِي، وَعَلَيْهَا وِشَاحٌ مِنْ أَدَمٍ فَسَقَطَ مِنْهَا، فَانْحَطَّتْ عَلَيْهِ الْحُدَيَّا وَهْىَ تَحْسِبُهُ لَحْمًا، فَأَخَذَتْ فَاتَّهَمُونِي بِهِ فَعَذَّبُونِي، حَتَّى بَلَغَ مِنْ أَمْرِي أَنَّهُمْ طَلَبُوا فِي قُبُلِي، فَبَيْنَا هُمْ حَوْلِي وَأَنَا فِي كَرْبِي إِذْ أَقْبَلَتِ الْحُدَيَّا حَتَّى وَازَتْ بِرُءُوسِنَا ثُمَّ أَلْقَتْهُ، فَأَخَذُوهُ فَقُلْتُ لَهُمْ هَذَا الَّذِي اتَّهَمْتُمُونِي بِهِ وَأَنَا مِنْهُ بَرِيئَةٌ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3835</td></tr><tr><td>Arabic No</td><td>3835</td></tr><tr><td>Reference</td><td>Book 63 Hadith 60</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
‘আয়িশাহ (রাঃ) হতে বর্ণিত, তিনি বলেন, আরবের কোন এক গোত্রের এক (মুক্তিপ্রাপ্ত) কৃষ্ণকায় মহিলা ইসলাম গ্রহণ করেন। মসজিদের পাশে ছিল তার একটি ছোট ঘর। ‘আয়িশাহ (রাঃ) বলেন, সে আমাদের নিকট আসত এবং আমাদের সাথে কথাবার্তা বলত। যখন তার বাক্যালাপ শেষ হত তখন প্রায়ই বলতো, ইয়াওমূল বিশাহ (মণিমুক্তা খচিত হারের দিন) আমাদের রবের পক্ষ হতে আশ্চর্যজনক ঘটনাবলীর একটি দিন জেনে রাখুন! আমার রব আমাকে কুফর এর দেশ হতে মুক্তি দিয়েছেন। সে এ কথাটি প্রায়ই বলত। একদিন ‘আয়িশাহ (রাঃ) ঐ মহিলাকে জিজ্ঞেস করলেন, ‘ইয়ামুল বিশাহ’ কী? তখন সে বলল যে, আমার মুনিবের পরিবারের এক শিশু কন্যা ঘর হতে বের হল। তার গলায় চামড়ার (উপর মণিমুক্তা খচিত) একটি হার ছিল। হারটি (ছিড়ে) গলা হতে পড়ে গেল। তখন একটি চিল ওটা গোশ্তের টুকরা মনে করে ছোঁ মেরে নিয়ে গেল। তারা আমাকে হার চুরির সন্দেহে শাস্তি ও নির্যাতন করতে লাগল। অবশেষে তারা আমার লজ্জাস্থানে তল্লাশী চালাল। যখন তারা আমার চারপাশে ছিল এবং আমি চরম দুঃখে ছিলাম এমন সময় একটি চিল কোত্থেকে উড়ে আসল এবং আমাদের মাথার উপরে এসে হারটি ফেলে দিল। তারা হারটি তুলে নিল। তখন আমি বললাম, এটা হল সেই হার যেটা চুরির জন্য আমার উপর অপবাদ দিয়েছ, অথচ এ ব্যাপারে আমি সম্পূর্ণ নির্দোষ। (৪৩৯) (আধুনিক প্রকাশনীঃ ৩৫৫০, ইসলামিক ফাউন্ডেশনঃ ৩৫৫৫)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3835</td></tr><tr><td>Arabic No</td><td>3835</td></tr><tr><td>Reference</td><td>Book 63 Hadith 60</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated 'Aisha:A black lady slave of some of the 'Arabs embraced Islam and she had a hut in the mosque. She used to visit us and talk to us, and when she finished her talk, she used to say: "The day of the scarf was one of our Lord's wonders: Verily! He has delivered me from the land of Kufr." When she said the above verse many times, I (i.e. 'Aisha) asked her, "What was the day of the scarf?" She replied, "Once the daughter of some of my masters went out and she was wearing a leather scarf (round her neck) and the leather scarf fell from her and a kite descended and picked it up, mistaking it for a piece of meat. They (i.e. my masters) accused me of stealing it and they tortured me to such an extent that they even looked for it in my private parts. So, while they all were around me, and I was in my great distress, suddenly the kite came over our heads and threw the scarf, and they took it. I said to them 'This is what you accused me of stealing, though I was innocent
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3835</td></tr><tr><td>Arabic No</td><td>3835</td></tr><tr><td>Reference</td><td>Book 63 Hadith 60</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepadaku [Farwah bin Abu Al Maghra'] telah mengabarkan kepada kami ['Ali bin Mushir] dari [Hisyam] dari [bapaknya] dari ['Aisyah] radliallahu 'anha berkata; Ada seorang wanita berkulit hitam yang bekerja dengan beberapa orang Arab yang telah masuk Islam. Wanita itu memiliki rumah kecil lagi sempit di dekat masjid. 'Aisyah radliallahu 'anha melanjutkan; Dia pernah datang lalu bercerita di hadapan kami. Jika telah selesai dari ceritanya dia bersya'ir; Peristiwa selendang adalah salah satu dari keajaiban Rabb kami. Sungguh peristiwa itu terjadi di negeri kafir yang kemudian Allah menyelamatkan aku. Tatkala dia terus saja bersya'ir, 'Aisyah bertanya kepadanya; "Apakah hari selendang itu?". Wanita itu berkata; "Pernah ada seorang anak wanita keluar kepada sebagian keluargaku dengan membawa selendang yang terbuat dari kulit. Kemudian selendang tersebut terjatuh darinya, tiba-tiba seekor burung menyambar dan mengambilnya karena mengira selendang itu daging. Tetapi orang-orang menuduh aku dan menyiksa aku hingga mereka menggeladahku dari bagian depanku. Ketika mereka berada di sekelilingku dan aku dalam keadaan gundah tiba-tiba burung itu datang dan dan berputar-putar di atas kepala kami, kemudian melemparkannya. Orang-orang pun mengambil selendang tersebut. Maka aku berkata kepada mereka; Itulah yang kalian tuduhkan kepadaku padahal aku berlepas diri dari tuduhan itu
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3835</td></tr><tr><td>Arabic No</td><td>3835</td></tr><tr><td>Reference</td><td>Book 63 Hadith 60</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ஆயிஷா (ரலி) அவர்கள் கூறியதாவது: ஓர் அரபுக் கோத்திரத்திற்குச் சொந்த மான கறுப்பு (நிற அடிமைப்) பெண் ஒருத்தி இஸ்லாத்தை ஏற்றுக்கொண்டாள். அவளுக்குப் பள்ளிவாசலில் சிறிய (தங்கும்) அறையொன்று இருந்தது. அவள் எங்களிடம் வந்து பேசிக்கொண்டி ருப்பாள். அவள் பேசி முடிக்கும்போது, “அரை யணித் தோள்பட்டிகை72 (காணாமற் போன) நாள் எம் இறைவனின் விந்தை களில் ஒன்றாகும். அந்த நாள் இறைமறுப்பு (மேலோங்கி) இருந்த ஊரிலிருந்து என்னை (வெளியேற்றிக்) காப்பாற்றிவிட்டது” என்று பாடுவாள். இவ்வாறு அவள் அதிகமாகப் பாடுவதைக் கேட்ட நான், “அரையணித் தோள்பட்டிகை நாள் என்றால் என்ன?” என்று கேட்டேன். அதற்கு அவள் சொன்னாள்: என் (எஜமானியர்) குடும்பத்தாரில் ஒருவருக்குரிய சிறுமி ஒருத்தி (மணப் பெண்ணாக இருந்ததால்) பதனிடப்பட்ட தோலால் ஆன (சிவப்பு) அரையணித் தோள்பட்டிகை ஒன்றை அணிந்து கொண்டு (குளியலறைக்குச்) சென்றாள். அப்போது அந்தப் பட்டிகை (எதிர்பாராத விதமாக) அவளிடமிருந்து (கழன்று) விழுந்துவிட, அதைப் பருந்து ஒன்று இறைச்சி என்று நினைத்துக் கவ்வி எடுத்துச் சென்றுவிட்டது. (என் எஜமானர்கள் நான்தான் அதைத் திருடினேன் என்று) என்மீது குற்றம் சாட்டி என்னைச் சித்திரவதை செய்தார்கள். எந்த அளவுக்கென்றால், அவர்கள் என் பிறவி உறுப்பையும் சோதனையிட்டார்கள். அவர்கள் என்னைச் சூழ்ந்திருக்க, நான் கடும் வேதனையில் (துடித்தபடி) இருந்தபோது, அந்தப் பருந்து எங்கள் தலைகளுக்கு நேராக வந்து அந்தப் பட்டிகையை(க் கீழே) போட்டது. உடனே அதை அவர்கள் எடுத்துக்கொண்டனர். அப்போது நான் அவர்களிடம், “நான் குற்றமற்றவளாயிருக்க, நான் திருடிவிட் டதாக நீங்கள் குற்றம் சாட்டினீர்களே அந்தப் பட்டிகைதான் இது” என்று சொன்னேன்.73 அத்தியாயம் : 63
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3835</td></tr><tr><td>Arabic No</td><td>3835</td></tr><tr><td>Reference</td><td>Book 63 Hadith 60</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Aişe r.anha dedi ki: "Araplardan birisine ait siyah bir kadın Müslüman oldu. Bu kadının mescitte daracık bir evi de vardı. (Aişe) dedi ki: (Zaman zaman) yanımıza gelir ve yanımızda konuşurdu. Sözü bittiği vakit şöyle derdi: "O kemer günü Rabbimizin hayret verici işlerindendir Haberiniz olsun, şüphesiz ki o, küfür beldesinden beni kurtardı." Bunu çokça söylediğini görünce Aişe ona dedi ki: Bu kemer günü dediğin nedir? Kadın dedi ki: Benim yakınlarımdan birisinin küçücük bir kızı üzerinde deriden yapılmış bir kemer olduğu halde dışarı çıkmıştı. Bu kemerini düşürdü, onu et sanan bir çaylak o kemerin üzerine indi ve onu alıp gitti. Onu çalmakla beni itham ettiler. Bu sebeple de bana işkence ettiler. Hatta onlar bunu önümde (fercimde) dahi araştıracak kadar işi ileriye götürdüler. Onlar benim etrafımda iken ve ben de o sıkıntıların içerisinde bulunuyarken o çaylak geliverdi ve tam başlarımızın hizasında durdu. Sonra da kemeri bırakıverdi, onlar da kemeri aldılar. Ben de onlara, işte kendisini çalmaktan beri olduğum halde beni çalmakla itham ettiğiniz budur, dedim
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3835</td></tr><tr><td>Arabic No</td><td>3835</td></tr><tr><td>Reference</td><td>Book 63 Hadith 60</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
مجھ سے فروہ بن ابی المغراء نے بیان کیا، کہا ہم کو علی بن مسہر نے خبر دی، انہیں ہشام نے، انہیں ان کے والد نے اور ان سے عائشہ رضی اللہ عنہا نے بیان کیا کہ ایک کالی عورت جو کسی عرب کی باندی تھی اسلام لائی اور مسجد میں اس کے رہنے کے لیے ایک کوٹھری تھی۔ عائشہ رضی اللہ عنہا نے بیان کیا وہ ہمارے یہاں آیا کرتی اور باتیں کیا کرتی تھی، لیکن جب باتوں سے فارغ ہو جاتی تو وہ یہ شعر پڑھتی ”اور ہار والا دن بھی ہمارے رب کے عجائب قدرت میں سے ہے، کہ اسی نے ( بفضلہ ) کفر کے شہر سے مجھے چھڑایا۔“ اس نے جب کئی مرتبہ یہ شعر پڑھا تو عائشہ رضی اللہ عنہا نے اس سے دریافت کیا کہ ہار والے دن کا قصہ کیا ہے؟ اس نے بیان کیا کہ میرے مالکوں کے گھرانے کی ایک لڑکی ( جو نئی دولہن تھی ) لال چمڑے کا ایک ہار باندھے ہوئے تھی۔ وہ باہر نکلی تو اتفاق سے وہ گر گیا۔ ایک چیل کی اس پر نظر پڑی اور وہ اسے گوشت سمجھ کر اٹھا لے گئی۔ لوگوں نے مجھ پر اس کی چوری کی تہمت لگائی اور مجھے سزائیں دینی شروع کیں۔ یہاں تک کہ میری شرمگاہ کی بھی تلاشی لی۔ خیر وہ ابھی میرے چاروں طرف جمع ہی تھے اور میں اپنی مصیبت میں مبتلا تھی کہ چیل آئی اور ہمارے سروں کے بالکل اوپر اڑنے لگی۔ پھر اس نے وہی ہار نیچے گرا دیا۔ لوگوں نے اسے اٹھا لیا تو میں نے ان سے کہا اسی کے لیے تم لوگ مجھے اتہام لگا رہے تھے حالانکہ میں بےگناہ تھی۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3835</td></tr><tr><td>Arabic No</td><td>3835</td></tr><tr><td>Reference</td><td>Book 63 Hadith 60</td></tr></tbody></table></div>