## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنِي عَبْدُ اللَّهِ بْنُ مُحَمَّدٍ، حَدَّثَنَا أَزْهَرُ السَّمَّانُ، عَنِ ابْنِ عَوْنٍ، عَنْ مُحَمَّدٍ، عَنْ قَيْسِ بْنِ عُبَادٍ، قَالَ كُنْتُ جَالِسًا فِي مَسْجِدِ الْمَدِينَةِ، فَدَخَلَ رَجُلٌ عَلَى وَجْهِهِ أَثَرُ الْخُشُوعِ، فَقَالُوا هَذَا رَجُلٌ مِنْ أَهْلِ الْجَنَّةِ‏.‏ فَصَلَّى رَكْعَتَيْنِ تَجَوَّزَ فِيهِمَا ثُمَّ خَرَجَ، وَتَبِعْتُهُ فَقُلْتُ إِنَّكَ حِينَ دَخَلْتَ الْمَسْجِدَ قَالُوا هَذَا رَجُلٌ مِنْ أَهْلِ الْجَنَّةِ‏.‏ قَالَ وَاللَّهِ مَا يَنْبَغِي لأَحَدٍ أَنْ يَقُولَ مَا لاَ يَعْلَمُ وَسَأُحَدِّثُكَ لِمَ ذَاكَ رَأَيْتُ رُؤْيَا عَلَى عَهْدِ النَّبِيِّ صلى الله عليه وسلم فَقَصَصْتُهَا عَلَيْهِ، وَرَأَيْتُ كَأَنِّي فِي رَوْضَةٍ ـ ذَكَرَ مِنْ سَعَتِهَا وَخُضْرَتِهَا ـ وَسْطَهَا عَمُودٌ مِنْ حَدِيدٍ، أَسْفَلُهُ فِي الأَرْضِ وَأَعْلاَهُ فِي السَّمَاءِ، فِي أَعْلاَهُ عُرْوَةٌ فَقِيلَ لَهُ ارْقَهْ‏.‏ قُلْتُ لاَ أَسْتَطِيعُ‏.‏ فَأَتَانِي مِنْصَفٌ فَرَفَعَ ثِيَابِي مِنْ خَلْفِي، فَرَقِيتُ حَتَّى كُنْتُ فِي أَعْلاَهَا، فَأَخَذْتُ بِالْعُرْوَةِ، فَقِيلَ لَهُ اسْتَمْسِكْ‏.‏ فَاسْتَيْقَظْتُ وَإِنَّهَا لَفِي يَدِي، فَقَصَصْتُهَا عَلَى النَّبِيِّ صلى الله عليه وسلم قَالَ ‏ "‏ تِلْكَ الرَّوْضَةُ الإِسْلاَمُ، وَذَلِكَ الْعَمُودُ عَمُودُ الإِسْلاَمِ، وَتِلْكَ الْعُرْوَةُ عُرْوَةُ الْوُثْقَى، فَأَنْتَ عَلَى الإِسْلاَمِ حَتَّى تَمُوتَ ‏"‏‏.‏ وَذَاكَ الرَّجُلُ عَبْدُ اللَّهِ بْنُ سَلاَمٍ‏.‏ وَقَالَ لِي خَلِيفَةُ حَدَّثَنَا مُعَاذٌ، حَدَّثَنَا ابْنُ عَوْنٍ، عَنْ مُحَمَّدٍ، حَدَّثَنَا قَيْسُ بْنُ عُبَادٍ، عَنِ ابْنِ سَلاَمٍ، قَالَ وَصِيفٌ مَكَانَ مِنْصَفٌ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3813</td></tr><tr><td>Arabic No</td><td>3813</td></tr><tr><td>Reference</td><td>Book 63 Hadith 38</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
কায়স ইবনু ‘উবাদ (রহ.) হতে বর্ণিত, তিনি বলেন, আমি মদিনার মসজিদে উপবিষ্ট ছিলাম। তখন এমন এক ব্যক্তি মসজিদে প্রবেশ করলেন যার চেহারায় বিনয় ও নম্রতার ছাপ ছিল। লোকজন বলতে লাগলেন, এই ব্যক্তি জান্নাতীগণের একজন। তিনি হালকাভাবে দু’রাকআত সালাত আদায় করে মাসজিদ হতে বেরিয়ে এলেন। আমি তাঁকে অনুসরণ করলাম এবং তাঁকে বললাম, আপনি যখন মসজিদে প্রবেশ করছিলেন তখন লোকজন বলাবলি করছিল যে, ইনি জান্নাতবাসীগণের একজন। তিনি বললেন, আল্লাহর কসম কারো জন্য এমন কথা বলা উচিত নয়, যা সে জানে না। আমি তোমাকে আসল কথা বলছি কেন তা বলা হয়। আমি নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর যামানায় একটি স্বপ্ন দেখে তাঁর নিকট বর্ণনা করলাম। আমি দেখলাম যে, আমি যেন একটি বাগানে অবস্থান করছি; বাগানটি বেশ প্রশস্ত, সবুজ। বাগানের মধ্যে একটি লোহার স্তম্ভ যার নিম্নভাগ মাটিতে এবং উপরিভাগ আকাশ স্পর্শ করেছে; স্তম্ভের উপরে একটি শক্ত কড়া সংযুক্ত রয়েছে। আমাকে বলা হল, উপরে উঠ। আমি বললাম, এটাতো আমার সামর্থ্যের বাইরে। তখন একজন খাদিম এসে পিছন দিক হতে আমার কাপড় সহ চেপে ধরে আমাকে উঠতে সাহায্য করলেন। আমি উঠতে লাগলাম এবং উপরে গিয়ে আংটাটি ধরলাম। তখন আমাকে বলা হল, শক্তভাবে আংটাটি ধর। তারপর কড়াটি আমার হাতের মুঠায় ধরা অবস্থায় আমি জেগে গেলাম। নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম-এর নিকট স্বপ্নটি বললে, তিনি বললেন, এ বাগান হল ইসলাম, আর স্তম্ভটি হল ইসলামের খুঁটিসমূহ কড়াটি হল ‘‘উরুয়াতুল উস্কা’’ (শক্ত ও অটুট কড়া) এবং তুুমি আজীবন ইসলামের উপর কায়েম থাকবে। (রাবী বলেন) এই ব্যক্তি হলেন, ‘আবদুল্লাহ ইবনু সালাম (রাঃ)। খালীফাহ (রহ.) مِنْصَفٌ এর স্থলে وَصِيْفٌ বলেছেন। (৭০১০, ৭০১৪, মুসলিম ৪৪/৩৩, হাঃ নং ২৪৮৪) (আধুনিক প্রকাশনীঃ ৩৫৩১, ইসলামিক ফাউন্ডেশনঃ ৩৫৩৮)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3813</td></tr><tr><td>Arabic No</td><td>3813</td></tr><tr><td>Reference</td><td>Book 63 Hadith 38</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated Qais bin Ubad:While I was sitting in the Mosque of Medina, there entered a man (Abdullah bin Salam) with signs of solemnity over his face. The people said, "He is one of the people of Paradise." He prayed two light rak'at and then left. I followed him and said, "When you entered the Mosque, the people said, 'He is one of the people of Paradise.' " He said, "By Allah, one ought not say what he does not know; and I will tell you why. In the lifetime of the Prophet (ﷺ) I had a dream which I narrated to him. I saw as if I were in a garden." He then described its extension and greenery. He added: In its center there was an iron pillar whose lower end was fixed in the earth and the upper end was in the sky, and at its upper end there was a (ring-shaped) hand-hold. I was told to climb it. I said, "I can't." "Then a servant came to me and lifted my clothes from behind and I climbed till I reached the top (of the pillar). Then I got hold of the hand-hold, and I was told to hold it tightly, then I woke up and (the effect of) the handhold was in my hand. I narrated al I that to the Prophet (ﷺ) who said, 'The garden is Islam, and the handhold is the Most Truth-worthy Hand-Hold. So you will remain as a Muslim till you die." The narrator added: "The man was 'Abdullah bin Salam
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3813</td></tr><tr><td>Arabic No</td><td>3813</td></tr><tr><td>Reference</td><td>Book 63 Hadith 38</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah bercerita kepadaku ['Abdullah bin Muhammad] telah bercerita kepada kami [Azhar as-Samman] dari [Ibnu 'Aun] dari [Muhammad] dari [Qais bin 'Abbad] berkata; Aku pernah duduk di masjid Madinah lalu datang seorang laki-laki yang nampak pada wajahnya tanda-tanda kekhusyu'an. Orang-orang berkata; "Inilah seseorang diantara calon penghuni surga". Orang itu kemudian mengerjakan shalat dua raka'at dengan menyempurnakannya lalu keluar masjid. Aku mengikutinya lalu aku berkata; " ketika anda masuk masjid tadi orang-orang mengatakan bahwa anda termasuk calon penghumi surga". Orang itu berkata; "Demi Allah, sungguh tidak patut buat seorangpun mengatakan hal yang dia tidak mengetahuinya. Aku akan ceritakan kepadamu apa alasannya. Sungguh aku pernah bermimpi pada zaman Nabi shallallahu 'alaihi wasallam lalu aku ceritakan mimpiku kepada beliau. Dalam mimpiku itu seolah aku melihat taman yang luas, suasananya yang hijau nan asri, di tengahnya ada tiang-tiang dari besi. Bagian bawahnya adalah bumi sedang atasnya adalah langit. Pada bagian atasnya itu ada tali. Dikatakan kepadaku; "Mendakilah". Aku katakan; "Aku tak sanggup". Kemudian datang kepadaku orang yang membantuku, lalu dia mengangkat bajuku dari belakangku sehingga aku mampu mendakinya hingga ketika sudah berada di atas aku pegang tali tersebut. Dikatakan kepadaku; "Berpeganglah". Maka aku sanggup memegangnya dan sungguh tali itu berada pada genggamanku". Kemudian aku ceritakan mimpiku itu kepada Nabi shallallahu 'alaihi wasallam maka beliau berkata; "Yang dimaksud dengan taman itu adalah Islam sedangkan tiang-tang adalah tiangnya Islam dan tali itu adalah al-'urwatul wutsqa (kalimat tauhid). Dan kamu berada dalam Islam hingga meninggal dunia". Orang itu adalah ['Abdullah bin Salam]. Dan berkata kepadaku [Khalifah] telah bercerita kepada kami [Mu'adz] telah bercerita kepada kami [Ibnu 'Aun] dari [Muhammad] telah bercerita kepada kami [Qais bin 'Abbad] dari [Ibnu Salam] berkata; Kata Shiifu sebagai kata ganti dari minshaf
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3813</td></tr><tr><td>Arabic No</td><td>3813</td></tr><tr><td>Reference</td><td>Book 63 Hadith 38</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
கைஸ் பின் உபாத் (ரஹ்) அவர்கள் கூறியதாவது: நான் மதீனாவின் (மஸ்ஜிதுந் நபவீ) பள்ளிவாசலில் (நபித்தோழர்கள் சிலருடன்) அமர்ந்திருந்தேன். அப்போது ஒரு மனிதர் தமது முகத்தில் சிரம்பணிந்(து சஜ்தா செய்)ததற்கான அடையாளத்துடன் உள்ளே வந்தார். மக்கள், “இவர் சொர்க்கவாசிகளில் ஒருவர்” என்று சொன்னார்கள். அவர் இரு ரக்அத்கள் தொழுதார்; அவற்றை (அதிக நேரம் எடுக்காமல்) சுருக்கமாகத் தொழுதார். பிறகு அவர் வெளியேற, நான் அவரைப் பின்தொடர்ந்து சென்று, “நீங்கள் பள்ளிவாசலுக்குள் நுழைந்தபோது மக்கள், “இவர் சொர்க்கவாசி' என்று கூறினர்” என்றேன். அதற்கு அவர் சொன்னார்: அல்லாஹ்வின் மீதாணையாக! தமக்குத் தெரியாததைக் கூறுவது எவருக்கும் முறையல்ல. ஏன் அவ்வாறு (மக்கள் பேசிக் கொள்கிறார்கள்) என்று உங்களுக்கு இதோ தெரிவிக்கிறேன்: அதாவது நான் நபி (ஸல்) அவர்களின் காலத்தில் கனவொன்று கண்டேன். அதை அவர்களிடம் விவரித்தேன். நான் ஒரு பூங்காவில் இருப்பதைப் போன்று கண்டேன்- அறிவிப்பாளர் கூறுகிறார்: அம்மனிதர் அதன் விசாலத்தையும் பசுமையையும் வர்ணித்தார் -அதன் நடுவே இரும்பாலான தூண் இருந்தது. அதன் அடிப்பகுதி பூமியில் இருந்தது. மேற்பகுதி வானத்தில் இருந்தது. அதன் மேற்பகுதியில் பிடி ஒன்று இருந்தது. என்னிடம், “இதில் ஏறு” என்று சொல்லப்பட்டது. நான், “என்னால் இயலாதே” என்று சொன்னேன். அப்போது என்னிடம் பணியாள் ஒருவர் வந்து என் ஆடையைப் பின்னாலிருந்து தூக்கிவிட்டார். உடனே நான் (அதில்) ஏறினேன். இறுதியில் அதன் மேற்பகுதிக்கு நான் சென்றுவிட்ட போது அந்தப் பிடியை நான் பற்றினேன். உடனே என்னிடம், “நன்கு பற்றிப் பிடித்துக்கொள்” என்று சொல்லப்பட்டது. (நான் அதைப் பற்றினேன்.) அந்தப் பிடி என் கையில் இருக்க (திடுக்கிட்டு) நான் விழித் தெழுந்தேன். நபி (ஸல்) அவர்களிடம் அதை நான் விவரித்தபோது, “அந்தப் பூங்கா இஸ்லாமாகும். அந்தத் தூண் இஸ்லாம் எனும் தூணாகும். அந்தப் பிடி பலமான (இறைநம்பிக்கை என்னும்) பிடியாகும். ஆகவே, நீங்கள் இறக்கும்வரை இஸ்லாத்திலேயே நிலைத்து நிற்பீர்கள்” என்று நபியவர்கள் பதிலளித்தார்கள். (இப்படிச் சொன்ன) அந்த மனிதர் அப்துல்லாஹ் பின் சலாம் (ரலி) அவர்கள்தான். இந்த ஹதீஸ் மற்றோர் அறிவிப்பாளர்தொடரிலும் வந்துள்ளது. அதில் “பணியாள்' என்பதற்குப் பதிலாக “சிறிய பணியாள்' எனும் சொல் இடம்பெற்றுள்ளது. அத்தியாயம் : 63
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3813</td></tr><tr><td>Arabic No</td><td>3813</td></tr><tr><td>Reference</td><td>Book 63 Hadith 38</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Kays b. Ubad dedi ki: "Medine mescidinde oturuyarken yüzünde huşu'un izleri görülen bir adam mescide girdi. Bu, cennet ehlinden bir adamdır, dediler. Hafifçe iki rekat namaz kıldı, sonra çıktı. Ben de arkasından giderek dedim ki: Sen mescide girdiğinde bu cennet ehlinden bir adamdır dediler. Şu cevabı verdi: Allah'a yemin ederim kimsenin bilmediği bir şeyi söylememesi gerekir. Ben sana bunun sebebini anlatayım. Nebi Sallallahu Aleyhi ve Sellem döneminde bir rüya gördüm. Ben de o rüyamı ona anlattım. Kendimi bir bahçedeymişim gibi gördüm. -Bahçenin genişliğini, yeşilliğini de zikretti- ortasında alt tarafı yerde, üst tarafı semada olan demirden bir direk vardı. Üst tarafında da bir kulp vardı. Bana, ona çık denildi. Ben, buna gücüm yetmez dedim. Daha sonra yanıma bir hizmetçi geldi, arkamdan elbiselerimi kaldırdı. Ben de o direğe yükseldim ve nihayet onun en üst tarafına kadar çıktım. O kulpu yakaladım. Bana, iyice tutun denildi. Uyandığımda hala o kulp elimde idi. Rüyamı Nebi Sallallahu Aleyhi ve Sellemle anlatınca şöyle buyurdu: O gördüğün bahçe İslamdır, direk İslamın direğidir, o kuIp ise sapasağlam olan kulptur, sen ölene kadar İslam üzere kalacaksın." İşte sözü geçen o adam Abdullah b. Selam'dır. Kays b. Ubad'dan, o İbn Selam'dan: (Hizmetçi demek olan) "Minsafi yerine "vasıf' lafzını kullanmıştır. Bu Hadis 7010 ve 7014 numara ile gelecektir
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3813</td></tr><tr><td>Arabic No</td><td>3813</td></tr><tr><td>Reference</td><td>Book 63 Hadith 38</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ہم سے عبداللہ بن محمد نے بیان کیا، کہا ہم سے ازہر سمان نے بیان کیا، ان سے ابوعوانہ نے، ان سے محمد نے اور ان سے قیس بن عباد نے بیان کیا کہ میں مسجد نبوی میں بیٹھا ہوا تھا کہ ایک بزرگ مسجد میں داخل ہوئے جن کے چہرے پر خشوع و خضوع کے آثار ظاہر تھے لوگوں نے کہا کہ یہ بزرگ جنتی لوگوں میں سے ہیں، پھر انہوں نے دو رکعت نماز مختصر طریقہ پر پڑھی اور باہر نکل گئے میں بھی ان کے پیچھے ہو لیا اور عرض کیا کہ جب آپ مسجد میں داخل ہوئے تھے تو لوگوں نے کہا کہ یہ بزرگ جنت والوں میں سے ہیں، اس پر انہوں نے کہا: اللہ کی قسم! کسی کے لیے ایسی بات زبان سے نکالنا مناسب نہیں ہے جسے وہ نہ جانتا ہو اور میں تمہیں بتاؤں گا کہ ایسا کیوں ہے۔ نبی کریم صلی اللہ علیہ وسلم کے زمانے میں، میں نے ایک خواب دیکھا اور نبی کریم صلی اللہ علیہ وسلم سے اسے بیان کیا میں نے خواب یہ دیکھا تھا کہ جیسے میں ایک باغ میں ہوں، پھر انہوں نے اس کی وسعت اور اس کے سبزہ زاروں کا ذکر کیا اس باغ کے درمیان میں ایک لوہے کا ستون ہے جس کا نچلا حصہ زمین میں ہے اور اوپر کا آسمان پر اور اس کی چوٹی پر ایک گھنا درخت ہے «العروة» مجھ سے کہا گیا کہ اس پر چڑھ جاؤ میں نے کہا کہ مجھ میں تو اتنی طاقت نہیں ہے اتنے میں ایک خادم آیا اور پیچھے سے میرے کپڑے اس نے اٹھائے تو میں چڑھ گیا اور جب میں اس کی چوٹی پر پہنچ گیا تو میں نے اس گھنے درخت کو پکڑ لیا مجھ سے کہا گیا کہ اس درخت کو پوری مضبوطی کے ساتھ پکڑ لے، ابھی میں اسے اپنے ہاتھ سے پکڑے ہوئے تھا کہ میری آنکھ کھل گئی۔ یہ خواب جب میں نے نبی کریم صلی اللہ علیہ وسلم سے بیان کیا تو آپ صلی اللہ علیہ وسلم نے فرمایا کہ جو باغ تم نے دیکھا ہے، وہ تو اسلام ہے اور اس میں ستون اسلام کا ستون ہے اور «العروة» ( گھنا درخت ) «عروة الوثقى» ہے اس لیے تم اسلام پر مرتے دم تک قائم رہو گے۔ یہ بزرگ عبداللہ بن سلام تھے اور مجھ سے خلیفہ نے بیان کیا ان سے معاذ نے بیان کیا ان سے ابن عون نے بیان کیا ان سے محمد نے ان سے قیس بن عباد نے بیان کیا عبداللہ بن سلام رضی اللہ عنہ سے انہوں نے «منصف‏.» ( خادم ) کے بجائے «وصيف» کا لفظ ذکر کیا۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>3813</td></tr><tr><td>Arabic No</td><td>3813</td></tr><tr><td>Reference</td><td>Book 63 Hadith 38</td></tr></tbody></table></div>