## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا مُوسَى بْنُ إِسْمَاعِيلَ، حَدَّثَنَا أَبُو عَوَانَةَ، عَنْ أَبِي بِشْرٍ، عَنْ سَعِيدِ بْنِ جُبَيْرٍ، عَنِ ابْنِ عَبَّاسٍ، قَالَ كَانَ عُمَرُ يُدْخِلُنِي مَعَ أَشْيَاخِ بَدْرٍ، فَكَأَنَّ بَعْضَهُمْ وَجَدَ فِي نَفْسِهِ فَقَالَ لِمَ تُدْخِلُ هَذَا مَعَنَا وَلَنَا أَبْنَاءٌ مِثْلُهُ فَقَالَ عُمَرُ إِنَّهُ مِنْ حَيْثُ عَلِمْتُمْ‏.‏ فَدَعَا ذَاتَ يَوْمٍ ـ فَأَدْخَلَهُ مَعَهُمْ ـ فَمَا رُئِيتُ أَنَّهُ دَعَانِي يَوْمَئِذٍ إِلاَّ لِيُرِيَهُمْ‏.‏ قَالَ مَا تَقُولُونَ فِي قَوْلِ اللَّهِ تَعَالَى ‏(‏إِذَا جَاءَ نَصْرُ اللَّهِ وَالْفَتْحُ‏)‏ فَقَالَ بَعْضُهُمْ أُمِرْنَا نَحْمَدُ اللَّهَ وَنَسْتَغْفِرُهُ، إِذَا نُصِرْنَا وَفُتِحَ عَلَيْنَا‏.‏ وَسَكَتَ بَعْضُهُمْ فَلَمْ يَقُلْ شَيْئًا فَقَالَ لِي أَكَذَاكَ تَقُولُ يَا ابْنَ عَبَّاسٍ فَقُلْتُ لاَ‏.‏ قَالَ فَمَا تَقُولُ قُلْتُ هُوَ أَجَلُ رَسُولِ اللَّهِ صلى الله عليه وسلم أَعْلَمَهُ لَهُ، قَالَ ‏(‏إِذَا جَاءَ نَصْرُ اللَّهِ وَالْفَتْحُ‏)‏ وَذَلِكَ عَلاَمَةُ أَجَلِكَ ‏(‏فَسَبِّحْ بِحَمْدِ رَبِّكَ وَاسْتَغْفِرْهُ إِنَّهُ كَانَ تَوَّابًا‏)‏‏.‏ فَقَالَ عُمَرُ مَا أَعْلَمُ مِنْهَا إِلاَّ مَا تَقُولُ‏.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4970</td></tr><tr><td>Arabic No</td><td>4970</td></tr><tr><td>Reference</td><td>Book 65 Hadith 492</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
বান্দাদের তওবা কবূলকারী। ঐ ব্যক্তিকে বলা হয় যে গুনাহ থেকে তওবা করে। ৪৯৭০. ইবনু ‘আব্বাস (রাঃ) হতে বর্ণিত। তিনি বলেন, ‘উমার (রাঃ) বদর যুদ্ধে যোগদানকারী প্রবীণ সাহাবীদের সঙ্গে আমাকেও শামিল করতেন। এ কারণে কারো কারো মনে প্রশ্ন দেখা দিল। একজন বললেন, আপনি তাকে আমাদের সঙ্গে কেন শামিল করছেন। আমাদের তো তার মত সন্তানই রয়েছে। ‘উমার (রাঃ) বললেন, এর কারণ তো আপনারাও অবগত আছেন। সুতরাং একদিন তিনি তাঁকে ডাকলেন এবং তাঁদের সঙ্গে বসালেন। ইবনু ‘আব্বাস (রাঃ) বলেন, আমি বুঝতে পারলাম, আজকে তিনি আমাকে ডেকেছেন এজন্য যে, তিনি আমার প্রজ্ঞা তাঁদেরকে দেখাবেন। তিনি তাদেরকে বললেনঃ- আল্লাহর বাণীঃ এর ব্যাখ্যা সম্পর্কে আপনারা কী বলেন, তখন তাঁদের কেউ বললেন, আমরা সাহায্য প্রাপ্ত হলে এবং আমরা বিজয় লাভ করলে এ আয়াতে আমাদেরকে আল্লাহর প্রশংসা এবং তার কাছে ক্ষমা প্রার্থনা করার জন্য আদেশ করা হয়েছে। আবার কেউ কিছু না বলে চুপ করে থাকলেন। এরপর তিনি আমাকে বললেন, হে ইবনু ‘আব্বাস! তুমিও কি তাই বল? আমি বললাম, না। তিনি বললেন, তাহলে তুমি কী চলতে চাও? উত্তরে আমি বললাম, এ আয়াতে আল্লাহ্ রাববুল আলামীন রাসূল সাল্লাল্লাহু ‘আলাইহি ওয়াসাল্লাম-কে তাঁর ইন্তিকালের সংবাদ জানিয়েছেন। আল্লাহ্ তা‘আলা বলেছেন, ‘আল্লাহর সাহায্য ও বিজয় আসলে’ এটিই হবে তোমার মৃত্যুর নিদর্শন।‘‘তখন তুমি তোমার প্রতিপালকের প্রশংসাসহ তাঁর পবিত্রতা ও মহিমা ঘোষণা কর এবং তাঁর কাছে ক্ষমা প্রার্থনা কর। তিনি তো তওবা কবূলকারী।’’ এ কথা শুনে ‘উমার (রাঃ) বললেন, তুমি যা বলছ, এ আয়াতের ব্যাখ্যা আমিও তা-ই জানি। [৩৬২৭] (আধুনিক প্রকাশনীঃ ৪৬০১, ইসলামিক ফাউন্ডেশনঃ ৪৬০৬)
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4970</td></tr><tr><td>Arabic No</td><td>4970</td></tr><tr><td>Reference</td><td>Book 65 Hadith 492</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated Ibn 'Abbas:'Umar used to make me sit with the elderly men who had fought in the Battle of Badr. Some of them felt it (did not like that) and said to 'Umar "Why do you bring in this boy to sit with us while we have sons like him?" 'Umar replied, "Because of what you know of his position (i.e. his religious knowledge.)" One day 'Umar called me and made me sit in the gathering of those people; and I think that he called me just to show them. (my religious knowledge). 'Umar then asked them (in my presence). "What do you say about the interpretation of the Statement of Allah: 'When comes Help of Allah (to you O, Muhammad against your enemies) and the conquest (of Mecca).' (110.1) Some of them said, "We are ordered to praise Allah and ask for His forgiveness when Allah's Help and the conquest (of Mecca) comes to us." Some others kept quiet and did not say anything. On that, 'Umar asked me, "Do you say the same, O Ibn 'Abbas?" I replied, "No." He said, 'What do you say then?" I replied, "That is the sign of the death of Allah's Messenger (ﷺ) which Allah informed him of. Allah said:-- '(O Muhammad) When comes the Help of Allah (to you against your enemies) and the conquest (of Mecca) (which is the sign of your death). You should celebrate the praises of your Lord and ask for His Forgiveness, and He is the One Who accepts the repentance and forgives.' (110.3) On that 'Umar said, "I do not know anything about it other than what you have said
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4970</td></tr><tr><td>Arabic No</td><td>4970</td></tr><tr><td>Reference</td><td>Book 65 Hadith 492</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Musa bin Isma'il] Telah menceritakan kepada kami [Abu 'Awanah] dari [Abu Bisyr] dari [Sa'id bin Jubair] dari [Ibnu Abbas] ia berkata; Suatu ketika Umar mengajakku masuk berkumpul bersama para syaikh pemuka-pemuka Badar, dan sepertinya, sebagian dari mereka memendam sesuatu pada dirinya. Maka salah seorang dari mereka pun bertanya, "Kenapa Anda mengikutsertakan anak ini bersama kami, padahal kami juga memiliki anak-anak yang sebaya dengannya?" Maka Umar pun berkata, "Sesungguhnya anak itu mempunyai kecerdasan tersendiri seperti yang telah kalian kenal." Kemudian pada suatu hari, Umar memangilnya dan mengingutsertakannya bersama mereka. Ibnu Abbas berkata; Aku tahu, bahwa tidak ada maksud lain Umar memanggilku, kecuali untuk memperlihatkan aku pada mereka. Umar berkata, "Bagaimanakah pendapat kalian berkenaan dengan ayat ini: 'IDZAA JAA'A NASHRULLAHI WAL FATH.'" Maka sebagian dari mereka berkata, "Kita diperintahkan untuk memuji Allah dan meminta maghfirah-Nya, yakni ketika kita diberi pertolongan dan kekuatan untuk menaklukkan suatu negeri." Lalu sebagian yang lain diam tak berkata sepatah kata pun. Setelah itu, Umar bertanya padaku, "Apakah seperti itu juga pendapatmu wahai Ibnu Abbas?" Aku menjawab, "Tidak." Umar bertanya lagi, "Lalu bagaimanakah pendapatmu?" Aku menjawab, "Hal itu terkait dengan ajal Rasulullah shallallahu 'alaihi wasallam, Allah telah memberitahukan padanya. Firman Allah: 'IDZAA JAA'A NASHRULLAHI WAL FATH.' Itu adalah alamat akan ajalmu. 'FASABBIH BIHAMDI RABBIKA WAS TAGHFIRHU INNAHU KAANA TAWWAABAA (Karena itu, sucikanlah Rabbu dengan memuji-Nya. Dan mintalah ampunan dari-Nya, sesungguhnya Dia Maha Menerima taubat).'" Umar berkata, "Tidak ada jawaban yang lebih tepat, kecuali apa yang telah kamu katakan
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4970</td></tr><tr><td>Arabic No</td><td>4970</td></tr><tr><td>Reference</td><td>Book 65 Hadith 492</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
இப்னு அப்பாஸ் (ரலி) அவர்கள் கூறியதாவது: உமர் (ரலி) அவர்கள் பத்ர் போரில் கலந்துகொண்ட புண்ணியவான்களுடன் எனக்கும் (தம் அவையில்) இடமளித்து வந்தார்கள். ஆகவே, அவர்களில் சிலர் வருத்தமடைந்து, ‘‘எங்களுக்கு இவரைப் போன்ற (வயதில்) பிள்ளைகள் இருக்க, இவரை எங்களுடன் ஏன் அமரச் செய்கிறீர்கள்?” என்று கேட்டார்கள். அதற்கு உமர் (ரலி) அவர்கள், ‘‘அவர் நீங்கள் அறிந்துள்ள வகையில் (அருமை பெருமைகள் உடையவராக) இருக்கிறார் என்பதால்தான்” என்றார்கள். பின்னர் ஒருநாள் (எங்களை) உமர் (ரலி) அவர்கள் (தமது அவைக்கு) அழைத்தார்கள். அப்போதும் என்னை அவர்களுடன் அமரச் செய்தார்கள். அவர்களுக்கு (என் தகுதியை உணர்த்திக்) காட்டுவதற்காகவே அன்று என்னை அழைத்தார்கள் என்றே கருதினேன். (எனவே, அனைவரும் வந்ததும் அவர்களிடம்) உமர் (ரலி) அவர்கள், ‘‘அல்லாஹ்வின் உதவியும் வெற்றியும் வந்துவிட்டால்...” எனும் (110:1ஆவது) இறைவசனம் குறித்து நீங்கள் என்ன (விளக்கம்) கூறுகிறீர்கள்? என்று கேட்டார்கள். அதற்கு அவர்களில் சிலர், ‘‘நமக்கு உதவியும் வெற்றியும் அளிக்கப்படும்போது அல்லாஹ்வைப் புகழும்படியும் அவனிடம் பாவமன்னிப்புக் கோரும்படியும் நாம் பணிக்கப்பட்டுள்ளோம்” என்று (அவ்வசனத்திற்கு விளக்கம்) கூறினர். அவர்களில் இன்னும் சிலர் ஏதும் சொல்லாமல் அமைதியாயிருந்தனர். அப்போது உமர் (ரலி) அவர்கள் என்னிடம், ‘‘இப்னு அப்பாஸே! நீங்களும் இவ்வாறுதான் கூறுகிறீர்களா?” எனக் கேட்டார்கள். நான், ‘இல்லை’ என்றேன். ‘‘அவ்வாறாயின், நீங்கள் என்ன கூறுகின்றீர்கள்?” என்று கேட்டார்கள். நான், ‘‘அது அல்லாஹ்வின் தூதர் (ஸல்) அவர்களுக்கு அவர்களது ஆயுட்காலம் (முடிந்துவிட்டதைக்) குறித்து (முன்)அறிவிப்புச் செய்ததாகும். ‘இறைவனின் உதவியும் வெற்றியும் வந்துவிட்டால்...’ அதாவது இது, உங்களின் ஆயுட்காலம் (முடிந்துவிட்டது) பற்றிய அறிகுறியாகும். எனவே, உங்களுடைய இறைவனைப் புகழ்ந்து, அவனது தூய்மையை எடுத்துரைத்து, அவனிடம் பாவமன்னிப்புக் கோருங்கள். அவன் பாவமன்னிப்பை ஏற்றுக்கொள்பவன் ஆவான் (என்பதே இதன் விளக்கமாகும்)” என்று பதிலளித்தேன். அப்போது உமர் (ரலி) அவர்கள், ‘‘நீங்கள் கூறுகின்ற விளக்கத்தையே இ(ந்த அத்தியாயத்)திலிருந்து நானும் அறிகின்றேன்” என்று சொன்னார்கள்.4 111. ‘அல்லஹப்’ அத்தியாயம்1 (அளவிலா அருளாளன் நிகரிலா அன்புடையோன் அல்லாஹ்வின் திருப்பெயரால்...) (111:1ஆவது வசனத்தின் மூலத்திலுள்ள ‘தப்ப’ எனும் சொல்லின் வேர்ச்சொல்லும், 40:37ஆவது வசனத்தின் மூலத்தில் இடம்பெற்றதுமான) ‘தபாப்’ எனும் சொல்லுக்கு ‘இழப்பு’ என்பது பொருள். (11:101ஆவது வசனத்தின் மூலத்திலுள்ள) ‘தத்பீப்’ எனும் சொல்லுக்கு ‘சீரழிவு’ என்று பொருள். அத்தியாயம் : 65
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4970</td></tr><tr><td>Arabic No</td><td>4970</td></tr><tr><td>Reference</td><td>Book 65 Hadith 492</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
İbn Abbas r.a.'dan şöyle dediği rivayet edilmiştir: Hz. Ömer beni, Bedir Savaşı'na katılan ve yaşlanmış olan insanların meclisine alırdı. İçlerinden biri bundan dolayı rahatsız olmuş olacak ki; "Bunu neden bizim yanımıza getiriyorsun? Bizim onun gibi çocuklarımız var!" demişti. Bunun üzerine Hz. Ömer ise "O, sizin bildiğiniz kimsedir," demişti. Bir gün onu davet edip yine onların meclisine aldı. [Olayın bundan sonraki kısmını İbn Abbas şöyle anlatmıştır:] O gün beni onlara göstermek için çağırdığını anladım. Hz. Ömer onlara; "Allah Teala'nın ..........iza cae nasrullahi ve'l-feth' suresinin anlamını sordu. Bazıları 'T3u surede yardıma mazhar olup fetih bize nasip olunca Allah'a hamd etmemiz ve ondan bağışlanma dilememiz bize emrediidi," dedi. Bazıları ise sustu ve hiçbir şey söylemedi. Sonra Hz. Ömer bana; "Ey İbn Abbas! Sen de mi böyle düşünüyorsun?" diye sordu. Ben de "Hayır," dedim. Hz. Ömer: "Peki sen ne düşünüyorsun?" diye sorunca şöyle cevap verdim: Burada Hz. Nebi'in vefatı anlatılmıştır. Allah Teala bunu Nebiine bildirmiştir. Şöyle ki; "Allah'ın yardım ve zaferi" -ki bu senin vefatının alametidir- "Rabbine hamd ile tesbih et ve O'ndan af dile. Çünkü O tevvabdır, tövbeleri çok kabul eder," buyurmuştur. Hz. Ömer de "Ben de bu surenin anlamını sadece söylediğin gibi biliyorum," demiştir. Fethu'l-Bari Açıklaması: Hz. Ömer, insanları dinlemek için oturduğu zaman adeti gereği geçmişteki derecelerine göre insanların yanına gelmesini sağladı. Bazen de Medıneli olmayanları eksiklerini telafi eden bir meziyetlerinden dolayı onlarla birlikte dinlerdi. Bu rivayette, İbn Abbas'ın fazileti ile Hz. Nebi'in ona te'vlli öğretmesi ve onu dinde fakıh kılması için yaptığı duanın Allah tarafından kabul edildiği açıkça görülmektedir. Nitekim bu, "Kitabu'l-ilm"de geçmişti. Bu örnekte olduğu gibi övünme ve hava atma için değil de Allah'ın kendisine verdiği nimeti göstermek, kendi değerini bilmeyenlere değerini öğretip onların buna göre muamele etmesini sağlamak ve daha başka iyi gayeler için kişi kendisinden bahsedebilir
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4970</td></tr><tr><td>Arabic No</td><td>4970</td></tr><tr><td>Reference</td><td>Book 65 Hadith 492</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ہم سے موسیٰ بن اسماعیل نے بیان کیا، کہا ہم سے ابوعوانہ نے بیان کیا، ان سے ابوبشر نے، ان سے سعید بن جبیر نے اور ان سے ابن عباس رضی اللہ عنہما نے بیان کیا کہ عمر بن خطاب رضی اللہ عنہ مجھے بوڑھے بدری صحابہ کے ساتھ مجلس میں بٹھاتے تھے۔ بعض ( عبدالرحمٰن بن عوف ) کو اس پر اعتراض ہوا، انہوں نے عمر رضی اللہ عنہ سے کہا کہ اسے آپ مجلس میں ہمارے ساتھ بٹھاتے ہیں، اس کے جیسے تو ہمارے بھی بچے ہیں؟ عمر رضی اللہ عنہ نے کہا کہ اس کی وجہ تمہیں معلوم ہے۔ پھر انہوں نے ایک دن ابن عباس رضی اللہ عنہما کو بلایا اور انہیں بوڑھے بدری صحابہ کے ساتھ بٹھایا ( ابن عباس رضی اللہ عنہما نے کہا کہ ) میں سمجھ گیا کہ آپ نے مجھے انہیں دکھانے کے لیے بلایا ہے، پھر ان سے پوچھا اللہ تعالیٰ کے اس ارشاد کے متعلق تمہارا کیا خیال ہے «إذا جاء نصر الله والفتح‏» الخ یعنی ”جب اللہ کی مدد اور فتح آ پہنچی“ بعض لوگوں نے کہا کہ جب ہمیں مدد اور فتح حاصل ہوئی تو اللہ کی حمد اور اس سے استغفار کا ہمیں آیت میں حکم دیا گیا ہے۔ کچھ لوگ خاموش رہے اور کوئی جواب نہیں دیا۔ پھر آپ نے مجھ سے پوچھا: ابن عباس! کیا تمہارا بھی یہی خیال ہے؟ میں نے عرض کیا کہ نہیں۔ پوچھا پھر تمہاری کیا رائے ہے؟ میں نے عرض کی کہ اس میں رسول اللہ صلی اللہ علیہ وسلم کی وفات کی طرف اشارہ ہے۔ اللہ تعالیٰ نے نبی کریم صلی اللہ علیہ وسلم کو یہی چیز بتائی ہے اور فرمایا «إذا جاء نصر الله والفتح‏» کہ ”جب اللہ کی مدد اور فتح آ پہنچی“ یعنی پھر یہ آپ کی وفات کی علامت ہے۔ اس لیے آپ اپنے پروردگار کی پاکی و تعریف بیان کیجئے اور اس سے بخشش مانگا کیجئے۔ بیشک وہ بڑا توبہ قبول کرنے والا ہے۔ عمر رضی اللہ عنہ نے اس پر کہا میں بھی وہی جانتا ہوں جو تم نے کہا۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>4970</td></tr><tr><td>Arabic No</td><td>4970</td></tr><tr><td>Reference</td><td>Book 65 Hadith 492</td></tr></tbody></table></div>