## Arabic


<div dir="rtl" lang="ar" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
حَدَّثَنَا عَبْدُ اللَّهِ بْنُ مُحَمَّدٍ، حَدَّثَنَا عَبْدُ الْمَلِكِ بْنُ عَمْرٍو، حَدَّثَنَا عُمَرُ بْنُ أَبِي زَائِدَةَ، عَنْ أَبِي إِسْحَاقَ، عَنْ عَمْرِو بْنِ مَيْمُونٍ، قَالَ مَنْ قَالَ عَشْرًا كَانَ كَمَنْ أَعْتَقَ رَقَبَةً مِنْ وَلَدِ إِسْمَاعِيلَ‏.‏ قَالَ عُمَرُ بْنُ أَبِي زَائِدَةَ وَحَدَّثَنَا عَبْدُ اللَّهِ بْنُ أَبِي السَّفَرِ عَنِ الشَّعْبِيِّ عَنْ رَبِيعِ بْنِ خُثَيْمٍ مِثْلَهُ‏.‏ فَقُلْتُ لِلرَّبِيعِ مِمَّنْ سَمِعْتَهُ فَقَالَ مِنْ عَمْرِو بْنِ مَيْمُونٍ‏.‏ فَأَتَيْتُ عَمْرَو بْنَ مَيْمُونٍ فَقُلْتُ مِمَّنْ سَمِعْتَهُ فَقَالَ مِنِ ابْنِ أَبِي لَيْلَى‏.‏ فَأَتَيْتُ ابْنَ أَبِي لَيْلَى فَقُلْتُ مِمَّنْ سَمِعْتَهُ فَقَالَ مِنْ أَبِي أَيُّوبَ الأَنْصَارِيِّ يُحَدِّثُهُ عَنِ النَّبِيِّ صلى الله عليه وسلم وَقَالَ إِبْرَاهِيمُ بْنُ يُوسُفَ عَنْ أَبِيهِ عَنْ أَبِي إِسْحَاقَ حَدَّثَنِي عَمْرُو بْنُ مَيْمُونٍ عَنْ عَبْدِ الرَّحْمَنِ بْنِ أَبِي لَيْلَى عَنْ أَبِي أَيُّوبَ قَوْلَهُ عَنِ النَّبِيِّ صلى الله عليه وسلم‏.‏ وَقَالَ مُوسَى حَدَّثَنَا وُهَيْبٌ، عَنْ دَاوُدَ، عَنْ عَامِرٍ، عَنْ عَبْدِ الرَّحْمَنِ بْنِ أَبِي لَيْلَى، عَنْ أَبِي أَيُّوبَ، عَنِ النَّبِيِّ صلى الله عليه وسلم‏.‏ وَقَالَ إِسْمَاعِيلُ عَنِ الشَّعْبِيِّ عَنِ الرَّبِيعِ قَوْلَهُ‏.‏ وَقَالَ آدَمُ حَدَّثَنَا شُعْبَةُ حَدَّثَنَا عَبْدُ الْمَلِكِ بْنُ مَيْسَرَةَ سَمِعْتُ هِلاَلَ بْنَ يَسَافٍ عَنِ الرَّبِيعِ بْنِ خُثَيْمٍ وَعَمْرِو بْنِ مَيْمُونٍ عَنِ ابْنِ مَسْعُودٍ قَوْلَهُ‏.‏ وَقَالَ الأَعْمَشُ وَحُصَيْنٌ عَنْ هِلاَلٍ عَنِ الرَّبِيعِ عَنْ عَبْدِ اللَّهِ قَوْلَهُ‏.‏ وَرَوَاهُ أَبُو مُحَمَّدٍ الْحَضْرَمِيُّ عَنْ أَبِي أَيُّوبَ عَنِ النَّبِيِّ صلى الله عليه وسلم‏ كَانَ كَمَنْ أَعْتَقَ رَقَبَةً مِنْ وَلَدِ إِسْمَاعِيلِ قَالَ أَبُو عَبْد اللَّهِ وَالصَّحِيحُ قَوْلُ عَبْدِ الْمَلِكِ بْنِ عَمْرٍو.‏
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6404</td></tr><tr><td>Arabic No</td><td>6404</td></tr><tr><td>Reference</td><td>Book 80 Hadith 99</td></tr></tbody></table></div>

## Bengali


<div dir="ltr" lang="bn" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
‘আমর ইবনু মাইমূন (রহঃ) হতে বর্ণিত। তিনি বলেন, নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম বলেছেনঃ যে লোক (এ কথাগুলো) দশবার পড়বে সে ঐ লোকের সমান হয়ে যাবে, সে লোক ইসমাঈল (আঃ)-এর বংশ থেকে একটা গোলাম মুক্ত করে দিয়েছে। শাবীও রাবী ইবনু খুসাইম হতে অনুরূপ বর্ণনা করেছেন। তিনি বলেন, ‘আমর ইবনু মায়মূন হতে। আমর ইবনু মায়মূনের নিকট থেকে শুনেছেন? তিনি বলেন, ‘আমর ইবনু মায়মূন হতে। ‘আমর ইবনু মায়মূনের নিকট গিয়ে তাঁকে জিজ্ঞেস করল, আপনি এ হাদীস কার নিকট হতে শুনেছেন? তিনি বললেন, ইবনু আবূ লায়লা হতে। আমি ইবনু আবূ লায়লার নিকট গিয়ে তাকে জিজ্ঞেস করলাম, আপনি এটি কার নিকট হতে শুনেছেন? তিনি বললেন, আমি এটি আবূ আইয়ূব আনসারী (রাঃ)-কে নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম হতে বর্ণনা করতে শুনেছি। (আধুনিক প্রকাশনী- ৫৯৫৬, ইসলামিক ফাউন্ডেশন- ৫৮৪৯) কয়েকটি ভিন্ন ভিন্ন সনদে অনুরূপ হাদীস আবূ আইয়ূব আনসারী (রাঃ) থেকেও বর্ণিত হয়েছে যে, রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম এ হাদীসটি তাঁর নিকটেও বলেছেন। আবূ আইয়ূব আনসারী (রাঃ) রাসূলুল্লাহ সাল্লাল্লাহু আলাইহি ওয়াসাল্লাম হতে বর্ণনা করেন, সে ঐ ব্যক্তির ন্যায় যে ইসমাঈলের বংশধরের কোন গোলামকে আযাদ করলো। আবূ ‘আবদুল্লাহ বুখারী বলেন, ‘আবদুল মালিক বিন ‘আমর এর উক্তিটিই সঠিক।
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6404</td></tr><tr><td>Arabic No</td><td>6404</td></tr><tr><td>Reference</td><td>Book 80 Hadith 99</td></tr></tbody></table></div>

## English


<div dir="ltr" lang="en" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Narrated 'Amr bin Maimun:Whoever recites it (i.e., the invocation in the above Hadith (412) ten times will be as if he manumitted one of Ishmael's descendants. Abu Aiyub narrated the same Hadith from the Prophet (ﷺ) saying, "(Whoever recites it ten times) will be as if he had manumitted one of Ishmael's descendants
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6404</td></tr><tr><td>Arabic No</td><td>6404</td></tr><tr><td>Reference</td><td>Book 80 Hadith 99</td></tr></tbody></table></div>

## Indonesian


<div dir="ltr" lang="id" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Telah menceritakan kepada kami [Abdullah bin Muhammad] telah menceritakan kepada kami [Abdul Malik bin 'Amru] telah menceritakan kepada kami [Umar bin Abu Za'idah] dari [Abu Ishaq] dari ['Amru bin Maimun] dia berkata; "Barangsiapa mengucapkannya (Laa ilaaha illallahu wahdahuu laa syariikalah lahul mulku wa lahul hamdu wa huwa 'alaa kulli syai'in qadir) sebanyak sepuluh kali, maka seolah-olah ia telah membebaskan budak dari keturunan Isma'il." Umar bin Abu Za'idah mengatakan; telah menceritakan kepada kami [Abdullah bin Abu Safar] dari [Asy Sya'bi] dari [Rabi' bin Khutsaim] seperti hadits tersebut. Lalu aku berkata kepada Rabi' 'Dari manakah kamu mendengar hadits tersebut? ' Dia menjawab; 'Dari [Amru bin Maimun], lalu aku mendatangi 'Amru bin Maimun, lalu aku bertanya; 'Dari manakah kamu mendengar hadits tersebut? ' Dia menjawab; 'Dari [Ibnu Abu Laila], lalu aku pun mendatangi Ibnu Abu Laila dan bertanya; 'Dari manakah kamu mendengar hadits tersebut? ' Dia menjawab; 'Dari [Abu Ayyub Al Anshari] dia pernah bercerita dari Nabi shallallahu 'alaihi wasallam.' [Ibrahim bin Yusuf] juga pernah berkata; dari [Ayahnya] dari [Abu Ishaq] telah menceritakan kepadaku ['Amru bin Maimun] dari [Abdurrahman bin Abu Laila] dari [Abu Ayyub] perkataannya dari Nabi shallallahu 'alaihi wasallam. [Musa] mengatakan; telah menceritakan kepada kami [Wuhaib] dari [Daud] dari ['Amir] dari [Abdurrahman bin Abu Laila] dari [Abu Ayyub] dari Nabi shallallahu 'alaihi wasallam. [Isma'il] mengatakan dari [Asy Sya'bi] dari [Ar Rabi'] pada perkataannya. [Adam] mengatakan; telah menceritakan kepada kami [Syu'bah] telah menceritakan kepada kami [Abdul Malik bin Maisarah] saya mendengar [Hilal bin Yasaf] dari [Ar Rabi' bin Khutsaim], dan ['Amru bin Maimun] dari [Ibnu Mas'ud] pada perkataannya. [Al A'masy] dan [Hushain] juga mengatakan; dari [Hilal] dari [Ar Rabi'] dari [Abdullah] pada perkataannya. Dan diriwayatkan pula oleh [Abu Muhammad Al Hadlrami] dari [Abu Ayyub] dari Nabi shallallahu 'alaihi wasallam: 'Seperti orang yang membebaskan budak dari keturunan Isma'il.' Abu Abdullah mengatakan; 'Yang benar adalah yang dikatakan oleh Abdul Malik bin 'Amru
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6404</td></tr><tr><td>Arabic No</td><td>6404</td></tr><tr><td>Reference</td><td>Book 80 Hadith 99</td></tr></tbody></table></div>

## Tamil


<div dir="ltr" lang="ta" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
அம்ர் பின் மைமூன் (ரஹ்) அவர்கள் கூறியதாவது: யார் (மேற்கண்ட வாக்கியங்களை) பத்துமுறை ஓதுகின்றாரோ அவர், இஸ்மாயீல் (அலை) அவர்களின் சந்ததியினரில் ஒருவரை விடுதலை செய்ததைப் போன்றவராவார் (என நபி (ஸல்) அவர்கள் கூறினார்கள்). (இதன் அறிவிப்பாளர்களில் ஒருவரான) உமர் பின் அபீஸாயிதா (ரஹ்) அவர்கள் கூறுகிறார்கள்: இதே நபிமொழி இன்னோர் அறிவிப்பாளர்தொடர் வழியாகவும் வந்துள்ளது. நான் இதன் அறிவிப்பாளர்களில் ஒருவரான ரபீஉ பின் குஸைம் (ரஹ்) அவர்களிடம், “இதை யாரிடமிருந்து தாங்கள் செவியுற்றீர்கள்?” என்று கேட்டேன். அதற்கு அவர்கள், “அம்ர் பின் மைமூன் (ரஹ்) அவர்களிடமிருந்து (இதைச் செவியுற்றேன்)” என்றார்கள். ஆகவே, நான் அம்ர் பின் மைமூன் (ரஹ்) அவர்களிடம் சென்று, “இதை யாரிடமிருந்து தாங்கள் செவியுற்றீர்கள்.?” என்று கேட்டேன். அதற்கு அவர்கள், “இப்னு அபீலைலா (ரஹ்) அவர்களிடமிருந்து (செவியுற்றேன்)” என்றார்கள். ஆகவே, நான் இப்னு அபீலைலா (ரஹ்) அவர்களிடம் சென்று, “இதை யாரிடமிருந்து தாங்கள் செவியுற்றீர்கள்?” என்று கேட்டேன். அதற்கு அவர்கள், “இதை நபி (ஸல்) அவர்கள் சொன்னதாக அபூஅய்யூப் அல்அன்சாரி (ரலி) அவர் களிடமிருந்து (நான் செவியுற்றேன்)” என்று சொன்னார்கள். இந்த ஹதீஸ் அபூஅய்யூப் அல் அன்சாரி (ரலி) அவர்களிடமிருந்து மொத்தம் ஏழு அறிவிப்பாளர்தொடர்களில் வந்துள்ளது. அவற்றில் ஒன்றில், “இஸ்மாயீல் (அலை) அவர்களின் வழித்தோன்றல்களில் ஓர் அடிமையை விடுதலை செய்தவரைப் போன்றவராவார்” என நபி (ஸல்) அவர்கள் கூறியதாக வந்துள்ளது. இதே ஹதீஸ் அப்துல்லாஹ் பின் மஸ்ஊத் (ரலி) அவர்களிடமிருந்து நான்கு அறிவிப்பாளர்தொடர்களில் வந்துள்ளது. அபூஅப்தில்லாஹ் (புகாரீ) கூறுகிறேன்: (முதலாவது அறிவிப்பாளர்தொடரில் உள்ளபடி) அபூஇஸ்ஹாக் (ரஹ்) அவர் களிடமிருந்து உமர் பின் ஸாயிதா (ரஹ்) அவர்கள் அறிவிப்பதே (மற்ற வர்கள் அபூஇஸ்ஹாக்கிடமிருந்து அறிவிப்பதைவிடச்) சரியானதாகும். இவர் ‘உமர்’ பின் ஸாயிதா என்பதே சரியானதாகும்; ‘அம்ர்’ அல்ல. அத்தியாயம் : 80
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6404</td></tr><tr><td>Arabic No</td><td>6404</td></tr><tr><td>Reference</td><td>Book 80 Hadith 99</td></tr></tbody></table></div>

## Turkish


<div dir="ltr" lang="tr" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
Amr İbn Meymun şöyle demiştir: "Kim bunu on sefer söylerse İsmail A.S'ın nesiinden on esiri azad etmiş gibi sevap kazanır". NOT: Tehlil "la ilahe illallah" demektir
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6404</td></tr><tr><td>Arabic No</td><td>6404</td></tr><tr><td>Reference</td><td>Book 80 Hadith 99</td></tr></tbody></table></div>

## Urdu


<div dir="rtl" lang="ur" style={{fontSize:'larger',backgroundColor:'#f8f9fa',padding:20}}>
ہم سے عبداللہ بن محمد مسندی نے بیان کیا، کہا ہم سے عبدالملک بن عمرو نے، کہا کہ ہم سے عمر بن ابی زائد نے، ان سے ابواسحاق سبیعی نے، ان سے عمرو بن میمون نے بیان کیا کہ جس نے یہ کلمہ دس مرتبہ پڑھ لیا وہ ایسا ہو گا جیسے اس نے ایک عربی غلام آزاد کیا۔ اسی سند سے عمر بن ابی زائدہ نے بیان کیا کہ ہم سے عبداللہ بن ابی السفر نے بیان کیا، ان سے شعبی نے، ان سے ربیع بن خثیم نے یہی مضمون تو میں نے ربیع بن خثیم سے پوچھا کہ تم نے کس سے یہ حدیث سنی ہے؟ انہوں نے کہا کہ عمرو بن میمون اودی سے۔ پھر میں عمرو بن میمون کے پاس آیا اور ان سے دریافت کیا کہ تم نے یہ حدیث کس سے سنی ہے؟ انہوں نے کہا کہ ابن ابی لیلیٰ سے۔ ( پھر میں ) ابن ابی لیلیٰ کے پاس آیا اور پوچھا کہ تم نے یہ حدیث کس سے سنی ہے؟ انہوں نے کہا کہ ابوایوب انصاری رضی اللہ عنہ سے، وہ یہ حدیث نبی کریم صلی اللہ علیہ وسلم سے بیان کرتے تھے اور ابراہیم بن یوسف نے بیان کیا، ان سے ان کے والد یوسف بن اسحاق نے، ان سے ابواسحاق سبیعی نے، انہوں نے کہا کہ مجھ سے عمرو بن میمون اودی نے بیان کیا، ان سے عبدالرحمٰن بن ابی لیلیٰ نے اور ان سے ابوایوب انصاری رضی اللہ عنہ نے نبی کریم صلی اللہ علیہ وسلم سے یہی حدیث نقل کی۔ اور موسیٰ بن اسماعیل نے بیان کیا کہ ہم سے وہیب بن خالد نے بیان کیا، ان سے داؤد بن ابی ہند نے،، ان سے عامر شعبی نے، ان سے عبدالرحمٰن بن ابی لیلیٰ نے اور ان سے ابوایوب رضی اللہ عنہ نے، انہوں نے نبی کریم صلی اللہ علیہ وسلم سے۔ اور اسماعیل بن ابی خالد نے بیان کیا، ان سے شعبی نے، ان سے ربیع نے موقوفاً ان کا قول نقل کیا۔ اور آدم بن ابی ایاس نے بیان کیا، کہا ہم سے شعبہ نے بیان کیا، کہا ہم سے عبدالملک بن میسرہ نے بیان کیا، کہا میں نے ہلال بن یساف سے سنا، ان سے ربیع بن خثیم اور عمرو بن میمون دونوں نے اور ان سے ابن مسعود رضی اللہ عنہ نے۔ اور اعمش اور حصین دونوں نے ہلال سے بیان کیا، ان سے ربیع بن خثیم نے اور ان سے عبداللہ بن مسعود رضی اللہ عنہ نے، یہی حدیث روایت کی۔ اور ابو محمد حضرمی نے ابوایوب رضی اللہ عنہ سے، انہوں نبی کریم صلی اللہ علیہ وسلم سے مرفوعاً اسی حدیث کو روایت کیا۔
</div>
<div style={{backgroundColor:'#f8f9fa',padding:20, marginBottom: 10}}><table> <thead> <tr> <th>References:</th> <th></th> </tr> </thead> <tbody><tr><td>Hadith No</td><td>6404</td></tr><tr><td>Arabic No</td><td>6404</td></tr><tr><td>Reference</td><td>Book 80 Hadith 99</td></tr></tbody></table></div>